apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-restserver
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/fabric-restserver
    git: https://github.com/Mohitv/bevel.git
    ref: main
  releaseName: carrier-restserver
  values:
    metadata:
      namespace: carrier-net
    server:
      name: carrier-restserver
      port: 20001
      localmspid: carrierMSP
      image: ghcr.io/hyperledger/bevel-supplychain-fabric:rest-server-stable
      username: user1
      cert_path: "/secret/tls/user1.cert"
      key_path: "/secret/tls/user1.pem"
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localcarrier-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/carrier-net
      serviceaccountname: vault-auth
      imagesecretname: regcred
      image: ghcr.io/hyperledger/alpine-utils:1.0
    service:
      servicetype: ClusterIP
      ports:
        apiPort: 20001
        targetPort: 8000
    connection:
      peer: peer0.carrier-net
      peerAddress: peer0.carrier-net
      peerPort: 7051
      ordererAddress: orderer1.supplychain-net
      ordererPort: 7050
