apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturer-expressapi
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/expressapp
    git: "https://github.com/Mohitv/bevel.git"
    ref: "main"
  releaseName: manufacturerfabric-expressapi
  values:
    nodeName: manufacturer-expressapi
    metadata:
      namespace: manufacturer-net
    replicaCount: 1
    expressapp:
      serviceType: ClusterIP
      image: ghcr.io/hyperledger/bevel-supplychain-fabric:express-app-stable
      pullPolicy: Always
      pullSecrets: regcred
      nodePorts:
        port: 3000
        targetPort: 3000
        name: tcp
      env:
        apiUrl: http://manufacturer-restserver.manufacturer-net:20001/api/v1
    proxy:
      provider: none
      name: manufacturer
      type: fabric
      external_url_suffix: develop.local.com
      peer_name: peer0
