apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: peer0-carrier-cli
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: peer0-carrier-cli
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/fabric_cli    
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      class: carriersc
      size: 256Mi
    vault:
      role: vault-role
      address: http://192.168.49.1:8200
      authpath: localcarrier-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    peer:
      name: peer0
      localmspid: carrierMSP
      tlsstatus: true
      address: peer0.carrier-net:7051
    orderer:
      address: orderer1.supplychain-net:7050
