apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: solo

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.66.8.13:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIOn7vmEn6Q3S/GXBU2qBmLsKJ/eYj4YHqAOjVBDb2u38ErhMCrVMCrJMCngKWggBEAEaBgjK
      6tWcBiIKc3lzY2hhbm5lbCpAMjhlNzAxYmQ3OWQ2MWU1YzI5ZDU2YjZlOGRjMDNhZDg0NDgwMTYx
      ZTI2ZjhkYjJhOTRhNjk0ZGIzNzY1OWFlORIaEhidgo9QM8Tk+gNJuWgET/WWEWsBWxJxHgkStUsK
      sksSr0sSqRkKB09yZGVyZXISnRkSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVTkNxK0VJa20yS01zRmJMRDF6RVlWRlYwUy9Bd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFeE1EUTBOakl5V2hjTk1qVXdPVE13TURRME5qSXlX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGVDI0
      Zkt5ZjhCc1BzY1FtVXNEL3RGQUgraWlHOURRL016d1hYaVFIUXEwdGpqMEVGdlkKNXR1RC9oQ3N1
      dm4vTTZqb1pTL1JpMkhlTFllbVJ4UU1mUStqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0xIVVBTSkE1ZmJ4MEk5TnlMaXhETjhK
      THJSREFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCZTMzV1IrZUxyeGU3TFljS0U2V2crdjVOK2k3
      OE1aOXFBMlhzMmV6Mi8KeHdJZ1ZsZXRGaXpnZHdxczEzSUJiSWdTMExoc3RSMlprYUxBS0I3eEtX
      Tm5KRlE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9lZ0F3SUJBZ0lVQWdJNTRSNHd5TXYxa0RNcmZJQm5EOFo3T09Zd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFeE1EUTFNakF3V2hjTk1q
      TXhNakV4TURRMU56QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOXplN2ZHcGQ5V0h5V09GektUTnNSMWpCdlp4
      dy9zODMKMTRwUEZSZHFBcVdkRkRvbm4zMzJxNnRiYUlGelRlRUxGdmVvdy9hRitKRXFLTUxZcDFw
      TUVxT0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRQWJnN2ZJY1RGCkZaS0hDc2lhSWdvaXJGckV6VEFmQmdOVkhTTUVHREFXZ0JT
      TEhVUFNKQTVmYngwSTlOeUxpeEROOEpMclJEQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kw
      NFpEYzNORFUyTlRrdGRHNDViV1l3Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBcTAwWDhMd3J2bnVBSTQ5T3BaSEQ2TStldjVOditwYmt6Wkl3cG1weDNad0NJRnRL
      VDZlazZwS3JQbTV2CnpzQlQzYXNMcFEzK1loclI0VEp5U3MrdWpjZUEKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVTkNxK0VJa20yS01zRmJMRDF6RVlWRlYwUy9Bd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFeE1EUTBOakl5V2hjTk1qVXdPVE13
      TURRME5qSXlXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJGVDI0Zkt5ZjhCc1BzY1FtVXNEL3RGQUgraWlHOURRL016d1hYaVFIUXEwdGpqMEVGdlkK
      NXR1RC9oQ3N1dm4vTTZqb1pTL1JpMkhlTFllbVJ4UU1mUStqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0xIVVBTSkE1ZmJ4MEk5
      TnlMaXhETjhKTHJSREFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCZTMzV1IrZUxyeGU3TFljS0U2
      V2crdjVOK2k3OE1aOXFBMlhzMmV6Mi8KeHdJZ1ZsZXRGaXpnZHdxczEzSUJiSWdTMExoc3RSMlpr
      YUxBS0I3eEtXTm5KRlE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiEKDUNvbnNlbnN1c1R5cGUSEBIGCgRzb2xvGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUS
      CwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChND
      aGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRf
      MhIAGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVy
      cxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZB
      ZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5z
      Er0vCgtDb25zb3J0aXVtcxKtLxLiLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsguErYWCgpjYXJy
      aWVyTVNQEqcWGsMUCgNNU1ASuxQSsBQSrRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVFcGpIODFDTEx1SU5SWHFJVmptckN0eGFL
      Yzh3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dG
      UVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1URXdORFE0TXpOYUZ3MHlO
      VEE1TXpBd05EUTRNek5hTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWti
      MjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdB
      MVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkMKQUFTV2xsYmFjbmFuaWs5V2Z0ZURIcTdTUEdnZHdzcGc3ZDVWcUpycjlRUzFGV1BmQ1ZiQ3pR
      enJ5R1BNa3J6bQpPWWt0MGlacVdZU2YrT1A4OWVxMXk5SGRvMEl3UURBUEJnTlZIUk1CQWY4RUJU
      QURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVVdVOEF0aUR0VHFDczVF
      THkxOVhCbzJObEVUc3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU5mU05TTW55UHNNdVA3bk9F
      VE41QmNvVXBBN2RvUW5tdjU2b3Q2M2JSTnBBaUJlWDVPTQpSdUJtUUp3VGdGaDNyUWlvblFYUFF2
      Q3lCenVnZFowSnRFRmlBQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3akNDQXBTZ0F3SUJBZ0lVTHBnZHlBR1dZb0RrSmRNK2ha
      WU1uR05Bcy80d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFX
      VnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXlNVEV3TkRVME1E
      QmFGdzB5TXpFeU1URXdORFU1TURCYU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4
      STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdO
      VgpCQXNUQldGa2JXbHVNQTRHQTFVRUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1
      QVkyRnljbWxsCmNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRteEcr
      amJGUjhKbERVTnJKbldjTGcKak85N05IclpQSWdrSzZWOXNNejBaa3pDSmpTcThrbzRFcWRrMHRi
      OWdZR0NDQWxISlVYdWROWDJjOVBLQjNEZApvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdl
      QU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFCkZJQlVEYjI5RzhoYWE3ZFF2U1JnZGlh
      bWMxUVlNQjhHQTFVZEl3UVlNQmFBRkZsUEFMWWc3VTZnck9SQzh0ZlYKd2FOalpSRTdNQ1FHQTFV
      ZEVRUWRNQnVDR1dOaExYUnZiMnh6TFRkak4yUTBOVFEwT0RndFkzQXlaMll3Z1kwRwpDQ29EQkFV
      R0J3Z0JCSUdBZXlKaGRIUnljeUk2ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRp
      Ck9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5
      YjJ4c2JXVnUKZEVsRUlqb2lRV1J0YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9p
      WVdSdGFXNGlmWDB3Q2dZSQpLb1pJemowRUF3SURTQUF3UlFJaEFMTGlkMTJmZmd6c2NiRk9XMWdu
      VzBrNFd6REVkeUd3QVBRK2pHK2RDdEpNCkFpQWI1Z2RBWTYzbS9WTUx2NGpicGIvMUh3NGx3Z1J5
      STBXNXc4WmpHbGtNTGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEy
      NTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVFcGpI
      ODFDTEx1SU5SWHFJVmptckN0eGFLYzh3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1D
      UjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lE
      VlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkK
      TWpFeU1URXdORFE0TXpOYUZ3MHlOVEE1TXpBd05EUTRNek5hTUZveEN6QUpCZ05WQkFZVEFrZENN
      UTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVD
      Z3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Fo
      a2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTV2xsYmFjbmFuaWs5V2Z0ZURIcTdTUEdnZHdzcGc3
      ZDVWcUpycjlRUzFGV1BmQ1ZiQ3pRenJ5R1BNa3J6bQpPWWt0MGlacVdZU2YrT1A4OWVxMXk5SGRv
      MEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZI
      UTRFRmdRVVdVOEF0aUR0VHFDczVFTHkxOVhCbzJObEVUc3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdS
      UUloQU5mU05TTW55UHNNdVA3bk9FVE41QmNvVXBBN2RvUW5tdjU2b3Q2M2JSTnBBaUJlWDVPTQpS
      dUJtUUp3VGdGaDNyUWlvblFYUFF2Q3lCenVnZFowSnRFRmlBQT09Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmll
      ck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJy
      aWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJN
      U1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoG
      QWRtaW5zKgZBZG1pbnMSsRcKD21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9t
      YW51ZmFjdHVyZXJNU1ASgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktn
      QXdJQkFnSVVIbFZFTkpTeWdkOGlRV2p6YS9zZk9xZnlhaFF3Q2dZSUtvWkl6ajBFQXdJdwpaREVM
      TUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlh
      V05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhi
      blZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qRXhNRFEwTnpJNFdoY05NalV3T1RNd01EUTBO
      ekk0V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURW
      UVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVB
      d3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlB
      d0VIQTBJQUJOMlpRRFEvd2o2UWxSNVZTelFQcG54VVJ3MS9FNkhERGpkVQp3Rm9MOWhYVkVzS0Nw
      MHVGR2JlQVpjNjgxVWhKcGVWVmNmQUNwVUNYQWpSMEFkMFdzdldqUWpCQU1BOEdBMVVkCkV3RUIv
      d1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFNUVXJ4d2NZa1ov
      bmwKRVcxem96eTBPOXhuSERBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTRZbWFEWEI4TDRuQnFV
      eWhuNjhHZjhScApDZFBZT0c5VGdHUXRBYnpCMGljQ0lFTDY2KytMdG9wc25Rd2N1a0htSkgvSDZB
      OG9xUTJNWnU1Q0QvbHBsSUNECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQXJlZ0F3SUJBZ0lVTnArUm9NM1I0ZzMwelNucUNE
      bml1enpQQ1Rvd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJB
      Z01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVpt
      RmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1q
      SXhNakV4TURRMU16QXdXaGNOTWpNeE1qRXhNRFExT0RBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1Ew
      Z3hHakFZQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1
      MQpabUZqZEhWeVpYSXhJekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNS
      MWNtVnlNUjh3CkhRWURWUVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZ
      SEtvWkl6ajBDQVFZSUtvWkkKemowREFRY0RRZ0FFaitTK0JYZlMxR2JzUnpsTytVOHM5QlI0S0hQ
      NDRwSlFtek16a3hpWnhFSEdZMHg1RzVjSwpUM1l5b0VJZmJma3BhLzdiRWJ5YWtmYzc4cWc4Zi9C
      RmhhT0NBU0l3Z2dFZU1BNEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSbGFTNGRsRGZ5T1dleWxrQUlzVS9pYnMvSkpqQWYKQmdOVkhTTUVHREFXZ0JU
      U1RVcnh3Y1lrWi9ubEVXMXpvenkwTzl4bkhEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kw
      MU9XUTROelUwTnpnMkxXZG1jSEJ3TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNp
      CllXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxz
      YVdGMGFXOXUKSWpvaWJXRnVkV1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9p
      UVdSdGFXNUFiV0Z1ZFdaaApZM1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5
      ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFCkFpQmlTMlZkVnRTRGxXM3dxdW5QZzVIZ2YrVlMyRTNE
      VC8xbkQzenA4aFdzWVFJZ0tSTUNuTm5SUzNmWnhxQmQKdDhiS3FETVZVVUhNN1RiU1YvbldaMkxG
      bFMwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVIbFZFTkpTeWdkOGlRV2p6
      YS9zZk9xZnlhaFF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05W
      QkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUx
      Wm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNO
      TWpJeE1qRXhNRFEwTnpJNFdoY05NalV3T1RNd01EUTBOekk0V2pCa01Rc3dDUVlEVlFRRwpFd0pE
      U0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZC
      QW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlM
      VzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOMlpRRFEvd2o2UWxSNVZT
      elFQcG54VVJ3MS9FNkhERGpkVQp3Rm9MOWhYVkVzS0NwMHVGR2JlQVpjNjgxVWhKcGVWVmNmQUNw
      VUNYQWpSMEFkMFdzdldqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9C
      QVFEQWdHbU1CMEdBMVVkRGdRV0JCVFNUVXJ4d2NZa1ovbmwKRVcxem96eTBPOXhuSERBS0JnZ3Fo
      a2pPUFFRREFnTklBREJGQWlFQTRZbWFEWEI4TDRuQnFVeWhuNjhHZjhScApDZFBZT0c5VGdHUXRB
      YnpCMGljQ0lFTDY2KytMdG9wc25Rd2N1a0htSkgvSDZBOG9xUTJNWnU1Q0QvbHBsSUNECi0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYI
      ARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIG
      CAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggS
      BggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggS
      BggBEgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVs
      Q3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoX
      L0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRo
      bRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP//
      //8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWlu
      LW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoK
      BlYxXzRfMxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
