apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIPX6enepO/IWku0zNeZvVq93vqZM8SKpcphZsBUUj+KoEp5eCpteCpheCngKWggBEAEaBgjg
      rvCZBiIKc3lzY2hhbm5lbCpAYzA4YjI1ODMzNzM4ZTVkMjc1NjAyMjcwYjAzOThhOWQ4OGFkNjNk
      ZGZmYTg1ZmQ3MDA2YmMyZTg5ZjM0Nzk4YxIaEhiUEF82OejYj09iOf7BQ03GSPi0bY1hN/ESm10K
      mF0SlV0SvS8KC0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SyC4SsRcK
      D21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVDQkVEQktvSkUw
      TWp0TjJJV3l5SjY4T2huWWd3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpJeE1EQTBNVEV3TnpFeVdoY05NalV3TnpJME1URXdOekV5V2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHd2hUMlgxM1Fu
      dFN3TWZPbitmUW01WG8zMksxRlM4UDB2NgpzSldvU3dSME5tbmVNcWZUbUJrMklTQlcraStERkdM
      WnJHMHR5VGRQWkVQUzJwVEpMQ2VqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1ZOS0RTRjRHUDN1VmwKVmNZd2xyeklXT1BMN1RB
      S0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBT0sxTDRwN2tmVU9EaEJndzdiSVVCQzR1VQpNbzRDWEhk
      eWEzdkNodVAwdmdJZ1NYMlpYLzE0RnhoYmpFek4wcDBjU25NN0poZVBmZW5ZY1BFSjVTVkd3dHM9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURFVENDQXJlZ0F3SUJBZ0lVZXdFNkNsN05JUUEzczFDcnNPRkVkVnBuMGFjd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNREEwTVRFeE5EQXdXaGNO
      TWpNeE1EQTBNVEV4T1RBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEz
      TGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFN
      QmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFE
      REJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkK
      emowREFRY0RRZ0FFL3JqdENDa2hrbDl5YXZRc3dsSkVQcnVOZkdpbnI2ck5qeUlQckw5TFlvQ2No
      djdhMktLMAo4czlITXBFMk5teXNKempnd1ZENnVmd2VDaFVQQzlCWmphT0NBU0l3Z2dFZU1BNEdB
      MVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUaGEyTDkv
      MkFWbWFiVlRaL0ZxdG5ISHVKQmlUQWYKQmdOVkhTTUVHREFXZ0JTVk5LRFNGNEdQM3VWbFZjWXds
      cnpJV09QTDdUQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1kyUTNabVJtT1RjMkxXNDRk
      bUo2TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVk
      V1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZ
      M1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TklBREJGCkFpRUErVkRJeEJvRGxQUnlWYmRKb1FCZ1ExQlRCT3dFcHR6ei9qbzhUTlIxS0VjQ0lG
      azVqQVR4T1h1TXJVelgKeU1Lejl3c3ZBcmtzdkhCOW1ONlpDRVlwN0RRQgotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVDQkVEQktvSkUwTWp0TjJJV3l5SjY4T2huWWd3Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1EQTBNVEV3TnpFeVdo
      Y05NalV3TnpJME1URXdOekV5V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1du
      VnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRY
      SmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NN
      NDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHd2hUMlgxM1FudFN3TWZPbitmUW01WG8zMksxRlM4UDB2
      NgpzSldvU3dSME5tbmVNcWZUbUJrMklTQlcraStERkdMWnJHMHR5VGRQWkVQUzJwVEpMQ2VqUWpC
      QU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdR
      V0JCU1ZOS0RTRjRHUDN1VmwKVmNZd2xyeklXT1BMN1RBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlB
      T0sxTDRwN2tmVU9EaEJndzdiSVVCQzR1VQpNbzRDWEhkeWEzdkNodVAwdmdJZ1NYMlpYLzE0Rnho
      YmpFek4wcDBjU25NN0poZVBmZW5ZY1BFSjVTVkd3dHM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJl
      ck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVy
      ZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxK2FgoKY2Fycmllck1TUBKnFhrDFAoDTVNQErsU
      ErAUEq0UCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrREND
      QVo2Z0F3SUJBZ0lVR0VrM2ZZNnI5SWx0TEozR2haRmdTMjJKR2k4d0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck1qRXdNRFF4TVRBNU1UTmFGdzB5TlRBM01qUXhNVEE1TVROYU1Gb3hD
      ekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZi
      bVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUzk0MGlLZUl4dlpMb1VI
      K2Y2eUZzdERReVY2ZkRLL0ZDN2RkdnlZZzJpYVpUM3VPSzQzMzFldlVjMjF4aTkKZmhubUc5REpI
      VXE3bTNFQ0d6VkhlUStqbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgov
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVV3NWhIRU9CaGNpOXpjeDczOFlBVFhNWDRUc3N3Q2dZSUtv
      Wkl6ajBFCkF3SURTQUF3UlFJZ0pCMzBMMlowRTh3NG9yclc4RFI3by9SeXdrbVA2cnRJVThFN2tQ
      Z0xpb0FDSVFDcXdabzAKM0FBWW9QWG4zOWExL25mRGNtUTVBZUJjbVdnSnlnK084YjdjSXc9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlDN2pDQ0FwU2dBd0lCQWdJVVkyeDVuQWVUS0NWS1R1RFQyWmJmWkppUFI2SXdDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV3TURReE1URTJNREJhRncweU16RXdNRFF4TVRJeE1E
      QmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIy
      NWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0Ex
      VUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTOXNOMk1MclhRaEgrWjNYU3ZTclRMClRz
      UmJFYWdTbytUWk5keVJzeHV5RktRc0UvQ2FuWnhZQXd5ZzVONXhHZkdRRWtvYjVpd0F1dHRQOUlj
      Y1p4bGUKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFB
      d0hRWURWUjBPQkJZRQpGTDZkaHlBQ1RwcTVTNGJYMkZLb1ZhMlNpK3haTUI4R0ExVWRJd1FZTUJh
      QUZNT1lSeERnWVhJdmMzTWU5L0dBCkUxekYrRTdMTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4
      ekxUWmtOR00yWmpjMlpHWXRibXhyWkc0d2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdS
      dGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29a
      SXpqMEVBd0lEU0FBd1JRSWhBSWhSYitLS3pxZ1I4bWhDMk1sSjFsVXl2ZmVmK05uZjZ1OWZpUVZN
      dVU3VApBaUJVOTVXeXdNNkdWeFN4ZzRvQU1wR0pVd1NBV1ByNVZzU3d0Y1g2MGd6UDl3PT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVR0VrM2ZZNnI5SWx0TEozR2haRmdTMjJK
      R2k4d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2
      Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3
      RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXdNRFF4TVRBNU1UTmFGdzB5
      TlRBM01qUXhNVEE1TVROYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVr
      YjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVH
      QTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJC
      d05DCkFBUzk0MGlLZUl4dlpMb1VIK2Y2eUZzdERReVY2ZkRLL0ZDN2RkdnlZZzJpYVpUM3VPSzQz
      MzFldlVjMjF4aTkKZmhubUc5REpIVXE3bTNFQ0d6VkhlUStqbzBJd1FEQVBCZ05WSFJNQkFmOEVC
      VEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVV3NWhIRU9CaGNpOXpj
      eDczOFlBVFhNWDRUc3N3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJZ0pCMzBMMlowRTh3NG9yclc4
      RFI3by9SeXdrbVA2cnRJVThFN2tQZ0xpb0FDSVFDcXdabzAKM0FBWW9QWG4zOWExL25mRGNtUTVB
      ZUJjbVdnSnlnK084YjdjSXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQK
      BkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0Vu
      ZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1Jl
      YWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNo
      YW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFu
      bmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxKPKwoHT3JkZXJlchKD
      KxLOFgoOc3VwcGx5Y2hhaW5NU1ASuxYaxxQKA01TUBK/FBK0FBKxFAoOc3VwcGx5Y2hhaW5NU1AS
      8QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi96Q0NBYWFnQXdJQkFnSVVTSnA1YmJt
      S0ErZTA2NGgwZHpRMUR2Z2gxTDh3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhj
      Tk1qSXhNREEwTVRFd05URXhXaGNOTWpVd056STBNVEV3TlRFeFdqQmVNUXN3Q1FZRFZRUUdFd0pI
      UWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05W
      QkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJa
      TUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkt0ajNkTU9Id3ptQmVJUVBRam43V1J1
      bUJLdEpOSHhsdWNjS2MzdytoSEljd2xzK3pMZAo5L1dCdXBhUzZFWFJpeC9FaytNNU5yZEt4SldF
      NjRhV254S2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dt
      TUIwR0ExVWREZ1FXQkJTZ2J0NSsyUjBIR3NyS29XejlsZUdXU3FpUVd6QUsKQmdncWhrak9QUVFE
      QWdOSEFEQkVBaUJXV2o1MXJEbUdRbkFsaEpscnVrMlNyczJScnpZd3dzVDd1b0FlbmI2OAp5Z0ln
      WGtJeGtGblNXRXR0U3h5dGxnUjdNMDNKa1VXaUZFd3RLRnFSa1kvNUtGYz0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoipggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzRqQ0NBb2ln
      QXdJQkFnSVVMbzZKYUxoazVuVVplRDExMjZhRUphU3dSUFF3Q2dZSUtvWkl6ajBFQXdJdwpYakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGph
      R0ZwYmkxdVpYUXcKSGhjTk1qSXhNREEwTVRFeE1qQXdXaGNOTWpNeE1EQTBNVEV4TnpBd1dqQnNN
      UXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVN
      UkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUTR3CkRBWURWUVFMRXdWaFpHMXBiakVlTUJ3R0ExVUVB
      d3dWUVdSdGFXNUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3cKRXdZSEtvWkl6ajBDQVFZSUtvWkl6
      ajBEQVFjRFFnQUV3Y3JRaFNvMEVtemgyYkJhL2d0bFhBNVhTMWpSSDhDbwp1NFY0VTBiNXBSY09H
      bjYzNm9zUmhUdEpNT2pvd1FURmFKa0NmMk5jMDlMT243Q05lWUhSOWFPQ0FSUXdnZ0VRCk1BNEdB
      MVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlEyQ2lxV0Jk
      ZncKRythVTJFdDhncFE5NjVhbVZEQWZCZ05WSFNNRUdEQVdnQlNnYnQ1KzJSMEhHc3JLb1d6OWxl
      R1dTcWlRV3pBawpCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAxTmpZM1l6WTNabVkzTFdwM2Rt
      eHJNSUdKQmdncUF3UUZCZ2NJCkFRUjlleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNu
      VmxJaXdpWVdSdGFXNGlPaUowY25WbElpd2kKYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpTENKb1pp
      NUZibkp2Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0J6ZFhCdwpiSGxqYUdGcGJpMXVaWFFpTENKb1pp
      NVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3ClJRSWhBT3pBdG4wc1p0
      UXlNa0o4eUdRcVJWTjRXWGVld0lwR09ycGpJSlhZaWJWZ0FpQUgwY2V0TnRLMWlDOTcKSWdINlov
      SGxEcTNDb25wNUdveVFhTHQ1QXV3TGJnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoE
      U0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekNDQWFhZ0F3
      SUJBZ0lVU0pwNWJibUtBK2UwNjRoMGR6UTFEdmdoMUw4d0NnWUlLb1pJemowRUF3SXcKWGpFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5
      dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdG
      cGJpMXVaWFF3CkhoY05Nakl4TURBME1URXdOVEV4V2hjTk1qVXdOekkwTVRFd05URXhXakJlTVFz
      d0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1
      a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdO
      b1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJLdGozZE1PSHd6
      bUJlSVFQUWpuN1dSdW1CS3RKTkh4bHVjY0tjM3craEhJY3dscyt6TGQKOS9XQnVwYVM2RVhSaXgv
      RWsrTTVOcmRLeEpXRTY0YVdueEtqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2didDUrMlIwSEdzcktvV3o5bGVHV1NxaVFXekFL
      CkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCV1dqNTFyRG1HUW5BbGhKbHJ1azJTcnMyUnJ6WXd3c1Q3
      dW9BZW5iNjgKeWdJZ1hrSXhrRm5TV0V0dFN4eXRsZ1I3TTAzSmtVV2lGRXd0S0ZxUmtZLzVLRmM9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOwoLRW5kb3JzZW1lbnQSLBIiCAES
      HhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcKB1JlYWRlcnMSLBIiCAES
      HhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcKB1dyaXRlcnMSLBIiCAES
      HhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgKBkFkbWlucxIuEiQIARIg
      EggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyoGQWRtaW5zGiYKDENhcGFi
      aWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqCEgoNQ29uc2Vuc3VzVHlwZRLwERLlEQoI
      ZXRjZHJhZnQS2BEKwREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrPCC0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlEQWpDQ0FxbWdBd0lCQWdJVWM1ZlpsaEFiZGJsM2c5dnU2cEJP
      YVBEbUNPa3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdN
      Qmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5
      TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1EQTBNVEV4
      TWpBd1doY05Nak14TURBME1URXhOekF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVF
      QnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcK
      RGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGph
      R0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNZaTQ2RUNoTjY2
      YlEwaTZYK01xV3VHaEhlCnFBWUE2WUZWTXgyMWVPM0FNcDJ4d29LR2dQKzFwOFhRTmNLUDh5THRl
      eEJwQVRvbFUyNXNPL2M5djNQZG80SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdB
      MVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFN
      QjBHQTFVZERnUVdCQlIrL01mUUVXZk5CK2t1WnVpbUVwd3NRcW1OCkt6QWZCZ05WSFNNRUdEQVdn
      QlNnYnQ1KzJSMEhHc3JLb1d6OWxlR1dTcWlRV3pBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlN
      UzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZ
      Mjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlq
      b2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFX
      NHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3
      QXdSQUlnTnp5NTd3RTdMc3hRY2tnMwprQlNuQVgxM01QcFRVYlFzc2s5UVFCM0NmUHNDSUd3bjdZ
      MXNiMFRQMDIrU0V4VXF4aStKUDloMkxkMjI1TFc5ClZpai9Ud21YCi0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KIs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJB
      Z0lVYzVmWmxoQWJkYmwzZzl2dTZwQk9hUERtQ09rd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJp
      MXVaWFF3CkhoY05Nakl4TURBME1URXhNakF3V2hjTk1qTXhNREEwTVRFeE56QXdXakJ4TVFzd0NR
      WURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0Rn
      WURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4
      aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBU1lpNDZFQ2hONjZiUTBpNlgrTXFXdUdoSGUKcUFZQTZZRlZNeDIxZU8zQU1w
      Mnh3b0tHZ1ArMXA4WFFOY0tQOHlMdGV4QnBBVG9sVTI1c08vYzl2M1BkbzRJQgpNRENDQVN3d0Rn
      WURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJR
      Y0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUisvTWZRRVdmTkIra3VadWltRXB3
      c1FxbU4KS3pBZkJnTlZIU01FR0RBV2dCU2didDUrMlIwSEdzcktvV3o5bGVHV1NxaVFXekEvQmdO
      VkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJ
      eExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpw
      N0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNK
      a1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJ
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdOenk1N3dFN0xzeFFja2czCmtCU25BWDEzTVBw
      VFViUXNzazlRUUIzQ2ZQc0NJR3duN1kxc2IwVFAwMitTRXhVcXhpK0pQOWgyTGQyMjVMVzkKVmlq
      L1R3bVgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICAChoGQWRt
      aW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIO
      EgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0
      ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwK
      CgoGVjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1p
      bnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRl
      cmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
