apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaICRdiSBeEqC9aW9i3G2XgX8vZ9vmIPCItVmiN1y2M0CjEqJeCp9eCpxeCngKWggBEAEaBgj4
      wvaXBiIKc3lzY2hhbm5lbCpAYmE5YzdlNjYyMzMyNzg0NTVhOTM5Mzk1YmI2ZWQ2ZTc2ZDk3YzJh
      YjEzODJlNDIwNzU4YTY1ZmNkNDcxNjFiYxIaEhijkT06CNa6jJsXD6MnEo75PYgPDiQSAvMSn10K
      nF0SmV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVVGd1WURNdE5nZ0hmbThRajdQZkVUczM3eTRRd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RFNE1ESXdNVFF3V2hjTk1qVXdOakEzTURJd01UUXdX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJPemwz
      Q2FQR1NwMnpaelR2cmM4VGwvdDhnWmsvOE5jNG10VDFCdUFmRi8vZFRDTFU1bHgKS3hGa0g0aDNE
      b2ltOUF4VDRVQ1dxMzlPTmpicXlYRzA4S21qUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVGcvNFVtQmQwOXZibUVRR2o1YjhJWDVT
      QmF0VEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBclNIVE5oSmNPbFhSTDQrdFVjdDJEQWZHa2pS
      aVBTMXNTMDVmZk85TkgKUHdJaEFQTGhlWWNPUWVLVnhHdEpMOE0rMmUrQnRXRFJaSkUyOFp1dGh6
      R1haN3g1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVVzVQV3RtT1BjMkRYZHprcktkNXI3bk9KN1Nrd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RFNE1ESXdPVEF3V2hjTk1q
      TXdPREU0TURJeE5EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFb25pdm5VMWI2UFJNNUdBcXpES0hESHpaQzdo
      T1lRdEUKS1c3Znl6cjFMaU91LzJ6L2htazB6TWJtZlQ2ckIxMjhOUUk1akVUU3ppaER4RmEvU093
      NGE2T0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRMzNSQXJqNGhuCkdkVUxSMHFNN3Vzb2oxcjl2ekFmQmdOVkhTTUVHREFXZ0JU
      Zy80VW1CZDA5dmJtRVFHajViOElYNVNCYXRUQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xUSjJPWGc0TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnQ1hQV3hCYVR1cUQ4ak9CalhpeExrMDg2SEx2em1KS3VRZk9EdGhkaEZrZ0NJRmww
      eVVFSHVoRlZQdExSCngrbFVVTlhLK3RJOVorekgzMTZaU0g1Y0l0ZHYKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVVGd1WURNdE5nZ0hmbThRajdQZkVUczM3eTRRd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RFNE1ESXdNVFF3V2hjTk1qVXdOakEz
      TURJd01UUXdXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJPemwzQ2FQR1NwMnpaelR2cmM4VGwvdDhnWmsvOE5jNG10VDFCdUFmRi8vZFRDTFU1bHgK
      S3hGa0g0aDNEb2ltOUF4VDRVQ1dxMzlPTmpicXlYRzA4S21qUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVGcvNFVtQmQwOXZibUVR
      R2o1YjhJWDVTQmF0VEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBclNIVE5oSmNPbFhSTDQrdFVj
      dDJEQWZHa2pSaVBTMXNTMDVmZk85TkgKUHdJaEFQTGhlWWNPUWVLVnhHdEpMOE0rMmUrQnRXRFJa
      SkUyOFp1dGh6R1haN3g1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOwoLRW5k
      b3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyoG
      QWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0
      aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooS
      Cg1Db25zZW5zdXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0EIo3GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQXFtZ0F3SUJB
      Z0lVVnIyU05LeXhxV09QWHZDSEZvRjdBZmFoRklRd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJp
      MXVaWFF3CkhoY05Nakl3T0RFNE1ESXdPVEF3V2hjTk1qTXdPREU0TURJeE5EQXdXakJ4TVFzd0NR
      WURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0Rn
      WURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4
      aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBUStqY0IvRURkZDRLWXZOWmxoQldaNjdMZ0wKdmtuczdlMCtkbWJ6S2ozaUgz
      YzR4NG1yYk9jbHRqRmFFZmx1MlBUR3E4SEJ6c3dKVjF3a09wczB2ek5mbzRJQgpNRENDQVN3d0Rn
      WURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJR
      Y0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUUhyOXhFNThrUkFjYWhtN2N3U054
      bXV6YlcKT3pBZkJnTlZIU01FR0RBV2dCVGcvNFVtQmQwOXZibUVRR2o1YjhJWDVTQmF0VEEvQmdO
      VkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJ
      eExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpw
      N0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNK
      a1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJ
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTnZjSTJ3Tzh5amdnSjcwCjFzYnZLcmRmcXJT
      VGtDQitKeUUzL0xITG9WRnNBaUJVVXBseEFUWnY1WEpGNk9vN3AwZUZ2WGluTHVldmlPelAKQVdh
      UTU0UTlSUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSURBekNDQXFtZ0F3SUJBZ0lVVnIyU05LeXhxV09QWHZDSEZvRjdBZmFoRklR
      d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZ
      RFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RFNE1ESXdPVEF3V2hj
      Tk1qTXdPREU0TURJeE5EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRF
      dU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFR
      TEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1
      ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUStqY0IvRURkZDRLWXZOWmxo
      QldaNjdMZ0wKdmtuczdlMCtkbWJ6S2ozaUgzYzR4NG1yYk9jbHRqRmFFZmx1MlBUR3E4SEJ6c3dK
      VjF3a09wczB2ek5mbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFX
      TUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVk
      RGdRV0JCUUhyOXhFNThrUkFjYWhtN2N3U054bXV6YlcKT3pBZkJnTlZIU01FR0RBV2dCVGcvNFVt
      QmQwOXZibUVRR2o1YjhJWDVTQmF0VEEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dH
      Q0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kK
      YUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJ
      aXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhB
      TnZjSTJ3Tzh5amdnSjcwCjFzYnZLcmRmcXJTVGtDQitKeUUzL0xITG9WRnNBaUJVVXBseEFUWnY1
      WEpGNk9vN3AwZUZ2WGluTHVldmlPelAKQVdhUTU0UTlSUT09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICA
      MRiAgEAaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1p
      bnMSvS8KC0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SyC4SsRcKD21h
      bnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVaSGUwc3V0VTJlazky
      ci9WTDhNUnNJZFFxWFl3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpJd09ERTRNREl3TXpReVdoY05NalV3TmpBM01ESXdNelF5V2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGSGxyN2trd2JaUnov
      bEpBVHhZc3VXbjcrRWRLT09XWHdzOApRSFpYOXZsRytQeXMvbjFEckRwRVMzSFJxSmFJdXg5eVJL
      NUNBc0hueHVHU0RiOEoveUtqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2hiT05vZ2hXaEtNNHIKb2IxNWRVRHpVWFFKempBS0Jn
      Z3Foa2pPUFFRREFnTkhBREJFQWlBS1gzY2dPbjM3cmFtYWFERDBMakNHaDhGOQpPeUMzdnZCS004
      R3BWSlNmQVFJZ0ZKUUErbGl0THBtd2RONEJaZmRLQ2dsUEEwWHQwTTQ1N1BKdHNXVXhPL2M9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURFVENDQXJlZ0F3SUJBZ0lVYjVTTGZsYjR6WFFJSjAwNWgxYWlvbjZOSEVrd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPREU0TURJeE1UQXdXaGNOTWpN
      d09ERTRNREl4TmpBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpN
      NEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdO
      VkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJa
      QlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemow
      REFRY0RRZ0FFTE5zK0FYU2FYVzJzNXJkN045ZTVvZE1pU0NpRXZ0SVpUMnZrM3RaOHU4RjUrd0Uy
      OERvbgpnd29GSjYwbko5MUgyZ0F0TGdPd2p2c0FqRzJqbWIwWDZLT0NBU0l3Z2dFZU1BNEdBMVVk
      RHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTRXV6Z1VKRldn
      YmdUMGRxSjVwNnhWVU5qby96QWYKQmdOVkhTTUVHREFXZ0JTaGJPTm9naFdoS000cm9iMTVkVUR6
      VVhRSnpqQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1kyUTNabVJtT1RjMkxXdG1Oakp6
      TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEox
      WlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1po
      WTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1Ix
      Y21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklB
      REJGCkFpRUE5Y2dodFZoWFYwMzRBOWVlMk5aMkJQK1R4eEIvVW9IOXVWRGVNRElsL093Q0lId2pK
      eVc4aUtzMjhFQ1kKa1dqWnczbCtJejB4QnlqMUt5dmxGUHVwaEp2eQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQ0N6Q0NBYktnQXdJQkFnSVVaSGUwc3V0VTJlazkyci9WTDhNUnNJZFFxWFl3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd09ERTRNREl3TXpReVdoY05N
      alV3TmpBM01ESXdNelF5V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlh
      V05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxj
      akVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJGSGxyN2trd2JaUnovbEpBVHhZc3VXbjcrRWRLT09XWHdzOApR
      SFpYOXZsRytQeXMvbjFEckRwRVMzSFJxSmFJdXg5eVJLNUNBc0hueHVHU0RiOEoveUtqUWpCQU1B
      OEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      U2hiT05vZ2hXaEtNNHIKb2IxNWRVRHpVWFFKempBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBS1gz
      Y2dPbjM3cmFtYWFERDBMakNHaDhGOQpPeUMzdnZCS004R3BWSlNmQVFJZ0ZKUUErbGl0THBtd2RO
      NEJaZmRLQ2dsUEEwWHQwTTQ1N1BKdHNXVXhPL2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1T
      UBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJN
      U1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJN
      U1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxK2FgoKY2Fycmllck1TUBKnFhrDFAoDTVNQErsUErAU
      Eq0UCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2
      Z0F3SUJBZ0lVVHdHUVVRaUxpbDlTdm5Fb1BvR25vKzFCTzh3d0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5
      TFc1bGREQWVGdzB5Ck1qQTRNVGd3TWpBMU5EVmFGdzB5TlRBMk1EY3dNakExTkRWYU1Gb3hDekFK
      QmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2
      YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVFdDUW5JVml4OW9aZ3FnYitG
      OGtzMzY1TWhGd3djbGE0TmI4NWEyUzlJSE03dFJvNnEvNTJmSUpHZFJ4NmUKc1ZhSThLRFgzTVJv
      blZ5SlpxNVMvL3o3bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FF
      QXdJQnBqQWRCZ05WSFE0RUZnUVVEZVR3eEJrREhEMHI2blRMK1JIbVpDaGZaZmd3Q2dZSUtvWkl6
      ajBFCkF3SURTQUF3UlFJZ2V6V3VBeEtKVXFlK1JLclpEMkxsZnVyTnJLcmd1Q1BOUVBCbXl5aTFu
      bFlDSVFERTJxNGcKeWllWWIvUzR2U2g1UjdRRk1tbDIyVlpxaDdSTmFIN05Kam1SWVE9PQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      N2pDQ0FwU2dBd0lCQWdJVURReTRxSU0zdDA5R3JhL2J0YUsyd1ZkM05XUXdDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNakE0TVRnd01qRXpNREJhRncweU16QTRNVGd3TWpFNE1EQmFN
      SGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWti
      MjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVD
      eE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSSlFMWjltYzFrekQyeG5ISEN5RnhUCkc5K2tL
      dVF4b2llNHRFditnUjhpTFptMVFlVDl0ZUhjemlKcVdqU2toNEwzT2pvbGNBaUMyaWk5RDlHMWNB
      dUMKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRQpGSlBUNVVLQVljRU9SbVhXSUlnU2pEWllIQ1ZCTUI4R0ExVWRJd1FZTUJhQUZB
      M2s4TVFaQXh3OUsrcDB5L2tSCjVtUW9YMlg0TUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxU
      WmtOR00yWmpjMlpHWXRaMjVvTldnd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5
      SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFX
      eHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFX
      NUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpq
      MEVBd0lEU0FBd1JRSWhBUE5yUHFGbXBXZVNZdGNUZytxejU1bnRvOEVXMUNieDFKNzdYb3VSY2p0
      OApBaUJRZ29LNEtzMlJsdW9OSmxEQkZRRE1vV0pVaVBNazREV3ZSbkcvREs2aThRPT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVVHdHUVVRaUxpbDlTdm5Fb1BvR25vKzFCTzh3
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTRNVGd3TWpBMU5EVmFGdzB5TlRB
      Mk1EY3dNakExTkRWYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0
      eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFV
      RUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05D
      CkFBVFdDUW5JVml4OW9aZ3FnYitGOGtzMzY1TWhGd3djbGE0TmI4NWEyUzlJSE03dFJvNnEvNTJm
      SUpHZFJ4NmUKc1ZhSThLRFgzTVJvblZ5SlpxNVMvL3o3bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFE
      QVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVEZVR3eEJrREhEMHI2blRM
      K1JIbVpDaGZaZmd3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJZ2V6V3VBeEtKVXFlK1JLclpEMkxs
      ZnVyTnJLcmd1Q1BOUVBCbXl5aTFubFlDSVFERTJxNGcKeWllWWIvUzR2U2g1UjdRRk1tbDIyVlpx
      aDdSTmFIN05Kam1SWVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcKC0Vu
      ZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1Jl
      YWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIg
      CAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5u
      ZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3Jp
      dGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI
      /////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwK
      CgoGVjFfNF8zEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
