apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIFEMGRVEsMnwmAYpH8X4zVHziuWKRQagrd3HiiRuq0z+Eo5eCoteCoheCngKWggBEAEaBgil
      9+mZBiIKc3lzY2hhbm5lbCpAOTg3MzU4ZmE4MGUzMTI4ZTY1M2ZkZTc4ZjhiMDFjMDJlNDVmOWRm
      NjdjZDJhNjM1MmI4OTQwMmUxOTE2MWUwNBIaEhiw+GiqvL/3CN3/bE3N7+1NF3y1IknrgCESi10K
      iF0ShV0SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVUFkyelJGUEZYNnRPL1hBOFNxNWxwV2hzMmx3d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBek1EVTBPREkzV2hjTk1qVXdOekl6TURVME9ESTNX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGaWtJ
      OTBPTXo2a3M0RGozTVJCSnJ2N3FtdW1CT0ZGWjJIWEM4Q24xTHNseUdwOTJmWUQKTlRXVnMrSGxr
      OFh4R0ZhVUw4aWJVYnhZVjhMR255blp3bCtqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWJSbXdSa0tzZ0VEcURxaUkreWF1N3J6
      cnNMekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCN1Qyb202aCtMTHoreEY0UW1ZRUlvVUkydGpE
      V1gvd3NXTUEzaWUzL2cKSWdJaEFJYlZ3WmxGZEJxeG9xb1NUbjd5bmpydjlYbm1DN3NSQ3huNi9I
      UnpuUkM0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVYVJYT05veUtvR3JpZzU5S25qN2R5R2hFRUxJd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBek1EVTFOVEF3V2hjTk1q
      TXhNREF6TURZd01EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFVklxdWVQOFJCdWtEdld6azVKZTI3cXh3eGZ4
      TWk0M3AKbWtkNjczeUpkNVF0T3JvckpLbW8yQlZTT2w5VnRTMXZ5enZGamtnWi8rZ2tsUlZwdTdL
      VnU2T0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUcnRhL1pBVVppCnU0Ulh4bkYvRnBvQWc0K09YVEFmQmdOVkhTTUVHREFXZ0JR
      YlJtd1JrS3NnRURxRHFpSSt5YXU3cnpyc0x6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xXTnFibk5yTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnWDEyL0RMWVdSbkVzWEdXWFJwcWpIWlNiV0dLVjlRMW9LM25SV2FNcnI5UUNJREU0
      MnBzczRtUlRpUXdkClRxSGtIZTY5eWRwckdFdmpaK2VoTGl0T1FRVFkKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVUFkyelJGUEZYNnRPL1hBOFNxNWxwV2hzMmx3d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBek1EVTBPREkzV2hjTk1qVXdOekl6
      TURVME9ESTNXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJGaWtJOTBPTXo2a3M0RGozTVJCSnJ2N3FtdW1CT0ZGWjJIWEM4Q24xTHNseUdwOTJmWUQK
      TlRXVnMrSGxrOFh4R0ZhVUw4aWJVYnhZVjhMR255blp3bCtqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWJSbXdSa0tzZ0VEcURx
      aUkreWF1N3J6cnNMekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCN1Qyb202aCtMTHoreEY0UW1Z
      RUlvVUkydGpEV1gvd3NXTUEzaWUzL2cKSWdJaEFJYlZ3WmxGZEJxeG9xb1NUbjd5bmpydjlYbm1D
      N3NSQ3huNi9IUnpuUkM0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGoISCg1Db25zZW5zdXNUeXBlEvAREuUR
      CghldGNkcmFmdBLYEQrBEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3Gs8ILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVQTJpbSs2eE1ZYmUrYThDZTBy
      cmVZeWRSQWJvd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBek1E
      VTFOakF3V2hjTk1qTXhNREF6TURZd01UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUm16QUowaDVL
      MnV5MVB2b0ZmQ2NwTGM1eVUKZndXNWFDVmtmNldnOGZSUkRMSHZNVTlybEh2L3QzejJsR3Z5cTBJ
      WmMxSjA2WE4wNTVhT09NL3ozMkx0bzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUXVveHJaUUgwMzVSVEV5RkVwWDhsc3ljVlQKY1RBZkJnTlZIU01FR0RB
      V2dCUWJSbXdSa0tzZ0VEcURxaUkreWF1N3J6cnNMekEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1
      ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1
      SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmho
      YVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBd1JBSWdkVm5VNWgrTGpveVduTWxQCmlFQTlDckpmNm15TVByci9URzlpMkJCL1hRd0NJRWZI
      V1RmemZEQ2l2cUQ5QVRIOS9Ib0RUbFVWeVNoa1p3eDAKMUJCTStndzEKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQoizwgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREFqQ0NBcW1nQXdJ
      QkFnSVVBMmltKzZ4TVliZSthOENlMHJyZVl5ZFJBYm93Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0Zw
      YmkxdVpYUXcKSGhjTk1qSXhNREF6TURVMU5qQXdXaGNOTWpNeE1EQXpNRFl3TVRBd1dqQnhNUXN3
      Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3
      RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFE
      RXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DQUFSbXpBSjBoNUsydXkxUHZvRmZDY3BMYzV5VQpmd1c1YUNWa2Y2V2c4ZlJS
      RExIdk1VOXJsSHYvdDN6MmxHdnlxMElaYzFKMDZYTjA1NWFPT00vejMyTHRvNElCCk1EQ0NBU3d3
      RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYK
      QlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRdW94clpRSDAzNVJURXlGRXBY
      OGxzeWNWVApjVEFmQmdOVkhTTUVHREFXZ0JRYlJtd1JrS3NnRURxRHFpSSt5YXU3cnpyc0x6QS9C
      Z05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnla
      WEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJ
      anA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2li
      M0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnla
      WElpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ2RWblU1aCtMam95V25NbFAKaUVBOUNySmY2
      bXlNUHJyL1RHOWkyQkIvWFF3Q0lFZkhXVGZ6ZkRDaXZxRDlBVEg5L0hvRFRsVVZ5U2hrWnd4MAox
      QkJNK2d3MQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZB
      ZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggD
      EgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMa
      BkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5zErEvCgtD
      b25zb3J0aXVtcxKhLxLWLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtErwuErEXCg9tYW51ZmFjdHVy
      ZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVZkpaUGsrRG1rWFp6ZHcxTSsrSm9G
      VWUzSG1Bd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhN
      REF6TURVMU1ESTRXaGNOTWpVd056SXpNRFUxTURJNFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBN
      QTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpE
      RTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGRE
      QlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCUGR3Q2NkaEJLRC8xNmwrdGdSU1pq
      b1NVL1FaS3BWQ1ZEZ2gKbWJYSTBEcFA4Z0N5VzliZnVma1F0Y3FBVHhjR3IwOWZRVFIxR0VKSmNw
      RGJZbVBzaEFhalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlJINWsycXR3NVZmSTFtClpZTnYwdjNtODl1Q1h6QUtCZ2dxaGtqT1BR
      UURBZ05JQURCRkFpRUEvTFNyWm85VGJOQzdKbmZTdldWb1o1RjYKV2dlQUR3Tnc5N1ZjSlM2QmJj
      WUNJQStBUmdyWDRxYTdSbmE5aEJrUWFGdkNacGNZOG9KOVNVaXBOY3ZGOGdGUAotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERURDQ0Fy
      ZWdBd0lCQWdJVUpCcEtFdzAxYmdHcjRNWXpHYkZwWmk2Wm1mRXdDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TURBek1EVTFPREF3V2hjTk1qTXhNREF6TURZ
      d016QXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRR
      dlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldG
      a2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtC
      dFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdB
      RTFjUExnRG96Y1hpNk8rYzZIc1gyY0tPcmhUOGRNOHNtUnVQTVNLWm02bVlPVFM3VTdLbFYKcUtG
      YXdnY1kzalpsbHlubUwwTWR2OGxXN0x6NWVSaUZhNk9DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FF
      QXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVHI4YkxoRGVlMVgrQlBpdDBZ
      NEMrbGVySmhnREFmCkJnTlZIU01FR0RBV2dCUkg1azJxdHc1VmZJMW1aWU52MHYzbTg5dUNYekFr
      QmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMWEkxYW5wck1JR1hCZ2dx
      QXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZr
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5
      SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVs
      ZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRQpBaUFp
      TEptK2tLZ2ppbWhISEJnanN5L1FOMEppbzQwdE50K0ZGaHgzdHVhL3l3SWdUVS9RcnIzeXhjd0RL
      Ti9lCkRjV1M5RUFGRW1FY1pOT2FZTmk1TFVaOUpQOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEREND
      QWJLZ0F3SUJBZ0lVZkpaUGsrRG1rWFp6ZHcxTSsrSm9GVWUzSG1Bd0NnWUlLb1pJemowRUF3SXcK
      WkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhM
      bTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNREF6TURVMU1ESTRXaGNOTWpVd056SXpN
      RFUxTURJNFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdE
      UVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dB
      MVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdT
      TTQ5QXdFSEEwSUFCUGR3Q2NkaEJLRC8xNmwrdGdSU1pqb1NVL1FaS3BWQ1ZEZ2gKbWJYSTBEcFA4
      Z0N5VzliZnVma1F0Y3FBVHhjR3IwOWZRVFIxR0VKSmNwRGJZbVBzaEFhalFqQkFNQThHQTFVZApF
      d0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJINWsycXR3
      NVZmSTFtClpZTnYwdjNtODl1Q1h6QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUEvTFNyWm85VGJO
      QzdKbmZTdldWb1o1RjYKV2dlQUR3Tnc5N1ZjSlM2QmJjWUNJQStBUmdyWDRxYTdSbmE5aEJrUWFG
      dkNacGNZOG9KOVNVaXBOY3ZGOGdGUAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlu
      cyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1p
      bnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQEAEaBkFk
      bWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1T
      UBoGQWRtaW5zKgZBZG1pbnMSqhYKCmNhcnJpZXJNU1ASmxYatxQKA01TUBKvFBKkFBKhFAoKY2Fy
      cmllck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJ
      VVZZY0RuWDdpVmVwU01kb3l1NnI2Ni9BajB6Z3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFl
      RncweQpNakV3TURNd05UVXlNamxhRncweU5UQTNNak13TlRVeU1qbGFNRm94Q3pBSkJnTlZCQVlU
      QWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRH
      QTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRSNlBEWHVIVmJnLzNCTko3UWhsQmNTMm5m
      MTA3aWo2aFZWTkhwTUczUHZsdjYvQVJHMWNXRW1EUEtsdmVOCitScjVpYnFwUStHVWJvZmFkZSti
      R09mS28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFk
      QmdOVkhRNEVGZ1FVdHlSUHBwczZpQ2Z5Sm5Nb0tETDU3Ti9VeFNvd0NnWUlLb1pJemowRQpBd0lE
      UndBd1JBSWdYeFB1a2ZMazM0dUtjalJSVmxoZ1NHTjZRaWtSYzRXalQvMENOS21wQkc0Q0lIc0xV
      L1lkCk5Ic0ViZmcyaW9ocThXL2xhUFNKOGJTS0xXeTZtYUFLcEhMdgotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDN1RDQ0FwU2dBd0lC
      QWdJVU5LVG1BUUJxYzU5c1ZiUktVOEYwYXRZRkhTSXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxk
      REFlRncweQpNakV3TURNd05qQXdNREJhRncweU16RXdNRE13TmpBMU1EQmFNSGd4Q3pBSkJnTlZC
      QVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZC
      QW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJGeWNtbGxj
      akVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJC
      Z2dxaGtqT1BRTUJCd05DQUFTYWRSa1FLcWFDa3pJc004S0J5bUV6CkVzOVJmK0pBZWFZWmZreGNG
      TjB5bFJRTXQyUUxPT2tvSmp4WGZ3OUNPUFNMODl5UVNBOUtMUGJiOHJIT3oxa0EKbzRJQkdEQ0NB
      UlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpG
      T0VocTZKVFF3VlR3TGtDeithbkQyVFNFUndJTUI4R0ExVWRJd1FZTUJhQUZMY2tUNmFiT29nbjhp
      WnpLQ2d5CitlemYxTVVxTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxUWmtOR00yWmpjMlpH
      WXRjbkJqZDNZd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFY
      UWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9p
      SmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFXNUFZMkZ5Y21sbGNp
      MXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpqMEVBd0lEUndBd1JB
      SWdDY1ZPNFJwSUJlWWI2bEJzQW9qNWczV1VLYlJweGx3TExmNndCT0VSUGVVQwpJQVNYUjNQeVBl
      cXcwUmQwc3puWFR0Q1VPUlBxOXhLVGRJZXZaZ0lScW81UwotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCkIOCgRTSEEyEgZTSEEyNTZK5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjl6
      Q0NBWjZnQXdJQkFnSVVWWWNEblg3aVZlcFNNZG95dTZyNjYvQWowemd3Q2dZSUtvWkl6ajBFQXdJ
      dwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhK
      eWFXVnlMVzVsZERBZUZ3MHkKTWpFd01ETXdOVFV5TWpsYUZ3MHlOVEEzTWpNd05UVXlNamxhTUZv
      eEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4
      dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21s
      bGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUUjZQRFh1SFZiZy8z
      Qk5KN1FobEJjUzJuZjEwN2lqNmhWVk5IcE1HM1B2bHY2L0FSRzFjV0VtRFBLbHZlTgorUnI1aWJx
      cFErR1Vib2ZhZGUrYkdPZktvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VC
      Ci93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXR5UlBwcHM2aUNmeUpuTW9LREw1N04vVXhTb3dDZ1lJ
      S29aSXpqMEUKQXdJRFJ3QXdSQUlnWHhQdWtmTGszNHVLY2pSUlZsaGdTR042UWlrUmM0V2pULzBD
      TkttcEJHNENJSHNMVS9ZZApOSHNFYmZnMmlvaHE4Vy9sYVBTSjhiU0tMV3k2bWFBS3BITHYKLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARIC
      CAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggB
      EgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggA
      Gg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIM
      CgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIM
      CAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRt
      aW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQT3Jk
      ZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5l
      bC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMi
      IgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdS
      ZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlu
      cxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
