apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://35.247.9.75:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: supplychain-net

    genesis: |-
      CiIaINtTbaucDkgFH4x+PEsIbLFtUSz/YBTa/irrSOjr/X4kEppeCpdeCpReCngKWggBEAEaBgiB
      w7SdBiIKc3lzY2hhbm5lbCpAOGUzYTM3YTY2YTU1MzRhZjQ0MjkyZmQ0ZDIzNGFiMjU2ODk3MGU5
      NWJiMzA0Yzc1ZDkxNDc1MGI4ODRjNjE3ZRIaEhjOdpgSoX6VEqx/9gDC+y+drHbQsVRaHwESl10K
      lF0SkV0SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVRnhDMjMzY2k2TjIzVktIeVYwMEFEY2hOYVI4d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJNU1EUTFOVFV4V2hjTk1qVXhNREU0TURRMU5UVXhX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJHbGVO
      dG1PcGFsKzJoYzJST2VROUNzN2lreGRqaHJsSkk2YzM3by9KM3NLRUhkdCtFb2gKWDlBUjJZUFY1
      bFZHNXprcU9IV05jSll2aEJCVUxNR1A4VTJqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2tYb0h3cmtvbmxkNm9JaU5iaktScDdE
      eVZWekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQWc5ejhqc21xOU13aUVhWVpsU1ZSYTBpb3l0
      ZUlrUFpub3k1N09relAKZnVnQ0lIZjZOVjFnN2UwaHlCN2ZuQm9oMDJaa09Tb2xnRnNtcWFQV1Jm
      YVlSZWs4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVVFFFOG8rOE1CRytrN0NjNFpSNlQ1dXZGdWhjd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJNU1EVXdNVEF3V2hjTk1q
      TXhNakk1TURVd05qQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFL2Q0S2RnU2ZjZG5laHovNHEzOFl5b1BkMzFE
      M3NCbGUKRUgzR0pnSHZDS3pFUlIxdHREVzhnQW1kTnhBZnNkSTJtdGtPME9LSU9ZcDNnZmEyZFF3
      ZVRLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTMGpRWjRiUHpKCllpRGlKcnZWWjZKS1hwWmlFekFmQmdOVkhTTUVHREFXZ0JT
      a1hvSHdya29ubGQ2b0lpTmJqS1JwN0R5VlZ6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      NE5qYzRZamxtT1dJM0xYcDNObXhyTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnTXJKa0dwSHhtU1BkRE1HaWk2NXc5b1VIdU41SS9EYjVBSVhwWWtpVkNENENJQ2px
      OEVLaGFVVllOZ0RTCjRQZXdQVmxkeEs5M3NUMjRkY3NZTFY4b2RyVUwKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVRnhDMjMzY2k2TjIzVktIeVYwMEFEY2hOYVI4d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJNU1EUTFOVFV4V2hjTk1qVXhNREU0
      TURRMU5UVXhXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJHbGVOdG1PcGFsKzJoYzJST2VROUNzN2lreGRqaHJsSkk2YzM3by9KM3NLRUhkdCtFb2gK
      WDlBUjJZUFY1bFZHNXprcU9IV05jSll2aEJCVUxNR1A4VTJqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2tYb0h3cmtvbmxkNm9J
      aU5iaktScDdEeVZWekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQWc5ejhqc21xOU13aUVhWVps
      U1ZSYTBpb3l0ZUlrUFpub3k1N09relAKZnVnQ0lIZjZOVjFnN2UwaHlCN2ZuQm9oMDJaa09Tb2xn
      RnNtcWFQV1JmYVlSZWs4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOwoLRW5k
      b3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyoG
      QWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqCEgoNQ29uc2Vu
      c3VzVHlwZRLwERLlEQoIZXRjZHJhZnQS2BEKwREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCK
      NxrPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQVRDQ0FxZWdBd0lCQWdJVUc3aHRk
      MVZZdUNJZ3BwQVQ4MEQyVlRPTVEwY3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURW
      UVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpI
      aGNOTWpJeE1qSTVNRFV3TVRBd1doY05Nak14TWpJNU1EVXdOakF3V2pCeE1Rc3dDUVlEVlFRR0V3
      SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3
      ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNt
      VnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkNBQVRxSFdtQTN6bm93NnlsQkNSNWs4ZE5RYXNWCmRDc1YwQmRnYWtOVkRwejR2MnZIcTNpVTRQ
      RWxHYXdwMXMwaEQxRE9qTU5KZ3l5N0NtZkFOdkhnVFNlNG80SUIKTGpDQ0FTb3dEZ1lEVlIwUEFR
      SC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJn
      TlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlF2c1U4K1h0emlBZTUyOUF3dGRlUHR0L2lYClhq
      QWZCZ05WSFNNRUdEQVdnQlNrWG9Id3Jrb25sZDZvSWlOYmpLUnA3RHlWVnpBOUJnTlZIUkVFTmpB
      MGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHRzl5WkdWeVpYSXhMbk4xY0hC
      c2VXTm9ZV2x1TFc1bApkREJzQmdncUF3UUZCZ2NJQVFSZ2V5SmhkSFJ5Y3lJNmV5Sm9aaTVCWm1a
      cGJHbGhkR2x2YmlJNklpSXNJbWhtCkxrVnVjbTlzYkcxbGJuUkpSQ0k2SW05eVpHVnlaWEl4TG5O
      MWNIQnNlV05vWVdsdUxXNWxkQ0lzSW1obUxsUjUKY0dVaU9pSnZjbVJsY21WeUluMTlNQW9HQ0Nx
      R1NNNDlCQU1DQTBnQU1FVUNJUURXdFRxRksrQWpubG83clYrMQpFRzU1NVg2OTBzbEFCVWxvSHk5
      NnI0WklSd0lnQVp0Ynd5bEp4SnNacHJiZjZkYTFOdnMzVGxoSlA0aEsyUy9kCjZ0YlpLS2s9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURBVENDQXFlZ0F3SUJBZ0lVRzdodGQxVll1Q0lncHBBVDgwRDJWVE9NUTBjd0NnWUlLb1pJemow
      RUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1
      emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJNU1EVXdNVEF3V2hjTk1qTXhNakk1TURV
      d05qQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRN
      dlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21W
      eU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdj
      cWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVHFIV21BM3pub3c2eWxCQ1I1azhkTlFhc1YKZENz
      VjBCZGdha05WRHB6NHYydkhxM2lVNFBFbEdhd3AxczBoRDFET2pNTkpneXk3Q21mQU52SGdUU2U0
      bzRJQgpMakNDQVNvd0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVG
      QndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUXZzVTgr
      WHR6aUFlNTI5QXd0ZGVQdHQvaVgKWGpBZkJnTlZIU01FR0RBV2dCU2tYb0h3cmtvbmxkNm9JaU5i
      aktScDdEeVZWekE5QmdOVkhSRUVOakEwZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1
      WlhTQ0dHOXlaR1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVsCmREQnNCZ2dxQXdRRkJnY0lBUVJn
      ZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwYkdsaGRHbHZiaUk2SWlJc0ltaG0KTGtWdWNtOXNiRzFs
      Ym5SSlJDSTZJbTl5WkdWeVpYSXhMbk4xY0hCc2VXTm9ZV2x1TFc1bGRDSXNJbWhtTGxSNQpjR1Vp
      T2lKdmNtUmxjbVZ5SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRRFd0VHFGSytBam5sbzdy
      VisxCkVHNTU1WDY5MHNsQUJVbG9IeTk2cjRaSVJ3SWdBWnRid3lsSnhKc1pwcmJmNmRhMU52czNU
      bGhKUDRoSzJTL2QKNnRiWktLaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQ
      ChgBIAUogICAChoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4K
      DEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZB
      ZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0I
      AxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMi
      KgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zEr0vCgtD
      b25zb3J0aXVtcxKtLxLiLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsguErEXCg9tYW51ZmFjdHVy
      ZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVUWFjUE9NR3U1Ym8wek1VcDkzeEhU
      YldhUm4wd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhN
      akk1TURRMU5qVTRXaGNOTWpVeE1ERTRNRFExTmpVNFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBN
      QTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpE
      RTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGRE
      QlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSlp1NndUNDNHYTJIUVNGTzdnMXFw
      TklVNjlUeXpkL1dYaXUKaGdoN0xjRDE2VTVFU2NGVHh2TmQ4Rm00Y0NJQjhvd21vMkxxMzdzTzJn
      NG0yU29ReWJtalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlQ2UVFqUGd2VUp3LzlBCkJVRXh4NHh0REwrZGtEQUtCZ2dxaGtqT1BR
      UURBZ05JQURCRkFpQk5PZTFzeUxZUTNHdjBBSklsTzJxbURrOTAKdjNycWY4bUd4d2oyelB5Wndn
      SWhBUFBFUW9wQysvUDRZamtIREhuRlpPMms2VjIrbnhjNEw5cXBZckFYMnJGawotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERURDQ0Fy
      ZWdBd0lCQWdJVVFTOGozdlM0MlE2dk9NV3UxVkhHY2toMmpITXdDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TWpJNU1EVXdNekF3V2hjTk1qTXhNakk1TURV
      d09EQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRR
      dlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldG
      a2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtC
      dFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdB
      RU01WWFXVnlZdlJ3T21VY2ZDR1lvbDRFVGtYOU5OYWxFRklDYUhzYXNWYlBCcUk4bWpyTWIKTmNK
      U1BDaENLTmdnalVOcEZyUXNhZDFaQUkvcUtVYkpzYU9DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FF
      QXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUm9iL2FFbDNyMnBEeHRwUmJn
      eG1VcVExVjI3REFmCkJnTlZIU01FR0RBV2dCVDZRUWpQZ3ZVSncvOUFCVUV4eDR4dERMK2RrREFr
      QmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDRORGcyT1RoaU5HTmtMVFExZWpZNU1JR1hCZ2dx
      QXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZr
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5
      SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVs
      ZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRQpBaUE3
      NkJpa24raVd3dGNJN2lnS1R1ckIwWk9KNnRRbkNVSEk5UmFLdjZMM21nSWdZZmFHQTZEWmIraytU
      U0JICnBXQU5PcVg2cHZWSFRUZ0JPeEFrVUJvU3J0RT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEREND
      QWJLZ0F3SUJBZ0lVUWFjUE9NR3U1Ym8wek1VcDkzeEhUYldhUm4wd0NnWUlLb1pJemowRUF3SXcK
      WkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhM
      bTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakk1TURRMU5qVTRXaGNOTWpVeE1ERTRN
      RFExTmpVNFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdE
      UVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dB
      MVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdT
      TTQ5QXdFSEEwSUFCSlp1NndUNDNHYTJIUVNGTzdnMXFwTklVNjlUeXpkL1dYaXUKaGdoN0xjRDE2
      VTVFU2NGVHh2TmQ4Rm00Y0NJQjhvd21vMkxxMzdzTzJnNG0yU29ReWJtalFqQkFNQThHQTFVZApF
      d0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlQ2UVFqUGd2
      VUp3LzlBCkJVRXh4NHh0REwrZGtEQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQk5PZTFzeUxZUTNH
      djBBSklsTzJxbURrOTAKdjNycWY4bUd4d2oyelB5WndnSWhBUFBFUW9wQysvUDRZamtIREhuRlpP
      Mms2VjIrbnhjNEw5cXBZckFYMnJGawotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZB
      ZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoG
      QWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1Aa
      BkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJNU1AQ
      ARoGQWRtaW5zKgZBZG1pbnMSthYKCmNhcnJpZXJNU1ASpxYawxQKA01TUBK7FBKwFBKtFAoKY2Fy
      cmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJ
      VVZUdmdnSzQ2TVQ2ZzZ1eW9weUMzN0wvcDdwNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFl
      RncweQpNakV5TWprd05EVTRNRFphRncweU5URXdNVGd3TkRVNE1EWmFNRm94Q3pBSkJnTlZCQVlU
      QWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRH
      QTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJDNm82TVZUS1VBZE9RVG9ZU1dYUER3TDRM
      bXlLTlZJUHU0RGNROEJXaGRYM2ZZRGJIVlhoblFEWDNueTFkCko2WktkL3EzWEdUOWxpR0xVcHlr
      N1FoYm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFk
      QmdOVkhRNEVGZ1FVbnBGWUFzUGxqcmFuRVZ3NzR6aVB0cGVIc0Vrd0NnWUlLb1pJemowRQpBd0lE
      U0FBd1JRSWdXTTBnOXN3YUtURXVLVEFWcWVQczJJNkExS28vejE5ZERMeFZUTG14US9RQ0lRQ29a
      c3BOCldHc2xzQ0JEOWUxRmoyTzRYeWlZS1h2OVhJbVdTQ2FEQVRqblZ3PT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdqQ0NBcFNn
      QXdJQkFnSVVjaG5MWjRnTlNKMXBQUUVIdk1tUktPTGl6VXN3Q2dZSUtvWkl6ajBFQXdJdwpXakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlM
      VzVsZERBZUZ3MHkKTWpFeU1qa3dOVEEyTURCYUZ3MHlNekV5TWprd05URXhNREJhTUhneEN6QUpC
      Z05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9C
      Z05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnlj
      bWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQ0FBUVZTTFZrNHJHTkNURDExTVh5eW9rMgpPQmJFRnRIcmVhSUdC
      TmkxZ0Q3WUUzN1A4RUhuVDdsNjZYZjhzZzg1Wk9VYzR4a1p2NHI2eGZaSXNEUEg0VW1lCm80SUJH
      RENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JC
      WUUKRkdhdUZ2bC9FMDZvcWRjWUswUEYvQ1pGbGdwQU1COEdBMVVkSXdRWU1CYUFGSjZSV0FMRDVZ
      NjJweEZjTytNNApqN2FYaDdCSk1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFZrT0RRMU9U
      WmtObUl0T0RSd1ltTXdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1Gakxt
      bHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIy
      NGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNt
      bGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFNB
      QXdSUUloQUtUc2E4b2tLYy90czNZcURGaWl3bzVPNWNlUW9wdHJRam9Ya1p3SzdKNVAKQWlBOW1T
      Z1BqUmZlc2lwblpGbUU4cGlEeDErbXhFaGFBYXpnUUN3bDlleWR5dz09Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVZUdmdnSzQ2TVQ2ZzZ1eW9weUMzN0wvcDdwNHdDZ1lJS29a
      SXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1
      allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV5TWprd05EVTRNRFphRncweU5URXdNVGd3TkRV
      NE1EWmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdO
      VkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJF
      dVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVJDNm82
      TVZUS1VBZE9RVG9ZU1dYUER3TDRMbXlLTlZJUHU0RGNROEJXaGRYM2ZZRGJIVlhoblFEWDNueTFk
      Cko2WktkL3EzWEdUOWxpR0xVcHlrN1FoYm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRH
      QTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVbnBGWUFzUGxqcmFuRVZ3NzR6aVB0cGVI
      c0Vrd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdXTTBnOXN3YUtURXVLVEFWcWVQczJJNkExS28v
      ejE5ZERMeFZUTG14US9RQ0lRQ29ac3BOCldHc2xzQ0JEOWUxRmoyTzRYeWlZS1h2OVhJbVdTQ2FE
      QVRqblZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIc
      EggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhII
      EgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRp
      b25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggK
      BlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZB
      ZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3
      MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRf
      MxIAGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVy
      cxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZB
      ZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
