apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIOBNH4IkaQYrfBWPsdZlyFsigqxBdTTvJ0Pg4+pE6/oWEppeCpdeCpReCngKWggBEAEaBgi6
      6vqYBiIKc3lzY2hhbm5lbCpANTVhMDMwMzllYWEwZDc1YjlmMzM5NzcxMjQwMDA5ZjU2NWZmYWVl
      ZjcyZmEyN2FiYmE0NjdiMDVhMmQ2NmE4ZRIaEhj6V+PUjZrgY/sVAmymDo6kcvM5yrRxf1ESl10K
      lF0SkV0SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVWFVuNGVlV1dnUXZZQUxpSFlhMExpa0lTUldFd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFeU1EUXhNRFV5V2hjTk1qVXdOekF5TURReE1EVXlX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJNNHQ3
      T08yVGFQUlh2dWVQcmVtcVpML3hNYnNYaDN5ZjFtTEg1RHlGRThYV3BVRjNWemYKRUtoWCtBSGNj
      b3h0TGRCVjYvQjNZN2lRUjYvMUV5bnhlWjJqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUnQwOCsxVTk1a3M4SEZVSEpvTGFrOWU0
      aVU3ekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBRWpjTEE3b2NwSUEzL0FPUjFHZUNsVzRXd0RM
      eTYzL2JqdGkxOFlPVFMKTmdJaEFQQnVXalJjZ1k5RjZHTW5xTE5zUk1XM3pFRVRTNVBGSnpob2JG
      YlRvRnEzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVUUhMa2IybGd5YUFFUmhOUUo0d3QwK3FOc3Fnd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFeU1EUXhPREF3V2hjTk1q
      TXdPVEV5TURReU16QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFK0lVUy9jR3ZNNk82U3VneE1QTldaZlNTMnZ4
      K0x3S2EKdTBUYzJWMnBJTS90WFR4N1pDUW4vQmNPSE04ZTEzbXFEZTFyV3NYd2xKRklXR2hSQjBM
      NmlxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRWkk1VmgvVS9zCnVjVlY3aUNvNDlYWi9RbjNLakFmQmdOVkhTTUVHREFXZ0JS
      dDA4KzFVOTVrczhIRlVISm9MYWs5ZTRpVTd6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xXaGlhMk5zTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnUDRoSzByZndJNG04QzdJa013VDBmODUrWUJuenFra2szRklBeXZXcnFYSUNJQk9z
      RmdRdjV3ZWMzamVICjNOVzd2Ym1PT2hIUm9vOHFEb2VKWUdIdys4ekIKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVWFVuNGVlV1dnUXZZQUxpSFlhMExpa0lTUldFd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFeU1EUXhNRFV5V2hjTk1qVXdOekF5
      TURReE1EVXlXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJNNHQ3T08yVGFQUlh2dWVQcmVtcVpML3hNYnNYaDN5ZjFtTEg1RHlGRThYV3BVRjNWemYK
      RUtoWCtBSGNjb3h0TGRCVjYvQjNZN2lRUjYvMUV5bnhlWjJqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUnQwOCsxVTk1a3M4SEZV
      SEpvTGFrOWU0aVU3ekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBRWpjTEE3b2NwSUEzL0FPUjFH
      ZUNsVzRXd0RMeTYzL2JqdGkxOFlPVFMKTmdJaEFQQnVXalJjZ1k5RjZHTW5xTE5zUk1XM3pFRVRT
      NVBGSnpob2JGYlRvRnEzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGoISCg1Db25zZW5zdXNUeXBlEvAREuUR
      CghldGNkcmFmdBLYEQrBEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3Gs8ILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVVE1NOXhjbmNiZlVEWENBRDZI
      V3JLalUxeUE0d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFeU1E
      UXhPREF3V2hjTk1qTXdPVEV5TURReU16QXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUWt4cnhIWnZT
      c3FDRnN6aEFPMXp1MWNabjcKVnhhWUttSFMvU3ZFck9Lam4zbDF1UXZFaEM1RXpmSkJwK2pSSlk5
      OUdJdDhOZWo2QWlmalNhcmszOFdnbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCU0FOeUFzWkNpbytPT29nbGhqTlo0TTlqWloKc1RBZkJnTlZIU01FR0RB
      V2dCUnQwOCsxVTk1a3M4SEZVSEpvTGFrOWU0aVU3ekEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1
      ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1
      SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmho
      YVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBd1JBSWdSendRc2Jrdm9ucnpBVE9wClFGdnRHK0NFNlR2MlRYZ01OZ2k5YncxN0xxTUNJQ1Fh
      em45NWVjTEdtUWlEdDViZkh1UGJDbEVJMmY5akIzT3YKMmM1S3VKZE4KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQoizwgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREFqQ0NBcW1nQXdJ
      QkFnSVVUTU05eGNuY2JmVURYQ0FENkhXcktqVTF5QTR3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0Zw
      YmkxdVpYUXcKSGhjTk1qSXdPVEV5TURReE9EQXdXaGNOTWpNd09URXlNRFF5TXpBd1dqQnhNUXN3
      Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3
      RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFE
      RXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DQUFRa3hyeEhadlNzcUNGc3poQU8xenUxY1puNwpWeGFZS21IUy9TdkVyT0tq
      bjNsMXVRdkVoQzVFemZKQnAralJKWTk5R0l0OE5lajZBaWZqU2FyazM4V2dvNElCCk1EQ0NBU3d3
      RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYK
      QlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTQU55QXNaQ2lvK09Pb2dsaGpO
      WjRNOWpaWgpzVEFmQmdOVkhTTUVHREFXZ0JSdDA4KzFVOTVrczhIRlVISm9MYWs5ZTRpVTd6QS9C
      Z05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnla
      WEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJ
      anA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2li
      M0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnla
      WElpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ1J6d1FzYmt2b25yekFUT3AKUUZ2dEcrQ0U2
      VHYyVFhnTU5naTlidzE3THFNQ0lDUWF6bjk1ZWNMR21RaUR0NWJmSHVQYkNsRUkyZjlqQjNPdgoy
      YzVLdUpkTgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZB
      ZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0I
      AxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMi
      KgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zEr0vCgtD
      b25zb3J0aXVtcxKtLxLiLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsguErEXCg9tYW51ZmFjdHVy
      ZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVUi92VWVYd1o1ckhLMHljNndUeVdH
      R0V2RlRFd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdP
      VEV5TURReE1qVXpXaGNOTWpVd056QXlNRFF4TWpVeldqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBN
      QTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpE
      RTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGRE
      QlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQjR3T3BhaFBseVc3dU5VUmY1YzRi
      QVgzcEh4bSs5cU1qS2EKL2daREYvNTIzU3ZxbHJjMk9sRTFHVTlKTFF0U1lmTUxha0l3Vk1XWnlT
      Z3JDRzZRRVM2alFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlI0OGg5T3JxNUJ1RGwvCkRJd0kyN0JjZzZJMk5qQUtCZ2dxaGtqT1BR
      UURBZ05JQURCRkFpQWx3Yk5FbmtnYTBlSVU2MFU2di9oajBnZ1MKTFJuTnN5dGFEZU8raTgrTkFB
      SWhBTmlBd0FjL1V4cy9JbGVJUGhkdk85ajVXam10TVE1bExVeHVEdXpwUEFrVAotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERVRDQ0Fy
      ZWdBd0lCQWdJVWJPbElGT1AyVkFJWW1vMGZDMEp2Z2tYNi8xNHdDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3T1RFeU1EUXlNREF3V2hjTk1qTXdPVEV5TURR
      eU5UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRR
      dlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldG
      a2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtC
      dFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdB
      RU5sZ2lUWHB4NFBGME4zb3hKLzhGWGR4MW1QOEhldmJnWExIVGV5YURQMkU2NEZXbUVLaVMKSGox
      MXNZdUhIOWZCeE1wdzFzdjkwbXR2R3BpM2xBSTVYS09DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FF
      QXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUkd6NjBIdlkraURQdGhwcU1n
      KzRQb1haTk5TREFmCkJnTlZIU01FR0RBV2dCUjQ4aDlPcnE1QnVEbC9ESXdJMjdCY2c2STJOakFr
      QmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMV1JuZW5Oa01JR1hCZ2dx
      QXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZr
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5
      SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVs
      ZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRgpBaUVB
      L0dCZFcxQkNvak1xQjA3RG5udGtsOWdMYzNHTWlScUVTYzhpTmxISHVab0NJRFJyRXYrNDJpTkJW
      bDhtCmpHN1Uxd2Eza01hZnVSeS9SdzZMRGF1Zk1GdEwKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEREND
      QWJLZ0F3SUJBZ0lVUi92VWVYd1o1ckhLMHljNndUeVdHR0V2RlRFd0NnWUlLb1pJemowRUF3SXcK
      WkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhM
      bTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPVEV5TURReE1qVXpXaGNOTWpVd056QXlN
      RFF4TWpVeldqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdE
      UVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dB
      MVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdT
      TTQ5QXdFSEEwSUFCQjR3T3BhaFBseVc3dU5VUmY1YzRiQVgzcEh4bSs5cU1qS2EKL2daREYvNTIz
      U3ZxbHJjMk9sRTFHVTlKTFF0U1lmTUxha0l3Vk1XWnlTZ3JDRzZRRVM2alFqQkFNQThHQTFVZApF
      d0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlI0OGg5T3Jx
      NUJ1RGwvCkRJd0kyN0JjZzZJMk5qQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQWx3Yk5FbmtnYTBl
      SVU2MFU2di9oajBnZ1MKTFJuTnN5dGFEZU8raTgrTkFBSWhBTmlBd0FjL1V4cy9JbGVJUGhkdk85
      ajVXam10TVE1bExVeHVEdXpwUEFrVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBABGgZBZG1p
      bnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1Aa
      BkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQ
      GgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1T
      UBoGQWRtaW5zKgZBZG1pbnMSthYKCmNhcnJpZXJNU1ASpxYawxQKA01TUBK7FBKwFBKtFAoKY2Fy
      cmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJ
      VUNIZ0xtQmIzd2ZYRC9WQWlBZmZqcEcvQU1JZ3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFl
      RncweQpNakE1TVRJd05ERTBOVE5hRncweU5UQTNNREl3TkRFME5UTmFNRm94Q3pBSkJnTlZCQVlU
      QWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRH
      QTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVI3TlRzZGV5dzlYaEdPdys4M00zYklsY25o
      eEtDTTdFSGt6ZlpXQVNkUlJodVlGdGpmNG90ZmlGYU5USWpPCmZ3MzRYa0lNRTFsbFhsRFRPZkZ3
      aEovRG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFk
      QmdOVkhRNEVGZ1FVMExMdGZVWWpuZlJLL2MxNHkrYURIVi9SRU04d0NnWUlLb1pJemowRQpBd0lE
      U0FBd1JRSWdhQUJOWkFkZk9kWVUrZlYwWEsyTksweVU5dTVRREFtdlZmUDArUVpzdXlFQ0lRRER3
      YUIyCmlXNkxhN0NBLzA0YU1tNXM1ZTlzZUl0THNzdEhDZEZOTm1mOEtnPT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdqQ0NBcFNn
      QXdJQkFnSVVBVjBad1FsOGNvODlJQjU4bWJ5clJGSUFVZmt3Q2dZSUtvWkl6ajBFQXdJdwpXakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlM
      VzVsZERBZUZ3MHkKTWpBNU1USXdOREl5TURCYUZ3MHlNekE1TVRJd05ESTNNREJhTUhneEN6QUpC
      Z05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9C
      Z05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnlj
      bWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQ0FBUlZTYzFuU0VuN3Znd2FlVWM2b2hTZgp1Zkh0NGVjOTRJOWN3
      emk3QmxwVDdkQ3JHMERWMHhjc1Fndkx6TmNROXEzR2VZUW5mb1llVUwvaWthYkV0SDgrCm80SUJH
      RENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JC
      WUUKRlBEMzhlUXg2bE5EbUtWbSt2alQyWkJnTGw5RE1COEdBMVVkSXdRWU1CYUFGTkN5N1gxR0k1
      MzBTdjNOZU12bQpneDFmMFJEUE1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFprTkdNMlpq
      YzJaR1l0YUdKcmNqWXdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1Gakxt
      bHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIy
      NGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNt
      bGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFNB
      QXdSUUloQVByb3pwUE5wdUxUNVFpYVlUTDJxT2JXYVdJNnAvZnRPVVlQYkN3cnpxRTkKQWlBazh0
      bE56U3NkcmtIK3NhMmorZWtjd2s3b3VXbFFxRU50RzkvV3pqeU5lQT09Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUNIZ0xtQmIzd2ZYRC9WQWlBZmZqcEcvQU1JZ3dDZ1lJS29a
      SXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1
      allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakE1TVRJd05ERTBOVE5hRncweU5UQTNNREl3TkRF
      ME5UTmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdO
      VkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJF
      dVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVI3TlRz
      ZGV5dzlYaEdPdys4M00zYklsY25oeEtDTTdFSGt6ZlpXQVNkUlJodVlGdGpmNG90ZmlGYU5USWpP
      CmZ3MzRYa0lNRTFsbFhsRFRPZkZ3aEovRG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRH
      QTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVMExMdGZVWWpuZlJLL2MxNHkrYURIVi9S
      RU04d0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdhQUJOWkFkZk9kWVUrZlYwWEsyTksweVU5dTVR
      REFtdlZmUDArUVpzdXlFQ0lRRER3YUIyCmlXNkxhN0NBLzA0YU1tNXM1ZTlzZUl0THNzdEhDZEZO
      Tm1mOEtnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIzCgdSZWFkZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAES
      GhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIG
      CAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhII
      EgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRp
      b25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggK
      BlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZB
      ZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3
      MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRf
      MxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
