apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIK+UlSA6SDka/PQl2k64QTGSuPCThDCqOilh9nKqcjMMErBeCq1eCqpeCngKWggBEAEaBgjg
      n+uZBiIKc3lzY2hhbm5lbCpAMTg5ZWM3NTY4M2U1YjQ5NjZhNWFkOTk3YTczYmU5MjQ4YmFiYjBl
      ZDk4YjdiZWFjOTIyMDM5YWE1OTI1ZTBlMxIaEhhBYBsmCrnW3DMTAFyn6MeBgjec8EUBoncSrV0K
      ql0Sp10SmysKB09yZGVyZXISjysS0hYKDnN1cHBseWNoYWluTVNQEr8WGssUCgNNU1ASwxQSuBQS
      tRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVTHlPUHVVcWVtNTkvbGxVRjlCS3pDZ3I2VXc0d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBek1URTBOelV6V2hjTk1qVXdOekl6TVRFME56VXpX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJKM1Bo
      NStubklOMUdkRG5peHBaZk1VTDMrTUZSOFFKZXQ5ZzdMQzRwR0VGeFJzZE5tbFQKdDR0VlNZVGhW
      azB2Y1hGZ0h0Wlh3OFAwSE55cTFiNWhaaHVqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0hYVmZRVVZ0VjNsWXlqeG80VnNPVm1x
      UDN1VEFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTdxM3dkQ3pCQklhMmJKazgvdGdIaVR5cWIw
      aDVkb1lVdFZ4ZXFWQXUKVitrQ0lRRGQwdm0yNThSbG9LTmNaQlBHWnhqK20zNVZQeWJZZ0RlcFk5
      YjdmekpnMXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKiCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNFRDQ0FvaWdBd0lCQWdJVUcxQjJ1aVdqL0VqUEErM1p1K1c2cXlCQ2ww
      OHdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1EQXpNVEUxTlRBd1do
      Y05Nak14TURBek1USXdNREF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXF4UGF0NVY1Q3QxRHJvV0xwdGthbDQz
      L0haZEJHOCtuCm1rK09QWW8vTWE0SC9kREZWNnE1WXpNSkpnb0xIKzQ4eVQ1RkF4Ri9OMTZHODJs
      d0lDRUFEcU9DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUTJLaGhPRThMTApRb2JRRm8xME9teXpsZ3VEb0RBZkJnTlZIU01FR0RB
      V2dCU0hYVmZRVVZ0VjNsWXlqeG80VnNPVm1xUDN1VEFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDFOalkzWXpZM1ptWTNMVzFqY2pWdU1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFJ3QXcKUkFJZ2NDbC9RNFc4emZtZzJJam9GTVRVeUtYTlpXNUsvb0V0M0NmY04vemhQeEVD
      SUFwMGhuTkQxVmN5WElCTgpnZ1BKWkhKdVR4S0dFQi9rNzcrSVdqWTdKWmRLCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkr1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVUx5T1B1VXFlbTU5L2xsVUY5Qkt6Q2dyNlV3NHdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1EQXpNVEUwTnpVeldoY05NalV3
      TnpJek1URTBOelV6V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCSjNQaDUrbm5JTjFHZERuaXhwWmZNVUwzK01GUjhRSmV0OWc3TEM0cEdFRnhSc2RO
      bWxUCnQ0dFZTWVRoVmswdmNYRmdIdFpYdzhQMEhOeXExYjVoWmh1alFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNIWFZmUVVWdFYz
      bFl5anhvNFZzT1ZtcVAzdVRBSwpCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUE3cTN3ZEN6QkJJYTJi
      Sms4L3RnSGlUeXFiMGg1ZG9ZVXRWeGVxVkF1ClYra0NJUURkMHZtMjU4UmxvS05jWkJQR1p4aitt
      MzVWUHliWWdEZXBZOWI3ZnpKZzF3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlu
      cyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1p
      bnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zKgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooS
      Cg1Db25zZW5zdXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0EIo3GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQXFtZ0F3SUJB
      Z0lVZXcrZjF1aDE5N0VuaFJvRFdJRmJlSzc5SXBFd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJp
      MXVaWFF3CkhoY05Nakl4TURBek1URTFOVEF3V2hjTk1qTXhNREF6TVRJd01EQXdXakJ4TVFzd0NR
      WURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0Rn
      WURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4
      aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBUWlvUDZPTG1mRXVrb3Vsa2g0eXNRWWl6aUMKSU5tdFU5ZmlBVmRxQ29SeTB3
      WUQvdFI3RTZqM3pwOEV0SVlnSit4T0FlMGVBS0pXcXlVZWNidmRjWGpybzRJQgpNRENDQVN3d0Rn
      WURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJR
      Y0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUjhNbnl6ODVsV1FGUXk1ZFB1Ymx6
      eTRLRHEKRnpBZkJnTlZIU01FR0RBV2dCU0hYVmZRVVZ0VjNsWXlqeG80VnNPVm1xUDN1VEEvQmdO
      VkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJ
      eExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpw
      N0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNK
      a1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJ
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBSXkyTzZ4MW1kT0FQUnJaCk1kOVJSS3JSVHkx
      N3B4ZDVUcXgvajZBWDF2SDdBaUI3TWJmZkcxVTRWeThaUldOWDQ3a09FMkFscnhJUCsxRW0KRFg0
      eDNCU05NZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSURBekNDQXFtZ0F3SUJBZ0lVZXcrZjF1aDE5N0VuaFJvRFdJRmJlSzc5SXBF
      d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZ
      RFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBek1URTFOVEF3V2hj
      Tk1qTXhNREF6TVRJd01EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRF
      dU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFR
      TEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1
      ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUWlvUDZPTG1mRXVrb3Vsa2g0
      eXNRWWl6aUMKSU5tdFU5ZmlBVmRxQ29SeTB3WUQvdFI3RTZqM3pwOEV0SVlnSit4T0FlMGVBS0pX
      cXlVZWNidmRjWGpybzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFX
      TUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVk
      RGdRV0JCUjhNbnl6ODVsV1FGUXk1ZFB1Ymx6eTRLRHEKRnpBZkJnTlZIU01FR0RBV2dCU0hYVmZR
      VVZ0VjNsWXlqeG80VnNPVm1xUDN1VEEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dH
      Q0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kK
      YUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJ
      aXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhB
      SXkyTzZ4MW1kT0FQUnJaCk1kOVJSS3JSVHkxN3B4ZDVUcXgvajZBWDF2SDdBaUI3TWJmZkcxVTRW
      eThaUldOWDQ3a09FMkFscnhJUCsxRW0KRFg0eDNCU05NZz09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICA
      MRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxS
      ZXN0cmljdGlvbnMSCBoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJz
      GgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIX
      Eg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1p
      bnMqBkFkbWlucxLDLwoLQ29uc29ydGl1bXMSsy8S6C4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLO
      LhK7FwoPbWFudWZhY3R1cmVyTVNQEqcXGq8VCgNNU1ASpxUSnBUSmRUKD21hbnVmYWN0dXJlck1T
      UBKGBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVWM0M0t3
      YlRhUFlCSzM4cVNjcndEYmp5UHE2NHdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNR
      MGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURW
      UVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApj
      aTF1WlhRd0hoY05Nakl4TURBek1URTBPVFUwV2hjTk1qVXdOekl6TVRFME9UVTBXakJrTVFzd0NR
      WURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFky
      Z3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRX
      WmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQlBldWxZ
      V1llcWZwVFRVcE9sOC9pN1JDOTFtdUdlWTQrVlJSCnFITkMzRmdGY3FkUlRQbTNyQnVzZTdwTFVp
      cTd3V3RXOG5aa2FudUZWeVR2UkJpbmNhNmpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0Rn
      WURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJSOFVWRnVnU21teHNrWQpHcUhFaWJEQ0x1
      NnNlVEFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBMjIwT0xFQmhzUFIvcVBkYUpuRTFGWis0CjFG
      Mmt6Vk5XM0JlT0ZFT3pVamdDSVFDN3A2M2xVUUVPNjhLNStKaENWRXdTZ21Jb3BDSGNjVDZMcTFR
      REZvUnAKSEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlERURDQ0FyZWdBd0lCQWdJVUY3MXIzTzRVTlA1Z29WMC8zYjRSdkQ5VUpw
      UXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpY
      SXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TURBek1U
      RTFOekF3V2hjTk1qTXhNREF6TVRJd01qQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJn
      TlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRI
      VnlaWEl4SXpBTUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4
      dwpIUVlEVlFRRERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJCnpqMERBUWNEUWdBRVJtM2dTT1VXdHdxQ0hoWE5GcDNrWVFGRExSNnVMT0ppcDBr
      UDcvS2lBdzBKelFDSEdlL0IKV3gvbjhLN01jTjdmSGFkMWo3Uy9HdXpKK1M0S2JNR21JYU9DQVNJ
      d2dnRWVNQTRHQTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdR
      V0JCVFVhdFpTQklWajRPelBZTEJoMmwrcllpWHRNakFmCkJnTlZIU01FR0RBV2dCUjhVVkZ1Z1Nt
      bXhza1lHcUhFaWJEQ0x1NnNlVEFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1S
      bU9UYzJMWEI2WTJoc01JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1
      cGJtbDBJam9pZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1
      Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVB
      YldGdWRXWmgKWTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dx
      aGtqT1BRUURBZ05IQURCRQpBaUJDeCtTOGE3NENud3dPY09wNnBLbWQycWZ0RVA5VlBQRXJUR2pL
      NWtjNEJ3SWdLRDMyUkhTNkpVUkxnZ2ZYCnZpVlg0UlVLNC9LQXdqVlBqaU53R0E2OFVMTT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoYGLS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSUNEVENDQWJLZ0F3SUJBZ0lVYzQzS3diVGFQWUJLMzhxU2Nyd0RianlQ
      cTY0d0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAx
      Y21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5
      WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNREF6
      TVRFME9UVTBXaGNOTWpVd056SXpNVEUwT1RVMFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBH
      QTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFo
      Ym5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpN
      Qk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCUGV1bFlXWWVxZnBUVFVwT2w4L2k3UkM5
      MW11R2VZNCtWUlIKcUhOQzNGZ0ZjcWRSVFBtM3JCdXNlN3BMVWlxN3dXdFc4blprYW51RlZ5VHZS
      QmluY2E2alFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21N
      QjBHQTFVZERnUVdCQlI4VVZGdWdTbW14c2tZCkdxSEVpYkRDTHU2c2VUQUtCZ2dxaGtqT1BRUURB
      Z05KQURCR0FpRUEyMjBPTEVCaHNQUi9xUGRhSm5FMUZaKzQKMUYya3pWTlczQmVPRkVPelVqZ0NJ
      UUM3cDYzbFVRRU82OEs1K0poQ1ZFd1NnbUlvcENIY2NUNkxxMVFERm9ScApIQT09Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUS
      EwoPbWFudWZhY3R1cmVyTVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggB
      EgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYI
      ARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIG
      CAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1T
      UBKjFhq/FAoDTVNQErcUEqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVZTVTbTY1R1FpTUJNK0ROMSt1eVdicktYUURBd0Nn
      WUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZR
      UUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXdNRE14TVRVeE5UVmFGdzB5TlRBM01q
      TXhNVFV4TlRWYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6
      QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3
      d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFB
      VCt4Ylc3dmdYNkQxajE4dE1wY0dCRy9OVEdBYXZDMUVrK05IUTdqNzdydDBONXBHQkJaNUNBTlhL
      TzNKVG8KSldkSlpUbDhHUHBjZGsvN3M2c1VmM0hnbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFI
      L01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVSSGRUR3lBWnlLT01kVDdwUllK
      RWsyWTZrd2d3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFMTkxzQ0JMNGhNa2xZaDAxWkQxUEUr
      cDBjMk5JVDN2RjFnTzc1Zzl4VzlXQWlCZUF6RFQKN21uNGhiVFhPMmhBODNFUlNndy9ObjArNi85
      aG1uSkFxS3ZLRGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDN1RDQ0FwU2dBd0lCQWdJVVk4ZjFCMzZmeDBwM21IMS9veUNYTC9m
      NlB4WXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJj
      d0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV3TURNeE1UVTVNREJhRncw
      eU16RXdNRE14TWpBME1EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0
      MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFz
      VEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5
      Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSL1BqdlFILzdw
      aUdnUDhCZzlEVFJOCnZabnJUUUFXTzJEU2ZSRFZid0o4YU5ZbU55U0J2T0RqbXAyZXBxV1ZGbkpM
      MEZFTGJ6VWRyT2lCUUhVbno4NnIKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdH
      QTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpGQ1A3ZStPNWJLNDVpQ2hRYnluNm9iM2VzREZ0
      TUI4R0ExVWRJd1FZTUJhQUZFUjNVeHNnR2NpampIVSs2VVdDClJKTm1PcE1JTUNRR0ExVWRFUVFk
      TUJ1Q0dXTmhMWFJ2YjJ4ekxUWmtOR00yWmpjMlpHWXRibVJtTjNBd2dZMEcKQ0NvREJBVUdCd2dC
      QklHQWV5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUow
      Y25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNi
      V1Z1CmRFbEVJam9pUVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRh
      VzRpZlgwd0NnWUkKS29aSXpqMEVBd0lEUndBd1JBSWdOcXE1ZEN1QTFUZVY0NDZxdmtsTmpEaGR1
      VDJqN2dtb1MxdmlhL1ZEbDBNQwpJQ0JENkpDeXoyc3RHQ0c0c0FuUDNLSVg5THhqSHYrSjE2MW1w
      Rzc1dElGdAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVlNVNtNjVHUWlNQk0r
      RE4xK3V5V2JyS1hRREF3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5C
      Z05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZ
      WEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFd01ETXhN
      VFV4TlRWYUZ3MHlOVEEzTWpNeE1UVXhOVFZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApW
      UVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNt
      bGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkMKQUFUK3hiVzd2Z1g2RDFqMTh0TXBjR0JHL05UR0FhdkMxRWsrTkhRN2o3
      N3J0ME41cEdCQlo1Q0FOWEtPM0pUbwpKV2RKWlRsOEdQcGNkay83czZzVWYzSGdvMEl3UURBUEJn
      TlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVVJI
      ZFRHeUFaeUtPTWRUN3BSWUpFazJZNmt3Z3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQUxOTHND
      Qkw0aE1rbFloMDFaRDFQRStwMGMyTklUM3ZGMWdPNzVnOXhXOVdBaUJlQXpEVAo3bW40aGJUWE8y
      aEE4M0VSU2d3L05uMCs2LzlobW5KQXFLdktEZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZB
      ZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZB
      ZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlu
      cyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZB
      ZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIE
      EgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGi0K
      GUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFk
      ZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMaJgoQSGFz
      aGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1p
      bnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRl
      cnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
