apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIJ+BLVzLqT1Lvg2co/Y03wkahsusYc+RFaHpkETqy0SIEo5eCoteCoheCngKWggBEAEaBgjf
      84qZBiIKc3lzY2hhbm5lbCpAODkyNmU5NTg0NjAyNmE3MzBlOWM3M2VmMzI2NWU4MTFjYjVkYTg1
      YThlNDA2NmI4MDBlNDBiY2I5MjUwZDZjYhIaEhjhXKkGEbZ1IowYXDcfw2e6PKEMyt8NwOISi10K
      iF0ShV0SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVYWpOeVBWckZQUDBMYVp0QzIwUUFLTmNyS0FRd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFMU1EVXhPVE0xV2hjTk1qVXdOekExTURVeE9UTTFX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJOT0dI
      UHpJa2NXNEJEUHZsWFVyMUdMOVpOUnAyOGlXNkRMaFdpbmNDVk1zL3AyazBnaFMKOERPREJmSG83
      T0NNZDlGaGlOUmRjMG5aZXg4UFJ5NERJSmlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUmQvd3dSRHVjNkpVdHpqdXcrSjdjRFZP
      UUcwekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCb21maFhEdEVxQ2F4TjZNNGlOaEp4OGRvUE5h
      QmpBM21VaG5XNkRPdVgKalFJaEFMRnE5ZVdITGx3V1I4OXNQSUZqc0hHajBzUVJtRVY5b2d2ZTd6
      ejRNbW1VCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVQlNkSkY4RzJqR3JwM2pad2h1NEJiTGV3NjhZd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFMU1EVXlOekF3V2hjTk1q
      TXdPVEUxTURVek1qQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFbEwxd3ZyUFVXaUJ3UnlWbUZOOFBGOExRd1JR
      OWd6YWEKb3BHK3R4M09ta2RyNkpvamRLcDY4c0pZN2NWTlJIbEMyaVF4MHVYR1lmeUZLdHBKdld2
      aVRLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSVXFJS2FKZVZ1CmhNUzdzcmJUR2taZk9hamRhakFmQmdOVkhTTUVHREFXZ0JS
      ZC93d1JEdWM2SlV0emp1dytKN2NEVk9RRzB6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xUaHRPWE5uTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnTUdta1duQ0Q0dDJLaXFoVEJiakx0NXI3TVIzb1l2M2twTXBpV0ZURDMvRUNJRi8x
      VjRwVEFpSkpJeUlQCmFnSFJJOFZFQjEwUHhQc0hPK04vd3lCL0tSREwKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVYWpOeVBWckZQUDBMYVp0QzIwUUFLTmNyS0FRd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFMU1EVXhPVE0xV2hjTk1qVXdOekEx
      TURVeE9UTTFXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJOT0dIUHpJa2NXNEJEUHZsWFVyMUdMOVpOUnAyOGlXNkRMaFdpbmNDVk1zL3AyazBnaFMK
      OERPREJmSG83T0NNZDlGaGlOUmRjMG5aZXg4UFJ5NERJSmlqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUmQvd3dSRHVjNkpVdHpq
      dXcrSjdjRFZPUUcwekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCb21maFhEdEVxQ2F4TjZNNGlO
      aEp4OGRvUE5hQmpBM21VaG5XNkRPdVgKalFJaEFMRnE5ZVdITGx3V1I4OXNQSUZqc0hHajBzUVJt
      RVY5b2d2ZTd6ejRNbW1VCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0
      aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGoIS
      Cg1Db25zZW5zdXNUeXBlEvAREuURCghldGNkcmFmdBLYEQrBEQoYb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0EIo3Gs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJB
      Z0lVSmNCOHVjQ1pFVCtrMDQrWm9ZZmx1Zlkzckswd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJp
      MXVaWFF3CkhoY05Nakl3T1RFMU1EVXlOekF3V2hjTk1qTXdPVEUxTURVek1qQXdXakJ4TVFzd0NR
      WURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0Rn
      WURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4
      aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBUTlRZUNBSzA0TlU3UmJrMWhpUENWT3NoY3QKM3JMdnpoL2d3T1RXYlQvMDcr
      OTdBNkZSUCtpVUE5dFJ5NzNCemxnYnZpY1JpVDNROHEweWNscXc2bndJbzRJQgpNRENDQVN3d0Rn
      WURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJR
      Y0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVDNlbWZqS1FYM3pQYU1BUFlSVHNt
      cnlHVGgKN3pBZkJnTlZIU01FR0RBV2dCUmQvd3dSRHVjNkpVdHpqdXcrSjdjRFZPUUcwekEvQmdO
      VkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJ
      eExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpw
      N0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNK
      a1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJ
      aWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdYbW9QRS93WEI2RjNpaFFWCjFZY0c4aVFOeDNw
      SUJzYjNEMTZySHFMR3NMQUNJQWV6TzVUdGxnaThvNyt1TXNOSzdQMzJkT3JGNEMwTXB1M1QKMGdV
      QktqU2IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoizwgtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJREFqQ0NBcW1nQXdJQkFnSVVKY0I4dWNDWkVUK2swNCtab1lmbHVmWTNySzB3Q2dZ
      SUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFR
      RERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdPVEUxTURVeU56QXdXaGNOTWpN
      d09URTFNRFV6TWpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRB
      dkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdk
      dmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFROVFlQ0FLMDROVTdSYmsxaGlQQ1ZP
      c2hjdAozckx2emgvZ3dPVFdiVC8wNys5N0E2RlJQK2lVQTl0Unk3M0J6bGdidmljUmlUM1E4cTB5
      Y2xxdzZud0lvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFH
      Q0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FX
      QkJUM2VtZmpLUVgzelBhTUFQWVJUc21yeUdUaAo3ekFmQmdOVkhTTUVHREFXZ0JSZC93d1JEdWM2
      SlV0emp1dytKN2NEVk9RRzB6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxq
      YUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29E
      QkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1
      Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lh
      R1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ1htb1BF
      L3dYQjZGM2loUVYKMVljRzhpUU54M3BJQnNiM0QxNnJIcUxHc0xBQ0lBZXpPNVR0bGdpOG83K3VN
      c05LN1AzMmRPckY0QzBNcHUzVAowZ1VCS2pTYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChIS
      CgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZB
      ZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFk
      ZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMa
      BkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5zErEvCgtD
      b25zb3J0aXVtcxKhLxLWLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtErwuErEXCg9tYW51ZmFjdHVy
      ZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVZkhrTGpDOVlqMk5IT0lpc3RmNTRI
      eGc3eVRrd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdP
      VEUxTURVeU1UTTNXaGNOTWpVd056QTFNRFV5TVRNM1dqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBN
      QTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpE
      RTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGRE
      QlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQk4xd3d6NElrRlIyKzdjTk1hZ0VH
      c2gxQVFjODJZaGZNRmYKcjlvcjNtMm5XUkRvSlNyZ2pDUzhHRk1sSkpaSVZFTUZ1YXcydXUvQ1NS
      K1lCRmFLd25HalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlFVUUFqSlVybVF4NkZTCk9UdDIyaFFRRzZlMVp6QUtCZ2dxaGtqT1BR
      UURBZ05JQURCRkFpRUFqMVdrZjlqdmRCbVFIN1I2RkdNM3FacVMKOTBzLzc5NklmMnQxUytwNkx4
      QUNJRnFiU3czblhUbUZmVFlLelc3cHdmN0psOWd4a0xqdW0zMXBLWEdNYjRvdAotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERVRDQ0Fy
      ZWdBd0lCQWdJVVhvQVdFVE04M0JRazh6U1VrT0ltUWdFT2FLQXdDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3T1RFMU1EVXlPVEF3V2hjTk1qTXdPVEUxTURV
      ek5EQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRR
      dlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldG
      a2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtC
      dFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdB
      RTJYVW81a01Tc3krd1pOMkZFWE81OHBiNjhCc1puR1NMY0ZiQU93am9UeFQ4Sm00czkrUzkKb1Bn
      QUl6K0I3U0d4bE05T09yclE0ZmpZQ01nUzk4WnV4S09DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FF
      QXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVGxmbHJiV3VyWWF2Q0NFcU5P
      T0c1M0JiR1c0VEFmCkJnTlZIU01FR0RBV2dCUVVRQWpKVXJtUXg2RlNPVHQyMmhRUUc2ZTFaekFr
      QmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMVGhyTjJ0bU1JR1hCZ2dx
      QXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZr
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5
      SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVs
      ZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRgpBaUVB
      emYxRjVrcGtjSnBvL1BVVG1UZFRwa0M5QndoZ0VwR01uZk54VkszZVF0SUNJRnRlYmRMZDY4ejBO
      VnFECjdZSDNNWkxFWkoxaFFTa1lVWnJZS05sMlRMZXQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEREND
      QWJLZ0F3SUJBZ0lVZkhrTGpDOVlqMk5IT0lpc3RmNTRIeGc3eVRrd0NnWUlLb1pJemowRUF3SXcK
      WkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhM
      bTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPVEUxTURVeU1UTTNXaGNOTWpVd056QTFN
      RFV5TVRNM1dqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdE
      UVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dB
      MVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdT
      TTQ5QXdFSEEwSUFCQk4xd3d6NElrRlIyKzdjTk1hZ0VHc2gxQVFjODJZaGZNRmYKcjlvcjNtMm5X
      UkRvSlNyZ2pDUzhHRk1sSkpaSVZFTUZ1YXcydXUvQ1NSK1lCRmFLd25HalFqQkFNQThHQTFVZApF
      d0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlFVUUFqSlVy
      bVF4NkZTCk9UdDIyaFFRRzZlMVp6QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFqMVdrZjlqdmRC
      bVFIN1I2RkdNM3FacVMKOTBzLzc5NklmMnQxUytwNkx4QUNJRnFiU3czblhUbUZmVFlLelc3cHdm
      N0psOWd4a0xqdW0zMXBLWEdNYjRvdAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlu
      cyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1p
      bnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQEAEaBkFk
      bWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1T
      UBoGQWRtaW5zKgZBZG1pbnMSqhYKCmNhcnJpZXJNU1ASmxYatxQKA01TUBKvFBKkFBKhFAoKY2Fy
      cmllck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJ
      VWMybDFrTS8yaUg1UG92dWxjNHdkT2ZpZUptVXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFl
      RncweQpNakE1TVRVd05USXpOREJhRncweU5UQTNNRFV3TlRJek5EQmFNRm94Q3pBSkJnTlZCQVlU
      QWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRH
      QTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVIvbnNla0JBLzZ1MzdncmlQazdwcGlOakEx
      M3RHVmJrbW5UVXp5ODUrTm93NDlyNktPcHhLSTBrd2FoRjlICmphbGVhdHhkNmc5NUU2OTlGN1N6
      VWt5dG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFk
      QmdOVkhRNEVGZ1FVTGZCYzl6M1NXbEp0RHZkRHhPNjVDODczVm1Fd0NnWUlLb1pJemowRQpBd0lE
      UndBd1JBSWdjL1pTQU10dlhZRWNUUXZCSkYrSUZpaG9KMW9YbVViVW1RQUg3QVMvaVpzQ0lDaVFL
      a0o3CmtIQjEwUVZwN2lBNHZyKzdycjVzMk5zR1NjWEFDUzZkbml3OAotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDN1RDQ0FwU2dBd0lC
      QWdJVVhIekRUbDJYREZubEFmOVl1UzMrZ29GMWcrOHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxk
      REFlRncweQpNakE1TVRVd05UTXhNREJhRncweU16QTVNVFV3TlRNMk1EQmFNSGd4Q3pBSkJnTlZC
      QVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZC
      QW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJGeWNtbGxj
      akVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJC
      Z2dxaGtqT1BRTUJCd05DQUFRSk9hZHk5cnlTRnBxdW45czN1bGlKCjJSR0x4bk5vc1hwNTlnb1VP
      TVlWWFNEejBmNlJTV1hxUDlMdWEzcWo4S3Zjc3pMRnlEVHF0ZU9GamU0VEZKckEKbzRJQkdEQ0NB
      UlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpG
      RzV6V1Vibm5hMTJFYmoxY05XbUc3RUloZENtTUI4R0ExVWRJd1FZTUJhQUZDM3dYUGM5MGxwU2JR
      NzNROFR1CnVRdk85MVpoTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxUWmtOR00yWmpjMlpH
      WXRabkZ6WTJRd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFY
      UWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9p
      SmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFXNUFZMkZ5Y21sbGNp
      MXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpqMEVBd0lEUndBd1JB
      SWdPWEc2T04zWE5iMC9VaVYycXBTbFUySS9MdHNUY1VRUWMrbzBFZ0VnYWlJQwpJRTQza2kxQk8w
      QmlmTnd3WlRya0JPYThmMkl2eVNRYUNnZ1ZRRkRKUTc5NwotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCkIOCgRTSEEyEgZTSEEyNTZK5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjl6
      Q0NBWjZnQXdJQkFnSVVjMmwxa00vMmlINVBvdnVsYzR3ZE9maWVKbVV3Q2dZSUtvWkl6ajBFQXdJ
      dwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhK
      eWFXVnlMVzVsZERBZUZ3MHkKTWpBNU1UVXdOVEl6TkRCYUZ3MHlOVEEzTURVd05USXpOREJhTUZv
      eEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4
      dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21s
      bGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFSL25zZWtCQS82dTM3
      Z3JpUGs3cHBpTmpBMTN0R1Zia21uVFV6eTg1K05vdzQ5cjZLT3B4S0kwa3dhaEY5SApqYWxlYXR4
      ZDZnOTVFNjk5RjdTelVreXRvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VC
      Ci93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUxmQmM5ejNTV2xKdER2ZER4TzY1Qzg3M1ZtRXdDZ1lJ
      S29aSXpqMEUKQXdJRFJ3QXdSQUlnYy9aU0FNdHZYWUVjVFF2QkpGK0lGaWhvSjFvWG1VYlVtUUFI
      N0FTL2lac0NJQ2lRS2tKNwprSEIxMFFWcDdpQTR2cis3cnI1czJOc0dTY1hBQ1M2ZG5pdzgKLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAES
      AggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAa
      DhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoK
      Y2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIM
      CgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIM
      CAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI////
      /w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4t
      bmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoG
      VjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMi
      IgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdS
      ZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlu
      cxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
