apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.172.161.165:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIADwLPVHoqQg1iO/RT8BMO1jr7uOezVTuzavittU/piLEqheCqVeCqJeCngKWggBEAEaBgjU
      p7ejBiIKc3lzY2hhbm5lbCpAYWI4OTAwYzgwNjc1NWMxN2NkZThlYmJjMDdlMDFhNGU5NjAyZjJk
      ODMyNTM1NWE0YjlhMTgwMmU3NTE1ZTdmYhIaEhhLheALC4HOCVTcq19dimLe2Gs2SJsZ/mYSpV0K
      ol0Sn10SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVYVM1blZpTW9MamwrWVc4bmkrbld2eXVrdWJ3d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRJME1EZzFPVEEwV2hjTk1qWXdNekV6TURnMU9UQTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJQVVlI
      amovUklEcjRzem9OcUV5TzZpODcwczJIY0NwZXdyUlIxZEhjV1ZiSlpWYTF3dUsKbTBxemlWR0Zv
      cXpLSGtOZUNSajZGVXNJY2VIcXNHTnhLUkdqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWc1WXVFQ1Jha1VRUDUxdmtkV3VMTVNU
      eWhFVEFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCbGs4OTNqNUdELzJKNThXRmYxODk0Z1hFaXU5
      U0lpU0tRczlBMW1tUmkKS1FJZ0ZneFRQdHpZUWRmSTBWWlVUeFFiQU5GZTAyNEtvTzNMUVBiTy9y
      YUQzYVk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9lZ0F3SUJBZ0lVTmEzTnd4M2hyWEZWTHZFcVc1ZUhjcmRDWjQwd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRJME1EZzFPVEF3V2hjTk1q
      UXdOVEl6TURrd05EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFSG43aE4rWVVRbnJ0aUc1dEZIRGc1SlFZbzlN
      Y2dlSG0KY1FxbWVXRER5KzVpYU9id0luU3NQOGJQeEhiMS9mTVo3ZzMxUHlZS2NrV2R4bk83ZmxB
      V0lhT0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTUUhyZk41T2NxCjFQKzYyeUF1R1oxQmZyRDRjekFmQmdOVkhTTUVHREFXZ0JR
      ZzVZdUVDUmFrVVFQNTF2a2RXdUxNU1R5aEVUQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kw
      MVpqWTNOR1ptTkRjdE5tMTBibXd3Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBNGVFdWVMa1dYR1hBZDhHdW1hem9zMFlBc1V6VEJ3NjE4Ylh6Mi9JbDcrVUNJQzg1
      V2tVQTdNcmNBWlQrClRBNEx1aHJNZGZiekRvNlRqOVk4Y0FxTForR1QKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVYVM1blZpTW9MamwrWVc4bmkrbld2eXVrdWJ3d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRJME1EZzFPVEEwV2hjTk1qWXdNekV6
      TURnMU9UQTBXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJQVVlIamovUklEcjRzem9OcUV5TzZpODcwczJIY0NwZXdyUlIxZEhjV1ZiSlpWYTF3dUsK
      bTBxemlWR0ZvcXpLSGtOZUNSajZGVXNJY2VIcXNHTnhLUkdqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWc1WXVFQ1Jha1VRUDUx
      dmtkV3VMTVNUeWhFVEFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCbGs4OTNqNUdELzJKNThXRmYx
      ODk0Z1hFaXU5U0lpU0tRczlBMW1tUmkKS1FJZ0ZneFRQdHpZUWRmSTBWWlVUeFFiQU5GZTAyNEtv
      TzNMUVBiTy9yYUQzYVk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0
      aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooS
      Cg1Db25zZW5zdXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0EIo3GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQXF1Z0F3SUJB
      Z0lVY0N4bE9QaHlvYks5NWtzbktNZjFreldPbitJd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJp
      MXVaWFF3CkhoY05Nak13TlRJME1EZzFPVEF3V2hjTk1qUXdOVEl6TURrd05EQXdXakJ4TVFzd0NR
      WURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0Rn
      WURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4
      aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBUzc5TTIxV3orRlhJNVlnaTVWLzJyZm54SkcKYkM1T3pOSmVsWTNYbWZ0UGZ0
      UGsrbEJCTUd0Vkp4Z1U4dk0wejBxVUR6blA0YTlJRTk1eXNqb0kwQkxHbzRJQgpNakNDQVM0d0Rn
      WURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJR
      Y0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUnNHTXd4bE9LcktKM3ZWV0JMWVNN
      L282TEoKN3pBZkJnTlZIU01FR0RBV2dCUWc1WXVFQ1Jha1VRUDUxdmtkV3VMTVNUeWhFVEJCQmdO
      VkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJ
      eExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25N
      aU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lK
      dmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhK
      bGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUI4MTVqcUh0Ykk2aTRaCmxNMWtqWHhTLzBZ
      YTh0RjRwT1pqOWJnYm9ENW8zQUlnY0YzUXlTNWZPVGpUK2JGMjdHVytaY2VrT3BQMDBBbE4Kd3pL
      Z1cwdFg4K0E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSURCRENDQXF1Z0F3SUJBZ0lVY0N4bE9QaHlvYks5NWtzbktNZjFreldPbitJ
      d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZ
      RFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRJME1EZzFPVEF3V2hj
      Tk1qUXdOVEl6TURrd05EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRF
      dU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFR
      TEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1
      ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUzc5TTIxV3orRlhJNVlnaTVW
      LzJyZm54SkcKYkM1T3pOSmVsWTNYbWZ0UGZ0UGsrbEJCTUd0Vkp4Z1U4dk0wejBxVUR6blA0YTlJ
      RTk1eXNqb0kwQkxHbzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFX
      TUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVk
      RGdRV0JCUnNHTXd4bE9LcktKM3ZWV0JMWVNNL282TEoKN3pBZkJnTlZIU01FR0RBV2dCUWc1WXVF
      Q1Jha1VRUDUxdmtkV3VMTVNUeWhFVEJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3
      YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkK
      TENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVa
      WFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVB
      aUI4MTVqcUh0Ykk2aTRaCmxNMWtqWHhTLzBZYTh0RjRwT1pqOWJnYm9ENW8zQUlnY0YzUXlTNWZP
      VGpUK2JGMjdHVytaY2VrT3BQMDBBbE4Kd3pLZ1cwdFg4K0E9Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICA
      MRiAgEAaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1p
      bnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1p
      bnMSwy8KC0NvbnNvcnRpdW1zErMvEuguChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0Szi4SuxcKD21h
      bnVmYWN0dXJlck1TUBKnFxqvFQoDTVNQEqcVEpwVEpkVCg9tYW51ZmFjdHVyZXJNU1AShgYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVmakJXM3paaWVUSlhV
      Mndub3ptMUpwc3lMa2d3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpNd05USTBNRGt3TURFMFdoY05Nall3TXpFek1Ea3dNREUwV2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJc0dWSkwyOElPdEhE
      L2pnS2F5L1RHeE9URXBRSzdFQXR1OApLMjdJNnRvT05ueTZPNEFaL256eStUTHpvSXZKaGxjOU8w
      aTdJaGF3ejhQdk8vVzI4LytqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFlyTDl0dEptdXlCdzYKenJwSytMaWVob3NxaGpBS0Jn
      Z3Foa2pPUFFRREFnTkpBREJHQWlFQTdCSnZLb2t6ZmxxM3BKNmZFWk56M2lFWgp5QmdjQ0VsK3RS
      azYwQzE2WWFzQ0lRQ0R3STRFZXQ3aEVRM2Q3Skp2dUptYW4vNDkwVERNL1g2S3pnbndDVWNlCmdB
      PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJREVUQ0NBcmVnQXdJQkFnSVVIaitGU3VlRkxQc0pnYUZSN0FWaHBRNmtrcUF3Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05USTBNRGt3TVRBd1do
      Y05NalF3TlRJek1Ea3dOakF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVU
      UTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6
      QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZR
      UUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29a
      SQp6ajBEQVFjRFFnQUVKT3hPREI4WHR4U2drcGRFYndrNTlWWDBKTEU1M2tkV2FaWmdUdmw0NC92
      MkFiN0t0VTUvCkMvRXl1d3djNzRnTGJ5SmlFK3ZoMzViWUwzN2VLQndtbGFPQ0FTSXdnZ0VlTUE0
      R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlRWc0xP
      UnEwemNIMUgyTnBNZGxjdzF6N0hyTXpBZgpCZ05WSFNNRUdEQVdnQlRZckw5dHRKbXV5Qnc2enJw
      SytMaWVob3NxaGpBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAxTlRSbU9XUTRZalZrTFdS
      aVltWTVNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpv
      aWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldG
      dWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1po
      ClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFE
      QWdOSUFEQkYKQWlFQTR6Wlc2UUpUbDIrczNFTUdFRTU3bytxNzhvbGtXWlN3R2pJcUxSSllqdU1D
      SUZpLzVHbllCUnF0OEpCVgpiSTVrTEx3cUpuZDNBTCswRkw4RjRNZHUzR3ZmCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqGBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVWZqQlczelppZVRKWFUyd25vem0xSnBzeUxrZ3dDZ1lJ
      S29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQ
      TUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFh
      QmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nak13TlRJME1Ea3dNREUw
      V2hjTk1qWXdNekV6TURrd01ERTBXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdH
      V25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04w
      ZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFH
      U000OUFnRUdDQ3FHU000OUF3RUhBMElBQklzR1ZKTDI4SU90SEQvamdLYXkvVEd4T1RFcFFLN0VB
      dHU4CksyN0k2dG9PTm55Nk80QVovbnp5K1RMem9JdkpobGM5TzBpN0loYXd6OFB2Ty9XMjgvK2pR
      akJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWRE
      Z1FXQkJUWXJMOXR0Sm11eUJ3Ngp6cnBLK0xpZWhvc3FoakFLQmdncWhrak9QUVFEQWdOSkFEQkdB
      aUVBN0JKdktva3pmbHEzcEo2ZkVaTnozaUVaCnlCZ2NDRWwrdFJrNjBDMTZZYXNDSVFDRHdJNEVl
      dDdoRVEzZDdKSnZ1Sm1hbi80OTBURE0vWDZLemdud0NVY2UKZ0E9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tChoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFu
      dWZhY3R1cmVyTVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoT
      EhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSshYKCmNhcnJpZXJNU1ASoxYavxQK
      A01TUBK3FBKsFBKpFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCK0RDQ0FaNmdBd0lCQWdJVUZSeklOWTA3eGZyMjVIU2pCOTVmYTdNakVIa3dDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNekExTWpRd09UQXhNakJhRncweU5qQXpNVE13T1RBeE1q
      QmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJB
      Y01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVky
      RnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFLb01WaWg5
      dFl4S1g2VEpLb25QNVIwWUZwK3E3c1lqMGpJc1hHY2lxTW9uNDYzT1VDUDZtSmdTVmpjOHExCmRQ
      K0tPaEhaMGlUVnRaWFFLV21GZUU0Zm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFV
      ZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVS2t4K1ROMDB2bDM1dE1FNVlmcWxVdTFCK1g0
      d0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdMTWtraU1idUhZZk5UM3dCQ29Famxsc0lJd3Z1SnhZ
      czA2YVlRY205ZERJQ0lRRHowSU1UCkhFYytrWkxWUnpIdDFGNXF4bXRGZ2dZVnN1MXVDakRLWm0x
      aG9RPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQzdUQ0NBcE9nQXdJQkFnSVVCY2s2YXBrcHFuQVJqTDFNQVdkY0VDVVRrY1l3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBMU1qUXdPVEF5TURCYUZ3MHlOREExTWpN
      d09UQTNNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0
      eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYlds
      dU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kx
      dVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUlVpVjEycndWVFhTZlI5dGpK
      UXAzMwpBdThRU1ByZ3NVdy9DTmVNOVZyeHdVNmlneTFtc0xQTDJtQndPLzBnM01DSkNIQjRDNHY0
      NWI5dFViL1ZHMVIvCm80SUJGekNDQVJNd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VC
      L3dRQ01BQXdIUVlEVlIwT0JCWUUKRkN2OTZmNnIwb0pRT0JlSVVpeVl4T2hDS2F3aE1COEdBMVVk
      SXdRWU1CYUFGQ3BNZmt6ZE5MNWQrYlRCT1dINgpwVkx0UWZsK01DTUdBMVVkRVFRY01CcUNHR05o
      TFhSdmIyeHpMV00xT0daa09HWTBOQzE0TW5oc2NEQ0JqUVlJCktnTUVCUVlIQ0FFRWdZQjdJbUYw
      ZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlMQ0poWkcxcGJpSTYKSW5SeWRXVWlMQ0pv
      Wmk1QlptWnBiR2xoZEdsdmJpSTZJbU5oY25KcFpYSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MApTVVFp
      T2lKQlpHMXBia0JqWVhKeWFXVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtC
      Z2dxCmhrak9QUVFEQWdOSUFEQkZBaUVBdytmZXBkdkY2OUpWazZ1M2lxdzNvSFJqSzRPYUt0VGtD
      YUFxTkxEbUY5MEMKSUF6dGgzUGJvbDRoR0VXWnFhWVJJeXlISnVHaUtOUHpZc2U5aE9hSjZMKzMK
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVRlJ6SU5ZMDd4ZnIyNUhTakI5NWZh
      N01qRUhrd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlN
      UmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck16QTFNalF3T1RBeE1qQmFG
      dzB5TmpBek1UTXdPVEF4TWpCYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1i
      MjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApN
      QlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BR
      TUJCd05DCkFBUUtvTVZpaDl0WXhLWDZUSktvblA1UjBZRnArcTdzWWowaklzWEdjaXFNb240NjNP
      VUNQNm1KZ1NWamM4cTEKZFArS09oSFowaVRWdFpYUUtXbUZlRTRmbzBJd1FEQVBCZ05WSFJNQkFm
      OEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVLa3grVE4wMHZs
      MzV0TUU1WWZxbFV1MUIrWDR3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJZ0xNa2tpTWJ1SFlmTlQz
      d0JDb0VqbGxzSUl3dnVKeFlzMDZhWVFjbTlkRElDSVFEejBJTVQKSEVjK2taTFZSekh0MUY1cXht
      dEZnZ1lWc3UxdUNqREtabTFob1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoH
      V3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1p
      bnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNl
      bWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAK
      FUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5n
      QWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVy
      ZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3Vw
      cGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGll
      cxIWEgwKCgoGVjFfNF8zEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
