apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaILESViZneEy+KCX+018ZADOZO9zil1zbe1Yv9kfn3wD1Ep5eCpteCpheCngKWggBEAEaBgii
      zZ2XBiIKc3lzY2hhbm5lbCpAMDFiNjgwMTQ5ZDYxYjg2NzNkZjA3ZTBhMjA5ZjZjYjUwMmZhYTk5
      ZmVlYmQzYTFhYjhhNTNiOWE4OWI2ZWZkMxIaEhgFaHcbvAlGUeoBZuC2k/bHUSdttGQ1oLoSm10K
      mF0SlV0SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVTm1UNk9rcjlHZmw2Z1hLZ1hsRVY2NWhmK0RFd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RBeE1EVXlNVEF4V2hjTk1qVXdOVEl4TURVeU1UQXhX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJJdDJC
      bU8zUW01dTJPTXNRMHVCRDdra0JjczFzRGhsWVNubFNRYXk1eTVGYVJLQnc0VkgKRjcrK2V5b0lZ
      N1l5UitKelJwbU8ybU9NREVoS3NCb3RQaDJqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFI3d1hiRmJLZ28zVnZnNGZlQWlGS0lr
      alhmREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBSVJNZkRJcWY4VGJja2dhRmJqK2s5VUJnMitC
      d0tNenl6VWhJZ2xqbG4KdFFJaEFLbWt4OG14VUF2d3FnZjZWVDQ4eGxPMFREakNwMzhjam1GdEt5
      YlVtdWZDCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVU09zTnFZQ2pMVjRJMXE3ZlRtZHVnM3NYK1pVd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RBeE1EVXlPVEF3V2hjTk1q
      TXdPREF4TURVek5EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFSVorekdHWG9mYjZOZnhjNWFpS01LM2UxdEZK
      clNYRS8KRGtFS2pnakFVaitGOXg0aWFvZmwxNEg5MmxuR0o1S2RFSERlUUZSbTc3eXhicit2aXI1
      SlRxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRM2FuOExOeDRVClhUdlJ2VzlRc0pKRU4rNkRDekFmQmdOVkhTTUVHREFXZ0JU
      Ujd3WGJGYktnbzNWdmc0ZmVBaUZLSWtqWGZEQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xUZHhNbXBtTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQU4zNERwZTUxRFBmaGxSdUpqSUF2YjFCMm1aQ0ZMUjBkaVhGL2tEQ1NoUnpBaUE5
      OVNpSXBLc1FLMXV6CkNIZThtejZSUElBTWRidk42bHloNGxWQnhzUUNydz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVU5tVDZPa3I5R2ZsNmdYS2dYbEVWNjVoZitERXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09EQXhNRFV5TVRBeFdoY05NalV3
      TlRJeE1EVXlNVEF4V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCSXQyQm1PM1FtNXUyT01zUTB1QkQ3a2tCY3Mxc0RobFlTbmxTUWF5NXk1RmFSS0J3
      NFZICkY3KytleW9JWTdZeVIrSnpScG1PMm1PTURFaEtzQm90UGgyalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRSN3dYYkZiS2dv
      M1Z2ZzRmZUFpRktJa2pYZkRBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQUlSTWZESXFmOFRiY2tn
      YUZiaitrOVVCZzIrQndLTXp5elVoSWdsamxuCnRRSWhBS21reDhteFVBdndxZ2Y2VlQ0OHhsTzBU
      RGpDcDM4Y2ptRnRLeWJVbXVmQwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4
      ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVUhKdjVtck5nMjNiTklN
      NmlGOW1TNWliMmtRSXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNt
      UmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09E
      QXhNRFV5T1RBd1doY05Nak13T0RBeE1EVXpOREF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1C
      a0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhC
      d2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNlTnkz
      L05JQW1qMXhhSklib0ZjekliVmFPCllhaVZzSmxvc24vV0k4UHBPRC9BZGN0Q01UdW1EMHI1c1Mx
      aERqMXp6R2xnUGZxdnBwQXJvSHhqYVZrWG80SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdP
      b01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4
      RUFqQUFNQjBHQTFVZERnUVdCQlFtR3dxa3VMa3pLa1VOcy8xOVVrc1NQOEhTCkpEQWZCZ05WSFNN
      RUdEQVdnQlRSN3dYYkZiS2dvM1Z2ZzRmZUFpRktJa2pYZkRBL0JnTlZIUkVFT0RBMmdoaHYKY21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlq
      WVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0Yw
      YVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1
      WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFNBQXdSUUloQU9qREFic3p5Qys2V0VwTgpwUUtxa3RQaFVWbVpYelJZZUpLbmpiZFNPK2ht
      QWlCSnIxRjJlZ2FRY0pKS0hUTmU1VUprUGFMQ2JPNm02YmdFCmlKVURQemVDdkE9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpD
      Q0FxbWdBd0lCQWdJVUhKdjVtck5nMjNiTklNNmlGOW1TNWliMmtRSXdDZ1lJS29aSXpqMEVBd0l3
      ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09EQXhNRFV5T1RBd1doY05Nak13T0RBeE1EVXpOREF3
      V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1
      Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3
      SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNlTnkzL05JQW1qMXhhSklib0ZjekliVmFPCllhaVZzSmxv
      c24vV0k4UHBPRC9BZGN0Q01UdW1EMHI1c1MxaERqMXp6R2xnUGZxdnBwQXJvSHhqYVZrWG80SUIK
      TURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJC
      Z2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFtR3dxa3VMa3pL
      a1VOcy8xOVVrc1NQOEhTCkpEQWZCZ05WSFNNRUdEQVdnQlRSN3dYYkZiS2dvM1Z2ZzRmZUFpRktJ
      a2pYZkRBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NH
      bTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJ
      bUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVk
      RWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJ
      bTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU9qREFic3p5Qys2V0VwTgpw
      UUtxa3RQaFVWbVpYelJZZUpLbmpiZFNPK2htQWlCSnIxRjJlZ2FRY0pKS0hUTmU1VUprUGFMQ2JP
      Nm02YmdFCmlKVURQemVDdkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAK
      GAEgBSiAgIAKGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoH
      V3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlu
      cxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoG
      QWRtaW5zErUvCgtDb25zb3J0aXVtcxKlLxLaLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsAuErEX
      Cg9tYW51ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEG
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVUlRva3N2ckVV
      bTVrZGtEQ3ZZbWNjS3lXMnNjd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hE
      ekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtE
      QXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVa
      WFF3SGhjTk1qSXdPREF4TURVeU16QTBXaGNOTWpVd05USXhNRFV5TXpBMFdqQmtNUXN3Q1FZRFZR
      UUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZU
      QVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkz
      UjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQVVnc3hLM2N3
      R2lhMk5vWFNXQUJwdlh6YUlKS2kyMThrK1MKYnBuSUpHa0RabllITmpaWk5SSjVnOFJLUjlRMGVF
      dkVwaEFMa21xZHZtWjV6bndmM04ralFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZS
      MFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlFjbEdWc3EwTmYyd3MwCm82ZHBHT3BLa2JYUGJq
      QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQjJvTnFPVkpCWGtoY2lZZXZJT2gyd0ZlUEIKVmlvQWpQ
      aGpVbDUwY0hESDRnSWhBTXY0cnFsZStENDBlazdYN21INXVPWHFsbmR6RjdqcUVsZXMxZ00xZE55
      MQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlERVRDQ0FyZWdBd0lCQWdJVUZMclBuMEs1Vy82a1E2YlVHQ1lWYUxDa3VwNHdDZ1lJS29a
      SXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdO
      VkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3T0RBeE1EVXpNREF3V2hj
      Tk1qTXdPREF4TURVek5UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRR
      M0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpB
      TUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFR
      RERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      CnpqMERBUWNEUWdBRS8zL281RzBvbkxhTzdTYUxjbzhuVDY5K1lTbE5NaU52c3BnUHJpbDNDUHJQ
      SUM1aERYc1gKQXpJWk9sb1VIbGRYNk5MQUgxOGw2akFlYlRLUlFMNmdXYU9DQVNJd2dnRWVNQTRH
      QTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUkdqc1I1
      NHlJRzdNUzIyR0NtQWFmVytOTytSekFmCkJnTlZIU01FR0RBV2dCUWNsR1ZzcTBOZjJ3czBvNmRw
      R09wS2tiWFBiakFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMWEpq
      YldnMU1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9p
      ZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1
      ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgK
      WTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURB
      Z05JQURCRgpBaUVBZ0xXR2toTTErVXJsSGVYV01hSzUzWVdicW1hdHpTY2pSNktHRDVYWjBHb0NJ
      RkQvY01FQnV2R1RjMGlDCmxNRkJEQ3Jhdm8vYmtBWmEyYWpncktwWU5rQ3YKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVUlRva3N2ckVVbTVrZGtEQ3ZZbWNjS3lXMnNjd0NnWUlL
      b1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBN
      QTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFC
      Z05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPREF4TURVeU16QTBX
      aGNOTWpVd05USXhNRFV5TXpBMFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dX
      blZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBk
      WEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdT
      TTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQVVnc3hLM2N3R2lhMk5vWFNXQUJwdlh6YUlKS2kyMThr
      K1MKYnBuSUpHa0RabllITmpaWk5SSjVnOFJLUjlRMGVFdkVwaEFMa21xZHZtWjV6bndmM04ralFq
      QkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERn
      UVdCQlFjbEdWc3EwTmYyd3MwCm82ZHBHT3BLa2JYUGJqQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFp
      QjJvTnFPVkpCWGtoY2lZZXZJT2gyd0ZlUEIKVmlvQWpQaGpVbDUwY0hESDRnSWhBTXY0cnFsZStE
      NDBlazdYN21INXVPWHFsbmR6RjdqcUVsZXMxZ00xZE55MQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51
      ZmFjdHVyZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMSrhYKCmNhcnJpZXJNU1ASnxYauxQKA01TUBKz
      FBKoFBKlFAoKY2Fycmllck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpD
      Q0FaNmdBd0lCQWdJVU9leEZkSHlwY1BLWldIbkJ1RC95dXN0TjNHOHdDZ1lJS29aSXpqMEVBd0l3
      CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5
      YVdWeUxXNWxkREFlRncweQpNakE0TURFd05USTFNRFJhRncweU5UQTFNakV3TlRJMU1EUmFNRm94
      Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2
      Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxs
      Y2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRISTc0ZWNwdFg2QTFq
      Z3I4S29uaUlNSVFXc0tQcEE3V0FsVFM1WC9PZnJiU1VvQktqWXZxZXJXMFFzMHBTCm1rcktFRzAw
      NkFBdXBRU3RYSHJnS251RW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIK
      L3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVR2lFYmcyM25tK2ROYkZMRXdjQjdvYnoxVHJnd0NnWUlL
      b1pJemowRQpBd0lEUndBd1JBSWdBZWV4a1hJdXcrdldpNHo1c2hGOC9jdHVBMmxRbmhpNU9MbkNl
      NHc3QUFVQ0lGOGprWDdLCnpjekdMNzhoOHY5WXBrOFpsdnN1U2d4Z3doazg2MGlxemF1OAotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      N2pDQ0FwU2dBd0lCQWdJVUdwd1BXY1lFM1VFM1lvOXRWNjgyeDk3d0xzY3dDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNakE0TURFd05UTXlNREJhRncweU16QTRNREV3TlRNM01EQmFN
      SGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWti
      MjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVD
      eE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRckdNWjBqNjBaSTdTK2o0Rmw1aHh6CkRTaWsw
      T1pETFNPMUtmdCt3aUFheFpmSi8wRXJ2SW1MdGFiRmRSWlhKczBrblRFbHlMamttaXhIeEMrT1BN
      N2IKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRQpGTlhSbXFPN0VpdGxrbmJQM0N3R0NaNWdtUWpuTUI4R0ExVWRJd1FZTUJhQUZC
      b2hHNE50NTV2blRXeFN4TUhBCmU2Rzg5VTY0TUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxU
      WmtOR00yWmpjMlpHWXRNamx0WW1Jd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5
      SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFX
      eHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFX
      NUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpq
      MEVBd0lEU0FBd1JRSWhBTHg1WUlRQ1pYbVA2WnpHRU1uNGxTOXZaZDJEbm9EOHphZ3VWVmdPTXh5
      cQpBaUJnUlp4ZDNMQy9MUGRzNTRNM3dabWFCcXpaak9XN3RLQUFFaEhwd2dsemFBPT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVT2V4RmRIeXBjUEtaV0huQnVEL3l1c3ROM0c4
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTRNREV3TlRJMU1EUmFGdzB5TlRB
      MU1qRXdOVEkxTURSYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0
      eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFV
      RUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05D
      CkFBVEhJNzRlY3B0WDZBMWpncjhLb25pSU1JUVdzS1BwQTdXQWxUUzVYL09mcmJTVW9CS2pZdnFl
      clcwUXMwcFMKbWtyS0VHMDA2QUF1cFFTdFhIcmdLbnVFbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFE
      QVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVHaUViZzIzbm0rZE5iRkxF
      d2NCN29iejFUcmd3Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ0FlZXhrWEl1dyt2V2k0ejVzaEY4
      L2N0dUEybFFuaGk1T0xuQ2U0dzdBQVVDSUY4amtYN0sKemN6R0w3OGg4djlZcGs4Wmx2c3VTZ3hn
      d2hrODYwaXF6YXU4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIc
      EggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0S
      EhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////
      DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1u
      ZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZW
      MV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
