apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: false
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://34.168.92.4:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: supplychain-net

    genesis: |-
      CiIaID8weeWQeH6nmmsLriGxstBv2pc1Vk28/t0bbDTHmBhnEo5eCoteCoheCngKWggBEAEaBgjj
      r5+dBiIKc3lzY2hhbm5lbCpANWI4NWMyMjVmM2VhMjMzMTZlNzA0NGEyMzgzNjMwOTY1NGNhYWFm
      NDg1YzEzZGM2ZGVjMTI4NjliNDg1NTRkYxIaEhjvJQyc/syV3IcUJPufpzgRF/ydZ965uzkSi10K
      iF0ShV0SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVV3daY1I5VzZCRThzZ24wUHRmYXk0L1g2WmlZd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJMU1EUTBNREl3V2hjTk1qVXhNREUwTURRME1ESXdX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJIU2Fa
      dHZGV24zRVpZTk10K2F1NnZ1NnFGdjQrcGtTcS9IK0hObHVsMkFDSW5FVHZxYjMKM09hcnluajYr
      aUorSHFTTmltTFRVQnVDVzJ3TUxyOFFiVlNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1BXNHlXUGFXZlNHc3FDNnhpWEZrN0Jr
      TklKakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBOFA0d3NOT1NxNXVkc2dYL0tZd0JTTmlSTndO
      MjByY3lwM29BSnB1TzYKR1FJaEFMTld2OUZ0alhJVkdDbHA4NmJBYlBReDhzWEkzb0FRWURxSU9D
      STUzR0hDCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0RENDQW9lZ0F3SUJBZ0lVTEwwQTRVTHZ4Z2dtbkRsSkZPSEZ6Mm9ZWURFd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJMU1EUTBOakF3V2hjTk1q
      TXhNakkxTURRMU1UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFQk1HZWd2Uy9iVVR5NXR5d2Q4VTdSZW1iakRr
      ditsRnIKeW5zWExmMEhsdGR5SCswWUhoYkdDdUE0OHdqZFk3akZ1YVF5NklsR1lBeEdvd1FBVDh2
      THpxT0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJURmpBa21BcXlaCncxTllqV0xsMEQwTldISkxLVEFmQmdOVkhTTUVHREFXZ0JT
      UFc0eVdQYVdmU0dzcUM2eGlYRms3QmtOSUpqQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kw
      M05XWTNPVFUxTkRVdGMzUnliSE13Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05I
      QURCRQpBaUJWbjFuTVRUSldMVDdRSm8wb1d5c3lRcUNWSVN3OFEya2VJNWVTWmJrT293SWdQeEtJ
      VDVxb09tZE5VRHQ2CktMQTFST2doRWxYWTBZK3BJc0RJZ3FIQk1Zbz0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVV3daY1I5VzZCRThzZ24wUHRmYXk0L1g2WmlZd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJMU1EUTBNREl3V2hjTk1qVXhNREUw
      TURRME1ESXdXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJIU2FadHZGV24zRVpZTk10K2F1NnZ1NnFGdjQrcGtTcS9IK0hObHVsMkFDSW5FVHZxYjMK
      M09hcnluajYraUorSHFTTmltTFRVQnVDVzJ3TUxyOFFiVlNqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1BXNHlXUGFXZlNHc3FD
      NnhpWEZrN0JrTklKakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBOFA0d3NOT1NxNXVkc2dYL0tZ
      d0JTTmlSTndOMjByY3lwM29BSnB1TzYKR1FJaEFMTld2OUZ0alhJVkdDbHA4NmJBYlBReDhzWEkz
      b0FRWURxSU9DSTUzR0hDCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqCEgoNQ29uc2Vu
      c3VzVHlwZRLwERLlEQoIZXRjZHJhZnQS2BEKwREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCK
      NxrPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQVRDQ0FxZWdBd0lCQWdJVU1ZRnZs
      SVNJYTl3M2t0RmxwazlIdWZUT3h6b3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURW
      UVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpI
      aGNOTWpJeE1qSTFNRFEwTmpBd1doY05Nak14TWpJMU1EUTFNVEF3V2pCeE1Rc3dDUVlEVlFRR0V3
      SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3
      ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNt
      VnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkNBQVEyeFpjUEg3Y1daakNGc3lmN1lkZzdTTFI3CmRlK1hGdExQUmhJYzZEOWZiUy94eHVDdFo0
      akY4ZDhmOWdJNGovQythVzhMMjF1a2ZjMGpZN29QcGxkNG80SUIKTGpDQ0FTb3dEZ1lEVlIwUEFR
      SC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJn
      TlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlI3OWdRbzhMNFNlUWNIbWNJUVRyc1Nrc3dnClh6
      QWZCZ05WSFNNRUdEQVdnQlNQVzR5V1BhV2ZTR3NxQzZ4aVhGazdCa05JSmpBOUJnTlZIUkVFTmpB
      MGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHRzl5WkdWeVpYSXhMbk4xY0hC
      c2VXTm9ZV2x1TFc1bApkREJzQmdncUF3UUZCZ2NJQVFSZ2V5SmhkSFJ5Y3lJNmV5Sm9aaTVCWm1a
      cGJHbGhkR2x2YmlJNklpSXNJbWhtCkxrVnVjbTlzYkcxbGJuUkpSQ0k2SW05eVpHVnlaWEl4TG5O
      MWNIQnNlV05vWVdsdUxXNWxkQ0lzSW1obUxsUjUKY0dVaU9pSnZjbVJsY21WeUluMTlNQW9HQ0Nx
      R1NNNDlCQU1DQTBnQU1FVUNJUURTZUVOd2dRVDJ6cXNCUENpTwozYndDNFJxWXBxQnR0R0VFSjI1
      Y2Rudkl5UUlnRDlhNVhDQzQ4ZjdFbDlKSUNta0xibkpBWFhhWDZEOFN5TUFkCkZMZDh3RzA9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURBVENDQXFlZ0F3SUJBZ0lVTVlGdmxJU0lhOXcza3RGbHBrOUh1ZlRPeHpvd0NnWUlLb1pJemow
      RUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1
      emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJMU1EUTBOakF3V2hjTk1qTXhNakkxTURR
      MU1UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRN
      dlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21W
      eU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdj
      cWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUTJ4WmNQSDdjV1pqQ0ZzeWY3WWRnN1NMUjcKZGUr
      WEZ0TFBSaEljNkQ5ZmJTL3h4dUN0WjRqRjhkOGY5Z0k0ai9DK2FXOEwyMXVrZmMwalk3b1BwbGQ0
      bzRJQgpMakNDQVNvd0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVG
      QndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUjc5Z1Fv
      OEw0U2VRY0htY0lRVHJzU2tzd2cKWHpBZkJnTlZIU01FR0RBV2dCU1BXNHlXUGFXZlNHc3FDNnhp
      WEZrN0JrTklKakE5QmdOVkhSRUVOakEwZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1
      WlhTQ0dHOXlaR1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVsCmREQnNCZ2dxQXdRRkJnY0lBUVJn
      ZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwYkdsaGRHbHZiaUk2SWlJc0ltaG0KTGtWdWNtOXNiRzFs
      Ym5SSlJDSTZJbTl5WkdWeVpYSXhMbk4xY0hCc2VXTm9ZV2x1TFc1bGRDSXNJbWhtTGxSNQpjR1Vp
      T2lKdmNtUmxjbVZ5SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRRFNlRU53Z1FUMnpxc0JQ
      Q2lPCjNid0M0UnFZcHFCdHRHRUVKMjVjZG52SXlRSWdEOWE1WENDNDhmN0VsOUpJQ21rTGJuSkFY
      WGFYNkQ4U3lNQWQKRkxkOHdHMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQ
      ChgBIAUogICAChoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4K
      DEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZB
      ZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFk
      ZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMa
      BkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5zErEvCgtD
      b25zb3J0aXVtcxKhLxLWLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtErwuErEXCg9tYW51ZmFjdHVy
      ZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVQi9iVklWV25Xek10aG4rMm1oRlZS
      ZDJHSExvd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhN
      akkxTURRME1USTVXaGNOTWpVeE1ERTBNRFEwTVRJNVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBN
      QTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpE
      RTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGRE
      QlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCR3RFNXBZNTFwQ0ZpbzNsVFBiZkRP
      Z2ZOL3FXSXVyWk5KWnEKQ1p2T2hSUWVUV1QvUXlRR3I1NzRsYTJyMFc0OVpEWU5uNUt3OVc1MG1a
      aG1QZGdJOEkyalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlNsdktIL0RPZHAyRFlrCmpnRzVhUkR4T2ZVSjZUQUtCZ2dxaGtqT1BR
      UURBZ05JQURCRkFpRUE1Uk5lZGpHelNveDlJbDBBOUxudVV3OEgKeFYybW1nSkM0N3JSNUtqLzk0
      WUNJR2lwV0VKNGE4R05wN2xhRnd1dFdxbW1VaVVtZXM1bEgzUFB2OW5rVmVGdQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERVRDQ0Fy
      ZWdBd0lCQWdJVVkvdmJDSHhaeTRadGYzZFVMNW43LzUvZEQ0Y3dDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TWpJMU1EUTBPREF3V2hjTk1qTXhNakkxTURR
      MU16QXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRR
      dlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldG
      a2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtC
      dFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdB
      RU1oYkFsQ0JYR3YrT1krc1FRdmtBd2psb1JDSDBvbGhpWTVLZldzVm54LzgweGloUk5mT3cKZEh5
      a1FMYWg1MVVKeDdmcHhMcmx2am91MzUvOXNKd1JQNk9DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FF
      QXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU2Era2tucmxTMmFBZ3hIUmRC
      MDc1Y1NpY0szekFmCkJnTlZIU01FR0RBV2dCU2x2S0gvRE9kcDJEWWtqZ0c1YVJEeE9mVUo2VEFr
      QmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDFOalkwWkRZNFlqZGlMVFIwWm1NME1JR1hCZ2dx
      QXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZr
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5
      SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVs
      ZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRgpBaUVB
      bVNaeUpXWmhSU1cya3UySkVJLzNjQzJOMG8ranA4bnV2a3dvc1pxWVkrNENJSCtlYTVQL2VraGd0
      ak0vCnBsT0liOUkvM2NiS21iNWJtUmNSNkxBWC9IRmIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEREND
      QWJLZ0F3SUJBZ0lVQi9iVklWV25Xek10aG4rMm1oRlZSZDJHSExvd0NnWUlLb1pJemowRUF3SXcK
      WkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhM
      bTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakkxTURRME1USTVXaGNOTWpVeE1ERTBN
      RFEwTVRJNVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdE
      UVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dB
      MVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdT
      TTQ5QXdFSEEwSUFCR3RFNXBZNTFwQ0ZpbzNsVFBiZkRPZ2ZOL3FXSXVyWk5KWnEKQ1p2T2hSUWVU
      V1QvUXlRR3I1NzRsYTJyMFc0OVpEWU5uNUt3OVc1MG1aaG1QZGdJOEkyalFqQkFNQThHQTFVZApF
      d0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNsdktIL0RP
      ZHAyRFlrCmpnRzVhUkR4T2ZVSjZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE1Uk5lZGpHelNv
      eDlJbDBBOUxudVV3OEgKeFYybW1nSkM0N3JSNUtqLzk0WUNJR2lwV0VKNGE4R05wN2xhRnd1dFdx
      bW1VaVVtZXM1bEgzUFB2OW5rVmVGdQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZB
      ZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoG
      QWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1Aa
      BkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJNU1AQ
      ARoGQWRtaW5zKgZBZG1pbnMSqhYKCmNhcnJpZXJNU1ASmxYatxQKA01TUBKvFBKkFBKhFAoKY2Fy
      cmllck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJ
      VVJCNWZ6dVhsUlZDSFRzdlpid3UxMU9qajBZMHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFl
      RncweQpNakV5TWpVd05EUXlNelZhRncweU5URXdNVFF3TkRReU16VmFNRm94Q3pBSkJnTlZCQVlU
      QWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRH
      QTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVQrZkxYVWdONm43M1BTdjgwd3AwTmxGQzJY
      SGtNc3Y0REhBT2FWMHdSa2doRDVrMEhDa0h1UUdFVHJ0UkM0CndGNEZSSHE0SjVybjB4YnVIQkJ0
      UXdWOW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFk
      QmdOVkhRNEVGZ1FVdnlTYjU2QjFuTjBWSyt4N2FHMThKcXZYbjBNd0NnWUlLb1pJemowRQpBd0lE
      UndBd1JBSWdBUE9tQTRScjVVMk5lQkVTd09CQkYydjFaSEpoaUc1VjVCcEQ4VjZmbE5JQ0lGcXdX
      U1hKCnFRT3BaaHpyTllkWm5IVE0zSTE1a2dSMzBDV2pqNFAvS2FVWQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDN1RDQ0FwT2dBd0lC
      QWdJVVBjZTRiMzZ4bXBCZVJGaXdCckVyVzVaTkJnOHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxk
      REFlRncweQpNakV5TWpVd05EVXdNREJhRncweU16RXlNalV3TkRVMU1EQmFNSGd4Q3pBSkJnTlZC
      QVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZC
      QW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJGeWNtbGxj
      akVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJC
      Z2dxaGtqT1BRTUJCd05DQUFUSmd4VGhrU0xvVlJOVUF6MGdjYTFlCmpvZUZLNGNTN1crcGNIeHVl
      Rzhvcjd6c092c2hhWWJNd2ozUXRhRVBqRnozMURTYms4bFpLdE9WZU9oN2x3Z0QKbzRJQkZ6Q0NB
      Uk13RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpG
      Qk9XeDdwV29xb2hmZzVzOC8wNElPWi9ndHFKTUI4R0ExVWRJd1FZTUJhQUZMOGttK2VnZFp6ZEZT
      dnNlMmh0CmZDYXIxNTlETUNNR0ExVWRFUVFjTUJxQ0dHTmhMWFJ2YjJ4ekxXUTJOalZrWkRoak5D
      MW5PRGx3T1RDQmpRWUkKS2dNRUJRWUhDQUVFZ1lCN0ltRjBkSEp6SWpwN0ltRmlZV011YVc1cGRD
      STZJblJ5ZFdVaUxDSmhaRzFwYmlJNgpJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGhkR2x2YmlJNklt
      TmhjbkpwWlhJaUxDSm9aaTVGYm5KdmJHeHRaVzUwClNVUWlPaUpCWkcxcGJrQmpZWEp5YVdWeUxX
      NWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3EKaGtqT1BRUURBZ05JQURCRkFp
      RUF2enpvRzFTTk1FSUdaN3RXSXNSbkN3Q1NBYXovRDJqVmtDQkNUSXA2R2tJQwpJRXR0THBWakQz
      TllhUEs2OTN0WjZQUUk1NVpXZmVBaWl2cjVMVFhyUkxTOQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCkIOCgRTSEEyEgZTSEEyNTZK5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjl6
      Q0NBWjZnQXdJQkFnSVVSQjVmenVYbFJWQ0hUc3ZaYnd1MTFPamowWTB3Q2dZSUtvWkl6ajBFQXdJ
      dwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhK
      eWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1qVXdORFF5TXpWYUZ3MHlOVEV3TVRRd05EUXlNelZhTUZv
      eEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4
      dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21s
      bGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUK2ZMWFVnTjZuNzNQ
      U3Y4MHdwME5sRkMyWEhrTXN2NERIQU9hVjB3UmtnaEQ1azBIQ2tIdVFHRVRydFJDNAp3RjRGUkhx
      NEo1cm4weGJ1SEJCdFF3VjlvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VC
      Ci93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXZ5U2I1NkIxbk4wVksreDdhRzE4SnF2WG4wTXdDZ1lJ
      S29aSXpqMEUKQXdJRFJ3QXdSQUlnQVBPbUE0UnI1VTJOZUJFU3dPQkJGMnYxWkhKaGlHNVY1QnBE
      OFY2ZmxOSUNJRnF3V1NYSgpxUU9wWmh6ck5ZZFpuSFRNM0kxNWtnUjMwQ1dqajRQL0thVVkKLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARIC
      CAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggB
      EgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggA
      Gg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIM
      CgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIM
      CAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRt
      aW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQT3Jk
      ZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5l
      bC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMi
      IgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdS
      ZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlu
      cxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
