apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIBhPAFZLGC3AF8lVyukG6MTVdst41C0mZ4+j07LuyRj5ErBeCq1eCqpeCngKWggBEAEaBgj0
      3cSZBiIKc3lzY2hhbm5lbCpAZmIwM2UzZWE4YWJmZWQwOTYxYzg3MDA3NjU3YzMxNTUyYjllMjk3
      ODk0ODVhZTVhYTVjYzU0MWVlODFiNjYzMxIaEhhL6mfDZUcTScfVEJmyecdT2rMVNA6gA2MSrV0K
      ql0Sp10SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVUmsvZnV4cTFNZVBkMnBHWVlETitMZWRwYnFNd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RJMk1EUXpNVEF3V2hjTk1qVXdOekUyTURRek1UQXdX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJMaXdK
      ZmJVY0ErYWNidkp5a3NtWldhRDFlOUpvRFB3U28xVnZXUllPTzZCR0lTN2pERVQKd1F5Z1I2eFp4
      RDdOcXYrNnBmT2sxbG1GcjBlU0FYdndUNHVqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFRXeDByZGJaQXpTYjhmRWJnY2dIR3Ew
      SytoREFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCUHdLRVdQbVNjS1hZNlh1YXZqK09zYy9NZEZN
      Wm8xbXpFTWs3NFNEd04KbkFJZ1lVWFVoOHU4R1M3R0RHdmdueDVHMDE3K04xa3JPNi9Gb3NJYU5X
      YVU5MGM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVU0NsVmNMNzRjZjlMQklzaUd4Z2lRYW84MGw0d0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RJMk1EUXpPREF3V2hjTk1q
      TXdPVEkyTURRME16QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFbnNwVEtFVzVnc3pRQW9NYlNlbUdXclcwYjFX
      RG05SnMKakpjTDJQakFqK1NYSXl1d0JxUkd6REVpY2l5bjgzc1d6OWMrNTUzWWxtU2hDemFHWWJF
      dDdhT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJScXc4M3VENUNVCjZ6Z3dDVUlzWlpXK2tIRENSekFmQmdOVkhTTUVHREFXZ0JU
      VFd4MHJkYlpBelNiOGZFYmdjZ0hHcTBLK2hEQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xYZDJiR2M0TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUxlM0dsNVRLOXdialNqV2FQS1U2TGV5Z0IwenRkWHFnMjFmbXVwM3I5Z25BaUEr
      L3VRczFIaWdZZjJLCkw2TWNLdW1zdVBDOTVZaXkrejA0TFJLenJPWUlCdz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlCL3pDQ0FhYWdBd0lCQWdJVVJrL2Z1eHExTWVQZDJwR1lZRE4rTGVkcGJxTXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09USTJNRFF6TVRBd1doY05NalV3
      TnpFMk1EUXpNVEF3V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCTGl3SmZiVWNBK2FjYnZKeWtzbVpXYUQxZTlKb0RQd1NvMVZ2V1JZT082QkdJUzdq
      REVUCndReWdSNnhaeEQ3TnF2KzZwZk9rMWxtRnIwZVNBWHZ3VDR1alFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRUV3gwcmRiWkF6
      U2I4ZkViZ2NnSEdxMEsraERBSwpCZ2dxaGtqT1BRUURBZ05IQURCRUFpQlB3S0VXUG1TY0tYWTZY
      dWF2aitPc2MvTWRGTVpvMW16RU1rNzRTRHdOCm5BSWdZVVhVaDh1OEdTN0dER3Znbng1RzAxNytO
      MWtyTzYvRm9zSWFOV2FVOTBjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0
      cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlu
      cxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBs
      eWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdB
      d0lCQWdJVVZTbzNwYUNlL0ZjL2d4U3RNMUs2OTZIZ1QvTXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpJd09USTJNRFF6T0RBd1doY05Nak13T1RJMk1EUTBNekF3V2pCeE1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZR
      UURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkNBQVFZYlNGbldWNWpXR2p2MEJyNStaT3hsVkpMCk5XUVYxN2l3b29kY2hV
      Z2ErdHdBZzgrZ1hXbWl2OFpOR1BTbS82VE1CMWhoNEpDWENOOFVORmw4eU5zbW80SUIKTURDQ0FT
      d3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdF
      RgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlRQcHNMMk1oN1phbHlIZUFV
      RHBpVXdpRkFrCi9qQWZCZ05WSFNNRUdEQVdnQlRUV3gwcmRiWkF6U2I4ZkViZ2NnSEdxMEsraERB
      L0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdW
      eVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhK
      eklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpv
      aWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdW
      eVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU9BY013bTNPTEFrUWxxaQpNSTlxYjUw
      VWduOHlEWmREM21wa3A1aVZVVVp4QWlCU2xOSUhrRHBJNVJPcHVMbUNiUzVaYUhzMUI1eUdCTlVo
      Clpnb0IvK0F6YXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVVZTbzNwYUNlL0ZjL2d4U3RNMUs2OTZI
      Z1QvTXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJz
      d0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09USTJNRFF6T0RB
      d1doY05Nak13T1RJMk1EUTBNekF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhN
      U05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZ
      RFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0Zw
      YmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFZYlNGbldWNWpXR2p2
      MEJyNStaT3hsVkpMCk5XUVYxN2l3b29kY2hVZ2ErdHdBZzgrZ1hXbWl2OFpOR1BTbS82VE1CMWho
      NEpDWENOOFVORmw4eU5zbW80SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVk
      SlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBH
      QTFVZERnUVdCQlRQcHNMMk1oN1phbHlIZUFVRHBpVXdpRkFrCi9qQWZCZ05WSFNNRUdEQVdnQlRU
      V3gwcmRiWkF6U2I4ZkViZ2NnSEdxMEsraERBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6
      ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0
      TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJ
      aXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRi
      bVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdS
      UUloQU9BY013bTNPTEFrUWxxaQpNSTlxYjUwVWduOHlEWmREM21wa3A1aVZVVVp4QWlCU2xOSUhr
      RHBJNVJPcHVMbUNiUzVaYUhzMUI1eUdCTlVoClpnb0IvK0F6YXc9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgK
      EICAgDEYgIBAGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoG
      QWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoG
      QWRtaW5zEscvCgtDb25zb3J0aXVtcxK3LxLsLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEtIuErsX
      Cg9tYW51ZmFjdHVyZXJNU1ASpxcarxUKA01TUBKnFRKcFRKZFQoPbWFudWZhY3R1cmVyTVNQEoYG
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEVENDQWJLZ0F3SUJBZ0lVWXdhdmJlaHRU
      YzhJcGdnalpYeWhzeVpDOTdvd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hE
      ekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtE
      QXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVa
      WFF3SGhjTk1qSXdPVEkyTURRek16QXhXaGNOTWpVd056RTJNRFF6TXpBeFdqQmtNUXN3Q1FZRFZR
      UUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZU
      QVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkz
      UjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRWhRRHp5cjFF
      c0hFTXFmcEZrRzFLRkF5dU96eXdIcDEzd2wKS0xXZUVuUWZWRVhQQi91U2hvVWlwR2xraXlsb05k
      MThOelp5UlNscmNvVXRkdVRMaUVlalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZS
      MFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJoRGtHSHpMUmxpZ3dwCjZqdFBxN1Y4VFpUc2x6
      QUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUFsc2lhZ0ZSZCtNZXpySWFhazVPSnBwT2EKeVA1Z2Rx
      QlBRd3BUSmcrOWpWb0NJUURqT1JJb1pNdEJteUdQUjdHNkVmZWlNempURWhtTEJhdi9Mb21zdy9I
      WQo0dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSURFRENDQXJlZ0F3SUJBZ0lVT05CMVJyMStOdCtHbjVrQnkxVkRkcm9PeXRVd0Nn
      WUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFE
      RVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhE
      QWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPVEkyTURRME1E
      QXdXaGNOTWpNd09USTJNRFEwTlRBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJB
      Y1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpY
      SXhJekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhR
      WURWUVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZ
      SUtvWkkKemowREFRY0RRZ0FFZjd5MEdKOTRVWEZkR1BpMDZUN0c0QnFTREFaZXkrQlFrUlBkai9H
      N1cwbFJJckYwQXUvQwo0cXRTSXJyK2JPcHFjb3ZTa1k5VVAxZ1NXLzR2akh0ZkFxT0NBU0l3Z2dF
      ZU1BNEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJS
      VG9ON1NhUmJKYnJ6ditqVWRpU1pycExMaSt6QWYKQmdOVkhTTUVHREFXZ0JSaERrR0h6TFJsaWd3
      cDZqdFBxN1Y4VFpUc2x6QWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1kyUTNabVJtT1Rj
      MkxXTjRjbmhxTUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1s
      MElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpv
      aWJXRnVkV1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1
      ZFdaaApZM1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pP
      UFFRREFnTkhBREJFCkFpQVcvM3RONGJEa0lRclk0djlaVDVJc2JxYk1lSk5HMjVkWG13YkJpb3lB
      V1FJZ2RQYTRxN25VQzBkb3Z3WHgKSXNhcml6bnUyQ0ZuRW45VFArSU0xTGh6Q1ljPQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKhgYtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVZd2F2YmVodFRjOElwZ2dqWlh5aHN5WkM5N293
      Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxq
      YURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4
      SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd09USTJNRFF6
      TXpBeFdoY05NalV3TnpFMk1EUXpNekF4V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVF
      Q0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZt
      WVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcK
      QnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFaFFEenlyMUVzSEVNcWZwRmtHMUtGQXl1T3p5
      d0hwMTN3bApLTFdlRW5RZlZFWFBCL3VTaG9VaXBHbGtpeWxvTmQxOE56WnlSU2xyY29VdGR1VExp
      RWVqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdB
      MVVkRGdRV0JCUmhEa0dIekxSbGlnd3AKNmp0UHE3VjhUWlRzbHpBS0JnZ3Foa2pPUFFRREFnTkpB
      REJHQWlFQWxzaWFnRlJkK01lenJJYWFrNU9KcHBPYQp5UDVnZHFCUFF3cFRKZys5alZvQ0lRRGpP
      UklvWk10Qm15R1BSN0c2RWZlaU16alRFaG1MQmF2L0xvbXN3L0hZCjR3PT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoP
      bWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEK
      D21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMK
      D21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARIC
      CAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zErYWCgpjYXJyaWVyTVNQEqcW
      GsMUCgNNU1ASuxQSsBQSrRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVNVUJNS2Rxem4yTFdWa3FDWE5UemRIYnh0SzB3Q2dZSUtv
      Wkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERB
      NWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBNU1qWXdORE0xTURGYUZ3MHlOVEEzTVRZd05E
      TTFNREZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJn
      TlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1ky
      RXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTNUVo
      UWZ5RTVuTWtOSWpCSFJUM1VMYSs0YjRhKzdFOTlEb2pKQ0h0Uk05NjhVbjBkdkRVb28yL1V1eS9P
      WApoMHlEbWVGeWh2dGhtZnRrVEVKZ1hYOFBvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0
      R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUxyMXNDSWdsbVFtZklvNjFQNjlwRGpo
      OVl1a3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUlnSTNzU0JSKyt2c3lmZ2dDRG4wYzFqb1JwVkwr
      bUdsWnBxZ0kvVkthc09jMENJUUM1Z0NMSworRTg5Y1JTZWFIcDZqRWFjRTBsZTVSdU1MSXRlVThz
      NkVydUQ2Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM3akNDQXBTZ0F3SUJBZ0lVWnYrWjJ3UTB1d3AxK2l0OWZqT09IY2tzQ25n
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTVNall3TkRReU1EQmFGdzB5TXpB
      NU1qWXdORFEzTURCYU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4
      dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldG
      a2JXbHVNQTRHQTFVRUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxs
      CmNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRuNWlaWWdhaFl2NjhQ
      Qm9GNTZOVGUKdUFKbldoS2tpYjVJblM4WVJpRi9hZ2RSUE5Wc1VVQXZPUVhCWU10cS9kYTVCaVBk
      NTZUNTFqY3ZXeU9iamxFSApvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVk
      RXdFQi93UUNNQUF3SFFZRFZSME9CQllFCkZPVFdHaFJTVndnT3RVaGFiTXVZaWl1RFNoRG1NQjhH
      QTFVZEl3UVlNQmFBRkM2OWJBaUlKWmtKbnlLT3RUK3YKYVE0NGZXTHBNQ1FHQTFVZEVRUWRNQnVD
      R1dOaExYUnZiMnh6TFRaa05HTTJaamMyWkdZdGREZGtZM0l3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdB
      ZXlKaGRIUnljeUk2ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZs
      SWl3aWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUK
      ZEVsRUlqb2lRV1J0YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlm
      WDB3Q2dZSQpLb1pJemowRUF3SURTQUF3UlFJaEFMU1dpa3NMemVNUEQ2Q3UxdnNwb09Oa3FwRFlu
      R0t6SXprSytJT1dxaXgyCkFpQUN1aGZTMUZSSUsxY1ZLb1FZK3pkaW96YjdYQnRnTnRnTnNlbHFP
      QThFL3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVNVUJNS2Rxem4yTFdW
      a3FDWE5UemRIYnh0SzB3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5C
      Z05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZ
      WEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBNU1qWXdO
      RE0xTURGYUZ3MHlOVEEzTVRZd05ETTFNREZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApW
      UVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNt
      bGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkMKQUFTNUVoUWZ5RTVuTWtOSWpCSFJUM1VMYSs0YjRhKzdFOTlEb2pKQ0h0
      Uk05NjhVbjBkdkRVb28yL1V1eS9PWApoMHlEbWVGeWh2dGhtZnRrVEVKZ1hYOFBvMEl3UURBUEJn
      TlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUxy
      MXNDSWdsbVFtZklvNjFQNjlwRGpoOVl1a3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUlnSTNzU0JS
      Kyt2c3lmZ2dDRG4wYzFqb1JwVkwrbUdsWnBxZ0kvVkthc09jMENJUUM1Z0NMSworRTg5Y1JTZWFI
      cDZqRWFjRTBsZTVSdU1MSXRlVThzNkVydUQ2Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFk
      bWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlu
      cyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlu
      cyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZB
      ZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIE
      EgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGht
      EhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI////
      /w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4t
      bmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1p
      bnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRl
      cnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
