apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: solo

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.66.8.13:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIDKM1DdByMhwMobw4JZ5ZLMSNYN1uAsE1p6S1UySzklDEpBMCo1MCopMCngKWggBEAEaBgjH
      k9acBiIKc3lzY2hhbm5lbCpAYTIxNjllZmZjYmM3ODVkYjNkOThjY2VkMzg5N2YyNzkwODVjNWU3
      OTM2Y2FhOTFkZGMwZmNhY2RkZWU2NTAyYhIaEhj/bgWDv2y4Snzqpx7PH58dD6ypWkPbiZcSjUsK
      iksSh0sSgRkKB09yZGVyZXIS9RgSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVTkNxK0VJa20yS01zRmJMRDF6RVlWRlYwUy9Bd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFeE1EUTBOakl5V2hjTk1qVXdPVE13TURRME5qSXlX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGVDI0
      Zkt5ZjhCc1BzY1FtVXNEL3RGQUgraWlHOURRL016d1hYaVFIUXEwdGpqMEVGdlkKNXR1RC9oQ3N1
      dm4vTTZqb1pTL1JpMkhlTFllbVJ4UU1mUStqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0xIVVBTSkE1ZmJ4MEk5TnlMaXhETjhK
      THJSREFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCZTMzV1IrZUxyeGU3TFljS0U2V2crdjVOK2k3
      OE1aOXFBMlhzMmV6Mi8KeHdJZ1ZsZXRGaXpnZHdxczEzSUJiSWdTMExoc3RSMlprYUxBS0I3eEtX
      Tm5KRlE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9lZ0F3SUJBZ0lVQWdJNTRSNHd5TXYxa0RNcmZJQm5EOFo3T09Zd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFeE1EUTFNakF3V2hjTk1q
      TXhNakV4TURRMU56QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOXplN2ZHcGQ5V0h5V09GektUTnNSMWpCdlp4
      dy9zODMKMTRwUEZSZHFBcVdkRkRvbm4zMzJxNnRiYUlGelRlRUxGdmVvdy9hRitKRXFLTUxZcDFw
      TUVxT0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRQWJnN2ZJY1RGCkZaS0hDc2lhSWdvaXJGckV6VEFmQmdOVkhTTUVHREFXZ0JT
      TEhVUFNKQTVmYngwSTlOeUxpeEROOEpMclJEQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kw
      NFpEYzNORFUyTlRrdGRHNDViV1l3Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBcTAwWDhMd3J2bnVBSTQ5T3BaSEQ2TStldjVOditwYmt6Wkl3cG1weDNad0NJRnRL
      VDZlazZwS3JQbTV2CnpzQlQzYXNMcFEzK1loclI0VEp5U3MrdWpjZUEKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVTkNxK0VJa20yS01zRmJMRDF6RVlWRlYwUy9Bd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFeE1EUTBOakl5V2hjTk1qVXdPVE13
      TURRME5qSXlXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJGVDI0Zkt5ZjhCc1BzY1FtVXNEL3RGQUgraWlHOURRL016d1hYaVFIUXEwdGpqMEVGdlkK
      NXR1RC9oQ3N1dm4vTTZqb1pTL1JpMkhlTFllbVJ4UU1mUStqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0xIVVBTSkE1ZmJ4MEk5
      TnlMaXhETjhKTHJSREFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCZTMzV1IrZUxyeGU3TFljS0U2
      V2crdjVOK2k3OE1aOXFBMlhzMmV6Mi8KeHdJZ1ZsZXRGaXpnZHdxczEzSUJiSWdTMExoc3RSMlpr
      YUxBS0I3eEtXTm5KRlE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaIQoNQ29u
      c2Vuc3VzVHlwZRIQEgYKBHNvbG8aBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIa
      BkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zKgZBZG1pbnMSvS8KC0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNv
      cnRpdW0SyC4SthYKCmNhcnJpZXJNU1ASpxYawxQKA01TUBK7FBKwFBKtFAoKY2Fycmllck1TUBLp
      BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUVwakg4MUNM
      THVJTlJYcUlWam1yQ3R4YUtjOHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4
      RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFL
      REFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV5
      TVRFd05EUTRNek5hRncweU5UQTVNekF3TkRRNE16TmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdE
      UVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hR
      MkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQwpBQVNXbGxiYWNuYW5pazlXZnRlREhxN1NQR2dkd3NwZzdkNVZx
      SnJyOVFTMUZXUGZDVmJDelF6cnlHUE1rcnptCk9Za3QwaVpxV1lTZitPUDg5ZXExeTlIZG8wSXdR
      REFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVG
      Z1FVV1U4QXRpRHRUcUNzNUVMeTE5WEJvMk5sRVRzd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhB
      TmZTTlNNbnlQc011UDduT0VUTjVCY29VcEE3ZG9Rbm12NTZvdDYzYlJOcEFpQmVYNU9NClJ1Qm1R
      SndUZ0ZoM3JRaW9uUVhQUXZDeUJ6dWdkWjBKdEVGaUFBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdqQ0NBcFNnQXdJQkFnSVVM
      cGdkeUFHV1lvRGtKZE0raFpZTW5HTkFzLzR3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVC
      aE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdE
      Z1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3
      MHkKTWpFeU1URXdORFUwTURCYUZ3MHlNekV5TVRFd05EVTVNREJhTUhneEN6QUpCZ05WQkFZVEFr
      ZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIw
      TmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1C
      Z0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBVG14RytqYkZSOEpsRFVOckpuV2NMZwpqTzk3TkhyWlBJZ2tLNlY5c016MFpr
      ekNKalNxOGtvNEVxZGswdGI5Z1lHQ0NBbEhKVVh1ZE5YMmM5UEtCM0RkCm80SUJHRENDQVJRd0Rn
      WURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRklCVURi
      MjlHOGhhYTdkUXZTUmdkaWFtYzFRWU1COEdBMVVkSXdRWU1CYUFGRmxQQUxZZzdVNmdyT1JDOHRm
      Vgp3YU5qWlJFN01DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVGRqTjJRME5UUTBPRGd0WTNB
      eVoyWXdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lK
      MGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhK
      eWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhR
      aUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFNBQXdSUUloQUxM
      aWQxMmZmZ3pzY2JGT1cxZ25XMGs0V3pERWR5R3dBUFErakcrZEN0Sk0KQWlBYjVnZEFZNjNtL1ZN
      THY0amJwYi8xSHc0bHdnUnlJMFc1dzhaakdsa01MZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RD
      Q0FaNmdBd0lCQWdJVUVwakg4MUNMTHVJTlJYcUlWam1yQ3R4YUtjOHdDZ1lJS29aSXpqMEVBd0l3
      CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5
      YVdWeUxXNWxkREFlRncweQpNakV5TVRFd05EUTRNek5hRncweU5UQTVNekF3TkRRNE16TmFNRm94
      Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2
      Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxs
      Y2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVNXbGxiYWNuYW5pazlX
      ZnRlREhxN1NQR2dkd3NwZzdkNVZxSnJyOVFTMUZXUGZDVmJDelF6cnlHUE1rcnptCk9Za3QwaVpx
      V1lTZitPUDg5ZXExeTlIZG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIK
      L3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVV1U4QXRpRHRUcUNzNUVMeTE5WEJvMk5sRVRzd0NnWUlL
      b1pJemowRQpBd0lEU0FBd1JRSWhBTmZTTlNNbnlQc011UDduT0VUTjVCY29VcEE3ZG9Rbm12NTZv
      dDYzYlJOcEFpQmVYNU9NClJ1Qm1RSndUZ0ZoM3JRaW9uUVhQUXZDeUJ6dWdkWjBKdEVGaUFBPT0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYI
      ARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggS
      BggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAES
      AggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAa
      DhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxKxFwoPbWFudWZhY3R1cmVyTVNQEp0XGqUV
      CgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1TUBKBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVUhsVkVOSlN5Z2Q4aVFXanphL3NmT3FmeWFoUXdDZ1lJ
      S29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQ
      TUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFh
      QmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TWpFeE1EUTBOekk0
      V2hjTk1qVXdPVE13TURRME56STRXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdH
      V25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04w
      ZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFH
      U000OUFnRUdDQ3FHU000OUF3RUhBMElBQk4yWlFEUS93ajZRbFI1VlN6UVBwbnhVUncxL0U2SERE
      amRVCndGb0w5aFhWRXNLQ3AwdUZHYmVBWmM2ODFVaEpwZVZWY2ZBQ3BVQ1hBalIwQWQwV3N2V2pR
      akJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWRE
      Z1FXQkJUU1RVcnh3Y1lrWi9ubApFVzF6b3p5ME85eG5IREFLQmdncWhrak9QUVFEQWdOSUFEQkZB
      aUVBNFltYURYQjhMNG5CcVV5aG42OEdmOFJwCkNkUFlPRzlUZ0dRdEFiekIwaWNDSUVMNjYrK0x0
      b3BzblF3Y3VrSG1KSC9INkE4b3FRMk1adTVDRC9scGxJQ0QKLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVO
      cCtSb00zUjRnMzB6U25xQ0RuaXV6elBDVG93Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVC
      aE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdF
      d1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRY
      SmwKY2kxdVpYUXdIaGNOTWpJeE1qRXhNRFExTXpBd1doY05Nak14TWpFeE1EUTFPREF3V2pDQmhq
      RUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01S
      VXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0Ex
      VUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRI
      VnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6ajBEQVFjRFFnQUVqK1MrQlhmUzFH
      YnNSemxPK1U4czlCUjRLSFA0NHBKUW16TXpreGlaeEVIR1kweDVHNWNLClQzWXlvRUlmYmZrcGEv
      N2JFYnlha2ZjNzhxZzhmL0JGaGFPQ0FTSXdnZ0VlTUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJn
      TlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJsYVM0ZGxEZnlPV2V5bGtBSXNVL2licy9KSmpB
      ZgpCZ05WSFNNRUdEQVdnQlRTVFVyeHdjWWtaL25sRVcxem96eTBPOXhuSERBa0JnTlZIUkVFSFRB
      YmdobGpZUzEwCmIyOXNjeTAxT1dRNE56VTBOemcyTFdkbWNIQndNSUdYQmdncUF3UUZCZ2NJQVFT
      Qmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhK
      MVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1
      eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxS
      NWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlCaVMyVmRWdFNEbFcz
      d3F1blBnNUhnZitWUzJFM0RULzFuRDN6cDhoV3NZUUlnS1JNQ25OblJTM2ZaeHFCZAp0OGJLcURN
      VlVVSE03VGJTVi9uV1oyTEZsUzA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTIS
      BlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJ
      VUhsVkVOSlN5Z2Q4aVFXanphL3NmT3FmeWFoUXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFV
      RUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJV
      d0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04w
      ZFhKbApjaTF1WlhRd0hoY05Nakl4TWpFeE1EUTBOekk0V2hjTk1qVXdPVE13TURRME56STRXakJr
      TVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVph
      ZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1
      YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElB
      Qk4yWlFEUS93ajZRbFI1VlN6UVBwbnhVUncxL0U2SEREamRVCndGb0w5aFhWRXNLQ3AwdUZHYmVB
      WmM2ODFVaEpwZVZWY2ZBQ3BVQ1hBalIwQWQwV3N2V2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1C
      QWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJUU1RVcnh3Y1lrWi9ubApFVzF6
      b3p5ME85eG5IREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBNFltYURYQjhMNG5CcVV5aG42OEdm
      OFJwCkNkUFlPRzlUZ0dRdEFiekIwaWNDSUVMNjYrK0x0b3BzblF3Y3VrSG1KSC9INkE4b3FRMk1a
      dTVDRC9scGxJQ0QKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgdSZWFkZXJz
      Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVy
      cxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlu
      cxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5k
      b3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoG
      QWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAES
      BBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxom
      CgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRo
      bRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP//
      //8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWlu
      LW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRt
      aW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0
      ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
