apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://172.23.170.159:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: supplychain-net

    genesis: |-
      CiIaIP1Gn0+rpILbhgxlFKy9Q0NbTqJ48F1DAx84lE/OcwH8Ep5eCpteCpheCngKWggBEAEaBgjZ
      /PucBiIKc3lzY2hhbm5lbCpAYWU3NzhlOTk1OTM5OTg4YjRhZTE1MTVkMzA5ZTAxNmY1Nzg4NzNh
      ODVjMmI3YWM3YjEyZjk3MWRlZDc3YmE3YhIaEhjilzu/kYBgiQLknF6cxfU5XDo1QyD4u6MSm10K
      mF0SlV0SjysKB09yZGVyZXISgysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVWEU3MC9zSnVIMTIrMnRPSXQrd0ZlOVp3RHBnd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFNE1URXpOREU0V2hjTk1qVXhNREEzTVRFek5ERTRX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJCR2Z2
      RmV3T01kbndWMzh3eEhXM1Fkb01kYnBFZnRleXJUQ3R1b2pJUjl0V0hmR2NHQjEKQWJ2UWliVFVF
      eXR5cmVBOS9tRDVHVDhBa3VvMEdhSHR0eUNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVHJvQUd0L2xPcDFnVXhBdlNza0pHYzM5
      b0ZrekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQWlQMmF1dGlaSGt2RXAxMUV0c0p3Y2tqcHdm
      cGs0eWtjOUxVSkZJMlYKMFdVQ0lHYUcwSS9JYm14d2JBNGhjMDE2SFlXRURtZkl1Lzg3UVFNeVVx
      cGxjbVNwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVQ2NyNnBaUU9pdDhWVWRMdWdhMzJQazRlcHFZd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFNE1URTBNVEF3V2hjTk1q
      TXhNakU0TVRFME5qQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFVWowWm54TFFib2pnS201RHBFcXYrTEY1bnNQ
      b1Q3NE0KMVJhS3g1V2FlL2JPRmVtVTZnRnkrTVBEQUZLRFZpYzhXZzNwbjBocWZhSGlYZ3NDRkRz
      eUVLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUbk1rZjlENGxhClQvbDhrNDM4Ui84cnZzZW1ZekFmQmdOVkhTTUVHREFXZ0JU
      cm9BR3QvbE9wMWdVeEF2U3NrSkdjMzlvRmt6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      NE5tWTNZalkzWmpZNExXWjBibUpxTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUxiQiswQXlvR2FnMG90TWN4Si9hSXdaT2hTYm14OTI4a3pqL3BPR2NsdldBaUFo
      M1UwNUZRNlJCdTJ5CnY5ZW9zRk4vRmpaVjBjQU1pV2VpQnJwak1nM0pQUT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVhFNzAvc0p1SDEyKzJ0T0l0K3dGZTlad0RwZ3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1qRTRNVEV6TkRFNFdoY05NalV4
      TURBM01URXpOREU0V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCQkdmdkZld09NZG53VjM4d3hIVzNRZG9NZGJwRWZ0ZXlyVEN0dW9qSVI5dFdIZkdj
      R0IxCkFidlFpYlRVRXl0eXJlQTkvbUQ1R1Q4QWt1bzBHYUh0dHlDalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRyb0FHdC9sT3Ax
      Z1V4QXZTc2tKR2MzOW9Ga3pBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFpUDJhdXRpWkhrdkVw
      MTFFdHNKd2NranB3ZnBrNHlrYzlMVUpGSTJWCjBXVUNJR2FHMEkvSWJteHdiQTRoYzAxNkhZV0VE
      bWZJdS84N1FRTXlVcXBsY21TcAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRp
      ZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaghIKDUNvbnNlbnN1c1R5cGUS8BES5REKCGV0Y2Ry
      YWZ0EtgRCsERChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijcazwgtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJREFEQ0NBcWVnQXdJQkFnSVVCdHgrLy9YMHJnWGVhRVlLSDEvZDEybTdt
      U1V3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dH
      UVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXhNakU0TVRFME1UQXdX
      aGNOTWpNeE1qRTRNVEUwTmpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNO
      VEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURW
      UVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJp
      MXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVlRRV2FyRENjVUxuZVZ0
      WGJNNzkyN0JxNApQUjF6OEtnWVJ1VmVYZGlFbnB0a3dmMG51U0NuMGRySnJNYVJ1bFJnOC9haGtR
      UWErNmUrdnV5VkhNMzRvNElCCkxqQ0NBU293RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpR
      UVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0Ex
      VWREZ1FXQkJSS2pDd3dPdklkY1lTSi9EUlkwVVlVUjdFdwplakFmQmdOVkhTTUVHREFXZ0JUcm9B
      R3QvbE9wMWdVeEF2U3NrSkdjMzlvRmt6QTlCZ05WSFJFRU5qQTBnaGh2CmNtUmxjbVZ5TVM1emRY
      QndiSGxqYUdGcGJpMXVaWFNDR0c5eVpHVnlaWEl4TG5OMWNIQnNlV05vWVdsdUxXNWwKZERCc0Jn
      Z3FBd1FGQmdjSUFRUmdleUpoZEhSeWN5STZleUpvWmk1QlptWnBiR2xoZEdsdmJpSTZJaUlzSW1o
      bQpMa1Z1Y205c2JHMWxiblJKUkNJNkltOXlaR1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVsZENJ
      c0ltaG1MbFI1CmNHVWlPaUp2Y21SbGNtVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUZ4
      c1JyMlROeEU1ajkxQ3ptdGwKTFVoSVd4SE9Xbi9KWEhQL2dZVlVEQVhWQWlCTU1rR251a0VLNWg2
      VkgzajlKNVZqaExmdVVGcmM1QlhwT1BQcwptNjFLemc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiLPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQURDQ0FxZWdBd0lCQWdJVUJ0
      eCsvL1gwcmdYZWFFWUtIMS9kMTJtN21TVXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      dwpIaGNOTWpJeE1qRTRNVEUwTVRBd1doY05Nak14TWpFNE1URTBOakF3V2pCeE1Rc3dDUVlEVlFR
      R0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkNBQVJWVFFXYXJEQ2NVTG5lVnRYYk03OTI3QnE0ClBSMXo4S2dZUnVWZVhkaUVucHRrd2Yw
      bnVTQ24wZHJKck1hUnVsUmc4L2Foa1FRYSs2ZSt2dXlWSE0zNG80SUIKTGpDQ0FTb3dEZ1lEVlIw
      UEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpB
      TUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJLakN3d092SWRjWVNKL0RSWTBVWVVSN0V3
      CmVqQWZCZ05WSFNNRUdEQVdnQlRyb0FHdC9sT3AxZ1V4QXZTc2tKR2MzOW9Ga3pBOUJnTlZIUkVF
      TmpBMGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHRzl5WkdWeVpYSXhMbk4x
      Y0hCc2VXTm9ZV2x1TFc1bApkREJzQmdncUF3UUZCZ2NJQVFSZ2V5SmhkSFJ5Y3lJNmV5Sm9aaTVC
      Wm1acGJHbGhkR2x2YmlJNklpSXNJbWhtCkxrVnVjbTlzYkcxbGJuUkpSQ0k2SW05eVpHVnlaWEl4
      TG5OMWNIQnNlV05vWVdsdUxXNWxkQ0lzSW1obUxsUjUKY0dVaU9pSnZjbVJsY21WeUluMTlNQW9H
      Q0NxR1NNNDlCQU1DQTBjQU1FUUNJRnhzUnIyVE54RTVqOTFDem10bApMVWhJV3hIT1duL0pYSFAv
      Z1lWVURBWFZBaUJNTWtHbnVrRUs1aDZWSDNqOUo1VmpoTGZ1VUZyYzVCWHBPUFBzCm02MUt6Zz09
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucxoi
      CglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIy
      cxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMS
      FxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRt
      aW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxK9
      LwoLQ29uc29ydGl1bXMSrS8S4i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLILhKxFwoPbWFudWZh
      Y3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1TUBKBBi0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lCQWdJVVU0MFFSRlZRWjNORHVPNy9o
      U1gwL1o4enFUb3dDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFa
      bUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05N
      akl4TWpFNE1URXpOVE14V2hjTk1qVXhNREEzTVRFek5UTXhXakJrTVFzd0NRWURWUVFHCkV3SkRT
      REVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJB
      b00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxX
      NWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk92dnhhdFZ4bXlvZ0Y0aHM1
      Y0QzTXVVRGRtc0RYSHlraUxwCkJpb2JBWUE4cDlKN2FXekJkS3Fac2pwVVdlSlNFUEhBZkFpWlcx
      amU1TnhKY0duY1pQK2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJRU0lhZllZcnFtcmpjWAp6VEtibzVRTUJWZWcyekFLQmdncWhr
      ak9QUVFEQWdOSEFEQkVBaUJ6cW8rQ0NXZWJrMDI2Uk5zdWs0dVpNOE5jCmtvcm0vaFNjc1lCVHBo
      RFF5UUlnSjhRYXR2VS91cFJrK1hicE5Ed3YzOGFjcGprZStvcUtScC9FT3RmZnN6RT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREVU
      Q0NBcmVnQXdJQkFnSVVWOUdyK0dGeWhxWFlQWlBUUFZIMFhjeFlNam93Q2dZSUtvWkl6ajBFQXdJ
      dwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3
      R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJO
      aExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qRTRNVEUwTWpBd1doY05Nak14TWpF
      NE1URTBOekF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNMak00THpn
      dU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6QU1CZ05WQkFz
      VEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZRUUREQlpCWkcx
      cGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6ajBEQVFj
      RFFnQUU2UzU0YlFpeC8rb2lWTHB2K29xWW9ZMXZYSXB5SnZpcjVqOC80MG96d0g3ZFJGZkNNRGFO
      CjhTblozejVaUkNNc0J4ckk0VXo0VkIyZWgyazB5MWVieHFPQ0FTSXdnZ0VlTUE0R0ExVWREd0VC
      L3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNrZ3p2UGZqZHl3UkxQ
      Y3hQMmxrZmE5UWlweERBZgpCZ05WSFNNRUdEQVdnQlFTSWFmWVlycW1yamNYelRLYm81UU1CVmVn
      MnpBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAxWmprME9XSTFaamczTFhveVpteDJNSUdY
      QmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpvaWRISjFaU0lz
      SW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldGdWRXWmhZM1Ix
      Y21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1poClkzUjFjbVZ5
      TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkYK
      QWlFQTd5TlN5Wi8yUmVRV2F2Y1VuSmZpN2dMcU1uYzR5YzV1VmM5MEVMR05CYnNDSUFremV4UXpy
      Y0h4SmQzZQpJOWhXTk5qdWkrbGRBS1U1QXl5Y1VCSTJJRWtMCi0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      Q3pDQ0FiS2dBd0lCQWdJVVU0MFFSRlZRWjNORHVPNy9oU1gwL1o4enFUb3dDZ1lJS29aSXpqMEVB
      d0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1F
      Mk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TWpFNE1URXpOVE14V2hjTk1qVXhN
      REEzTVRFek5UTXhXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9N
      UTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNN
      Qm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdD
      Q3FHU000OUF3RUhBMElBQk92dnhhdFZ4bXlvZ0Y0aHM1Y0QzTXVVRGRtc0RYSHlraUxwCkJpb2JB
      WUE4cDlKN2FXekJkS3Fac2pwVVdlSlNFUEhBZkFpWlcxamU1TnhKY0duY1pQK2pRakJBTUE4R0Ex
      VWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJRU0lh
      ZllZcnFtcmpjWAp6VEtibzVRTUJWZWcyekFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUJ6cW8rQ0NX
      ZWJrMDI2Uk5zdWs0dVpNOE5jCmtvcm0vaFNjc1lCVHBoRFF5UUlnSjhRYXR2VS91cFJrK1hicE5E
      d3YzOGFjcGprZStvcUtScC9FT3RmZnN6RT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFk
      bWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZB
      ZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoG
      QWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBAB
      GgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyoGQWRtaW5zErYWCgpjYXJyaWVyTVNQEqcWGsMUCgNNU1ASuxQSsBQSrRQK
      CmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJ
      QkFnSVVPRDZOaCtmMHI0ZXhSaVArcnhWWVlzbEFiNzR3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVs
      ZERBZUZ3MHkKTWpFeU1UZ3hNVE0yTkRSYUZ3MHlOVEV3TURjeE1UTTJORFJhTUZveEN6QUpCZ05W
      QkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVR
      TUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3
      V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRZGFhazQ2VEhJZ29CN1Q0enhLVG9U
      M1VaRHFjYldDN2diUVFSRW52Z0dYWE9taGZ4Ujh2US9KL0ZoYWdyagp0OFZCODIrYzFFQjAvM3Rn
      bUJrZnliRmhvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lC
      cGpBZEJnTlZIUTRFRmdRVTduamZGdVpiVEk4NHZyUHlwdVlHUU5DN3FQVXdDZ1lJS29aSXpqMEUK
      QXdJRFNBQXdSUUlnRmFVKzlRd2ZsQUhxR29VaU0xMncyK0V2SzNkSW5SUytBQVJ3L1pMQTZRb0NJ
      UUNoT3pXWQpjL0tKOUYrYm9qOG04NlBtQTUxdkJISU9nWXJTbnVqeGlubGpaUT09Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3akND
      QXBTZ0F3SUJBZ0lVWnl4LzlncERvd1dVQloxTzc1R1pyOVhNOGtRd0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck1qRXlNVGd4TVRRek1EQmFGdzB5TXpFeU1UZ3hNVFE0TURCYU1IZ3hD
      ekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhF
      REFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFVRUN4TUhZ
      MkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RBVEJnY3Fo
      a2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJ0UlJMcmJsVXlWaGlndDlwZzJKalgKT3NkQ3RkeTBp
      OWVKUjFwaHkrUnpqUHpiSG5LVWtmSngrWjIvYWowRTBCZVBkQUVwcnNDUzNVdU1HbWhkZVdNVwpv
      NElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZS
      ME9CQllFCkZFQXA3WlFIS2JPeldwM3A2c0pleDdZREVzcjRNQjhHQTFVZEl3UVlNQmFBRk81NDN4
      Ym1XMHlQT0w2ejhxYm0KQmtEUXU2ajFNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6TFRZNU5H
      WTBZamhqWkdZdGRuTnhkMkl3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2ZXlKaFlt
      RmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cFlY
      UnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0YVc1QVky
      RnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJemowRUF3
      SURTQUF3UlFJaEFJRERnb09yeUxaNUdLNU56cExiQnlwUU1ydjZHWDlscTNTM2R5TUQ0bzJaCkFp
      QXVaMTdvOHRhNDF5SDNYKzZUdjBjdEZlZ2hiaFRHQng4NW1XYkVDY2V1d0E9PQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVPRDZOaCtmMHI0ZXhSaVArcnhWWVlzbEFiNzR3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1UZ3hNVE0yTkRSYUZ3MHlOVEV3TURj
      eE1UTTJORFJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpB
      TkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3
      T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFR
      ZGFhazQ2VEhJZ29CN1Q0enhLVG9UM1VaRHFjYldDN2diUVFSRW52Z0dYWE9taGZ4Ujh2US9KL0Zo
      YWdyagp0OFZCODIrYzFFQjAvM3RnbUJrZnliRmhvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgv
      TUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVTduamZGdVpiVEk4NHZyUHlwdVlH
      UU5DN3FQVXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUlnRmFVKzlRd2ZsQUhxR29VaU0xMncyK0V2
      SzNkSW5SUytBQVJ3L1pMQTZRb0NJUUNoT3pXWQpjL0tKOUYrYm9qOG04NlBtQTUxdkJISU9nWXJT
      bnVqeGlubGpaUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoLRW5kb3Jz
      ZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIc
      EggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0S
      EhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////
      DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1u
      ZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZW
      MV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
