apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIMksNlqAQ7Oy0hmx9FzgW9RAS1PNYv6ZAo3TXgQNprJBErReCrFeCq5eCngKWggBEAEaBgi/
      0tGXBiIKc3lzY2hhbm5lbCpAZGZhYWZiNGI2YzliMzBlODc2ODU5NWVkZjAxOTMyNDkxMDBkNGUx
      MTViYjg4M2JkMjRhNGJmMzBlODdjMjEzOBIaEhgRq+kJjRCj/O9KsPiElkOwedThmSeVCC0SsV0K
      rl0Sq10SnysKB09yZGVyZXISkysS1hYKDnN1cHBseWNoYWluTVNQEsMWGs8UCgNNU1ASxxQSvBQS
      uRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVZVUveC9sd1pJcm5ORFFtaGNkdXhvMzlRS3BFd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RFeE1ESXhNVEV3V2hjTk1qVXdOVE14TURJeE1URXdX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJBQWlI
      ZGlMdkJHNWZtK2lubDRDTDZoVGh4eEIyOWJrdlhkRUx3bkhjWjdUZWtWYmdCUCsKZmNKaENSc3Aw
      TGhYZ0hrcVlqZ1hOZ1JvbEIvRlh4azMwQmFqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUVRwWkliMTVZaGYvVVdsTjNCOURBeFBk
      bXAzREFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQWdhZ3I2ZFM5bldrMUhLZ3JXcG01SzAxZm4w
      a01EV2V1b0lXbThzTGoKWDRvQ0lRQzhkbHVjVGVuRWk5S1lTZ0t3ekRvWkF5d3p5Ui9LeEtBUjhn
      OG9MS3U0bkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKmCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNGpDQ0FvaWdBd0lCQWdJVVV4SzZJZWVqMzk2YkJ1Nm1UQzFzOXA0N0k2
      Z3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09ERXhNREl4T1RBd1do
      Y05Nak13T0RFeE1ESXlOREF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVdiclJXQVlkQXcxN3d3R3N5L0g3ZmFS
      aTJFV3ZaS2dMClNBUlpsZDJGQ2RtTnErQzBsTVdLZ3hzTFRsbEszMjZlSDRXcExYd2lPdS9BdnBG
      VjNCdkRWNk9DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCU2J3dWl2d0IyegpjbVFKL1lvYjdBZ2tNbk5hVmpBZkJnTlZIU01FR0RB
      V2dCUVRwWkliMTVZaGYvVVdsTjNCOURBeFBkbXAzREFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDFOalkzWXpZM1ptWTNMV055WTJSb01JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFNBQXcKUlFJaEFPeUVqbmx6RHR1eDV1R2txaG03QzE2bVhLOW9ZVmVTZGFyUFhQQkVMdWwr
      QWlCeXpzdTNtdEY5SWpsTwpReDdXdC9ZMGhJdU5zbVBJVFJ4M2tKblc4dXBIeVE9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK9QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQ0FUQ0NBYWFnQXdJQkFnSVVlVS94L2x3Wklybk5EUW1oY2R1eG8zOVFLcEV3
      Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlE
      VlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdPREV4TURJeE1URXdXaGNO
      TWpVd05UTXhNREl4TVRFd1dqQmVNUXN3Q1FZRFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1
      Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFa
      QmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcK
      U000OUF3RUhBMElBQkFBaUhkaUx2Qkc1Zm0raW5sNENMNmhUaHh4QjI5Ymt2WGRFTHduSGNaN1Rl
      a1ZiZ0JQKwpmY0poQ1JzcDBMaFhnSGtxWWpnWE5nUm9sQi9GWHhrMzBCYWpRakJBTUE4R0ExVWRF
      d0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJRVHBaSWIx
      NVloZi9VV2xOM0I5REF4UGRtcDNEQUsKQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBZ2FncjZkUzlu
      V2sxSEtncldwbTVLMDFmbjBrTURXZXVvSVdtOHNMagpYNG9DSVFDOGRsdWNUZW5FaTlLWVNnS3d6
      RG9aQXl3enlSL0t4S0FSOGc4b0xLdTRuQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZB
      ZG1pbnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1T
      UBoGQWRtaW5zIjcKB1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1T
      UBoGQWRtaW5zIjcKB1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1T
      UBoGQWRtaW5zIjgKBkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQ
      EAEaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4K
      DEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZB
      ZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooSCg1Db25zZW5z
      dXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3
      GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQXFtZ0F3SUJBZ0lVS0lXdUhB
      dGxaMFFvVkh2bElrM3lBelhkZS9nd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3Ckho
      Y05Nakl3T0RFeE1ESXhPVEF3V2hjTk1qTXdPREV4TURJeU5EQXdXakJ4TVFzd0NRWURWUVFHRXdK
      SFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdk
      UGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndO
      Q0FBU1Z4Mkd0TGNPODJIblhCUmViWGlYa3ZzWnoKVG5TUFFkU0Uxa21kRkt0UHZiUEpobExpRXd2
      dndCb1p2dEEyYSthM251eHJ1UzJzWU00V0lIQTljd2MrbzRJQgpNRENDQVN3d0RnWURWUjBQQVFI
      L0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdO
      VkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUkdlaTNJUVZVTUh6SThqanF4WmhpQ3poVUsKUnpB
      ZkJnTlZIU01FR0RBV2dCUVRwWkliMTVZaGYvVVdsTjNCOURBeFBkbXAzREEvQmdOVkhSRUVPREEy
      Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZz
      YjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0Zt
      Wm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1
      YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJ
      S29aSXpqMEVBd0lEU0FBd1JRSWhBTDVrdWFzeTRMWkxCMjRCCnFMZFFOSXVhVnM1czNvQUNIYklM
      VlBPUk1oSWhBaUFSdEFwZFFoSDR1SXI3d2NCeGVNWDJxdmNTQkhiYXE4cWQKdnZDUXNqMUxRdz09
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURBekNDQXFtZ0F3SUJBZ0lVS0lXdUhBdGxaMFFvVkh2bElrM3lBelhkZS9nd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RFeE1ESXhPVEF3V2hjTk1qTXdPREV4
      TURJeU5EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1
      TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJs
      Y21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU1Z4Mkd0TGNPODJIblhCUmViWGlYa3ZzWnoK
      VG5TUFFkU0Uxa21kRkt0UHZiUEpobExpRXd2dndCb1p2dEEyYSthM251eHJ1UzJzWU00V0lIQTlj
      d2MrbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dB
      UVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUkdl
      aTNJUVZVTUh6SThqanF4WmhpQ3poVUsKUnpBZkJnTlZIU01FR0RBV2dCUVRwWkliMTVZaGYvVVds
      TjNCOURBeFBkbXAzREEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBi
      aTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdC
      d2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXli
      MnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpW
      SGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTDVrdWFzeTRM
      WkxCMjRCCnFMZFFOSXVhVnM1czNvQUNIYklMVlBPUk1oSWhBaUFSdEFwZFFoSDR1SXI3d2NCeGVN
      WDJxdmNTQkhiYXE4cWQKdnZDUXNqMUxRdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIK
      BTUwMG1zEAoYASAFKICAgAoaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFk
      bWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMS
      CgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoG
      QWRtaW5zKgZBZG1pbnMSwy8KC0NvbnNvcnRpdW1zErMvEuguChVTdXBwbHlDaGFpbkNvbnNvcnRp
      dW0Szi4SuxcKD21hbnVmYWN0dXJlck1TUBKnFxqvFQoDTVNQEqcVEpwVEpkVCg9tYW51ZmFjdHVy
      ZXJNU1AShgYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVO
      T29iSXhWSm1MNnd6cEhrRTdKalJSTW43N2N3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVC
      aE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdF
      d1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRY
      SmwKY2kxdVpYUXdIaGNOTWpJd09ERXhNREl4TXpFeFdoY05NalV3TlRNeE1ESXhNekV4V2pCa01R
      c3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRY
      SnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJX
      RnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJB
      dDQvc1BmK2dLZlpNNm0ycnpKbW9Pa2VmQU9xblhRa29EMgpHWXhkS0ZqZFdVNXFiK2ZRNzF5Vldt
      RnFGR0wwYzhNM0pWS0VrbkE3YkM3V2tscjNXL1NqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFm
      OHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFk4SXFVNWFTMzNpYTIKaVRtYU1y
      MU5NQjRVeGpBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXF6alhNN0VTV2tkWkJKVWI2OVV0YUh6
      RApldi9Jd1NtNjc0TFhqRkZJdkNJQ0lRQ1Fib2xHQkhPa0dnQVBJT2IxZHNWYU5paVFDQ3duWi9H
      am9OT1dtYjZnCjZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVDUDd0bElFQm1HckNOM3FwWm1pQ0F1
      MUtUOVV3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRI
      VnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd09E
      RXhNREl5TURBd1doY05Nak13T0RFeE1ESXlOVEF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdq
      QVlCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClpt
      RmpkSFZ5WlhJeEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21W
      eU1SOHcKSFFZRFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29a
      SXpqMENBUVlJS29aSQp6ajBEQVFjRFFnQUVYWGlyOHlPU2xrckVLa2NhaFI3b2FiaXJuYnVVLy95
      N3EwQXNDdnpLTXdmOUV4cFpXUTRLCmt4dklLdkNCbTNDdVBSQlFndGprdVYyT2xvQWxzSDd1NWFP
      Q0FTSXdnZ0VlTUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFV
      ZERnUVdCQlIrbkExZDRVckNYbVN2OGFrWWJRdDdYSGx4TXpBZgpCZ05WSFNNRUdEQVdnQlRZOElx
      VTVhUzMzaWEyaVRtYU1yMU5NQjRVeGpBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAzWTJR
      M1ptUm1PVGMyTFdodU5qZzBNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdK
      aFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0Yw
      YVc5dQpJam9pYldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0
      YVc1QWJXRnVkV1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFL
      QmdncWhrak9QUVFEQWdOSEFEQkUKQWlBaTdrMUxicUI0RThXVE9qYk1sZmlBWis0cFY0NE1TcmlH
      ZnpyUHBpMVJWd0lnRVVMK0p4cUk0MWRHRUEregpydkxCZXlCWHAxbkYzTXZEcnJUblFPemZ4MG89
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqGBi0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVU5Pb2JJeFZKbUw2d3pwSGtFN0pq
      UlJNbjc3Y3dDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdN
      QmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZq
      ZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3
      T0RFeE1ESXhNekV4V2hjTk1qVXdOVE14TURJeE16RXhXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQ
      TUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00K
      REUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxk
      REJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkF0NC9zUGYrZ0tmWk02bTJyekpt
      b09rZWZBT3FuWFFrb0QyCkdZeGRLRmpkV1U1cWIrZlE3MXlWV21GcUZHTDBjOE0zSlZLRWtuQTdi
      QzdXa2xyM1cvU2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURB
      Z0dtTUIwR0ExVWREZ1FXQkJUWThJcVU1YVMzM2lhMgppVG1hTXIxTk1CNFV4akFLQmdncWhrak9Q
      UVFEQWdOSkFEQkdBaUVBcXpqWE03RVNXa2RaQkpVYjY5VXRhSHpECmV2L0l3U202NzRMWGpGRkl2
      Q0lDSVFDUWJvbEdCSE9rR2dBUElPYjFkc1ZhTmlpUUNDd25aL0dqb05PV21iNmcKNnc9PQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIG
      CAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggS
      BggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxII
      EgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRII
      EgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMSshYKCmNhcnJp
      ZXJNU1ASoxYavxQKA01TUBK3FBKsFBKpFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUdJQlNDVHhKOGdrbWV1M1JnMGhFMjN6b1hz
      RXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZR
      WURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakE0TVRFd01qRTFNVFJhRncweU5U
      QTFNekV3TWpFMU1UUmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2Iy
      NHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0Ex
      VUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndO
      QwpBQVFVV1pNbWcrbTd3Zjg1R2lhL1Jkb2VTT3cwR3VidHBmUXdmbjNTVnJnd0N1akFreWdVM1ox
      dEZKbEVqZWVrClNVNWFKb2RUUFBWL3lpRWNJVnZPbHpaaG8wSXdRREFQQmdOVkhSTUJBZjhFQlRB
      REFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVK0srRnBJUWJXem1qN3pY
      MUEwRHEzUWNVa1hBd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdDWlYvVlNVTzhpWkVNbzNJN2h1
      d0FaYy85bHlsNGZpUEJ6cXdyaUcvdUg0Q0lRQ2tmTmVTCmVST0U3QTlLbk5SZ0plMllaUkRKU2dh
      ZWN4TnhGMjhZSmM2d0l3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzdUQ0NBcFNnQXdJQkFnSVVhNE0xdkpwWXhmZWVXWVRQNjdC
      dW80Uld2bGt3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBNE1URXdNakl5TURC
      YUZ3MHlNekE0TVRFd01qSTNNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJ
      MU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05W
      CkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVB
      WTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUVNoSXdV
      RFJrbEIzbjhCQS9zOC9LSApoRjB0SHdDVG4rSGRzZHQ4eC9DMmdPMVF5MnA1SERVeGQzSXVZYnJG
      WVI1WXQ2TnhSVWtUQXZoOUFzZDNrNlYrCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VB
      TUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRklsWWk1QlptcWFnNWQvNWdBc2pnWUxZ
      YkRqSk1COEdBMVVkSXdRWU1CYUFGUGl2aGFTRUcxczVvKzgxOVFOQQo2dDBIRkpGd01DUUdBMVVk
      RVFRZE1CdUNHV05oTFhSdmIyeHpMVFprTkdNMlpqYzJaR1l0ZG1jM2VIQXdnWTBHCkNDb0RCQVVH
      QndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkK
      T2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXli
      MnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZ
      V1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnSHN0aUpQVEUzTjBIR1MxUXQ0ZHlC
      eVhRZytCK09QYnJyK3IzclZuNXNra0MKSUZsdHdDRkd2cFRySlAvUnl1ZVZoaVNVNHMzRk5FTTJG
      R1pvalFLVmkzSE8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukF
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVR0lCU0NUeEo4
      Z2ttZXUzUmcwaEUyM3pvWHNFd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhE
      ekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtE
      QWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTRN
      VEV3TWpFMU1UUmFGdzB5TlRBMU16RXdNakUxTVRSYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RR
      WUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEy
      RnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BR
      SUJCZ2dxaGtqT1BRTUJCd05DCkFBUVVXWk1tZyttN3dmODVHaWEvUmRvZVNPdzBHdWJ0cGZRd2Zu
      M1NWcmd3Q3VqQWt5Z1UzWjF0RkpsRWplZWsKU1U1YUpvZFRQUFYveWlFY0lWdk9selpobzBJd1FE
      QVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZn
      UVUrSytGcElRYld6bWo3elgxQTBEcTNRY1VrWEF3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJZ0Na
      Vi9WU1VPOGlaRU1vM0k3aHV3QVpjLzlseWw0ZmlQQnpxd3JpRy91SDRDSVFDa2ZOZVMKZVJPRTdB
      OUtuTlJnSmUyWVpSREpTZ2FlY3hOeEYyOFlKYzZ3SXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQ
      ARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1T
      UBoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZB
      ZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlu
      cyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFu
      bmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxII
      CAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlu
      cxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFz
      aGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwod
      b3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8zEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoG
      QWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdX
      cml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
