apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIB5gFWRdeMJToqT5ssgOtBtvX6ap6ZuXCzVfKQSzmK0lEpJeCo9eCoxeCngKWggBEAEaBgif
      t/2WBiIKc3lzY2hhbm5lbCpAMTk2NTMyZjBhNjc5ZTUwYjJlZWVjYjExNTY4NmYzYzgwNjhjNDUw
      M2RlYzQxMGIzY2U1ZWQwMDViOTdjYWM4ORIaEhi8hj50RPvaVAz9amKPfP/9uQXoNJGJy0oSj10K
      jF0SiV0SjysKB09yZGVyZXISgysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVU1U5NElJbmpVSkdzUzFVTXpRMTVyR2pUczA0d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJMk1ESTFOVFUyV2hjTk1qVXdOVEUxTURJMU5UVTJX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJOc1Fo
      bmJUOVdsek9aemg2Q001ZkIvcFVZUmc0M1d2NEk0VHFYMk1VaE9ZYXIxWWFDZTIKMlZYeTljVnlV
      L1dyZCs5dVNTMjhnaXJ4azhkNzQvRi9SOGFqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUW55cjl5K21PSy9vakdYS3dxQVdqeGxC
      Z3pQakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCY1pOcmZ3cTIycTltaGVINVpNUDIxWFpKb3hZ
      WnRMK1c5a2JXRTFmMDAKQmdJaEFJeGp3L3hBZllnS2RTRHcxZ1dKeldkRDJQaWNtQ1RodlNjcjZM
      YUp4Z3pVCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVWG5WZlU1NTEyYmViak1Jakl4WXJ6ZENoWTZVd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJMk1ETXdNekF3V2hjTk1q
      TXdOekkyTURNd09EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNVpLNnZ5aWxvTDE2TS9uYUVnSUh0VmlmZmFK
      OVVxSlYKSnZwVDMxUEx2WnhDZmVyVkIzcXJZbmhXc3V2dE4ybExrTzRWQUEyK3lBSXU4Nit5TWdM
      UHRhT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSNnFXRTNQcnNFCmpYemRmRk5zQkk5QjNhUUNqakFmQmdOVkhTTUVHREFXZ0JR
      bnlyOXkrbU9LL29qR1hLd3FBV2p4bEJnelBqQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xUYzNaM1kyTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQU1lQmlkdXJ4TXh6ejFibVNiTFNTMmRYRzc1VjA1TE54aWpJWXBQaHlDNElBaUJC
      alI5OE1rYTVPZVR1CnJIZTRrMmlEY1NENk1TcUw0bzRscTZpRnBETTAzdz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVNVOTRJSW5qVUpHc1MxVU16UTE1ckdqVHMwNHdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056STJNREkxTlRVMldoY05NalV3
      TlRFMU1ESTFOVFUyV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCTnNRaG5iVDlXbHpPWnpoNkNNNWZCL3BVWVJnNDNXdjRJNFRxWDJNVWhPWWFyMVlh
      Q2UyCjJWWHk5Y1Z5VS9XcmQrOXVTUzI4Z2lyeGs4ZDc0L0YvUjhhalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlFueXI5eSttT0sv
      b2pHWEt3cUFXanhsQmd6UGpBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQmNaTnJmd3EyMnE5bWhl
      SDVaTVAyMVhaSm94WVp0TCtXOWtiV0UxZjAwCkJnSWhBSXhqdy94QWZZZ0tkU0R3MWdXSnpXZEQy
      UGljbUNUaHZTY3I2TGFKeGd6VQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqCEgoNQ29uc2Vuc3VzVHlwZRLw
      ERLlEQoIZXRjZHJhZnQS2BEKwREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrPCC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQWpDQ0FxbWdBd0lCQWdJVVBVRFlkZzc4NWg2bjFh
      WGRvdUpZemEyQjJFWXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNt
      UmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056
      STJNRE13TXpBd1doY05Nak13TnpJMk1ETXdPREF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1C
      a0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhC
      d2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNJeVZE
      TG5PcDd4cUlzbDQ4dzJxMFVwZ0N2CkFkaUdyQmhLeDlPakQ0MVhUQ2UxaG1aM0c5MW1sdGdrZm5n
      UUVaZ2V5QTNqWm9kMUI2enpMVHhpRmFKb280SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdP
      b01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4
      RUFqQUFNQjBHQTFVZERnUVdCQlM2bXE0SFJwUWNSWmRiQVJqWFoxMm14ZXpKCmt6QWZCZ05WSFNN
      RUdEQVdnQlFueXI5eSttT0svb2pHWEt3cUFXanhsQmd6UGpBL0JnTlZIUkVFT0RBMmdoaHYKY21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlq
      WVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0Yw
      YVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1
      WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFJ3QXdSQUlnUlc5aW40MkxHd0kxYUZSVApQVGZ0Sm16STk5bHRsbHhYZnVKL3Axd2kwRnND
      SUVtQ3dYclE3R1c4a050Vi8xaHJiVk1BRm5aUDVUWnpoSCtNCmRoKzFYN1JOCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KIs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFt
      Z0F3SUJBZ0lVUFVEWWRnNzg1aDZuMWFYZG91Sll6YTJCMkVZd0NnWUlLb1pJemowRUF3SXcKWGpF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxq
      YUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJMk1ETXdNekF3V2hjTk1qTXdOekkyTURNd09EQXdXakJ4
      TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1
      TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lE
      VlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQ0FBU0l5VkRMbk9wN3hxSXNsNDh3MnEwVXBnQ3YKQWRpR3JCaEt4OU9q
      RDQxWFRDZTFobVozRzkxbWx0Z2tmbmdRRVpnZXlBM2pab2QxQjZ6ekxUeGlGYUpvbzRJQgpNREND
      QVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JC
      Z0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUzZtcTRIUnBRY1JaZGJB
      UmpYWjEybXhlekoKa3pBZkJnTlZIU01FR0RBV2dCUW55cjl5K21PSy9vakdYS3dxQVdqeGxCZ3pQ
      akEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXla
      R1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBk
      SEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJ
      am9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXla
      R1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdSVzlpbjQyTEd3STFhRlJUClBUZnRK
      bXpJOTlsdGxseFhmdUovcDF3aTBGc0NJRW1Dd1hyUTdHVzhrTnRWLzFocmJWTUFGblpQNVRaemhI
      K00KZGgrMVg3Uk4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICA
      ChoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFs
      aWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFk
      ZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxKx
      LwoLQ29uc29ydGl1bXMSoS8S1i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRK8LhKxFwoPbWFudWZh
      Y3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1TUBKBBi0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVUo0bmkrUXFLOGc5dm5tMmE0
      UHBqUk1ueGYxMHdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFa
      bUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05N
      akl3TnpJMk1ESTFOelUzV2hjTk1qVXdOVEUxTURJMU56VTNXakJrTVFzd0NRWURWUVFHCkV3SkRT
      REVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJB
      b00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxX
      NWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk9GRzk2djFubXlkN2R1cVhL
      eHY4RVgvbUZqSDVjRk1DMFA2CnVpQUQ0cXlOb3RHbExuYXpVbFFkRVlQbzdHK3dURGRBMHNkTHhB
      Yk45SGxFanFDclp1Q2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJRWkZZclExUDhsUEwwQgptYVk1UkdVaGhpOWZLREFLQmdncWhr
      ak9QUVFEQWdOSUFEQkZBaUVBenNCaElmZkRDbDZaU3lHbitvc2EyNUcxCmpheVVqdW5zVCsvUFNE
      dkEwV3dDSUNVSm1JMGZzVE5pL0dIR1JpTWJtRkVuNkxQVnNyeWR0T0pBYmI1UlNoNEUKLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREVE
      Q0NBcmVnQXdJQkFnSVVGWTV1bkVtY3V4aG9xM1ZtTXRCZ0Z4ODFkOE13Q2dZSUtvWkl6ajBFQXdJ
      dwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3
      R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJO
      aExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056STJNRE13TlRBd1doY05Nak13TnpJ
      Mk1ETXhNREF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNMak00THpn
      dU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6QU1CZ05WQkFz
      VEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZRUUREQlpCWkcx
      cGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6ajBEQVFj
      RFFnQUVsa084cHR5b0RETGtJN1J1d1M4K0VpVVlFd3dEY3VPU284alN4Zld3MDVQaWZxMDloUnRa
      Ck9BSThtYU1FeUZsY21tSnVBRk8rbzNnaU5BQVo3eWduNjZPQ0FTSXdnZ0VlTUE0R0ExVWREd0VC
      L3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJCWkUxVk1tYkFWelRI
      QmUzY0FKM09JUzVxampBZgpCZ05WSFNNRUdEQVdnQlFaRllyUTFQOGxQTDBCbWFZNVJHVWhoaTlm
      S0RBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAzWTJRM1ptUm1PVGMyTFhNNVpEYzVNSUdY
      QmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpvaWRISjFaU0lz
      SW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldGdWRXWmhZM1Ix
      Y21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1poClkzUjFjbVZ5
      TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkUK
      QWlBSjF6NDdvMmtyR1M3VkdVZG9XN3J1TVlOUUZSb1MrTkxKZlpwL2tJUUoyZ0lnQXFrUERKNnk2
      clJwYUVMRwoyNjI2cm91UkMxQ1FSZGNZR0RFU3k2aGxFSm89Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      RERDQ0FiS2dBd0lCQWdJVUo0bmkrUXFLOGc5dm5tMmE0UHBqUk1ueGYxMHdDZ1lJS29aSXpqMEVB
      d0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1F
      Mk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpJMk1ESTFOelUzV2hjTk1qVXdO
      VEUxTURJMU56VTNXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9N
      UTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNN
      Qm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdD
      Q3FHU000OUF3RUhBMElBQk9GRzk2djFubXlkN2R1cVhLeHY4RVgvbUZqSDVjRk1DMFA2CnVpQUQ0
      cXlOb3RHbExuYXpVbFFkRVlQbzdHK3dURGRBMHNkTHhBYk45SGxFanFDclp1Q2pRakJBTUE4R0Ex
      VWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJRWkZZ
      clExUDhsUEwwQgptYVk1UkdVaGhpOWZLREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBenNCaElm
      ZkRDbDZaU3lHbitvc2EyNUcxCmpheVVqdW5zVCsvUFNEdkEwV3dDSUNVSm1JMGZzVE5pL0dIR1Jp
      TWJtRkVuNkxQVnNyeWR0T0pBYmI1UlNoNEUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFk
      bWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1T
      UBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJN
      U1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVy
      TVNQGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVy
      TVNQEAEaBkFkbWlucyoGQWRtaW5zEqoWCgpjYXJyaWVyTVNQEpsWGrcUCgNNU1ASrxQSpBQSoRQK
      CmNhcnJpZXJNU1AS5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjl6Q0NBWjZnQXdJ
      QkFnSVVYNFBVZkFOUWd5eTVIQndiM2NmUWhQRWUwUWN3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVs
      ZERBZUZ3MHkKTWpBM01qWXdNalU1TlRkYUZ3MHlOVEExTVRVd01qVTVOVGRhTUZveEN6QUpCZ05W
      QkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVR
      TUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3
      V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFSZnAzUEFhbjNwelB0a0taVUU1ZmlK
      UzhBUjFiMnN5VTMxeHNVV2RkR0tKVjBrdk93MmxvemdBZzhDcSs5awpSaStJdlZGRm1FTkpScEdW
      VGRwUCtiNzJvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lC
      cGpBZEJnTlZIUTRFRmdRVXc4dDhFZzhaMHZPRzVWOXhuQnVXa0ZMMWFJY3dDZ1lJS29aSXpqMEUK
      QXdJRFJ3QXdSQUlnR1VTbGMwbG8wbVhvamxFZEpUMENXNVRRU2VhTis2Rk5hdjNnM3RnUjVWQUNJ
      SGNEaklPLwpUYVlISHlkWWpVcUhlVjNvSS9iYUxmSDhuQmViam04NWozbXQKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdUQ0NBcFNn
      QXdJQkFnSVVUSDc1SEcxS0ZjYjVNRFRrRFNFclUrcXJ0N2t3Q2dZSUtvWkl6ajBFQXdJdwpXakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlM
      VzVsZERBZUZ3MHkKTWpBM01qWXdNekEzTURCYUZ3MHlNekEzTWpZd016RXlNREJhTUhneEN6QUpC
      Z05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9C
      Z05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnlj
      bWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQ0FBVElaQ2tvQzRWRjNhckROVHRRTE4wZwpGYk9laXJkRzljS0pX
      LzJTSGhNR0ZFSVV5MXlyOGVISzlrQlBUQUFqOVVhUHhFMTRVaElPUkhsLzRRdkhqcDQyCm80SUJH
      RENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JC
      WUUKRkhtSnczMXJIMW5haU9XMFpuc010Mndtem5wbE1COEdBMVVkSXdRWU1CYUFGTVBMZkJJUEdk
      THpodVZmY1p3YgpscEJTOVdpSE1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFprTkdNMlpq
      YzJaR1l0WmpWcmEyWXdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1Gakxt
      bHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIy
      NGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNt
      bGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFJ3
      QXdSQUlnSGtWeVlmelNKVmZXMml6ZUVtK1g4dllpc1VRQmh4TlRXUWp3T3BZUGN4OEMKSUJyTkVs
      V09xS25BYWtVWjN3RmEwTm9nUkpoUDZDbndUU2w4bEpGYXVQS1EKLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUI5ekNDQVo2Z0F3SUJBZ0lVWDRQVWZBTlFneXk1SEJ3YjNjZlFoUEVlMFFjd0NnWUlLb1pJemow
      RUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1
      allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNall3TWpVNU5UZGFGdzB5TlRBMU1UVXdNalU1TlRk
      YU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFj
      TUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJG
      eWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUmZwM1BBYW4z
      cHpQdGtLWlVFNWZpSlM4QVIxYjJzeVUzMXhzVVdkZEdLSlYwa3ZPdzJsb3pnQWc4Q3ErOWsKUmkr
      SXZWRkZtRU5KUnBHVlRkcFArYjcybzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVk
      RHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVV3OHQ4RWc4WjB2T0c1Vjl4bkJ1V2tGTDFhSWN3
      Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ0dVU2xjMGxvMG1Yb2psRWRKVDBDVzVUUVNlYU4rNkZO
      YXYzZzN0Z1I1VkFDSUhjRGpJTy8KVGFZSEh5ZFlqVXFIZVYzb0kvYmFMZkg4bkJlYmptODVqM210
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAES
      GhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggS
      BggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAES
      AggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQ
      Eg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5
      EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMq
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYa
      BkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGk4K
      EE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRt
      aW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMS
      CQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZB
      ZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
