apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.63.78.155:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIPWvauWGpUVDAIzWLjFG5Ot88jiYJhExtbd49ieTh0kgEqBeCp1eCppeCngKWggBEAEaBgji
      jK6iBiIKc3lzY2hhbm5lbCpAODI0ZTkzZjk1MmM3YThjM2Y5ZTcyZWI1MjJjOTBiZmFlYWQyOTgy
      OTRjZTg0Yjg0NDM3ZjVmZGM1MmQyNWQzMRIaEhgAJtHkoEeZwF0Za39Nmu4OySCZZJCepLUSnV0K
      ml0Sl10Suy8KC0NvbnNvcnRpdW1zEqsvEuAuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0Sxi4SuxcK
      D21hbnVmYWN0dXJlck1TUBKnFxqvFQoDTVNQEqcVEpwVEpkVCg9tYW51ZmFjdHVyZXJNU1AShgYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVPN2R1RHBJUFU5
      cWU5VzRkcVRQdE5mWGVSODB3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpNd05ESTRNRGd5TnpNeldoY05Nall3TWpFMU1EZ3lOek16V2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJDZFR1R1YrTDRt
      TW95cFFZZklLeFFzbmlpUkppWW1IYjdONwpSQ1FMSW5FSG5ZenM1NU1YckQwOGNmM3kzbXFNTEdk
      a0ZYZjFNS2NWNzc2VWtFeVFjYk9qUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWl5ZEZKbHFzNW5FR0EKdjJQdlY1S3VqeFpGZkRB
      S0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQW5TdmZRdWdVL2FzR0tNLy9VSGRzb2dhZAprRC9kQlp5
      WmJYY0lyZGV1OWZvQ0lRRFdRRWp4RFNHUG1RUG8xdTErNXNHY3lhRStGRHpzRnVvTXVpREIxRmpo
      CklRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVEK1RRNmZBdGlsdU5oTkhDMjVWbEdxajRhZ013Q2dZ
      SUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURF
      UE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERB
      YUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05ESTRNRGd6TXpB
      d1doY05NalF3TkRJM01EZ3pPREF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFj
      VEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJ
      eEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZ
      RFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSQp6ajBEQVFjRFFnQUU4SXVuTFpxT2ovNFRJNGdCd21qejZ4b0Mrb1p4YW9tOERjVWRLYXRq
      QUJQS0lYbGJUSG8rCmJYYTlwdW16UTFBSXM3Q2I3MjhqZXBiZE9MYTBRL3JFcTZPQ0FTSXdnZ0Vl
      TUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlMw
      VUNPL2tXYjA4emJPR1I5MkFMYy9oSm9YUmpBZgpCZ05WSFNNRUdEQVdnQlFpeWRGSmxxczVuRUdB
      djJQdlY1S3VqeFpGZkRBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAyT0dZM04yWTFPRGxp
      TFdzNU5XZG5NSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWww
      SWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9p
      YldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVk
      V1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9Q
      UVFEQWdOSEFEQkUKQWlCUnFGYzNZVDNYZ2NVUnA2K2xTNXNGOG0rQjVQNU9QL1kzZGtmd2hmWWVJ
      Z0lnSUNJOXIvcEtMeGdSeGdOaApCa25GcTZYWGFYMlNlTFNRYzd0STVENHpHUzQ9Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqGBi0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVU83ZHVEcElQVTlxZTlXNGRxVFB0TmZYZVI4MHdD
      Z1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGph
      REVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhI
      REFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nak13TkRJNE1EZ3lO
      ek16V2hjTk1qWXdNakUxTURneU56TXpXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVD
      QXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1Z
      V04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpC
      eXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkNkVHVHVitMNG1Nb3lwUVlmSUt4UXNuaWlSSmlZ
      bUhiN043ClJDUUxJbkVIbll6czU1TVhyRDA4Y2YzeTNtcU1MR2RrRlhmMU1LY1Y3NzZVa0V5UWNi
      T2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0Ex
      VWREZ1FXQkJRaXlkRkpscXM1bkVHQQp2MlB2VjVLdWp4WkZmREFLQmdncWhrak9QUVFEQWdOSkFE
      QkdBaUVBblN2ZlF1Z1UvYXNHS00vL1VIZHNvZ2FkCmtEL2RCWnlaYlhjSXJkZXU5Zm9DSVFEV1FF
      anhEU0dQbVFQbzF1MSs1c0djeWFFK0ZEenNGdW9NdWlEQjFGamgKSVE9PQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tChoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMS
      EQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoT
      EhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAa
      ExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAa
      FRITCg9tYW51ZmFjdHVyZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMSqhYKCmNhcnJpZXJNU1ASmxYa
      txQKA01TUBKvFBKkFBKhFAoKY2Fycmllck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlCOXpDQ0FaNmdBd0lCQWdJVVVnQlhKMzJlVStKT1J1VkwyMHZ1M2tVVHU4b3dDZ1lJS29a
      SXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1
      allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekEwTWpnd09ESTRNemhhRncweU5qQXlNVFV3T0RJ
      NE16aGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdO
      VkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJF
      dVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVF2VFRj
      cGNCdmRab0RRcXQ4STEwVzFoZEpucngyenJkZTU2OU9GRjZ0d0kwMXNCamc2dnBjdHd5ejVVWFlP
      Ckg3VDd1cWVNZVlBMXVBcnpNeUhNUGVqNm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRH
      QTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVNjhTUVNmQXFjL0JKS1dmdENTbjJGbjZU
      K0R3d0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdEN2tOUjNrRGk3SFppT0kyaFBkRUxCc3dxQXVl
      MGR1ODBZV3NJbFRIc2U0Q0lGWHBRYjl3ClJuaDJzU1RvWTBXK1lSTEJyNFMvelliUU9EV0lENGt1
      aHBMdAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDN1RDQ0FwU2dBd0lCQWdJVUQyVFNyTmJWRW5WRUpXMUp5dXBBUnU4YUpIY3dDZ1lJ
      S29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFE
      REE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekEwTWpnd09ETTBNREJhRncweU5EQTBNamN3
      T0RNNU1EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4
      TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1
      TUE0R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUU3Y4V2JGajRjajRCeFh3NzNT
      SXZkCnlqcFczSEFmeXYvMlJHSVZHWTk5bmllVGhLM0Y0MUdXVE0xUTVrc09OS3E1eGx3bkxjM00z
      bHpKYlN6VCtuQnEKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIv
      d1FDTUFBd0hRWURWUjBPQkJZRQpGQzk0cEJvS280YklPT3Jma29zeTkyLytGZDlvTUI4R0ExVWRJ
      d1FZTUJhQUZPdkVrRW53S25Qd1NTbG43UWtwCjloWitrL2c4TUNRR0ExVWRFUVFkTUJ1Q0dXTmhM
      WFJ2YjJ4ekxUVTJZMk5tTjJaak5HUXRORzVrYUhjd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5Smhk
      SFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lh
      R1l1UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJ
      am9pUVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0Nn
      WUkKS29aSXpqMEVBd0lEUndBd1JBSWdURUQzZ1hlWjh0c2lub3l2ZmlhK05vK05TUUYrSHp6azFI
      STlLQ0NleTZRQwpJRG5zT01mVHNlQ0FGbVAyNjVmN1RVVzRIZ3dUUlRIR2VDbWJDUUV1aTNLNQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK5QUtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQjl6Q0NBWjZnQXdJQkFnSVVVZ0JYSjMyZVUrSk9SdVZMMjB2dTNr
      VVR1OG93Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1S
      Y3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBME1qZ3dPREk0TXpoYUZ3
      MHlOakF5TVRVd09ESTRNemhhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIy
      NWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1C
      VUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkMKQUFRdlRUY3BjQnZkWm9EUXF0OEkxMFcxaGRKbnJ4MnpyZGU1NjlPRkY2dHdJMDFzQmpn
      NnZwY3R3eXo1VVhZTwpIN1Q3dXFlTWVZQTF1QXJ6TXlITVBlajZvMEl3UURBUEJnTlZIUk1CQWY4
      RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVTY4U1FTZkFxYy9C
      SktXZnRDU24yRm42VCtEd3dDZ1lJS29aSXpqMEUKQXdJRFJ3QXdSQUlnRDdrTlIza0RpN0haaU9J
      MmhQZEVMQnN3cUF1ZTBkdTgwWVdzSWxUSHNlNENJRlhwUWI5dwpSbmgyc1NUb1kwVytZUkxCcjRT
      L3pZYlFPRFdJRDRrdWhwTHQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIzCgdS
      ZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRl
      cnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioS
      IAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQS
      KBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFu
      bmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlu
      cyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5l
      bC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMSkysKB09yZGVyZXIShysS
      yhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQSrRQKDnN1cHBseWNoYWluTVNQEvEF
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBRENDQWFhZ0F3SUJBZ0lVRTE0aDNiYW5i
      SnRvTFNyM0lzYmRURnFQYUlJd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhE
      ekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtE
      QWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05N
      ak13TkRJNE1EZ3lOakkxV2hjTk1qWXdNakUxTURneU5qSTFXakJlTVFzd0NRWURWUVFHRXdKSFFq
      RVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJB
      b01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1C
      TUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJEYTFHVkk1dks3eC81c1h5bjhjMjl1Z2g5
      TFNGTWhqYythOS9OWEdRMG9QeEpjeEs5blEKZEJ3M2VVY0hjTmJraHRIWGpBTzcrd1g3bmZNdDdy
      YzZiUHlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1C
      MEdBMVVkRGdRV0JCUXJnR1duYk5YcHFkSmdiUDFPbnRqOFIrVVloakFLCkJnZ3Foa2pPUFFRREFn
      TklBREJGQWlBT3hZSmU1QlBOcGVIOXZnWnlvKzA4VmRUTnFLam41QVRrQ0h5dmhaZ0gKaUFJaEFK
      TFI3VG13dEdseC9oOVNrK3FkVmJBUTJkOEFWQWFRRmNQUkpZaEZDQkllCi0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQW9lZ0F3
      SUJBZ0lVZFpVZWUxNFNpNFNqeTYxNFVXSktMS0ZucmhRd0NnWUlLb1pJemowRUF3SXcKWGpFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5
      dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdG
      cGJpMXVaWFF3CkhoY05Nak13TkRJNE1EZ3pNakF3V2hjTk1qUXdOREkzTURnek56QXdXakJzTVFz
      d0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJB
      d0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3VmhaRzFwYmpFZU1Cd0dBMVVFQXd3
      VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemow
      REFRY0RRZ0FFVURsVFlOZmIrTTQ0cXJmbHRRcnJ4OWU2VWVxMnVwelUKbjRzcmdXZGdVZFAwK1R4
      ejJJaVh3MnBvM0xjWi9FS0hJRFJLTUJOUVNieldYM2dqSW9ZQUc2T0NBUk13Z2dFUApNQTRHQTFV
      ZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJReUhvMHl2Wk8v
      ClJvNDg2bnpCYXI4c05OUGNzREFmQmdOVkhTTUVHREFXZ0JRcmdHV25iTlhwcWRKZ2JQMU9udGo4
      UitVWWhqQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kwM09UazVOelUwTmpVdGJtSTJiamd3
      Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1Vp
      TENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkdsaGRHbHZiaUk2SWlJc0ltaG1Ma1Z1
      Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdOb1lXbHVMVzVsZENJc0ltaG1MbFI1
      Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRgpBaUVBZ1YxaG5LN3RKayt0
      VDY2M2JtUG5NWkRxMVVUZmt2WEpKQkM4cUFsOFUwY0NJSGlEU21BeExHRVJyU1ZxCldnNThFYW8x
      YVd4aUNLVTRNb1JIblpqQnNKaGUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIG
      U0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBRENDQWFhZ0F3SUJBZ0lV
      RTE0aDNiYW5iSnRvTFNyM0lzYmRURnFQYUlJd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVF
      QmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3
      RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVa
      WFF3CkhoY05Nak13TkRJNE1EZ3lOakkxV2hjTk1qWXdNakUxTURneU5qSTFXakJlTVFzd0NRWURW
      UVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhF
      REFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdOb1lXbHVM
      VzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJEYTFHVkk1dks3eC81c1h5
      bjhjMjl1Z2g5TFNGTWhqYythOS9OWEdRMG9QeEpjeEs5blEKZEJ3M2VVY0hjTmJraHRIWGpBTzcr
      d1g3bmZNdDdyYzZiUHlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIwUEFRSC9C
      QVFEQWdHbU1CMEdBMVVkRGdRV0JCUXJnR1duYk5YcHFkSmdiUDFPbnRqOFIrVVloakFLCkJnZ3Fo
      a2pPUFFRREFnTklBREJGQWlBT3hZSmU1QlBOcGVIOXZnWnlvKzA4VmRUTnFLam41QVRrQ0h5dmha
      Z0gKaUFJaEFKTFI3VG13dEdseC9oOVNrK3FkVmJBUTJkOEFWQWFRRmNQUkpZaEZDQkllCi0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIGCAESAggA
      GhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0VuZG9yc2VtZW50EiwSIggBEh4SCBIG
      CAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3CgdSZWFkZXJzEiwSIggBEh4SCBIG
      CAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3CgdXcml0ZXJzEiwSIggBEh4SCBIG
      CAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIV
      EgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoT
      Q2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80
      XzISABoGQWRtaW5zGooSCg1Db25zZW5zdXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3Jk
      ZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURCVENDQXF1Z0F3SUJBZ0lVYXFYV0Z0b2JhS0kyK0w3UEZyeDhTVmlTeDBJd0NnWUlLb1pJemow
      RUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1
      emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRJNE1EZ3pNakF3V2hjTk1qUXdOREkzTURn
      ek56QXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRN
      dlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21W
      eU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdj
      cWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUU9hSjh2aUxQbmtvbEUrUWY1TjVreWR3K1YKTXpS
      Z2VMMmFzRENZYlBTdTJNNGVLekozbmJka2hnSG1SR0RFd01XYlY3dGdicVUwS05FRzcxUytYN09H
      bzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVG
      QndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVHQrWGdZ
      YXhyZ05uY3d1aytaMjk1L3JBNmYKcVRBZkJnTlZIU01FR0RBV2dCUXJnR1duYk5YcHFkSmdiUDFP
      bnRqOFIrVVloakJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1
      WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlI
      Q0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2
      Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVV
      ZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBNmoyenVIMUht
      aUpoCkhLbXdodDNpanpHVnFGczhtVE9iNVNlbUh3dnI1OGtDSUZQOVZuYjZxNnBmdGZ3UUUvMUE4
      K0hEbGtwOXB3NkQKMjlIMWdOSVY0RVVLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0t
      LS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQXF1Z0F3SUJBZ0lVYXFYV0Z0b2JhS0ky
      K0w3UEZyeDhTVmlTeDBJd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFO
      QmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQ
      Y21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13
      TkRJNE1EZ3pNakF3V2hjTk1qUXdOREkzTURnek56QXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIK
      TUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxj
      bVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpk
      WEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUU9h
      Sjh2aUxQbmtvbEUrUWY1TjVreWR3K1YKTXpSZ2VMMmFzRENZYlBTdTJNNGVLekozbmJka2hnSG1S
      R0RFd01XYlY3dGdicVUwS05FRzcxUytYN09HbzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURB
      Z09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJB
      ZjhFQWpBQU1CMEdBMVVkRGdRV0JCVHQrWGdZYXhyZ05uY3d1aytaMjk1L3JBNmYKcVRBZkJnTlZI
      U01FR0RBV2dCUXJnR1duYk5YcHFkSmdiUDFPbnRqOFIrVVloakJCQmdOVkhSRUVPakE0Z2hodgpj
      bVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRY
      Qm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFX
      eHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRY
      QndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhr
      ak9QUVFEQWdOSUFEQkZBaUVBNmoyenVIMUhtaUpoCkhLbXdodDNpanpHVnFGczhtVE9iNVNlbUh3
      dnI1OGtDSUZQOVZuYjZxNnBmdGZ3UUUvMUE4K0hEbGtwOXB3NkQKMjlIMWdOSVY0RVVLCi0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucyIiCgZBZG1p
      bnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYS
      DAoKCgZWMV80XzMSABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9y
      ZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
