apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIHZBaHBSq5wstCHzxopVK6o1F4OwydcNKJyOGZopC42zEpxeCpleCpZeCngKWggBEAEaBgiy
      rrOWBiIKc3lzY2hhbm5lbCpAZjMzOTMyZDU4ZGU5YjQ2YWU0YzkyNWJmZmMxNjYzNmI5OTJhMDUw
      MTlkNDI1MDg3ZTY0NjQyMzhhMTg2MWQ2NRIaEhja0aAEdGupcQmDBzr7ol+/LQGPiwAHHIcSmV0K
      ll0Sk10SjysKB09yZGVyZXISgysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVUlBQWXZoREoyVFUxNmg3a2JldUNzMjRUL3F3d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFeU1ERTFNREl4V2hjTk1qVXdOVEF4TURFMU1ESXhX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJHN2VO
      MGxwWnNCNWtFUDhIZkRJSmFSa2RSaVZGdVZ0VldlOXN2bUNFQ1NOeDlhU0duWjMKa1NUcENBSGhI
      UmJOQ3V1QllTSjRJbkdBT2RyaWRaRzQza3FqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVEZvMldhUnBRR1ozbVRYTUFGTWRtR045
      RWJWakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCRkdNVFFxVWE4b0c5Ym1xdGl4MzU0QmRNY3U1
      VjdneEg4WURlSzFrU3EKWFFJaEFMVXlPNzZmTWRFSlRlRHZseWhDVTVLRTljWEc5MzRNQWpWMFIz
      ZHF2V1ZJCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVZnZxV0RCL2hEZVFmUXdzSElrTHNyVUk4VStNd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFeU1ERTFPREF3V2hjTk1q
      TXdOekV5TURJd016QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFVFRXb1BPelVmUDY3cVhFTXU1N1RuaVAyZUlq
      VmZYVWIKRG5VNE9wa1A5SzRzMXg0eVFwMzlvZXhBVHFDbHZHb1VLdklNaEFkaDFENmNBR2JFQTJP
      UklLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSZlNkQVY0bGNxCjVDQVAvUW9BRTVGdTZDdi9UVEFmQmdOVkhTTUVHREFXZ0JU
      Rm8yV2FScFFHWjNtVFhNQUZNZG1HTjlFYlZqQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xXUjNhM1k0TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQU40NUVYQ0lSRGJGVHZvN1V5bGNOMzBzRUR3TE16OXFWcGFlWk9GL2M0aUVBaUJa
      V2JzWGlVTFVNbnI5CjVkQ00vNkc2bFArNENGZE9nQjNicjJBZDV3cUtNZz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVJQUFl2aERKMlRVMTZoN2tiZXVDczI0VC9xd3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RXlNREUxTURJeFdoY05NalV3
      TlRBeE1ERTFNREl4V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCRzdlTjBscFpzQjVrRVA4SGZESUphUmtkUmlWRnVWdFZXZTlzdm1DRUNTTng5YVNH
      blozCmtTVHBDQUhoSFJiTkN1dUJZU0o0SW5HQU9kcmlkWkc0M2txalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRGbzJXYVJwUUda
      M21UWE1BRk1kbUdOOUViVmpBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQkZHTVRRcVVhOG9HOWJt
      cXRpeDM1NEJkTWN1NVY3Z3hIOFlEZUsxa1NxClhRSWhBTFV5Tzc2Zk1kRUpUZUR2bHloQ1U1S0U5
      Y1hHOTM0TUFqVjBSM2RxdldWSQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxqCEgoNQ29uc2Vuc3VzVHlwZRLwERLlEQoIZXRjZHJhZnQS2BEKwREKGG9yZGVy
      ZXIxLnN1cHBseWNoYWluLW5ldBCKNxrPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlE
      QWpDQ0FxbWdBd0lCQWdJVWZMYlQydzFLa2NKU2xkc0Zaai9iV09BMWtyY3dDZ1lJS29aSXpqMEVB
      d0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpk
      WEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RXlNREUxT0RBd1doY05Nak13TnpFeU1ESXdN
      ekF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZU
      Rzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlN
      U0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Fo
      a2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFsYlg0c3B5NThaeGZxN2ZYa25xZFhsVDVuCnhqYVhs
      OTNMUmdGeC9aUlBXTlE3Q0FwMkVMcFFjbUVza2xTYzRzVlluMFJId0FFTjM1NmpOUy9VeEczRm80
      SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3
      TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNCVW1ZOGdi
      Z0R4emY2UU9zZFJEV2F1bUt5CkFqQWZCZ05WSFNNRUdEQVdnQlRGbzJXYVJwUUdaM21UWE1BRk1k
      bUdOOUViVmpBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpY
      U0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJH
      QjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JX
      VnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pT
      STZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnSGdUNDZETnl4cUs3MGtk
      KwpFOTV3YUJIL0pjU3h1ejFCVTAxNVMwc0FWNDhDSUQwazNBbnU0Y3R3UzdNTjBueGZ3RkVOTlZQ
      Q3NTT2E3YjJMCkUvaUpwMXlYCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIs8ILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVZkxiVDJ3MUtrY0pTbGRzRlpq
      L2JXT0Exa3Jjd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFeU1E
      RTFPREF3V2hjTk1qTXdOekV5TURJd016QXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUWxiWDRzcHk1
      OFp4ZnE3ZlhrbnFkWGxUNW4KeGphWGw5M0xSZ0Z4L1pSUFdOUTdDQXAyRUxwUWNtRXNrbFNjNHNW
      WW4wUkh3QUVOMzU2ak5TL1V4RzNGbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCU0JVbVk4Z2JnRHh6ZjZRT3NkUkRXYXVtS3kKQWpBZkJnTlZIU01FR0RB
      V2dCVEZvMldhUnBRR1ozbVRYTUFGTWRtR045RWJWakEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1
      ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1
      SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmho
      YVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBd1JBSWdIZ1Q0NkROeXhxSzcwa2QrCkU5NXdhQkgvSmNTeHV6MUJVMDE1UzBzQVY0OENJRDBr
      M0FudTRjdHdTN01OMG54ZndGRU5OVlBDc1NPYTdiMkwKRS9pSnAxeVgKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICAChoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsI
      ChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hh
      bm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzIS
      ABoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxK7
      LwoLQ29uc29ydGl1bXMSqy8S4C4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLGLhK7FwoPbWFudWZh
      Y3R1cmVyTVNQEqcXGq8VCgNNU1ASpxUSnBUSmRUKD21hbnVmYWN0dXJlck1TUBKGBi0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVWF0b0hUbUJlK0xTcTlhaHpB
      SHM2d25KeFBTTXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFa
      bUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05N
      akl3TnpFeU1ERTFNak16V2hjTk1qVXdOVEF4TURFMU1qTXpXakJrTVFzd0NRWURWUVFHCkV3SkRT
      REVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJB
      b00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxX
      NWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkpOa1BDaHUvWkFxRGtldlBF
      c3dOM21XamtMemRVMzV0aTVPCkxIVExtRUZYdG5MckxCRU96T0ZjdTU0WjlZZDNXVmh1UWRPcmRP
      dE1XK1RmZG40cHVFU2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJRN0xXakV2Wjh3MDVINQpKUFc0RnBpVm84c0xvakFLQmdncWhr
      ak9QUVFEQWdOSkFEQkdBaUVBOW8zakY4OEQ2REZYOWcxZzlTWGhQNHlaCld0N2crYnhzUUNheHZL
      ZUo1b3NDSVFEMExFajZwNnFuZkVjNVpMTS9JeDN2UzA2NWtSVGxJNjZyL0JqaTVXQXYKSlE9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlERURDQ0FyZWdBd0lCQWdJVUE0N1h6ckxGSSs4WGRTQVZmRlB1ZC9TeHE3c3dDZ1lJS29aSXpq
      MEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJB
      TU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpFeU1ESXdNREF3V2hjTk1q
      TXdOekV5TURJd05UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xq
      TTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJn
      TlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERC
      WkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpq
      MERBUWNEUWdBRU9vanNidUhKbk1QK2t4UWZ6RW5SbGhMYUR1RHZkOU1RUVYxRzF4NkE3Rmh2NEFh
      eEdVTFgKMkxZWUJCRjdOTXZNT291T1djMldpMFZQZTdBdXpqQ3MwYU9DQVNJd2dnRWVNQTRHQTFV
      ZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUThQUmF2c3JF
      NEw2Q2Jad3dKYUZCN0FvRWJCekFmCkJnTlZIU01FR0RBV2dCUTdMV2pFdlo4dzA1SDVKUFc0RnBp
      Vm84c0xvakFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMWFo0ZUcx
      eE1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhK
      MVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFda
      aFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNS
      MWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05I
      QURCRQpBaUFIdFgrWUQ3dmI5eFBzd1JaQ1AxL2Z2RHNwZWRjTXUzdUkwS3BXYmkwQTBBSWdIZG9C
      a3JaT0ZrL1BGSlJYCjMvMFJxdWZ5c1pxQ2JFdzFJdzdFU1Q3RnIxWT0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoYGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNEVENDQWJLZ0F3SUJBZ0lVYXRvSFRtQmUrTFNxOWFoekFIczZ3bkp4UFNNd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekV5TURFMU1qTXpXaGNO
      TWpVd05UQXhNREUxTWpNeldqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5
      YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEps
      Y2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5
      QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSk5rUENodS9aQXFEa2V2UEVzd04zbVdqa0x6ZFUzNXRpNU8K
      TEhUTG1FRlh0bkxyTEJFT3pPRmN1NTRaOVlkM1dWaHVRZE9yZE90TVcrVGZkbjRwdUVTalFqQkFN
      QThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdC
      QlE3TFdqRXZaOHcwNUg1CkpQVzRGcGlWbzhzTG9qQUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUE5
      bzNqRjg4RDZERlg5ZzFnOVNYaFA0eVoKV3Q3ZytieHNRQ2F4dktlSjVvc0NJUUQwTEVqNnA2cW5m
      RWM1WkxNL0l4M3ZTMDY1a1JUbEk2NnIvQmppNVdBdgpKUT09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1
      cmVyTVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21h
      bnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9t
      YW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoP
      bWFudWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKqFgoKY2Fycmllck1TUBKbFhq3FAoDTVNQ
      Eq8UEqQUEqEUCgpjYXJyaWVyTVNQEuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5
      ekNDQVo2Z0F3SUJBZ0lVVTFJalJaQWtmZ3RFTDh6NTJuazZFS2lJd3Fvd0NnWUlLb1pJemowRUF3
      SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allY
      SnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNVEl3TVRVME1qVmFGdzB5TlRBMU1ERXdNVFUwTWpWYU1G
      b3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJr
      eHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNt
      bGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVDgrWThGZkc5cSsw
      ekdQWDRYUzcwRGxDSUkzbkNnYW1aMklXUE9aQjFTUkVOWDhoZXNOVjdNOTZNTC9qeEEKNVRNZWtn
      cU1IVVlObGtqby9qOTR0dTd0bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdF
      Qgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVHMm90VUw1Z3RIUjJnNWdTbENGT004Y3Rlb2t3Q2dZ
      SUtvWkl6ajBFCkF3SURSd0F3UkFJZ2R3b1lKcEtZOFdZU3Z0WHZURytxcExKSFoxYXBrcFdJRHFE
      M0hUWWtTZVlDSUJEM2hxbEUKdElkZFduczB5TldJbWpGMU4zd0xrOWg3UHArU2hzRGdkZUgrCi0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrIILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUM3VENDQXBTZ0F3SUJBZ0lVRmRDOE9rSmRudHQrVnh1U3h6Y055WGpNQ1ZZd0NnWUlLb1pJemow
      RUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1
      allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNVEl3TWpBeE1EQmFGdzB5TXpBM01USXdNakEyTURC
      YU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1
      a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFV
      RUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFZdXVEdzJFV3lIRWJBRENkK3NmbDIKbms4
      d0lzRkpObG5tOWR6OGdHWlF5N3BmMktacHByU1FjMXhXVFFiN3FMNFcxYXVmYmp1KzM4SmZwMXdW
      aWhoeApvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3
      SFFZRFZSME9CQllFCkZGSEdXeG8remJFWGlSTFNoYlRRNVllQzU3VHFNQjhHQTFVZEl3UVlNQmFB
      RkJ0cUxWQytZTFIwZG9PWUVwUWgKVGpQSExYcUpNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6
      TFRaa05HTTJaamMyWkdZdE5XbzVhbXd3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2
      ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1pt
      YVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0
      YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJ
      emowRUF3SURSd0F3UkFJZ01UNm1sdnBwa2ZHbTlPc1RjbmdtNEhMNmJFS2ZKV0dLa1JzalFtMGVy
      RkFDCklIRE10aGRzYlpENzNnY1NNeVR5MXIrV0p2NGtnRi9jcVRJOEJ1d3lFbFF3Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrlBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJVVUxSWpSWkFrZmd0RUw4ejUybms2RUtpSXdxb3dD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURW
      UVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakEzTVRJd01UVTBNalZhRncweU5UQTFN
      REV3TVRVME1qVmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhE
      ekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVB
      d3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpB
      QVQ4K1k4RmZHOXErMHpHUFg0WFM3MERsQ0lJM25DZ2FtWjJJV1BPWkIxU1JFTlg4aGVzTlY3TTk2
      TUwvanhBCjVUTWVrZ3FNSFVZTmxram8vajk0dHU3dG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFR
      SC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVRzJvdFVMNWd0SFIyZzVnU2xD
      Rk9NOGN0ZW9rd0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdkd29ZSnBLWThXWVN2dFh2VEcrcXBM
      SkhaMWFwa3BXSURxRDNIVFlrU2VZQ0lCRDNocWxFCnRJZGRXbnMweU5XSW1qRjFOM3dMazloN1Bw
      K1Noc0RnZGVIKwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcKC0VuZG9yc2Vt
      ZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1JlYWRlcnMS
      KBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVycxIoEh4I
      ARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBII
      EgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVh
      dGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhIS
      CAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8a
      BkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0
      OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFf
      NF8zEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFk
      ZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMa
      BkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
