apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.63.78.155:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIELiJlNUMQaaedMoNCbA3N4tZKdFdikmlmYiI3YqD28gEqJeCp9eCpxeCngKWggBEAEaBgie
      w52iBiIKc3lzY2hhbm5lbCpANGU4YTI5ZDNkNTBmZTcyNzJlMjM2NDAyYzljOTBhYTA4MTFmNTNi
      NTM2OGQzYjAxY2QxY2JmM2NhYjNkYzkyMhIaEhg9BPXOnlKo+zx5k7N8S1BtN7xnuJB+qZ0Sn10K
      nF0SmV0SvS8KC0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SyC4SsRcK
      D21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVVWHlKWWxmY24z
      Zzd4ZGt3eFlXTWVHUlMzeDB3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpNd05ESTFNRFV3TVRVMVdoY05Nall3TWpFeU1EVXdNVFUxV2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHMGVYZ0MwcmZJ
      TE5URlEvYkFvZEFwemhXWlFIcXlNNHV1NApHOFZYVVV1SEhjWFI1bURsRHRuZFlSbXRuYm42UTFo
      aUsrODJOVCsxRG5odUd2QlBvbTJqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU3c2V3JzcHBNbWJYc2IKdk1NMHgrNllhNDZMRURB
      S0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQXFEZ3ZuS1h6U0ljbm4vMWJYdzhHb0h4VQp0bUV3aVUx
      bER0dlIvWTY4TStBQ0lFUVAyeFZtd2NPSVc1eG13Wi9SMFJyUTlYazJYMVBsOWhUakNqWHl0NDNS
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURFRENDQXJlZ0F3SUJBZ0lVQ0llcUUxY2dhK2pzRVBoUmE1ZDBzR1JINC9vd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdOREkxTURVd09EQXdXaGNO
      TWpRd05ESTBNRFV4TXpBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEz
      TGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFN
      QmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFE
      REJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkK
      emowREFRY0RRZ0FFVlRaOEpvaUx5Z0J3QisrTlo5Qk5QRmlsZXBIV1lGUDMydEdTZk9BTUxqVERa
      Y2JVamFuOAp0NG1wMk5SK3pQT3VXMEg1WWNJNjRWMmVpQkZSazE2d29hT0NBU0l3Z2dFZU1BNEdB
      MVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUK0FJYWN5
      NVBQNDNiVG9QTjFFNitVR24vdWpUQWYKQmdOVkhTTUVHREFXZ0JTdzZXcnNwcE1tYlhzYnZNTTB4
      KzZZYTQ2TEVEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMk9HWTNOMlkxT0RsaUxXMXlO
      amQ2TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVk
      V1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZ
      M1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TkhBREJFCkFpQllaaTZNWUllbHZWbEUrcnVwNSszMUVzYWk1bmJTS1VOdWJKOEtvdFFWMVFJZ1cy
      NTNVQnZWQ1VtQkhYd1gKcWlQVksvb0dUV05UQWtzUkRhajA3emMvTjhvPQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVVWHlKWWxmY24zZzd4ZGt3eFlXTWVHUlMzeDB3Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05ESTFNRFV3TVRVMVdo
      Y05Nall3TWpFeU1EVXdNVFUxV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1du
      VnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRY
      SmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NN
      NDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHMGVYZ0MwcmZJTE5URlEvYkFvZEFwemhXWlFIcXlNNHV1
      NApHOFZYVVV1SEhjWFI1bURsRHRuZFlSbXRuYm42UTFoaUsrODJOVCsxRG5odUd2QlBvbTJqUWpC
      QU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdR
      V0JCU3c2V3JzcHBNbWJYc2IKdk1NMHgrNllhNDZMRURBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlF
      QXFEZ3ZuS1h6U0ljbm4vMWJYdzhHb0h4VQp0bUV3aVUxbER0dlIvWTY4TStBQ0lFUVAyeFZtd2NP
      SVc1eG13Wi9SMFJyUTlYazJYMVBsOWhUakNqWHl0NDNSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJl
      ck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVy
      ZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxK2FgoKY2Fycmllck1TUBKnFhrDFAoDTVNQErsU
      ErAUEq0UCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrREND
      QVo2Z0F3SUJBZ0lVY2ZSc1ZQTytRQUtPaFlyQ3hzbmpjTmpGWEN3d0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck16QTBNalV3TlRBek1ERmFGdzB5TmpBeU1USXdOVEF6TURGYU1Gb3hD
      ekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZi
      bVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVEx2RVpkLzlPcUxvWDNw
      U1duVm5JVmNNa0tPUGo1OGxoK2E4dzdwQ2F3WUVtellDeERKRmZOVG5IVlp4R3kKMmNiK3RtYU12
      cFg0VUpYUW1xdlVpNUxHbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgov
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVDMGpnWDZ5U1l2S3IwMWhrTFp6RkNsam1aRDh3Q2dZSUtv
      Wkl6ajBFCkF3SURTQUF3UlFJZ01uSTVTWFBCTW5xdTZ6VDg2K3Y1OUYxTHdoeWVwMFRGVjhtKzN2
      MlozRWdDSVFDdzFRTGEKUnFhMVUxNm9yVmhEclRvdEdLcEtGUTJsc09NS1BDSEpRelFtSmc9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlDN2pDQ0FwU2dBd0lCQWdJVWFyM0o3ZmVGVm5tam9HNS9XZklML2I1SDZJb3dDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNekEwTWpVd05UQTVNREJhRncweU5EQTBNalF3TlRFME1E
      QmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIy
      NWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0Ex
      VUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTZmVSYlZlWWQ5enF1UDRuTnZNZVpnCmVN
      QnRYY1Z3VjdqVWwyZ1VtUmtaV2gvTGJxUlo2SEtPSk1Pa2RhTjB5ZWRzZDNxSy9nUTVFMFZBbzFL
      Sks4YjIKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFB
      d0hRWURWUjBPQkJZRQpGSk1IaytkQWVwOWk2cFFHNzROajNuT0pJUVZDTUI4R0ExVWRJd1FZTUJh
      QUZBdEk0Ritza21MeXE5TllaQzJjCnhRcFk1bVEvTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4
      ekxUVTJZMk5tTjJaak5HUXRjemR4WW1Jd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdS
      dGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29a
      SXpqMEVBd0lEU0FBd1JRSWhBSWJFSlFYN1Z1bXNoMVBrZW1BeXVaOFpnTlRNVEJhQlpiMFVXYW1x
      WGtOOApBaUFUdmRaSTB0djFoNEt2WjFYUERiczk1U3RXZTVuMHQ0K1NNZkh4eHhaZ2ZnPT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVY2ZSc1ZQTytRQUtPaFlyQ3hzbmpjTmpG
      WEN3d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2
      Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3
      RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck16QTBNalV3TlRBek1ERmFGdzB5
      TmpBeU1USXdOVEF6TURGYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVr
      YjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVH
      QTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJC
      d05DCkFBVEx2RVpkLzlPcUxvWDNwU1duVm5JVmNNa0tPUGo1OGxoK2E4dzdwQ2F3WUVtellDeERK
      RmZOVG5IVlp4R3kKMmNiK3RtYU12cFg0VUpYUW1xdlVpNUxHbzBJd1FEQVBCZ05WSFJNQkFmOEVC
      VEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVDMGpnWDZ5U1l2S3Iw
      MWhrTFp6RkNsam1aRDh3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJZ01uSTVTWFBCTW5xdTZ6VDg2
      K3Y1OUYxTHdoeWVwMFRGVjhtKzN2MlozRWdDSVFDdzFRTGEKUnFhMVUxNm9yVmhEclRvdEdLcEtG
      UTJsc09NS1BDSEpRelFtSmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQK
      BkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0Vu
      ZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1Jl
      YWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNo
      YW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFu
      bmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxKTKwoHT3JkZXJlchKH
      KxLKFgoOc3VwcGx5Y2hhaW5NU1AStxYawxQKA01TUBK7FBKwFBKtFAoOc3VwcGx5Y2hhaW5NU1AS
      8QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0FEQ0NBYWFnQXdJQkFnSVVIaW1lZDc0
      UHZCWWZUWnpwcG9XOTQ2K3NrNGN3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhj
      Tk1qTXdOREkxTURVd01EUTRXaGNOTWpZd01qRXlNRFV3TURRNFdqQmVNUXN3Q1FZRFZRUUdFd0pI
      UWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05W
      QkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJa
      TUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkROaXFVY1gxS3Z3Z1RacS9WV1hwK3N0
      eFU3NkhYUzMrN2trMEsrN0lEY2RxcSt3Q0NBawpvTGZ4VExGVzhhblBaeFBIT1VscmJzRnpJQWpm
      NCs0d1FIeWpRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dt
      TUIwR0ExVWREZ1FXQkJScHVGelBOKzVPVE1EM2FqT0tBb3ZEb1J3UVVUQUsKQmdncWhrak9QUVFE
      QWdOSUFEQkZBaUVBbEI3K1B1SkVXSTNjblI0eVYxTXVtUk9WczVNbkhHeWZWRHhwWEU2WQpPYUFD
      SUd0YWJvQTFFcEloc1RNbXViU2VJUFZDWFMzcWxZS29iak9GTG1hcmdBSVoKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoioggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzREQ0NBb2Vn
      QXdJQkFnSVVHMG01YWF6RXV1OURiaGE5RktaZEFNc3BTd293Q2dZSUtvWkl6ajBFQXdJdwpYakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGph
      R0ZwYmkxdVpYUXcKSGhjTk1qTXdOREkxTURVd05qQXdXaGNOTWpRd05ESTBNRFV4TVRBd1dqQnNN
      UXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVN
      UkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUTR3CkRBWURWUVFMRXdWaFpHMXBiakVlTUJ3R0ExVUVB
      d3dWUVdSdGFXNUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3cKRXdZSEtvWkl6ajBDQVFZSUtvWkl6
      ajBEQVFjRFFnQUVjWFIzQVJVUFdkcWJMSWZoUklYK21abnpaQkNpdUU1ZQpseVgvR056a1d0Rzla
      VTNmQ1FaR1lJUWlXVFFYdmF5TWsrUmlpWCthVDdtWElvUWZaNnBycmFPQ0FSTXdnZ0VQCk1BNEdB
      MVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlMvcGJma0h5
      Tk8KWndJQkJZSkxWenA2dlBTdFREQWZCZ05WSFNNRUdEQVdnQlJwdUZ6UE4rNU9UTUQzYWpPS0Fv
      dkRvUndRVVRBagpCZ05WSFJFRUhEQWFnaGhqWVMxMGIyOXNjeTAzT1RrNU56VTBOalV0Y1doeWRq
      Y3dnWWtHQ0NvREJBVUdCd2dCCkJIMTdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRX
      VWlMQ0poWkcxcGJpSTZJblJ5ZFdVaUxDSm8KWmk1QlptWnBiR2xoZEdsdmJpSTZJaUlzSW1obUxr
      VnVjbTlzYkcxbGJuUkpSQ0k2SWtGa2JXbHVRSE4xY0hCcwplV05vWVdsdUxXNWxkQ0lzSW1obUxs
      UjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFCkFpQkFmV1NLdEhRSFZj
      dzZUcm8zamljU2ljSkphN1pRT1NPQmd4QkY5aXFwSXdJZ0hNZlVjYzJpcGFQZ3lab3MKQzdidWlE
      bEdpWEUxR3Bnb0RLU05SakZiZWxzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEy
      EgZTSEEyNTZK8QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0FEQ0NBYWFnQXdJQkFn
      SVVIaW1lZDc0UHZCWWZUWnpwcG9XOTQ2K3NrNGN3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkx
      dVpYUXcKSGhjTk1qTXdOREkxTURVd01EUTRXaGNOTWpZd01qRXlNRFV3TURRNFdqQmVNUXN3Q1FZ
      RFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0
      eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVds
      dUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkROaXFVY1gxS3Z3Z1Ra
      cS9WV1hwK3N0eFU3NkhYUzMrN2trMEsrN0lEY2RxcSt3Q0NBawpvTGZ4VExGVzhhblBaeFBIT1Vs
      cmJzRnpJQWpmNCs0d1FIeWpRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFI
      L0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJScHVGelBOKzVPVE1EM2FqT0tBb3ZEb1J3UVVUQUsKQmdn
      cWhrak9QUVFEQWdOSUFEQkZBaUVBbEI3K1B1SkVXSTNjblI0eVYxTXVtUk9WczVNbkhHeWZWRHhw
      WEU2WQpPYUFDSUd0YWJvQTFFcEloc1RNbXViU2VJUFZDWFMzcWxZS29iak9GTG1hcmdBSVoKLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAES
      AggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAES
      AggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARIC
      CAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1pbnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhII
      EgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zKgZBZG1pbnMaHwoTQ2hhbm5lbFJl
      c3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRt
      aW5zGooSCg1Db25zZW5zdXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3Vw
      cGx5Y2hhaW4tbmV0EIo3GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQXF1
      Z0F3SUJBZ0lVUlYzRmZSL1o1RU1IemdNSXpRUTdkUXZyZnhzd0NnWUlLb1pJemowRUF3SXcKWGpF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxq
      YUdGcGJpMXVaWFF3CkhoY05Nak13TkRJMU1EVXdOakF3V2hjTk1qUXdOREkwTURVeE1UQXdXakJ4
      TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1
      TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lE
      VlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQ0FBUkMyWjFiNWpBK0FYb0t1VGhYam0ycXhKNTkKMHNqUE54T1pZQ1dZ
      S29Ock1KNzIzNmpBcDU2cDE5RUorUkdUNkdEclJBSzV6ZE1PNkpteHVONEQ1c2VJbzRJQgpNakND
      QVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JC
      Z0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUlZqNitLOEhYRVZFY2Vq
      L09rSHdZUEtoMHQKWGpBZkJnTlZIU01FR0RBV2dCUnB1RnpQTis1T1RNRDNhak9LQW92RG9Sd1FV
      VEJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXla
      R1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZ
      WFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBT
      VVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2li
      M0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBaHJsSlMxWWtxKzFqCnJVaHhU
      ZnZDMU94OGd0ZktMYW5jdDdxUG9WMlVkVzBDSUgzeFZaQ0pIT2U4SjdBdHBwWFo0MUVTeDFmVzlP
      VG0Kb0ZjS2xXeEdiNTlNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQXF1Z0F3SUJBZ0lVUlYzRmZSL1o1RU1IemdNSXpRUTdk
      UXZyZnhzd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TkRJMU1EVXdO
      akF3V2hjTk1qUXdOREkwTURVeE1UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVC
      eE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpE
      Z1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFH
      RnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUkMyWjFiNWpBK0FY
      b0t1VGhYam0ycXhKNTkKMHNqUE54T1pZQ1dZS29Ock1KNzIzNmpBcDU2cDE5RUorUkdUNkdEclJB
      SzV6ZE1PNkpteHVONEQ1c2VJbzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0Ex
      VWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1C
      MEdBMVVkRGdRV0JCUlZqNitLOEhYRVZFY2VqL09rSHdZUEtoMHQKWGpBZkJnTlZIU01FR0RBV2dC
      UnB1RnpQTis1T1RNRDNhak9LQW92RG9Sd1FVVEJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1T
      NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpT
      NWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0
      aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdG
      cGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdO
      SUFEQkZBaUVBaHJsSlMxWWtxKzFqCnJVaHhUZnZDMU94OGd0ZktMYW5jdDdxUG9WMlVkVzBDSUgz
      eFZaQ0pIT2U4SjdBdHBwWFo0MUVTeDFmVzlPVG0Kb0ZjS2xXeEdiNTlNCi0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucxoiCglCYXRjaFNpemUSFRIL
      CAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zIioKD0Js
      b2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJ
      CgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoG
      QWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxomCgxDYXBhYmlsaXRpZXMS
      FhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoG
      QWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQ
      T3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
