apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: solo

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.66.8.13:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaICEZ7ziRwI3fBM8UhORE88BMR+3Bw79dK4KIR0PzPnzuEpBMCo1MCopMCngKWggBEAEaBgiM
      h9acBiIKc3lzY2hhbm5lbCpAMGQyZDkyMzUxNWE4OGQ0NzQ5ZDM5N2Q3OTk0NmI4MzgwOTg4N2Fk
      MWY2YTlkZjRmNzNjMDFlZTI4OTVlMzI2NBIaEhh+XlnN0ddbuukGvDKMpGeU6/nF3ZhzUNASjUsK
      iksSh0sSgRkKB09yZGVyZXIS9RgSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVTkNxK0VJa20yS01zRmJMRDF6RVlWRlYwUy9Bd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFeE1EUTBOakl5V2hjTk1qVXdPVE13TURRME5qSXlX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGVDI0
      Zkt5ZjhCc1BzY1FtVXNEL3RGQUgraWlHOURRL016d1hYaVFIUXEwdGpqMEVGdlkKNXR1RC9oQ3N1
      dm4vTTZqb1pTL1JpMkhlTFllbVJ4UU1mUStqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0xIVVBTSkE1ZmJ4MEk5TnlMaXhETjhK
      THJSREFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCZTMzV1IrZUxyeGU3TFljS0U2V2crdjVOK2k3
      OE1aOXFBMlhzMmV6Mi8KeHdJZ1ZsZXRGaXpnZHdxczEzSUJiSWdTMExoc3RSMlprYUxBS0I3eEtX
      Tm5KRlE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9lZ0F3SUJBZ0lVQWdJNTRSNHd5TXYxa0RNcmZJQm5EOFo3T09Zd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFeE1EUTFNakF3V2hjTk1q
      TXhNakV4TURRMU56QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOXplN2ZHcGQ5V0h5V09GektUTnNSMWpCdlp4
      dy9zODMKMTRwUEZSZHFBcVdkRkRvbm4zMzJxNnRiYUlGelRlRUxGdmVvdy9hRitKRXFLTUxZcDFw
      TUVxT0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRQWJnN2ZJY1RGCkZaS0hDc2lhSWdvaXJGckV6VEFmQmdOVkhTTUVHREFXZ0JT
      TEhVUFNKQTVmYngwSTlOeUxpeEROOEpMclJEQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kw
      NFpEYzNORFUyTlRrdGRHNDViV1l3Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBcTAwWDhMd3J2bnVBSTQ5T3BaSEQ2TStldjVOditwYmt6Wkl3cG1weDNad0NJRnRL
      VDZlazZwS3JQbTV2CnpzQlQzYXNMcFEzK1loclI0VEp5U3MrdWpjZUEKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVTkNxK0VJa20yS01zRmJMRDF6RVlWRlYwUy9Bd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFeE1EUTBOakl5V2hjTk1qVXdPVE13
      TURRME5qSXlXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJGVDI0Zkt5ZjhCc1BzY1FtVXNEL3RGQUgraWlHOURRL016d1hYaVFIUXEwdGpqMEVGdlkK
      NXR1RC9oQ3N1dm4vTTZqb1pTL1JpMkhlTFllbVJ4UU1mUStqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0xIVVBTSkE1ZmJ4MEk5
      TnlMaXhETjhKTHJSREFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCZTMzV1IrZUxyeGU3TFljS0U2
      V2crdjVOK2k3OE1aOXFBMlhzMmV6Mi8KeHdJZ1ZsZXRGaXpnZHdxczEzSUJiSWdTMExoc3RSMlpr
      YUxBS0I3eEtXTm5KRlE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaIQoNQ29u
      c2Vuc3VzVHlwZRIQEgYKBHNvbG8aBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zKgZBZG1pbnMSvS8KC0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNv
      cnRpdW0SyC4SsRcKD21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFj
      dHVyZXJNU1ASgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFn
      SVVIbFZFTkpTeWdkOGlRV2p6YS9zZk9xZnlhaFF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0Ex
      VUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1S
      VXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdO
      MGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qRXhNRFEwTnpJNFdoY05NalV3T1RNd01EUTBOekk0V2pC
      a01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFa
      YWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJF
      dWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJ
      QUJOMlpRRFEvd2o2UWxSNVZTelFQcG54VVJ3MS9FNkhERGpkVQp3Rm9MOWhYVkVzS0NwMHVGR2Jl
      QVpjNjgxVWhKcGVWVmNmQUNwVUNYQWpSMEFkMFdzdldqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFN
      QkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFNUVXJ4d2NZa1ovbmwKRVcx
      em96eTBPOXhuSERBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTRZbWFEWEI4TDRuQnFVeWhuNjhH
      ZjhScApDZFBZT0c5VGdHUXRBYnpCMGljQ0lFTDY2KytMdG9wc25Rd2N1a0htSkgvSDZBOG9xUTJN
      WnU1Q0QvbHBsSUNECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSURFRENDQXJlZ0F3SUJBZ0lVTnArUm9NM1I0ZzMwelNucUNEbml1enpQ
      Q1Rvd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAx
      Y21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5
      WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakV4
      TURRMU16QXdXaGNOTWpNeE1qRXhNRFExT0RBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZ
      QmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZq
      ZEhWeVpYSXhJekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlN
      Ujh3CkhRWURWUVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6
      ajBDQVFZSUtvWkkKemowREFRY0RRZ0FFaitTK0JYZlMxR2JzUnpsTytVOHM5QlI0S0hQNDRwSlFt
      ek16a3hpWnhFSEdZMHg1RzVjSwpUM1l5b0VJZmJma3BhLzdiRWJ5YWtmYzc4cWc4Zi9CRmhhT0NB
      U0l3Z2dFZU1BNEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWRE
      Z1FXQkJSbGFTNGRsRGZ5T1dleWxrQUlzVS9pYnMvSkpqQWYKQmdOVkhTTUVHREFXZ0JUU1RVcnh3
      Y1lrWi9ubEVXMXpvenkwTzl4bkhEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMU9XUTRO
      elUwTnpnMkxXZG1jSEJ3TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZ
      eTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFX
      OXUKSWpvaWJXRnVkV1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFX
      NUFiV0Z1ZFdaaApZM1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0Jn
      Z3Foa2pPUFFRREFnTkhBREJFCkFpQmlTMlZkVnRTRGxXM3dxdW5QZzVIZ2YrVlMyRTNEVC8xbkQz
      enA4aFdzWVFJZ0tSTUNuTm5SUzNmWnhxQmQKdDhiS3FETVZVVUhNN1RiU1YvbldaMkxGbFMwPQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVIbFZFTkpTeWdkOGlRV2p6YS9zZk9x
      ZnlhaFF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRI
      VnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1q
      RXhNRFEwTnpJNFdoY05NalV3T1RNd01EUTBOekk0V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1B
      MEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRF
      MWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERC
      Wk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOMlpRRFEvd2o2UWxSNVZTelFQcG54
      VVJ3MS9FNkhERGpkVQp3Rm9MOWhYVkVzS0NwMHVGR2JlQVpjNjgxVWhKcGVWVmNmQUNwVUNYQWpS
      MEFkMFdzdldqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdH
      bU1CMEdBMVVkRGdRV0JCVFNUVXJ4d2NZa1ovbmwKRVcxem96eTBPOXhuSERBS0JnZ3Foa2pPUFFR
      REFnTklBREJGQWlFQTRZbWFEWEI4TDRuQnFVeWhuNjhHZjhScApDZFBZT0c5VGdHUXRBYnpCMGlj
      Q0lFTDY2KytMdG9wc25Rd2N1a0htSkgvSDZBOG9xUTJNWnU1Q0QvbHBsSUNECi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEK
      D21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMK
      D21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARIC
      CAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAES
      AggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxK2FgoKY2Fycmllck1TUBKn
      FhrDFAoDTVNQErsUErAUEq0UCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVRXBqSDgxQ0xMdUlOUlhxSVZqbXJDdHhhS2M4d0NnWUlL
      b1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUURE
      QTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXlNVEV3TkRRNE16TmFGdzB5TlRBNU16QXdO
      RFE0TXpOYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5C
      Z05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09Z
      MkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU1ds
      bGJhY25hbmlrOVdmdGVESHE3U1BHZ2R3c3BnN2Q1VnFKcnI5UVMxRldQZkNWYkN6UXpyeUdQTWty
      em0KT1lrdDBpWnFXWVNmK09QODllcTF5OUhkbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01B
      NEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVXVThBdGlEdFRxQ3M1RUx5MTlYQm8y
      TmxFVHN3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFOZlNOU01ueVBzTXVQN25PRVRONUJjb1Vw
      QTdkb1FubXY1Nm90NjNiUk5wQWlCZVg1T00KUnVCbVFKd1RnRmgzclFpb25RWFBRdkN5Qnp1Z2Ra
      MEp0RUZpQUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDN2pDQ0FwU2dBd0lCQWdJVUxwZ2R5QUdXWW9Ea0pkTStoWllNbkdOQXMv
      NHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZR
      WURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV5TVRFd05EVTBNREJhRncweU16
      RXlNVEV3TkRVNU1EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1D
      OHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJX
      RmtiV2x1TUE0R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21s
      bApjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUbXhHK2piRlI4SmxE
      VU5ySm5XY0xnCmpPOTdOSHJaUElna0s2VjlzTXowWmt6Q0pqU3E4a280RXFkazB0YjlnWUdDQ0Fs
      SEpVWHVkTlgyYzlQS0IzRGQKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFV
      ZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpGSUJVRGIyOUc4aGFhN2RRdlNSZ2RpYW1jMVFZTUI4
      R0ExVWRJd1FZTUJhQUZGbFBBTFlnN1U2Z3JPUkM4dGZWCndhTmpaUkU3TUNRR0ExVWRFUVFkTUJ1
      Q0dXTmhMWFJ2YjJ4ekxUZGpOMlEwTlRRME9EZ3RZM0F5WjJZd2dZMEcKQ0NvREJBVUdCd2dCQklH
      QWV5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25W
      bElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1
      CmRFbEVJam9pUVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRp
      Zlgwd0NnWUkKS29aSXpqMEVBd0lEU0FBd1JRSWhBTExpZDEyZmZnenNjYkZPVzFnblcwazRXekRF
      ZHlHd0FQUStqRytkQ3RKTQpBaUFiNWdkQVk2M20vVk1MdjRqYnBiLzFIdzRsd2dSeUkwVzV3OFpq
      R2xrTUxnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0t
      LS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVRXBqSDgxQ0xMdUlO
      UlhxSVZqbXJDdHhhS2M4d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFO
      QmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRE
      WVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXlNVEV3
      TkRRNE16TmFGdzB5TlRBNU16QXdORFE0TXpOYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQK
      VlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnlj
      bWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJC
      Z2dxaGtqT1BRTUJCd05DCkFBU1dsbGJhY25hbmlrOVdmdGVESHE3U1BHZ2R3c3BnN2Q1VnFKcnI5
      UVMxRldQZkNWYkN6UXpyeUdQTWtyem0KT1lrdDBpWnFXWVNmK09QODllcTF5OUhkbzBJd1FEQVBC
      Z05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVX
      VThBdGlEdFRxQ3M1RUx5MTlYQm8yTmxFVHN3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFOZlNO
      U01ueVBzTXVQN25PRVRONUJjb1VwQTdkb1FubXY1Nm90NjNiUk5wQWlCZVg1T00KUnVCbVFKd1Rn
      RmgzclFpb25RWFBRdkN5Qnp1Z2RaMEp0RUZpQUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      ChoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZB
      ZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlu
      cyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3
      CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoG
      QWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAES
      BBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxpO
      ChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8zEgAaBkFk
      bWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRh
      SGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRt
      aW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0
      ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
