apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.63.78.155:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIMtRL8cJeSZCHKviLB/fYxm9OwO2Fq4FItCLoiV2WbRfEppeCpdeCpReCngKWggBEAEaBgjS
      7IyjBiIKc3lzY2hhbm5lbCpAYTQxYzI4ZmJmN2VlMjAxN2RlOGEwYWU5ODgxNDhmYjBhNzg2ODlm
      OWU1NDkyZWEwZjBkMjdiNDZkZDcyMmE0MRIaEhi/Gh48gAcoMFbC3lAPqt7pXWcdHpj6z/gSl10K
      lF0SkV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVTGU5Z21wSDJPcVZVdUdwUHRiNUt0M1pnWWU4d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRFMk1EY3pPVEF3V2hjTk1qWXdNekExTURjek9UQXdX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJLTmhu
      ekF6NHNVM2RJNkhQZUZXbXEvNmF2WTNEQUlpek11RWM2ZWlkMkFzLzV4czluTnEKdlJFNjlKcG90
      RFhKY0IxNWZQOVhQbWZNZVl5WjdERmRmTmFqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVG1WR0dOTENPdjJKUjErNHoyMHZpd2Y4
      NkhlekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQS96dHpwS0RlZWJyZ2o5bk1yWDI5cEZuTkpk
      S2IrYUswUEFVcUFpMksKTjZFQ0lHcnZaZE5WVlFMRGVqMDJSOWVONzN6bUdUdlRQYWNVLzVlWldm
      VHB1NnlhCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9lZ0F3SUJBZ0lVU3B0ajZObENjbWErcitTL0dySlNudmZQTFZrd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRFMk1EYzBOVEF3V2hjTk1q
      UXdOVEUxTURjMU1EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFbDk3bUFWVklOLy84ckRvaWM4dXpBaUNidmtw
      YTRNOFkKWmVOS0VxTFY1QUhJbW5WL1puWERNRTBXcjBjWGNqTldiZmJtcHpVYUhkZjZLdCt5U2ZD
      cTBxT0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTSm5kdEZmWWpCCjFEQi9INTM5L3A4N1pOdDdlekFmQmdOVkhTTUVHREFXZ0JU
      bVZHR05MQ092MkpSMSs0ejIwdml3Zjg2SGV6QWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kw
      M09UazVOelUwTmpVdFpuWnVlR293Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBMDZkY0JpdXhsK3ZSdkxCM3lscHJQUEpkeXBUTlh0a1NUZkNZYU0yczRoWUNJSEpC
      OGZleWlja0FLSzRJCnR0MDFWbjVpS0ZtOVZiSjR0c2ZDWEI4RUFuU00KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVTGU5Z21wSDJPcVZVdUdwUHRiNUt0M1pnWWU4d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRFMk1EY3pPVEF3V2hjTk1qWXdNekEx
      TURjek9UQXdXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJLTmhuekF6NHNVM2RJNkhQZUZXbXEvNmF2WTNEQUlpek11RWM2ZWlkMkFzLzV4czluTnEK
      dlJFNjlKcG90RFhKY0IxNWZQOVhQbWZNZVl5WjdERmRmTmFqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVG1WR0dOTENPdjJKUjEr
      NHoyMHZpd2Y4NkhlekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQS96dHpwS0RlZWJyZ2o5bk1y
      WDI5cEZuTkpkS2IrYUswUEFVcUFpMksKTjZFQ0lHcnZaZE5WVlFMRGVqMDJSOWVONzN6bUdUdlRQ
      YWNVLzVlWldmVHB1NnlhCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vu
      c3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCK
      NxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQkRDQ0FxdWdBd0lCQWdJVVNMcVlr
      TUd1bkJyZU4rWGRQWjdqM3h2ckRqd3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURW
      UVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpI
      aGNOTWpNd05URTJNRGMwTlRBd1doY05NalF3TlRFMU1EYzFNREF3V2pCeE1Rc3dDUVlEVlFRR0V3
      SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3
      ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNt
      VnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkNBQVJ1Q013djJOYzRIMlVaOU9GVnRuODNhWko2Cms0TXpVdlpwVDFycXhYOHZKTEhCVnQ1YXRu
      UzlKSS9Tbk02L1RuYzJYeDFZSkhySnp2UmsrMXIrVFBtSW80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFR
      SC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJn
      TlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlR3ZDlyLzhqek1xOTAwUE9BZHFGYXVkQkpWCnNq
      QWZCZ05WSFNNRUdEQVdnQlRtVkdHTkxDT3YySlIxKzR6MjB2aXdmODZIZXpCQkJnTlZIUkVFT2pB
      NGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNK
      aFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZ
      dVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRB
      S0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBb05PR1VmRDR3S0w3egorcGF5RGlOUHovUHJOQm82YmhC
      MURjd1NrbkVkcWdJZ0d0czZQRytTcWpXMEJmZUlTRGgyMWEyWjJpUllSRmMyClRGSU9ISURsUUZn
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlEQkRDQ0FxdWdBd0lCQWdJVVNMcVlrTUd1bkJyZU4rWGRQWjdqM3h2ckRqd3dDZ1lJS29a
      SXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJK
      allTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05URTJNRGMwTlRBd1doY05NalF3TlRF
      MU1EYzFNREF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRB
      dU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21S
      bGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJ1Q013djJOYzRIMlVaOU9GVnRuODNhWko2
      Cms0TXpVdlpwVDFycXhYOHZKTEhCVnQ1YXRuUzlKSS9Tbk02L1RuYzJYeDFZSkhySnp2UmsrMXIr
      VFBtSW80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NH
      QVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlR3
      ZDlyLzhqek1xOTAwUE9BZHFGYXVkQkpWCnNqQWZCZ05WSFNNRUdEQVdnQlRtVkdHTkxDT3YySlIx
      KzR6MjB2aXdmODZIZXpCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0Zw
      YmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01F
      QlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVG
      Ym5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8K
      Wmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBb05PR1Vm
      RDR3S0w3egorcGF5RGlOUHovUHJOQm82YmhCMURjd1NrbkVkcWdJZ0d0czZQRytTcWpXMEJmZUlT
      RGgyMWEyWjJpUllSRmMyClRGSU9ISURsUUZnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChIS
      CgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZB
      ZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rp
      b25zEggaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1p
      bnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1p
      bnMStS8KC0NvbnNvcnRpdW1zEqUvEtouChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SwC4SrhYKCmNh
      cnJpZXJNU1ASnxYauxQKA01TUBKzFBKoFBKlFAoKY2Fycmllck1TUBLlBS0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJVWR1Wks4NGJQWG4zY2s0K083eU5pSFFu
      eGtPUXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJj
      d0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekExTVRZd056UXhNVFJhRncw
      eU5qQXpNRFV3TnpReE1UUmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1
      a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJV
      R0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1C
      QndOQwpBQVJHOG1HM2hWT3ZsdG9YeC9lM0Zlay9oN3dWQlRVMkx1WnRsdis4T2hCeENhcDZZVUsw
      WXV6SjJZK3QrZEdMCnBNU2JGanVxQlk2MEpGd2lhakRvaHFDM28wSXdRREFQQmdOVkhSTUJBZjhF
      QlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVSWdmblh6NjFzRTVp
      aDV3cGJOTWxuOEpZamxrd0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdKRVNKQklpOXlja09PQzNv
      WHlpMjgxTit6cXNucElZZ2lLTHkxNFdBNHQ0Q0lBdm44V0xhClJXVTBxb2JQK1AybGFZWnpxZnlx
      bXBlU2k0Y3pjQi83RlhEcwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlDN2pDQ0FwU2dBd0lCQWdJVWVtci9qTVVTaW01WHdDVDExL3Zx
      aERYM1N3TXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdN
      Qmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5
      TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekExTVRZd056UTNNREJh
      RncweU5EQTFNVFV3TnpVeU1EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkx
      TVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYK
      QkFzVEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZ
      MkZ5Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUN280VlhU
      ajFmc1FSYVdqbVRHWTIrCkJieTVsbjVOM21sV1hyeXUrWVN6bU9jREV2Um51cmo5eTBXU09BQnRh
      aE9tek5VVDVyUUs4OEJUYnpVS1gyb04KbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFN
      QXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpGSllPeFo2SVU2eG81UUc2SHRkdGtnMG96
      T3dCTUI4R0ExVWRJd1FZTUJhQUZDSUg1MTgrdGJCT1lvZWNLV3pUCkpaL0NXSTVaTUNRR0ExVWRF
      UVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxUVTJZMk5tTjJaak5HUXRkM0JpY21jd2dZMEcKQ0NvREJBVUdC
      d2dCQklHQWV5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpP
      aUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIy
      eHNiV1Z1CmRFbEVJam9pUVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlX
      UnRhVzRpZlgwd0NnWUkKS29aSXpqMEVBd0lEU0FBd1JRSWhBUHhBT0tjc3ZyaTRVaVZPa2lWbm16
      Q01Sb0NLNXVtSUxRUnF2SUp5VVd6QQpBaUFMdFN3QmhkTDBodGNVd2lCMG5lRk9PVzNpRE5rbXE2
      eE5lWlZlOTIwcVN3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2
      SuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVZHVaSzg0
      YlBYbjNjazQrTzd5TmlIUW54a09Rd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck16
      QTFNVFl3TnpReE1UUmFGdzB5TmpBek1EVXdOelF4TVRSYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4
      d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3
      SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtq
      T1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUkc4bUczaFZPdmx0b1h4L2UzRmVrL2g3d1ZCVFUyTHVa
      dGx2KzhPaEJ4Q2FwNllVSzBZdXpKMlkrdCtkR0wKcE1TYkZqdXFCWTYwSkZ3aWFqRG9ocUMzbzBJ
      d1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0
      RUZnUVVJZ2ZuWHo2MXNFNWloNXdwYk5NbG44SllqbGt3Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJ
      Z0pFU0pCSWk5eWNrT09DM29YeWkyODFOK3pxc25wSVlnaUtMeTE0V0E0dDRDSUF2bjhXTGEKUldV
      MHFvYlArUDJsYVlaenFmeXFtcGVTaTRjemNCLzdGWERzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBAB
      GgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQ
      GgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFk
      bWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5z
      KgZBZG1pbnMSsRcKD21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFj
      dHVyZXJNU1ASgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFn
      SVVCOEVTeDhxYVY5Y1RQV1pzT0Mzb1M0RlphZmN3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0Ex
      VUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1S
      VXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdO
      MGRYSmwKY2kxdVpYUXdIaGNOTWpNd05URTJNRGMwTURBNFdoY05Nall3TXpBMU1EYzBNREE0V2pC
      a01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFa
      YWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJF
      dWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJ
      QUJCYjRoNS9HclBXejg5R2hSQWI1bERZVUlJckpOdlU2V2VRVwpQT1kzd2d5OVlzTjJGTERBczY5
      QWpIeW96LzlBZGw2ckJNTkF2dm5GUWhJQ3ptbGd1NU9qUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFN
      QkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUlhUaWpETnV4NGV2eWIKRnAx
      eFpkQ3BYWXQ0ZGpBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCaERpcGE5RGJuS3ZBOENiRmwzNkhZ
      TGdpOAphU3pnRzIvcHBQelhlMHpkMHdJZ0J3NE5ucE5RVkoyM1FWYTJ0NUdQVU5rMklpcytpMTky
      aDEvR1FTeGVpOU09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSURFRENDQXJlZ0F3SUJBZ0lVVGNJMWIyVWJKYXBTTE9HN2lRdXZuVE1v
      NXVvd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAx
      Y21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5
      WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdOVEUy
      TURjME5qQXdXaGNOTWpRd05URTFNRGMxTVRBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZ
      QmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZq
      ZEhWeVpYSXhJekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlN
      Ujh3CkhRWURWUVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6
      ajBDQVFZSUtvWkkKemowREFRY0RRZ0FFMCtCcXIvWVZyNTBxZkxLM3BlcnJlK01ra3VtVGxXZXR2
      cE1JeGJtdzFBaWcvZ0lHNkRSQQorK2YzQlUvN09RVVN3ZXdUNjVReVlNMFB6b3UxTHpEcmlhT0NB
      U0l3Z2dFZU1BNEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWRE
      Z1FXQkJUQlRVSmlWeDNRRFFxeXc4NzQrcHhJbGdOWnZEQWYKQmdOVkhTTUVHREFXZ0JSWFRpakRO
      dXg0ZXZ5YkZwMXhaZENwWFl0NGRqQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMk9HWTNO
      MlkxT0RsaUxUaG9lSFozTUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZ
      eTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFX
      OXUKSWpvaWJXRnVkV1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFX
      NUFiV0Z1ZFdaaApZM1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0Jn
      Z3Foa2pPUFFRREFnTkhBREJFCkFpQlRLRi9rNXNzK2MvR0c0Z2xmNXB2alVIZ2Rod2w4U2o0ZFJO
      c3pEamhDdlFJZ0o3ZHg5VlpOWUR2Y0NncjYKYzFtcGNKYjVJMDhjYzRzY0txelV1WlZ1R08wPQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVCOEVTeDhxYVY5Y1RQV1pzT0Mzb1M0
      RlphZmN3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRI
      VnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05U
      RTJNRGMwTURBNFdoY05Nall3TXpBMU1EYzBNREE0V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1B
      MEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRF
      MWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERC
      Wk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCYjRoNS9HclBXejg5R2hSQWI1bERZ
      VUlJckpOdlU2V2VRVwpQT1kzd2d5OVlzTjJGTERBczY5QWpIeW96LzlBZGw2ckJNTkF2dm5GUWhJ
      Q3ptbGd1NU9qUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdH
      bU1CMEdBMVVkRGdRV0JCUlhUaWpETnV4NGV2eWIKRnAxeFpkQ3BYWXQ0ZGpBS0JnZ3Foa2pPUFFR
      REFnTkhBREJFQWlCaERpcGE5RGJuS3ZBOENiRmwzNkhZTGdpOAphU3pnRzIvcHBQelhlMHpkMHdJ
      Z0J3NE5ucE5RVkoyM1FWYTJ0NUdQVU5rMklpcytpMTkyaDEvR1FTeGVpOU09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoP
      bWFudWZhY3R1cmVyTVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgII
      ABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARIC
      CAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAES
      AggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRp
      b25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVj
      dHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEu
      c3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxp
      dGllcxIWEgwKCgoGVjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hB
      MjU2GgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
