apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.63.78.155:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIAmTvyK3tMTQuIwjkRqQjuANFgPFtb8e7B1SX0Pu87PGEppeCpdeCpReCngKWggBEAEaBgjW
      ns2iBiIKc3lzY2hhbm5lbCpAMGU1YjNjNGUwZWY3ZmU1ZWNhMmIxYjdkODg4OWU3OTRjZTEwNjk4
      ODQ4Yjc4MjhjMzAyYzkyYTAwY2NhODIyZRIaEhjCVpAeM1rTdKzCKJD/8qLvVo7ktsksOd8Sl10K
      lF0SkV0StS8KC0NvbnNvcnRpdW1zEqUvEtouChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SwC4SsRcK
      D21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVIR1M5V0psRnhK
      Uml3MlFTWGR6Y3VkSkVFVzh3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpNd05UQTBNRFl4TURRMldoY05Nall3TWpJeE1EWXhNRFEyV2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLVUFyVnY1STVp
      dCtkN2ZYTjhuZlB6ODZ1L3ZIL2dyUjF0dAp1T2F4Q3NHWTdBRmw2RVh3Yjh2UnVCa0ZXalhSeWE3
      SHZNV2pNblJCMmU3MlpNOVVZY1NqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUmVzY0txaEdWdE14OVIKVFJGdThCV1JEZjhyUkRB
      S0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTlHblR5YkowZnZJclZHS3ZZOU5Ceng2VAoreWZxbGJv
      RzFyeW1PRlRTQWZnQ0lHL3hJekQ5dGRpdWYrOEYvMlNjbnM4UnhVZGZYVzJDS2J1VFFCZUFWZDRW
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURFVENDQXJlZ0F3SUJBZ0lVZXFHS0IvODNWdUZqRmxTUFNnWGdSSDNyNmt3d0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdOVEEwTURZeE56QXdXaGNO
      TWpRd05UQXpNRFl5TWpBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEz
      TGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFN
      QmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFE
      REJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkK
      emowREFRY0RRZ0FFZHFLY2VaVFdPWWNIb1drY0QvRjBMU04rb0tzMDU3eUNQUnl2a2V5WXQwUi9a
      R0xSNi9YcQpGZ3RQOXZudk1wb3ZCTFRFTnRsb3JjcXdhVmh6RTE0U1lhT0NBU0l3Z2dFZU1BNEdB
      MVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUQS9DWTFC
      dXk1RUtoQU1QM2MrUnRlbkx5ay96QWYKQmdOVkhTTUVHREFXZ0JSZXNjS3FoR1Z0TXg5UlRSRnU4
      QldSRGY4clJEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMk9HWTNOMlkxT0RsaUxUYzRa
      R3R4TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVk
      V1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZ
      M1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TklBREJGCkFpRUFtV1dBQ2hTYmpqNzVFdUsxY2tvQTV5c1FyR2ZaMWR6NHJldkgzZ3M0Y2RJQ0lF
      RmRiODcza3JLN05iSmYKL2hZUThGYlBMQWdzSHRrdCtEOEd2NkM1TzRTSwotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVIR1M5V0psRnhKUml3MlFTWGR6Y3VkSkVFVzh3Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05UQTBNRFl4TURRMldo
      Y05Nall3TWpJeE1EWXhNRFEyV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1du
      VnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRY
      SmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NN
      NDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLVUFyVnY1STVpdCtkN2ZYTjhuZlB6ODZ1L3ZIL2dyUjF0
      dAp1T2F4Q3NHWTdBRmw2RVh3Yjh2UnVCa0ZXalhSeWE3SHZNV2pNblJCMmU3MlpNOVVZY1NqUWpC
      QU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdR
      V0JCUmVzY0txaEdWdE14OVIKVFJGdThCV1JEZjhyUkRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlF
      QTlHblR5YkowZnZJclZHS3ZZOU5Ceng2VAoreWZxbGJvRzFyeW1PRlRTQWZnQ0lHL3hJekQ5dGRp
      dWYrOEYvMlNjbnM4UnhVZGZYVzJDS2J1VFFCZUFWZDRWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFj
      dHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVm
      YWN0dXJlck1TUBABGgZBZG1pbnMqBkFkbWlucxKuFgoKY2Fycmllck1TUBKfFhq7FAoDTVNQErMU
      EqgUEqUUCgpjYXJyaWVyTVNQEuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekND
      QVo2Z0F3SUJBZ0lVUTFtSC9LSlUxTXV1bWtBbVBPclFuTXIrTmprd0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck16QTFNRFF3TmpFeE5UVmFGdzB5TmpBeU1qRXdOakV4TlRWYU1Gb3hD
      ekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZi
      bVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU0dWV2lWeC8wSmtOVHU2
      d2tuQmVOSlhvdXNJZG9FcXUyZjJYRWxhYkdBczBURnNJNHRlUHM0UXBSOS8xNmoKRXlZVmpxb3Q5
      L2ZUclFWZmp4M3FvQ09sbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgov
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVU1cndsVG84czJUenlheDVxU3BNeUpFYnJqL1l3Q2dZSUtv
      Wkl6ajBFCkF3SURSd0F3UkFJZ1h6UlJDTXhMSXloSXczeHQ4RUJma0JsTmFlYnVXT0tXYnUzWEc4
      R1pLd01DSUdZb2dZRnMKalNrU3JzVEt1V1pIdW8zRHNSUEE5aWF2RWxLUUxCNzI0V3lRCi0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3
      akNDQXBTZ0F3SUJBZ0lVRlUvNnVzM0F6bnFtQWFDY3lwRU1yNFQvU2w4d0NnWUlLb1pJemowRUF3
      SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allY
      SnlhV1Z5TFc1bGREQWVGdzB5Ck16QTFNRFF3TmpFNE1EQmFGdzB5TkRBMU1ETXdOakl6TURCYU1I
      Z3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2Iy
      NHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFVRUN4
      TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RBVEJn
      Y3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFrK2g2ZzdDckozQTAzYmFGSUpzbWgKbTcweW90
      TEc1UlVhQU1EVWticm9YRElkZW5KQlVGZisxK0Jqd21xemRsaHV1Vkt4cjJuMVIyWk9rSnZKejB6
      OQpvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZ
      RFZSME9CQllFCkZCdkRVaEtsUkdwUjJESHh0czFDVU1hZWE3ZUxNQjhHQTFVZEl3UVlNQmFBRk9h
      OEpVNlBMTms4OG1zZWFrcVQKTWlSRzY0LzJNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6TFRV
      MlkyTm1OMlpqTkdRdE9YUnlaSGd3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0YVc1
      QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJemow
      RUF3SURTQUF3UlFJaEFQbzRjSm5NV1pwM0EyQ0VNZzRyV0hmRk9nSGdIeFF4c093d0MrcUMzcjFE
      CkFpQUVqemtLZG1rL21Kay8zZDc5U2xPVEQyTk03TlZhdzl5TmU1WXdqSjBPTlE9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK5QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQjl6Q0NBWjZnQXdJQkFnSVVRMW1IL0tKVTFNdXVta0FtUE9yUW5NcitOamt3
      Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlE
      VlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBMU1EUXdOakV4TlRWYUZ3MHlOakF5
      TWpFd05qRXhOVFZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4
      RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVF
      QXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMK
      QUFTR1ZXaVZ4LzBKa05UdTZ3a25CZU5KWG91c0lkb0VxdTJmMlhFbGFiR0FzMFRGc0k0dGVQczRR
      cFI5LzE2agpFeVlWanFvdDkvZlRyUVZmangzcW9DT2xvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURB
      UUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVTVyd2xUbzhzMlR6eWF4NXFT
      cE15SkVicmovWXdDZ1lJS29aSXpqMEUKQXdJRFJ3QXdSQUlnWHpSUkNNeExJeWhJdzN4dDhFQmZr
      QmxOYWVidVdPS1didTNYRzhHWkt3TUNJR1lvZ1lGcwpqU2tTcnNUS3VXWkh1bzNEc1JQQTlpYXZF
      bEtRTEI3MjRXeVEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI3CgtFbmRvcnNl
      bWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJz
      EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIe
      CAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwS
      CBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3Jl
      YXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMSkysKB09yZGVyZXIShysSyhYKDnN1
      cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQSrRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBRENDQWFhZ0F3SUJBZ0lVRXZVeXBCc2ZCek8wLzNq
      L1pNQk54L2tLSDQ0d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21S
      bGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRB
      ME1EWXdPVE00V2hjTk1qWXdNakl4TURZd09UTTRXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEw
      R0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5
      WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFH
      U000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJLdTNYTHcveWxqYWRwTFBXYkxvZUZDQU80dE9GalRT
      MGlsd2JteUxWaDVFenNzcWZpNUUKUEtLR0E1aEk3aHUwUGR0RE5rRk5BalBsZGQwT0pxR21MaWFq
      UWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVk
      RGdRV0JCUzM4TitQSW14cHJDakM4RkMrbkUwM2tPR0JLVEFLCkJnZ3Foa2pPUFFRREFnTklBREJG
      QWlFQTNRbVJHYmkxdGErRURWQk5Hc1NOMTRBU05JelNQSlEyYWhvVTRsbkUKWjM0Q0lCUTY0TmtM
      ZFVZcjIzR09wN21NVjgxK0RDd1RhUUo4Tm1FT0FIRnRDYUQ2Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQW9lZ0F3SUJBZ0lV
      S3VlNm9JYitUcVVKNDFxZWVZekNSVnlSRkZzd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVF
      QmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3
      RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVa
      WFF3CkhoY05Nak13TlRBME1EWXhOVEF3V2hjTk1qUXdOVEF6TURZeU1EQXdXakJzTVFzd0NRWURW
      UVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURW
      UVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRh
      VzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RR
      Z0FFK0J6Y3BvOUtJWmpwVnBJdkI5MVAxSTNBZU4vRkM2dVIKb1g1VWJmZTJibTVPRFA4dUk3VXBt
      N0NGRFFiT0NZa3U2eDdTa1dGTE1FUWNLamFVbW5YZ2RxT0NBUk13Z2dFUApNQTRHQTFVZER3RUIv
      d1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUZmRtdHBpZGNxCnB0S3lL
      c0VXd3BveHlKNzJsekFmQmdOVkhTTUVHREFXZ0JTMzhOK1BJbXhwckNqQzhGQytuRTAza09HQktU
      QWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kwM09UazVOelUwTmpVdFptd3ljRzR3Z1lrR0ND
      b0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpH
      MXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkdsaGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JH
      MWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdOb1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9p
      SmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRgpBaUVBNWo3RWUvUkhSS2RyQ0VwMFdK
      N1RuQlF3MmJ5RmtnOFUySVNPSVcwTHJ0Y0NJRjlKWDNxUmQ1YzFXYlhECm1McHMrSWdmSk5Hemlm
      a0NaZGFTOTFONndWcGYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2
      SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBRENDQWFhZ0F3SUJBZ0lVRXZVeXBC
      c2ZCek8wLzNqL1pNQk54L2tLSDQ0d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3Ckho
      Y05Nak13TlRBME1EWXdPVE00V2hjTk1qWXdNakl4TURZd09UTTRXakJlTVFzd0NRWURWUVFHRXdK
      SFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdO
      VkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERC
      Wk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJLdTNYTHcveWxqYWRwTFBXYkxvZUZD
      QU80dE9GalRTMGlsd2JteUxWaDVFenNzcWZpNUUKUEtLR0E1aEk3aHUwUGR0RE5rRk5BalBsZGQw
      T0pxR21MaWFqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdH
      bU1CMEdBMVVkRGdRV0JCUzM4TitQSW14cHJDakM4RkMrbkUwM2tPR0JLVEFLCkJnZ3Foa2pPUFFR
      REFnTklBREJGQWlFQTNRbVJHYmkxdGErRURWQk5Hc1NOMTRBU05JelNQSlEyYWhvVTRsbkUKWjM0
      Q0lCUTY0TmtMZFVZcjIzR09wN21NVjgxK0RDd1RhUUo4Tm1FT0FIRnRDYUQ2Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAK
      DnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAK
      DnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoO
      c3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0VuZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggA
      GhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoGQWRtaW5zGooSCg1Db25zZW5zdXNUeXBlEvgR
      Eu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3GtMILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQXF1Z0F3SUJBZ0lVSWM1bzI2WWY1U3NJYk9C
      SjZrY2huQndqKy9Jd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21S
      bGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRB
      ME1EWXhOVEF3V2hjTk1qUXdOVEF6TURZeU1EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJr
      R0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5
      TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU21ha0lZ
      N2NSSkl5emJSbVNhdVVlVXkyT2sKNURqYVhLME54RDhVcnh2ZTJRSXhOUDVoY1ErMC9KNUtsb3FQ
      RzcyZ2FoTXhkSVZZRTJUSFhqKzVIVE9LbzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09v
      TUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhF
      QWpBQU1CMEdBMVVkRGdRV0JCVHlPQVVlOUd6UDZ0TDNVQXQ0bFZjTWNtME0KdXpBZkJnTlZIU01F
      R0RBV2dCUzM4TitQSW14cHJDakM4RkMrbkUwM2tPR0JLVEJCQmdOVkhSRUVPakE0Z2hodgpjbVJs
      Y21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5j
      bUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZ
      WFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndi
      SGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9Q
      UVFEQWdOSUFEQkZBaUVBbjN4T0J6TFk2MDNLCjNxYS91VnlPeXRYSGNpSFIvWmwrVWVkRjY0WE1C
      ZDhDSUNKNHdPU1A0V2N3RWkrOFJtREpPcURiS0dWYSthcnYKTk56dldIM0dXMkZ3Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVEND
      QXF1Z0F3SUJBZ0lVSWM1bzI2WWY1U3NJYk9CSjZrY2huQndqKy9Jd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRBME1EWXhOVEF3V2hjTk1qUXdOVEF6TURZeU1EQXdX
      akJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVa
      Rzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdI
      d1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQ0FBU21ha0lZN2NSSkl5emJSbVNhdVVlVXkyT2sKNURqYVhLME54
      RDhVcnh2ZTJRSXhOUDVoY1ErMC9KNUtsb3FQRzcyZ2FoTXhkSVZZRTJUSFhqKzVIVE9LbzRJQgpN
      akNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJn
      Z3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVHlPQVVlOUd6UDZ0
      TDNVQXQ0bFZjTWNtME0KdXpBZkJnTlZIU01FR0RBV2dCUzM4TitQSW14cHJDakM4RkMrbkUwM2tP
      R0JLVEJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hH
      OXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlI
      c2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpX
      NTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElq
      b2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBbjN4T0J6TFk2MDNLCjNx
      YS91VnlPeXRYSGNpSFIvWmwrVWVkRjY0WE1CZDhDSUNKNHdPU1A0V2N3RWkrOFJtREpPcURiS0dW
      YSthcnYKTk56dldIM0dXMkZ3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoY
      ASAFKICAgAoaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxC
      YXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRt
      aW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucyIiCgdSZWFkZXJzEhcS
      DQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlu
      cyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24S
      FxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggK
      BlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZB
      ZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3
      MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRf
      MxIAGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVy
      cxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZB
      ZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
