apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIPuBO06sYrBIE1vPE1MIdG9EKBmM06yDJlKAHjhDWIoQEqpeCqdeCqReCngKWggBEAEaBgiY
      jOmZBiIKc3lzY2hhbm5lbCpAZDc3OTA1YzNhYmUzOGE4NmE1NjdhNGNkMWM1YjkwNWIzZTg0Yzlm
      M2MxNWRjODM4MjU4M2M4ODk5ZDUxMmE1ZhIaEhizEhytBdDcvWTHTjpgZxgb+utGpvJh3koSp10K
      pF0SoV0SmysKB09yZGVyZXISjysS0hYKDnN1cHBseWNoYWluTVNQEr8WGssUCgNNU1ASwxQSuBQS
      tRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVSzZ4S3ExcHRhNndDRnJKbUZqZ3hZQmFCMXlrd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBek1ESXdNREF6V2hjTk1qVXdOekl6TURJd01EQXpX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJEWG9m
      eCt1RDVJNlhSZHExcWdUbTJNeDEwQkdjbHBISzJ5bnZNNlpYYVNZRFRiaHVSSFkKeHIwSHVibVJW
      M2tZN0xidGs3ZWsrNll2TFpSNlJRQkpkeE9qUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2FJNm0yZEZjeCtSdWsyUVhDYUxsOHVZ
      RjdSekFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQWsweGNaWkMreTNWRGFwem0yREhuRFdZUHRq
      ZzBRKzhBMkVpOEwwdUYKMlNJQ0lRRHZCTVVnWDkyWVlzR1k5UUp1cW9kVXN2YldIejhkQXZsUGEv
      cU52MWpxd1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKiCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNFRDQ0FvaWdBd0lCQWdJVUlyMmpaeWxlVVZTSzc5SGhSdUlkRmxWOG5Y
      MHdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1EQXpNREl3T0RBd1do
      Y05Nak14TURBek1ESXhNekF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUtiRW1sOGYvVFhsRTNCTEpva29BeUJk
      b0xURWNwZU1kCi9tOS84czRyQmJMU0YwRDBuTzlXRjZEUU40d1dNVXF1eCtUSWxjMWkrejE2eVFY
      M25xRHVicU9DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCVHo5L0FuRUhaWgpuUHFDaGpUM3RuV1BlS2xSb0RBZkJnTlZIU01FR0RB
      V2dCU2FJNm0yZEZjeCtSdWsyUVhDYUxsOHVZRjdSekFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDFOalkzWXpZM1ptWTNMWG8xZERoME1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFJ3QXcKUkFJZ1djR0I3bTlOZktWcHgwV2d1Um43c2Y2UXdta2ZxMjNwRFROUGcrdHJzeTBD
      SUdUc3hYQllBMkIxSE5TLwpNK0dFRWZKNDN1amx6Z2NuamtkODlxZ1ZDREFFCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkr1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVUs2eEtxMXB0YTZ3Q0ZySm1Gamd4WUJhQjF5a3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1EQXpNREl3TURBeldoY05NalV3
      TnpJek1ESXdNREF6V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCRFhvZngrdUQ1STZYUmRxMXFnVG0yTXgxMEJHY2xwSEsyeW52TTZaWGFTWURUYmh1
      UkhZCnhyMEh1Ym1SVjNrWTdMYnRrN2VrKzZZdkxaUjZSUUJKZHhPalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNhSTZtMmRGY3gr
      UnVrMlFYQ2FMbDh1WUY3UnpBSwpCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUFrMHhjWlpDK3kzVkRh
      cHptMkRIbkRXWVB0amcwUSs4QTJFaThMMHVGCjJTSUNJUUR2Qk1VZ1g5MllZc0dZOVFKdXFvZFVz
      dmJXSHo4ZEF2bFBhL3FOdjFqcXdRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlu
      cyI7CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZB
      ZG1pbnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZB
      ZG1pbnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZB
      ZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoG
      QWRtaW5zKgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVs
      UmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMhIAGgZB
      ZG1pbnMaihIKDUNvbnNlbnN1c1R5cGUS+BES7REKCGV0Y2RyYWZ0EuARCskRChhvcmRlcmVyMS5z
      dXBwbHljaGFpbi1uZXQQijca0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NB
      cW1nQXdJQkFnSVVUbFhza3B5WTRNeWlSd0x6UjBsQ0l4c1hGTmt3Q2dZSUtvWkl6ajBFQXdJdwpY
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYUXcKSGhjTk1qSXhNREF6TURJd09EQXdXaGNOTWpNeE1EQXpNREl4TXpBd1dq
      QnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpH
      OXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3
      WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BR
      SUJCZ2dxaGtqT1BRTUJCd05DQUFTaVpkNWt2UzdIMlJiNVMyNzZwOTZmV3RSVQpTWmpvVlAwWjBs
      QUo1Mjk0ZCtFRldxS1RpT0pjMUFJdU1tM1hDN1hwWUwxVWFwR2RiTFNFT3IxcHRDQW1vNElCCk1E
      Q0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdn
      ckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTSzVNR1FYQ2VXSWl0
      SzM2a1Vnak5KSzY2eQpTakFmQmdOVkhTTUVHREFXZ0JTYUk2bTJkRmN4K1J1azJRWENhTGw4dVlG
      N1J6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205
      eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1G
      MGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVs
      RUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05
      eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFKVnhLUU44eGR3RzE5L1YKYTN3
      b0VIQ0d4VFFxdTJEbzQwRmY5VlRLQmx1dEFpQTBlRStrN2dLdTc2R1NzU2xKVmJ3YmxUTnNJazlu
      LzRadApxVzhkNld5TVNBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi0wgtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVUbFhza3B5WTRNeWlSd0x6UjBs
      Q0l4c1hGTmt3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21W
      eU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXhNREF6TURJ
      d09EQXdXaGNOTWpNeE1EQXpNREl4TXpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFV
      RUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3
      CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxq
      YUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTaVpkNWt2UzdI
      MlJiNVMyNzZwOTZmV3RSVQpTWmpvVlAwWjBsQUo1Mjk0ZCtFRldxS1RpT0pjMUFJdU1tM1hDN1hw
      WUwxVWFwR2RiTFNFT3IxcHRDQW1vNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBH
      QTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFB
      TUIwR0ExVWREZ1FXQkJTSzVNR1FYQ2VXSWl0SzM2a1Vnak5KSzY2eQpTakFmQmdOVkhTTUVHREFX
      Z0JTYUk2bTJkRmN4K1J1azJRWENhTGw4dVlGN1J6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5
      TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UK
      WTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJ
      am9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhh
      VzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURT
      QUF3UlFJaEFKVnhLUU44eGR3RzE5L1YKYTN3b0VIQ0d4VFFxdTJEbzQwRmY5VlRLQmx1dEFpQTBl
      RStrN2dLdTc2R1NzU2xKVmJ3YmxUTnNJazluLzRadApxVzhkNld5TVNBPT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICAChoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIV
      EgsIChCAgIAxGICAQBoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIX
      Eg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1p
      bnMqBkFkbWlucxK9LwoLQ29uc29ydGl1bXMSrS8S4i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLI
      LhKxFwoPbWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1T
      UBKBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lCQWdJVUdlQSsx
      YjdBLzBKS0Q1bGgxeHhqYkFEa1NuVXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNR
      MGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURW
      UVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApj
      aTF1WlhRd0hoY05Nakl4TURBek1ESXdNakExV2hjTk1qVXdOekl6TURJd01qQTFXakJrTVFzd0NR
      WURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFky
      Z3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRX
      WmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk12SFBs
      ZmZ0TktvbGZnRStIdXVTY2EyRWtiZ21UTXZzYlVlCmxDOGRYN0twL3Y2UDhVTmwyS2ZmemkralVn
      bEZzYW9yUU5LaFZVMW4vbnNpbXU0QlF2YWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0Rn
      WURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJSRFQ1c2hqVTdsQ1VuSwozTnVCQ3M3QlBL
      cGE4akFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUJwemx3MzVic29wWVNlTTB6TXNRbHU2enlZCkdO
      NkZLQjhPVjRYa1ZRem05QUlnUFZlRW84b1AzenZnblp5LzlpSmNUdngrKzVSSXZhVDdTK2tFZmsw
      aWRMcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJREVUQ0NBcmVnQXdJQkFnSVVia2JUOHVBTVhyRnhQMCtDZjE4S3AwVjZCQmN3Q2dZ
      SUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURF
      UE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERB
      YUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1EQXpNREl3T1RB
      d1doY05Nak14TURBek1ESXhOREF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFj
      VEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJ
      eEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZ
      RFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSQp6ajBEQVFjRFFnQUVIVlZkc2pKZXVpOHI3RGZvN3FQV3orUDBiaitobWZkNXlVWUNqVFNY
      bGVxMzhLMVBQTXpMCkdmTVhhRERpcVlEemVtQUVncHMzamp3YTZDd3FxWjlkYktPQ0FTSXdnZ0Vl
      TUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJJ
      ak52dGdaZWV4WXhJWTZldlVuRDJaWG1JaWpBZgpCZ05WSFNNRUdEQVdnQlJEVDVzaGpVN2xDVW5L
      M051QkNzN0JQS3BhOGpBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAzWTJRM1ptUm1PVGMy
      TFRkM1pHMXhNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWww
      SWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9p
      YldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVk
      V1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9Q
      UVFEQWdOSUFEQkYKQWlFQXlTU0g3T2ExeDJhN3g4enhLcDhSTGNnbXNmZGxIdUhMMGp5Nlc5Nmxr
      bVVDSUJjRW9XanFSYjNTVjlMVQo3RWp1MkEwVHdGZUY2Yi9LZU5kTGRMNzVJZGdJCi0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lCQWdJVUdlQSsxYjdBLzBKS0Q1bGgxeHhqYkFEa1NuVXdD
      Z1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGph
      REVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhI
      REFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TURBek1ESXdN
      akExV2hjTk1qVXdOekl6TURJd01qQTFXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVD
      QXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1Z
      V04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpC
      eXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk12SFBsZmZ0TktvbGZnRStIdXVTY2EyRWtiZ21U
      TXZzYlVlCmxDOGRYN0twL3Y2UDhVTmwyS2ZmemkralVnbEZzYW9yUU5LaFZVMW4vbnNpbXU0QlF2
      YWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0Ex
      VWREZ1FXQkJSRFQ1c2hqVTdsQ1VuSwozTnVCQ3M3QlBLcGE4akFLQmdncWhrak9QUVFEQWdOSEFE
      QkVBaUJwemx3MzVic29wWVNlTTB6TXNRbHU2enlZCkdONkZLQjhPVjRYa1ZRem05QUlnUFZlRW84
      b1AzenZnblp5LzlpSmNUdngrKzVSSXZhVDdTK2tFZmswaWRMcz0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQoaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZh
      Y3R1cmVyTVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEK
      D21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIR
      Cg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zErYWCgpjYXJyaWVyTVNQEqcWGsMUCgNN
      U1ASuxQSsBQSrRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      QitEQ0NBWjZnQXdJQkFnSVVBK1JOWm1BM3BneEdaVUdtT2d0SklKcEhTYUF3Q2dZSUtvWkl6ajBF
      QXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVF
      Qnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVq
      WVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFd01ETXdNakEwTURkYUZ3MHlOVEEzTWpNd01qQTBNRGRh
      TUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNN
      Qmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5
      Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTL0pvTUR4anRP
      UTRSWmdoRldDbnBETDZzc3Zyd3JYMCtCTm81d1VQNWE5MVBPRDdWZDU0S2tKbFptKzVYUQpRcHVI
      Rm0zbnNrNnAvVE5UVHVibTAwbklvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWRE
      d0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUxMSWV2ZGlBNS9NWHBnUnB6SnZJU3Z3K0VYMHdD
      Z1lJS29aSXpqMEUKQXdJRFNBQXdSUUlnQ3l5Y244OGg4eVU3YTlrUXkrNE9PQlgxZXlxSnM0bTJQ
      UXgvTld4SW4zQUNJUUQzRjFMWAo5aktIRWZOUitJeEtyemlkdmY5MHdmRk00YUxDbU9nQzBGN0Fp
      QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUM3akNDQXBTZ0F3SUJBZ0lVVGYwM24xUXBTNzJDMnlMNDNiclc2UWtzRXQ4d0NnWUlL
      b1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUURE
      QTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXdNRE13TWpFeE1EQmFGdzB5TXpFd01ETXdN
      akUyTURCYU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhN
      eTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVN
      QTRHQTFVRUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJXWnJMM1d0a3c4Q2l5a2IxVS9X
      TGQKai9ENk9uWEoxeG4rYmJYMlNpUGZ0V1VlQTF2MFRlMWovWE53ME5FQUU2RFR5TkU3ajNndmEz
      bnh0VG80eFNVQQpvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93
      UUNNQUF3SFFZRFZSME9CQllFCkZDQlppcElXeDRINy9qeDBYemUzVUVQYWgwdjFNQjhHQTFVZEl3
      UVlNQmFBRkN5eUhyM1lnT2Z6RjZZRWFjeWIKeUVyOFBoRjlNQ1FHQTFVZEVRUWRNQnVDR1dOaExY
      UnZiMnh6TFRaa05HTTJaamMyWkdZdE9XeDRibWd3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRI
      UnljeUk2ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFH
      WXVRV1ptYVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlq
      b2lRV1J0YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZ
      SQpLb1pJemowRUF3SURTQUF3UlFJaEFKL0JreHlPKzlDQjNvQzRsQll6RHhTNzZkUGFqUHlSK21N
      Sld2U1djMFQzCkFpQTcyOStBNVh4TUJCSlRGdnA2TkFaNjgvZEZ2eTNzVlNUYlBaMXl1bU1nMVE9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVBK1JOWm1BM3BneEdaVUdtT2d0
      SklKcEhTYUF3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFd01ETXdNakEwTURk
      YUZ3MHlOVEEzTWpNd01qQTBNRGRhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFa
      TWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVY
      Ck1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pP
      UFFNQkJ3TkMKQUFTL0pvTUR4anRPUTRSWmdoRldDbnBETDZzc3Zyd3JYMCtCTm81d1VQNWE5MVBP
      RDdWZDU0S2tKbFptKzVYUQpRcHVIRm0zbnNrNnAvVE5UVHVibTAwbklvMEl3UURBUEJnTlZIUk1C
      QWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUxMSWV2ZGlB
      NS9NWHBnUnB6SnZJU3Z3K0VYMHdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUlnQ3l5Y244OGg4eVU3
      YTlrUXkrNE9PQlgxZXlxSnM0bTJQUXgvTld4SW4zQUNJUUQzRjFMWAo5aktIRWZOUitJeEtyemlk
      dmY5MHdmRk00YUxDbU9nQzBGN0FpQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIz
      CgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFk
      bWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9y
      c2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMa
      QAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJl
      ci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoX
      L0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hp
      bmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0
      dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5z
      dXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0
      aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoG
      QWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
