apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://34.168.136.6:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: supplychain-net

    genesis: |-
      CiIaIHtgNIkkiqYdeRItX1gnOB8c/7e/o+fIfj0Tf+TBE0hZEpZeCpNeCpBeCngKWggBEAEaBgjw
      j6qdBiIKc3lzY2hhbm5lbCpAOTYyNDJhZmJlMWUxY2IxZWQzYmU3MGYzMzQ2MjYwODNiNDNiZmNl
      MjNmNTk3YTg2NjkwNGVmYWQ2M2FjNjRjNBIaEhiVkQLvKs6PEQIcq/eGeVZ+Gm0DeybEaj8Sk10K
      kF0SjV0SuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcK
      D21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVJUHFWc3JHbnFK
      QVVVUmdxdXQwMU9VeitLdkF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpJeE1qSTNNRFV6TlRVMldoY05NalV4TURFMk1EVXpOVFUyV2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGanpEaEJOdEhv
      QXROdDVnQ2hPdjR4UTJ1Sk8raHMvVTFCegpvZHZhZ1QxNzRiUHBOUXd0d1Y0VUFTMU9pbVphM0U4
      WXlCZ28xVFhiVmpnMy9FMEhtSGVqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVHk1MHRaS2RaVlIybjEKRy9PNUlaa2dWRzhZT3pB
      S0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCajl2ejdNT2NEQjU5czRIN0hHa3JvaWlWbwplMGp5em9q
      dEVEQVBxOVFrc0FJZ0VrTEFrT2htUDRnUE54SDhIdkw2TTQ1TUwzUmNXampSSW8vQWs2bFRBN2s9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURFRENDQXJlZ0F3SUJBZ0lVV2gvZzIydGpJQXFoRE45WkJzNkdBSVZYLytJd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakkzTURVME16QXdXaGNO
      TWpNeE1qSTNNRFUwT0RBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEz
      TGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFN
      QmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFE
      REJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkK
      emowREFRY0RRZ0FFS3pqeGhtVVFGdUUvQWVPVGFNN0s4UXd1dW8vTG94MlVNT2lBOUp0czFoZGpQ
      VXY2c0FGUgppWXBMMDI0YjlseEYxTmdJTnQ1SzJPTjc4dVJzMlcyYWpLT0NBU0l3Z2dFZU1BNEdB
      MVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUTWFwWVhL
      R0d0RXhFOTFRbDlDQ2JUbFQ0R2V6QWYKQmdOVkhTTUVHREFXZ0JUeTUwdFpLZFpWUjJuMUcvTzVJ
      WmtnVkc4WU96QWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMVpEUTRaRGsyWWpSaUxXNDFa
      emh5TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVk
      V1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZ
      M1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TkhBREJFCkFpQUM5SEQ4SVRJaFRjUFdYZHp1NzVlRVc0REFrUSt3cTJQdllKb0wzS0ZIelFJZ0Za
      MWorbzJlVDZBZlNxOCsKVFo1akV0S1NJcFU3VUh6bi9mSFA0cXlRNkR3PQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVJUHFWc3JHbnFKQVVVUmdxdXQwMU9VeitLdkF3Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qSTNNRFV6TlRVMldo
      Y05NalV4TURFMk1EVXpOVFUyV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1du
      VnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRY
      SmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NN
      NDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGanpEaEJOdEhvQXROdDVnQ2hPdjR4UTJ1Sk8raHMvVTFC
      egpvZHZhZ1QxNzRiUHBOUXd0d1Y0VUFTMU9pbVphM0U4WXlCZ28xVFhiVmpnMy9FMEhtSGVqUWpC
      QU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdR
      V0JCVHk1MHRaS2RaVlIybjEKRy9PNUlaa2dWRzhZT3pBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlC
      ajl2ejdNT2NEQjU5czRIN0hHa3JvaWlWbwplMGp5em9qdEVEQVBxOVFrc0FJZ0VrTEFrT2htUDRn
      UE54SDhIdkw2TTQ1TUwzUmNXampSSW8vQWs2bFRBN2s9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVy
      TVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcU
      EqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrVEND
      QVo2Z0F3SUJBZ0lVRGwvaHB5bmZ5aEYzMHhIUVQrdXRibjdpR2Jzd0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck1qRXlNamN3TlRNM01EUmFGdzB5TlRFd01UWXdOVE0zTURSYU1Gb3hD
      ekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZi
      bVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUjlnTzIrSTRTbVVKSkJY
      cjJ1Szg2amV0REFoa0Mrajl4UVNaUElhK1Jobmg5eTN0ZjFOeml3SzRaTmpIcTQKWDFkbUs3bDY2
      M21JS2w5dlFMcllmbzRQbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgov
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVV6YTJIMUs2TTZRMnRmTVBqb1Z2R1MzM2R1S293Q2dZSUtv
      Wkl6ajBFCkF3SURTUUF3UmdJaEFJb1duV1hKclJlVStyK1ZoV0d0MjVuR0VrWFozeXg4RGExRVlO
      azdsOW4vQWlFQStSMWkKbkhEbEVLLzQwR3lLa0dYbitoSTZhZmJWZGwrcUNvWGlHYkJRemhnPQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlDN1RDQ0FwU2dBd0lCQWdJVVhGNEJseENYalNCT1MrMkZFTzBJa21FaGZJOHdDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV5TWpjd05UUTJNREJhRncweU16RXlNamN3TlRVeE1E
      QmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIy
      NWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0Ex
      VUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRT3NoWHlhbmRPc1VTWHZ5NGtyc0NYCmh0
      SlFXMkx4UGg2TnF1TUhnb0NYT1drTEVuMGpwRjNDaG16SzBwMnQvZE8wbGo2N1h4NmJPUzk2Ykg4
      Y05DQkUKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFB
      d0hRWURWUjBPQkJZRQpGTnBUdW9taGVrWkMrdjdDR29OdGgvNkl3M3lHTUI4R0ExVWRJd1FZTUJh
      QUZNMnRoOVN1ak9rTnJYekQ0NkZiCnhrdDkzYmlxTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4
      ekxUZzJOalExTlRVNE5UWXRaR3R1Wm5jd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdS
      dGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29a
      SXpqMEVBd0lEUndBd1JBSWdkT2VKZ3ZhWDRNenJRN3daM0M1bHhlSTUxRmtiRVhFVWlLZjBkaUp0
      emlvQwpJQS91OEpaY3h0cklBanFIS3V2M2F6UHlzT29rQUIzWkNtZmxpdkNnRDJkMQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVEbC9ocHluZnloRjMweEhRVCt1dGJuN2lHYnN3
      Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlE
      VlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1qY3dOVE0zTURSYUZ3MHlOVEV3
      TVRZd05UTTNNRFJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4
      RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVF
      QXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMK
      QUFSOWdPMitJNFNtVUpKQlhyMnVLODZqZXREQWhrQytqOXhRU1pQSWErUmhuaDl5M3RmMU56aXdL
      NFpOakhxNApYMWRtSzdsNjYzbUlLbDl2UUxyWWZvNFBvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURB
      UUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXphMkgxSzZNNlEydGZNUGpv
      VnZHUzMzZHVLb3dDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUlvV25XWEpyUmVVK3IrVmhXR3Qy
      NW5HRWtYWjN5eDhEYTFFWU5rN2w5bi9BaUVBK1IxaQpuSERsRUsvNDBHeUtrR1huK2hJNmFmYlZk
      bCtxQ29YaUdiQlF6aGc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoHUmVh
      ZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJz
      EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAI
      ARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5l
      bENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMq
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zEosrCgdPcmRlcmVyEv8qEsoW
      Cg5zdXBwbHljaGFpbk1TUBK3FhrDFAoDTVNQErsUErAUEq0UCg5zdXBwbHljaGFpbk1TUBLxBS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVUpiN2liMDg3MzJt
      R1VXK2VpSnVCa1hCcGlKb3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJ
      eE1qSTNNRFV6TkRRM1doY05NalV4TURFMk1EVXpORFEzV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQ
      Ck1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9N
      QjA5eVpHVnkKWlhJeEd6QVpCZ05WQkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1H
      QnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCSWdNWXY2Yyt3cnNCd2NBOGd3SG91YTNlVERO
      S3l4QVhreGY5VTRFTTdlUjliaXdySGxLCmlmNUgvR1FwYlZ6K2hTeEJpalhTaC9TMzdMLzZDRy9v
      Q1ZPalFqQkFNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBH
      QTFVZERnUVdCQlEyTmt4VjQ2QVZMVURaVERPbUJCSUtpSDlOSFRBSwpCZ2dxaGtqT1BRUURBZ05J
      QURCRkFpQStLZ1NKL2VlVWNKS08rTXkzR1hrb2Z6MjA5Uyt6OVROc0FjejNGdDA3CmtRSWhBUGlS
      OCtNTTB4RzJEWU04N25EV09qMWRlVGIwVGFscHZ3UEVkNzI4c0ZYUQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCiKiCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDNERDQ0FvZWdBd0lC
      QWdJVVp2N1FpN1FSbGpnVG1HUG4xbUltTkMwWXNOZ3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBi
      aTF1WlhRdwpIaGNOTWpJeE1qSTNNRFUwTVRBd1doY05Nak14TWpJM01EVTBOakF3V2pCc01Rc3dD
      UVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdE
      Z1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZRUUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZR
      V1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZrdwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERB
      UWNEUWdBRUFRYTVMTDl1Z2JMRDlRVFRQN2ZyZklwaWs3YklKVmxiCjRYQTJVWEtJMG1ScVhFVmw3
      SlRuTGVlbmk2UWY3cVlUUE9BRE9YVnJMSGFSVytDWG9XcnBJcU9DQVJNd2dnRVAKTUE0R0ExVWRE
      d0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUU14N1U5REovNAp4
      SHJNT1I1aGtoVXpyeEpxRHpBZkJnTlZIU01FR0RBV2dCUTJOa3hWNDZBVkxVRFpURE9tQkJJS2lI
      OU5IVEFqCkJnTlZIUkVFSERBYWdoaGpZUzEwYjI5c2N5MDJORGMwWkdZNU4yWXRjM054TnpJd2dZ
      a0dDQ29EQkFVR0J3Z0IKQkgxN0ltRjBkSEp6SWpwN0ltRmlZV011YVc1cGRDSTZJblJ5ZFdVaUxD
      SmhaRzFwYmlJNkluUnlkV1VpTENKbwpaaTVCWm1acGJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNt
      OXNiRzFsYm5SSlJDSTZJa0ZrYldsdVFITjFjSEJzCmVXTm9ZV2x1TFc1bGRDSXNJbWhtTGxSNWNH
      VWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlCSWQ2c2pCM3BQeldXbVA4
      Y3BtTXVSZ012dnVLUzdQZm1QZk1UWjdWTmh6UUlnV1BPRWoyVCtmdk1wWkVYMApPNk9qaTE1d3oz
      MlVjclhkWCs0d2k0MEJYQVk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNI
      QTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVUpi
      N2liMDg3MzJtR1VXK2VpSnVCa1hCcGlKb3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      dwpIaGNOTWpJeE1qSTNNRFV6TkRRM1doY05NalV4TURFMk1EVXpORFEzV2pCZU1Rc3dDUVlEVlFR
      R0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURB
      T0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05WQkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1
      bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCSWdNWXY2Yyt3cnNCd2NBOGd3
      SG91YTNlVEROS3l4QVhreGY5VTRFTTdlUjliaXdySGxLCmlmNUgvR1FwYlZ6K2hTeEJpalhTaC9T
      MzdMLzZDRy9vQ1ZPalFqQkFNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFR
      REFnR21NQjBHQTFVZERnUVdCQlEyTmt4VjQ2QVZMVURaVERPbUJCSUtpSDlOSFRBSwpCZ2dxaGtq
      T1BRUURBZ05JQURCRkFpQStLZ1NKL2VlVWNKS08rTXkzR1hrb2Z6MjA5Uyt6OVROc0FjejNGdDA3
      CmtRSWhBUGlSOCtNTTB4RzJEWU04N25EV09qMWRlVGIwVGFscHZ3UEVkNzI4c0ZYUQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcKB1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAa
      EhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgKBkFkbWlucxIuEiQIARIgEggSBggBEgIIABoU
      EhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggB
      EgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggB
      EgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMqBkFkbWlucxqCEgoNQ29uc2Vuc3VzVHlw
      ZRLwERLlEQoIZXRjZHJhZnQS2BEKwREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrPCC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQVRDQ0FxZWdBd0lCQWdJVVovM3VJQTdjMHp3
      RUtwWStQeVZZWkZjRnFTMHdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJ
      eE1qSTNNRFUwTVRBd1doY05Nak14TWpJM01EVTBOakF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakVi
      Ck1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJs
      Y21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6
      ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVF2
      bWdJczNLQXA0REFWTDVkUUF1T29jQWtPCnRrOGNicmdZaEpaY3lrM0kxU3FtK1NWQm10QVlneDZi
      eHJhY0dLR25kU3pkd3RNK2ZmTUJCYjU5NitVOG80SUIKTGpDQ0FTb3dEZ1lEVlIwUEFRSC9CQVFE
      QWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1C
      QWY4RUFqQUFNQjBHQTFVZERnUVdCQlRoTkxEUlVnaWIzWUMxcm9KMjN0SncyMUtMCkx6QWZCZ05W
      SFNNRUdEQVdnQlEyTmt4VjQ2QVZMVURaVERPbUJCSUtpSDlOSFRBOUJnTlZIUkVFTmpBMGdoaHYK
      Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHRzl5WkdWeVpYSXhMbk4xY0hCc2VXTm9Z
      V2x1TFc1bApkREJzQmdncUF3UUZCZ2NJQVFSZ2V5SmhkSFJ5Y3lJNmV5Sm9aaTVCWm1acGJHbGhk
      R2x2YmlJNklpSXNJbWhtCkxrVnVjbTlzYkcxbGJuUkpSQ0k2SW05eVpHVnlaWEl4TG5OMWNIQnNl
      V05vWVdsdUxXNWxkQ0lzSW1obUxsUjUKY0dVaU9pSnZjbVJsY21WeUluMTlNQW9HQ0NxR1NNNDlC
      QU1DQTBnQU1FVUNJUUQraWcvVjRveDE0TkRlMlRKTApZUExJUURoZlR4UktHTE9idit6NmZ4L0l1
      QUlnTmN3V0RiR0pZNFFNN1RSMi9zOFA4WGFoZHRQMHQ4SCtEYktjCjZxZ1FRalE9Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KIs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVEND
      QXFlZ0F3SUJBZ0lVWi8zdUlBN2MwendFS3BZK1B5VllaRmNGcVMwd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJM01EVTBNVEF3V2hjTk1qTXhNakkzTURVME5qQXdX
      akJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVa
      Rzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdI
      d1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQ0FBUXZtZ0lzM0tBcDREQVZMNWRRQXVPb2NBa08KdGs4Y2JyZ1lo
      SlpjeWszSTFTcW0rU1ZCbXRBWWd4NmJ4cmFjR0tHbmRTemR3dE0rZmZNQkJiNTk2K1U4bzRJQgpM
      akNDQVNvd0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJn
      Z3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVGhOTERSVWdpYjNZ
      QzFyb0oyM3RKdzIxS0wKTHpBZkJnTlZIU01FR0RBV2dCUTJOa3hWNDZBVkxVRFpURE9tQkJJS2lI
      OU5IVEE5QmdOVkhSRUVOakEwZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dH
      OXlaR1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVsCmREQnNCZ2dxQXdRRkJnY0lBUVJnZXlKaGRI
      UnljeUk2ZXlKb1ppNUJabVpwYkdsaGRHbHZiaUk2SWlJc0ltaG0KTGtWdWNtOXNiRzFsYm5SSlJD
      STZJbTl5WkdWeVpYSXhMbk4xY0hCc2VXTm9ZV2x1TFc1bGRDSXNJbWhtTGxSNQpjR1VpT2lKdmNt
      UmxjbVZ5SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRRCtpZy9WNG94MTRORGUyVEpMCllQ
      TElRRGhmVHhSS0dMT2J2K3o2ZngvSXVBSWdOY3dXRGJHSlk0UU03VFIyL3M4UDhYYWhkdFAwdDhI
      K0RiS2MKNnFnUVFqUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUo
      gICAChoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNo
      VGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMa
      JgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMS
      CQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIK
      BkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0I
      AxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRf
      MxIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJs
      b2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJl
      c3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcS
      DQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlu
      cyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
