apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIG2H9dPnzedSHN+u0zxu29au5CohW4A3XAFNyfc4xAdMEoxeColeCoZeCngKWggBEAEaBgif
      gI+aBiIKc3lzY2hhbm5lbCpAMzVmN2MwNjI4MzhjNTE4ZDljZDVmZjZjZjA5ZTIyMWE3NWYwMDYz
      YzE3NzI2ZjRhMTZkYmM5NGZkMzM3MmJiNRIaEhjV+nuyiOeiKWoDLNHUbgr0+cbXVXemLPcSiV0K
      hl0Sg10SuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcK
      D21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVjWCtDV0NiTFI0
      dDVPWjN4eXlEMTJXVXN1aEF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpJeE1EQTVNRGN4T0RFeldoY05NalV3TnpJNU1EY3hPREV6V2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGZWplWWtZeWdO
      d2tXUTFmVHRtWWpkTStYeUlXT3p0ZnQxRwo5UzRGOENqb2pZUGFDeFM2aUpHSUluamF3V1hIOEgw
      ajdQL2VRbi9TSld2Ym94bUVVbHVqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1pNMHhYVEZGYmJIbWUKN1Rrd2xRWVBMOGZySXpB
      S0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQW1nT2tXMjh5Ulg2NHlnQ0xQTWZzZDhtNQplamZSZlRW
      UHdBQWsreXVKV3prQ0lISXRVdU5DcGNaakZ1bFVBRXJyK3ZESk1SVjdCd0pIQ1JOZy8yem0zeEpl
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURFVENDQXJlZ0F3SUJBZ0lVSTh3UFV1SnRXd2RpRVg3RmVLSVFKQldhTU1Fd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNREE1TURjeU5UQXdXaGNO
      TWpNeE1EQTVNRGN6TURBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEz
      TGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFN
      QmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFE
      REJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkK
      emowREFRY0RRZ0FFek5pS1k0Zzg0YkhZK0JhZjlKSzNTelRTL2kyWHRha0dzcGY5am96eVZnUUtp
      c2dWVVlMOAplWkFvemxMWDJFb0dhNVd0UGd4cE9NZlphWWlYNjZJOXVxT0NBU0l3Z2dFZU1BNEdB
      MVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSS2hnVXM3
      QVZ4L091M29taWFLU2pjUHNqSDhUQWYKQmdOVkhTTUVHREFXZ0JTWk0weFhURkZiYkhtZTdUa3ds
      UVlQTDhmckl6QWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1kyUTNabVJtT1RjMkxUaDRk
      bWhrTUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVk
      V1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZ
      M1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TklBREJGCkFpRUEwOWRXT2V4aWNjMGRjeDlIWGRjTHZHR1VlM0FjNlJIRUVvUlNzZCsrNklFQ0lG
      ZHRFVXhqanpPTnI2Sk0KTHo3dDNVNWx5UkxoUVIvVytPRFdRZnBqbUZxWAotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVjWCtDV0NiTFI0dDVPWjN4eXlEMTJXVXN1aEF3Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1EQTVNRGN4T0RFeldo
      Y05NalV3TnpJNU1EY3hPREV6V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1du
      VnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRY
      SmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NN
      NDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGZWplWWtZeWdOd2tXUTFmVHRtWWpkTStYeUlXT3p0ZnQx
      Rwo5UzRGOENqb2pZUGFDeFM2aUpHSUluamF3V1hIOEgwajdQL2VRbi9TSld2Ym94bUVVbHVqUWpC
      QU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdR
      V0JCU1pNMHhYVEZGYmJIbWUKN1Rrd2xRWVBMOGZySXpBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlF
      QW1nT2tXMjh5Ulg2NHlnQ0xQTWZzZDhtNQplamZSZlRWUHdBQWsreXVKV3prQ0lISXRVdU5DcGNa
      akZ1bFVBRXJyK3ZESk1SVjdCd0pIQ1JOZy8yem0zeEplCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFj
      dHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVm
      YWN0dXJlck1TUBABGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcU
      EqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrREND
      QVo2Z0F3SUJBZ0lVTW9IR0o0Z0VWN29yTnkyY05Mejc4aXI5NzZ3d0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck1qRXdNRGt3TnpJd01UUmFGdzB5TlRBM01qa3dOekl3TVRSYU1Gb3hD
      ekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZi
      bVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUmhsN0NWV2RnZWFOMGU1
      bWtJOFFRQ2txdXViTXlDc1M5ZmtRcWpqdTNWSkRrZDJSblFXZE1XVEk5RU5uVVYKTS96cDdqTkFS
      R1FQWU9kenUxNzI2bTl2bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgov
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVmYWNiMk1VUGtncFJ5amN5LzVzRk5yTFg5RkV3Q2dZSUtv
      Wkl6ajBFCkF3SURTQUF3UlFJaEFOY1QwN0lxK25hWTdDUWJkcnRNakhyRVNpdlRLQkFxQXd6b1l2
      V3JjR2xxQWlCdnVtZ0UKVWhYSzlvd2lzbmt1bHVycTZmZ2lqSjlJQzEySUhadGtIaWZvOXc9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlDN1RDQ0FwU2dBd0lCQWdJVVErSVpEL2JycTFLNWg1ak5lUXRqRTNIVU1qQXdDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV3TURrd056STNNREJhRncweU16RXdNRGt3TnpNeU1E
      QmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIy
      NWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0Ex
      VUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRU3BqQ3hkYVZDcGk0Ny94TndjNlpCCmxJ
      S2dyTU1JUm9tMXA3VzQ3SncvSWJ1UG9hSHRaNTN6dkJXY1IvSFhsdXV3MTFpWkZza3VCNCs3Q1pP
      SHpuc2sKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFB
      d0hRWURWUjBPQkJZRQpGRndWb0pGVnErRFFrU1FMdTJpUVFjTjdnVHB0TUI4R0ExVWRJd1FZTUJh
      QUZIMm5HOWpGRDVJS1VjbzNNditiCkJUYXkxL1JSTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4
      ekxUWmtOR00yWmpjMlpHWXRkbTFvYXpnd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdS
      dGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29a
      SXpqMEVBd0lEUndBd1JBSWdXMmRzdkFmRnlHRkZYY3BReWtuYnhaS2lKS1dwTkRtZGU4bXZGc2NW
      UHBJQwpJQWFqNjBZbVMzRDcxdTNpbVRuOXRiaVFnQkIvU3Awa0ZYbndkMmZOckdLMAotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVNb0hHSjRnRVY3b3JOeTJjTkx6Nzhpcjk3Nnd3
      Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlE
      VlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFd01Ea3dOekl3TVRSYUZ3MHlOVEEz
      TWprd056SXdNVFJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4
      RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVF
      QXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMK
      QUFSaGw3Q1ZXZGdlYU4wZTVta0k4UVFDa3F1dWJNeUNzUzlma1Fxamp1M1ZKRGtkMlJuUVdkTVdU
      STlFTm5VVgpNL3pwN2pOQVJHUVBZT2R6dTE3MjZtOXZvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURB
      UUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWZhY2IyTVVQa2dwUnlqY3kv
      NXNGTnJMWDlGRXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU5jVDA3SXErbmFZN0NRYmRydE1q
      SHJFU2l2VEtCQXFBd3pvWXZXcmNHbHFBaUJ2dW1nRQpVaFhLOW93aXNua3VsdXJxNmZnaWpKOUlD
      MTJJSFp0a0hpZm85dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoGQWRt
      aW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3Jz
      ZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5l
      bENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMq
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zEoMrCgdPcmRlcmVyEvcqEtYW
      Cg5zdXBwbHljaGFpbk1TUBLDFhrPFAoDTVNQEscUErwUErkUCg5zdXBwbHljaGFpbk1TUBL1BS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVVYzSVlRbTF2dXdE
      UThDQmxRYnBjVmNPUTVMb3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJ
      eE1EQTVNRGN4TmpFeldoY05NalV3TnpJNU1EY3hOakV6V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQ
      Ck1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9N
      QjA5eVpHVnkKWlhJeEd6QVpCZ05WQkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1H
      QnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCRTFFZHd4S054QjRxd2lPdGlGUVQ5YWFRejBn
      VC84L0lvdldiZEpMYjA1RDgxVHZ0ZGI1CnlQLzZtZFllR0ZYMTRLSnVlMWNSUVh3MzVzYzBaN3M5
      bkVHalFqQkFNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBH
      QTFVZERnUVdCQlNoNytqUlBUWGs2T1B4S3dOREcyRVZ0R1V0WVRBSwpCZ2dxaGtqT1BRUURBZ05K
      QURCR0FpRUE1a0NTODVGR0FoTTF5RFRUZlMwV2JLc3RRUUg5a0ZFZ0lQVFVxK3JYCnM0Z0NJUUNq
      d29qZVY0SWxGamo1dFh2VzVnU3M0THBSbVd1cThwRWFnbDM3cjVuclBBPT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoipggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzRqQ0NBb2ln
      QXdJQkFnSVVHQndJSU1MY21CVWgvSldTRTFPOThxRTRBT013Q2dZSUtvWkl6ajBFQXdJdwpYakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGph
      R0ZwYmkxdVpYUXcKSGhjTk1qSXhNREE1TURjeU16QXdXaGNOTWpNeE1EQTVNRGN5T0RBd1dqQnNN
      UXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVN
      UkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUTR3CkRBWURWUVFMRXdWaFpHMXBiakVlTUJ3R0ExVUVB
      d3dWUVdSdGFXNUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3cKRXdZSEtvWkl6ajBDQVFZSUtvWkl6
      ajBEQVFjRFFnQUVmeTJIaFFpUXlWK2RGeU1HU0tKNEFnYndPd21hUk40Uwova1FCQ1l0ZFpIdkpV
      d0Z2ODIxU0FWSCsvOVZzYzFEVmIvSmRvU0toRS9MQTJTYkczWE1jVnFPQ0FSUXdnZ0VRCk1BNEdB
      MVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlM0ZVR1WEsr
      UVkKbDdXa0M5NGFYVnE0dTdEZ0JEQWZCZ05WSFNNRUdEQVdnQlNoNytqUlBUWGs2T1B4S3dOREcy
      RVZ0R1V0WVRBawpCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAxTmpZM1l6WTNabVkzTFd0dGVq
      YzBNSUdKQmdncUF3UUZCZ2NJCkFRUjlleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNu
      VmxJaXdpWVdSdGFXNGlPaUowY25WbElpd2kKYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpTENKb1pp
      NUZibkp2Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0J6ZFhCdwpiSGxqYUdGcGJpMXVaWFFpTENKb1pp
      NVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3ClJRSWhBTUxjMUpNcTFQ
      OG5pT3RKSXRJa0VMaDlGbzV4QkU2R0dNak5qTEEvWW5BdUFpQUNNUGVwNUtnQTlqeEMKSnFFOWhQ
      eWVwL2Q1QTNZTGpNZmVBWGI2R2ZqVWd3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoE
      U0hBMhIGU0hBMjU2SvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVENDQWFhZ0F3
      SUJBZ0lVVjNJWVFtMXZ1d0RROENCbFFicGNWY09RNUxvd0NnWUlLb1pJemowRUF3SXcKWGpFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5
      dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdG
      cGJpMXVaWFF3CkhoY05Nakl4TURBNU1EY3hOakV6V2hjTk1qVXdOekk1TURjeE5qRXpXakJlTVFz
      d0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1
      a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdO
      b1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJFMUVkd3hLTnhC
      NHF3aU90aUZRVDlhYVF6MGdULzgvSW92V2JkSkxiMDVEODFUdnRkYjUKeVAvNm1kWWVHRlgxNEtK
      dWUxY1JRWHczNXNjMFo3czluRUdqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2g3K2pSUFRYazZPUHhLd05ERzJFVnRHVXRZVEFL
      CkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTVrQ1M4NUZHQWhNMXlEVFRmUzBXYktzdFFRSDlrRkVn
      SVBUVXErclgKczRnQ0lRQ2p3b2plVjRJbEZqajV0WHZXNWdTczRMcFJtV3VxOHBFYWdsMzdyNW5y
      UEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcKB1JlYWRlcnMSLBIiCAES
      HhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcKB1dyaXRlcnMSLBIiCAES
      HhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgKBkFkbWlucxIuEiQIARIg
      EggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7CgtFbmRvcnNlbWVudBIs
      EiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMqBkFkbWlucxoiCglC
      YXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoG
      QWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIW
      EgwKCgoGVjFfNF8yEgAaBkFkbWlucxruEQoNQ29uc2Vuc3VzVHlwZRLcERLREQoIZXRjZHJhZnQS
      xBEKrREKFm9yZGVyZXIxLndob2xlc2FsZS1uZXQQijcaxggtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQytqQ0NBcUdnQXdJQkFnSVVCY3hCWTMvQzRMOEZzVVJHc1ZxczQvRTFNWHd3Q2dZ
      SUtvWkl6ajBFQXdJdwpYREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sa3dGd1lEVlFR
      RERCQmpZUzUzYUc5c1pYTmhiR1V0Ym1WME1CNFgKRFRJeU1UQXhNREEyTWprd01Gb1hEVEl6TVRB
      eE1EQTJNelF3TUZvd2J6RUxNQWtHQTFVRUJoTUNSMEl4R3pBWgpCZ05WQkFjVEVqVXhMalV3THkw
      d0xqRXpMMHh2Ym1SdmJqRVFNQTRHQTFVRUNoTUhUM0prWlhKbGNqRVFNQTRHCkExVUVDeE1IYjNK
      a1pYSmxjakVmTUIwR0ExVUVBeE1XYjNKa1pYSmxjakV1ZDJodmJHVnpZV3hsTFc1bGREQloKTUJN
      R0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSmNMdStyOUYzclQzYXFyMDJQRXpZY1V5VzUz
      Q1ZRNgpmNlJGZ2w0aElueDA0cG1ubUpTMFY5NHVZeDc1SFdvRTZJejJmUjBKZGdSSlhHUlBxZ2dV
      dllHamdnRXNNSUlCCktEQU9CZ05WSFE4QkFmOEVCQU1DQTZnd0hRWURWUjBsQkJZd0ZBWUlLd1lC
      QlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGUFhM
      dVYzV3g3UkdlTUN0UzMwK25nQ0x0VUo0TUI4RwpBMVVkSXdRWU1CYUFGRG5STEZtV3BqMWZvNDdh
      M3ZBVDNJNXB5KzZHTUQwR0ExVWRFUVEyTURTQ0ZtOXlaR1Z5ClpYSXhMbmRvYjJ4bGMyRnNaUzF1
      WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1WTI5dE1Hb0cKQ0NvREJBVUdCd2dC
      QkY1N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eQpiMnhz
      YldWdWRFbEVJam9pYjNKa1pYSmxjakV1ZDJodmJHVnpZV3hsTFc1bGRDSXNJbWhtTGxSNWNHVWlP
      aUp2CmNtUmxjbVZ5SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lBNEZIN0dOSGViSnRmeTN4
      aE5QNUNYb00xbHYKbTA1UjdhZjAvdU4yOFc0YkFpQmc1OGhxeDllTVh5aFRBa2d4MEdGQUtNYTRP
      UEhPN3QycTM0WjF0MDlDSFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLGCC0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDK2pDQ0FxR2dBd0lCQWdJVUJjeEJZMy9DNEw4RnNVUkdz
      VnFzNC9FMU1Yd3dDZ1lJS29aSXpqMEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZC
      QWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxj
      bVZ5TVJrd0Z3WURWUVFEREJCallTNTNhRzlzWlhOaGJHVXRibVYwTUI0WApEVEl5TVRBeE1EQTJN
      amt3TUZvWERUSXpNVEF4TURBMk16UXdNRm93YnpFTE1Ba0dBMVVFQmhNQ1IwSXhHekFaCkJnTlZC
      QWNURWpVeExqVXdMeTB3TGpFekwweHZibVJ2YmpFUU1BNEdBMVVFQ2hNSFQzSmtaWEpsY2pFUU1B
      NEcKQTFVRUN4TUhiM0prWlhKbGNqRWZNQjBHQTFVRUF4TVdiM0prWlhKbGNqRXVkMmh2YkdWellX
      eGxMVzVsZERCWgpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKY0x1K3I5RjNyVDNh
      cXIwMlBFelljVXlXNTNDVlE2CmY2UkZnbDRoSW54MDRwbW5tSlMwVjk0dVl4NzVIV29FNkl6MmZS
      MEpkZ1JKWEdSUHFnZ1V2WUdqZ2dFc01JSUIKS0RBT0JnTlZIUThCQWY4RUJBTUNBNmd3SFFZRFZS
      MGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQwpNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRUZQWEx1VjNXeDdSR2VNQ3RTMzArbmdDTHRVSjRNQjhHCkExVWRJd1FZTUJhQUZE
      blJMRm1XcGoxZm80N2EzdkFUM0k1cHkrNkdNRDBHQTFVZEVRUTJNRFNDRm05eVpHVnkKWlhJeExu
      ZG9iMnhsYzJGc1pTMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3VZMjl0TUdv
      RwpDQ29EQkFVR0J3Z0JCRjU3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3
      aWFHWXVSVzV5CmIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVkMmh2YkdWellXeGxMVzVsZENJ
      c0ltaG1MbFI1Y0dVaU9pSnYKY21SbGNtVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUE0
      Rkg3R05IZWJKdGZ5M3hoTlA1Q1hvTTFsdgptMDVSN2FmMC91TjI4VzRiQWlCZzU4aHF4OWVNWHlo
      VEFrZ3gwR0ZBS01hNE9QSE83dDJxMzRaMXQwOUNIUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRl
      cnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1Zh
      bGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVh
      ZGVycxoGQWRtaW5zKgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRt
      aW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTAoQT3Jk
      ZXJlckFkZHJlc3NlcxI4Eh0KG29yZGVyZXIxLndob2xlc2FsZS1uZXQ6NzA1MBoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zIiIK
      BkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVh
      ZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMa
      CgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
