apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIB+02wqnPQfMorfSFXhtplQUBIzqT727nman5+4lsUVbEp5eCpteCpheCngKWggBEAEaBgi1
      3vWYBiIKc3lzY2hhbm5lbCpAOTYzZWEzMTk5NDgwZGJkNGI3OWFiNjMxOWU3OTFlMzYwOWQwNTg3
      ZDk5ZWI3ZDcxOWFkODVjYTE1ZDUzMmQ5MBIaEhja/hF+fDrMtWKrqwU3bWOoAjQMWA5FWFgSm10K
      mF0SlV0SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVVWM3SHQ4bFh5bGRwOVhPR3V2RnBHS0VXOW5Bd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFeE1EUTFPVFE1V2hjTk1qVXdOekF4TURRMU9UUTVX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJMYTIy
      cUZveSt5dnl1MVlLTzUvanY2M0ZkNnMvWWxHUlRXUmJLQ0t6OXZmWjhvVDFzeUYKZ202S2JmQ09W
      VTFmdVROS2p5TktoOW9zcE5CMUt3b3hwaVdqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUytzbG9QZyswYW9CTTlrQm90eVZPVUdX
      WXRqakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXhJOXh2RGdqaHdKWW1sTWx2cmpuR21ocCti
      cVZhNWxHeHlLemR1Y0wKaXpnQ0lCekdXenhvNHVZNk5YTHFZTWlDK0pCRWdkVjdsOFVIM3pkSGpP
      dzdJZDBQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVQkMyUVhDZzl1UXFKUHhtZFltZGJPM2ZwVnFrd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFeE1EVXdOekF3V2hjTk1q
      TXdPVEV4TURVeE1qQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFR1k2Z3o0c0RBZWoxWXdkcm44bC8xeks5b1Fp
      REZROGQKR2xhampzRmYxYmsrQytxQmRpQS9aTkdRUUNCcVJMR2JCUGhleW1FU3hERzRMVkI1Z05J
      UjI2T0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTRVRKYWhGUG04CmdpN0lqZkpCTTdKaTF6WHFTVEFmQmdOVkhTTUVHREFXZ0JT
      K3Nsb1BnKzBhb0JNOWtCb3R5Vk9VR1dZdGpqQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xUWTFhbU5qTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQVA0L3Y0SEtDclh3NGNFV2FMcW13cmlYWFNWSHQxeThRUUVKTVRNQ2dkcEJBaUFB
      MjRPUkZzZkg0U2tDCk1qcFFZWGpzVmVzdWVqUjMrUzZBWVpJWk9wenZ0dz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVVjN0h0OGxYeWxkcDlYT0d1dkZwR0tFVzluQXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09URXhNRFExT1RRNVdoY05NalV3
      TnpBeE1EUTFPVFE1V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCTGEyMnFGb3kreXZ5dTFZS081L2p2NjNGZDZzL1lsR1JUV1JiS0NLejl2Zlo4b1Qx
      c3lGCmdtNktiZkNPVlUxZnVUTktqeU5LaDlvc3BOQjFLd294cGlXalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlMrc2xvUGcrMGFv
      Qk05a0JvdHlWT1VHV1l0ampBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUF4STl4dkRnamh3Sllt
      bE1sdnJqbkdtaHArYnFWYTVsR3h5S3pkdWNMCml6Z0NJQnpHV3p4bzR1WTZOWExxWU1pQytKQkVn
      ZFY3bDhVSDN6ZEhqT3c3SWQwUAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4
      ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVVlFa1pibDBMWUlEOTBG
      RktCbE1BZCs5MlZYa3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNt
      UmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09U
      RXhNRFV3TnpBd1doY05Nak13T1RFeE1EVXhNakF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1C
      a0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhC
      d2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVN3SWF4
      Q05ERHd2VmNvTnNRbTgreElxZ2c4CkQ0RitNV3pmNFVRRjhlY01qS3Z3TlNJMytFV0h1bXFIYTE0
      aWVaM1hUdTRNUVpSTit0ZU9TcGhneW9kbG80SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdP
      b01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4
      RUFqQUFNQjBHQTFVZERnUVdCQlFreWtOZTUzMkFPK2J1akRFZlprTHVER0p3Cit6QWZCZ05WSFNN
      RUdEQVdnQlMrc2xvUGcrMGFvQk05a0JvdHlWT1VHV1l0ampBL0JnTlZIUkVFT0RBMmdoaHYKY21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlq
      WVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0Yw
      YVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1
      WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFNBQXdSUUloQUoxLzhTT2VDMTBvY1BIUQpaRUtOU0FNdUk3NG90aUE3VTNCYjhpMTE1Mmsw
      QWlCOW9oa0dkZW5CUWxTSEVLOW9ad3FOb1lOczNQaFgya1pPCnB4aUVURFNmdFE9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpD
      Q0FxbWdBd0lCQWdJVVlFa1pibDBMWUlEOTBGRktCbE1BZCs5MlZYa3dDZ1lJS29aSXpqMEVBd0l3
      ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09URXhNRFV3TnpBd1doY05Nak13T1RFeE1EVXhNakF3
      V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1
      Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3
      SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVN3SWF4Q05ERHd2VmNvTnNRbTgreElxZ2c4CkQ0RitNV3pm
      NFVRRjhlY01qS3Z3TlNJMytFV0h1bXFIYTE0aWVaM1hUdTRNUVpSTit0ZU9TcGhneW9kbG80SUIK
      TURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJC
      Z2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFreWtOZTUzMkFP
      K2J1akRFZlprTHVER0p3Cit6QWZCZ05WSFNNRUdEQVdnQlMrc2xvUGcrMGFvQk05a0JvdHlWT1VH
      V1l0ampBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NH
      bTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJ
      bUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVk
      RWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJ
      bTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUoxLzhTT2VDMTBvY1BIUQpa
      RUtOU0FNdUk3NG90aUE3VTNCYjhpMTE1MmswQWlCOW9oa0dkZW5CUWxTSEVLOW9ad3FOb1lOczNQ
      aFgya1pPCnB4aUVURFNmdFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAK
      GAEgBSiAgIAKGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoG
      QWRtaW5zErUvCgtDb25zb3J0aXVtcxKlLxLaLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsAuErEX
      Cg9tYW51ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEG
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVWTFlL1M1ZjdV
      S3NnRzQyZXp5SjBEMjNZSytvd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hE
      ekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtE
      QXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVa
      WFF3SGhjTk1qSXdPVEV4TURVd01UVXdXaGNOTWpVd056QXhNRFV3TVRVd1dqQmtNUXN3Q1FZRFZR
      UUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZU
      QVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkz
      UjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSzlzSFZzbkti
      WXpwRFhqcXRYYk5ORy9tZktCQnpQRmt3ZlgKZWNEYnZSTXNzaVkwWTVqNFhuczRqSVBsR1NDWSs5
      MDBlbGZERnZhbzJDTkhlUGp2UUgyalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZS
      MFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJRdGtyMzlpVC9JcjRhClM3THYxUklDSDRMY2Rq
      QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUF0RVkvVlJpbjJoSlhhYmNNbXc5OEhIOGcKU1VJbWxR
      QldTcjA0MzRrbG1oTUNJQWppRmRiOFltWjlhcG5PUGNxYXdqMGtOcGhTb3VJTDUrQWM5eExpVDBF
      SwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlERVRDQ0FyZWdBd0lCQWdJVVVGN1EvRmtIMTg2RmJFNTJGWEdvNHd6Rm1WOHdDZ1lJS29a
      SXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdO
      VkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3T1RFeE1EVXdPVEF3V2hj
      Tk1qTXdPVEV4TURVeE5EQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRR
      M0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpB
      TUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFR
      RERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      CnpqMERBUWNEUWdBRXBlOG53QW5ubTdUK0FPMTgwcjNIcFllaElFU3c3Rm9DM0J0aG9pekF2Um9J
      eko0bWhSb2YKTFI0SlAxb1dWdHlrS0lNMElJUTZJQU83N1lrbzJ0bVhvS09DQVNJd2dnRWVNQTRH
      QTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVFMrTW9N
      U3hzOS8ydTNmTG1BRFJaNzRsOHNvVEFmCkJnTlZIU01FR0RBV2dCUlF0a3IzOWlUL0lyNGFTN0x2
      MVJJQ0g0TGNkakFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMV0p3
      Y0hGaU1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9p
      ZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1
      ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgK
      WTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURB
      Z05JQURCRgpBaUVBdVh0Ry9rb003TEdGVWY1cUtLb1VyRmtJU3pLbGszVUJQODNBS1FKaGJvTUNJ
      R3VMNnMxSG5WcXZEOXNoCjJrN2RVbnhURkpvWFViQVNzaHMydE96Ry9GRTcKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVWTFlL1M1ZjdVS3NnRzQyZXp5SjBEMjNZSytvd0NnWUlL
      b1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBN
      QTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFC
      Z05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPVEV4TURVd01UVXdX
      aGNOTWpVd056QXhNRFV3TVRVd1dqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dX
      blZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBk
      WEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdT
      TTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSzlzSFZzbktiWXpwRFhqcXRYYk5ORy9tZktCQnpQRmt3
      ZlgKZWNEYnZSTXNzaVkwWTVqNFhuczRqSVBsR1NDWSs5MDBlbGZERnZhbzJDTkhlUGp2UUgyalFq
      QkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERn
      UVdCQlJRdGtyMzlpVC9JcjRhClM3THYxUklDSDRMY2RqQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFp
      RUF0RVkvVlJpbjJoSlhhYmNNbXc5OEhIOGcKU1VJbWxRQldTcjA0MzRrbG1oTUNJQWppRmRiOFlt
      WjlhcG5PUGNxYXdqMGtOcGhTb3VJTDUrQWM5eExpVDBFSwotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJl
      ck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21h
      bnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSrhYKCmNhcnJpZXJNU1ASnxYauxQKA01TUBKz
      FBKoFBKlFAoKY2Fycmllck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpD
      Q0FaNmdBd0lCQWdJVVY0OTlCMHEweFg4R0ZjcDJwMitNblM2R1QwQXdDZ1lJS29aSXpqMEVBd0l3
      CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5
      YVdWeUxXNWxkREFlRncweQpNakE1TVRFd05UQXpOVEZhRncweU5UQTNNREV3TlRBek5URmFNRm94
      Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2
      Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxs
      Y2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVNDS1RQVUZzVnBTYzkz
      dTd1eW5keXlMT0RXNUlMWlpNeWlKOWJ4UnNnc3Q4ZUN2d21YYzNXSjZad3BqNTRXCnpKMFdablpG
      blNwdHg0NlNLWUN6eFpzS28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIK
      L3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVM3o4NjBIR0l4NXhBU1AzTGtzQUZZdUY2ckc4d0NnWUlL
      b1pJemowRQpBd0lEUndBd1JBSWdRdnJqT1FkQlMrbzR4UHVzZElaS3ovK1NUVmIrTGsyOFR3cDBY
      dXZOUHBBQ0lDSjMvQW5WCmxMdUo0aEpjRUJrZ2JBWHAxY0dDOFlZMkZJZzA5ekQzTlpkdwotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      N2pDQ0FwU2dBd0lCQWdJVVV1b2JLNVk0aXFRUjNKc1VPTUx6Y2VUNDEyQXdDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNakE1TVRFd05URXhNREJhRncweU16QTVNVEV3TlRFMk1EQmFN
      SGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWti
      MjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVD
      eE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUMG9ZekZzdDIyWmUwdVp5aWVZRlVLCm1VOG0w
      Q1RLajBBUjNBY0dVRWNOc05YcUxUMzdST1B4R2tlMWdROUsxdGUzeWRkaDhSbldDYm9hYmN1SGtY
      TlMKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRQpGRE1ZOC83RFRtcHIwYmtnVS9ZdXdORmNnNEhITUI4R0ExVWRJd1FZTUJhQUZO
      OC9PdEJ4aU1lY1FFajl5NUxBCkJXTGhlcXh2TUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxU
      WmtOR00yWmpjMlpHWXRaMnBvY25Rd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5
      SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFX
      eHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFX
      NUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpq
      MEVBd0lEU0FBd1JRSWhBTW5oTUZhUlpuSnZrKzVCSUhGWXk1Q2JLTzluakNodktic20wK2dIcFFW
      VgpBaUFjMVQwNkttc1dKVXNVMU4rQkhENU9PZkJYQVhyNHdEeHNaejNRQlgwOTBnPT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVVjQ5OUIwcTB4WDhHRmNwMnAyK01uUzZHVDBB
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTVNVEV3TlRBek5URmFGdzB5TlRB
      M01ERXdOVEF6TlRGYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0
      eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFV
      RUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05D
      CkFBU0NLVFBVRnNWcFNjOTN1N3V5bmR5eUxPRFc1SUxaWk15aUo5YnhSc2dzdDhlQ3Z3bVhjM1dK
      Nlp3cGo1NFcKekowV1puWkZuU3B0eDQ2U0tZQ3p4WnNLbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFE
      QVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVUzejg2MEhHSXg1eEFTUDNM
      a3NBRll1RjZyRzh3Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ1F2cmpPUWRCUytvNHhQdXNkSVpL
      ei8rU1RWYitMazI4VHdwMFh1dk5QcEFDSUNKMy9BblYKbEx1SjRoSmNFQmtnYkFYcDFjR0M4WVky
      RklnMDl6RDNOWmR3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIc
      EggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0S
      EhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////
      DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1u
      ZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZW
      MV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
