apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIEbpTNbkGeAmIESMGgrMmUYysvu+bgqOPnFBOwW0iOzcEqheCqVeCqJeCngKWggBEAEaBgiE
      uqmWBiIKc3lzY2hhbm5lbCpAMTA1MjRmYTQwNGNiOTJjYmFmZWJiNWUxOGQyMDE1MTQyYmYwNGMw
      YmZiNmQ3YThjZWRlNzhmNjgxN2MxNDhhNRIaEhh0JVDcQpRXQrhLsMryp4wpkdmxIlz+d/4SpV0K
      ol0Sn10SjysKB09yZGVyZXISgysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVWTFtY2ZqQnJkZDhzcy83RzNoc2hOSVc1OWNBd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFd01EUTBORE16V2hjTk1qVXdOREk1TURRME5ETXpX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJJOU5z
      WmtXQitxTFduZEwxdm9jV0UrY2JmV0JnOUE1VDZBYWhHcmNRVHVpYS9POHVCMkMKcHBQZG1HWEFu
      eXNJeHZnTElTY1NoQmZQL3FUV0RLZFlzOUNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVGxnNVNBRjd1YXYzVXUzd0l4Q1R3eUdr
      TEdjakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBNHNLQkNTdVM0WDZkdE9WTjNjRkc4V1hBUnF1
      SXhmWSsyZlFobng3dzMKN3dJaEFOQnFRTVg0ek4xNzFDT29jU3BVVDI1bEcwOWw4bFZ6SGVaZWE4
      NkFab0VTCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVZDhkUmJpZWYwaDNpSms4c2dzcjFiaVI1SUlzd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFd01EUTFNakF3V2hjTk1q
      TXdOekV3TURRMU56QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFaWFUd2pCcUs2Z00xSUs4TGdIQjhkbjNRcmdN
      c21yZlUKTlY1WE4wdkJQTFBNN21tVUl1L0FycGJNS01SdE5ybEdDV1hCKzk4NkhrTCtNY1VyQzRD
      SkRxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTVjBrL0lTVWluClpYMHcxZ0tnMFpuWnUzbmZBVEFmQmdOVkhTTUVHREFXZ0JU
      bGc1U0FGN3VhdjNVdTN3SXhDVHd5R2tMR2NqQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xXMDRPV3AwTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQU1EaE11OVdaQmRMdTVsVGtoUE5GUWV0bzVGdWlpZ01xYWNCWnRhUHprb09BaUJO
      VEE1SUlKa2dYak9tCkpMWXB3YzZIVlFqbEVONlpkUGlsck9JcUlKWVpjZz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVkxbWNmakJyZGQ4c3MvN0czaHNoTklXNTljQXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RXdNRFEwTkRNeldoY05NalV3
      TkRJNU1EUTBORE16V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCSTlOc1prV0IrcUxXbmRMMXZvY1dFK2NiZldCZzlBNVQ2QWFoR3JjUVR1aWEvTzh1
      QjJDCnBwUGRtR1hBbnlzSXh2Z0xJU2NTaEJmUC9xVFdES2RZczlDalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRsZzVTQUY3dWF2
      M1V1M3dJeENUd3lHa0xHY2pBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQTRzS0JDU3VTNFg2ZHRP
      Vk4zY0ZHOFdYQVJxdUl4ZlkrMmZRaG54N3czCjd3SWhBTkJxUU1YNHpOMTcxQ09vY1NwVVQyNWxH
      MDlsOGxWekhlWmVhODZBWm9FUwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxqCEgoNQ29uc2Vuc3VzVHlwZRLwERLlEQoIZXRjZHJhZnQS2BEKwREKGG9yZGVy
      ZXIxLnN1cHBseWNoYWluLW5ldBCKNxrPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlE
      QWpDQ0FxbWdBd0lCQWdJVUg1M0g0Ymo3ZEdwY2R3V25xb1RVOEU3amdIWXdDZ1lJS29aSXpqMEVB
      d0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpk
      WEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RXdNRFExTWpBd1doY05Nak13TnpFd01EUTFO
      ekF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZU
      Rzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlN
      U0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Fo
      a2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFFK0FCYVVUc3lJdDJLNTBERFBTM2VYU1VDCkszMXdy
      TXJIZmJGbllTWktNangvRmswYU5EdkI1bGtaQ2trai9jMlczZWJITWNvdkdDZjVqelBhbUU4eG80
      SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3
      TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFGaDBDa2hn
      bnhYc2JIMmlhTysyVDlGb1hmCnRUQWZCZ05WSFNNRUdEQVdnQlRsZzVTQUY3dWF2M1V1M3dJeENU
      d3lHa0xHY2pBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpY
      U0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJH
      QjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JX
      VnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pT
      STZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnU3YvZS9yaXVMd05wZmph
      SwpQN2d6M2hTYjBhZHIySElXTmxDcGtCeDRGbjBDSUhEUFpGQzVsdm43SW9Hb1dQWUMzOW9ZdnN3
      RDlzVytvdGdiClJ4Q0pXSUZiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIs8ILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVSDUzSDRiajdkR3BjZHdXbnFv
      VFU4RTdqZ0hZd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFd01E
      UTFNakF3V2hjTk1qTXdOekV3TURRMU56QXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUUUrQUJhVVRz
      eUl0Mks1MEREUFMzZVhTVUMKSzMxd3JNckhmYkZuWVNaS01qeC9GazBhTkR2QjVsa1pDa2tqL2My
      VzNlYkhNY292R0NmNWp6UGFtRTh4bzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUUZoMENraGdueFhzYkgyaWFPKzJUOUZvWGYKdFRBZkJnTlZIU01FR0RB
      V2dCVGxnNVNBRjd1YXYzVXUzd0l4Q1R3eUdrTEdjakEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1
      ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1
      SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmho
      YVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBd1JBSWdTdi9lL3JpdUx3TnBmamFLClA3Z3ozaFNiMGFkcjJISVdObENwa0J4NEZuMENJSERQ
      WkZDNWx2bjdJb0dvV1BZQzM5b1l2c3dEOXNXK290Z2IKUnhDSldJRmIKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICAChoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsI
      ChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hh
      bm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzIS
      ABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFs
      aWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFk
      ZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxLH
      LwoLQ29uc29ydGl1bXMSty8S7C4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLSLhK7FwoPbWFudWZh
      Y3R1cmVyTVNQEqcXGq8VCgNNU1ASpxUSnBUSmRUKD21hbnVmYWN0dXJlck1TUBKGBi0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVWYvSVNkVlg0ZEcwT2lrRzBx
      NXMrZGcxMXgyQXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFa
      bUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05N
      akl3TnpFd01EUTBOak0zV2hjTk1qVXdOREk1TURRME5qTTNXakJrTVFzd0NRWURWUVFHCkV3SkRT
      REVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJB
      b00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxX
      NWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQlBubTRNVXljSGwrQlEzMldM
      eUxpWVA5Z1B6QWFPS2t1dDZLCkZ2bnBWS2EwSE1hQU5RSlpCZmRWZVEyeFRUYWNmU29ESmN5ZHdN
      QTFzZTQySE9Za01WeWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJTSEpnTSsxSmk3WnJTbQplM3B6Tmp5RmsybEppakFLQmdncWhr
      ak9QUVFEQWdOSkFEQkdBaUVBOWFnMmEyRGh6dWFsV2FEd2tIbTcyRGJFClczZjF5K3dRQ2tna2Nx
      NktYQUlDSVFDRjYyQWwrUk16N1FTVmM0UktBQWVsdUFPdmRhSWR1NGlKUnJHaVJkOEsKdHc9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlERVRDQ0FyZWdBd0lCQWdJVUJXUzVFNVRkNXl4c01qc0F1VlpIS0FRZENTd3dDZ1lJS29aSXpq
      MEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJB
      TU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpFd01EUTFOREF3V2hjTk1q
      TXdOekV3TURRMU9UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xq
      TTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJn
      TlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERC
      WkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpq
      MERBUWNEUWdBRUp4S2JlbEVaOEE5TE1EeFNDYkFzV3A3dEt4TWV5LzZ2TVZGSVdYKzkyMkJScWhK
      RjZWbkMKaG92QThyV3F4ZFRIcVlScHNMMFM4YkVVcEV0WFFNUXpsYU9DQVNJd2dnRWVNQTRHQTFV
      ZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVEQ2SndHZFIw
      cXNkMHVWUmF5WFhZOHpPY3dTekFmCkJnTlZIU01FR0RBV2dCU0hKZ00rMUppN1pyU21lM3B6Tmp5
      RmsybEppakFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMV1EwYkhv
      Mk1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhK
      MVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFda
      aFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNS
      MWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBMnA2dHhQcGNScHBzMFprOVRKOFhINU54OUZzQjhDZ0FYWnZ2UWVTaHhWQUNJQ3Jr
      Y0xQcld5dmJDT1RiCmt2bnhwRStTN1ZRYkxCdUFRSGx1YXZVNlNnOHoKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoYGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNEVENDQWJLZ0F3SUJBZ0lVZi9JU2RWWDRkRzBPaWtHMHE1cytkZzExeDJBd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekV3TURRME5qTTNXaGNO
      TWpVd05ESTVNRFEwTmpNM1dqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5
      YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEps
      Y2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5
      QWdFR0NDcUdTTTQ5QXdFSEEwSUFCUG5tNE1VeWNIbCtCUTMyV0x5TGlZUDlnUHpBYU9La3V0NksK
      RnZucFZLYTBITWFBTlFKWkJmZFZlUTJ4VFRhY2ZTb0RKY3lkd01BMXNlNDJIT1lrTVZ5alFqQkFN
      QThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdC
      QlNISmdNKzFKaTdaclNtCmUzcHpOanlGazJsSmlqQUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUE5
      YWcyYTJEaHp1YWxXYUR3a0htNzJEYkUKVzNmMXkrd1FDa2drY3E2S1hBSUNJUUNGNjJBbCtSTXo3
      UVNWYzRSS0FBZWx1QU92ZGFJZHU0aUpSckdpUmQ4Swp0dz09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1
      cmVyTVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21h
      bnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9t
      YW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoP
      bWFudWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxK2FgoKY2Fycmllck1TUBKnFhrDFAoDTVNQ
      ErsUErAUEq0UCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIr
      RENDQVo2Z0F3SUJBZ0lVU1lsK2dVWDNWQVMwd0Z5dEwyYkRzRHhyc2Fvd0NnWUlLb1pJemowRUF3
      SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allY
      SnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNVEF3TkRRNE16ZGFGdzB5TlRBME1qa3dORFE0TXpkYU1G
      b3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJr
      eHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNt
      bGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVGZ5WlNQUFlESzZk
      Y3kvQzdjcWwzRk9ybjRDNmNXZ0ZsblBPMll1R3FScTVVRFo3SERtbTNzVlVJUzBTTWgKTlBzS2NJ
      N3VaeU1NMUhnQVNWcEp4Q08wbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdF
      Qgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVUrelNKbTlXVnM3bnhKVURGcVBWci9qc3RwU1F3Q2dZ
      SUtvWkl6ajBFCkF3SURTQUF3UlFJaEFJbFpkQkg0SFhabCtZSEtmSE95Q2ozYS9iOEV0cVptNlhk
      ZU9sSE8rcnFoQWlBS0VMOWYKTmtuTGFrbE1RWFZyZ1hEZjdnd0ZsV0JHeVZKS0pzZk1ZckEyL2c9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlDN2pDQ0FwU2dBd0lCQWdJVVMzYnVBT2dmTFBQQklsRk9iTzJDdkdVNzhhMHdDZ1lJS29a
      SXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1
      allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakEzTVRBd05EVTJNREJhRncweU16QTNNVEF3TlRB
      eE1EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5
      TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0
      R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUMk03K3QrVnhkZ2pNSm9kRnJPRXBt
      CmZZN1NCUDBRWmZUenNBSG11OHMvQVpjQkZTK1BjVC9sNzRxd3RaU1RwK2ErSFU1VGhRRHBBSldU
      V0JMMFZDZFoKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FD
      TUFBd0hRWURWUjBPQkJZRQpGTnFmUlVGNkRibDM5QmVCQUw2K3IwRFVYUXkzTUI4R0ExVWRJd1FZ
      TUJhQUZQczBpWnZWbGJPNThTVkF4YWoxCmEvNDdMYVVrTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2
      YjJ4ekxUWmtOR00yWmpjMlpHWXRORFJ6TjNBd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5
      Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1
      UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9p
      UVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkK
      S29aSXpqMEVBd0lEU0FBd1JRSWhBSTNQWWlGN1FHeEZxWm1hNXU1emxIWThPL0JvT2xYM1gxbHIz
      d3FjL3V3NQpBaUJuajV0d0dXeU0xUlVvRm1HN0tlT0JXY1RXS1crWnQ2MXlHRmd0dWk1V3N3PT0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVU1lsK2dVWDNWQVMwd0Z5dEwyYkRz
      RHhyc2Fvd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlN
      UmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNVEF3TkRRNE16ZGFG
      dzB5TlRBME1qa3dORFE0TXpkYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1i
      MjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApN
      QlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BR
      TUJCd05DCkFBVGZ5WlNQUFlESzZkY3kvQzdjcWwzRk9ybjRDNmNXZ0ZsblBPMll1R3FScTVVRFo3
      SERtbTNzVlVJUzBTTWgKTlBzS2NJN3VaeU1NMUhnQVNWcEp4Q08wbzBJd1FEQVBCZ05WSFJNQkFm
      OEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVUrelNKbTlXVnM3
      bnhKVURGcVBWci9qc3RwU1F3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFJbFpkQkg0SFhabCtZ
      SEtmSE95Q2ozYS9iOEV0cVptNlhkZU9sSE8rcnFoQWlBS0VMOWYKTmtuTGFrbE1RWFZyZ1hEZjdn
      d0ZsV0JHeVZKS0pzZk1ZckEyL2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoG
      QWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5k
      b3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVh
      ZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAK
      FUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmls
      aXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNI
      QTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1p
      bnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3MDUw
      GhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
