apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIO0ujt4ZTJLOBav35gBJ7h1L365WT7c7RkiMosSEPuVjEqpeCqdeCqReCngKWggBEAEaBgjD
      8OKWBiIKc3lzY2hhbm5lbCpAOTE3ZjIzYjc4ZjBlM2RkMTI1NTVmYTU2MDM3ZTEyZmM3YzQ2MDc5
      YzcwYTE5MjA2NjczZTNiZWYxMDYyYzhiORIaEhhRSpYzTurcxYIGGC01uTsdcs1PfxATSw0Sp10K
      pF0SoV0SmysKB09yZGVyZXISjysS0hYKDnN1cHBseWNoYWluTVNQEr8WGssUCgNNU1ASwxQSuBQS
      tRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVYTFRZUpKM21mMjdTV3pQT0NKekxOTllvWjdvd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJeE1ESXdORFUyV2hjTk1qVXdOVEV3TURJd05EVTJX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJBWVEy
      ZVFlWWRGTHo5bTVvbHM0djQ4ZlNzQWsvTzhmdmJDY2pQZzZpaCtGQ0pkNmtRdkYKUHY2ajlhcUlE
      dWJ0UDJndTAyWC9WQ1BNNEVnaU1xTmQrbW1qUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVEtPOHRTL2tud0FCSUE0cG91VzlobTVy
      cTdEekFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQWcrSGhxZ2YvMkd1OW5LS1FqNFQyMW1ITWQ1
      aDBZSFNRR0hGMWJXa3IKOTZRQ0lRREtEWWhHQmt1SnVqVUFhNi9NcTlIWlFYZElkTEt6c2Z4bkRO
      TDBwcTRHOGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKiCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNFRDQ0FvaWdBd0lCQWdJVWUrWVdCbWdXODBqQk5kelNTVVBNcG5lUEVn
      c3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056SXhNREl4TXpBd1do
      Y05Nak13TnpJeE1ESXhPREF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXRKTVlWQUMzbGtDcVVhYjhsdUMzeUs2
      VzhneUlIZ1g4CjJ3WjlMbTkxWGVtL0NNb2RyWmI0K3V0SklWeHJKQWhkUGk1anJyZnZkWnE4c0RU
      ZlNaUjBFYU9DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUnY1QldkSjI3SQorTDNJL3pJVFRZM09oNE8zWmpBZkJnTlZIU01FR0RB
      V2dCVEtPOHRTL2tud0FCSUE0cG91VzlobTVycTdEekFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDFOalkzWXpZM1ptWTNMWFE0ZUhCaU1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFJ3QXcKUkFJZ2NjTTV0cVQ4S09hQ3VrTWhlSmpvTEdmRzNQaVFOdFJNaVJ5Y2VxNTlhamdD
      SUczWUYvUE9XWG9NNXVTWQozUVY5NE0yclhqb2dhQUQ4UHIxS0dXN1g0ZHJ3Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkr1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVWExUWVKSjNtZjI3U1d6UE9DSnpMTk5Zb1o3b3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056SXhNREl3TkRVMldoY05NalV3
      TlRFd01ESXdORFUyV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCQVlRMmVRZVlkRkx6OW01b2xzNHY0OGZTc0FrL084ZnZiQ2NqUGc2aWgrRkNKZDZr
      UXZGClB2Nmo5YXFJRHVidFAyZ3UwMlgvVkNQTTRFZ2lNcU5kK21talFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRLTzh0Uy9rbndB
      QklBNHBvdVc5aG01cnE3RHpBSwpCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUFnK0hocWdmLzJHdTlu
      S0tRajRUMjFtSE1kNWgwWUhTUUdIRjFiV2tyCjk2UUNJUURLRFloR0JrdUp1alVBYTYvTXE5SFpR
      WGRJZExLenNmeG5ETkwwcHE0RzhnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlu
      cyI7CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZB
      ZG1pbnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZB
      ZG1pbnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZB
      ZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoG
      QWRtaW5zKgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVs
      UmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMhIAGgZB
      ZG1pbnMaihIKDUNvbnNlbnN1c1R5cGUS+BES7REKCGV0Y2RyYWZ0EuARCskRChhvcmRlcmVyMS5z
      dXBwbHljaGFpbi1uZXQQijca0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NB
      cW1nQXdJQkFnSVVEYmJiZlg0a0NMcXJEVnUyVWRQNlRab3N3YkV3Q2dZSUtvWkl6ajBFQXdJdwpY
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekl4TURJeE16QXdXaGNOTWpNd056SXhNREl4T0RBd1dq
      QnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpH
      OXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3
      WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BR
      SUJCZ2dxaGtqT1BRTUJCd05DQUFTRnVkM1ZpVWh6WjlvdzA2dEJoT2hRUkwzTwpQK1l1dDh5UWov
      anVPa3RXMkxpZWhkNUZYa2t1MFl3cnRmY0lqcExud1dBQWpUdFpNZ3dkTkxwVWd4b2pvNElCCk1E
      Q0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdn
      ckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSMlY3V3l1TnJCbDI4
      ZFZ5ZjhwQXd1cXErNgorakFmQmdOVkhTTUVHREFXZ0JUS084dFMva253QUJJQTRwb3VXOWhtNXJx
      N0R6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205
      eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1G
      MGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVs
      RUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05
      eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFKbncyY29vSUhXdGN4ZkgKYWdO
      RVdKM09hc2JSY3JWazgrQWlNTjNtSDBnRkFpQWxNbGYwZGJoWEFGNnZmWVY1Y3ZtRDZaS2NEMkdU
      VHRENApkOU9KSEFOZmFBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi0wgtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVEYmJiZlg0a0NMcXJEVnUyVWRQ
      NlRab3N3YkV3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21W
      eU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekl4TURJ
      eE16QXdXaGNOTWpNd056SXhNREl4T0RBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFV
      RUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3
      CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxq
      YUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTRnVkM1ZpVWh6
      WjlvdzA2dEJoT2hRUkwzTwpQK1l1dDh5UWovanVPa3RXMkxpZWhkNUZYa2t1MFl3cnRmY0lqcExu
      d1dBQWpUdFpNZ3dkTkxwVWd4b2pvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBH
      QTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFB
      TUIwR0ExVWREZ1FXQkJSMlY3V3l1TnJCbDI4ZFZ5ZjhwQXd1cXErNgorakFmQmdOVkhTTUVHREFX
      Z0JUS084dFMva253QUJJQTRwb3VXOWhtNXJxN0R6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5
      TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UK
      WTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJ
      am9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhh
      VzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURT
      QUF3UlFJaEFKbncyY29vSUhXdGN4ZkgKYWdORVdKM09hc2JSY3JWazgrQWlNTjNtSDBnRkFpQWxN
      bGYwZGJoWEFGNnZmWVY1Y3ZtRDZaS2NEMkdUVHRENApkOU9KSEFOZmFBPT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICAChoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIV
      EgsIChCAgIAxGICAQBoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5z
      IioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIX
      Eg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1p
      bnMqBkFkbWlucxK9LwoLQ29uc29ydGl1bXMSrS8S4i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLI
      LhKxFwoPbWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1T
      UBKBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lCQWdJVVdWSys2
      RFNBWEtBTFVvTXJwZXU5YUJEWHN5WXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNR
      MGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURW
      UVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApj
      aTF1WlhRd0hoY05Nakl3TnpJeE1ESXdOalUzV2hjTk1qVXdOVEV3TURJd05qVTNXakJrTVFzd0NR
      WURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFky
      Z3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRX
      WmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk1KTzI1
      LzNtcVJ2N1FpN0U1T0lGY05yWnk0VzZZNVk3UnNJCkhlbmQ0VVdUYVR3ckNaOG05YXpETFpNMUw0
      cUJZM3ZCYS9Gektjd1Nucko2RmdEdFMyYWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0Rn
      WURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJSMFFjNi9DRUYxblBGRQp4QjBFaXNnUG9J
      UGJlakFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUJYek5mWi9TT0dxbDlYUndTQVprQ1Mrb3JBCkwr
      ZUgra3lKVVlFUy9FZlRtUUlnZnp1L3FrZzF0REhuM0N3NEFoN2RUMVAvaTNSZ1o1THZBb1BJWEcw
      a3Jvbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJREVUQ0NBcmVnQXdJQkFnSVVHVWlSMG9YbkR0MmZZeDNZcHp3a1pmMTlPMUF3Q2dZ
      SUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURF
      UE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERB
      YUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056SXhNREl4TkRB
      d1doY05Nak13TnpJeE1ESXhPVEF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFj
      VEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJ
      eEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZ
      RFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSQp6ajBEQVFjRFFnQUVQV25HVjcreUVBUS9FTk5CbE5jc3FYZkRxNjg1VEhsYnd1ZkNDeEd1
      WUhrNUFRcHZQVTBWCnpWUUUvdkpFWmppck9PdU9oWms3dkpwM0ZPRHpOcGlPMGFPQ0FTSXdnZ0Vl
      TUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlRC
      UXJvU1JaT0tndk56eVdqK2wzZTBuU01FZ1RBZgpCZ05WSFNNRUdEQVdnQlIwUWM2L0NFRjFuUEZF
      eEIwRWlzZ1BvSVBiZWpBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAzWTJRM1ptUm1PVGMy
      TFRRMllqSmlNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWww
      SWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9p
      YldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVk
      V1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9Q
      UVFEQWdOSUFEQkYKQWlFQXlGV2h0bkxZTXdjbm0wL3drNUNpNFFDYy9iRUJxakRlY0pCSzNmaStN
      aDRDSUd1REsvOUJFdzB3MmlBQQpSQU5rbTVLdFFzdHJvTHVKbVF1TkNSY3I2S0srCi0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lCQWdJVVdWSys2RFNBWEtBTFVvTXJwZXU5YUJEWHN5WXdD
      Z1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGph
      REVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhI
      REFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpJeE1ESXdO
      alUzV2hjTk1qVXdOVEV3TURJd05qVTNXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVD
      QXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1Z
      V04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpC
      eXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk1KTzI1LzNtcVJ2N1FpN0U1T0lGY05yWnk0VzZZ
      NVk3UnNJCkhlbmQ0VVdUYVR3ckNaOG05YXpETFpNMUw0cUJZM3ZCYS9Gektjd1Nucko2RmdEdFMy
      YWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0Ex
      VWREZ1FXQkJSMFFjNi9DRUYxblBGRQp4QjBFaXNnUG9JUGJlakFLQmdncWhrak9QUVFEQWdOSEFE
      QkVBaUJYek5mWi9TT0dxbDlYUndTQVprQ1Mrb3JBCkwrZUgra3lKVVlFUy9FZlRtUUlnZnp1L3Fr
      ZzF0REhuM0N3NEFoN2RUMVAvaTNSZ1o1THZBb1BJWEcwa3Jvbz0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQoaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVm
      YWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIR
      Cg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zErYWCgpjYXJyaWVyTVNQEqcWGsMUCgNN
      U1ASuxQSsBQSrRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      QitEQ0NBWjZnQXdJQkFnSVVCT2cwY24vM0xkNCtNQktVY0Y3K0U2Y1V3RUV3Q2dZSUtvWkl6ajBF
      QXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVF
      Qnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVq
      WVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01qRXdNakE1TURCYUZ3MHlOVEExTVRBd01qQTVNREJh
      TUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNN
      Qmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5
      Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFSck5wNENUZUYz
      SUYwMGR2QnFkZUx1WjFpemd0cm9jNStFOG5QNzV3YzV6MVdmK3lsT2o3dUxCUE9wSmV6SwplS010
      OWxkZGdQZGFESU1KZnp1VWQyOHVvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWRE
      d0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXpiNGNIa1lkVFF5L1UyZ3JWL0xNNkZ5N2UwNHdD
      Z1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU1QNWNrb2xSQVpSWE5oYy82R1lyc25UUWNrQzZGeWxw
      cHJRTjk5bEFEL1RBaUFMeDVaQwpDVVJTWDFRNStFRWtSc3FtKzI0OGx3b0pZSEN3QVJjM3J3MVNj
      UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUM3akNDQXBTZ0F3SUJBZ0lVY01jQS9SNkYxeHlUbW9qQkdsMm4vYjlueHlFd0NnWUlL
      b1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUURE
      QTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNakV3TWpFMk1EQmFGdzB5TXpBM01qRXdN
      akl4TURCYU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhN
      eTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVN
      QTRHQTFVRUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNxUGQvcFdYQk16TmhldXhkU000
      OGIKUy9HWURWQzA4amhiU0pTbjFBWFBPTXRqcDdGbi9rZmgwNERRejlpaVJidCt0NndVUWZPWmNm
      YjVqU2JyNXNweQpvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93
      UUNNQUF3SFFZRFZSME9CQllFCkZGV2tKd1ljOG5EWS9DZk5aaHhpRm1POS9hRlRNQjhHQTFVZEl3
      UVlNQmFBRk0yK0hCNUdIVTBNdjFOb0sxZnkKek9oY3UzdE9NQ1FHQTFVZEVRUWRNQnVDR1dOaExY
      UnZiMnh6TFRaa05HTTJaamMyWkdZdE5UbG1kbXN3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRI
      UnljeUk2ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFH
      WXVRV1ptYVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlq
      b2lRV1J0YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZ
      SQpLb1pJemowRUF3SURTQUF3UlFJaEFLQzExV2xTR1hvMHBFZEJaVHhycWxyT2tvVkV2bHhnUUxP
      ejlrZTdZdGptCkFpQldWRFNDcFRsanZnSk9qN3hLQlBwQThzR1dMUVNMYXlNRjZVV3BxUUdib1E9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVCT2cwY24vM0xkNCtNQktVY0Y3
      K0U2Y1V3RUV3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01qRXdNakE1TURC
      YUZ3MHlOVEExTVRBd01qQTVNREJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFa
      TWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVY
      Ck1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pP
      UFFNQkJ3TkMKQUFSck5wNENUZUYzSUYwMGR2QnFkZUx1WjFpemd0cm9jNStFOG5QNzV3YzV6MVdm
      K3lsT2o3dUxCUE9wSmV6SwplS010OWxkZGdQZGFESU1KZnp1VWQyOHVvMEl3UURBUEJnTlZIUk1C
      QWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXpiNGNIa1lk
      VFF5L1UyZ3JWL0xNNkZ5N2UwNHdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU1QNWNrb2xSQVpS
      WE5oYy82R1lyc25UUWNrQzZGeWxwcHJRTjk5bEFEL1RBaUFMeDVaQwpDVVJTWDFRNStFRWtSc3Ft
      KzI0OGx3b0pZSEN3QVJjM3J3MVNjUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMi
      NwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMi
      MwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdX
      cml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMa
      QAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJl
      ci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoX
      L0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hp
      bmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0
      dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5z
      dXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0
      aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoG
      QWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
