apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIJoBlZnG+88t2pUvPB++bU8Id3+eshUBh8ZG+pMQvxAQEp5eCpteCpheCngKWggBEAEaBgjh
      sv6ZBiIKc3lzY2hhbm5lbCpAZTRlMzFhOWRmNDJlNTc1NmUwYmMxOWM1MmFhYmY3YzJmODdkODdh
      ZDhjYTFiNDBiZmYzYTU2ZDJlMzc0YTg1NRIaEhhE/T7sKQR5+yg24+GJ7CRvFGUrBCGtGQcSm10K
      mF0SlV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVQXhNRmxtV0FoT2ZiNjFtVFZWOEVDeGwvOFhzd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBM01ESTFOak00V2hjTk1qVXdOekkzTURJMU5qTTRX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJBcHdI
      NFJLbkxUTVdDNitYNEwvRitwRmJPWVV1a2VIWnhFcUJ4bnl0VTI5UCtZNTFQSGgKZER6YUVhVjdT
      T0txK2haS3NGTDdPNldmdUtFRWNuMFlDeVNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUXg3a09ZOG11dmhUN2dvcmVoK01MNSsx
      d0h5ekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQWpoVDZ1OTNOSUswWWEwV0tVNWJSOWlwcHpt
      L0xqUkNzWWdLaU1ZOW4KSjFZQ0lHK29pMEFRYVFXVEhKZk1rdktWbzhEWGMvbUhNNmJXdmpQRkFp
      aEc1WUMrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVWW1LK0Qxbm13QXphNVFpTGlCUVV1TVo5N1NFd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBM01ETXdOREF3V2hjTk1q
      TXhNREEzTURNd09UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOVptMm0yRWN2eStGTmJxMy84OVE3eEt2S09m
      dWRwMW8KOEtKVGl1cmZPSlk5SzBEV1ZDMlM0OUFoUC9vcHdzRXBpOUg5Ty8zMHZsOEsxZE9Rc0NQ
      Vkw2T0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSZWZLUllodVdnCjFMcDBHRHRua0RPTXhFTVpUakFmQmdOVkhTTUVHREFXZ0JR
      eDdrT1k4bXV2aFQ3Z29yZWgrTUw1KzF3SHl6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xUUnpabk5vTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnYWtXQ09yMXhMYkJDZ2h6NEN6TGZ5bjhDS3BoQVo2bzVXVGNhZm13TWc5UUNJQ2hW
      U3pOaDB1YUFDK2cxClRlYW5lMWFxRTl2SWpxRUExNk5pTW1QcHU1M2oKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVQXhNRmxtV0FoT2ZiNjFtVFZWOEVDeGwvOFhzd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBM01ESTFOak00V2hjTk1qVXdOekkz
      TURJMU5qTTRXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJBcHdINFJLbkxUTVdDNitYNEwvRitwRmJPWVV1a2VIWnhFcUJ4bnl0VTI5UCtZNTFQSGgK
      ZER6YUVhVjdTT0txK2haS3NGTDdPNldmdUtFRWNuMFlDeVNqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUXg3a09ZOG11dmhUN2dv
      cmVoK01MNSsxd0h5ekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQWpoVDZ1OTNOSUswWWEwV0tV
      NWJSOWlwcHptL0xqUkNzWWdLaU1ZOW4KSjFZQ0lHK29pMEFRYVFXVEhKZk1rdktWbzhEWGMvbUhN
      NmJXdmpQRkFpaEc1WUMrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vu
      c3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCK
      NxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVUdsVXhm
      N3FGdkVxR3Y5L2xDMG51dllodXlVVXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURW
      UVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpI
      aGNOTWpJeE1EQTNNRE13TkRBd1doY05Nak14TURBM01ETXdPVEF3V2pCeE1Rc3dDUVlEVlFRR0V3
      SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3
      ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNt
      VnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkNBQVFpYmN6VUxaVWowVlpodkdTdXJ1SGRzNFFPClo4czNmNGlTTk9EWlJocWF0ZFh3N0l0Y2w3
      aFVIZ1pGaFA4WC8yV0hUa3VpVFlVeXVDUnprRExGT3hyTW80SUIKTURDQ0FTd3dEZ1lEVlIwUEFR
      SC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJn
      TlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJvaFJkcytFQnBuK25RNno0NkdBemljSXNDCjd6
      QWZCZ05WSFNNRUdEQVdnQlF4N2tPWThtdXZoVDdnb3JlaCtNTDUrMXdIeXpBL0JnTlZIUkVFT0RB
      MmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1W
      c2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtG
      bVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pF
      dWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZ
      SUtvWkl6ajBFQXdJRFNBQXdSUUloQU5yMzJ0eUlpcUExNlFpNAo5eTNRYjQ3YVZzY1dXQ3VJZ29w
      Z29IODU0SmRNQWlBWnVYbVlqN28yaEN5V0FJWFE1SStmTDl2TkdydWRWYmJCCktHRXpDZVA3Q3c9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlEQXpDQ0FxbWdBd0lCQWdJVUdsVXhmN3FGdkVxR3Y5L2xDMG51dllodXlVVXdDZ1lJS29a
      SXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJK
      allTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1EQTNNRE13TkRBd1doY05Nak14TURB
      M01ETXdPVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRB
      dU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21S
      bGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVFpYmN6VUxaVWowVlpodkdTdXJ1SGRzNFFP
      Clo4czNmNGlTTk9EWlJocWF0ZFh3N0l0Y2w3aFVIZ1pGaFA4WC8yV0hUa3VpVFlVeXVDUnprRExG
      T3hyTW80SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NH
      QVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJv
      aFJkcytFQnBuK25RNno0NkdBemljSXNDCjd6QWZCZ05WSFNNRUdEQVdnQlF4N2tPWThtdXZoVDdn
      b3JlaCtNTDUrMXdIeXpBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0Zw
      YmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVH
      QndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5
      YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUK
      Vkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU5yMzJ0eUlp
      cUExNlFpNAo5eTNRYjQ3YVZzY1dXQ3VJZ29wZ29IODU0SmRNQWlBWnVYbVlqN28yaEN5V0FJWFE1
      SStmTDl2TkdydWRWYmJCCktHRXpDZVA3Q3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChIS
      CgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZB
      ZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rp
      b25zEggaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1p
      bnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SshYKCmNh
      cnJpZXJNU1ASoxYavxQKA01TUBK3FBKsFBKpFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVWNkaUpheUhQT1dFUlBBa2FCWklrbU5U
      YnpPUXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJj
      d0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV3TURjd016QXdORE5hRncw
      eU5UQTNNamN3TXpBd05ETmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1
      a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJV
      R0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1C
      QndOQwpBQVJEQjB3VHJUdlNOeDdScDU0cDArNEE0SXhLM2poeFdRVFIvMWg3NHIvaXJqM0pnVjRi
      RzNzcmNmUzliWUx4CjhQNi9Bc1p0TEZBSWNHeWQ3UmIxcmpleW8wSXdRREFQQmdOVkhSTUJBZjhF
      QlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVM2hXTmFDQUp2QWpj
      ellhZkFURTZBWTFKNG93d0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBTzNlUFBscE1zZDQ5M3Uw
      eFVPVzJFSjdkbUpNSldqUXlYRUdSeWhiS0lOZEFpQkZkajhMCkU1ekZLYlBQNmMwSjJ1TG1KbmtU
      QVZBYjNvbHl0bjVUNkRaRFhBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdUQ0NBcFNnQXdJQkFnSVVUbTN5OERzWGlkYnBzc2Ix
      SWtNN29jTFJ1cVV3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05W
      QkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5
      YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFd01EY3dNekE0
      TURCYUZ3MHlNekV3TURjd016RXpNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFI
      RXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1C
      Z05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRh
      VzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUk5p
      a0N5aHIvb1ZsdXZ4akJXbXBieQpDbysvVkJRNzdsOFpnMVRYdDB2SlFDQjJLZ2dUa2psK2p6WHFw
      dTI3Zy9URFJReTNzWkVLbFMxWkYrM2dua3dpCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURB
      Z2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRlB1WW5aaFErL3VWT3Q2YTF0aWxE
      anpEczRNNk1COEdBMVVkSXdRWU1CYUFGTjRWaldnZ0Nid0kzTTJHbndFeApPZ0dOU2VLTU1DUUdB
      MVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFprTkdNMlpqYzJaR1l0WjJoak5EVXdnWTBHCkNDb0RC
      QVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFX
      NGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJX
      NXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElq
      b2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnYk00dVN0UHNMWE54SEJWRnI0
      d3g2U0FMcWpBb0twTk16WndGU2E1Q2JaZ0MKSUFGZm9Lb0pscGF6aTUxanJjYkpaTXZiMkNtbVdZ
      UzdsVU5wTnh3V2JpNEQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2
      SukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVY2RpSmF5
      SFBPV0VSUEFrYUJaSWttTlRiek9Rd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1q
      RXdNRGN3TXpBd05ETmFGdzB5TlRBM01qY3dNekF3TkROYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4
      d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3
      SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtq
      T1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUkRCMHdUclR2U054N1JwNTRwMCs0QTRJeEszamh4V1FU
      Ui8xaDc0ci9pcmozSmdWNGJHM3NyY2ZTOWJZTHgKOFA2L0FzWnRMRkFJY0d5ZDdSYjFyamV5bzBJ
      d1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0
      RUZnUVUzaFdOYUNBSnZBamN6WWFmQVRFNkFZMUo0b3d3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJ
      aEFPM2VQUGxwTXNkNDkzdTB4VU9XMkVKN2RtSk1KV2pReVhFR1J5aGJLSU5kQWlCRmRqOEwKRTV6
      RktiUFA2YzBKMnVMbUpua1RBVkFiM29seXRuNVQ2RFpEWEE9PQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tChoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJN
      U1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmll
      ck1TUBoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQ
      GgZBZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFk
      bWlucyoGQWRtaW5zErEXCg9tYW51ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFu
      dWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3
      SUJBZ0lVWkJaZ0xITUcxbklZSzlITEp3bDZENzkxbndvd0NnWUlLb1pJemowRUF3SXcKWkRFTE1B
      a0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdO
      bwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5W
      bVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNREEzTURJMU9ETTVXaGNOTWpVd056STNNREkxT0RN
      NVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFR
      SERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3
      VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdF
      SEEwSUFCSXdjTUZ2STFUcXpWS3pxTDQ5eklrMkxlTkw5YVYreVJtWUIKTEVPQldBU3loNWk3bWRX
      VkhUVHoybCs3cHNidkt4aFZZZ3ZyYjI2eVUvMVRqbGdFL2NhalFqQkFNQThHQTFVZApFd0VCL3dR
      Rk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNtL2l4amtmb3JyLzlp
      CmMzT0dhWXhqaGExMU56QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUEweTR1WDF4WGlUQU9NM25J
      UTJoYnBab3MKUzlqWW5XNmo3cGxpTHVrYy93UUNJRFZ0TmsySm8xZU5PcGhKa2hIWDRyL3FqekYx
      ME1aM09oTGY1SExSM2d0MwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlERVRDQ0FyZWdBd0lCQWdJVU95bzFkN1hGd2VacjdNYjFZenlL
      NzFtNlViNHdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdN
      QmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZq
      ZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4
      TURBM01ETXdOakF3V2hjTk1qTXhNREEzTURNeE1UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4
      R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEK
      Wm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFj
      bVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhL
      b1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdBRUxMcDJsbHRtSkxiZGpoZU9tYVVUYUlidjY5WFZo
      YjYvSE40Vmdnc1dJMW9jOEpCR3QzWEsKdEl0TzZCY1FaZ3ZhTnROckMyakFJRzFJZGl1b3pmbGNG
      Nk9DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdB
      MVVkRGdRV0JCUnBtZVBQOWtUaStYelpQaTUrUndnWWRGdE8wekFmCkJnTlZIU01FR0RBV2dCU20v
      aXhqa2ZvcnIvOWljM09HYVl4amhhMTFOekFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZ
      MlEzWm1SbU9UYzJMVFp1ZEdweU1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZ
      V0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FX
      RjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFX
      UnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZU
      QUtCZ2dxaGtqT1BRUURBZ05JQURCRgpBaUVBM01CVmJIL0JjNVZ4T1RFNnZXNWdKK1o3SHN4RnZZ
      Sk04S3RwN3g4YjFRd0NJSHdJcGNwd3VGak9jQlRmCjRWRlNNMVZZZWVlN0s3K3VKTTA3TmsvMzAr
      TTAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVWkJaZ0xITUcxbklZSzlITEp3
      bDZENzkxbndvd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJB
      Z01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVpt
      RmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1q
      SXhNREEzTURJMU9ETTVXaGNOTWpVd056STNNREkxT0RNNVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNE
      RVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFv
      TQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1
      bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSXdjTUZ2STFUcXpWS3pxTDQ5
      eklrMkxlTkw5YVYreVJtWUIKTEVPQldBU3loNWk3bWRXVkhUVHoybCs3cHNidkt4aFZZZ3ZyYjI2
      eVUvMVRqbGdFL2NhalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFR
      REFnR21NQjBHQTFVZERnUVdCQlNtL2l4amtmb3JyLzlpCmMzT0dhWXhqaGExMU56QUtCZ2dxaGtq
      T1BRUURBZ05JQURCRkFpRUEweTR1WDF4WGlUQU9NM25JUTJoYnBab3MKUzlqWW5XNmo3cGxpTHVr
      Yy93UUNJRFZ0TmsySm8xZU5PcGhKa2hIWDRyL3FqekYxME1aM09oTGY1SExSM2d0MwotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoV
      EhMKD21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYI
      ARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIG
      CAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggS
      BggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0S
      EhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////
      DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1u
      ZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZW
      MV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
