apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIPsNuAJJ9bDSvL+LDtpShh5Okw/9s0w4QVgPTSYQsmqpEqReCqFeCp5eCngKWggBEAEaBgiG
      2IKXBiIKc3lzY2hhbm5lbCpAZTFlNGU0MTlkMDA2YjY0MGNmYjc4MDY0YjE2ODZhMTQ3MmY1NDcy
      NGU1MTAyZWNiNDRiMGQxMzFiMGY4ODA5MhIaEhgDvCMhLra90+ezKxT9UA+E3hfX0XvBsqkSoV0K
      nl0Sm10SjysKB09yZGVyZXISgysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVV1lBS0gyUytPbFl0T292bmRQQzJ5dEpzeldJd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJM01ESTFNVEUyV2hjTk1qVXdOVEUyTURJMU1URTJX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJETGZj
      SXBtUHUyRWg5M1BhenZVb1VoNklKZy8rSmdxSmlNWkgwVVhxUUxoWVlqVjhQRngKY0N6WHI4V3BK
      S2ExdkJNRTk0RlN5d3NuMUw0dy9qRHJwVWFqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVDhaUjFmYVNyM3hkK0YyeFA0dDEybGhs
      MXRsekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCVThFUS81YWdnRHBEVE0wQUlEdHBYUyszUW9T
      aU8zK1Judy94T3BTVzcKS1FJaEFMT0RzbEs1UTJNV0xNcHFrUythT1JoQ3lUNkhHaWRaTDFCMmE2
      WXd5RXc5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVYkZ1dnJ0SHZxZ25nNzBzaEhmR3hVb3c1Q3lnd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJM01ESTFPVEF3V2hjTk1q
      TXdOekkzTURNd05EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFcGZpek9GSTZhWDdwRm9xd2VhYml6Q0ZGT2RI
      cHhIZUoKZGtKNERuQjdEcEpCQzFFU2ptcXk2UTJOK1Mxb2JHb2lYRUJWaVRncmVEYml5YSt5ZzYz
      djdxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTNHJTLzhuTmdxCmhOaVFjV1NRR2dUZzlWVm8xREFmQmdOVkhTTUVHREFXZ0JU
      OFpSMWZhU3IzeGQrRjJ4UDR0MTJsaGwxdGx6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xUWnVObXR5TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUtFeFhWS1l6Q2VFZDFLclAyZ2s2a2s0S2JIMjlicWpEcDU4YiszanZRUE9BaUFV
      R2Q0VHVvaEhNVlQ2CmE3bXdkZnJ2Szc0Tk5ZOW1wTTRqQzFXaDV2OG1vUT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVdZQUtIMlMrT2xZdE9vdm5kUEMyeXRKc3pXSXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056STNNREkxTVRFMldoY05NalV3
      TlRFMk1ESTFNVEUyV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCRExmY0lwbVB1MkVoOTNQYXp2VW9VaDZJSmcvK0pncUppTVpIMFVYcVFMaFlZalY4
      UEZ4CmNDelhyOFdwSkthMXZCTUU5NEZTeXdzbjFMNHcvakRycFVhalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlQ4WlIxZmFTcjN4
      ZCtGMnhQNHQxMmxobDF0bHpBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQlU4RVEvNWFnZ0RwRFRN
      MEFJRHRwWFMrM1FvU2lPMytSbncveE9wU1c3CktRSWhBTE9Ec2xLNVEyTVdMTXBxa1MrYU9SaEN5
      VDZIR2lkWkwxQjJhNll3eUV3OQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRp
      ZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaghIKDUNvbnNlbnN1c1R5cGUS8BES5REKCGV0Y2Ry
      YWZ0EtgRCsERChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijcazwgtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJREFqQ0NBcW1nQXdJQkFnSVVlS3FYaEU0bHdRbG05SVNmeFhvM2g2LzFj
      S1V3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dH
      UVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekkzTURJMU9UQXdX
      aGNOTWpNd056STNNRE13TkRBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNO
      VEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURW
      UVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJp
      MXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRVXhiSUxsMkVNWXQ1dk1T
      NmZMT0RUdEs0cApadWVhWUJYSStrZ2hxVXMvTHVpUHVnSFo2VnR1T0hKalU1WVVHSkR2ekcrS3p4
      bkZ4YS8wcjJpcU1nTzFvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpR
      UVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0Ex
      VWREZ1FXQkJTYlM4MFhYVkxzc3ZpVTgxOUVzWStmRHZweApyVEFmQmdOVkhTTUVHREFXZ0JUOFpS
      MWZhU3IzeGQrRjJ4UDR0MTJsaGwxdGx6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRY
      QndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1H
      d0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3
      aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1W
      MElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJ
      Z0dUcGNHQVVhajFYS1FhRjIKR0FMdUZDVVNnUFNrODZTdEdnYUp4MGRZWCs4Q0lEcnJyQ0FyekFQ
      dHI2Y0c0RFdrSTNHbUthb2FzODBpMmlEcQoxdWdnWXdnaQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiLPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQWpDQ0FxbWdBd0lCQWdJVWVL
      cVhoRTRsd1FsbTlJU2Z4WG8zaDYvMWNLVXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      dwpIaGNOTWpJd056STNNREkxT1RBd1doY05Nak13TnpJM01ETXdOREF3V2pCeE1Rc3dDUVlEVlFR
      R0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkNBQVFVeGJJTGwyRU1ZdDV2TVM2ZkxPRFR0SzRwClp1ZWFZQlhJK2tnaHFVcy9MdWlQdWdI
      WjZWdHVPSEpqVTVZVUdKRHZ6RytLenhuRnhhLzByMmlxTWdPMW80SUIKTURDQ0FTd3dEZ1lEVlIw
      UEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpB
      TUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNiUzgwWFhWTHNzdmlVODE5RXNZK2ZEdnB4
      CnJUQWZCZ05WSFNNRUdEQVdnQlQ4WlIxZmFTcjN4ZCtGMnhQNHQxMmxobDF0bHpBL0JnTlZIUkVF
      T0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJs
      ZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWht
      TGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEps
      Y2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3
      Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnR1RwY0dBVWFqMVhLUWFGMgpHQUx1RkNVU2dQU2s4NlN0
      R2dhSngwZFlYKzhDSURycnJDQXJ6QVB0cjZjRzREV2tJM0dtS2FvYXM4MGkyaURxCjF1Z2dZd2dp
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucxoi
      CglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIY
      Eg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFkbWlucxLD
      LwoLQ29uc29ydGl1bXMSsy8S6C4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLOLhK7FwoPbWFudWZh
      Y3R1cmVyTVNQEqcXGq8VCgNNU1ASpxUSnBUSmRUKD21hbnVmYWN0dXJlck1TUBKGBi0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVWJ4M0pMZWI3R0RzRjlRSjRP
      eUlRZUVLdGpFRXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFa
      bUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05N
      akl3TnpJM01ESTFNekUzV2hjTk1qVXdOVEUyTURJMU16RTNXakJrTVFzd0NRWURWUVFHCkV3SkRT
      REVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJB
      b00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxX
      NWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkhVT1lzMEZDSlg4dkFBR1lB
      Y3ZKT3pMMmE3WDdWalRKY2I1Cm82RGpNTlFvZWY0cjEwM0xRUEZiRDhWV2Z4eVFRbEovT1ZucXRw
      QWZZbGpCMEVzZzI0V2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJTQUE1UFhJRUR6d3ZabAowYmJuNWVnUktsTUNwREFLQmdncWhr
      ak9QUVFEQWdOSkFEQkdBaUVBM3VEYlcrRUNseVBQUDFWdkp4UWptSDV6CnAzbk1YRjVFN2J5eDNx
      aTRuSXdDSVFEWkhGRU92c1ppZ0ZGdWpWK2h0VndPQ0V4TTZDSUcyeVRieHpwR1F3L1EKMmc9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlERURDQ0FyZWdBd0lCQWdJVUs2TU5EOWJtKzVZbENrSDlKb0ZlMlRUV1Foa3dDZ1lJS29aSXpq
      MEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJB
      TU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpJM01ETXdNREF3V2hjTk1q
      TXdOekkzTURNd05UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xq
      TTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJn
      TlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERC
      WkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpq
      MERBUWNEUWdBRWNXSGxYWFFUNDJWV1VCd1BzeDFWenkrMHBtcFVHRFVTUEQ4UFNrdFJwaDl3N2x4
      dUt2dEsKTDZlNlVlZTJ6THAwNmMxNTN0dSt5cW9SdGU5eVgvN3RGcU9DQVNJd2dnRWVNQTRHQTFV
      ZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUktzb2k5Nkty
      RklUakQycnpseFVHVFJaVTUxakFmCkJnTlZIU01FR0RBV2dCU0FBNVBYSUVEend2WmwwYmJuNWVn
      UktsTUNwREFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMV1puWWpW
      ck1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhK
      MVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFda
      aFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNS
      MWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05I
      QURCRQpBaUJLamZsY0FtdUVUSVYxbFV4N1Y0Y0NTajIxTXhVTHYzR0J0c3VJdVFVL1FBSWdLSmdo
      YmN0TlZBdmxnNWczCmliSzFMYW8vRUhqaDY3dzg3S3c0U2R4UDBvQT0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoYGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNEVENDQWJLZ0F3SUJBZ0lVYngzSkxlYjdHRHNGOVFKNE95SVFlRUt0akVFd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekkzTURJMU16RTNXaGNO
      TWpVd05URTJNREkxTXpFM1dqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5
      YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEps
      Y2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5
      QWdFR0NDcUdTTTQ5QXdFSEEwSUFCSFVPWXMwRkNKWDh2QUFHWUFjdkpPekwyYTdYN1ZqVEpjYjUK
      bzZEak1OUW9lZjRyMTAzTFFQRmJEOFZXZnh5UVFsSi9PVm5xdHBBZllsakIwRXNnMjRXalFqQkFN
      QThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdC
      QlNBQTVQWElFRHp3dlpsCjBiYm41ZWdSS2xNQ3BEQUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUEz
      dURiVytFQ2x5UFBQMVZ2SnhRam1INXoKcDNuTVhGNUU3Ynl4M3FpNG5Jd0NJUURaSEZFT3ZzWmln
      RkZ1alYraHRWd09DRXhNNkNJRzJ5VGJ4enBHUXcvUQoyZz09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21h
      bnVmYWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21h
      bnVmYWN0dXJlck1TUBABGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQ
      ErcUEqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIr
      VENDQVo2Z0F3SUJBZ0lVVjF0c1JCeDFQSWY1WllsZXJxS2pxd09Ja3BNd0NnWUlLb1pJemowRUF3
      SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allY
      SnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNamN3TWpVMU1UbGFGdzB5TlRBMU1UWXdNalUxTVRsYU1G
      b3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJr
      eHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNt
      bGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUkduYkFsL0xwdnln
      T0hBRUFGamFnQkJnWUMwaXYyQklVeG1vKzZoeXpuVkF1Qk1yNHVYeE1SUk5KclJqS2cKaVFYanlC
      SjluOGhySFQ5L1A1bXhXLzBkbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdF
      Qgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVwNFFhK2hQa0JIbkk4NTlhdkFGNWpmVUs3UEF3Q2dZ
      SUtvWkl6ajBFCkF3SURTUUF3UmdJaEFMc24yZFJ3VExNdnBKMHliamlyZWE5VHg5YkxHVXpJeTh2
      a3h0QUs3ekhxQWlFQTlUYUQKNGpIS1E2eGsyTk85T2lORmRTNWdOUFJnL0J2eURFczVrSHd0cnRr
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlDN1RDQ0FwU2dBd0lCQWdJVUUwYTY0cHpsWUNlYzJpeHptSjJGSWU1Q1Jpd3dDZ1lJS29a
      SXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1
      allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakEzTWpjd016QXlNREJhRncweU16QTNNamN3TXpB
      M01EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5
      TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0
      R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRZTlGSlFxN1N5M1RZTEhUaUpaMnZi
      CnJvWWoraG5VU013RlJLWlFCUnFjQXBPNXBDM2VwWXdGRlFXNkZRQnB3aE1oVzdlK0NSRExBd1lK
      VForUy8vZDcKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FD
      TUFBd0hRWURWUjBPQkJZRQpGRnFQckQ1WCtjWUdUeVpld2M1U3I1SUhNRUFsTUI4R0ExVWRJd1FZ
      TUJhQUZLZUVHdm9UNUFSNXlQT2ZXcndCCmVZMzFDdXp3TUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2
      YjJ4ekxUWmtOR00yWmpjMlpHWXRPVzF5WkRZd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5
      Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1
      UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9p
      UVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkK
      S29aSXpqMEVBd0lEUndBd1JBSWdSUFRpSTZhNTg4dXZ3cGF1Q2NyajJKVyswb1FoQXVxSlhqaWlG
      S29acW5JQwpJRU1sOWt6b0lzZWNvanR2SWJhZTZaRHdYQnNuS0NWQW9zUzUxRGVsQ21PVwotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVWMXRzUkJ4MVBJZjVaWWxlcnFLanF3T0lr
      cE13Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dG
      UVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01qY3dNalUxTVRsYUZ3MHlO
      VEExTVRZd01qVTFNVGxhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWti
      MjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdB
      MVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkMKQUFSR25iQWwvTHB2eWdPSEFFQUZqYWdCQmdZQzBpdjJCSVV4bW8rNmh5em5WQXVCTXI0dVh4
      TVJSTkpyUmpLZwppUVhqeUJKOW44aHJIVDkvUDVteFcvMGRvMEl3UURBUEJnTlZIUk1CQWY4RUJU
      QURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXA0UWEraFBrQkhuSTg1
      OWF2QUY1amZVSzdQQXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUxzbjJkUndUTE12cEoweWJq
      aXJlYTlUeDliTEdVekl5OHZreHRBSzd6SHFBaUVBOVRhRAo0akhLUTZ4azJOTzlPaU5GZFM1Z05Q
      UmcvQnZ5REVzNWtId3RydGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoL
      RW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoH
      UmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0
      ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIq
      EiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hh
      bm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdv
      cml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhAS
      Bgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHlj
      aGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYS
      DAoKCgZWMV80XzMSABoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoH
      UmVhZGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
