apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIBr1FkqDgXvVHPtwKSL1RfTlw+q2WvImOWw09rYENC2XEqheCqVeCqJeCngKWggBEAEaBgiq
      sNyXBiIKc3lzY2hhbm5lbCpAZGQzNjQ4MTYxNDQyNDNjOTVkMjU3OGI4ZDgxM2IwZTJjMTk1ZTdk
      Zjg3YTYxNTQzNGVmMWZmM2VlOTg1ODQ0ORIaEhiS/TgsGFBrh4yFuh78iBqX+AZ6I1GOgjoSpV0K
      ol0Sn10SjysKB09yZGVyZXISgysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVSldxSmhIdFdCc3NlNWlwWGQ0bFZjM1Z1bklZd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RFek1ETXdNakUyV2hjTk1qVXdOakF5TURNd01qRTJX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJLNlNk
      YXV4bTdDZlhTaW4yK1o0dndpTVp2SUxlOHZQWitLa3pTN1JPMkZJR0tOWGJIVVIKU25aWWdiZE1C
      RUl5MU5pK3BXb2UzMjNIcTg1VitWdEhwNlNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWp1VGdFd0padkg3RmpFWTZUa2YwaXdB
      NnFJREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTFxUjVtYk9KRyt5WVdmc0IwY2RXQUEvV2w3
      V2ZSOFoyTjVBQ1hIUG8KMzdrQ0lCcm5PMTA5dksremh4ZWZWdkE4Q0srcTEwSFREN3FMNzFxTklJ
      UjJhT09rCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVUXBjdjhJc3dqMHFOZ0FmNHBOc0tKQmtrWU9zd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RFek1ETXhNREF3V2hjTk1q
      TXdPREV6TURNeE5UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZ0wxN1F1OFJPeVJrYTZYa2FDOTcwSDFUbTQy
      Vk55ckUKOFg2Q0YyQnM2YzdUeXZkclBqbU5oVTBDSVJ2Ym9PVUZKRG1yQjhTSmpVcTRWOEk0TkpB
      T2dLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTR2gwRTJvc1RRCmk0bFhrb04yVk1TUGJrckVxekFmQmdOVkhTTUVHREFXZ0JR
      anVUZ0V3Slp2SDdGakVZNlRrZjBpd0E2cUlEQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xUVnRZbTEwTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQU0yR0NUODZoZFdhRVNsaXJNOG9PR0JuRGZ2K1MxV2lJQUN2SXhCR095Z0dBaUJC
      REhHeGVaazdUUzlDCmpFY1RqVW5lUm5LVW5kOTloaWFyRmV6ZERxeEh6QT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVUpXcUpoSHRXQnNzZTVpcFhkNGxWYzNWdW5JWXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09ERXpNRE13TWpFMldoY05NalV3
      TmpBeU1ETXdNakUyV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCSzZTZGF1eG03Q2ZYU2luMitaNHZ3aU1adklMZTh2UForS2t6UzdSTzJGSUdLTlhi
      SFVSClNuWllnYmRNQkVJeTFOaStwV29lMzIzSHE4NVYrVnRIcDZTalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlFqdVRnRXdKWnZI
      N0ZqRVk2VGtmMGl3QTZxSURBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUExcVI1bWJPSkcreVlX
      ZnNCMGNkV0FBL1dsN1dmUjhaMk41QUNYSFBvCjM3a0NJQnJuTzEwOXZLK3poeGVmVnZBOENLK3Ex
      MEhURDdxTDcxcU5JSVIyYU9PawotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRp
      ZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaghIKDUNvbnNlbnN1c1R5cGUS8BES5REKCGV0Y2Ry
      YWZ0EtgRCsERChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijcazwgtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJREFqQ0NBcW1nQXdJQkFnSVVYRVVWZUNxK01oMmNVb1Z3S0FQeHdsQzNB
      clF3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dH
      UVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdPREV6TURNeE1EQXdX
      aGNOTWpNd09ERXpNRE14TlRBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNO
      VEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURW
      UVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJp
      MXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSSmoyb0Q5ZzNhaWhMeXYv
      RFNrM3dFcTk1aQpMNjNjZFZBdHd6T3Z4V1FQL0JhZHlxVllCNmVMbUoyY0IyS253ZGZYWS9iWC9X
      Qzlzay8zYUxFRDFlcjNvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpR
      UVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0Ex
      VWREZ1FXQkJTOXNmVTJHTmF2QThvaWZqYWp5TmptMm9LbwpTakFmQmdOVkhTTUVHREFXZ0JRanVU
      Z0V3Slp2SDdGakVZNlRrZjBpd0E2cUlEQS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRY
      QndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1H
      d0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3
      aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1W
      MElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJ
      Z0xheEl5MVJody9saC9zMzYKaVd2aGhxTTBESm9zZE91Qyt1WkRMUkJVcVVvQ0lFWGs1MUxycG52
      SVlOU0NQZ3dWNmlocDJwSFQrUW9BU0lEQgowYUlYZS92dgotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiLPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQWpDQ0FxbWdBd0lCQWdJVVhF
      VVZlQ3ErTWgyY1VvVndLQVB4d2xDM0FyUXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      dwpIaGNOTWpJd09ERXpNRE14TURBd1doY05Nak13T0RFek1ETXhOVEF3V2pCeE1Rc3dDUVlEVlFR
      R0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkNBQVJKajJvRDlnM2FpaEx5di9EU2szd0VxOTVpCkw2M2NkVkF0d3pPdnhXUVAvQmFkeXFW
      WUI2ZUxtSjJjQjJLbndkZlhZL2JYL1dDOXNrLzNhTEVEMWVyM280SUIKTURDQ0FTd3dEZ1lEVlIw
      UEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpB
      TUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlM5c2ZVMkdOYXZBOG9pZmphanlOam0yb0tv
      ClNqQWZCZ05WSFNNRUdEQVdnQlFqdVRnRXdKWnZIN0ZqRVk2VGtmMGl3QTZxSURBL0JnTlZIUkVF
      T0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJs
      ZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWht
      TGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEps
      Y2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3
      Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnTGF4SXkxUmh3L2xoL3MzNgppV3ZoaHFNMERKb3NkT3VD
      K3VaRExSQlVxVW9DSUVYazUxTHJwbnZJWU5TQ1Bnd1Y2aWhwMnBIVCtRb0FTSURCCjBhSVhlL3Z2
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucxoi
      CglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIY
      Eg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFkbWlucxLH
      LwoLQ29uc29ydGl1bXMSty8S7C4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLSLhK7FwoPbWFudWZh
      Y3R1cmVyTVNQEqcXGq8VCgNNU1ASpxUSnBUSmRUKD21hbnVmYWN0dXJlck1TUBKGBi0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVUU3ODNyRENjR0M1YjdCM0kr
      NktZcHNWSTBhTXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFa
      bUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05N
      akl3T0RFek1ETXdOREU0V2hjTk1qVXdOakF5TURNd05ERTRXakJrTVFzd0NRWURWUVFHCkV3SkRT
      REVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJB
      b00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxX
      NWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkQ1SXFFRTZJUXlrcnpFYTk3
      dVF3YithNk1CRnVCUy90WWZ5CnZvaXRQMnc4OUp3VEptRTYvbG44aU0ydTBPMldtVFdjcy9QSHRX
      R0J5OWZEY3ZDV0o2T2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJSSmRtNVpORU00bUh1QgpoekpwK29EcGh3NG9hekFLQmdncWhr
      ak9QUVFEQWdOSkFEQkdBaUVBN3dGblp3cDRFQUxYcTR6UmhrY2FlMElzCldGRUg2aVRhQ0NEem9T
      YTVCbUFDSVFDNWcvRjJRdzZLdmY5OUt6TWpkT0RnN01rcmpNYm1nRm1UdEphRUF1VUwKclE9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlERVRDQ0FyZWdBd0lCQWdJVUtRQ2pOWVJpSHl3enMwMGt5VHBtOWNETlUwY3dDZ1lJS29aSXpq
      MEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0Ex
      VUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJB
      TU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3T0RFek1ETXhNVEF3V2hjTk1q
      TXdPREV6TURNeE5qQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xq
      TTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJn
      TlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERC
      WkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpq
      MERBUWNEUWdBRUxXVk1lc3hFWHZqWmtNRXg1SnJKellOU0VINWp3aU5tNU5JRWZtd2NKVU9JV1lh
      SENGQkQKSXJOTURTTHcrdVJZQ1U0NlJGdFZIY1dmVUFKcFV5dGprNk9DQVNJd2dnRWVNQTRHQTFV
      ZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU1hWa2xVQTRM
      ZVRYUFc5eUZWaVdqcFEwVGV5ekFmCkJnTlZIU01FR0RBV2dCUkpkbTVaTkVNNG1IdUJoekpwK29E
      cGh3NG9hekFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMWFp4WW5k
      eU1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhK
      MVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFda
      aFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNS
      MWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBOWlGUk1WMW9xUk9LSkFid0NXaGpEMzZEQzVETkVPWnJWcXpLejhUUDJ6c0NJQ3JH
      b3B2RXZkSDFCSWoyCks5VTNyTW9hLzg4bTlDSEVZekdaRjE3cGI1NU4KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoYGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNEVENDQWJLZ0F3SUJBZ0lVRTc4M3JEQ2NHQzViN0IzSSs2S1lwc1ZJMGFNd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPREV6TURNd05ERTRXaGNO
      TWpVd05qQXlNRE13TkRFNFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5
      YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEps
      Y2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5
      QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRDVJcUVFNklReWtyekVhOTd1UXdiK2E2TUJGdUJTL3RZZnkK
      dm9pdFAydzg5SndUSm1FNi9sbjhpTTJ1ME8yV21UV2NzL1BIdFdHQnk5ZkRjdkNXSjZPalFqQkFN
      QThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdC
      QlJKZG01Wk5FTTRtSHVCCmh6SnArb0RwaHc0b2F6QUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUE3
      d0ZuWndwNEVBTFhxNHpSaGtjYWUwSXMKV0ZFSDZpVGFDQ0R6b1NhNUJtQUNJUUM1Zy9GMlF3Nkt2
      Zjk5S3pNamRPRGc3TWtyak1ibWdGbVR0SmFFQXVVTApyUT09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21h
      bnVmYWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21h
      bnVmYWN0dXJlck1TUBABGgZBZG1pbnMqBkFkbWlucxK2FgoKY2Fycmllck1TUBKnFhrDFAoDTVNQ
      ErsUErAUEq0UCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIr
      RENDQVo2Z0F3SUJBZ0lVTGRVL2FPbVUwbzdFMHVpd0NOd01hSm9YR2xFd0NnWUlLb1pJemowRUF3
      SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allY
      SnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTRNVE13TXpBMk1qQmFGdzB5TlRBMk1ESXdNekEyTWpCYU1G
      b3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJr
      eHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNt
      bGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU1phb0dKZjFiQVQy
      cS9PY2dqMjRVaXMzV0VvR0JCOVlrajlTY0VmTURJdGRqMFR1R2RLVFZzeW5LUmFobmEKTzlzc0g3
      UGV2TWlIMjIrSENYUlhWcWlHbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdF
      Qgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVJNjVkUVN4OGoyT3V2N2FOVEJQUkppSmRxa0V3Q2dZ
      SUtvWkl6ajBFCkF3SURTQUF3UlFJaEFPOGtHY0NudWRjYzU4ZU8rSHFyRm84Y1B0NHVsYzBnK0g2
      anFqZ0N5TmNhQWlBR0J0WlgKYlZoeFZQYzdYWmJMc3V2bjZSNTU0MmRmb2RWdUg2enB5QmtjNlE9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlDN2pDQ0FwU2dBd0lCQWdJVVhMS1ZkSklCWFFBUXRoUEh5U0ViWmREOFRtd3dDZ1lJS29a
      SXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1
      allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakE0TVRNd016RXpNREJhRncweU16QTRNVE13TXpF
      NE1EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5
      TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0
      R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUOFZleEpHYkoxSE5JWGw1em9waU8x
      CnVUTUFLcm1HNExuaUJqMGNubEl5blZYOURPenNma20rcmxaNW9BR040OElYS08xK0EvcnBCRW94
      N3lDVWZaUWgKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FD
      TUFBd0hRWURWUjBPQkJZRQpGSUp4OExvdTNUaTgzNVJPTUgxam9TOGJqdzcxTUI4R0ExVWRJd1FZ
      TUJhQUZDT3VYVUVzZkk5anJyKzJqVXdUCjBTWWlYYXBCTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2
      YjJ4ekxUWmtOR00yWmpjMlpHWXRObkpvYWpjd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5
      Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1
      UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9p
      UVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkK
      S29aSXpqMEVBd0lEU0FBd1JRSWhBUC9OdWg1b3dnYjYzZDhRcm5yeElwbGRvUHJGZngvZTFESnpk
      YkN3R01yQwpBaUF4MDNWYjZqbEhaczJwaGVUb3VKSnFpK05xOUx4djQwRXAvZy9XMmRubGRBPT0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVTGRVL2FPbVUwbzdFMHVpd0NOd01h
      Sm9YR2xFd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlN
      UmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTRNVE13TXpBMk1qQmFG
      dzB5TlRBMk1ESXdNekEyTWpCYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1i
      MjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApN
      QlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BR
      TUJCd05DCkFBU1phb0dKZjFiQVQycS9PY2dqMjRVaXMzV0VvR0JCOVlrajlTY0VmTURJdGRqMFR1
      R2RLVFZzeW5LUmFobmEKTzlzc0g3UGV2TWlIMjIrSENYUlhWcWlHbzBJd1FEQVBCZ05WSFJNQkFm
      OEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVJNjVkUVN4OGoy
      T3V2N2FOVEJQUkppSmRxa0V3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFPOGtHY0NudWRjYzU4
      ZU8rSHFyRm84Y1B0NHVsYzBnK0g2anFqZ0N5TmNhQWlBR0J0WlgKYlZoeFZQYzdYWmJMc3V2bjZS
      NTU0MmRmb2RWdUg2enB5QmtjNlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoH
      V3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1p
      bnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNl
      bWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAK
      FUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5n
      QWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVy
      ZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3Vw
      cGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGll
      cxIWEgwKCgoGVjFfNF8zEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
