apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIOP7+fSYHs4BiH9WWAy7dZyAt5Lo77E2TY+8XfP89PHjEqZeCqNeCqBeCngKWggBEAEaBgjH
      p/mWBiIKc3lzY2hhbm5lbCpAYmRkYjNhY2Y4MjU5MTI1OWQ2ZWE0NGVlODI0YmQyMjg4OTliM2Zh
      MDM0MGE2OWUyYTg4MmJkMzAzOGZhNDQ3ZBIaEhg/uTWV24pppYArh5SzGc6c2VkNxxsS/2ISo10K
      oF0SnV0SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVS2ErS0RjdGJnRGxQaU1UVDcvQ3VyTk5DV2Iwd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJMU1EZ3hNREEzV2hjTk1qVXdOVEUwTURneE1EQTNX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJHQTc4
      WFQ5TU1NNDlaN0V5aG13bWJWRVROam10aHl6M0ZRSWNOZndtWmcyZGFDSm1WUXQKZENrNGFQSmNJ
      UkhobjNDeDF5Z1FBUXRnVFhlZTdvZzl0Q2FqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1NYL29mVWVTMlRON1RHaTlTT25DUWRy
      SXd6REFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQWx6ZzdlTlUvbWhUQ21QZGlVaGJZL1hnSGxI
      NFFmNmoxeStzR1loN20KZEc0Q0lBNEpaTFRQT0R2WkNSclJteCtra0J2WVE3NUQzaDdWMFVvanpU
      MFRrbmJ3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVWFAwYVVLVVNsMWl4N2tRS0pnZGsvWHVxNzN3d0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJMU1EZ3hOekF3V2hjTk1q
      TXdOekkxTURneU1qQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFUjEwSlhzdDZPNVBoK1BJK25hMCs3NjRYNnEr
      dldIQloKcXVxZzk5SC9CREsvTTdqYlhDSlZreEdsdzZySTljcVJmZ2NxVTBsQWZ0RVJYS1l2RE9l
      N2RLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUaGptc2E5NW0zCmJUV3psNHVUOXRGZ0JIOWVmVEFmQmdOVkhTTUVHREFXZ0JT
      U1gvb2ZVZVMyVE43VEdpOVNPbkNRZHJJd3pEQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xXbzVhMnA2TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQVA3VjI4d0t5aStwN2xFbzZENTdsTmdvZnhDdW5Ja0dlVUJNamIvVDRRWGpBaUFl
      STNzQlA4T09WR2pPCk1iazdaZFRCSVR3TDlSdTV4MjRhbnZ0Qy9FZmJDQT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVUthK0tEY3RiZ0RsUGlNVFQ3L0N1ck5OQ1diMHdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056STFNRGd4TURBM1doY05NalV3
      TlRFME1EZ3hNREEzV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCR0E3OFhUOU1NTTQ5WjdFeWhtd21iVkVUTmptdGh5ejNGUUljTmZ3bVpnMmRhQ0pt
      VlF0CmRDazRhUEpjSVJIaG4zQ3gxeWdRQVF0Z1RYZWU3b2c5dENhalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNTWC9vZlVlUzJU
      TjdUR2k5U09uQ1Fkckl3ekRBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFsemc3ZU5VL21oVENt
      UGRpVWhiWS9YZ0hsSDRRZjZqMXkrc0dZaDdtCmRHNENJQTRKWkxUUE9EdlpDUnJSbXgra2tCdllR
      NzVEM2g3VjBVb2p6VDBUa25idwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRp
      ZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaihIKDUNvbnNlbnN1c1R5cGUS+BES7REKCGV0Y2Ry
      YWZ0EuARCskRChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijca0wgtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVEbFBCWnVWamdFNXFFc3dqRnNJemhDZ0ll
      eFl3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dH
      UVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekkxTURneE56QXdX
      aGNOTWpNd056STFNRGd5TWpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNO
      VEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURW
      UVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJp
      MXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUNkJNcXFpbHA2Mm14Q1kv
      d2VUa3N6emo0TApOWGFWOVo1N1ZwdVoybEcwU1FYSGw3NDJBRnJvZEN3NUt0YVF4cktEK015WEdk
      dG5maXpRQlJyQ1FDMEFvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpR
      UVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0Ex
      VWREZ1FXQkJUcml1U3ZtZHlJVlRLUnlLam9FZndEbDJHQgp3akFmQmdOVkhTTUVHREFXZ0JTU1gv
      b2ZVZVMyVE43VEdpOVNPbkNRZHJJd3pEQS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRY
      QndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1H
      d0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3
      aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1W
      MElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJ
      aEFNSWJNOTlZNUJENG10SUMKTnp6SityYWFrdExWaFFMemxVMklZNm00ZnoyL0FpQVpOeXF4V3ZN
      NU15aWU4MEUrWncxYjZuOFVGaXR5NnE1bAp2bGxZUDNkM3NBPT0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQoi0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFn
      SVVEbFBCWnVWamdFNXFFc3dqRnNJemhDZ0lleFl3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkx
      dVpYUXcKSGhjTk1qSXdOekkxTURneE56QXdXaGNOTWpNd056STFNRGd5TWpBd1dqQnhNUXN3Q1FZ
      RFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZ
      RFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXho
      dmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtq
      T1BRTUJCd05DQUFUNkJNcXFpbHA2Mm14Q1kvd2VUa3N6emo0TApOWGFWOVo1N1ZwdVoybEcwU1FY
      SGw3NDJBRnJvZEN3NUt0YVF4cktEK015WEdkdG5maXpRQlJyQ1FDMEFvNElCCk1EQ0NBU3d3RGdZ
      RFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFj
      REFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUcml1U3ZtZHlJVlRLUnlLam9FZndE
      bDJHQgp3akFmQmdOVkhTTUVHREFXZ0JTU1gvb2ZVZVMyVE43VEdpOVNPbkNRZHJJd3pEQS9CZ05W
      SFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4
      TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3
      SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0pr
      WlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElp
      Zlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFNSWJNOTlZNUJENG10SUMKTnp6SityYWFrdExW
      aFFMemxVMklZNm00ZnoyL0FpQVpOeXF4V3ZNNU15aWU4MEUrWncxYjZuOFVGaXR5NnE1bAp2bGxZ
      UDNkM3NBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICAChoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoG
      QWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoG
      QWRtaW5zEr0vCgtDb25zb3J0aXVtcxKtLxLiLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsguErEX
      Cg9tYW51ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEG
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNDekNDQWJLZ0F3SUJBZ0lVVVdzMnR1N0J1
      R0c5QmZrcjRoeTZuOU1qNzM4d0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hE
      ekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtE
      QXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVa
      WFF3SGhjTk1qSXdOekkxTURneE1qQTRXaGNOTWpVd05URTBNRGd4TWpBNFdqQmtNUXN3Q1FZRFZR
      UUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZU
      QVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkz
      UjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTk9MVGYvNEZs
      bXBLYzBmenJ0dlBjMU0xb0hrODIrSW5yeDcKQzV6cFF3RGhMdzFqcUpSSEVHV3hvS3doNE5hWHNo
      dUhpcUpPWHlLUDE5a1FLSFFGNTVLalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZS
      MFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlFjTzdSckNtektDbkxFCi9tVnhqRmVxYzFKcUNU
      QUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQXNrTFB5THFyYTMxQ015ZEh6NkVJWHowV0kKenFPcW0z
      M1lPZDRpYkJvSzhnSWdVK1Z0NDlMV0JNVGlSUkg4WGl0aWUzcDRvVFQvM1lrUEVrNnNQSHR4dEpN
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlERURDQ0FyZWdBd0lCQWdJVWZzVFhHT3MvMWNoVXhxOWN6T3RoNlRDaGcwa3dDZ1lJS29a
      SXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdO
      VkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpJMU1EZ3hPVEF3V2hj
      Tk1qTXdOekkxTURneU5EQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRR
      M0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpB
      TUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFR
      RERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      CnpqMERBUWNEUWdBRVF2dmh4dHp4cEF2T3cyQU1sdDBEY2ZpSDJLUlZwbWdtS2pOZkhTQUgxS3JZ
      Wk0zSDBrS3UKblVsNkI0NG1nY2dvY0FWTytONEVhVzdlbnZmVU1ZbFZhS09DQVNJd2dnRWVNQTRH
      QTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVG92MnBI
      YXJJRjNGR1hYNTNCVFpldy83K1EyREFmCkJnTlZIU01FR0RBV2dCUWNPN1JyQ216S0NuTEUvbVZ4
      akZlcWMxSnFDVEFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMWEUz
      ZWpabk1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9p
      ZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1
      ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgK
      WTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURB
      Z05IQURCRQpBaUJMWndmQkF0UkdncWNZRW9rWnNIeXpaSmZiVDNMS1RjQWlyVThUblM3TTJ3SWdH
      SkFPMTZTOHdCMmtwa1JpCkJxUSsxOEFJd0xTbGE4ck52bk5VTnlQTXpMVT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUNDekNDQWJLZ0F3SUJBZ0lVVVdzMnR1N0J1R0c5QmZrcjRoeTZuOU1qNzM4d0NnWUlL
      b1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBN
      QTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFC
      Z05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekkxTURneE1qQTRX
      aGNOTWpVd05URTBNRGd4TWpBNFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dX
      blZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBk
      WEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdT
      TTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTk9MVGYvNEZsbXBLYzBmenJ0dlBjMU0xb0hrODIrSW5y
      eDcKQzV6cFF3RGhMdzFqcUpSSEVHV3hvS3doNE5hWHNodUhpcUpPWHlLUDE5a1FLSFFGNTVLalFq
      QkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERn
      UVdCQlFjTzdSckNtektDbkxFCi9tVnhqRmVxYzFKcUNUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFp
      QXNrTFB5THFyYTMxQ015ZEh6NkVJWHowV0kKenFPcW0zM1lPZDRpYkJvSzhnSWdVK1Z0NDlMV0JN
      VGlSUkg4WGl0aWUzcDRvVFQvM1lrUEVrNnNQSHR4dEpNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVy
      ZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21h
      bnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSthYKCmNhcnJpZXJNU1ASpxYawxQKA01TUBK7
      FBKwFBKtFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RD
      Q0FaNmdBd0lCQWdJVVh3a1pYcGw0V3ZENWMxWEtTTU9nWlpCQ25wMHdDZ1lJS29aSXpqMEVBd0l3
      CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5
      YVdWeUxXNWxkREFlRncweQpNakEzTWpVd09ERTBNRGhhRncweU5UQTFNVFF3T0RFME1EaGFNRm94
      Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2
      Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxs
      Y2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVE4aTk1YS9YbWZqYk05
      VTNjRVMwVWZYTTdBK0U3V2Ixb0JzOHRLbHNFN0NIaWRmUXI5UTNZTUJCSldOUVJkCnJEdXdNUkJP
      c1VTQXZaaHp1YmdxMnVWcW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIK
      L3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVdUVXS0NVbmh3UVlKRFp1dnpGdURJM3g1eHVvd0NnWUlL
      b1pJemowRQpBd0lEU0FBd1JRSWhBSVdnWW43Z2FDUVNSbC9hYTlrRGZrL3k3aFdyazM4d0ZKOGJD
      M3JDcTVDcUFpQjZmR2VPCkRZc1dPdHBlQkY2YWRoSStUL1ZOK1lpWStQNml4OTJHVXBBdDZBPT0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQzdqQ0NBcFNnQXdJQkFnSVVYcWExWUl4NEFvbmxzcnlPUitEZFF3U2xXSFV3Q2dZSUtvWkl6
      ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZ
      UzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01qVXdPREl4TURCYUZ3MHlNekEzTWpVd09ESTJN
      REJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1i
      MjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdB
      MVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVDNvVjdTd2wxR0J3bkFKWkpSTERvVgpx
      VmMwNXZ2bU1BaytPRDIyQnRxUEt2VnpaMFB6NzR6MjgzeVYra1htT1RjSndac29hQlpZK0I1amNO
      YWhUVDNrCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01B
      QXdIUVlEVlIwT0JCWUUKRko3bDdWL2hJVjVZUWd0UHoxOGhsM2NQWkEveU1COEdBMVVkSXdRWU1C
      YUFGTGhGaWdsSjRjRUdDUTJicjh4YgpneU44ZWNicU1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIy
      eHpMVFprTkdNMlpqYzJaR1l0T1RWMlluY3dnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5
      STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFX
      Wm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFX
      UnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktv
      Wkl6ajBFQXdJRFNBQXdSUUloQUswSGtwcE9rMDN6bmdabzk2QXJIL1BiMy9Ea01wS1lSTnBhaGxz
      L2VqeEsKQWlCSjI0ZTNENlVPd1Y5QnRDMlBqNHhpS2VXZ1lqcFA3eHhnbkJuZ21qaHcrZz09Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVh3a1pYcGw0V3ZENWMxWEtTTU9nWlpC
      Q25wMHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJj
      d0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakEzTWpVd09ERTBNRGhhRncw
      eU5UQTFNVFF3T0RFME1EaGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1
      a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJV
      R0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1C
      QndOQwpBQVE4aTk1YS9YbWZqYk05VTNjRVMwVWZYTTdBK0U3V2Ixb0JzOHRLbHNFN0NIaWRmUXI5
      UTNZTUJCSldOUVJkCnJEdXdNUkJPc1VTQXZaaHp1YmdxMnVWcW8wSXdRREFQQmdOVkhSTUJBZjhF
      QlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVdUVXS0NVbmh3UVlK
      RFp1dnpGdURJM3g1eHVvd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBSVdnWW43Z2FDUVNSbC9h
      YTlrRGZrL3k3aFdyazM4d0ZKOGJDM3JDcTVDcUFpQjZmR2VPCkRZc1dPdHBlQkY2YWRoSStUL1ZO
      K1lpWStQNml4OTJHVXBBdDZBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI3
      CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIz
      CgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dy
      aXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5z
      EioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMqBkFkbWlucxpAChVD
      aGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0Fk
      bWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaTgoQT3JkZXJlckFk
      ZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMaJgoQSGFz
      aGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1
      Y3R1cmUSEBIGCP////8PGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
