apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIJ6VmfOvDrmo4o5IT9heTULHhM0jo7Jiu28jsWMNj9KzEqJeCp9eCpxeCngKWggBEAEaBgjz
      oJuWBiIKc3lzY2hhbm5lbCpAZmM4ZGUzMzUyMGY5N2NiMzljOWFiMzVlY2IyYTU3YTkwNTQ0YmFi
      ZDY3Zjg3YTJiMDYzZjc4NGQ4YjMzOGY0YhIaEhhI3O9v+CFdpJvTPadDthPaWuCqEXo+4R4Sn10K
      nF0SmV0SlysKB09yZGVyZXISiysS1hYKDnN1cHBseWNoYWluTVNQEsMWGs8UCgNNU1ASxxQSvBQS
      uRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVUVd3UWpQSXBpbVlra3h5MVdKMnVWd3FPeHFzd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpBM01USXdOelF5V2hjTk1qVXdOREkyTVRJd056UXlX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJIODUz
      L2pycEhIWHlVY3NSMHIwS0xQWlJPNURzUGNWOTNrc2Znc21abytWUFhiaEZBbVcKZlBGbE1aaUVi
      VC9oT3ArdExFOWRWZzdEM09YN2pRUGhTb1dqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUi9zM2hnQjlxWEVDd21HelVuTHg4eGFQ
      dllhREFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTZvLzk2ZmFoTTRJTzB5Slg4ZDVITHJTM1ox
      VFVOVzhPRzdaSzU1OEoKd1hNQ0lRQ3N1UDY2UC9Jd1lPd1A4ZkJQUm5XbG9OVENCaHQvN2RkSzhC
      STExMHBOekE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKmCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNGpDQ0FvaWdBd0lCQWdJVWMyZ2NjQWtadU5DM1FheXlQZXA2UFhRL2FJ
      Y3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056QTNNVEl4TlRBd1do
      Y05Nak13TnpBM01USXlNREF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUVsc2JXcDJ4SkpTWUE3UEZ3ZXczQ2Jv
      alFkT3hDdTQrCnB5V3VvSkNqNzF5bkdxQzRlclhoV1l4SVIrWkp1b1hTc1huend2YTRzYy9NTTJn
      MXdFcWxsYU9DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUjJYeFdkdG9kVApaSnloL0xRbjU2c0JmU0cxRFRBZkJnTlZIU01FR0RB
      V2dCUi9zM2hnQjlxWEVDd21HelVuTHg4eGFQdllhREFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDFOalkzWXpZM1ptWTNMV3R3Wm1kNk1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFNBQXcKUlFJaEFLWTFLd25CakdpTkFTM0hPMjcrdFNoYkp3eG1jQXFueTlPb2tQRG9BSkdr
      QWlBRE5CY29sSFV1aXR4ZwppR3h0bzR2V3MvWlRQbWxtaTlyVjJFWjF6ZmpXTlE9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK9QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQ0FUQ0NBYWFnQXdJQkFnSVVRV3dRalBJcGltWWtreHkxV0oydVZ3cU94cXN3
      Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlE
      VlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekEzTVRJd056UXlXaGNO
      TWpVd05ESTJNVEl3TnpReVdqQmVNUXN3Q1FZRFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1
      Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFa
      QmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcK
      U000OUF3RUhBMElBQkg4NTMvanJwSEhYeVVjc1IwcjBLTFBaUk81RHNQY1Y5M2tzZmdzbVpvK1ZQ
      WGJoRkFtVwpmUEZsTVppRWJUL2hPcCt0TEU5ZFZnN0QzT1g3alFQaFNvV2pRakJBTUE4R0ExVWRF
      d0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJSL3MzaGdC
      OXFYRUN3bUd6VW5MeDh4YVB2WWFEQUsKQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBNm8vOTZmYWhN
      NElPMHlKWDhkNUhMclMzWjFUVU5XOE9HN1pLNTU4Sgp3WE1DSVFDc3VQNjZQL0l3WU93UDhmQlBS
      bldsb05UQ0JodC83ZGRLOEJJMTEwcE56QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZB
      ZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoG
      QWRtaW5zIjsKC0VuZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5N
      U1AaBkFkbWlucyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5N
      U1AaBkFkbWlucyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5N
      U1AaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4K
      DEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZB
      ZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGoISCg1Db25zZW5z
      dXNUeXBlEvAREuURCghldGNkcmFmdBLYEQrBEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3
      Gs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVTXJBV0Z1
      RzBKQWhuT25XTHlPc3BXZVAwWGVjd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3Ckho
      Y05Nakl3TnpBM01USXhOVEF3V2hjTk1qTXdOekEzTVRJeU1EQXdXakJ4TVFzd0NRWURWUVFHRXdK
      SFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdk
      UGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndO
      Q0FBUk9TWFhnUGVuUnMzWnc4V1RjRWJCUktKdUcKY0ZxcTBXOXMwd0plOGJOVVZKbzY5aGRnS2Vn
      V1dRVGlJamI1UXh0Rm5OZ096VjJGVDg5NzdIamJuakhobzRJQgpNRENDQVN3d0RnWURWUjBQQVFI
      L0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdO
      VkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUmdpMENEOEJ0ZWVTbFBoSkU1d0doSWVzN1YKMlRB
      ZkJnTlZIU01FR0RBV2dCUi9zM2hnQjlxWEVDd21HelVuTHg4eGFQdllhREEvQmdOVkhSRUVPREEy
      Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZz
      YjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0Zt
      Wm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1
      YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJ
      S29aSXpqMEVBd0lEUndBd1JBSWdjQy9rK0o3bnhPOG00VzlZClRQZkQ1ZkNlNWxsbDVJb1FjcGxI
      dEtZcWJkZ0NJSDQ5dnNUNjA2eUdCSENHU2p4Y3JKZElBSEUrblZ5c3BYUXMKZXZQTlR6L0kKLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoizwgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      REFqQ0NBcW1nQXdJQkFnSVVNckFXRnVHMEpBaG5PbldMeU9zcFdlUDBYZWN3Q2dZSUtvWkl6ajBF
      QXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVF
      Qnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6
      ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekEzTVRJeE5UQXdXaGNOTWpNd056QTNNVEl5
      TURBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12
      VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5
      TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2Nx
      aGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFST1NYWGdQZW5SczNadzhXVGNFYkJSS0p1RwpjRnFx
      MFc5czB3SmU4Yk5VVkpvNjloZGdLZWdXV1FUaUlqYjVReHRGbk5nT3pWMkZUODk3N0hqYm5qSGhv
      NElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZC
      d01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSZ2kwQ0Q4
      QnRlZVNsUGhKRTV3R2hJZXM3VgoyVEFmQmdOVkhTTUVHREFXZ0JSL3MzaGdCOXFYRUN3bUd6VW5M
      eDh4YVB2WWFEQS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVa
      WFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JC
      R0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNi
      V1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHda
      U0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ2NDL2srSjdueE84bTRX
      OVkKVFBmRDVmQ2U1bGxsNUlvUWNwbEh0S1lxYmRnQ0lINDl2c1Q2MDZ5R0JIQ0dTanhjckpkSUFI
      RStuVnlzcFhRcwpldlBOVHovSQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAK
      GAEgBSiAgIAKGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoH
      V3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlu
      cxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoG
      QWRtaW5zErkvCgtDb25zb3J0aXVtcxKpLxLeLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsQuErEX
      Cg9tYW51ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEG
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVTE9xSW9NeVhr
      ZW91bjNteXZ2MU9nNkxsTi80d0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hE
      ekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtE
      QXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVa
      WFF3SGhjTk1qSXdOekEzTVRJd09UVXhXaGNOTWpVd05ESTJNVEl3T1RVeFdqQmtNUXN3Q1FZRFZR
      UUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZU
      QVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkz
      UjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCT25UZ2xsS3N5
      NTFEcnA1aGtNSkVVR0VhSnhscnFwMnB2RmQKQkM0a3AvckZmdkNwVXd0dzNYY2FoMEFlTEozV3dO
      VjZaREtHUll6a2ZKYUFtbmVLWGRXalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZS
      MFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRMbU8wbnIzS0o2WGcvCllxaVBHbUNjZ2phMFlq
      QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQmprWE9hVW5OUkYzUVJOR05Pb0cwNzV3d1AKN1g4SmZB
      Nm9kS2k4Z0IyR3lRSWhBTWZkNDZ1am95ZUZKREpvSVdCQmpPU2FhZ0ZlYnJiYjdBcTNTTVQ4VmRG
      VQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlERURDQ0FyZWdBd0lCQWdJVUJMS1Zudng0V2gvYlloTTRFaWZ2M1V0RjZDd3dDZ1lJS29a
      SXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdO
      VkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpBM01USXhOekF3V2hj
      Tk1qTXdOekEzTVRJeU1qQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRR
      M0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpB
      TUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFR
      RERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      CnpqMERBUWNEUWdBRXFtZTJYZFhQbHZRbkhLZE1RcUZ4ZDFvd3BNeWtVRFRVR2x1cVVqMVMyNXhP
      dzh6aXZWMTUKMzZWRTVncG00ZmJvRXd0Q2dERmN5K2NaZ1plcmpoeDZ1YU9DQVNJd2dnRWVNQTRH
      QTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU3lUYWZS
      QUt3Z3VFYWw1c0NNM04rZ1NWc2FkREFmCkJnTlZIU01FR0RBV2dCVExtTzBucjNLSjZYZy9ZcWlQ
      R21DY2dqYTBZakFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMV00x
      ZEdONE1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9p
      ZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1
      ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgK
      WTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURB
      Z05IQURCRQpBaUEzeGtLQ20rMmd4WVNaVHlvSXRydi81ZzllUnM0R29vdjlNTzF1cGNPQnB3SWdO
      Qm5TaXpQRWdWelRKNWQyClJYckVWcTJkbWRNajlQWUl6eTZ6ZW5pcUoxUT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVTE9xSW9NeVhrZW91bjNteXZ2MU9nNkxsTi80d0NnWUlL
      b1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBN
      QTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFC
      Z05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekEzTVRJd09UVXhX
      aGNOTWpVd05ESTJNVEl3T1RVeFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dX
      blZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBk
      WEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdT
      TTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCT25UZ2xsS3N5NTFEcnA1aGtNSkVVR0VhSnhscnFwMnB2
      RmQKQkM0a3AvckZmdkNwVXd0dzNYY2FoMEFlTEozV3dOVjZaREtHUll6a2ZKYUFtbmVLWGRXalFq
      QkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERn
      UVdCQlRMbU8wbnIzS0o2WGcvCllxaVBHbUNjZ2phMFlqQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFp
      QmprWE9hVW5OUkYzUVJOR05Pb0cwNzV3d1AKN1g4SmZBNm9kS2k4Z0IyR3lRSWhBTWZkNDZ1am95
      ZUZKREpvSVdCQmpPU2FhZ0ZlYnJiYjdBcTNTTVQ4VmRGVQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVy
      ZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21h
      bnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSshYKCmNhcnJpZXJNU1ASoxYavxQKA01TUBK3
      FBKsFBKpFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RD
      Q0FaNmdBd0lCQWdJVUZxMkVOTW5VdEpYeGxLZXlkUWZmSGpmdmlXSXdDZ1lJS29aSXpqMEVBd0l3
      CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5
      YVdWeUxXNWxkREFlRncweQpNakEzTURjeE1qRXhORFphRncweU5UQTBNall4TWpFeE5EWmFNRm94
      Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2
      Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxs
      Y2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRBZjRRbnJFSE5HSmVu
      a0dMaFBZWFEyNG1DZ0FxMHZKcTdBT0R5a2xkMWVxeWFudCtBZm9MQWVsVndiK1EyCkdMZS9xNDRC
      Tnp6Y2hhUmQwN3pza2pnMG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIK
      L3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVbXBJTGswY3RrYm5mL1E4TlpLSEliMHd0RG1rd0NnWUlL
      b1pJemowRQpBd0lEU1FBd1JnSWhBUC9tOXdvZmJoNk5OYWhYaCsrdnRpMUJ2MEJEdDQyaytQd0pk
      QVIwYWJNb0FpRUFsQTc3CmlhRmFtUEQ3L2RjVXo1MnhrMUo1TklYMU9kZm1XRnhxVVhiTzU0UT0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQzdUQ0NBcFNnQXdJQkFnSVVZSXY1bUd1NGdYZHZWVHVFNk1qYmtnMkpnbEV3Q2dZSUtvWkl6
      ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZ
      UzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01EY3hNakU1TURCYUZ3MHlNekEzTURjeE1qSTBN
      REJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1i
      MjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdB
      MVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU215dG1PTUIxOURKVmNlbFFWWTlocgps
      R0FYTFRaaDE3TEFOeUFzeWpGL05peUdZVFp6aHIyY0w5S1AvL3pGdUovVy9ybjE4MHJFMDQ4ZFY5
      OTNBdWhnCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01B
      QXdIUVlEVlIwT0JCWUUKRlBtRlF3eDNBM09tSkkya3dFUldEUGs4K0tFNk1COEdBMVVkSXdRWU1C
      YUFGSnFTQzVOSExaRzUzLzBQRFdTaAp5RzlNTFE1cE1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIy
      eHpMVFprTkdNMlpqYzJaR1l0ZHpsNE5Ea3dnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5
      STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFX
      Wm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFX
      UnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktv
      Wkl6ajBFQXdJRFJ3QXdSQUlnTmxYaEJlY2tVMEFwZ0lxS2pNcUw3RmVuMi84RnYvSWVGem14REdF
      UWdwZ0MKSUFRdmYrWmZDc2RxdWVCaW94Uzh2RFlZSlJKSGNoMEgzbENsYnQrWm5oOTYKLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUIrVENDQVo2Z0F3SUJBZ0lVRnEyRU5NblV0Slh4bEtleWRRZmZIamZ2aVdJ
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNRGN4TWpFeE5EWmFGdzB5TlRB
      ME1qWXhNakV4TkRaYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0
      eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFV
      RUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05D
      CkFBVEFmNFFuckVITkdKZW5rR0xoUFlYUTI0bUNnQXEwdkpxN0FPRHlrbGQxZXF5YW50K0Fmb0xB
      ZWxWd2IrUTIKR0xlL3E0NEJOenpjaGFSZDA3enNramcwbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFE
      QVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVtcElMazBjdGtibmYvUThO
      WktISWIwd3REbWt3Q2dZSUtvWkl6ajBFCkF3SURTUUF3UmdJaEFQL205d29mYmg2Tk5haFhoKyt2
      dGkxQnYwQkR0NDJrK1B3SmRBUjBhYk1vQWlFQWxBNzcKaWFGYW1QRDcvZGNVejUyeGsxSjVOSVgx
      T2RmbVdGeHFVWGJPNTRRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjMKB1Jl
      YWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIg
      CAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIo
      Eh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5u
      ZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3Jp
      dGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI
      /////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwK
      CgoGVjFfNF8zEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
