apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaINx6UC9mjoK3oxrQIknVi8yJZ4t1q3DTWlWaijoziETuEo5eCoteCoheCngKWggBEAEaBgj1
      lK+ZBiIKc3lzY2hhbm5lbCpAZTJjM2MwYmE5ZTdiNjg3ZjZmYWU1NTMyM2FiOGY4MzRhYjg2ZGU5
      NDc4ZmUyZDNiNjZkMmE1MjQzYTZjZWQzMRIaEhiRJmcyRary2yY9VOeASFTtDksESHKC0HYSi10K
      iF0ShV0SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVSVJnMWl4b2lmczAwQTljOEtqaDBYUFoxd2dFd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RJeU1ESXlNRFEwV2hjTk1qVXdOekV5TURJeU1EUTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJEV0x4
      ek9KN1RFTnB6VXlRQ01lYWR4b0dQSHJiUzBDNExvbHg0QzdHMzh6bUthUWsvOUUKRnBST3pkUGpJ
      R2YwZmNoaU82L3VLSTdwWitqVDRoOTRLQjJqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUVZYelZVS0psWUFVdkZIci9kRFFsa3hZ
      UUR5ekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCWjNsclhXS0R1Q092VDd4VWY3RUc4WG5Qd3pS
      UHNVTVhiUEllWHFvNk0KRFFJaEFNbFRPczNBU2ptc3lGYjlPSjdPK283RGJESjQrMG0rWjBSTEtu
      ZDFMNjBQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVVC9HUFdJckh5WENMcEs1SVp0Z2tWemFEbFprd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RJeU1ESXlPREF3V2hjTk1q
      TXdPVEl5TURJek16QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFRzNxTFBpWEFmUk9Ld1BrSVVzUlM0d1dhUGlw
      TVcrbDUKWW5Idy9hN0JtQnQ4RkpYZVk1VmZLejFFZjh2dmk1Zm5CRytDbENCSWVqc0t0d1hZY3Ry
      NzlLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRcTN3UlRkNHplCjFqcnJHRzRnVXkrSkxQU0dyakFmQmdOVkhTTUVHREFXZ0JR
      Vlh6VlVLSmxZQVV2RkhyL2REUWxreFlRRHl6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xUVnpjVGx1TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnSTNlVjhnSWlEVmtBYXN5SE4rLzRxQXZxQ1dSL1ZidWtraitxWHVtczEwa0NJQWU2
      eS9Udkx6T0FNcm1nCjRpZ3c3YmFZTmtPUHVkTThPWlVzWjdBMG9GQnYKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVSVJnMWl4b2lmczAwQTljOEtqaDBYUFoxd2dFd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RJeU1ESXlNRFEwV2hjTk1qVXdOekV5
      TURJeU1EUTBXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJEV0x4ek9KN1RFTnB6VXlRQ01lYWR4b0dQSHJiUzBDNExvbHg0QzdHMzh6bUthUWsvOUUK
      RnBST3pkUGpJR2YwZmNoaU82L3VLSTdwWitqVDRoOTRLQjJqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUVZYelZVS0psWUFVdkZI
      ci9kRFFsa3hZUUR5ekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCWjNsclhXS0R1Q092VDd4VWY3
      RUc4WG5Qd3pSUHNVTVhiUEllWHFvNk0KRFFJaEFNbFRPczNBU2ptc3lGYjlPSjdPK283RGJESjQr
      MG0rWjBSTEtuZDFMNjBQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGoISCg1Db25zZW5zdXNUeXBlEvAREuURCghldGNkcmFmdBLYEQrBEQoYb3JkZXJlcjEu
      c3VwcGx5Y2hhaW4tbmV0EIo3Gs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakND
      QXFtZ0F3SUJBZ0lVYmhOckl0d1BJQVZOdmV4RzJPUzU3MFNWTDF3d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RJeU1ESXlPREF3V2hjTk1qTXdPVEl5TURJek16QXdX
      akJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVa
      Rzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdI
      d1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQ0FBUm80TFpTVllXZTA0UHNJT28weTVwbVJhYlkKdmFCNTdnZGdv
      eXpwR1lRRGFRRDNKcTNuVzdqZjZadlpiNVgxQWdYU1kyWUYxdjhzM3pDdnBGVUtiT2RPbzRJQgpN
      RENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJn
      Z3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVDc3elNLY0w5M29Y
      NE5WU0ZaMGl1U1FFc1IKelRBZkJnTlZIU01FR0RBV2dCUVZYelZVS0psWUFVdkZIci9kRFFsa3hZ
      UUR5ekEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dt
      OXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0lt
      RjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRF
      bEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNklt
      OXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdJcnNpQlpURDY4T1NVdTI5CitG
      K0VJb2YyM2JiL1VQVW1iKzh5allRUitOY0NJR0JrUzFpck1RKzl2ek84dEp3NHJ3OXN5WEtPT3pi
      ZnZrbXQKVEJndzhnMGkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoizwgtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJREFqQ0NBcW1nQXdJQkFnSVViaE5ySXR3UElBVk52ZXhHMk9TNTcw
      U1ZMMXd3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1S
      c3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdPVEl5TURJeU9E
      QXdXaGNOTWpNd09USXlNREl6TXpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4
      TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRn
      WURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdG
      cGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSbzRMWlNWWVdlMDRQ
      c0lPbzB5NXBtUmFiWQp2YUI1N2dkZ295enBHWVFEYVFEM0pxM25XN2pmNlp2WmI1WDFBZ1hTWTJZ
      RjF2OHMzekN2cEZVS2JPZE9vNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFV
      ZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUNzd6U0tjTDkzb1g0TlZTRlowaXVTUUVzUgp6VEFmQmdOVkhTTUVHREFXZ0JR
      Vlh6VlVLSmxZQVV2RkhyL2REUWxreFlRRHl6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1
      emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5
      dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9p
      SWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0
      Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3
      UkFJZ0lyc2lCWlRENjhPU1V1MjkKK0YrRUlvZjIzYmIvVVBVbWIrOHlqWVFSK05jQ0lHQmtTMWly
      TVErOXZ6Tzh0Snc0cnc5c3lYS09PemJmdmttdApUQmd3OGcwaQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICA
      gDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVs
      UmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMhIAGgZB
      ZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggD
      EgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMa
      BkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5zErEvCgtD
      b25zb3J0aXVtcxKhLxLWLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtErwuErEXCg9tYW51ZmFjdHVy
      ZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVUGtnVVplRnMrL0NFbzRLM3pSRUlX
      dnpOZ3FJd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdP
      VEl5TURJeU1qVXdXaGNOTWpVd056RXlNREl5TWpVd1dqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBN
      QTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpE
      RTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGRE
      QlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCR0oxL0pjU3dhSVFPdXd5eUlidEpx
      dzlHRng3TFQxRDlyVUwKc2JvdDBReTFBTDNCWGUxSkQ5MnhvaE51b3kyTW9HMEdacy94Ny9hT1Rn
      aWx6UURmc3QralFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlFxSzZLTlA1R0NFUEtPCmZvdHV6MjZQandHZ2JEQUtCZ2dxaGtqT1BR
      UURBZ05JQURCRkFpRUE2S2V0ZFFWaUdnSVRzZGQ5NWN5ZC9yM1QKcXdnY0oxNDRDLy92MVhEZkVB
      NENJRHRxRkRyRnV5UE9kbU5QNGhLL2RweDQzK3Q4RzM0R2xkTGNUK2QyY2dNNQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERVRDQ0Fy
      ZWdBd0lCQWdJVUhQRlRVdGhEd2E3aERmbENXeDZnKzdZd0Vld3dDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3T1RJeU1ESXpNREF3V2hjTk1qTXdPVEl5TURJ
      ek5UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRR
      dlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldG
      a2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtC
      dFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdB
      RTFZTVBOMGMvZTNWOG9tU3lVTkhZVXVKWldoUFZCZjdQK2FUUE1kaEFjMjZKajM3LzBySHkKekpv
      RlRSellBSUFOVkZiN0dlYlRhK1RNb09nNmtaUWJTcU9DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FF
      QXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU2N6eXhkZUF5cW5rMkszcmt0
      cEhFeGhaMUIvREFmCkJnTlZIU01FR0RBV2dCUXFLNktOUDVHQ0VQS09mb3R1ejI2UGp3R2diREFr
      QmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMWEJ0WkhOME1JR1hCZ2dx
      QXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZr
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5
      SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVs
      ZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRgpBaUVB
      NEo5cHhQOTJ2VllqRnhTdm1oWm4wbEpLZWNzNVdmQm4yQThkem13eGxla0NJQnlNVHFwSmNieUpY
      bnNyCnhYZTNyd3BHUzRVQ3JBYjgzQ1VvTzBLWTVGaUsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEREND
      QWJLZ0F3SUJBZ0lVUGtnVVplRnMrL0NFbzRLM3pSRUlXdnpOZ3FJd0NnWUlLb1pJemowRUF3SXcK
      WkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhM
      bTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPVEl5TURJeU1qVXdXaGNOTWpVd056RXlN
      REl5TWpVd1dqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdE
      UVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dB
      MVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdT
      TTQ5QXdFSEEwSUFCR0oxL0pjU3dhSVFPdXd5eUlidEpxdzlHRng3TFQxRDlyVUwKc2JvdDBReTFB
      TDNCWGUxSkQ5MnhvaE51b3kyTW9HMEdacy94Ny9hT1RnaWx6UURmc3QralFqQkFNQThHQTFVZApF
      d0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlFxSzZLTlA1
      R0NFUEtPCmZvdHV6MjZQandHZ2JEQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE2S2V0ZFFWaUdn
      SVRzZGQ5NWN5ZC9yM1QKcXdnY0oxNDRDLy92MVhEZkVBNENJRHRxRkRyRnV5UE9kbU5QNGhLL2Rw
      eDQzK3Q4RzM0R2xkTGNUK2QyY2dNNQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlu
      cyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1p
      bnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQEAEaBkFk
      bWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1T
      UBoGQWRtaW5zKgZBZG1pbnMSqhYKCmNhcnJpZXJNU1ASmxYatxQKA01TUBKvFBKkFBKhFAoKY2Fy
      cmllck1TUBLlBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJ
      VVcraWswR0tXVkU1bFdXMUtQVnNHVG80bGloSXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFl
      RncweQpNakE1TWpJd01qSTBORFphRncweU5UQTNNVEl3TWpJME5EWmFNRm94Q3pBSkJnTlZCQVlU
      QWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRH
      QTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVNnMEN6RGxBVkZnWW5tN2NXS2s3N2NpcE9T
      SlRqei9uU0lLUy9wRHpXOUpienB6MUZ5VUlEYTFsMEZrUU4xClJjYzlwd2FmK0dUUFBrRzlmSWsw
      ZFRhb28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFk
      QmdOVkhRNEVGZ1FVWHF3SnlMVFVkeXYrVzlFdGJHYXNHemczcWs0d0NnWUlLb1pJemowRQpBd0lE
      UndBd1JBSWdFOGx5SUV1U3grdW1rVUM0anFkN2ZKdnFtUlFpY1BCRTMwMng4YWYwUzZrQ0lISmhq
      OFQrCjdqWWZoZXg2YXZDcVlTcWtwTFVIWTlUV0UrVWxocndmS2xENQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDN1RDQ0FwU2dBd0lC
      QWdJVUJTbStyY0U3aEtScVJkZm9TQzB5eVZUR05oMHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxk
      REFlRncweQpNakE1TWpJd01qTXlNREJhRncweU16QTVNakl3TWpNM01EQmFNSGd4Q3pBSkJnTlZC
      QVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZC
      QW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJGeWNtbGxj
      akVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJC
      Z2dxaGtqT1BRTUJCd05DQUFSWnhQeE9aekdTK0lyTFRRMkhKcjR2CjNqSXM2a3Y3UGJ1MjFwbkxm
      TkVWNFgxay9jRzlJWHA2S0VOVGJzUU91VzV1M3ZJMEVjSUtISm84VFZtVDVuVk4KbzRJQkdEQ0NB
      UlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpG
      SytnSytEKzVUZjZoR1l4cWdxUlB0S3FYK1VKTUI4R0ExVWRJd1FZTUJhQUZGNnNDY2kwMUhjci9s
      dlJMV3htCnJCczRONnBPTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxUWmtOR00yWmpjMlpH
      WXRkMlprZDNJd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFY
      UWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9p
      SmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFXNUFZMkZ5Y21sbGNp
      MXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpqMEVBd0lEUndBd1JB
      SWdWTFJmWEhMMjdWblk0T1BUWHpob0h4V2NuTm5xT1JGbXRJQ2Zoalk2blpBQwpJR0QrSzBWWmE1
      bW5WMWJqQ0Y5MURCbkRNSHhZK0tNMDR1MVBlVFdrRDdTTAotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCkIOCgRTSEEyEgZTSEEyNTZK5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjl6
      Q0NBWjZnQXdJQkFnSVVXK2lrMEdLV1ZFNWxXVzFLUFZzR1RvNGxpaEl3Q2dZSUtvWkl6ajBFQXdJ
      dwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhK
      eWFXVnlMVzVsZERBZUZ3MHkKTWpBNU1qSXdNakkwTkRaYUZ3MHlOVEEzTVRJd01qSTBORFphTUZv
      eEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4
      dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21s
      bGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTZzBDekRsQVZGZ1lu
      bTdjV0trNzdjaXBPU0pUanovblNJS1MvcER6VzlKYnpwejFGeVVJRGExbDBGa1FOMQpSY2M5cHdh
      ZitHVFBQa0c5ZklrMGRUYW9vMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VC
      Ci93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVVhxd0p5TFRVZHl2K1c5RXRiR2FzR3pnM3FrNHdDZ1lJ
      S29aSXpqMEUKQXdJRFJ3QXdSQUlnRThseUlFdVN4K3Vta1VDNGpxZDdmSnZxbVJRaWNQQkUzMDJ4
      OGFmMFM2a0NJSEpoajhUKwo3allmaGV4NmF2Q3FZU3FrcExVSFk5VFdFK1VsaHJ3ZktsRDUKLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAES
      AggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAa
      DhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoK
      Y2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIM
      CgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIM
      CAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRt
      aW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQT3Jk
      ZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5l
      bC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMi
      IgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdS
      ZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlu
      cxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
