apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://172.27.245.67:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: supplychain-net

    genesis: |-
      CiIaIK85usQ54FDrE4So4ePyGaeHGI13AmW1RacF2C6EBBmiEpZeCpNeCpBeCngKWggBEAEaBgjx
      gYCdBiIKc3lzY2hhbm5lbCpANWM2Y2Y4ZjEyYmU0MDg1NmQxNTc3MzViMTNkMjhkNjU1MWY2MmMx
      ZTU2Mzg1ZjQzN2U1MGVjM2FiNGE2Njk2ZhIaEhiKiQ7eB/N6TMyLGkc+76DG6sHRKUNxMFYSk10K
      kF0SjV0SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVRlhxWFpaNUhaUVBxTU5YMTRTNUNIWGFkRitvd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFNU1EVTFOREE0V2hjTk1qVXhNREE0TURVMU5EQTRX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJNSUhZ
      bUpEU1dtSnZOS3NPekdFQWtLUk83VUE3UlZzMkRjdGViaEVzMDhENGRSL3JyUXcKMy9BQVlGQ1I5
      c0QyNjFoMnl0OWtKQzI0dDRxU2NtZXFyeitqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUU1WMkJ5WkhZREo0L1hEQXJmNzM1YnRU
      L1oyVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBQnQxdU1GUmRtUC9mRlVadEttdTFTS2xPSTdE
      Rm1Fektlbno1Y1I5c3EKcndJaEFJWUx0RjIrRFFRZGZFVE5hRDNRRWxLT0VFWGlVUVdHWkR2RXBV
      My9YYmc0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVS2p2aU9FU2lLRTZKaU1RVFVZTXpaKzZxa1kwd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFNU1EWXdNakF3V2hjTk1q
      TXhNakU1TURZd056QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFenFrU2RnRFd4OVpGVDduNUlJUjhkTm01YkNM
      TFFLNDAKczdYaTNvNWpPMkprSkdJQVpMWjlSdGlqWDZjamtUZHcwZWRydEMxSEZGSSt6ZHc2dTEw
      TUFxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTM21DWG1na2dPCmM3WG0rVHJwQXQ4YUFlclJiVEFmQmdOVkhTTUVHREFXZ0JR
      TVYyQnlaSFlESjQvWERBcmY3MzVidFQvWjJUQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M1ptTmtPRGs0Tm1ZNExXMDJkbVJvTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnSFdMWmtUMEpuOG9WNUU1MWdPaDQ4K2lud3RjcE5XTGhnVmFnV1FRQWlqVUNJRVRa
      dEV3YVg2UkFRN1gvCjQ2eWtTV242Ym00NkdqaW1GWDVIMkxMUUFGWEoKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVRlhxWFpaNUhaUVBxTU5YMTRTNUNIWGFkRitvd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFNU1EVTFOREE0V2hjTk1qVXhNREE0
      TURVMU5EQTRXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJNSUhZbUpEU1dtSnZOS3NPekdFQWtLUk83VUE3UlZzMkRjdGViaEVzMDhENGRSL3JyUXcK
      My9BQVlGQ1I5c0QyNjFoMnl0OWtKQzI0dDRxU2NtZXFyeitqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUU1WMkJ5WkhZREo0L1hE
      QXJmNzM1YnRUL1oyVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBQnQxdU1GUmRtUC9mRlVadEtt
      dTFTS2xPSTdERm1Fektlbno1Y1I5c3EKcndJaEFJWUx0RjIrRFFRZGZFVE5hRDNRRWxLT0VFWGlV
      UVdHWkR2RXBVMy9YYmc0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOwoLRW5k
      b3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyoG
      QWRtaW5zGoISCg1Db25zZW5zdXNUeXBlEvAREuURCghldGNkcmFmdBLYEQrBEQoYb3JkZXJlcjEu
      c3VwcGx5Y2hhaW4tbmV0EIo3Gs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVEND
      QXFlZ0F3SUJBZ0lVRmM2VWhSWTF3ODBjdVpHUmI5NzhHbE5PTUlvd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFNU1EWXdNakF3V2hjTk1qTXhNakU1TURZd056QXdX
      akJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVa
      Rzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdI
      d1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQ0FBUnRZOUdiQW5nQys2cUtqUHRzaTY1U1poUm8KZnU3bGpienhM
      bjlIL2Nsby9CU3NDcFJwaThjMHFPR3Z1WjB0dHhINHdtVmtFcDUzSlphNHhhSkI3MnNWbzRJQgpM
      akNDQVNvd0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJn
      Z3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVGJxMGN4N253RGZm
      NkZHWE9COXlhMkR5M2cKblRBZkJnTlZIU01FR0RBV2dCUU1WMkJ5WkhZREo0L1hEQXJmNzM1YnRU
      L1oyVEE5QmdOVkhSRUVOakEwZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dH
      OXlaR1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVsCmREQnNCZ2dxQXdRRkJnY0lBUVJnZXlKaGRI
      UnljeUk2ZXlKb1ppNUJabVpwYkdsaGRHbHZiaUk2SWlJc0ltaG0KTGtWdWNtOXNiRzFsYm5SSlJD
      STZJbTl5WkdWeVpYSXhMbk4xY0hCc2VXTm9ZV2x1TFc1bGRDSXNJbWhtTGxSNQpjR1VpT2lKdmNt
      UmxjbVZ5SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ3laNEhNd2lBbS9PQnduZXlPCklJ
      U2ZKak9xUHd0NFRJcy95RFZOQVFMOWlBSWdmZnFuM0tNK09Tcm1JUUlnWTZRdzJQdlJUU3BkbzZN
      Y0ttZ3AKbFpuNVMrcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoizwgtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJREFUQ0NBcWVnQXdJQkFnSVVGYzZVaFJZMXc4MGN1WkdSYjk3OEds
      Tk9NSW93Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1S
      c3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXhNakU1TURZd01q
      QXdXaGNOTWpNeE1qRTVNRFl3TnpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4
      TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRn
      WURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdG
      cGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSdFk5R2JBbmdDKzZx
      S2pQdHNpNjVTWmhSbwpmdTdsamJ6eExuOUgvY2xvL0JTc0NwUnBpOGMwcU9HdnVaMHR0eEg0d21W
      a0VwNTNKWmE0eGFKQjcyc1ZvNElCCkxqQ0NBU293RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFV
      ZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUYnEwY3g3bndEZmY2RkdYT0I5eWEyRHkzZwpuVEFmQmdOVkhTTUVHREFXZ0JR
      TVYyQnlaSFlESjQvWERBcmY3MzVidFQvWjJUQTlCZ05WSFJFRU5qQTBnaGh2CmNtUmxjbVZ5TVM1
      emRYQndiSGxqYUdGcGJpMXVaWFNDR0c5eVpHVnlaWEl4TG5OMWNIQnNlV05vWVdsdUxXNWwKZERC
      c0JnZ3FBd1FGQmdjSUFRUmdleUpoZEhSeWN5STZleUpvWmk1QlptWnBiR2xoZEdsdmJpSTZJaUlz
      SW1obQpMa1Z1Y205c2JHMWxiblJKUkNJNkltOXlaR1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVs
      ZENJc0ltaG1MbFI1CmNHVWlPaUp2Y21SbGNtVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVD
      SVFDeVo0SE13aUFtL09Cd25leU8KSUlTZkpqT3FQd3Q0VElzL3lEVk5BUUw5aUFJZ2ZmcW4zS00r
      T1NybUlRSWdZNlF3MlB2UlRTcGRvNk1jS21ncApsWm41UytzPQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICA
      gDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVs
      UmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMhIAGgZB
      ZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0I
      AxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMi
      KgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zErkvCgtD
      b25zb3J0aXVtcxKpLxLeLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsQuErEXCg9tYW51ZmFjdHVy
      ZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVTFdMaTBrOHhEeDEvUU00RGxHc2Mv
      ci9iQUcwd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhN
      akU1TURVMU5USTRXaGNOTWpVeE1EQTRNRFUxTlRJNFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBN
      QTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpE
      RTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGRE
      QlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRXlPNENqVVh5T0pTOVlYVEc4bUE2
      dExwaERVOThtTnZJb0wKaUhIMWZuZldQYVNhd01ianBVaFRtSEJreGZBaGNKV3ordjVrK3pjeWpv
      dUxTM3VYc2dxalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlJlQWNCQUNxMEJIS0xCCnJNSkFXVFR0WXZ4eTl6QUtCZ2dxaGtqT1BR
      UURBZ05JQURCRkFpRUF4MG96dEJqZ2ZZQm5POFVjK0UxdFZQalcKQnNXNUlIVSt6UDd2cVVXZVZB
      Y0NJRWtmL2dYS21JblNOZXJuUXJsY0t0UkEwb1dHTmRGS1dHdG85TjJCN1lXcwotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERURDQ0Fy
      ZWdBd0lCQWdJVU9jOUxmV21oQzZPMjdpZW5ndnA3OEZzWVlGRXdDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TWpFNU1EWXdOREF3V2hjTk1qTXhNakU1TURZ
      d09UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRR
      dlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldG
      a2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtC
      dFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdB
      RVZFcGFUUUZzN3N4bmExeGl1TXJRNC9abitNZVhwcXZTME5WZmZldHpDM0pVUHFmcXc0NjYKS1Bj
      V3R2K1k5VDc0TFdSallSRVNPeW5udW9VS1BCMDd0Nk9DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FF
      QXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUmlDNFhaSVlXV2h1akQ1dnNk
      alMzN2M1QTBtVEFmCkJnTlZIU01FR0RBV2dCUmVBY0JBQ3EwQkhLTEJyTUpBV1RUdFl2eHk5ekFr
      QmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNaRGRpTlRaa05EWm1MWEUxWTJ4ek1JR1hCZ2dx
      QXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZr
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5
      SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVs
      ZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRQpBaUI5
      eUs5NSsxRkNLQlQxZjMxZTNpYzJZWkJIQ3BoSWJZUWdsOTVqUmU3QnF3SWdZbmg1RzFtV2crb3lm
      N0hJCm5NOTVkNitvVE9HT3YydE1kb1FWRnNmQ1J0RT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEREND
      QWJLZ0F3SUJBZ0lVTFdMaTBrOHhEeDEvUU00RGxHc2Mvci9iQUcwd0NnWUlLb1pJemowRUF3SXcK
      WkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhM
      bTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakU1TURVMU5USTRXaGNOTWpVeE1EQTRN
      RFUxTlRJNFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdE
      UVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dB
      MVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdT
      TTQ5QXdFSEEwSUFCRXlPNENqVVh5T0pTOVlYVEc4bUE2dExwaERVOThtTnZJb0wKaUhIMWZuZldQ
      YVNhd01ianBVaFRtSEJreGZBaGNKV3ordjVrK3pjeWpvdUxTM3VYc2dxalFqQkFNQThHQTFVZApF
      d0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJlQWNCQUNx
      MEJIS0xCCnJNSkFXVFR0WXZ4eTl6QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUF4MG96dEJqZ2ZZ
      Qm5POFVjK0UxdFZQalcKQnNXNUlIVSt6UDd2cVVXZVZBY0NJRWtmL2dYS21JblNOZXJuUXJsY0t0
      UkEwb1dHTmRGS1dHdG85TjJCN1lXcwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlu
      cyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJNU1AQARoGQWRt
      aW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQ
      GgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1T
      UBoGQWRtaW5zKgZBZG1pbnMSshYKCmNhcnJpZXJNU1ASoxYavxQKA01TUBK3FBKsFBKpFAoKY2Fy
      cmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdBd0lCQWdJ
      VUxJU3BWeE9adG94VzRKWGRlb1hPamtYUjhOc3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFl
      RncweQpNakV5TVRrd05UVTNOVE5hRncweU5URXdNRGd3TlRVM05UTmFNRm94Q3pBSkJnTlZCQVlU
      QWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRH
      QTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRvMXZuZ2YvZXVLekIzeC92dTdUZUhwcTRZ
      Zlo2L0JYdXFBZlRVa0ovMFRQRHRGWS9mV3BTVHpleU01WVdOCkxHdmdwdndpU1M3UTZ0SkRQaVlt
      d1JhQm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFk
      QmdOVkhRNEVGZ1FVa3YraWhRdU9zYlkyc2hxaGM4SmJDUWpLK21Rd0NnWUlLb1pJemowRQpBd0lE
      U1FBd1JnSWhBUHZWQ3UrNzBNYkRaa3I5ejZNcHMxVTEzUFhjZU5sOFNUQVdhZTRrUkVDTEFpRUFt
      MWxqCmRXREpvSWZlaG1Qc2RYZUJOcGg0UE9LMG9IMnBDMGwxNGRtZHBFcz0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdUQ0NBcFNn
      QXdJQkFnSVVNN2VwVGJEeHlSNmFQZStxQmZxMUk3bXQzQVV3Q2dZSUtvWkl6ajBFQXdJdwpXakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlM
      VzVsZERBZUZ3MHkKTWpFeU1Ua3dOakEzTURCYUZ3MHlNekV5TVRrd05qRXlNREJhTUhneEN6QUpC
      Z05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9C
      Z05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnlj
      bWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQ0FBUlIzMWJtLy9mMWMvaVFZbFZqZVpmWgpjK1puM1E4YnFZd3pK
      TmRYSWUzNDBTM2ZBQVVlNXV5VjNqcHNVOHlhU1ZWNXYyS0FyaFB5L3VSN0w3a2tVYlp2Cm80SUJH
      RENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JC
      WUUKRkt3Q012cDBXREdvblRNSENsTlhJYW1pcVVJc01COEdBMVVkSXdRWU1CYUFGSkwvb29VTGpy
      RzJOcklhb1hQQwpXd2tJeXZwa01DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVGMxWTJRMU9U
      VmlPR010ZUd0c2NUa3dnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1Gakxt
      bHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIy
      NGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNt
      bGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFJ3
      QXdSQUlnUDcvejlPNG5tTjB5ajcybVZ2Y3hsYW5WUEhTdW1yenB4aFhWVTJrZzZFVUMKSUY4U3N5
      OEhpd2hQU3RZM1hicmJLWk1DdnlQa0dlMW8vdjJZZWpuUHBWU3EKLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUIrVENDQVo2Z0F3SUJBZ0lVTElTcFZ4T1p0b3hXNEpYZGVvWE9qa1hSOE5zd0NnWUlLb1pJemow
      RUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1
      allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXlNVGt3TlRVM05UTmFGdzB5TlRFd01EZ3dOVFUzTlRO
      YU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFj
      TUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJG
      eWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVG8xdm5nZi9l
      dUt6QjN4L3Z1N1RlSHBxNFlmWjYvQlh1cUFmVFVrSi8wVFBEdEZZL2ZXcFNUemV5TTVZV04KTEd2
      Z3B2d2lTUzdRNnRKRFBpWW13UmFCbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVk
      RHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVrditpaFF1T3NiWTJzaHFoYzhKYkNRaksrbVF3
      Q2dZSUtvWkl6ajBFCkF3SURTUUF3UmdJaEFQdlZDdSs3ME1iRFprcjl6Nk1wczFVMTNQWGNlTmw4
      U1RBV2FlNGtSRUNMQWlFQW0xbGoKZFdESm9JZmVobVBzZFhlQk5waDRQT0swb0gycEMwbDE0ZG1k
      cEVzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAES
      GhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggS
      BggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARIC
      CAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggB
      EgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBv
      bGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hB
      MjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlu
      cxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAa
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8zEgAa
      BkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcS
      DQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlu
      cyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
