apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIGYGkso3NvNhko2nbN72x8VN2mjolBpRwIr9LYoCrqcIErReCrFeCq5eCngKWggBEAEaBgiJ
      89+ZBiIKc3lzY2hhbm5lbCpAZTlmMzhmYzU4ZTJmOTI1NThlYTI0MWI4Zjc4MDQyZDM5MTUwZmFk
      ZWVjMTRmOTI0OThiOTg2NTM0MmNmMzZlNRIaEhh34zV6iRaVFlSfAgAfJwE04zgLF3v0xo8SsV0K
      rl0Sq10SnysKB09yZGVyZXISkysS1hYKDnN1cHBseWNoYWluTVNQEsMWGs8UCgNNU1ASxxQSvBQS
      uRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVTG5VNUxyL2NBaGJSN2o0NGw2ZEZVbW1uaDJzd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBeE1EZ3dPVEV4V2hjTk1qVXdOekl4TURnd09URXhX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJOZHZp
      MmM5Z0RJYy9TcEVSQTMzY3dMTUlVU2thUkFvL2ZSQ2FaUWs5MWxMZnRZOXJPTWgKM3VkeEhCRGdH
      OGxINXNtRjZqQW4wOXgzVlVkY25kcXA0ZWlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUyt3cURzR1FvWGMyRldZRDlzODUzcTBr
      eEdCekFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQWo3a2diY3d6dDJFbHRGUThoeVdWQytCWlB6
      dFY4OVVCeS9LMnNtL2EKbXFzQ0lRRC8yUXpMRUhBQTZ1bE5RZWcwZEY2VEpEZzRrZXp0Y3hnUHNX
      NnZQYlExN1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKmCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNGpDQ0FvaWdBd0lCQWdJVVhST2hNcGtWa3FzbWY1RFU2b1dQbktxVm40
      Y3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1EQXhNRGd4TmpBd1do
      Y05Nak14TURBeE1EZ3lNVEF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXRjaGtacnluakJpTUhoQWxkYkxLeVNQ
      c3FrR2VnWWVzCjB2SmdpckI3Ukdialo2emVuV1BKckt5NnV3Rm82OENjUG9INStMRkxoRGlCcXJv
      T0tqRHdyS09DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCVDQ2OERJSHZzYwpna1E5K09TWFV3NnhwZlg1YVRBZkJnTlZIU01FR0RB
      V2dCUyt3cURzR1FvWGMyRldZRDlzODUzcTBreEdCekFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDFOalkzWXpZM1ptWTNMVGRyWTNoeU1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFNBQXcKUlFJaEFNblBvRXl5cE5VSGhuc2xsQ1h3SHNIUWt5d3hkaGM1b2xtanFRV1pUUXBD
      QWlBck1mK2dzdDFjK0xJdgpFNlduY1ZSN2dnczQxckZKeUxOVktpaHhhUTBQaEE9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK9QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQ0FUQ0NBYWFnQXdJQkFnSVVMblU1THIvY0FoYlI3ajQ0bDZkRlVtbW5oMnN3
      Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlE
      VlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXhNREF4TURnd09URXhXaGNO
      TWpVd056SXhNRGd3T1RFeFdqQmVNUXN3Q1FZRFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1
      Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFa
      QmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcK
      U000OUF3RUhBMElBQk5kdmkyYzlnREljL1NwRVJBMzNjd0xNSVVTa2FSQW8vZlJDYVpRazkxbExm
      dFk5ck9NaAozdWR4SEJEZ0c4bEg1c21GNmpBbjA5eDNWVWRjbmRxcDRlaWpRakJBTUE4R0ExVWRF
      d0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTK3dxRHNH
      UW9YYzJGV1lEOXM4NTNxMGt4R0J6QUsKQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBajdrZ2Jjd3p0
      MkVsdEZROGh5V1ZDK0JaUHp0Vjg5VUJ5L0syc20vYQptcXNDSVFELzJRekxFSEFBNnVsTlFlZzBk
      RjZUSkRnNGtlenRjeGdQc1c2dlBiUTE3UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZB
      ZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoG
      QWRtaW5zIjsKC0VuZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5N
      U1AaBkFkbWlucyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5N
      U1AaBkFkbWlucyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5N
      U1AaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4K
      DEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZB
      ZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooSCg1Db25zZW5z
      dXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3
      GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQXFtZ0F3SUJBZ0lVQmFWSmRs
      dUxqMVN4dU1XdUpqTUNFbjIxaGxNd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3Ckho
      Y05Nakl4TURBeE1EZ3hOakF3V2hjTk1qTXhNREF4TURneU1UQXdXakJ4TVFzd0NRWURWUVFHRXdK
      SFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdk
      UGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndO
      Q0FBUk1pZlRTNkFZb2VNQ2NnRWlKM1VSTDFvZGgKWU1xTEVpcEhGWGE3RnV4WWNLRkZkUVo2N003
      bW9UOUJzVWp2ci9FYm5QUWZsMTZBWHFHZ0J6VkZMb0tFbzRJQgpNRENDQVN3d0RnWURWUjBQQVFI
      L0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdO
      VkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUTN2S0lTcXpkeVVGNHFMVFBteDEzT3hzbFUKMERB
      ZkJnTlZIU01FR0RBV2dCUyt3cURzR1FvWGMyRldZRDlzODUzcTBreEdCekEvQmdOVkhSRUVPREEy
      Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZz
      YjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0Zt
      Wm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1
      YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJ
      S29aSXpqMEVBd0lEU0FBd1JRSWhBTWUrQ2Zhd0VRdnJhWnBvCjhnZktuQmlFZDRUQ051dXZHc0hY
      M0I5QkFhbkJBaUE1RSsyK2t4S0d1M2pRaXZySDhKclVqRk1CR3hTT2ZZa04KcVRYREoydDlBQT09
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURBekNDQXFtZ0F3SUJBZ0lVQmFWSmRsdUxqMVN4dU1XdUpqTUNFbjIxaGxNd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBeE1EZ3hOakF3V2hjTk1qTXhNREF4
      TURneU1UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1
      TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJs
      Y21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUk1pZlRTNkFZb2VNQ2NnRWlKM1VSTDFvZGgK
      WU1xTEVpcEhGWGE3RnV4WWNLRkZkUVo2N003bW9UOUJzVWp2ci9FYm5QUWZsMTZBWHFHZ0J6VkZM
      b0tFbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dB
      UVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUTN2
      S0lTcXpkeVVGNHFMVFBteDEzT3hzbFUKMERBZkJnTlZIU01FR0RBV2dCUyt3cURzR1FvWGMyRldZ
      RDlzODUzcTBreEdCekEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBi
      aTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdC
      d2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXli
      MnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpW
      SGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTWUrQ2Zhd0VR
      dnJhWnBvCjhnZktuQmlFZDRUQ051dXZHc0hYM0I5QkFhbkJBaUE1RSsyK2t4S0d1M2pRaXZySDhK
      clVqRk1CR3hTT2ZZa04KcVRYREoydDlBQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIK
      BTUwMG1zEAoYASAFKICAgAoaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3Jp
      dGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRl
      cnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoG
      QWRtaW5zKgZBZG1pbnMSwy8KC0NvbnNvcnRpdW1zErMvEuguChVTdXBwbHlDaGFpbkNvbnNvcnRp
      dW0Szi4SuxcKD21hbnVmYWN0dXJlck1TUBKnFxqvFQoDTVNQEqcVEpwVEpkVCg9tYW51ZmFjdHVy
      ZXJNU1AShgYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVh
      SDBsREM2MTlIL0l6K0xqRklBcmpLeUNHYUV3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVC
      aE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdF
      d1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRY
      SmwKY2kxdVpYUXdIaGNOTWpJeE1EQXhNRGd4TVRFeVdoY05NalV3TnpJeE1EZ3hNVEV5V2pCa01R
      c3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRY
      SnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJX
      RnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJK
      U3NId0JDekVGZlVydW94djloYmIrZGExN1VwRGJ4Tk4xOApGaVRXcFJxTU9RbmRqaFdSQXFRL01T
      SEhBTXRNb0hkK2IwRVRPZG9qaUxHSGEwNFMvRm1qUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFm
      OHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVGxCZVlyWVRDNUorcUUKejc2TjNI
      dmM4VThvY3pBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXk2TXh1WVJPN0U2TERsWG1JZ1lJc09Q
      SQpzakJJM1cwMXR0MDArSXJoZ0RrQ0lRREo2cmhRTEVEbTh4Mk5uRThMZE1vSVpCNXFLSmJWMXQ2
      bDFYWWMwYVVtCmJBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVlTHRWSWRTQS8yU1BXNURtUDNWQzRT
      bnhXWVF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRI
      VnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1E
      QXhNRGd4T0RBd1doY05Nak14TURBeE1EZ3lNekF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdq
      QVlCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClpt
      RmpkSFZ5WlhJeEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21W
      eU1SOHcKSFFZRFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29a
      SXpqMENBUVlJS29aSQp6ajBEQVFjRFFnQUVqb0VqT3dpbzRaT3BxTWJmekpTaFdsM1dGRGVZd0ZP
      R1JWeWtmOExObWpPaGNac3RtRFBFCk55bjN4TEQ2WGNhaHBiN1hubGVLanVjMWV4N1oxTHZuMjZP
      Q0FTSXdnZ0VlTUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFV
      ZERnUVdCQlQvOURIVktLd3JyR3Y5aFdWeVE5Slg2U2wrQlRBZgpCZ05WSFNNRUdEQVdnQlRsQmVZ
      cllUQzVKK3FFejc2TjNIdmM4VThvY3pBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAzWTJR
      M1ptUm1PVGMyTFdwdGJXWjNNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdK
      aFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0Yw
      YVc5dQpJam9pYldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0
      YVc1QWJXRnVkV1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFL
      QmdncWhrak9QUVFEQWdOSEFEQkUKQWlCYlJDZFp2NTJOQkt4eDJWdEpSSXBjYVlXTktXZFBqVjJD
      RVM4TGF6NnYyZ0lnTnhwK2h3VnBOZjQ2eWxuQwpkU0QrR1YvR1g4VHlVTDBwb3o3MWJ2REhuRTg9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqGBi0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVWFIMGxEQzYxOUgvSXorTGpGSUFy
      akt5Q0dhRXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdN
      QmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZq
      ZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4
      TURBeE1EZ3hNVEV5V2hjTk1qVXdOekl4TURneE1URXlXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQ
      TUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00K
      REUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxk
      REJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkpTc0h3QkN6RUZmVXJ1b3h2OWhi
      YitkYTE3VXBEYnhOTjE4CkZpVFdwUnFNT1FuZGpoV1JBcVEvTVNISEFNdE1vSGQrYjBFVE9kb2pp
      TEdIYTA0Uy9GbWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURB
      Z0dtTUIwR0ExVWREZ1FXQkJUbEJlWXJZVEM1SitxRQp6NzZOM0h2YzhVOG9jekFLQmdncWhrak9Q
      UVFEQWdOSkFEQkdBaUVBeTZNeHVZUk83RTZMRGxYbUlnWUlzT1BJCnNqQkkzVzAxdHQwMCtJcmhn
      RGtDSVFESjZyaFFMRURtOHgyTm5FOExkTW9JWkI1cUtKYlYxdDZsMVhZYzBhVW0KYkE9PQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARIC
      CAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAES
      AggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAES
      AggAGhUSEwoPbWFudWZhY3R1cmVyTVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIf
      EggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSshYKCmNhcnJp
      ZXJNU1ASoxYavxQKA01TUBK3FBKsFBKpFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUlqOEFQV0U5ZWh4WlJrWHc1d2dPL09jMmww
      OHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZR
      WURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV3TURFd09ERXpNVEphRncweU5U
      QTNNakV3T0RFek1USmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2Iy
      NHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0Ex
      VUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndO
      QwpBQVMyN3pod2tZYVdKVHFyLzBGM0dEbEduNDlsQVYwamhWaE9GUk9qMlFvS3hIYUlZVnI1WlB2
      OG1CVkFzTFVKClYxbC9MUXFzM1BYNVlqZTZIRkxkS2VJU28wSXdRREFQQmdOVkhSTUJBZjhFQlRB
      REFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVdjE1cFRjVG5KTkRWdE9Z
      RGxLcmFScGQrZUM0d0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBS213b2NtbDIvTlZlcUhqb2J1
      aUxNbmJ5K1dYbkJ5QjJzQXU0V1Nmei9lQ0FpQmRFeTRPCkZVc2ZCZUxrY0NLV1IzcTFZaG5PTFhi
      QWd0REM0T2k0YkdwSHdRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzdUQ0NBcFNnQXdJQkFnSVVTakJTRTl0aWFlbkVhRlBvR3ht
      NitIQzVBR0l3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFd01ERXdPREl3TURC
      YUZ3MHlNekV3TURFd09ESTFNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJ
      MU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05W
      CkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVB
      WTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUU9RSThB
      dGlpSTVCYnJ0THJvbmJtMQpCanBNd0hWZ0pSSkdJMC9USENXa2taSHhQb094cGQ2a2UydUYrOGw4
      SnJTRjNldSsyNzBCUkpoODZmaWw5RTY4Cm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VB
      TUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRk9MZ1FvVW56YlBhTUxodUtNMGtJMEJQ
      Z2Y3c01COEdBMVVkSXdRWU1CYUFGTDllYVUzRTV5VFExYlRtQTVTcQoya2FYZm5ndU1DUUdBMVVk
      RVFRZE1CdUNHV05oTFhSdmIyeHpMVFprTkdNMlpqYzJaR1l0YUd4MlpIWXdnWTBHCkNDb0RCQVVH
      QndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkK
      T2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXli
      MnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZ
      V1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnVy8xbkdBUGdpTUltdzRjakppUExW
      QXBMRUZRRXZsRzFiY3JlQzFCVXBKY0MKSUhjU0ZtZUVPU3k2dFQrZUtMcXBMYk1TaDRpMW9xekUr
      dzhybkpnVnlRVVkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukF
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVSWo4QVBXRTll
      aHhaUmtYdzV3Z08vT2MybDA4d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhE
      ekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtE
      QWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXdN
      REV3T0RFek1USmFGdzB5TlRBM01qRXdPREV6TVRKYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RR
      WUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEy
      RnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BR
      SUJCZ2dxaGtqT1BRTUJCd05DCkFBUzI3emh3a1lhV0pUcXIvMEYzR0RsR240OWxBVjBqaFZoT0ZS
      T2oyUW9LeEhhSVlWcjVaUHY4bUJWQXNMVUoKVjFsL0xRcXMzUFg1WWplNkhGTGRLZUlTbzBJd1FE
      QVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZn
      UVV2MTVwVGNUbkpORFZ0T1lEbEtyYVJwZCtlQzR3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFL
      bXdvY21sMi9OVmVxSGpvYnVpTE1uYnkrV1huQnlCMnNBdTRXU2Z6L2VDQWlCZEV5NE8KRlVzZkJl
      TGtjQ0tXUjNxMVlobk9MWGJBZ3REQzRPaTRiR3BId1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQ
      ARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1T
      UBoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZB
      ZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlu
      cyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFu
      bmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxII
      CAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlu
      cxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVy
      ZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zGiYK
      EEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoG
      QWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdX
      cml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
