apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIBL/YY4+IzTSRSJe6jiOb9BioNuEcrvJN/y3KlY9EUtQEqpeCqdeCqReCngKWggBEAEaBgic
      9taZBiIKc3lzY2hhbm5lbCpAOWUzNzkzODg5YWQzMjk4OWIyMjdiY2MyOGQ0ZDcyMDUyNWMwYzg3
      ZTkzOTQ0NjBlMGJjNGYyNDczMzZiMWMyZhIaEhgjCIu1PiQMrJYOzBNAk5ewtVrDUUtPu78Sp10K
      pF0SoV0SmysKB09yZGVyZXISjysS0hYKDnN1cHBseWNoYWluTVNQEr8WGssUCgNNU1ASwxQSuBQS
      tRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVVXQ1cEQzWmZGUitUN24wWm1sL2FkK0dOZXcwd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RJNU1UTXhPREV5V2hjTk1qVXdOekU1TVRNeE9ERXlX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJJbktL
      UzlMRkNkV1FMUkRrR3RTUDM2VmQzRzdlSmRXWWxGL3crQktNeGFIV3lVQ3dTVGEKVDNjM0JaZFNF
      NS9DWGVPTEdvRE91SnJBRXlZM0VaemFzQjJqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVDlxQ3NWMjcrU1U0NDJJZ0dnYzQycmF4
      Mjk0ekFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTZDc2JwUEdqTloySzE2U203NFJCN2RDZStI
      SWUxaXo5R09RVWhLeXgKZXdRQ0lRQ2lnNFJCRDRiUnFLUFQxSzl4L2dyYnM1b2hKblZObUJTYzBO
      SEttNzQ2T3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKiCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNFRDQ0FvaWdBd0lCQWdJVU5zMGN1a3h4WFJFMmJiZXZFNG1neXFMNys4
      MHdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09USTVNVE15TlRBd1do
      Y05Nak13T1RJNU1UTXpNREF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRU1hMkQ5eGRLYlRaWTljQ3Q1OFluZVNE
      Tnozbld0WVZjCk9oTHRTRVR2SnNBYytZeUxkTG9tbWcyUUQ1b3k1YkFrUGVHbU0raWhrQ0hRNjk4
      aVhxNjluYU9DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCVEM0OFF1dVRWQQp3bTZXSmVxc0VFVk9rd2F2bWpBZkJnTlZIU01FR0RB
      V2dCVDlxQ3NWMjcrU1U0NDJJZ0dnYzQycmF4Mjk0ekFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDFOalkzWXpZM1ptWTNMVFpxTmpZeU1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFJ3QXcKUkFJZ01EUnJ1K3hHWnpzdEplMWJsRzBWQUllZWVQNzkxS09wa20yN0NHOTJEeUFD
      SUFHOG9lbDZ1VWw4L1dOQQpmMCsxMGRXUWQycTNQQldPYmhROUxnYzdHUXBkCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkr1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVVV0NXBEM1pmRlIrVDduMFptbC9hZCtHTmV3MHdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09USTVNVE14T0RFeVdoY05NalV3
      TnpFNU1UTXhPREV5V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCSW5LS1M5TEZDZFdRTFJEa0d0U1AzNlZkM0c3ZUpkV1lsRi93K0JLTXhhSFd5VUN3
      U1RhClQzYzNCWmRTRTUvQ1hlT0xHb0RPdUpyQUV5WTNFWnphc0IyalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlQ5cUNzVjI3K1NV
      NDQySWdHZ2M0MnJheDI5NHpBSwpCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUE2Q3NicFBHak5aMksx
      NlNtNzRSQjdkQ2UrSEllMWl6OUdPUVVoS3l4CmV3UUNJUUNpZzRSQkQ0YlJxS1BUMUs5eC9ncmJz
      NW9oSm5WTm1CU2MwTkhLbTc0Nk93PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlu
      cyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1p
      bnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zIjcKB1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zKgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0
      Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlu
      cxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaihIKDUNvbnNlbnN1c1R5
      cGUS+BES7REKCGV0Y2RyYWZ0EuARCskRChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijca0wgt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVmK3dOdEdieWVU
      bk8xejFXQ3NEQmlxN05LU013Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6
      QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RB
      ZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1q
      SXdPVEk1TVRNeU5UQXdXaGNOTWpNd09USTVNVE16TURBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpF
      YgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21S
      bGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1
      emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFT
      dWNxaWFjOUJTK1FEMzBLOHc1Vml3YkRtdApyNmpsUjhtVG5EV1BEQlJtY2wwR2hQS1dnT2FtWGhm
      c0h0bzRURFlrcTFxNGJrR2NLWHl6ald5WVlvNWxvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFR
      REFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJN
      QkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRRzdTWWJtc2p6R0p6a3dEd3JOSHpmVGlZYQp0REFmQmdO
      VkhTTUVHREFXZ0JUOXFDc1YyNytTVTQ0MklnR2djNDJyYXgyOTR6QS9CZ05WSFJFRU9EQTJnaGh2
      CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1
      Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxz
      YVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3
      Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJ
      emowRUF3SURTQUF3UlFJaEFLNDMwOWw3NEJRakkxSWMKUWFQckVGcjdpT2dXcTlYUW9sb3V2NU5z
      T1JuN0FpQXdxMjlMeUE4M0RQdS9VdDJPTXVTM1lONmpnYWNSM0RYZQo4cjNraVl3M25nPT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      REF6Q0NBcW1nQXdJQkFnSVVmK3dOdEdieWVUbk8xejFXQ3NEQmlxN05LU013Q2dZSUtvWkl6ajBF
      QXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVF
      Qnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6
      ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdPVEk1TVRNeU5UQXdXaGNOTWpNd09USTVNVE16
      TURBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12
      VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5
      TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2Nx
      aGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTdWNxaWFjOUJTK1FEMzBLOHc1Vml3YkRtdApyNmps
      UjhtVG5EV1BEQlJtY2wwR2hQS1dnT2FtWGhmc0h0bzRURFlrcTFxNGJrR2NLWHl6ald5WVlvNWxv
      NElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZC
      d01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRRzdTWWJt
      c2p6R0p6a3dEd3JOSHpmVGlZYQp0REFmQmdOVkhTTUVHREFXZ0JUOXFDc1YyNytTVTQ0MklnR2dj
      NDJyYXgyOTR6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVa
      WFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JC
      R0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNi
      V1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHda
      U0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFLNDMwOWw3NEJRakkx
      SWMKUWFQckVGcjdpT2dXcTlYUW9sb3V2NU5zT1JuN0FpQXdxMjlMeUE4M0RQdS9VdDJPTXVTM1lO
      NmpnYWNSM0RYZQo4cjNraVl3M25nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAw
      bXMQChgBIAUogICAChoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5z
      IiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZB
      ZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1p
      bnMqBkFkbWlucxK9LwoLQ29uc29ydGl1bXMSrS8S4i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLI
      LhKxFwoPbWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1T
      UBKBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVUNVZmR0
      ekVNQjMzWDd3OUJ0R1dkNU04Qk9iVXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNR
      MGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURW
      UVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApj
      aTF1WlhRd0hoY05Nakl3T1RJNU1UTXlNREV6V2hjTk1qVXdOekU1TVRNeU1ERXpXakJrTVFzd0NR
      WURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFky
      Z3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRX
      WmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk1CZWNG
      S2V5djVYeWgrMzh0QzZMWWEzTkpLaWdKWEFObURiCnEvTnJjdXpDMmRaZXFjNzU5eEJXdFRJT3Ni
      czdnVnYxaGlndWc2QzEzbk8zUXpuanhTZWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0Rn
      WURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJUbEVyYTV2cFZpQTNYVwpBbjRRYVVsT1Vk
      QnorekFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBL3JsMHA1M3VpRTYxZnJ6STlEcmYxVzRNCkgw
      VEpqSjlVMVNxMEluTTMzNndDSURNSW5uQ0ZjS3RCSkRsZEtIVmdNTzM2L1BJT28rZzNpYlJlTkdS
      MzQ2cnoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVVL1ZBTC9FTGxvank0NkhybGViZ1J1WmJmTzR3Q2dZ
      SUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURF
      UE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERB
      YUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd09USTVNVE15TnpB
      d1doY05Nak13T1RJNU1UTXpNakF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFj
      VEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJ
      eEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZ
      RFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJ
      S29aSQp6ajBEQVFjRFFnQUVDZHNZUEZVbWJveW85MEhVZmE4dm41SHVtNmlGbFZvREZtQjFBdjR4
      TmdIOS9XSlIwOFZBCjkyM2IydGM4ZXJ1WmFKZ3VYK0tacUNIZHBzNGpEamhlZmFPQ0FTSXdnZ0Vl
      TUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNT
      RzAvWm5MdkNralg4K05hRVlrZkl5ZVlVc0RBZgpCZ05WSFNNRUdEQVdnQlRsRXJhNXZwVmlBM1hX
      QW40UWFVbE9VZEJ6K3pBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAzWTJRM1ptUm1PVGMy
      TFdRMGFHUmlNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWww
      SWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9p
      YldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVk
      V1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9Q
      UVFEQWdOSEFEQkUKQWlCUHM5T3JHMy84Vmd5TzI2ZTlqZW1TZi9hT2p4M2ZmYis1b0tkclg4dzNU
      d0lnTlkxY0VEZHFRSXBHeS9hSgpQZHFaRGVjbERIWWRYRTJzSkxISytubVd1R3c9Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVUNVZmR0ekVNQjMzWDd3OUJ0R1dkNU04Qk9iVXdD
      Z1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGph
      REVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhI
      REFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3T1RJNU1UTXlN
      REV6V2hjTk1qVXdOekU1TVRNeU1ERXpXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVD
      QXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1Z
      V04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpC
      eXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk1CZWNGS2V5djVYeWgrMzh0QzZMWWEzTkpLaWdK
      WEFObURiCnEvTnJjdXpDMmRaZXFjNzU5eEJXdFRJT3NiczdnVnYxaGlndWc2QzEzbk8zUXpuanhT
      ZWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0Ex
      VWREZ1FXQkJUbEVyYTV2cFZpQTNYVwpBbjRRYVVsT1VkQnorekFLQmdncWhrak9QUVFEQWdOSUFE
      QkZBaUVBL3JsMHA1M3VpRTYxZnJ6STlEcmYxVzRNCkgwVEpqSjlVMVNxMEluTTMzNndDSURNSW5u
      Q0ZjS3RCSkRsZEtIVmdNTzM2L1BJT28rZzNpYlJlTkdSMzQ2cnoKLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQoaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFj
      dHVyZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoP
      bWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEK
      D21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIR
      Cg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zErYWCgpjYXJyaWVyTVNQEqcWGsMUCgNN
      U1ASuxQSsBQSrRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      QitEQ0NBWjZnQXdJQkFnSVVReWtlTE5zZnpYd3d3MUl0K216T3VkZ3lXQWN3Q2dZSUtvWkl6ajBF
      QXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVF
      Qnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVq
      WVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBNU1qa3hNekl5TVROYUZ3MHlOVEEzTVRreE16SXlNVE5h
      TUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNN
      Qmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5
      Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRZUtLTUsrNzNC
      bzlJN1BIeUtpUjRtL0lWRlJpcDBuZVdTNjdJV2RDMEFJSTh5Q3RUZEYzTUJ4L1JndUltTApzNHkw
      RjNkWFN2NTBhenVlcEtpdmhONzdvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWRE
      d0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUxldThCcXA3dFl6amh6cXVNdGkrWlkyR2E3MHdD
      Z1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU1UQkk4d3ZFdDR0S01TT2JjV1B5Y0JON2M1UGs4V0xO
      cm50N2hSRkdvOE9BaUJ6ay9vKwo2L1EwTDFqMjhRM2hmQWJUUWZSNUZBMHFJc1I5aHBwSndTeUpF
      dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUM3akNDQXBTZ0F3SUJBZ0lVWS9Fd1pPMktjNmlWYlZIaDNCREhlTFhhKzMwd0NnWUlL
      b1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUURE
      QTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTVNamt4TXpJNU1EQmFGdzB5TXpBNU1qa3hN
      ek0wTURCYU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhN
      eTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVN
      QTRHQTFVRUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVQ0cUR0UE00WmVXT25rQWljdW9q
      NFoKR0NMdVNqeG9oaVNMZmtlSVQ3QmI5RXJObE1LbzlVUUhQVFhzVkFrbFQ3L3NiSG1ZdVlLK1VW
      VUVSQmZVS2NRaApvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93
      UUNNQUF3SFFZRFZSME9CQllFCkZDRVZIQXVwdGo2YUpjMVZIN0lEUDBjNkNWSHlNQjhHQTFVZEl3
      UVlNQmFBRkMzcnZBYXFlN1dNNDRjNnJqTFkKdm1XTmhtdTlNQ1FHQTFVZEVRUWRNQnVDR1dOaExY
      UnZiMnh6TFRaa05HTTJaamMyWkdZdE5Xd3lPWEF3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRI
      UnljeUk2ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFH
      WXVRV1ptYVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlq
      b2lRV1J0YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZ
      SQpLb1pJemowRUF3SURTQUF3UlFJaEFKYU1adTZEbnhsNHJneklxd3lLNHlObnJlSVFBTEJXaTRh
      ZHFKendlUVlqCkFpQlZNTk1TWGlreE51dlpKMUhYR1RVMEdlRTFqL2xkMjFGbGV6WVkxYmhWbUE9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVReWtlTE5zZnpYd3d3MUl0K216
      T3VkZ3lXQWN3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBNU1qa3hNekl5TVRO
      YUZ3MHlOVEEzTVRreE16SXlNVE5hTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFa
      TWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVY
      Ck1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pP
      UFFNQkJ3TkMKQUFRZUtLTUsrNzNCbzlJN1BIeUtpUjRtL0lWRlJpcDBuZVdTNjdJV2RDMEFJSTh5
      Q3RUZEYzTUJ4L1JndUltTApzNHkwRjNkWFN2NTBhenVlcEtpdmhONzdvMEl3UURBUEJnTlZIUk1C
      QWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUxldThCcXA3
      dFl6amh6cXVNdGkrWlkyR2E3MHdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU1UQkk4d3ZFdDR0
      S01TT2JjV1B5Y0JON2M1UGs4V0xOcm50N2hSRkdvOE9BaUJ6ay9vKwo2L1EwTDFqMjhRM2hmQWJU
      UWZSNUZBMHFJc1I5aHBwSndTeUpFdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0
      CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtF
      bmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdS
      ZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMa
      QAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJl
      ci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoX
      L0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hp
      bmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0
      dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5z
      dXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0
      aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoG
      QWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
