apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIOFruMRvGJtagFQE8o9Kyf/5GNCbeER4/cKg7xUUczRAEqZeCqNeCqBeCngKWggBEAEaBgiB
      j/mWBiIKc3lzY2hhbm5lbCpAZDQ1MjY5N2I3M2E2OTJhOTU3YzI2ZGE0MWM2MjY5OWM1YjFiM2Q3
      ZjMwNmQ2NzM1NWEzNjZkZDQ5YjNiNWJhYxIaEhieS1hQ1s8k/BLCxfOxEw9dVqI7BFEUdzQSo10K
      oF0SnV0SuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcK
      D21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVOaEVFWU0wMzlD
      eTBOOURXbHp6VWs4ck1RZll3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpJd056STFNRGN4T1RVM1doY05NalV3TlRFME1EY3hPVFUzV2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJDb1o5dzJ1WG93
      ZlVpWCtXM3RpU2JpUE9OSEZnZGF3ZVpjZAo3YnFuaHFnUFdOcGt1N0lZWkVqSFhFOVRpRWs4UjdX
      T2pITkJscnFKdlZlVFViRHkyczJqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWF0MmZJN2s1N3JpbXoKUUpRdG1abmFhc1orcVRB
      S0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQWk5ajNJNWpOVlo4cG5lTmVCTXl3aEJpNApmMG5XZ2pv
      cnI0TkFxWFJEWTRBQ0lBaFJwSGdhWVR5d3hsM0MxSVh3SSttKzkrTVZ5aktaNHc3VEdRNzFsbk9C
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURFRENDQXJlZ0F3SUJBZ0lVQzdjRzYxR3FxQmE0dDYxZXFlL2N0OG9jVEdzd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekkxTURjeU56QXdXaGNO
      TWpNd056STFNRGN6TWpBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEz
      TGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFN
      QmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFE
      REJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkK
      emowREFRY0RRZ0FFb3FNZlk5RitrWHpEbFhRcXNUY3ZSL29lQVpCUEplQXVmS09CS1IvbkxDZ3pZ
      YnAvNEwvMgpodFhFcUJ1SzdjZzB3SzJhbkc0Qm5zYzVGSEVhamx6TGlxT0NBU0l3Z2dFZU1BNEdB
      MVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUdHBTeXpv
      aWRYaUtmZkpYY1FCSUc5SE1vM0JqQWYKQmdOVkhTTUVHREFXZ0JRYXQyZkk3azU3cmltelFKUXRt
      Wm5hYXNaK3FUQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1kyUTNabVJtT1RjMkxYWjJP
      V3c1TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVk
      V1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZ
      M1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TkhBREJFCkFpQkVOZStrTGNldWFjbFBkQW0wMCtPY0VOMkRZejErOTkyQXZIYWcyM0Uxa2dJZ1RM
      aVNCeWlWaDlPSXBYSXkKaTZ1SHE1VnIzUW5Fb0pKa3RFYnpleVJuMWQwPQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVOaEVFWU0wMzlDeTBOOURXbHp6VWs4ck1RZll3Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056STFNRGN4T1RVM1do
      Y05NalV3TlRFME1EY3hPVFUzV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1du
      VnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRY
      SmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NN
      NDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJDb1o5dzJ1WG93ZlVpWCtXM3RpU2JpUE9OSEZnZGF3ZVpj
      ZAo3YnFuaHFnUFdOcGt1N0lZWkVqSFhFOVRpRWs4UjdXT2pITkJscnFKdlZlVFViRHkyczJqUWpC
      QU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdR
      V0JCUWF0MmZJN2s1N3JpbXoKUUpRdG1abmFhc1orcVRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlF
      QWk5ajNJNWpOVlo4cG5lTmVCTXl3aEJpNApmMG5XZ2pvcnI0TkFxWFJEWTRBQ0lBaFJwSGdhWVR5
      d3hsM0MxSVh3SSttKzkrTVZ5aktaNHc3VEdRNzFsbk9CCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJl
      ck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVy
      ZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcU
      EqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrREND
      QVo2Z0F3SUJBZ0lVZjRuMzIzUWwrRzJZYW5wWWlPc1FyanBZaXMwd0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck1qQTNNalV3TnpJeE5UWmFGdzB5TlRBMU1UUXdOekl4TlRaYU1Gb3hD
      ekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZi
      bVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVG9zaW9CcTUrR2dNdmVV
      NlRFcytlYjVWN3pFTTZhN1V0ZkVXRmVtczd3TlpUb21hajV3UzRwVjYxeVBKZGoKUTdqQ0Joa3lG
      QjJnMzNacTc1L2dub0ZObzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgov
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVV5bUp6RWMzMHBkcWdrTXAvQ2JWelYvWk01bmt3Q2dZSUtv
      Wkl6ajBFCkF3SURTQUF3UlFJaEFQK0ljMUVoS3FZOTllM3hpd1A3dVdRM2RGRFpPclJDUjFtZjRa
      M2paWkN4QWlBckV1c1gKelZoYUxabVNtN3FzTFNyR3ZmazVWU3hCWlhTbnJHd2hMU1VEWWc9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlDN1RDQ0FwU2dBd0lCQWdJVWRUUGU2Vis5SzJ6UVBoU25uTzE4US81RWVKa3dDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNakEzTWpVd056STVNREJhRncweU16QTNNalV3TnpNME1E
      QmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIy
      NWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0Ex
      VUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUUE93cmpINk5pb24xWXlRSzdiRm5rCkZY
      NW1sUElOL2pXQXp5WTVpMXBvdWVWSVpNd0dJRml6TW05SkFCVWVUZitxdXBOMTBKWERoaEFaQmdH
      MEJKVFkKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFB
      d0hRWURWUjBPQkJZRQpGUElzVEdIK0hMcmZvK3BIaGpHcTlObFRIaXNTTUI4R0ExVWRJd1FZTUJh
      QUZNcGljeEhOOUtYYW9KREtmd20xCmMxZjJUT1o1TUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4
      ekxUWmtOR00yWmpjMlpHWXRZelZtZG5nd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdS
      dGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29a
      SXpqMEVBd0lEUndBd1JBSWdWSkdVMyszSTU3ODBIWjNGVURtK2NlTHZXSEYyRTZDRkRoYmcrenF5
      L2NnQwpJRGdleUgrMnRXRmpqQnNkU2VTYllRd1pNaW1RMlZGcUxpWStsODI5TldVZQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVmNG4zMjNRbCtHMllhbnBZaU9zUXJqcFlpczB3
      Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlE
      VlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01qVXdOekl4TlRaYUZ3MHlOVEEx
      TVRRd056SXhOVFphTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4
      RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVF
      QXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMK
      QUFUb3Npb0JxNStHZ012ZVU2VEVzK2ViNVY3ekVNNmE3VXRmRVdGZW1zN3dOWlRvbWFqNXdTNHBW
      NjF5UEpkagpRN2pDQmhreUZCMmczM1pxNzUvZ25vRk5vMEl3UURBUEJnTlZIUk1CQWY4RUJUQURB
      UUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXltSnpFYzMwcGRxZ2tNcC9D
      YlZ6Vi9aTTVua3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQVArSWMxRWhLcVk5OWUzeGl3UDd1
      V1EzZEZEWk9yUkNSMW1mNFozalpaQ3hBaUFyRXVzWAp6VmhhTFptU203cXNMU3JHdmZrNVZTeEJa
      WFNuckd3aExTVURZZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoGQWRt
      aW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3Jz
      ZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5l
      bENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMq
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zEpsrCgdPcmRlcmVyEo8rEtIW
      Cg5zdXBwbHljaGFpbk1TUBK/FhrLFAoDTVNQEsMUErgUErUUCg5zdXBwbHljaGFpbk1TUBL1BS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVVVsZ3R0REt1WHlL
      OXpxUUhKdzcwZGRodUM4UXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJ
      d056STFNRGN4TnpVMFdoY05NalV3TlRFME1EY3hOelUwV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQ
      Ck1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9N
      QjA5eVpHVnkKWlhJeEd6QVpCZ05WQkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1H
      QnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCRE5YUzJtZjVWVjhEUmdDcm9naGI3OGZZMHdX
      bWk5aWJBUkU2QmxzSHlRWmxBYUYyVGVnCmY5OFR1eVJMMHFSOFdtTGFzcG1PMklNNHltamsyN1RX
      NnlLalFqQkFNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBH
      QTFVZERnUVdCQlFFckErdlNuUElHL1Rsem9aZlIxaGR1OU5za0RBSwpCZ2dxaGtqT1BRUURBZ05K
      QURCR0FpRUExbTRHejRYdGl0K0FJZmNmc3JvZGFLMWlkVFE1Z2lKNStLTTNUc3p5CmorSUNJUUQy
      UzdyS0J1UUZQRkVOK3lOM3Z0c3hqYjBnemtWNVJFa1FBV3crQjlTRHFBPT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoioggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzRUQ0NBb2ln
      QXdJQkFnSVVJWm1YMmNVUHBPQzI2NUFUZEpWWVl5L3oweFV3Q2dZSUtvWkl6ajBFQXdJdwpYakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGph
      R0ZwYmkxdVpYUXcKSGhjTk1qSXdOekkxTURjeU5qQXdXaGNOTWpNd056STFNRGN6TVRBd1dqQnNN
      UXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVN
      UkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUTR3CkRBWURWUVFMRXdWaFpHMXBiakVlTUJ3R0ExVUVB
      d3dWUVdSdGFXNUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3cKRXdZSEtvWkl6ajBDQVFZSUtvWkl6
      ajBEQVFjRFFnQUVQU0RXU1hqaEVLaFRSK3MxRWFTc1JpSGJaNzNHSVI2MApiUUJkRC9neFVHYm1x
      MU5yWFY5Smp6SHFYb1VEaDRVdDhLTjlVdnNvalE4WXZIWVRHQW40VnFPQ0FSUXdnZ0VRCk1BNEdB
      MVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJVbUNNK2hV
      MUQKRUJmS0MwaUJJbFlJZXozcHJUQWZCZ05WSFNNRUdEQVdnQlFFckErdlNuUElHL1Rsem9aZlIx
      aGR1OU5za0RBawpCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAxTmpZM1l6WTNabVkzTFdab2Qz
      ZHVNSUdKQmdncUF3UUZCZ2NJCkFRUjlleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNu
      VmxJaXdpWVdSdGFXNGlPaUowY25WbElpd2kKYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpTENKb1pp
      NUZibkp2Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0J6ZFhCdwpiSGxqYUdGcGJpMXVaWFFpTENKb1pp
      NVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3ClJBSWdRYStuN0NtZGxT
      ejA5MGNHM2N0NGNVMCtudFRjdVgwdGJMdmRMMVRhRytRQ0lEb3ZPY0U2U29Fa2tuQUsKeGNpSWhB
      OTR3V2JsN2VGSkY2WkgzczJSWXMvWQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEy
      EgZTSEEyNTZK9QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0FUQ0NBYWFnQXdJQkFn
      SVVVbGd0dERLdVh5Szl6cVFISnc3MGRkaHVDOFF3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkx
      dVpYUXcKSGhjTk1qSXdOekkxTURjeE56VTBXaGNOTWpVd05URTBNRGN4TnpVMFdqQmVNUXN3Q1FZ
      RFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0
      eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVds
      dUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkROWFMybWY1VlY4RFJn
      Q3JvZ2hiNzhmWTB3V21pOWliQVJFNkJsc0h5UVpsQWFGMlRlZwpmOThUdXlSTDBxUjhXbUxhc3Bt
      TzJJTTR5bWprMjdUVzZ5S2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFI
      L0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJRRXJBK3ZTblBJRy9UbHpvWmZSMWhkdTlOc2tEQUsKQmdn
      cWhrak9QUVFEQWdOSkFEQkdBaUVBMW00R3o0WHRpdCtBSWZjZnNyb2RhSzFpZFRRNWdpSjUrS00z
      VHN6eQpqK0lDSVFEMlM3cktCdVFGUEZFTit5TjN2dHN4amIwZ3prVjVSRWtRQVd3K0I5U0RxQT09
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVhZGVycxIsEiIIARIeEggS
      BggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3JpdGVycxIsEiIIARIeEggS
      BggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIG
      CAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0VuZG9yc2VtZW50EiwSIggB
      Eh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNo
      U2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1p
      bnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoK
      CgZWMV80XzISABoGQWRtaW5zGooSCg1Db25zZW5zdXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJ
      EQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSURBekNDQXFtZ0F3SUJBZ0lVSktZd3owNzZKTTBMYXZHTlZYdTlNb1MvTmo0d0NnWUlL
      b1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUURE
      QkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJMU1EY3lOakF3V2hjTk1qTXdO
      ekkxTURjek1UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZM
      VEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZj
      bVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUklSL1N2Qkp4eXJXNlFNclVpbW1sRUpV
      SDAKZXJBQUJvTE1jUlcvQWtvdisxbEVaeUNLM2hic3FrbDJUY3FoYWttOGlrNnFPT2wvUlJLcFFo
      QjJaamVLbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0ND
      c0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JC
      UytNSFlNRWpzdGN1dFIrazlDN2IrM3IvMDcKekRBZkJnTlZIU01FR0RBV2dCUUVyQSt2U25QSUcv
      VGx6b1pmUjFoZHU5TnNrREEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFH
      RnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJB
      VUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJX
      NXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZ
      dQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBUDBFMDlz
      WWh2SEdlTjlZCllYaCtVYnc0K2FBTUpHcktyT2tQTG1RQ0swNE5BaUFoNTIxUjNHRDNiS0MzN3E1
      bWtXdmZ5cjIxQzJDS1hTNHgKUnJjb3g1SVdFdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      ItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQXFtZ0F3SUJBZ0lVSktZd3ow
      NzZKTTBMYXZHTlZYdTlNb1MvTmo0d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3Ckho
      Y05Nakl3TnpJMU1EY3lOakF3V2hjTk1qTXdOekkxTURjek1UQXdXakJ4TVFzd0NRWURWUVFHRXdK
      SFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdk
      UGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndO
      Q0FBUklSL1N2Qkp4eXJXNlFNclVpbW1sRUpVSDAKZXJBQUJvTE1jUlcvQWtvdisxbEVaeUNLM2hi
      c3FrbDJUY3FoYWttOGlrNnFPT2wvUlJLcFFoQjJaamVLbzRJQgpNRENDQVN3d0RnWURWUjBQQVFI
      L0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdO
      VkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUytNSFlNRWpzdGN1dFIrazlDN2IrM3IvMDcKekRB
      ZkJnTlZIU01FR0RBV2dCUUVyQSt2U25QSUcvVGx6b1pmUjFoZHU5TnNrREEvQmdOVkhSRUVPREEy
      Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZz
      YjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0Zt
      Wm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1
      YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJ
      S29aSXpqMEVBd0lEU0FBd1JRSWhBUDBFMDlzWWh2SEdlTjlZCllYaCtVYnc0K2FBTUpHcktyT2tQ
      TG1RQ0swNE5BaUFoNTIxUjNHRDNiS0MzN3E1bWtXdmZ5cjIxQzJDS1hTNHgKUnJjb3g1SVdFdz09
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9j
      a1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaJgoQSGFzaGluZ0Fs
      Z29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUS
      EBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBs
      eWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMS
      FhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
