apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIM5J7kp56dgumD2ID03kBO6p6iMI3zQ9H4r53kiiSd6xEqJeCp9eCpxeCngKWggBEAEaBgit
      3r+WBiIKc3lzY2hhbm5lbCpAMzM4NWJhYWNkZmE5MTY1YjRlMTZkMzg1NzdkY2YwYzA2YzQxNzNk
      MDk0ZjdkM2E3NzczNTk2NzlhNzk5NWUzZhIaEhhEJeQdOKqEWjtVzeVnGSpNdhjrjfOv7g8Sn10K
      nF0SmV0SvS8KC0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SyC4SsRcK
      D21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVBWENRWU8wMERp
      R1g4YUd1bFgwVjFBcnJJUDB3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpJd056RTBNVEF4TURVM1doY05NalV3TlRBek1UQXhNRFUzV2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLYmxydnRHd1dv
      cTZEdnJkaWZVMlMzd1AvOEgrYkJ5YksvMQpnRGM3WHpSek5yc0pGWFFtOHRhNWoxWHJYamxmeG5t
      enBNQXBKRzZ6Wk1KbE85bEJ3WCtqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU09KNkdOL21HOEJKdjEKVXk2M2xaS1EvQkdzQlRB
      S0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQWgyRjArWmJQa01vN0k0SkFReC9rSG4zYQo4VTRpbmZo
      enBmWEdFaVVVT2ZvQ0lCQi9kczV5R1FMamVQY2kxenFlZ0UxenlBaHU3TTY0VFRMK295Z0pnZVAv
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURFRENDQXJlZ0F3SUJBZ0lVRngwYVpYV24xci9BdnZpTjV6OTlFV0x2bXpBd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekUwTVRBeE9EQXdXaGNO
      TWpNd056RTBNVEF5TXpBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEz
      TGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFN
      QmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFE
      REJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkK
      emowREFRY0RRZ0FFREF4bThDdEZWcHlOK0U2aHVKaHRrM2ZkaFA5VTBFMENqdTZ4UUpwczBJUWg4
      azFPdThWaQozdVd2a2d5cjNjQTAxSlV5TTNqQXZmZFRxTUZWV3hYbXNhT0NBU0l3Z2dFZU1BNEdB
      MVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSUEpPeStT
      RWh3NzBVNS9OTGxoL2pGQ3BIMVNEQWYKQmdOVkhTTUVHREFXZ0JTT0o2R04vbUc4Qkp2MVV5NjNs
      WktRL0JHc0JUQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1kyUTNabVJtT1RjMkxXZzJZ
      bkJ1TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVk
      V1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZ
      M1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TkhBREJFCkFpQU1CaTkvNzdlZlJEQ05NRDNhWms5YzJBYU9LUW10bFFOaUVNam1kSTNabVFJZ1A3
      aWtIYkhZa1hwN0VsZ0EKMzRiK1RLSFJJVkVHbFJmcmdnVTl4dVNVSXkwPQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVBWENRWU8wMERpR1g4YUd1bFgwVjFBcnJJUDB3Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056RTBNVEF4TURVM1do
      Y05NalV3TlRBek1UQXhNRFUzV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1du
      VnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRY
      SmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NN
      NDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLYmxydnRHd1dvcTZEdnJkaWZVMlMzd1AvOEgrYkJ5Yksv
      MQpnRGM3WHpSek5yc0pGWFFtOHRhNWoxWHJYamxmeG5tenBNQXBKRzZ6Wk1KbE85bEJ3WCtqUWpC
      QU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdR
      V0JCU09KNkdOL21HOEJKdjEKVXk2M2xaS1EvQkdzQlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlF
      QWgyRjArWmJQa01vN0k0SkFReC9rSG4zYQo4VTRpbmZoenBmWEdFaVVVT2ZvQ0lCQi9kczV5R1FM
      amVQY2kxenFlZ0UxenlBaHU3TTY0VFRMK295Z0pnZVAvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJl
      ck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVy
      ZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxK2FgoKY2Fycmllck1TUBKnFhrDFAoDTVNQErsU
      ErAUEq0UCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrVEND
      QVo2Z0F3SUJBZ0lVSDAwK2xCK20raUd3NjVySmJTVVJGdFIrbVdBd0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck1qQTNNVFF4TURFek1EQmFGdzB5TlRBMU1ETXhNREV6TURCYU1Gb3hD
      ekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZi
      bVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUWxDS1hhY0U5TWRJTVFt
      c1luMEZmNjVPdDRQVVduYzBicXpWenYxLzBIY0psbkV3NkY2V2d4Ry8wc3Y0V3AKMHFLR0tlWXFk
      TTdQb09nOXlxSUhDUnZjbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgov
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVuZk1hMkNhZldBc0Nadmg5cWN1VmZrMjNmdmt3Q2dZSUtv
      Wkl6ajBFCkF3SURTUUF3UmdJaEFLbVQ2UUZ2RFhzcVlsWnRqSEhiY29zUFhUazhxQXdiS05HcjlF
      SzcrQ2dwQWlFQXZ1ckMKU0tlVDlub0dFZVl0bTBneUFnRGR4YUVWMTY4Ny9PSWR2blVyTTBjPQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlDN2pDQ0FwU2dBd0lCQWdJVVJ6VjlMYUwzVFNrbXBvc3A3K2pFcXZ6YWRqa3dDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNakEzTVRReE1ESXdNREJhRncweU16QTNNVFF4TURJMU1E
      QmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIy
      NWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0Ex
      VUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVXlqTU11ZTRpcGZQY2ozaTVIZG9DCjkx
      N0gwVW5zWXp1WXFJYkw2TTdyNmRDd1psU01yc3ZVYVF0NUg1dGtIUWJxT1lNVEt0MnhyczFxT1NM
      RXgvUWoKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFB
      d0hRWURWUjBPQkJZRQpGTE45Z3JCNy9mWE9ld2R3UTZMaEg4KzlQZWlPTUI4R0ExVWRJd1FZTUJh
      QUZKM3pHdGdtbjFnTEFtYjRmYW5MCmxYNU50Mzc1TUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4
      ekxUWmtOR00yWmpjMlpHWXRabU55T1Rjd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdS
      dGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29a
      SXpqMEVBd0lEU0FBd1JRSWhBUG0ySVJTYlNIQ1VEbGFUUXl6d2NkdEFHU1I4YlcrSEZPREtBYUdO
      NkFNUApBaUE5WGV5Tk9yMTVZTy9rT3BVa0x5YWpWQzhnNDB0ckhBaVN3TnhTVlk3ZWRRPT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSUIrVENDQVo2Z0F3SUJBZ0lVSDAwK2xCK20raUd3NjVySmJTVVJGdFIr
      bVdBd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2
      Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3
      RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNVFF4TURFek1EQmFGdzB5
      TlRBMU1ETXhNREV6TURCYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVr
      YjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVH
      QTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJC
      d05DCkFBUWxDS1hhY0U5TWRJTVFtc1luMEZmNjVPdDRQVVduYzBicXpWenYxLzBIY0psbkV3NkY2
      V2d4Ry8wc3Y0V3AKMHFLR0tlWXFkTTdQb09nOXlxSUhDUnZjbzBJd1FEQVBCZ05WSFJNQkFmOEVC
      VEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVuZk1hMkNhZldBc0Na
      dmg5cWN1VmZrMjNmdmt3Q2dZSUtvWkl6ajBFCkF3SURTUUF3UmdJaEFLbVQ2UUZ2RFhzcVlsWnRq
      SEhiY29zUFhUazhxQXdiS05HcjlFSzcrQ2dwQWlFQXZ1ckMKU0tlVDlub0dFZVl0bTBneUFnRGR4
      YUVWMTY4Ny9PSWR2blVyTTBjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjQK
      BkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0Vu
      ZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1Jl
      YWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNo
      YW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFu
      bmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxKTKwoHT3JkZXJlchKH
      KxLKFgoOc3VwcGx5Y2hhaW5NU1AStxYawxQKA01TUBK7FBKwFBKtFAoOc3VwcGx5Y2hhaW5NU1AS
      8QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0FEQ0NBYWFnQXdJQkFnSVVIRU9WZnRy
      dUdCR2xBcy91K1RoOGRuc3Y2LzR3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhj
      Tk1qSXdOekUwTVRBd09EVTFXaGNOTWpVd05UQXpNVEF3T0RVMVdqQmVNUXN3Q1FZRFZRUUdFd0pI
      UWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05W
      QkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJa
      TUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQk5CVzI5SmJ6c2pPSk4vdlI1dGp5dmxS
      WEdZZyt0M0g0OTZ1L094QUtPcnl6UTBjbEhaVAoydFM1d3grZWNYOEpyaDdES1ZzNk55NUJHYnZS
      UUs0Rm50K2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dt
      TUIwR0ExVWREZ1FXQkJTeFN5UEF2SDc1Q2k4YTFrK2hGZDBET0lEY1VqQUsKQmdncWhrak9QUVFE
      QWdOSUFEQkZBaUVBcFFSTG1McW4zbi9qcjdmTnZOdENIUEdXekZrT0ZPejJrazdDd2FNUwpkWFVD
      SUNrTXVCc3VPaHBlQlByaVRqYXFZU3VRbjJZZGxLUmZsTGZZUmQ1cHVDSmsKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoioggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzRUQ0NBb2Vn
      QXdJQkFnSVRNN0lCNXd1MFdqcXZYVm1VT1ZoUVFhOUdnREFLQmdncWhrak9QUVFEQWpCZQpNUXN3
      Q1FZRFZRUUdFd0pIUWpFUE1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWti
      MjR4CkVEQU9CZ05WQkFvTUIwOXlaR1Z5WlhJeEd6QVpCZ05WQkFNTUVtTmhMbk4xY0hCc2VXTm9Z
      V2x1TFc1bGREQWUKRncweU1qQTNNVFF4TURFM01EQmFGdzB5TXpBM01UUXhNREl5TURCYU1Hd3hD
      ekFKQmdOVkJBWVRBa2RDTVJzdwpHUVlEVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhF
      REFPQmdOVkJBb1RCMDl5WkdWeVpYSXhEakFNCkJnTlZCQXNUQldGa2JXbHVNUjR3SEFZRFZRUURE
      QlZCWkcxcGJrQnpkWEJ3YkhsamFHRnBiaTF1WlhRd1dUQVQKQmdjcWhrak9QUUlCQmdncWhrak9Q
      UU1CQndOQ0FBUU53WFB4dTBSQjVFQnZqbUhrVjZSNEtOckVPemJ1L2pHegpHakF4WnZQU2VNWDVq
      WDdnRjJyU3Y3ZzRJNlh2UFpteTZ1WlB0TytJSnFaK2FGWHhaT2VobzRJQkZEQ0NBUkF3CkRnWURW
      UjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGTWdlWHEzNDc3
      VXMKVEJBdkhnb3BQb3dibUNReU1COEdBMVVkSXdRWU1CYUFGTEZMSThDOGZ2a0tMeHJXVDZFVjNR
      TTRnTnhTTUNRRwpBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFUyTmpkak5qZG1aamN0YTNKNmEy
      WXdnWWtHQ0NvREJBVUdCd2dCCkJIMTdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRX
      VWlMQ0poWkcxcGJpSTZJblJ5ZFdVaUxDSm8KWmk1QlptWnBiR2xoZEdsdmJpSTZJaUlzSW1obUxr
      VnVjbTlzYkcxbGJuUkpSQ0k2SWtGa2JXbHVRSE4xY0hCcwplV05vWVdsdUxXNWxkQ0lzSW1obUxs
      UjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGCkFpRUEzanZyb0RBMlBG
      TTNyTXRNWkFWaFh1ZTJublVtNkRGY3lKcmRVbjRhazZVQ0lFU3BDMGtrWjFNNFdCK2IKaFEvWFZR
      Z1d5S2J1UHRVbC9hblVaUkhOOGR0TQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEy
      EgZTSEEyNTZK8QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0FEQ0NBYWFnQXdJQkFn
      SVVIRU9WZnRydUdCR2xBcy91K1RoOGRuc3Y2LzR3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkx
      dVpYUXcKSGhjTk1qSXdOekUwTVRBd09EVTFXaGNOTWpVd05UQXpNVEF3T0RVMVdqQmVNUXN3Q1FZ
      RFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0
      eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVds
      dUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQk5CVzI5SmJ6c2pPSk4v
      dlI1dGp5dmxSWEdZZyt0M0g0OTZ1L094QUtPcnl6UTBjbEhaVAoydFM1d3grZWNYOEpyaDdES1Zz
      Nk55NUJHYnZSUUs0Rm50K2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFI
      L0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTeFN5UEF2SDc1Q2k4YTFrK2hGZDBET0lEY1VqQUsKQmdn
      cWhrak9QUVFEQWdOSUFEQkZBaUVBcFFSTG1McW4zbi9qcjdmTnZOdENIUEdXekZrT0ZPejJrazdD
      d2FNUwpkWFVDSUNrTXVCc3VPaHBlQlByaVRqYXFZU3VRbjJZZGxLUmZsTGZZUmQ1cHVDSmsKLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI7CgtFbmRvcnNlbWVudBIsEiIIARIeEggS
      BggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHUmVhZGVycxIsEiIIARIeEggS
      BggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3JpdGVycxIsEiIIARIeEggS
      BggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIG
      CAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zKgZBZG1pbnMaihIKDUNvbnNlbnN1
      c1R5cGUS+BES7REKCGV0Y2RyYWZ0EuARCskRChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijca
      0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVOeEZ1bExq
      ejhOVGxEUXlmREV2WnRmdDR4QTh3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhj
      Tk1qSXdOekUwTVRBeE56QXdXaGNOTWpNd056RTBNVEF5TWpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pI
      UWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQ
      Y21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5
      TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05D
      QUFSb1NheUFKZnVNd0kxQ1kzNG9mN2ZzRGRLQQo3YWd4cHJJWlk0dUhFT1VLTjVKbTdtRklmMmNv
      QnB3TWlMV09hOE1MOE0xcDJWTEt1RWh3L0FwTDZGQjNvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgv
      QkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05W
      SFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUaS9iYnJTWlBqWlNpb0VkaDJNWGVleER4aApMakFm
      QmdOVkhTTUVHREFXZ0JTeFN5UEF2SDc1Q2k4YTFrK2hGZDBET0lEY1VqQS9CZ05WSFJFRU9EQTJn
      aGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNi
      M0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1a
      bWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVj
      M1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlL
      b1pJemowRUF3SURTQUF3UlFJaEFNQXFpRkZCR2lBdmJ6WU0KdUR0MFFQMHNUSzlIbmh1NWkvWGsw
      UkRTSW1sTUFpQjVyVGVsTVNBZHQvZ0RnSDFWbWMzV0I5L2pGSHhPOW91UApIZkhWcVc1eHdBPT0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJREF6Q0NBcW1nQXdJQkFnSVVOeEZ1bExqejhOVGxEUXlmREV2WnRmdDR4QTh3Q2dZSUtvWkl6
      ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZ
      UzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekUwTVRBeE56QXdXaGNOTWpNd056RTBN
      VEF5TWpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVN
      VE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxj
      bVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSb1NheUFKZnVNd0kxQ1kzNG9mN2ZzRGRLQQo3
      YWd4cHJJWlk0dUhFT1VLTjVKbTdtRklmMmNvQnB3TWlMV09hOE1MOE0xcDJWTEt1RWh3L0FwTDZG
      QjNvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FR
      VUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUaS9i
      YnJTWlBqWlNpb0VkaDJNWGVleER4aApMakFmQmdOVkhTTUVHREFXZ0JTeFN5UEF2SDc1Q2k4YTFr
      K2hGZDBET0lEY1VqQS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJp
      MXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3
      Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIy
      eHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZI
      bHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFNQXFpRkZCR2lB
      dmJ6WU0KdUR0MFFQMHNUSzlIbmh1NWkvWGswUkRTSW1sTUFpQjVyVGVsTVNBZHQvZ0RnSDFWbWMz
      V0I5L2pGSHhPOW91UApIZkhWcVc1eHdBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoF
      NTAwbXMQChgBIAUogICAChoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRt
      aW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9u
      cxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFkbWlucxomChBIYXNoaW5nQWxnb3Jp
      dGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI
      /////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwK
      CgoGVjFfNF8zEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
