apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://34.83.218.105:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: supplychain-net

    genesis: |-
      CiIaIOpqJxe5A/1Ony5qj6Lcc3ldZ5NHVGuWG2Euum9x0uwWEqReCqFeCp5eCngKWggBEAEaBgiK
      5+ucBiIKc3lzY2hhbm5lbCpAYjNhMzI1MDg2ZTkwZTY0N2IyODEyZDVmMTYyOGE3YzVhMjRjZGVk
      ZmZhNWJkZmQ3NTVhNjQxYmEyNmI5MTJiMBIaEhi7870UqXTtZoItAG1A5ncrPePQQX6ZIYkSoV0K
      nl0Sm10Swy8KC0NvbnNvcnRpdW1zErMvEuguChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0Szi4SshYK
      CmNhcnJpZXJNU1ASoxYavxQKA01TUBK3FBKsFBKpFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVBiS2paVFJSNE9UN2ttN2hUdHNV
      c3JBd1ZIRXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdN
      Qmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5
      TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV5TVRVeE1EQXdOVGhh
      RncweU5URXdNRFF4TURBd05UaGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpN
      YjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgK
      TUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9Q
      UU1CQndOQwpBQVNWeDJYMGZNZHIvaXFOMmVkUVRVWnY2RUlmZU9KWlJzcVV4T05zUDRpdUs4aThq
      STJ6T1RoY1RkbXpScWpxCkE5OXVwY1paT0ZmVFlKSnRBTzY5UkpsMm8wSXdRREFQQmdOVkhSTUJB
      ZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVZWlXTmc0SDBh
      dCtkY2R2UmxjRjZiMGxKZDFZd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBUFdDTkI5NjFIVFlF
      d3lMN3pZaFpGSitta0pJWVV6a2YvOFAxRkVpYWRvNUFpQUY2VHhjCjJlOVl2WEQ0bEd4LzFsdWlH
      SUpmYnE2STRCVG5iU2w3MnBMaFN3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdUQ0NBcFNnQXdJQkFnSVVhMlBwcStPcTh0azNv
      N1RCc08rOWJjMGxFRVl3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5C
      Z05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZ
      WEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1UVXhN
      REE1TURCYUZ3MHlNekV5TVRVeE1ERTBNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApW
      UVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhq
      QU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFX
      UnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FB
      U3FIZmhxRmRDbXZWWkNmZnFET2d6Vgo2T2tPdW41cEQ0L1FGVGR4VU04dklwWWluYjhmdnMxS3ho
      M2pHcDNlVk1OSWExa3JPUGtkUm5vdHY3M0tYcHRHCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JB
      UURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRkdMdXAwRVVIdU1UN0xkbjR1
      R0k5VGNyWTV0dE1COEdBMVVkSXdRWU1CYUFGSG9sallPQjlHcmZuWEhiMFpYQgplbTlKU1hkV01D
      UUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFUwTkdJMFl6ZGlObVF0Tm5nNWMzRXdnWTBHCkND
      b0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdS
      dGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZ
      dVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhC
      bElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnQWpNalRGbVpCSGFLeG4r
      MFh1L25RTHF2M3VCK01xaWhndEtRQk9IN29qQUMKSUF5cThKcTJuTTBSRWJ0WUQxcWswbW5GR3c0
      RW9WNDNlTlNVYUdrR1Z6Z0MKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hB
      MjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVUGJL
      alpUUlI0T1Q3a203aFR0c1VzckF3VkhFd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhN
      Q1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZ
      RFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5
      Ck1qRXlNVFV4TURBd05UaGFGdzB5TlRFd01EUXhNREF3TlRoYU1Gb3hDekFKQmdOVkJBWVRBa2RD
      TVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVF
      Q2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2Nx
      aGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU1Z4MlgwZk1kci9pcU4yZWRRVFVadjZFSWZlT0pa
      UnNxVXhPTnNQNGl1SzhpOGpJMnpPVGhjVGRtelJxanEKQTk5dXBjWlpPRmZUWUpKdEFPNjlSSmwy
      bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05W
      SFE0RUZnUVVlaVdOZzRIMGF0K2RjZHZSbGNGNmIwbEpkMVl3Q2dZSUtvWkl6ajBFCkF3SURTQUF3
      UlFJaEFQV0NOQjk2MUhUWUV3eUw3elloWkZKK21rSklZVXprZi84UDFGRWlhZG81QWlBRjZUeGMK
      MmU5WXZYRDRsR3gvMWx1aUdJSmZicTZJNEJUbmJTbDcycExoU3c9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tChoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoK
      Y2Fycmllck1TUBoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJy
      aWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJN
      U1AaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEa
      BkFkbWlucyoGQWRtaW5zErsXCg9tYW51ZmFjdHVyZXJNU1ASpxcarxUKA01TUBKnFRKcFRKZFQoP
      bWFudWZhY3R1cmVyTVNQEoYGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEVENDQWJL
      Z0F3SUJBZ0lVVlRoSTMyMHRtbmo2di9HdWNmeDhhbkhaQnBJd0NnWUlLb1pJemowRUF3SXcKWkRF
      TE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5
      YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFo
      Ym5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakUxTURrMU9UVXhXaGNOTWpVeE1EQTBNRGsx
      T1RVeFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlE
      VlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVF
      QXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5
      QXdFSEEwSUFCQnhXbFRiRlNXQ3BNd0VON1gvMWRoY2RuQ1Z5SzlveUYxNC8KRlljdWNuMjdQQUl0
      cWxIMDBVUzhtSmFsaEJZUXRYUnNJVGVZc1VFZy9aaTJsTzhnNDdPalFqQkFNQThHQTFVZApFd0VC
      L3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRFK3gzaHNnRlcz
      S1luCkJyYjNwaVpqTWVRamlUQUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUEvb0cvdzZUdU9ZOFBx
      Zy8rdkhuYmp1V2gKeTlzL3ZUM0o2YmR2M251K1l5OENJUURBSkZNemwwamcvUDQyR2ZMc2JkZit1
      Ym9jaWprY3AvcldENG9RNjNCNgpEZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0t
      LS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQXJlZ0F3SUJBZ0lVVTFVZjcvSjRoSEov
      aGtXYW5PRHpvS2o5UXowd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFO
      QmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhO
      WVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3
      SGhjTk1qSXhNakUxTVRBd056QXdXaGNOTWpNeE1qRTFNVEF4TWpBd1dqQ0JoakVMTUFrR0ExVUUK
      QmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtF
      d3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVk
      V1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBN
      Rmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemowREFRY0RRZ0FFd0tLL1R5NGgzVjJqRDI4QTF1eVNt
      UGExQWRtYi9tVWFNdGFET0xWQzFPamV4OUk2M2taKwpscFBYenhycERtYjdjUHB6TE1iSWNqaUtC
      cStrM3lhSGE2T0NBU0l3Z2dFZU1BNEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVB
      akFBTUIwR0ExVWREZ1FXQkJRWjdHNkFDTVE0NFE4NDFFUVpuU0lUUElIM0JUQWYKQmdOVkhTTUVH
      REFXZ0JURSt4M2hzZ0ZXM0tZbkJyYjNwaVpqTWVRamlUQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApi
      MjlzY3kwM09XSm1OalZqTmprMExUbG1ZMmgyTUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNu
      TWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxr
      Rm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRF
      bEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpH
      MXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFCkFpQnAyUWNqWXFtaWwxT3J3aVNWSTRZZTA4
      djI4MFF3Tng2TDNnVVFsQ29IT3dJZ1pnNFhLQU8zYTNYQVd0WVgKOXlYVGZlUkVJWGE0VTNpQ2Nm
      WTRHdjIrcUZRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKhgYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVWVGhJMzIwdG1u
      ajZ2L0d1Y2Z4OGFuSFpCcEl3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpJeE1qRTFNRGsxT1RVeFdoY05NalV4TURBME1EazFPVFV4V2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCeFdsVGJGU1dD
      cE13RU43WC8xZGhjZG5DVnlLOW95RjE0LwpGWWN1Y24yN1BBSXRxbEgwMFVTOG1KYWxoQllRdFhS
      c0lUZVlzVUVnL1ppMmxPOGc0N09qUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVEUreDNoc2dGVzNLWW4KQnJiM3BpWmpNZVFqaVRB
      S0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQS9vRy93NlR1T1k4UHFnLyt2SG5ianVXaAp5OXMvdlQz
      SjZiZHYzbnUrWXk4Q0lRREFKRk16bDBqZy9QNDJHZkxzYmRmK3Vib2NpamtjcC9yV0Q0b1E2M0I2
      CkRnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAES
      IRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50
      Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVy
      cxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRl
      cnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5z
      GkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAa
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxKPKwoHT3Jk
      ZXJlchKDKxLOFgoOc3VwcGx5Y2hhaW5NU1ASuxYaxxQKA01TUBK/FBK0FBKxFAoOc3VwcGx5Y2hh
      aW5NU1AS8QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0FEQ0NBYWFnQXdJQkFnSVVG
      dDNOT1k3M1YwZ0ZEeEhpOUlnbFN2RDEzemd3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVC
      aE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdE
      Z1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpY
      UXcKSGhjTk1qSXhNakUxTURrMU9EUXlXaGNOTWpVeE1EQTBNRGsxT0RReVdqQmVNUXN3Q1FZRFZR
      UUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVE
      QU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxX
      NWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkR5T1hQWjhaOHFWNVpTaFRw
      N01KNWlvQ3R1K3NnWVQzc1VOUXRJbEk1RXp6alRZTHpHMgpjUmNBNSt2RWVBWTVQWVN1Z09SR3Zk
      dm43bDFsU3BtUkJqeWpRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJSTXZFRUZFTTRwUTFXalNuNmZCZlJRdEMzL0xEQUsKQmdncWhr
      ak9QUVFEQWdOSUFEQkZBaUJoa2dYZEpRUzFwSUZSMk9FUDBVclg5QTJGZytBTDFXRjVEUUFtcUU4
      TgpUZ0loQUptMXc4VTM1a0FENC9ZcGtoTS80dSs4OXBRTTRmcUlyMGNGTmN5enBWeUsKLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoipggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzRq
      Q0NBb2lnQXdJQkFnSVVkajNVWlpPUUNZeUJLT2F1RmtjYVJKcTZSOXN3Q2dZSUtvWkl6ajBFQXdJ
      dwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhC
      d2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXhNakUxTVRBd05UQXdXaGNOTWpNeE1qRTFNVEF4TURB
      d1dqQnNNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5
      dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUTR3CkRBWURWUVFMRXdWaFpHMXBiakVlTUJ3
      R0ExVUVBd3dWUVdSdGFXNUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3cKRXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBEQVFjRFFnQUU3TVUvc0M0Nkg2LzY4c0NJM0g0R2ViRmJ6SHFsclVheQpOai9hNFY3
      M2cvTExQandqZittU0MzWUw3UnMyV1FDWC9ieDEvenpNRlcyZXVKN3lkZG4zV2FPQ0FSUXdnZ0VR
      Ck1BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJO
      S2d3aGxEZTAKQmlMWWZxT3lvTHZ3Z2JiRFNEQWZCZ05WSFNNRUdEQVdnQlJNdkVFRkVNNHBRMVdq
      U242ZkJmUlF0QzMvTERBawpCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzTmpjMVpEWmtZemM1
      TFc1b1luSTNNSUdKQmdncUF3UUZCZ2NJCkFRUjlleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFp
      T2lKMGNuVmxJaXdpWVdSdGFXNGlPaUowY25WbElpd2kKYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlp
      TENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0J6ZFhCdwpiSGxqYUdGcGJpMXVaWFFp
      TENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3ClJRSWhBTU1Q
      S1V2VDM0aXd1bGhERm1GeFdIQUlpMTAxVmFrT3hXSVk5SjEwRHpNWEFpQWFDcml3ZzdXNjZJRTIK
      REdGaTJsMElsU2JTcFFiRmp1THFrSXVFWkhHcldnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVRnQzTk9ZNzNWMGdGRHhIaTlJZ2xTdkQxM3pnd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFMU1EazFPRFF5V2hjTk1qVXhNREEwTURrMU9EUXlX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJEeU9Y
      UFo4WjhxVjVaU2hUcDdNSjVpb0N0dStzZ1lUM3NVTlF0SWxJNUV6empUWUx6RzIKY1JjQTUrdkVl
      QVk1UFlTdWdPUkd2ZHZuN2wxbFNwbVJCanlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUk12RUVGRU00cFExV2pTbjZmQmZSUXRD
      My9MREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCaGtnWGRKUVMxcElGUjJPRVAwVXJYOUEyRmcr
      QUwxV0Y1RFFBbXFFOE4KVGdJaEFKbTF3OFUzNWtBRDQvWXBraE0vNHUrODlwUU00ZnFJcjBjRk5j
      eXpwVnlLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVhZGVycxIsEiII
      ARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3JpdGVycxIsEiII
      ARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRtaW5zEi4SJAgB
      EiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0VuZG9yc2VtZW50
      EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoGQWRtaW5zGh8K
      E0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFf
      NF8yEgAaBkFkbWlucxqCEgoNQ29uc2Vuc3VzVHlwZRLwERLlEQoIZXRjZHJhZnQS2BEKwREKGG9y
      ZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlEQVRDQ0FxZWdBd0lCQWdJVVEzTWc2STRxTVpjZ1NwSW1VRlBKMGZEeHYxa3dDZ1lJS29aSXpq
      MEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallT
      NXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1qRTFNVEF3TlRBd1doY05Nak14TWpFMU1U
      QXhNREF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1U
      TXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNt
      VnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJn
      Y3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJqSnM5SGxFUC93dURmc1ZvSUtmajZPdUErCldm
      RWp5UEhsa3pwcGVMaXFrbUtUT0ZES21oeUZOc05jRk5SZFRMamcwNVdwVEh4SGVkYVB2RkhYUWJB
      Z280SUIKTGpDQ0FTb3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFV
      RkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlExeEFP
      VlNFR3E1NXNtandSb3BrUHlTcXZRCjJEQWZCZ05WSFNNRUdEQVdnQlJNdkVFRkVNNHBRMVdqU242
      ZkJmUlF0QzMvTERBOUJnTlZIUkVFTmpBMGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkx
      dVpYU0NHRzl5WkdWeVpYSXhMbk4xY0hCc2VXTm9ZV2x1TFc1bApkREJzQmdncUF3UUZCZ2NJQVFS
      Z2V5SmhkSFJ5Y3lJNmV5Sm9aaTVCWm1acGJHbGhkR2x2YmlJNklpSXNJbWhtCkxrVnVjbTlzYkcx
      bGJuUkpSQ0k2SW05eVpHVnlaWEl4TG5OMWNIQnNlV05vWVdsdUxXNWxkQ0lzSW1obUxsUjUKY0dV
      aU9pSnZjbVJsY21WeUluMTlNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJUUNYbzY3VnVpSzBEMVBO
      NWhMUApnM3dzM1BaYTlYRVlweDRuSTFBbGptME4zZ0lnZjFmMndOeG1wR1N3VjFsQnlGcFhXWG5a
      c1JqMEkzZkpEUDJLCmczUi9WdGM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIs8ILS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQXFlZ0F3SUJBZ0lVUTNNZzZJNHFNWmNnU3BJ
      bVVGUEowZkR4djFrd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21S
      bGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpF
      MU1UQXdOVEF3V2hjTk1qTXhNakUxTVRBeE1EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJr
      R0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5
      TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUmpKczlI
      bEVQL3d1RGZzVm9JS2ZqNk91QSsKV2ZFanlQSGxrenBwZUxpcWttS1RPRkRLbWh5Rk5zTmNGTlJk
      VExqZzA1V3BUSHhIZWRhUHZGSFhRYkFnbzRJQgpMakNDQVNvd0RnWURWUjBQQVFIL0JBUURBZ09v
      TUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhF
      QWpBQU1CMEdBMVVkRGdRV0JCUTF4QU9WU0VHcTU1c21qd1JvcGtQeVNxdlEKMkRBZkJnTlZIU01F
      R0RBV2dCUk12RUVGRU00cFExV2pTbjZmQmZSUXRDMy9MREE5QmdOVkhSRUVOakEwZ2hodgpjbVJs
      Y21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dHOXlaR1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVM
      VzVsCmREQnNCZ2dxQXdRRkJnY0lBUVJnZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwYkdsaGRHbHZi
      aUk2SWlJc0ltaG0KTGtWdWNtOXNiRzFsYm5SSlJDSTZJbTl5WkdWeVpYSXhMbk4xY0hCc2VXTm9Z
      V2x1TFc1bGRDSXNJbWhtTGxSNQpjR1VpT2lKdmNtUmxjbVZ5SW4xOU1Bb0dDQ3FHU000OUJBTUNB
      MGdBTUVVQ0lRQ1hvNjdWdWlLMEQxUE41aExQCmczd3MzUFphOVhFWXB4NG5JMUFsam0wTjNnSWdm
      MWYyd054bXBHU3dWMWxCeUZwWFdYblpzUmowSTNmSkRQMksKZzNSL1Z0Yz0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICAChoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIV
      EgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tW
      YWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGk4KEE9yZGVyZXJBZGRy
      ZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJl
      ci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zGiYKEEhhc2hp
      bmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0
      dXJlEhASBgj/////DxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoH
      UmVhZGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
