apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIBlhdxOs2WPzGI8ndetx1JZe+MSV+A3pBRt26anuSvCLEqZeCqNeCqBeCngKWggBEAEaBgiM
      45yYBiIKc3lzY2hhbm5lbCpAMjg5ZWVlNjJlZTVjZWM5ZjJlMTEyMmZmNzQwYjMyY2Y2NDFiZWEy
      OTJmY2I5NWI2MTU5NDgxZmY4ZDZkOWVhORIaEhicff1NRWmVRMpuU6VE2NWYiT01sIC/BbcSo10K
      oF0SnV0SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVZUwvejYwY0FIZ1VrK0loN2lyLzBySVAwTVVRd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RJMU1EZ3dOak01V2hjTk1qVXdOakUwTURnd05qTTVX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJLUmp5
      ditlaVZEeXRlWFlxemI5OUhoTHpGTzQzMkQxclBzZHZXTzNBT1NhL1B5alREdnAKUkJDRjRUVEo4
      Y2VER0lMU1RwT1B1VnNETVNTTkxIZmlQa2FqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVEo1RCt3d05weXBnTVp6dkMrQ2dBNUJO
      OGVRekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBdzZac3hxWGdjUk5pTm84NHdieXEwQmtYd0wz
      dmI3d0prbi96elA0N2EKM3dJaEFOU1VkaXdad2h1MnpBalJsN1dXaWlvb21HNE9lWXFUN1ZmOENG
      MWlyemxDCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVTWVmOEcwQ2ZvczlnVUIxc082Q2x3UzREWllNd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RJMU1EZ3hOREF3V2hjTk1q
      TXdPREkxTURneE9UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFbzRZdm9EbUJ4MlFScUxzWlludEsrRUdLMUhk
      SHpaYjgKTHZINDJMeDZvRlRINTFLRlovNkNJVkRNQ05CMVkySkdCbTlHMmFiZWpLaVFKbWtESkdC
      aUNLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTZVhDK0JJZGg3CkxQaFcwKzhnanFCa3lDMEJ2VEFmQmdOVkhTTUVHREFXZ0JU
      SjVEK3d3TnB5cGdNWnp2QytDZ0E1Qk44ZVF6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xYWTJaREk0TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQVBHYnJqc0E1SDh3QktiNS95TC9QWTBqRllhS1V1MS90eDdxZUtaOG1LRFFBaUIv
      TE4zdlJlZCt1SEh3CjRzV2hWZGVuZ3I1UTgxUFVMN0FaZnNxcm5TTW9RUT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVWVML3o2MGNBSGdVaytJaDdpci8wcklQME1VUXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09ESTFNRGd3TmpNNVdoY05NalV3
      TmpFME1EZ3dOak01V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCS1JqeXYrZWlWRHl0ZVhZcXpiOTlIaEx6Rk80MzJEMXJQc2R2V08zQU9TYS9QeWpU
      RHZwClJCQ0Y0VFRKOGNlREdJTFNUcE9QdVZzRE1TU05MSGZpUGthalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRKNUQrd3dOcHlw
      Z01aenZDK0NnQTVCTjhlUXpBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQXc2WnN4cVhnY1JOaU5v
      ODR3YnlxMEJrWHdMM3ZiN3dKa24venpQNDdhCjN3SWhBTlNVZGl3WndodTJ6QWpSbDdXV2lpb29t
      RzRPZVlxVDdWZjhDRjFpcnpsQwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0
      cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlu
      cxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBs
      eWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdB
      d0lCQWdJVUo0UzNiL3dqa1pUVUNPeGk5dzYybTF1NURETXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpJd09ESTFNRGd4TkRBd1doY05Nak13T0RJMU1EZ3hPVEF3V2pCeE1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZR
      UURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkNBQVI0Ynp6ZzEyYTc2N1lKZ3owNWcyR2FYV0Z4CkNWdmhvTVlTdnZYYUlz
      QTdKbktSMzBRQnI4STU1cmlpdzVnS01QR2hDT2xXWlM2d2szcE9jcUY3RitWQm80SUIKTURDQ0FT
      d3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdF
      RgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNpZSt4RWxQQ3VqVmRWRmF3
      WjlCb3NtUW1aCkh6QWZCZ05WSFNNRUdEQVdnQlRKNUQrd3dOcHlwZ01aenZDK0NnQTVCTjhlUXpB
      L0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdW
      eVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhK
      eklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpv
      aWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdW
      eVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU1RU1JRVmtXeFdaZ2loZworRWdFNmR5
      TEtJU1JvM0FLWTEyYlF3dTlwejMyQWlBWC9UOTREeUVhN2ozam9RNzMvMzF0QmZ6b1lwd1NlR21r
      ClZQcFVpZ1A3Q1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVUo0UzNiL3dqa1pUVUNPeGk5dzYybTF1
      NURETXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJz
      d0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09ESTFNRGd4TkRB
      d1doY05Nak13T0RJMU1EZ3hPVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhN
      U05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZ
      RFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0Zw
      YmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVI0Ynp6ZzEyYTc2N1lK
      Z3owNWcyR2FYV0Z4CkNWdmhvTVlTdnZYYUlzQTdKbktSMzBRQnI4STU1cmlpdzVnS01QR2hDT2xX
      WlM2d2szcE9jcUY3RitWQm80SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVk
      SlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBH
      QTFVZERnUVdCQlNpZSt4RWxQQ3VqVmRWRmF3WjlCb3NtUW1aCkh6QWZCZ05WSFNNRUdEQVdnQlRK
      NUQrd3dOcHlwZ01aenZDK0NnQTVCTjhlUXpBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6
      ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0
      TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJ
      aXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRi
      bVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdS
      UUloQU1RU1JRVmtXeFdaZ2loZworRWdFNmR5TEtJU1JvM0FLWTEyYlF3dTlwejMyQWlBWC9UOTRE
      eUVhN2ozam9RNzMvMzF0QmZ6b1lwd1NlR21rClZQcFVpZ1A3Q1E9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgK
      EICAgDEYgIBAGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoG
      QWRtaW5zEr0vCgtDb25zb3J0aXVtcxKtLxLiLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsguErEX
      Cg9tYW51ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEG
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNDekNDQWJLZ0F3SUJBZ0lVZklQM2ZZUjVq
      akNYbDA3UXBta1VUVVVSTUk4d0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hE
      ekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtE
      QXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVa
      WFF3SGhjTk1qSXdPREkxTURnd09EUXhXaGNOTWpVd05qRTBNRGd3T0RReFdqQmtNUXN3Q1FZRFZR
      UUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZU
      QVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkz
      UjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTDhMTjVDNTNI
      YUFNQ1IvWUttYThhSE1SK0M4enZHNmtwZjMKMzhYSHlaZElCekhIVU1yMGRLd3c2c0tMTlhoN2Ja
      ZnVBUTJEdzNxdlh2MWl1ZGFHTG5palFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZS
      MFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJQS09SSU5tVlFzUExRCm5YMjhDU0VRaVBiNjRE
      QUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQWR4VzA4MXlkcnlsK2tPTkV5dC9lejhDU1IKREgyNFla
      Z1BGZXQxQXdCV0tnSWdEMy9GMXhaK1pLUW9JeUNYenlZYml3RlFteVJPMlNxZVdjY0RxRUYvSzdB
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlERURDQ0FyZWdBd0lCQWdJVVdOVUE1b0hneEY3NENLZWQzQWQ2STBVU01ya3dDZ1lJS29a
      SXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdO
      VkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3T0RJMU1EZ3hOakF3V2hj
      Tk1qTXdPREkxTURneU1UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRR
      M0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpB
      TUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFR
      RERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      CnpqMERBUWNEUWdBRU9WNUFmWmNFczFncE9xbXZsbFYvRW1sMk05R05UQTFiZkdOTkd3TENyUzFh
      Mlc0eUQ2ZE0KUHZnYVRWVTZsRVBZdlNkRFdRVmt2Y1RvNCtWaGMyUW55Nk9DQVNJd2dnRWVNQTRH
      QTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUW1BQ1Z3
      dzd5NUZNd0EwQlpzaUgzKzlTSTR3REFmCkJnTlZIU01FR0RBV2dCUlBLT1JJTm1WUXNQTFFuWDI4
      Q1NFUWlQYjY0REFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMVFIz
      ZUhoNE1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9p
      ZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1
      ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgK
      WTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURB
      Z05IQURCRQpBaUFWVEc0ODB3Q1gzUER6VDZBdEQvbnR5RUd6NkpFYitqbDh6WDNaWDVKMDBnSWdI
      RE9JMllCQUtSMFpqTlI3CnVvTkl1ZEVRU1ZRMndGQkEwVEVudXNPRUZuRT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUNDekNDQWJLZ0F3SUJBZ0lVZklQM2ZZUjVqakNYbDA3UXBta1VUVVVSTUk4d0NnWUlL
      b1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBN
      QTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFC
      Z05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPREkxTURnd09EUXhX
      aGNOTWpVd05qRTBNRGd3T0RReFdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dX
      blZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBk
      WEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdT
      TTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTDhMTjVDNTNIYUFNQ1IvWUttYThhSE1SK0M4enZHNmtw
      ZjMKMzhYSHlaZElCekhIVU1yMGRLd3c2c0tMTlhoN2JaZnVBUTJEdzNxdlh2MWl1ZGFHTG5palFq
      QkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERn
      UVdCQlJQS09SSU5tVlFzUExRCm5YMjhDU0VRaVBiNjREQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFp
      QWR4VzA4MXlkcnlsK2tPTkV5dC9lejhDU1IKREgyNFlaZ1BGZXQxQXdCV0tnSWdEMy9GMXhaK1pL
      UW9JeUNYenlZYml3RlFteVJPMlNxZVdjY0RxRUYvSzdBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJl
      ck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21h
      bnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSthYKCmNhcnJpZXJNU1ASpxYawxQKA01TUBK7
      FBKwFBKtFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RD
      Q0FaNmdBd0lCQWdJVWNpSUplRVNaSHhMTTJadzdpZURPOVV5UFFiUXdDZ1lJS29aSXpqMEVBd0l3
      CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5
      YVdWeUxXNWxkREFlRncweQpNakE0TWpVd09ERXdORFZhRncweU5UQTJNVFF3T0RFd05EVmFNRm94
      Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2
      Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxs
      Y2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVNYRUdJdTJFRU1EVjJs
      WGlnYnFlTVYxYkNLZkduQ0dGYzFCY2J3ZzNRb2hDVjNXakRDNXBheGxBbERKU2NjCjNqOWVEWTM1
      bmxpS016ak1LYlZacVJMUW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIK
      L3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVZ09DZzdDSGZRMXBHbENsNFJiazQ4ZW15MWlvd0NnWUlL
      b1pJemowRQpBd0lEU0FBd1JRSWhBS3JRQ2Exb0J4Y2V0Wmd1SmhyN1dDUk80ZThpZlRkRXU1OUlF
      bTd6YWtTUkFpQTZQK0JJCnhvS1BZcjM2bExqTWtnZEc3SmlkdlhsRGdLVC9DZnlHNTJkTElBPT0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQzdqQ0NBcFNnQXdJQkFnSVVmaURYLzI1MHYzdXBHbkp3akRmK2FaSE1SaVl3Q2dZSUtvWkl6
      ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZ
      UzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBNE1qVXdPREU0TURCYUZ3MHlNekE0TWpVd09ESXpN
      REJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1i
      MjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdB
      MVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVFd5ZGREcmZ4dzNVWmhZZVdla3FSNgpm
      ekdmejF0T2lvTHlKZFRuTitNSUx4LzREMVNkMk9ZWUFqNU45Y3l6NlhVSWlPSGdNWERQTnVWcERV
      TDZFZXY2Cm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01B
      QXdIUVlEVlIwT0JCWUUKRkhNQzdKSWJHdFZwbCtCZGx3TnkwaUd2aWs2WU1COEdBMVVkSXdRWU1C
      YUFGSURnb093aDMwTmFScFFwZUVXNQpPUEhwc3RZcU1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIy
      eHpMVFprTkdNMlpqYzJaR1l0ZG5NMVpHMHdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5
      STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFX
      Wm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFX
      UnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktv
      Wkl6ajBFQXdJRFNBQXdSUUloQU9sQUcxRDIzVC9ucExUVk5Wbkd4WEE0Wi9CUXdTQzVxNis2bXVo
      Y0dtT3kKQWlCNHZUaTA3ZmFiamtmMkl6QnFCKzNpbzdUdUIrUGhTMzJFazV0S1RtbVNmUT09Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVWNpSUplRVNaSHhMTTJadzdpZURPOVV5
      UFFiUXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJj
      d0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakE0TWpVd09ERXdORFZhRncw
      eU5UQTJNVFF3T0RFd05EVmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1
      a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJV
      R0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1C
      QndOQwpBQVNYRUdJdTJFRU1EVjJsWGlnYnFlTVYxYkNLZkduQ0dGYzFCY2J3ZzNRb2hDVjNXakRD
      NXBheGxBbERKU2NjCjNqOWVEWTM1bmxpS016ak1LYlZacVJMUW8wSXdRREFQQmdOVkhSTUJBZjhF
      QlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVZ09DZzdDSGZRMXBH
      bENsNFJiazQ4ZW15MWlvd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBS3JRQ2Exb0J4Y2V0Wmd1
      SmhyN1dDUk80ZThpZlRkRXU1OUlFbTd6YWtTUkFpQTZQK0JJCnhvS1BZcjM2bExqTWtnZEc3Smlk
      dlhsRGdLVC9DZnlHNTJkTElBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIz
      CgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dy
      aXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5z
      EioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1l
      bnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVD
      aGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0Fk
      bWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0Fs
      Z29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUS
      EBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBs
      eWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMS
      FhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
