apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIFrPd/uVqG3zJgVIOB4xxyWleywoD3F5fPw0vEfqNRzgEqJeCp9eCpxeCngKWggBEAEaBgjD
      z/CYBiIKc3lzY2hhbm5lbCpAOWIyNTRmMjU3YWI2MTFhYTZkOWM4OTI2NmFjYzhkMDg0MTcyNTY5
      MjU2NGY3YWJhNWIzYjk4OWQ3NGYxYTgxMhIaEhjJOcMwIbAiCPTOZEUf+u33Lnx59Iw2N3cSn10K
      nF0SmV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVQXNBMDYwUWc2aFRHRVBGLy9NeFFSTnhrb1I0d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFd01EVTBNakk1V2hjTk1qVXdOak13TURVME1qSTVX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJMeGgz
      eWg4MTBablpWTGRWWUk3bmJTTDZwK3dCeUV1WVlxempmaXBPUzNvakl6UEpFdEUKSWQ1MU4wbjFO
      Z0ExblBCclB4R2hYajhkc0xYUFBFbXR0Q0NqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUlYvVWRlckhXTCsrTFA2Wmg0ZUt6UXZV
      Y3BYekFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCckxDcG5QdlNIRHVYc2wwd1k1bk4vS29NSTU1
      WHA5SkJUSTlJNUtVc0wKbndJZ0FJbHRrdGhLMFAvYWhNNlluRi94MUxIVndWN1RRbmwxRkdqV3JM
      S2xkOUk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVZXVDVXBKR3czaGNlWTA2elp1OFpzMWxieHhvd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFd01EVTFNREF3V2hjTk1q
      TXdPVEV3TURVMU5UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZ2NDSTB6aUxnaGRuK2xXRUxvWk1rbThhNXBq
      NW00UEQKR0Z2a1E0UUdHN2ZkOC9IblQxbnd2aFNwTE1MMzR5UEI3Q2NVTEVnNDBaQ3ZqT2lxSTl5
      M1VLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSZy9yL0tZRmZmCjRHWGhoMUI4UG5mckJLWWo3VEFmQmdOVkhTTUVHREFXZ0JS
      Vi9VZGVySFdMKytMUDZaaDRlS3pRdlVjcFh6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xYTnNOV2QyTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnRHlSWFlLeDZZbkNCakFiYmUzam45a041Q2tMdE05Mld5UitxdFh2cHBLa0NJQ3hi
      QTE4aytKOHJPMGFnCm1FcHBDVWJyN2tuUUtBaDIyZEdnSFFaa0JJZDcKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVQXNBMDYwUWc2aFRHRVBGLy9NeFFSTnhrb1I0d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RFd01EVTBNakk1V2hjTk1qVXdOak13
      TURVME1qSTVXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJMeGgzeWg4MTBablpWTGRWWUk3bmJTTDZwK3dCeUV1WVlxempmaXBPUzNvakl6UEpFdEUK
      SWQ1MU4wbjFOZ0ExblBCclB4R2hYajhkc0xYUFBFbXR0Q0NqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUlYvVWRlckhXTCsrTFA2
      Wmg0ZUt6UXZVY3BYekFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCckxDcG5QdlNIRHVYc2wwd1k1
      bk4vS29NSTU1WHA5SkJUSTlJNUtVc0wKbndJZ0FJbHRrdGhLMFAvYWhNNlluRi94MUxIVndWN1RR
      bmwxRkdqV3JMS2xkOUk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIW
      EgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS
      4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVU92dko4OXhEZGVrdzlOTUpDMEJXQWtScU04TXdD
      Z1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURW
      UVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09URXdNRFUxTURBd1doY05N
      ak13T1RFd01EVTFOVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVO
      VEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxF
      d2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNSQ2RidStZSVF5NTJwUlBQWURE
      Q1BBTkdrCk9VVzVnRWpwVWE1eVBTUTEyR0lHajBPQVltSlFsbW1URlZVdlBoekh5eUF6MzduMlBQ
      WnBJYkN5QWRxY280SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01C
      UUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERn
      UVdCQlJlN0VQL29EVWRIcHRwQUJJbHFjODFCZ0t3CnZqQWZCZ05WSFNNRUdEQVdnQlJWL1VkZXJI
      V0wrK0xQNlpoNGVLelF2VWNwWHpBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0ND
      b0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFH
      WXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3
      aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU9L
      Y0VmVjd0b3NqRVp0TQpIei9LL2QvUXVwcm1vM1VkdFZZL0trOVlrZTNuQWlBMGIxREpHSE0waTZh
      VkswclFScVNSVklNa2NoOVJZNk0yCkFEbXd6TEc2RWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVU92
      dko4OXhEZGVrdzlOTUpDMEJXQWtScU04TXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      dwpIaGNOTWpJd09URXdNRFUxTURBd1doY05Nak13T1RFd01EVTFOVEF3V2pCeE1Rc3dDUVlEVlFR
      R0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkNBQVNSQ2RidStZSVF5NTJwUlBQWUREQ1BBTkdrCk9VVzVnRWpwVWE1eVBTUTEyR0lHajBP
      QVltSlFsbW1URlZVdlBoekh5eUF6MzduMlBQWnBJYkN5QWRxY280SUIKTURDQ0FTd3dEZ1lEVlIw
      UEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpB
      TUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJlN0VQL29EVWRIcHRwQUJJbHFjODFCZ0t3
      CnZqQWZCZ05WSFNNRUdEQVdnQlJWL1VkZXJIV0wrK0xQNlpoNGVLelF2VWNwWHpBL0JnTlZIUkVF
      T0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJs
      ZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWht
      TGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEps
      Y2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3
      Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU9LY0VmVjd0b3NqRVp0TQpIei9LL2QvUXVwcm1vM1Vk
      dFZZL0trOVlrZTNuQWlBMGIxREpHSE0waTZhVkswclFScVNSVklNa2NoOVJZNk0yCkFEbXd6TEc2
      RWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1p
      bnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4S
      BAoCMnMaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1p
      bnMSvS8KC0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SyC4SthYKCmNh
      cnJpZXJNU1ASpxYawxQKA01TUBK7FBKwFBKtFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVWRHZ3lQNWxnMGppaVlQWU1IcEdmUDU4
      d0JBNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJj
      d0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakE1TVRBd05UUTJNekZhRncw
      eU5UQTJNekF3TlRRMk16RmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1
      a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJV
      R0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1C
      QndOQwpBQVFBYzZwUmtNOHB0aWt3NDFtTk1TMW01UFRhbEdSbTZOVjBMSWI0cXhpaWkzOUk5WHJ5
      SVZuN0xUZlpWakEwClVFcU9qZ25TWXA3R2RMcjZtY00yZ1ROdW8wSXdRREFQQmdOVkhSTUJBZjhF
      QlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVSHFuUEVOMDhwWFBR
      R1d2Y2pUaUVFbi9IekpZd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdQZkRlNDloNnFadktLL1Nt
      Q2t5NGtYYjJlUWRsbGpwNW9IMXVQanExVTdJQ0lRQ3gwQXhNCitMd3QxOGMvVWxrRUYrUk1XZk5S
      RDFMNVQ0b2d2SjFNeFM1R2lBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdqQ0NBcFNnQXdJQkFnSVVRTnY1YW9XNkQrY3dTaFgx
      UzdQK3FKZUU5aFl3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05W
      QkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5
      YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBNU1UQXdOVFUw
      TURCYUZ3MHlNekE1TVRBd05UVTVNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFI
      RXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1C
      Z05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRh
      VzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUThw
      VXdzazEyamZFalhoSE9obXNjMQpjeFVmeC9qZWxtcEdieExLdDNqdldDKzRGcmZ2NHJVV28vek5q
      ZnF6aVhrZnE3cnFxVWpWVno4SkVKQSt2L1d1Cm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURB
      Z2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRkRFV3hvWkFYWkFNK2ViL2l0S3hZ
      WTREczlIZk1COEdBMVVkSXdRWU1CYUFGQjZwenhEZFBLVnowQmxyM0kwNApoQkoveDh5V01DUUdB
      MVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFprTkdNMlpqYzJaR1l0Tm1OamFIWXdnWTBHCkNDb0RC
      QVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFX
      NGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJX
      NXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElq
      b2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFNBQXdSUUloQUs4alRVMTdYWkRwRmVicjR6
      V0syUlFOSXZQMWwxbVpVOTRvQTNZYmZHSjcKQWlBbHltQmpTTzRObnJjZHBEVUVNenczZStydTJZ
      Sys3ZWVFYzV4eUF1UEwxdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNI
      QTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVWRH
      Z3lQNWxnMGppaVlQWU1IcEdmUDU4d0JBNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncw
      eQpNakE1TVRBd05UUTJNekZhRncweU5UQTJNekF3TlRRMk16RmFNRm94Q3pBSkJnTlZCQVlUQWtk
      Q01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFV
      RUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdj
      cWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFBYzZwUmtNOHB0aWt3NDFtTk1TMW01UFRhbEdS
      bTZOVjBMSWI0cXhpaWkzOUk5WHJ5SVZuN0xUZlpWakEwClVFcU9qZ25TWXA3R2RMcjZtY00yZ1RO
      dW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdO
      VkhRNEVGZ1FVSHFuUEVOMDhwWFBRR1d2Y2pUaUVFbi9IekpZd0NnWUlLb1pJemowRQpBd0lEU0FB
      d1JRSWdQZkRlNDloNnFadktLL1NtQ2t5NGtYYjJlUWRsbGpwNW9IMXVQanExVTdJQ0lRQ3gwQXhN
      CitMd3QxOGMvVWxrRUYrUk1XZk5SRDFMNVQ0b2d2SjFNeFM1R2lBPT0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQoaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwK
      CmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fy
      cmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVy
      TVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBAB
      GgZBZG1pbnMqBkFkbWlucxKxFwoPbWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUK
      D21hbnVmYWN0dXJlck1TUBKBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0Fi
      S2dBd0lCQWdJVUpnUHAvcFFVcklvTGZ1TlBEdjFYcEI0YWdlMHdDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3T1RFd01EVTBORE13V2hjTk1qVXdOak13TURV
      ME5ETXdXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZ
      RFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFV
      RUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000
      OUF3RUhBMElBQk9lbUhoLy9xVkljZTlsTG9Jd1JjZmNjVXQwY1dTZW9DaW9NCkNLaWdZSkZNWTU4
      a0hqT1E1SkV0RFYvWmUxd0dUUDMxMG4xTGRmU3hGVllkK2tJVTQxNmpRakJBTUE4R0ExVWQKRXdF
      Qi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJSOE9mKzlYYS9m
      di9oWQoxRVVRNktTYzBEdmNCREFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFSVldaZkZXOUM5STR4
      c2ordnBZbm14MkZhCmRjbSt0TEI4dzU3QnNTQUx4d0lnSTBHUXI3bmdsU2NRTnM0cWFEUWhVRHBr
      VHNoeFFHOG81WUlpMjg4MEJrcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREVUQ0NBcmVnQXdJQkFnSVVBNGxkcWszZ21rR2VWV2hK
      N2ZOeXpFNytKTk13Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05W
      QkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUx
      Wm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNO
      TWpJd09URXdNRFUxTWpBd1doY05Nak13T1RFd01EVTFOekF3V2pDQmhqRUxNQWtHQTFVRQpCaE1D
      UTBneEdqQVlCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5Z
      VzUxClptRmpkSFZ5WlhJeEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZ
      M1IxY21WeU1SOHcKSFFZRFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dF
      d1lIS29aSXpqMENBUVlJS29aSQp6ajBEQVFjRFFnQUVYQWpUWGxqajh0QiswK2g3TlFEZThOS2dO
      cGZqc2pkS0lncHkyWWxQU2dhRFBkdTVGWWJjCmZWV3hVQkdES01ZSWNRbUtiL29HaDNYYi9LcmQy
      bFUvaXFPQ0FTSXdnZ0VlTUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFN
      QjBHQTFVZERnUVdCQlRXeXpDRUUyTG53eDZsbEEySXFGcDgzeE5aYWpBZgpCZ05WSFNNRUdEQVdn
      QlI4T2YrOVhhL2Z2L2hZMUVVUTZLU2MwRHZjQkRBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNj
      eTAzWTJRM1ptUm1PVGMyTFRWMk5Hc3lNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9u
      c2kKWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVpt
      bHNhV0YwYVc5dQpJam9pYldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlq
      b2lRV1J0YVc1QWJXRnVkV1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJp
      SjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQXdSNUhOTXBUaWZwVjRDZ093UHBPRitab0Z6
      ekFnZ1FFdkxYalg3OEY0aTRDSUdYdlZSV0tNd2d6L1BudgpES01LV3F4d3k2SWozMGd3SHkwQW9Q
      bERlclhICi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lCQWdJVUpnUHAvcFFVcklvTGZ1
      TlBEdjFYcEI0YWdlMHdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllX
      NTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0ho
      Y05Nakl3T1RFd01EVTBORE13V2hjTk1qVXdOak13TURVME5ETXdXakJrTVFzd0NRWURWUVFHCkV3
      SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdO
      VkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21W
      eUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk9lbUhoLy9xVkljZTls
      TG9Jd1JjZmNjVXQwY1dTZW9DaW9NCkNLaWdZSkZNWTU4a0hqT1E1SkV0RFYvWmUxd0dUUDMxMG4x
      TGRmU3hGVllkK2tJVTQxNmpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFI
      L0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJSOE9mKzlYYS9mdi9oWQoxRVVRNktTYzBEdmNCREFLQmdn
      cWhrak9QUVFEQWdOSEFEQkVBaUFSVldaZkZXOUM5STR4c2ordnBZbm14MkZhCmRjbSt0TEI4dzU3
      QnNTQUx4d0lnSTBHUXI3bmdsU2NRTnM0cWFEUWhVRHBrVHNoeFFHOG81WUlpMjg4MEJrcz0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggS
      BggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxII
      EgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8S
      CBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiES
      CBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQEAEaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5u
      ZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxotChlCbG9ja0RhdGFIYXNo
      aW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1v
      cmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoM
      Q2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0S
      EhIICgZTSEEyNTYaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
