apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.66.8.13:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaILR3yhVNKE68PH0fx0LKHTdyTKx/bnqgL4XkXdesviLJEp5eCpteCpheCngKWggBEAEaBgii
      2oGcBiIKc3lzY2hhbm5lbCpANTgwODA4M2U3MjFiZTA0OWE2ZmZhNDAxNjIzOTNkOGJlMzRiMzY2
      Mzc5ZWY3OTk0MGJiMzNhNzlhMTQ1NThiZhIaEhi1+hWq7nFAFi0pkBKbVhvGjz9gqdildu4Sm10K
      mF0SlV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVR1BMMTMvM0NVQ01WS0VpTFcxVDUzWHJnMUJ3d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TVRJMU1EY3dPREUwV2hjTk1qVXdPVEUwTURjd09ERTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJJS2ZJ
      eitTNG5YKzlXWGdRWk5mYXZFSWFncm5xQTNzSmxKSzJNY0JwS2dCN2cwTStQWVoKanQ2ZStMQ0Uz
      Ri9BeEVEWmRnbW1JK3dUc21XV0Q1YmoyUkNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUU9ibjkxMmFUUGlRVzBnLzhRVFRrbjRX
      MEpRakFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCdGZOM1BMMlNJK1dXT05zTklCbmVyNHhZbXZh
      V1QxU3NaVDc5NE1Uc3QKbUFJZ1hBdlI0Y2t4L0dCSHVGT01UdVJHR3kyL0wyTDBmMjJBeGJoUFBO
      VU85WlU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9lZ0F3SUJBZ0lVS0RuN1RvVnhhbHRuVUNuWDNjWWJlN3FUTnBzd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TVRJMU1EY3hOREF3V2hjTk1q
      TXhNVEkxTURjeE9UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNlpnYUtZNFUxVXVzVTJvYllnaG1wdThMeDVG
      VjZUSUEKVTNyUWR6bTl4V0dPNjNBMmNRVUNINmlXUzVPQTFiTzBiVVBDTlhUbnByUHRkVDBRcTUx
      aUc2T0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSN1VOOXRUQjVTCmlGMWg3YTBaMC9uRVNNRk41REFmQmdOVkhTTUVHREFXZ0JR
      T2JuOTEyYVRQaVFXMGcvOFFUVGtuNFcwSlFqQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kw
      NFpEYzNORFUyTlRrdGJXcGpabXd3Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05J
      QURCRgpBaUVBbW5iQ1JvU0c2U3A4QUgzdTd0ODNPSFArMy9jT29nZnlqZHJnTE16WVdtWUNJRG94
      ZW5IbmNXMEg2SEE2ClRiaXRDNVJqakVGNEhSNUZGOHpRSEl5Vy9aQkgKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVR1BMMTMvM0NVQ01WS0VpTFcxVDUzWHJnMUJ3d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TVRJMU1EY3dPREUwV2hjTk1qVXdPVEUw
      TURjd09ERTBXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJJS2ZJeitTNG5YKzlXWGdRWk5mYXZFSWFncm5xQTNzSmxKSzJNY0JwS2dCN2cwTStQWVoK
      anQ2ZStMQ0UzRi9BeEVEWmRnbW1JK3dUc21XV0Q1YmoyUkNqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUU9ibjkxMmFUUGlRVzBn
      LzhRVFRrbjRXMEpRakFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCdGZOM1BMMlNJK1dXT05zTklC
      bmVyNHhZbXZhV1QxU3NaVDc5NE1Uc3QKbUFJZ1hBdlI0Y2t4L0dCSHVGT01UdVJHR3kyL0wyTDBm
      MjJBeGJoUFBOVU85WlU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vu
      c3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCK
      NxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQkRDQ0FxdWdBd0lCQWdJVUQreUh6
      ald4T1N6emFzNVROVFN5ZXlQeXdkY3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURW
      UVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpI
      aGNOTWpJeE1USTFNRGN4TkRBd1doY05Nak14TVRJMU1EY3hPVEF3V2pCeE1Rc3dDUVlEVlFRR0V3
      SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3
      ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNt
      VnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkNBQVREd3pGQkJyYlkwcGxmWXJGMWhrNUdubVYwCkZrQ05ObjNwUzR4Mjh4UC9WSitydHNyUTFB
      YWFEbjMwNVBycXRyY05YMG5ab3pGTmVmdy9sOUtjU0h1MG80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFR
      SC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJn
      TlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlQ1V0hQRXVESXBxSnkxdzg5MHllSUZ1Q3hqCktU
      QWZCZ05WSFNNRUdEQVdnQlFPYm45MTJhVFBpUVcwZy84UVRUa240VzBKUWpCQkJnTlZIUkVFT2pB
      NGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNK
      aFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZ
      dVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRB
      S0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCeTl6NnoxZlZXWG9XbQphODVpaTN2YUtCYUsvTmRuRWdr
      MS9nMEVkU0NMYndJZ2RCSG5PTnZvUnBRM1JMSzZnSlU1UWlvWHArTStQdHlQCnAzZjRTUUNKaDc0
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlEQkRDQ0FxdWdBd0lCQWdJVUQreUh6ald4T1N6emFzNVROVFN5ZXlQeXdkY3dDZ1lJS29a
      SXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJK
      allTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1USTFNRGN4TkRBd1doY05Nak14TVRJ
      MU1EY3hPVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRB
      dU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21S
      bGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVREd3pGQkJyYlkwcGxmWXJGMWhrNUdubVYw
      CkZrQ05ObjNwUzR4Mjh4UC9WSitydHNyUTFBYWFEbjMwNVBycXRyY05YMG5ab3pGTmVmdy9sOUtj
      U0h1MG80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NH
      QVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlQ1
      V0hQRXVESXBxSnkxdzg5MHllSUZ1Q3hqCktUQWZCZ05WSFNNRUdEQVdnQlFPYm45MTJhVFBpUVcw
      Zy84UVRUa240VzBKUWpCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0Zw
      YmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01F
      QlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVG
      Ym5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8K
      Wmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCeTl6Nnox
      ZlZXWG9XbQphODVpaTN2YUtCYUsvTmRuRWdrMS9nMEVkU0NMYndJZ2RCSG5PTnZvUnBRM1JMSzZn
      SlU1UWlvWHArTStQdHlQCnAzZjRTUUNKaDc0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChIS
      CgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZB
      ZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rp
      b25zEggaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1p
      bnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SshYKCmNh
      cnJpZXJNU1ASoxYavxQKA01TUBK3FBKsFBKpFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdBd0lCQWdJVVJUU3BzQThaMFBlOGRFZnh3a1pCZENz
      a3ZmQXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJj
      d0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV4TWpVd056RXdNamhhRncw
      eU5UQTVNVFF3TnpFd01qaGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1
      a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJV
      R0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1C
      QndOQwpBQVEyVTVTSWdaWjJWaXF2QVJPeHgvYkdxQTZCSjlxeW8rNXZuRGVGN0VsMzZCcW4rYkEy
      L1VSRHhWQ3Y0S3pIClBSTkd4RUc2YWNlYWtzU0l5TzhsS3IxaG8wSXdRREFQQmdOVkhSTUJBZjhF
      QlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVSzl6UE5DNE1ja2Zm
      RTBMVXhhWEdwcUJKS0RBd0NnWUlLb1pJemowRQpBd0lEU1FBd1JnSWhBTmZsb2Q0UEwvWHBaTFRS
      bWRUajNnYWYwL3VwUEpVZStJMlh5U1hhQ01NbUFpRUFzUUQxCnk1ME1idlZoVXkwdW5LSkZyRE5k
      WkF0bHhlVmxZcTdtMnNmNlFmVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdUQ0NBcFNnQXdJQkFnSVVQc2drcmFiRnB5QUVtZklt
      RWVSUXBPWC9SSmd3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05W
      QkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5
      YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeE1qVXdOekUy
      TURCYUZ3MHlNekV4TWpVd056SXhNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFI
      RXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1C
      Z05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRh
      VzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUXcw
      TlMyT2VxNDMzSWxiQkNVcmRwNApLRjVjV3hYYTFodGo2NkxuYURMc29nMlZYSGRoU0w2c2tnZDJZ
      TDFzQWNuaklRMjRJSUtpakNhVzhHa0RNaVRsCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURB
      Z2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRkRFSzlVRm9PMmZ2Z1FDZjJ1RlRw
      cjJEbWFla01COEdBMVVkSXdRWU1CYUFGQ3ZjenpRdURISkgzeE5DMU1XbAp4cWFnU1Nnd01DUUdB
      MVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVGRqTjJRME5UUTBPRGd0Ym5Oa1pHb3dnWTBHCkNDb0RC
      QVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFX
      NGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJX
      NXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElq
      b2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnS0pBdis3MnlwNHhaeDFXRWVM
      RGtRajJ6Q3crekNoeGs1cldHM3ZadTVEWUMKSUUzSm1EOXFqQ0wvSndzNy9pT1cxc3RsTytIVjcy
      Z0p1Z3ZxTkg0VnAxaDMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2
      SukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrVENDQVo2Z0F3SUJBZ0lVUlRTcHNB
      OFowUGU4ZEVmeHdrWkJkQ3NrdmZBd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1q
      RXhNalV3TnpFd01qaGFGdzB5TlRBNU1UUXdOekV3TWpoYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4
      d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3
      SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtq
      T1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUTJVNVNJZ1paMlZpcXZBUk94eC9iR3FBNkJKOXF5bys1
      dm5EZUY3RWwzNkJxbitiQTIvVVJEeFZDdjRLekgKUFJOR3hFRzZhY2Vha3NTSXlPOGxLcjFobzBJ
      d1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0
      RUZnUVVLOXpQTkM0TWNrZmZFMExVeGFYR3BxQkpLREF3Q2dZSUtvWkl6ajBFCkF3SURTUUF3UmdJ
      aEFOZmxvZDRQTC9YcFpMVFJtZFRqM2dhZjAvdXBQSlVlK0kyWHlTWGFDTU1tQWlFQXNRRDEKeTUw
      TWJ2VmhVeTB1bktKRnJETmRaQXRseGVWbFlxN20yc2Y2UWZVPQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tChoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVy
      TVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBAB
      GgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQ
      GgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFk
      bWlucyoGQWRtaW5zErEXCg9tYW51ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFu
      dWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3
      SUJBZ0lVWHlqM2IwbHVFcTJRMjBlWkNHYzRsVG5zb1Uwd0NnWUlLb1pJemowRUF3SXcKWkRFTE1B
      a0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdO
      bwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5W
      bVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNVEkxTURjd09USXlXaGNOTWpVd09URTBNRGN3T1RJ
      eVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFR
      SERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3
      VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdF
      SEEwSUFCQ0ZHVCtKeHFKUjRkSmZnT1Mwajh2bW1kN3pHZVRiTVJPbTcKZ2pEMEJqUU5qZ3pjNGNU
      alhlY2FUVVhvcGFIQWQ5OWw5UmpybFRjazAyaGZ2V3lpR1NHalFqQkFNQThHQTFVZApFd0VCL3dR
      Rk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlF4eTBOTlJMNHdnYWp1
      CmdrZnhsWE9weDdIdTZEQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUF6Y20yK0p0cHcxTERwUE5T
      OHlOVkxGemQKVHVxRFFoMjN0bVNaOTRKSldmWUNJSHVTanRSN3BSaFZZNFI3MkZqUGNJNzhzaEtT
      d2VpTXBacWZYZGRaVTErSwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlERURDQ0FyZWdBd0lCQWdJVVM1QUhuRjB1UDgvSkxqRlU1dS9Y
      MitMdFA0SXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdN
      QmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZq
      ZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4
      TVRJMU1EY3hOVEF3V2hjTk1qTXhNVEkxTURjeU1EQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4
      R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEK
      Wm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFj
      bVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhL
      b1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdBRW1yL2p6VzhiMGFEa0xYb1hoSUlPWlJ5eDZmdTcx
      aFp4b0tNbzlGSUhiTSttbkFldDFESGQKSlZFdksyNithdXU1THovSU1FZGdqbzUwZEd4cWc5VU1k
      cU9DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdB
      MVVkRGdRV0JCUmFOcy80cEZYL0dEeTgvMWZ6Sk1PeHBMK3FPakFmCkJnTlZIU01FR0RBV2dCUXh5
      ME5OUkw0d2dhanVna2Z4bFhPcHg3SHU2REFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDFP
      V1E0TnpVME56ZzJMVFUyTWpsNE1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZ
      V0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FX
      RjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFX
      UnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZU
      QUtCZ2dxaGtqT1BRUURBZ05IQURCRQpBaUEyeUNoWnptTGhjU1p3Q0VnbUhPYW52Q2tyVVdObmsy
      bkJCQWFQelIraTVBSWdNRk9wNlBkVG5hcEJ1dTFFCm5EbzBnTjc5eU9HYmRKaVd3NDVXbkl2NGZn
      OD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVWHlqM2IwbHVFcTJRMjBlWkNH
      YzRsVG5zb1Uwd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJB
      Z01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVpt
      RmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1q
      SXhNVEkxTURjd09USXlXaGNOTWpVd09URTBNRGN3T1RJeVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNE
      RVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFv
      TQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1
      bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQ0ZHVCtKeHFKUjRkSmZnT1Mw
      ajh2bW1kN3pHZVRiTVJPbTcKZ2pEMEJqUU5qZ3pjNGNUalhlY2FUVVhvcGFIQWQ5OWw5UmpybFRj
      azAyaGZ2V3lpR1NHalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFR
      REFnR21NQjBHQTFVZERnUVdCQlF4eTBOTlJMNHdnYWp1CmdrZnhsWE9weDdIdTZEQUtCZ2dxaGtq
      T1BRUURBZ05JQURCRkFpRUF6Y20yK0p0cHcxTERwUE5TOHlOVkxGemQKVHVxRFFoMjN0bVNaOTRK
      SldmWUNJSHVTanRSN3BSaFZZNFI3MkZqUGNJNzhzaEtTd2VpTXBacWZYZGRaVTErSwotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoV
      EhMKD21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYI
      ARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIG
      CAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggS
      BggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwK
      CgoGVjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1p
      bnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRl
      cmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
