apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://34.83.14.202:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: supplychain-net

    genesis: |-
      CiIaIPq/h8iMNfOgHfJ6++lwjblxkZXFZ5ldnB3dkVrhSvTTEp5eCpteCpheCngKWggBEAEaBgiD
      pJOeBiIKc3lzY2hhbm5lbCpAODM1OGIzNWM2YzMzYzcxYmI1MDY5ZjAzMzlmZTA1YTY1MjY4YzQ5
      N2Q1ZTFjZTMyNzU0YjA5YTg0NjY5YTA1ORIaEhh0taIZizs3cgZRDUSnKxG13wOMK+qdVSUSm10K
      mF0SlV0SjysKB09yZGVyZXISgysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVUzlpRkU2Zml4TEsydW5RM3dIdERsUHE5cHhzd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRFMk1EUXhNRFUyV2hjTk1qVXhNVEExTURReE1EVTJX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJQV1E4
      N2VubWFsMHU1ZjhtRlBITitZNTFCKzBWcGpBNUlIc1BKdHlTNXlMT2xJd2E0NjIKbFUwQTZNN2Ir
      SUdaa2ZmdDZQd2VKQTBoOUc5STkrOGhNMTZqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0s3YllwSGdtdExiaURnR1IxWjh0di82
      aUhYVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCczhzR0ZaN29SY0liVmNNVVBqMTlZa25VYjRk
      bFlHcEpLSGF0cGFHRUsKUVFJaEFOWTI2eHYyOU0yU0lqWmtWRXJWdGFSZ01CU2lUcVFwbWhMcFR6
      eHFSWDhQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVUjQydkNUaXNoY0RJZkZGZVpib0xxdHFIc1Frd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRFMk1EUXhOekF3V2hjTk1q
      UXdNVEUyTURReU1qQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFL3NvMjZSNDFSdjlnZEdRNUVBVkF1NkRRZUxN
      c3M3QysKaldaNWRmejl3U0M4dHN3TmpleWhTZFQyQnQyVTdDbVFnR3BLdFIvR0QrM1daTEdCQWtZ
      M2xxT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSZUFpRXkzU3RSCjlFbDE0Rms0U0JxenFCcmNmekFmQmdOVkhTTUVHREFXZ0JT
      SzdiWXBIZ210TGJpRGdHUjFaOHR2LzZpSFhUQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M056ZzVOelJpT0dKbUxUWnhjbkJyTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUpzR2hwdk9DQTYrN092MWQ1R3M1MmN0SGtZL0Zqa2VaeXg5ZmFkYnN4UnRBaUJr
      ZHlVQ0RGM2pabm5BCmRYNEk4eUx5OW04ZFoycG90aWdjaWg5RUFkdHpCZz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVM5aUZFNmZpeExLMnVuUTN3SHREbFBxOXB4c3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd01URTJNRFF4TURVMldoY05NalV4
      TVRBMU1EUXhNRFUyV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCUFdRODdlbm1hbDB1NWY4bUZQSE4rWTUxQiswVnBqQTVJSHNQSnR5UzV5TE9sSXdh
      NDYyCmxVMEE2TTdiK0lHWmtmZnQ2UHdlSkEwaDlHOUk5KzhoTTE2alFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNLN2JZcEhnbXRM
      YmlEZ0dSMVo4dHYvNmlIWFRBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQnM4c0dGWjdvUmNJYlZj
      TVVQajE5WWtuVWI0ZGxZR3BKS0hhdHBhR0VLClFRSWhBTlkyNnh2MjlNMlNJalprVkVyVnRhUmdN
      QlNpVHFRcG1oTHBUenhxUlg4UAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxqCEgoNQ29uc2Vuc3VzVHlwZRLw
      ERLlEQoIZXRjZHJhZnQS2BEKwREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrPCC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQVRDQ0FxZWdBd0lCQWdJVVBscFU3YkR0MkVJU0xS
      cVVmTjlmM1lRV3dWa3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNt
      UmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd01U
      RTJNRFF4TnpBd1doY05NalF3TVRFMk1EUXlNakF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1C
      a0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhC
      d2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVF4VzNQ
      bndLM3hNalp6bGJjbnV3a2MvWHM0Cm4wb1JVeDQ5RzhPRld6c0VHTmNtR0NqTWxDYlRLbzdHQkU4
      VHVPYlMrWTZOTU92RzNSUFRwT3B1M0h2UW80SUIKTGpDQ0FTb3dEZ1lEVlIwUEFRSC9CQVFEQWdP
      b01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4
      RUFqQUFNQjBHQTFVZERnUVdCQlQzT01QYUp3bDVmanRHNjAvaElPa0gzeEpJCnF6QWZCZ05WSFNN
      RUdEQVdnQlNLN2JZcEhnbXRMYmlEZ0dSMVo4dHYvNmlIWFRBOUJnTlZIUkVFTmpBMGdoaHYKY21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHRzl5WkdWeVpYSXhMbk4xY0hCc2VXTm9ZV2x1
      TFc1bApkREJzQmdncUF3UUZCZ2NJQVFSZ2V5SmhkSFJ5Y3lJNmV5Sm9aaTVCWm1acGJHbGhkR2x2
      YmlJNklpSXNJbWhtCkxrVnVjbTlzYkcxbGJuUkpSQ0k2SW05eVpHVnlaWEl4TG5OMWNIQnNlV05v
      WVdsdUxXNWxkQ0lzSW1obUxsUjUKY0dVaU9pSnZjbVJsY21WeUluMTlNQW9HQ0NxR1NNNDlCQU1D
      QTBnQU1FVUNJUURBVmtJaktPQTBwdUR6WHJEWApZT3Bzblc3NysrQjdPQWFHeWV6OFFDTXFGd0ln
      WlYwZzlCTVJDYitUbTcwQlYxT0xBdHQ1d3R1MnJxUDhoQ3ArCjBtcmp3YUU9Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KIs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQXFl
      Z0F3SUJBZ0lVUGxwVTdiRHQyRUlTTFJxVWZOOWYzWVFXd1Zrd0NnWUlLb1pJemowRUF3SXcKWGpF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxq
      YUdGcGJpMXVaWFF3CkhoY05Nak13TVRFMk1EUXhOekF3V2hjTk1qUXdNVEUyTURReU1qQXdXakJ4
      TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1
      TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lE
      VlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQ0FBUXhXM1Bud0szeE1qWnpsYmNudXdrYy9YczQKbjBvUlV4NDlHOE9G
      V3pzRUdOY21HQ2pNbENiVEtvN0dCRThUdU9iUytZNk5NT3ZHM1JQVHBPcHUzSHZRbzRJQgpMakND
      QVNvd0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JC
      Z0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVDNPTVBhSndsNWZqdEc2
      MC9oSU9rSDN4SkkKcXpBZkJnTlZIU01FR0RBV2dCU0s3YllwSGdtdExiaURnR1IxWjh0di82aUhY
      VEE5QmdOVkhSRUVOakEwZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dHOXla
      R1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVsCmREQnNCZ2dxQXdRRkJnY0lBUVJnZXlKaGRIUnlj
      eUk2ZXlKb1ppNUJabVpwYkdsaGRHbHZiaUk2SWlJc0ltaG0KTGtWdWNtOXNiRzFsYm5SSlJDSTZJ
      bTl5WkdWeVpYSXhMbk4xY0hCc2VXTm9ZV2x1TFc1bGRDSXNJbWhtTGxSNQpjR1VpT2lKdmNtUmxj
      bVZ5SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRREFWa0lqS09BMHB1RHpYckRYCllPcHNu
      Vzc3KytCN09BYUd5ZXo4UUNNcUZ3SWdaVjBnOUJNUkNiK1RtNzBCVjFPTEF0dDV3dHUycnFQOGhD
      cCsKMG1yandhRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICA
      ChoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxK9
      LwoLQ29uc29ydGl1bXMSrS8S4i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLILhKxFwoPbWFudWZh
      Y3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1TUBKBBi0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVUtMRHNiVGI4dXhWZGIvZXVI
      QXlUVnBOdnhxOHdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFa
      bUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05N
      ak13TVRFMk1EUXhNakExV2hjTk1qVXhNVEExTURReE1qQTFXakJrTVFzd0NRWURWUVFHCkV3SkRT
      REVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJB
      b00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxX
      NWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkdqbFVJSkNKcjF6WHVZUWtr
      a1p0SjlOL2RCejVtaXBrV0I2CjJibkJZekwyVDVoS1FTS2lwQmZXYzF1cERwb2xyWVYyUHhXOW82
      aGlDb3oxb3FvbWllbWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJUUURRcjhqVENPclJqcgpvNHgyQUNISmhUMlpkREFLQmdncWhr
      ak9QUVFEQWdOSUFEQkZBaUVBMkd0VVl5MktwRC9vUHB5a2NaUTB3R3hECmF4UVVBWURZUjd3b20x
      TWZpWUFDSUNWbVVFbzBZVE80NjZQRUQ5c2RKY2FMcmIrVloyc2tTMWFtNmw0Z2gxdGMKLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREVU
      Q0NBcmVnQXdJQkFnSVVVL2V2MldBT2FUQnlaQWdCYjRvQWVOdnFqNjB3Q2dZSUtvWkl6ajBFQXdJ
      dwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3
      R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJO
      aExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd01URTJNRFF4T1RBd1doY05NalF3TVRF
      Mk1EUXlOREF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNMak00THpn
      dU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6QU1CZ05WQkFz
      VEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZRUUREQlpCWkcx
      cGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6ajBEQVFj
      RFFnQUVhTXgzUi9aRWNsa1RaVGVmbTZXNXRsYnovNHg5REQzNytiTFlITDh2c0J1S0VHcGM5RXEw
      CnNMV3d0OEYvSWJjN0xHelExaXVYdlYwQURGTFJhcWFva0tPQ0FTSXdnZ0VlTUE0R0ExVWREd0VC
      L3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlIwQUJCaXM4elZUUGNl
      eThQV2pOdXB1emZ1Q2pBZgpCZ05WSFNNRUdEQVdnQlRRRFFyOGpUQ09yUmpybzR4MkFDSEpoVDJa
      ZERBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAxTmpSaU9UZzNaR1kyTFRKaWVHaG9NSUdY
      QmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpvaWRISjFaU0lz
      SW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldGdWRXWmhZM1Ix
      Y21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1poClkzUjFjbVZ5
      TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkYK
      QWlFQTF0OER6SGs3S3RBcWxTY0FuWXkyL280c0I2ckpkMVRsMUowcTU4eE54SGdDSUU5UXZONFU3
      WE1DaUJqeQpHcXl0bHNBYXN2UXNtYnZmVGttTTRwSzEvc3VwCi0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      RERDQ0FiS2dBd0lCQWdJVUtMRHNiVGI4dXhWZGIvZXVIQXlUVnBOdnhxOHdDZ1lJS29aSXpqMEVB
      d0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1F
      Mk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nak13TVRFMk1EUXhNakExV2hjTk1qVXhN
      VEExTURReE1qQTFXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9N
      UTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNN
      Qm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdD
      Q3FHU000OUF3RUhBMElBQkdqbFVJSkNKcjF6WHVZUWtra1p0SjlOL2RCejVtaXBrV0I2CjJibkJZ
      ekwyVDVoS1FTS2lwQmZXYzF1cERwb2xyWVYyUHhXOW82aGlDb3oxb3FvbWllbWpRakJBTUE4R0Ex
      VWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJUUURR
      cjhqVENPclJqcgpvNHgyQUNISmhUMlpkREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBMkd0VVl5
      MktwRC9vUHB5a2NaUTB3R3hECmF4UVVBWURZUjd3b20xTWZpWUFDSUNWbVVFbzBZVE80NjZQRUQ5
      c2RKY2FMcmIrVloyc2tTMWFtNmw0Z2gxdGMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFk
      bWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZB
      ZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoG
      QWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBAB
      GgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyoGQWRtaW5zErYWCgpjYXJyaWVyTVNQEqcWGsMUCgNNU1ASuxQSsBQSrRQK
      CmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitUQ0NBWjZnQXdJ
      QkFnSVVWM1RxOHY3UzJaUnhQaHpPTW9YN2tOVDRHTFV3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVs
      ZERBZUZ3MHkKTXpBeE1UWXdOREV6TVRCYUZ3MHlOVEV4TURVd05ERXpNVEJhTUZveEN6QUpCZ05W
      QkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVR
      TUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3
      V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTNDl6dWZwbm93MGRMZWlXYzdlWE95
      eTF5WGZ3Visvd25nRHhMc1VROWM1RG1Wa3ZjOHF6b01mZ21KVENjdwpGOFdZZ3JDV3RPcmN4dHhI
      aHlnRzU5bllvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lC
      cGpBZEJnTlZIUTRFRmdRVThjOEx5WHZhTVFTS043UlE4ODVzb3dOeDA2VXdDZ1lJS29aSXpqMEUK
      QXdJRFNRQXdSZ0loQUpmZDM2NFVpS0k5TzVlOWJUTHRQZFpHMWVoNUM4elN1TW00Sm9kK1F1ejJB
      aUVBNXNwZApuc25BYUwvYnQ2YVVQTHV6TGdZNFNXd0Z1UmdCVDVxbG1MUjNQOVU9Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3akND
      QXBTZ0F3SUJBZ0lVTHRIM1Uva2VVWVdLZWlYWjM4R0J3ZjNEcTJ3d0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck16QXhNVFl3TkRJeE1EQmFGdzB5TkRBeE1UWXdOREkyTURCYU1IZ3hD
      ekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhF
      REFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFVRUN4TUhZ
      MkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RBVEJnY3Fo
      a2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRvS0U4TFRlbTJQdjFNZm9uUEdXbjAKNldyQnI0dHEw
      QmV6THpVS3BTUDVHME1FZmRYNVBlbGFsQTQ3Lyt3WjZuZFFUcU9iMlVMb21ULytMSDNSQ1RxSgpv
      NElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZS
      ME9CQllFCkZPQUtIUHVKRm00L1JWakVmWDBxTUgxTEtCYkNNQjhHQTFVZEl3UVlNQmFBRlBIUEM4
      bDcyakVFaWplMFVQUE8KYktNRGNkT2xNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6TFRWa056
      VTJORGsxTm1RdGMycGpNbTB3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2ZXlKaFlt
      RmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cFlY
      UnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0YVc1QVky
      RnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJemowRUF3
      SURTQUF3UlFJaEFKb2dTajNLb0V4NWZNNDgycVVsSm9jOTJvYmxMWmZXUEtkMVVzMzBoYTlUCkFp
      QVh3ZmZmTDJ5bS9GT3RIbmVzSEdEOTVRaWZKb1RROU1WanVQVTBSR2FnUXc9PQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVWM1RxOHY3UzJaUnhQaHpPTW9YN2tOVDRHTFV3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBeE1UWXdOREV6TVRCYUZ3MHlOVEV4TURV
      d05ERXpNVEJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpB
      TkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3
      T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFT
      NDl6dWZwbm93MGRMZWlXYzdlWE95eTF5WGZ3Visvd25nRHhMc1VROWM1RG1Wa3ZjOHF6b01mZ21K
      VENjdwpGOFdZZ3JDV3RPcmN4dHhIaHlnRzU5bllvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgv
      TUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVThjOEx5WHZhTVFTS043UlE4ODVz
      b3dOeDA2VXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUpmZDM2NFVpS0k5TzVlOWJUTHRQZFpH
      MWVoNUM4elN1TW00Sm9kK1F1ejJBaUVBNXNwZApuc25BYUwvYnQ2YVVQTHV6TGdZNFNXd0Z1UmdC
      VDVxbG1MUjNQOVU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIc
      EggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdT
      dHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVy
      ZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBh
      YmlsaXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggK
      BlNIQTI1NhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
