apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaILQtT2q1YMHANzedRx7ihx1VHnBFlJa4wnv5uoGrShvGEqReCqFeCp5eCngKWggBEAEaBgii
      ndaZBiIKc3lzY2hhbm5lbCpAYThjYzAzYjUxODY5YTNjMTg1ZjkyYjNhN2Q3ODFjNTQ1NjFjY2Y4
      OTMwOGM4ZTVlMmI2NGE2ZmFlZGVhZGFjOBIaEhgHNtGGpc77XodsZ9v7lFzZCXW4IYxH09sSoV0K
      nl0Sm10SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVRU5ST1RUR2RwU3B3azFMaUhrK0pmU1phWXdvd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RJNU1USXdPREkwV2hjTk1qVXdOekU1TVRJd09ESTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGeStv
      Q3lJU3dManlIMG1VNVBxMFI2cXFXbXZWT05tQzlmSE5mYlBWb1pSaE42R2F6Q0MKVnNPdnVHc3FD
      NWdaVnBvaFA2Rm1SdVFjZlBUeUdYRk5EWStqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU3NYVzlSNUdDM1IyNUJDSVRtcWU4bjdU
      UVMzVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTdCNm1JYVljZE5tc3ZxaWZHdVV1UDBFQWRl
      Vmg3d2tEeHhxTDBsdjYKSEtBQ0lFNXhDY1h3Nm9CRXF4ZDROU2JQZEpYR1pKcWFITFdMVTluYnZl
      dTB3akJvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVR0t1WWx0NlVkN0JYNDFiMSt0aXVoVDZQSkpJd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RJNU1USXhOakF3V2hjTk1q
      TXdPVEk1TVRJeU1UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFczhjWTNLajNaY0Uyc3RqdnBkZTJuQ25JVnBZ
      M0xBQ2UKcVhPei8xUkE4L0dqRnNXdHlvT1FiUXVRd09EYlRCYVBKN0VGTVBzbmNOVEJJM25kMHMr
      M3hLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRWlVSZmJYaDBGCjJLaDJyK2lEeTVHUDBvbkdHekFmQmdOVkhTTUVHREFXZ0JT
      c1hXOVI1R0MzUjI1QkNJVG1xZThuN1RRUzNUQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xYWjJlREkyTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUlBWVFpdW5RQ1ZHcFFLUnZabDZDNVcxQjg2cEpWRjNzc0ZMaGl0OElmTlZBaUI2
      WnpJdngxV21XMnM1Ck5UOEl2dExpNlQveTk2cDlwandsQUppYkV0STlIUT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVUVOUk9UVEdkcFNwd2sxTGlIaytKZlNaYVl3b3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09USTVNVEl3T0RJMFdoY05NalV3
      TnpFNU1USXdPREkwV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCRnkrb0N5SVN3TGp5SDBtVTVQcTBSNnFxV212Vk9ObUM5ZkhOZmJQVm9aUmhONkdh
      ekNDClZzT3Z1R3NxQzVnWlZwb2hQNkZtUnVRY2ZQVHlHWEZORFkralFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNzWFc5UjVHQzNS
      MjVCQ0lUbXFlOG43VFFTM1RBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE3QjZtSWFZY2RObXN2
      cWlmR3VVdVAwRUFkZVZoN3drRHh4cUwwbHY2CkhLQUNJRTV4Q2NYdzZvQkVxeGQ0TlNiUGRKWEda
      SnFhSExXTFU5bmJ2ZXUwd2pCbwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0
      cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlu
      cxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBs
      eWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdB
      d0lCQWdJVVFqRlk2UWwxQ1dGbHgzSUlxMXFzc1o4R0FPSXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpJd09USTVNVEl4TmpBd1doY05Nak13T1RJNU1USXlNVEF3V2pCeE1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZR
      UURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkNBQVN5S01YY2ZzdEFRS0Vtb3VrQ1Jack04K3ZOCmpCMWRWZk5tcXhYeWQr
      TTN1c0VNQzIrNlhJeDAyaFRqNXJqSmNoZDduWXk4SWJoSDlUc0VFeXc2MUNnQW80SUIKTURDQ0FT
      d3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdF
      RgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNGZFNDTlJqTFN1VUxEMkli
      VDltK2pkbXZrCmJUQWZCZ05WSFNNRUdEQVdnQlNzWFc5UjVHQzNSMjVCQ0lUbXFlOG43VFFTM1RB
      L0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdW
      eVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhK
      eklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpv
      aWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdW
      eVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU43Rm9UaXdIT0V2K1ZUQwphQ0hlZXlN
      aFAvY2V3d05TNjY0enFoYU1qSFBNQWlCMzRPMS96YzZHeHYvTkxIcThzUCtVSzVURy80c3BJaTNk
      CjVkdHg2cjRzMnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVVFqRlk2UWwxQ1dGbHgzSUlxMXFzc1o4
      R0FPSXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJz
      d0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09USTVNVEl4TmpB
      d1doY05Nak13T1RJNU1USXlNVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhN
      U05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZ
      RFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0Zw
      YmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVN5S01YY2ZzdEFRS0Vt
      b3VrQ1Jack04K3ZOCmpCMWRWZk5tcXhYeWQrTTN1c0VNQzIrNlhJeDAyaFRqNXJqSmNoZDduWXk4
      SWJoSDlUc0VFeXc2MUNnQW80SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVk
      SlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBH
      QTFVZERnUVdCQlNGZFNDTlJqTFN1VUxEMkliVDltK2pkbXZrCmJUQWZCZ05WSFNNRUdEQVdnQlNz
      WFc5UjVHQzNSMjVCQ0lUbXFlOG43VFFTM1RBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6
      ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0
      TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJ
      aXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRi
      bVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdS
      UUloQU43Rm9UaXdIT0V2K1ZUQwphQ0hlZXlNaFAvY2V3d05TNjY0enFoYU1qSFBNQWlCMzRPMS96
      YzZHeHYvTkxIcThzUCtVSzVURy80c3BJaTNkCjVkdHg2cjRzMnc9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgK
      EICAgDEYgIBAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoP
      QmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgD
      EgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoG
      QWRtaW5zErsvCgtDb25zb3J0aXVtcxKrLxLgLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsYuEqoW
      CgpjYXJyaWVyTVNQEpsWGrcUCgNNU1ASrxQSpBQSoRQKCmNhcnJpZXJNU1AS5QUtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQjl6Q0NBWjZnQXdJQkFnSVVZSlVyWm8zTVJnNXVDT0ZiMGFz
      SlhWTENWWU13Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBNU1qa3hNakV5TWpa
      YUZ3MHlOVEEzTVRreE1qRXlNalphTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFa
      TWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVY
      Ck1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pP
      UFFNQkJ3TkMKQUFRRVF2VmVZa3pNYWx5Y0V5N0owR1dacTFsVmxuU1REaHhSY3k2RnRiYVJ6VHZ6
      UTBoSU00Z2ZaZ1M3Mzd2YgpZZnQ1eVVCNElETUxjVFQ3VzFrV2dIdG9vMEl3UURBUEJnTlZIUk1C
      QWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUI5dERyNDB1
      U2ZyNFZTcXZxYmJ0Y05VYUovNHdDZ1lJS29aSXpqMEUKQXdJRFJ3QXdSQUlnUlNvSFlVUnB0bFJP
      VDBIeUt6K2RqSGQ3YjVNU1d4UzRDQUFmSmwxM3FVWUNJSC9kS245dApJaWZKNXVLaUJMR2pNcVAv
      RlJSTlF2TThaY0NLYklqcW9aeUYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdUQ0NBcFNnQXdJQkFnSVVEUEVRL3NrdFhUOVZMNkF0
      WTNZcFNjNWUyek13Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05W
      QkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5
      YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBNU1qa3hNakU1
      TURCYUZ3MHlNekE1TWpreE1qSTBNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFI
      RXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1C
      Z05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRh
      VzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUkpD
      YWJYQUVuN2ptclUvcE5vS2QxMgpGZ2dUbmJ5WFNsUHBJNzRwNlcyOUpJdmVlcFFTTnlBOE8zYStz
      aWhqN01SZVA3bXUzdFZNc1ZRSFhQSzhMZjI1Cm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURB
      Z2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRlBzRjIxZzNXZEUyMXJKa2RhNkg1
      OTh3YlNaeE1COEdBMVVkSXdRWU1CYUFGQWZiUTYrTkxrbjYrRlVxcjZtMgo3WERWR2lmK01DUUdB
      MVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFprTkdNMlpqYzJaR1l0ZUdObVptd3dnWTBHCkNDb0RC
      QVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFX
      NGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJX
      NXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElq
      b2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnVDlrdXllUmJPSVVXZlExWG9R
      cGZEUzl4TUNCd1k3R2Foc0htN2Vscm0wOEMKSUdqdWNDMC9BN1B6aXdTRFA4djU0Y0JNam96U21K
      dUo4R2piNGlLZktOU1AKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2
      SuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVWUpVclpv
      M01SZzV1Q09GYjBhc0pYVkxDVllNd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1q
      QTVNamt4TWpFeU1qWmFGdzB5TlRBM01Ua3hNakV5TWpaYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4
      d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3
      SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtq
      T1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUUVRdlZlWWt6TWFseWNFeTdKMEdXWnExbFZsblNURGh4
      UmN5NkZ0YmFSelR2elEwaElNNGdmWmdTNzM3dmIKWWZ0NXlVQjRJRE1MY1RUN1cxa1dnSHRvbzBJ
      d1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0
      RUZnUVVCOXREcjQwdVNmcjRWU3F2cWJidGNOVWFKLzR3Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJ
      Z1JTb0hZVVJwdGxST1QwSHlLeitkakhkN2I1TVNXeFM0Q0FBZkpsMTNxVVlDSUgvZEtuOXQKSWlm
      SjV1S2lCTEdqTXFQL0ZSUk5Rdk04WmNDS2JJanFvWnlGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVy
      TVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1Aa
      BkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRt
      aW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5z
      KgZBZG1pbnMSuxcKD21hbnVmYWN0dXJlck1TUBKnFxqvFQoDTVNQEqcVEpwVEpkVCg9tYW51ZmFj
      dHVyZXJNU1AShgYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFn
      SVVVUFhYSHNZejFZY01JQm1BdHlUT3MzTDUzakV3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0Ex
      VUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1S
      VXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdO
      MGRYSmwKY2kxdVpYUXdIaGNOTWpJd09USTVNVEl4TURJMldoY05NalV3TnpFNU1USXhNREkyV2pC
      a01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFa
      YWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJF
      dWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJ
      QUJJdzVLdGN6ZWdVeitqSlFPRFFzQytnREtKRCs5RDhWVmZPcAppMVVzL3dIMVhOMDd6eSt2UElN
      eC9vVWRCV2pxL1JNMGpINHBneTBCQ2hWUEw1LzZOQktqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFN
      QkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFBiTUYxdDFPRHlPc3IKK2tu
      bkJ5SlRHV0NHV2pBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXkxd2RabkNvR25Qcy8xVW8zVVRT
      NkF0cQpQTWo5dFJDZi9VSkNuRlIraEY4Q0lRRE9zekFFTDJLQ3dmdUd4OWdvbWRtMnUwcFhBam9x
      YVJIeFlvMlVzMFNGCmFBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVWS1M0UzB6azJYUXlrNXhETVlK
      eWhXdjk2RVF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFn
      TUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1G
      amRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJ
      d09USTVNVEl4TnpBd1doY05Nak13T1RJNU1USXlNakF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBn
      eEdqQVlCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUx
      ClptRmpkSFZ5WlhJeEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1Ix
      Y21WeU1SOHcKSFFZRFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lI
      S29aSXpqMENBUVlJS29aSQp6ajBEQVFjRFFnQUVEUzR3ZGM3OFNwWHZ0Tk5zaTBRSGRwQnR3K2F2
      YXlST0drY0VyanZyRDZ1am55TUwvSXRjCnprKzUyenBWdFlNdHNQeHZ0SzlFK0p0NXNXTWQ5ay8z
      eWFPQ0FTSXdnZ0VlTUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBH
      QTFVZERnUVdCQlJrSWpRUGcyK2U5L1hlanR2MThORTFtT3loU2pBZgpCZ05WSFNNRUdEQVdnQlRQ
      Yk1GMXQxT0R5T3NyK2tubkJ5SlRHV0NHV2pBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAz
      WTJRM1ptUm1PVGMyTFdzM01qSjBNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kK
      WVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNh
      V0YwYVc5dQpJam9pYldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lR
      V1J0YVc1QWJXRnVkV1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlm
      VEFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlBNHh5VFlYT2o4YUVXZ21SRVJvcklNV2ZmaHp1SmVh
      cnZuZTFBVXF1eFBQd0lnS3BpZ0tEYVpTUnozWG8yNQpKSUNMRTU2Z0RFQ0w5eDdUR1lMa2lQdVUx
      V0E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqGBi0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVVVQWFhIc1l6MVljTUlCbUF0
      eVRPczNMNTNqRXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFa
      bUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05N
      akl3T1RJNU1USXhNREkyV2hjTk1qVXdOekU1TVRJeE1ESTJXakJrTVFzd0NRWURWUVFHCkV3SkRT
      REVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJB
      b00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxX
      NWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkl3NUt0Y3plZ1V6K2pKUU9E
      UXNDK2dES0pEKzlEOFZWZk9wCmkxVXMvd0gxWE4wN3p5K3ZQSU14L29VZEJXanEvUk0wakg0cGd5
      MEJDaFZQTDUvNk5CS2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJUUGJNRjF0MU9EeU9zcgora25uQnlKVEdXQ0dXakFLQmdncWhr
      ak9QUVFEQWdOSkFEQkdBaUVBeTF3ZFpuQ29HblBzLzFVbzNVVFM2QXRxClBNajl0UkNmL1VKQ25G
      UitoRjhDSVFET3N6QUVMMktDd2Z1R3g5Z29tZG0ydTBwWEFqb3FhUkh4WW8yVXMwU0YKYUE9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggB
      EgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAES
      HxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgB
      Eh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMI
      ARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hh
      bm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGll
      cxIWEgwKCgoGVjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2
      GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpO
      ChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoH
      UmVhZGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
