apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaINZIzU+DsFckK/Hu8xTira3OBPv+Ov6NWdp+86cFXj94EqpeCqdeCqReCngKWggBEAEaBgir
      8omaBiIKc3lzY2hhbm5lbCpAMWRjYzFlNzIzOGEyMGIxNTg3MDVjNmQwY2MwZjE2ZmJjNDA4Nzlk
      NTQ1NzY1YTI5MTc3ZjNkMjdhYWJkYjI0NBIaEhjL7x0gqg1H9NHPR36IDesilXQfP/SMrd8Sp10K
      pF0SoV0SnysKB09yZGVyZXISkysS1hYKDnN1cHBseWNoYWluTVNQEsMWGs8UCgNNU1ASxxQSvBQS
      uRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVVjNJWVFtMXZ1d0RROENCbFFicGNWY09RNUxvd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBNU1EY3hOakV6V2hjTk1qVXdOekk1TURjeE5qRXpX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJFMUVk
      d3hLTnhCNHF3aU90aUZRVDlhYVF6MGdULzgvSW92V2JkSkxiMDVEODFUdnRkYjUKeVAvNm1kWWVH
      RlgxNEtKdWUxY1JRWHczNXNjMFo3czluRUdqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2g3K2pSUFRYazZPUHhLd05ERzJFVnRH
      VXRZVEFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTVrQ1M4NUZHQWhNMXlEVFRmUzBXYktzdFFR
      SDlrRkVnSVBUVXErclgKczRnQ0lRQ2p3b2plVjRJbEZqajV0WHZXNWdTczRMcFJtV3VxOHBFYWds
      MzdyNW5yUEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKmCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNGpDQ0FvaWdBd0lCQWdJVUdCd0lJTUxjbUJVaC9KV1NFMU85OHFFNEFP
      TXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1EQTVNRGN5TXpBd1do
      Y05Nak14TURBNU1EY3lPREF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWZ5MkhoUWlReVYrZEZ5TUdTS0o0QWdi
      d093bWFSTjRTCi9rUUJDWXRkWkh2SlV3RnY4MjFTQVZIKy85VnNjMURWYi9KZG9TS2hFL0xBMlNi
      RzNYTWNWcU9DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUzRlVHVYSytRWQpsN1drQzk0YVhWcTR1N0RnQkRBZkJnTlZIU01FR0RB
      V2dCU2g3K2pSUFRYazZPUHhLd05ERzJFVnRHVXRZVEFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDFOalkzWXpZM1ptWTNMV3R0ZWpjME1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFNBQXcKUlFJaEFNTGMxSk1xMVA4bmlPdEpJdElrRUxoOUZvNXhCRTZHR01qTmpMQS9ZbkF1
      QWlBQ01QZXA1S2dBOWp4QwpKcUU5aFB5ZXAvZDVBM1lMak1mZUFYYjZHZmpVZ3c9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK9QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQ0FUQ0NBYWFnQXdJQkFnSVVWM0lZUW0xdnV3RFE4Q0JsUWJwY1ZjT1E1TG93
      Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlE
      VlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXhNREE1TURjeE5qRXpXaGNO
      TWpVd056STVNRGN4TmpFeldqQmVNUXN3Q1FZRFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1
      Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFa
      QmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcK
      U000OUF3RUhBMElBQkUxRWR3eEtOeEI0cXdpT3RpRlFUOWFhUXowZ1QvOC9Jb3ZXYmRKTGIwNUQ4
      MVR2dGRiNQp5UC82bWRZZUdGWDE0S0p1ZTFjUlFYdzM1c2MwWjdzOW5FR2pRakJBTUE4R0ExVWRF
      d0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTaDcralJQ
      VFhrNk9QeEt3TkRHMkVWdEdVdFlUQUsKQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBNWtDUzg1RkdB
      aE0xeURUVGZTMFdiS3N0UVFIOWtGRWdJUFRVcStyWApzNGdDSVFDandvamVWNElsRmpqNXRYdlc1
      Z1NzNExwUm1XdXE4cEVhZ2wzN3I1bnJQQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZB
      ZG1pbnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZB
      ZG1pbnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZB
      ZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoG
      QWRtaW5zIjsKC0VuZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5N
      U1AaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4K
      DEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZB
      ZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooSCg1Db25zZW5z
      dXNUeXBlEvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3
      GtMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQXFtZ0F3SUJBZ0lVQXhFYTZ2
      Y0ZrRCs3TWo0Mnp2NGdkWHhpRXU0d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3Ckho
      Y05Nakl4TURBNU1EY3lNekF3V2hjTk1qTXhNREE1TURjeU9EQXdXakJ4TVFzd0NRWURWUVFHRXdK
      SFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdk
      UGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndO
      Q0FBUzhMb1R1MVo3OUMxK1VZc1lvdzJKQXZKb3QKT2Z2WGVpSFI5TWRidlYxUnhDUlVxeUFJZklY
      V1k0TzMxcExOU2d1d0tVVlRCN2gyYmhiYy9LTE5PZkljbzRJQgpNRENDQVN3d0RnWURWUjBQQVFI
      L0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdO
      VkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU3BIcTY3SmhSbjh4aE9VQU9VaUpvNDA4L04KK0RB
      ZkJnTlZIU01FR0RBV2dCU2g3K2pSUFRYazZPUHhLd05ERzJFVnRHVXRZVEEvQmdOVkhSRUVPREEy
      Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZz
      YjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0Zt
      Wm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1
      YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJ
      S29aSXpqMEVBd0lEU0FBd1JRSWhBUGZVUS82Z2F3SlZ2WlluCkVNZHpaelRDaU9YS0swV2FPM296
      aElHN3Z2S3FBaUI0bHF0VEplcmdiSmVVTXJsRTNRMjI5M1lSSjFBeTRHLzgKZlZjanZDUjBmUT09
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURBekNDQXFtZ0F3SUJBZ0lVQXhFYTZ2Y0ZrRCs3TWo0Mnp2NGdkWHhpRXU0d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TURBNU1EY3lNekF3V2hjTk1qTXhNREE1
      TURjeU9EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1
      TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJs
      Y21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUzhMb1R1MVo3OUMxK1VZc1lvdzJKQXZKb3QK
      T2Z2WGVpSFI5TWRidlYxUnhDUlVxeUFJZklYV1k0TzMxcExOU2d1d0tVVlRCN2gyYmhiYy9LTE5P
      ZkljbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dB
      UVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU3BI
      cTY3SmhSbjh4aE9VQU9VaUpvNDA4L04KK0RBZkJnTlZIU01FR0RBV2dCU2g3K2pSUFRYazZPUHhL
      d05ERzJFVnRHVXRZVEEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBi
      aTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdC
      d2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXli
      MnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpW
      SGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBUGZVUS82Z2F3
      SlZ2WlluCkVNZHpaelRDaU9YS0swV2FPM296aElHN3Z2S3FBaUI0bHF0VEplcmdiSmVVTXJsRTNR
      MjI5M1lSSjFBeTRHLzgKZlZjanZDUjBmUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIK
      BTUwMG1zEAoYASAFKICAgAoaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFk
      bWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRl
      cnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoG
      QWRtaW5zKgZBZG1pbnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRp
      dW0SxC4SsRcKD21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVy
      ZXJNU1ASgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVj
      WCtDV0NiTFI0dDVPWjN4eXlEMTJXVXN1aEF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVC
      aE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdF
      d1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRY
      SmwKY2kxdVpYUXdIaGNOTWpJeE1EQTVNRGN4T0RFeldoY05NalV3TnpJNU1EY3hPREV6V2pCa01R
      c3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRY
      SnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJX
      RnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJG
      ZWplWWtZeWdOd2tXUTFmVHRtWWpkTStYeUlXT3p0ZnQxRwo5UzRGOENqb2pZUGFDeFM2aUpHSUlu
      amF3V1hIOEgwajdQL2VRbi9TSld2Ym94bUVVbHVqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFm
      OHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1pNMHhYVEZGYmJIbWUKN1Rrd2xR
      WVBMOGZySXpBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQW1nT2tXMjh5Ulg2NHlnQ0xQTWZzZDht
      NQplamZSZlRWUHdBQWsreXVKV3prQ0lISXRVdU5DcGNaakZ1bFVBRXJyK3ZESk1SVjdCd0pIQ1JO
      Zy8yem0zeEplCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSURFVENDQXJlZ0F3SUJBZ0lVSTh3UFV1SnRXd2RpRVg3RmVLSVFKQldhTU1F
      d0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21s
      amFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJ
      eEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNREE1TURj
      eU5UQXdXaGNOTWpNeE1EQTVNRGN6TURBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdO
      VkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhW
      eVpYSXhJekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3
      CkhRWURWUVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBD
      QVFZSUtvWkkKemowREFRY0RRZ0FFek5pS1k0Zzg0YkhZK0JhZjlKSzNTelRTL2kyWHRha0dzcGY5
      am96eVZnUUtpc2dWVVlMOAplWkFvemxMWDJFb0dhNVd0UGd4cE9NZlphWWlYNjZJOXVxT0NBU0l3
      Z2dFZU1BNEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FX
      QkJSS2hnVXM3QVZ4L091M29taWFLU2pjUHNqSDhUQWYKQmdOVkhTTUVHREFXZ0JTWk0weFhURkZi
      YkhtZTdUa3dsUVlQTDhmckl6QWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1kyUTNabVJt
      T1RjMkxUaDRkbWhrTUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVw
      Ym1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUK
      SWpvaWJXRnVkV1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFi
      V0Z1ZFdaaApZM1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Fo
      a2pPUFFRREFnTklBREJGCkFpRUEwOWRXT2V4aWNjMGRjeDlIWGRjTHZHR1VlM0FjNlJIRUVvUlNz
      ZCsrNklFQ0lGZHRFVXhqanpPTnI2Sk0KTHo3dDNVNWx5UkxoUVIvVytPRFdRZnBqbUZxWAotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVjWCtDV0NiTFI0dDVPWjN4eXlEMTJXVXN1
      aEF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFj
      bWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnla
      WEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1EQTVN
      RGN4T0RFeldoY05NalV3TnpJNU1EY3hPREV6V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdB
      MVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhi
      blZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1C
      TUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGZWplWWtZeWdOd2tXUTFmVHRtWWpkTStY
      eUlXT3p0ZnQxRwo5UzRGOENqb2pZUGFDeFM2aUpHSUluamF3V1hIOEgwajdQL2VRbi9TSld2Ym94
      bUVVbHVqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1C
      MEdBMVVkRGdRV0JCU1pNMHhYVEZGYmJIbWUKN1Rrd2xRWVBMOGZySXpBS0JnZ3Foa2pPUFFRREFn
      TklBREJGQWlFQW1nT2tXMjh5Ulg2NHlnQ0xQTWZzZDhtNQplamZSZlRWUHdBQWsreXVKV3prQ0lI
      SXRVdU5DcGNaakZ1bFVBRXJyK3ZESk1SVjdCd0pIQ1JOZy8yem0zeEplCi0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFu
      dWZhY3R1cmVyTVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoT
      EhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAa
      ExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggA
      GhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/
      FAoDTVNQErcUEqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIrRENDQVo2Z0F3SUJBZ0lVTW9IR0o0Z0VWN29yTnkyY05Mejc4aXI5NzZ3d0NnWUlLb1pJ
      emowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVq
      WVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXdNRGt3TnpJd01UUmFGdzB5TlRBM01qa3dOekl3
      TVRSYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05W
      QkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1
      WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUmhsN0NW
      V2RnZWFOMGU1bWtJOFFRQ2txdXViTXlDc1M5ZmtRcWpqdTNWSkRrZDJSblFXZE1XVEk5RU5uVVYK
      TS96cDdqTkFSR1FQWU9kenUxNzI2bTl2bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdB
      MVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVmYWNiMk1VUGtncFJ5amN5LzVzRk5yTFg5
      RkV3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFOY1QwN0lxK25hWTdDUWJkcnRNakhyRVNpdlRL
      QkFxQXd6b1l2V3JjR2xxQWlCdnVtZ0UKVWhYSzlvd2lzbmt1bHVycTZmZ2lqSjlJQzEySUhadGtI
      aWZvOXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlDN1RDQ0FwU2dBd0lCQWdJVVErSVpEL2JycTFLNWg1ak5lUXRqRTNIVU1qQXdD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURW
      UVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV3TURrd056STNNREJhRncweU16RXdN
      RGt3TnpNeU1EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRN
      QzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmti
      V2x1TUE0R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRU3BqQ3hkYVZDcGk0Ny94
      TndjNlpCCmxJS2dyTU1JUm9tMXA3VzQ3SncvSWJ1UG9hSHRaNTN6dkJXY1IvSFhsdXV3MTFpWkZz
      a3VCNCs3Q1pPSHpuc2sKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3
      RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpGRndWb0pGVnErRFFrU1FMdTJpUVFjTjdnVHB0TUI4R0Ex
      VWRJd1FZTUJhQUZIMm5HOWpGRDVJS1VjbzNNditiCkJUYXkxL1JSTUNRR0ExVWRFUVFkTUJ1Q0dX
      TmhMWFJ2YjJ4ekxUWmtOR00yWmpjMlpHWXRkbTFvYXpnd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5
      SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElp
      d2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRF
      bEVJam9pUVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgw
      d0NnWUkKS29aSXpqMEVBd0lEUndBd1JBSWdXMmRzdkFmRnlHRkZYY3BReWtuYnhaS2lKS1dwTkRt
      ZGU4bXZGc2NWUHBJQwpJQWFqNjBZbVMzRDcxdTNpbVRuOXRiaVFnQkIvU3Awa0ZYbndkMmZOckdL
      MAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVNb0hHSjRnRVY3b3JOeTJjTkx6
      Nzhpcjk3Nnd3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFd01Ea3dOekl3TVRS
      YUZ3MHlOVEEzTWprd056SXdNVFJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFa
      TWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVY
      Ck1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pP
      UFFNQkJ3TkMKQUFSaGw3Q1ZXZGdlYU4wZTVta0k4UVFDa3F1dWJNeUNzUzlma1Fxamp1M1ZKRGtk
      MlJuUVdkTVdUSTlFTm5VVgpNL3pwN2pOQVJHUVBZT2R6dTE3MjZtOXZvMEl3UURBUEJnTlZIUk1C
      QWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWZhY2IyTVVQ
      a2dwUnlqY3kvNXNGTnJMWDlGRXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU5jVDA3SXErbmFZ
      N0NRYmRydE1qSHJFU2l2VEtCQXFBd3pvWXZXcmNHbHFBaUJ2dW1nRQpVaFhLOW93aXNua3VsdXJx
      NmZnaWpKOUlDMTJJSFp0a0hpZm85dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1p
      bnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1p
      bnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIz
      CgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFk
      bWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMa
      QAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJl
      ci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoX
      L0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hp
      bmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0
      dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5z
      dXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0
      aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoG
      QWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
