apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.66.8.13:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIEFLO8B/1I6HEeqOlEogFcAWPE2eVBzlGSXoyS3pn35LEqJeCp9eCpxeCngKWggBEAEaBgjV
      o72cBiIKc3lzY2hhbm5lbCpAOGJiMDU0NmE3M2QyODA0ZTI0MzkxZWE5OTllOWUyNTE1MmM2ZWE5
      OTQ4NTc5ZjI1MTYwMjNhOGEzMDcyMjhmNxIaEhiMJq3VxkC5BF7Tpn6EW+KGmtmWRBP7hfMSn10K
      nF0SmV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVV2FGZ2gwenZ2SFVCMFBNREE5U1M0ZFdOdEpJd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBMk1UUXhOVFV3V2hjTk1qVXdPVEkxTVRReE5UVXdX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJMdUhx
      N3ZRQmtHN1phait5NkhEUjlMa3NjNzN5Mi9TSHRzbDM2bkgwaTR1SHEzZDV6K3QKSUxyRlh4ZmpP
      MTZMQlZUdVJqclk5YTZodlFLZmlmOWpYWHVqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU01aUE9LS3dIY1pEeWh0MEN3TXZQWDAy
      aHpxVEFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlBaThDeTRFbDZXcjBNczc5TFRDT0VMcEJmVE05
      RTdJbmk0Z25uRTN0clcKOVFJZ05wSVg2b3k3bldkL01zR1BUVGJNcVd3Q3pJTUNnTGsrY1BYdWp3
      d2NZZnc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUMzekNDQW9hZ0F3SUJBZ0lVVDRYVjg5L0tuNGduSm1zcUVZay9INnc0alNNd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBMk1UUXlNVEF3V2hjTk1q
      TXhNakEyTVRReU5qQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFUGpzOE90YWJySG1LY1MwQzgwLzcyZ0FsL2hN
      Mkw5MkgKclNFUXN3UFpHVkk1Uzd3OEY5N0VFZVVYT1lQMUFnazl3NVp5U2x3ZHpKcjE4OWNUR1VB
      RGtxT0NBUkl3Z2dFTwpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSb04rRW56L2VjCnZpcGpNUXkxZklaTjdZNDNLekFmQmdOVkhTTUVHREFXZ0JT
      TVpQT0tLd0hjWkR5aHQwQ3dNdlBYMDJoenFUQWkKQmdOVkhSRUVHekFaZ2hkallTMTBiMjlzY3kw
      MU5UazVOalJqTmkxak5HcHpkakNCaVFZSUtnTUVCUVlIQ0FFRQpmWHNpWVhSMGNuTWlPbnNpWVdK
      aFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtCkxrRm1abWxzYVdG
      MGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYzNWd2NHeDUKWTJo
      aGFXNHRibVYwSWl3aWFHWXVWSGx3WlNJNkltRmtiV2x1SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGNB
      TUVRQwpJRnk4bkJrY1l1eVNyN2pHaXJxVzhmNi9pZmlNbmJqc0gxL0F3dmNScXZ2cEFpQmN1WWhx
      aTV5VitqNG4vSDJ6ClpubWV3eFhjNk03MytPd1VTaUZES3ZEYWJ3PT0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVV2FGZ2gwenZ2SFVCMFBNREE5U1M0ZFdOdEpJd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBMk1UUXhOVFV3V2hjTk1qVXdPVEkx
      TVRReE5UVXdXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJMdUhxN3ZRQmtHN1phait5NkhEUjlMa3NjNzN5Mi9TSHRzbDM2bkgwaTR1SHEzZDV6K3QK
      SUxyRlh4ZmpPMTZMQlZUdVJqclk5YTZodlFLZmlmOWpYWHVqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU01aUE9LS3dIY1pEeWh0
      MEN3TXZQWDAyaHpxVEFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlBaThDeTRFbDZXcjBNczc5TFRD
      T0VMcEJmVE05RTdJbmk0Z25uRTN0clcKOVFJZ05wSVg2b3k3bldkL01zR1BUVGJNcVd3Q3pJTUNn
      TGsrY1BYdWp3d2NZZnc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooSCg1Db25zZW5zdXNUeXBlEvgREu0R
      CghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3GtMILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQXF1Z0F3SUJBZ0lVUFFLdEdDVXE1WDhNM0kwaE53
      OFJ1cEtpaDFZd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBMk1U
      UXlNVEF3V2hjTk1qTXhNakEyTVRReU5qQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU3o3clpzYWc5
      bmFmOEQrZERjSUtyYmwzVjUKYVI2UE04L0RoM1kzcjBTL2JIYmFGbGVWTytuQ3Q2VXhCR2lheWs0
      TDRpd3J2OXliN2gxWVRZSnNNRXRabzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUlluV1c5L2Qza3lxdHpIVkR4VW15STl1RjcKMWpBZkJnTlZIU01FR0RB
      V2dCU01aUE9LS3dIY1pEeWh0MEN3TXZQWDAyaHpxVEJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZr
      ClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJw
      YjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxq
      YUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFE
      QWdOSUFEQkZBaUVBd2c0VXVURThpL3paCmVITFdnUjJPSXNlcUdhdEpBOTZVaGs5TUlmRGc0T29D
      SURKZnJ2a0dsMlZ6Z0l1aGlldllRbDIzaXE4TmdaUGQKa25qNlRmZWJhSmcrCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQXF1
      Z0F3SUJBZ0lVUFFLdEdDVXE1WDhNM0kwaE53OFJ1cEtpaDFZd0NnWUlLb1pJemowRUF3SXcKWGpF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxq
      YUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBMk1UUXlNVEF3V2hjTk1qTXhNakEyTVRReU5qQXdXakJ4
      TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1
      TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lE
      VlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQ0FBU3o3clpzYWc5bmFmOEQrZERjSUtyYmwzVjUKYVI2UE04L0RoM1kz
      cjBTL2JIYmFGbGVWTytuQ3Q2VXhCR2lheWs0TDRpd3J2OXliN2gxWVRZSnNNRXRabzRJQgpNakND
      QVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JC
      Z0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUlluV1c5L2Qza3lxdHpI
      VkR4VW15STl1RjcKMWpBZkJnTlZIU01FR0RBV2dCU01aUE9LS3dIY1pEeWh0MEN3TXZQWDAyaHpx
      VEJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXla
      R1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZ
      WFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBT
      VVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2li
      M0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBd2c0VXVURThpL3paCmVITFdn
      UjJPSXNlcUdhdEpBOTZVaGs5TUlmRGc0T29DSURKZnJ2a0dsMlZ6Z0l1aGlldllRbDIzaXE4Tmda
      UGQKa25qNlRmZWJhSmcrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAF
      KICAgAoaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1p
      bnMSvS8KC0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SyC4SsRcKD21h
      bnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVOMC8zQUtncFA1dmdv
      TENyaFNWRTBDSzdTc1F3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpJeE1qQTJNVFF4TmpVNFdoY05NalV3T1RJMU1UUXhOalU0V2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJNN2dCa2dITVhRODhq
      TWEwYnZZU0VZTEhJT0JhS2RQdEozTwpWdC91UUswY2RNc1k3U0MwUEY4RGpSbEd0RlplcHp5RnpB
      ekRBYVhjamdHWXA2NTZPVE9qUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0tMVk1HTEtNRWJmVDAKaStMeGJMRjZ2VGF1UERBS0Jn
      Z3Foa2pPUFFRREFnTklBREJGQWlBMHRJa2gzSHNUckxZcXN6b3FvOFpLVTg5QQpWa2YwVHd0dTNH
      MnpYU29COXdJaEFKcmNMNk83aHMwaVZtWlJWdWZGRWxub205VC82WGhhb3pTUmM0ZnlNUHM1Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURFVENDQXJlZ0F3SUJBZ0lVU2VaaXJDZkZhVzFSRFhLT3JSQjJJZVBscnI4d0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakEyTVRReU16QXdXaGNOTWpN
      eE1qQTJNVFF5T0RBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpN
      NEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdO
      VkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJa
      QlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemow
      REFRY0RRZ0FFUFJ0NUtqR1Q3dDVEV29CdFBkQVNZSGtFT2hIaTJqSTRjN20yWVgxeVlCN0FjNmw3
      UnJKMApmSlkybm9tRkVXR2FrSmk5RWZaN3FSSjZJdlZpaVZZZHBxT0NBU0l3Z2dFZU1BNEdBMVVk
      RHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSWVRxWHJHNTJu
      alVjVC9YWklzYStCNldOU0REQWYKQmdOVkhTTUVHREFXZ0JTS0xWTUdMS01FYmZUMGkrTHhiTEY2
      dlRhdVBEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMU5qYzVaR1JrT1RRM0xYaHVhbVpy
      TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEox
      WlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1po
      WTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1Ix
      Y21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklB
      REJGCkFpRUFwUWRUMDl1SEJPM0ozTTNCSG93TWl6TDBuUlcrSEQrdWttM0hKK3BWLzg0Q0lEMHRp
      c3l5QzVVbjhFd3kKVTVkWVl4SWFScGFHOVdpN0JnMGRneFo3R01zcQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQ0REQ0NBYktnQXdJQkFnSVVOMC8zQUtncFA1dmdvTENyaFNWRTBDSzdTc1F3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qQTJNVFF4TmpVNFdoY05N
      alV3T1RJMU1UUXhOalU0V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlh
      V05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxj
      akVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJNN2dCa2dITVhRODhqTWEwYnZZU0VZTEhJT0JhS2RQdEozTwpW
      dC91UUswY2RNc1k3U0MwUEY4RGpSbEd0RlplcHp5RnpBekRBYVhjamdHWXA2NTZPVE9qUWpCQU1B
      OEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      U0tMVk1HTEtNRWJmVDAKaStMeGJMRjZ2VGF1UERBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlBMHRJ
      a2gzSHNUckxZcXN6b3FvOFpLVTg5QQpWa2YwVHd0dTNHMnpYU29COXdJaEFKcmNMNk83aHMwaVZt
      WlJWdWZGRWxub205VC82WGhhb3pTUmM0ZnlNUHM1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1
      cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0
      dXJlck1TUBABGgZBZG1pbnMqBkFkbWlucxK2FgoKY2Fycmllck1TUBKnFhrDFAoDTVNQErsUErAU
      Eq0UCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrVENDQVo2
      Z0F3SUJBZ0lVWThXNjNsUFA1VUVkSzd2RG0weEhsbUZoZVpFd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5
      TFc1bGREQWVGdzB5Ck1qRXlNRFl4TkRFNE1EUmFGdzB5TlRBNU1qVXhOREU0TURSYU1Gb3hDekFK
      QmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2
      YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUWhMQTBlSDVVUlM5TnNmRzlP
      eHdKMUtBcENHaDJVaHBRWnViWk1HUFNmZk9CYnQ3Rm9ocnBZNEplYTluZXoKTE9SYWFBb1VPak92
      amM3UFcyUFFSejF6bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FF
      QXdJQnBqQWRCZ05WSFE0RUZnUVVydEc0SjdFUUVVNHVocU5CQjhSdjdIKzJMYjh3Q2dZSUtvWkl6
      ajBFCkF3SURTUUF3UmdJaEFMalhWQ1hmVlZmRHRoL0dCeE5FQjRxazZ2NGlITTRjNlVtVDRXNjd6
      MHVHQWlFQWtpTkkKTWhuYVlKOTFmL1EvMUxTd3hydWNtclFyRXgzcUtHQ2tZUlJyZWEwPQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      N2pDQ0FwU2dBd0lCQWdJVU40R1NWVWMraHpmNjBFb1cyalZBeTFGN0p4SXdDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNakV5TURZeE5ESTBNREJhRncweU16RXlNRFl4TkRJNU1EQmFN
      SGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWti
      MjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVD
      eE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUVFk5cG1hdXdFNDN3WFR4TEtPZ3dwClRGRUZD
      WDE2MEEvTEZCSmlRTVFmNWd2RTRib2tzMkQxZ2gwZ1VESnExVlc4MU90NGhqWEl3aXlwY0JVUEtS
      b2gKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRQpGR2hkYTczc0d5L254b2RDV25Db1RtdmlMOHpuTUI4R0ExVWRJd1FZTUJhQUZL
      N1J1Q2V4RUJGT0xvYWpRUWZFCmIreC90aTIvTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxU
      WTFOelprTm1abVpEVXRPWGM1Tm1Rd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5
      SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFX
      eHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFX
      NUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpq
      MEVBd0lEU0FBd1JRSWhBTWdnYmgvRkM1UTdKa3MzeE10d1VQY0Z2YjJUbzBCejIyR21kWXE0Z01u
      bApBaUErQ0VMelovNUpHRTBsMXp4QzFUeGpjRys4WHltTWxVRlVkTEdyRVJSSUJ3PT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUIrVENDQVo2Z0F3SUJBZ0lVWThXNjNsUFA1VUVkSzd2RG0weEhsbUZoZVpF
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXlNRFl4TkRFNE1EUmFGdzB5TlRB
      NU1qVXhOREU0TURSYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0
      eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFV
      RUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05D
      CkFBUWhMQTBlSDVVUlM5TnNmRzlPeHdKMUtBcENHaDJVaHBRWnViWk1HUFNmZk9CYnQ3Rm9ocnBZ
      NEplYTluZXoKTE9SYWFBb1VPak92amM3UFcyUFFSejF6bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFE
      QVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVydEc0SjdFUUVVNHVocU5C
      QjhSdjdIKzJMYjh3Q2dZSUtvWkl6ajBFCkF3SURTUUF3UmdJaEFMalhWQ1hmVlZmRHRoL0dCeE5F
      QjRxazZ2NGlITTRjNlVtVDRXNjd6MHVHQWlFQWtpTkkKTWhuYVlKOTFmL1EvMUxTd3hydWNtclFy
      RXgzcUtHQ2tZUlJyZWEwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjMKB1Jl
      YWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIg
      CAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIo
      Eh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5u
      ZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3Jp
      dGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI
      /////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwK
      CgoGVjFfNF8zEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
