apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.172.161.165:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIBfkRUZOqCa1JFX0aDNpGdo4ntqf5rg+kYoT2ZpUX/XMEppeCpdeCpReCngKWggBEAEaBgiF
      ytajBiIKc3lzY2hhbm5lbCpAMTVjNDM5NDc2ZGM3YzJlODFlYWJlMDBlZjQwYjlhNmZhZGMzNzE2
      YjQ1NmM2YTQwZDlmNjBjMmI0ODMwN2Q3MRIaEhiGzc5vxc/FNrDT81IqdWlcwdtrDFI3Yc0Sl10K
      lF0SkV0SkSsKB09yZGVyZXIShSsSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVUnhKOWpmcFkxelh6dWNYUTV3S2lJWnlTZHV3d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRNd01EY3hNekV6V2hjTk1qWXdNekU1TURjeE16RXpX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJNeW9F
      NUxIOGxES2g5ZW55Y05ia2ttL0RiWGhGZjA2RXhobGZDS0IyYzFyUTRFangvMnoKUGFhUW1BdXBC
      MEI0d2ZMa3Ftc1d6NWFhNGVqQ1I3bGw2b2lqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUmhjbFViYW5pdGl5Y2Z6TDE2bjZacFA0
      WTRXakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXZOVGJhQUl6Z2hnMmhmOXhUaG1UbUpDWHhu
      MTJpblYzSVpCOFRXemIKY0pnQ0lINEZ1VzJ5ay9KRWV0SGVOWjY3N3c2WW43aFYxWlg2ZG91d0s0
      dm5CZ1h4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0RENDQW9lZ0F3SUJBZ0lVWEVyS2taR29uaVM4S1hWTnBJVDRQalV1YjNzd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRNd01EY3hOakF3V2hjTk1q
      UXdOVEk1TURjeU1UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZ1lWSWdURTRLVEYzQlQvQ0p2TWtoWGVBQml3
      dGRCR0YKZkRjdGVQTVFWdURVamJEL2hsTDZDNHZpK2pvYnhEMjA5UDhUUzhScUpCNzZ2WStVUXlC
      aGtxT0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSV1d2aFo5RnlXCmY1REloM3dXUHg3cU1TODR1REFmQmdOVkhTTUVHREFXZ0JS
      aGNsVWJhbml0aXljZnpMMTZuNlpwUDRZNFdqQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kw
      MVpqWTNOR1ptTkRjdGJuWXlPWFF3Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05I
      QURCRQpBaUJzM2xnakQxaXN2MUt6VDlFRy9EWXMxalI2YS9uaG9HVC9vRi9ocEVER1FRSWdSRjhU
      bGlVdm1ZMkZ2Y0lJCml0MHlNcGJvcisrb0poSEVDOEVyQlFpUUJVOD0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVUnhKOWpmcFkxelh6dWNYUTV3S2lJWnlTZHV3d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TlRNd01EY3hNekV6V2hjTk1qWXdNekU1
      TURjeE16RXpXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJNeW9FNUxIOGxES2g5ZW55Y05ia2ttL0RiWGhGZjA2RXhobGZDS0IyYzFyUTRFangvMnoK
      UGFhUW1BdXBCMEI0d2ZMa3Ftc1d6NWFhNGVqQ1I3bGw2b2lqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUmhjbFViYW5pdGl5Y2Z6
      TDE2bjZacFA0WTRXakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXZOVGJhQUl6Z2hnMmhmOXhU
      aG1UbUpDWHhuMTJpblYzSVpCOFRXemIKY0pnQ0lINEZ1VzJ5ay9KRWV0SGVOWjY3N3c2WW43aFYx
      Wlg2ZG91d0s0dm5CZ1h4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOwoLRW5k
      b3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyoG
      QWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0
      aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxqKEgoN
      Q29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWlu
      LW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQlRDQ0FxdWdBd0lCQWdJ
      VUdYYmVvbkRNcDVoMnk2OXgvelJZVGQ0VWswVXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1
      WlhRdwpIaGNOTWpNd05UTXdNRGN4TmpBd1doY05NalF3TlRJNU1EY3lNVEF3V2pCeE1Rc3dDUVlE
      VlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lE
      VlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2
      Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pP
      UFFNQkJ3TkNBQVJwMVhibnBFY0QxMm9zb1VnaGl3TElNQUdPCnNzZ2o2d0FwRHh2RTdVM1NVQ3VD
      YXZTdnBOU09PcTRRZVk3UGpQQ25iQVg3b1I2NmlrZlJsa3FRdDlLVW80SUIKTWpDQ0FTNHdEZ1lE
      VlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNE
      QWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlIvb3o5cWUxOFB3anQ0eUF2TytuOUhi
      dkJaCldEQWZCZ05WSFNNRUdEQVdnQlJoY2xVYmFuaXRpeWNmekwxNm42WnBQNFk0V2pCQkJnTlZI
      UkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhM
      blZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlP
      bnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZj
      bVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxj
      aUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQXlGL3cyMi91RkFSawpzc0d4bGlRVnRPaTFX
      c0hNaUl2SjRaTUlPK0tsZmQ0Q0lHTDBhck5hN1F1RmlpSUNPa1IwSkowRTZSeFVYSUg3CnFJTGZM
      ZFJXbWdqRgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlEQlRDQ0FxdWdBd0lCQWdJVUdYYmVvbkRNcDVoMnk2OXgvelJZVGQ0VWswVXdD
      Z1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURW
      UVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd05UTXdNRGN4TmpBd1doY05N
      alF3TlRJNU1EY3lNVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVO
      VEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxF
      d2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJwMVhibnBFY0QxMm9zb1VnaGl3
      TElNQUdPCnNzZ2o2d0FwRHh2RTdVM1NVQ3VDYXZTdnBOU09PcTRRZVk3UGpQQ25iQVg3b1I2Nmlr
      ZlJsa3FRdDlLVW80SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01C
      UUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERn
      UVdCQlIvb3o5cWUxOFB3anQ0eUF2TytuOUhidkJaCldEQWZCZ05WSFNNRUdEQVdnQlJoY2xVYmFu
      aXRpeWNmekwxNm42WnBQNFk0V2pCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JB
      WUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxD
      Sm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      aUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlF
      QXlGL3cyMi91RkFSawpzc0d4bGlRVnRPaTFXc0hNaUl2SjRaTUlPK0tsZmQ0Q0lHTDBhck5hN1F1
      RmlpSUNPa1IwSkowRTZSeFVYSUg3CnFJTGZMZFJXbWdqRgotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEY
      gIBAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tW
      YWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1Jl
      YWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5z
      ErkvCgtDb25zb3J0aXVtcxKpLxLeLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsQuErIWCgpjYXJy
      aWVyTVNQEqMWGr8UCgNNU1AStxQSrBQSqRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVWbHR3SWVJaDZ5cXZIS0o5bDBmSEpxZ1Va
      OUV3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dG
      UVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBMU16QXdOekUxTkRaYUZ3MHlO
      akF6TVRrd056RTFORFphTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWti
      MjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdB
      MVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkMKQUFSQlZWQU56Q1MwZzh5c01jb2M0VkVLQ0l2aitkT04ydCt5ckJTVWlnY1Frd1BOM1dPdkhY
      UlQrYW44M3gzWQptbWlDZnQrMEJ5VEVxY2cvWG9zU1dodGNvMEl3UURBUEJnTlZIUk1CQWY4RUJU
      QURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWJLSzlMVXd0aVNodGh0
      M0NuTUZLUk00SXJMQXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQVAzdERsdTBHSTM4VUxMSWJB
      eG5GNDhTMEkvZUIxY2FMVENaZGdob0dDYmVBaUFNZXNiaQovb2Y2RUMvOVlVN0pjY0ZmOUhCb1Rm
      SHVueXdnN1FSRjZmK1B5Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrIILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3VENDQXBPZ0F3SUJBZ0lVYU9ycFlza0thTVQzS1FZODBY
      S2xXQ1JIck5jd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFX
      VnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck16QTFNekF3TnpJd01E
      QmFGdzB5TkRBMU1qa3dOekkxTURCYU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4
      STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdO
      VgpCQXNUQldGa2JXbHVNQTRHQTFVRUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1
      QVkyRnljbWxsCmNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJRd2pS
      Y3R3engvRngyaGk4MXNBUGsKRWxmMGFCdVE5dzJJbHNBMGZYUlIxNTBYOVQvdG1lQktqVjJuWFlW
      Tm1tdXY2Nk03NWV4OWVkUmJKUll5S01kUgpvNElCRnpDQ0FSTXdEZ1lEVlIwUEFRSC9CQVFEQWdl
      QU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFCkZJbWxLaW5BNWtBZitGamg1TmpGSVE3
      bDFiRUlNQjhHQTFVZEl3UVlNQmFBRkd5aXZTMU1MWWtvYlliZHdwekIKU2tUT0NLeXdNQ01HQTFV
      ZEVRUWNNQnFDR0dOaExYUnZiMnh6TFdNMU9HWmtPR1kwTkMxb1kySnhiRENCalFZSQpLZ01FQlFZ
      SENBRUVnWUI3SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2
      CkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRHbHZiaUk2SW1OaGNuSnBaWElpTENKb1ppNUZibkp2
      Ykd4dFpXNTAKU1VRaU9pSkJaRzFwYmtCallYSnlhV1Z5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpo
      WkcxcGJpSjlmVEFLQmdncQpoa2pPUFFRREFnTklBREJGQWlFQTZvRm9HdUtpbGlNWFNqR0Ewb0gv
      OGkwMVhTbW9QQ3NHbmIzeFlocndNMUlDCklCdFNiN2dXK0IyTVF2cXZCNTNObDBrTk5qWGoxWVBy
      Y3hBSVE4U242TGdYCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkrp
      BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVZsdHdJZUlo
      NnlxdkhLSjlsMGZISnFnVVo5RXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4
      RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFL
      REFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekEx
      TXpBd056RTFORFphRncweU5qQXpNVGt3TnpFMU5EWmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdE
      UVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hR
      MkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQwpBQVJCVlZBTnpDUzBnOHlzTWNvYzRWRUtDSXZqK2RPTjJ0K3ly
      QlNVaWdjUWt3UE4zV092SFhSVCthbjgzeDNZCm1taUNmdCswQnlURXFjZy9Yb3NTV2h0Y28wSXdR
      REFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVG
      Z1FVYktLOUxVd3RpU2h0aHQzQ25NRktSTTRJckxBd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhB
      UDN0RGx1MEdJMzhVTExJYkF4bkY0OFMwSS9lQjFjYUxUQ1pkZ2hvR0NiZUFpQU1lc2JpCi9vZjZF
      Qy85WVU3SmNjRmY5SEJvVGZIdW55d2c3UVJGNmYrUHlnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUt
      LS0tLQoaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQ
      EAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJN
      U1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoG
      QWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1p
      bnMqBkFkbWlucxKxFwoPbWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVm
      YWN0dXJlck1TUBKBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lC
      QWdJVUlkN0hKb2xqMmdlWW1taXRTTHpnajBRMzhnRXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtH
      QTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8K
      TVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1Z
      V04wZFhKbApjaTF1WlhRd0hoY05Nak13TlRNd01EY3hORE13V2hjTk1qWXdNekU1TURjeE5ETXdX
      akJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhE
      QVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZ
      MkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhB
      MElBQkVyOXNraVFieGpNdi80VERtVGgvaGtEdHY4UHFIYTJWMnFVCmwxSDJscTA5RloxRkxXMXhr
      Q0x3c0xWMWhWZFd0SU9PTHFJSlpRQmhoU1BBVDR1Zzh5aWpRakJBTUE4R0ExVWQKRXdFQi93UUZN
      QU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTby9mNnJMWFdvNDNoZQpN
      NHo0SFI4Ulk5TVNBVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUJIbW95bUtoN0J0QlF1RUZDUEtQ
      SGhOeW9OCnhSeS9MOHZxMFdJS1NjLzhpZ0loQU1naStMYktwSTdxYTFSRytwZ0d0ZXlISTlqOUhM
      NFVPL0RXMUdrS0dRN3cKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVSYndxSjRoRTZnd3RqM1VLbVBKSjBW
      SG4ySTh3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJs
      cDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRI
      VnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpNd05U
      TXdNRGN4T0RBd1doY05NalF3TlRJNU1EY3lNekF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdq
      QVlCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClpt
      RmpkSFZ5WlhJeEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21W
      eU1SOHcKSFFZRFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29a
      SXpqMENBUVlJS29aSQp6ajBEQVFjRFFnQUVkaUJrZFZYUDNsZ1NGZ0REakdlcjBqSlZHaEVCSXJx
      b0VkZEFBUFl2Y1o4Q1grWU4yYU1PCis4ZisxUTgreWJaWitTQ2NQUEZlNjE3M2JobjZrRERvUDZP
      Q0FTSXdnZ0VlTUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFV
      ZERnUVdCQlRsTlh3WGl6emJYMDNJRzZPZnUwYS9oNnV6dGpBZgpCZ05WSFNNRUdEQVdnQlNvL2Y2
      ckxYV280M2hlTTR6NEhSOFJZOU1TQVRBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAxTlRS
      bU9XUTRZalZrTFhSMFozTTVNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdK
      aFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0Yw
      YVc5dQpJam9pYldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0
      YVc1QWJXRnVkV1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFL
      QmdncWhrak9QUVFEQWdOSEFEQkUKQWlCSkY5QUpNam9DVVJaK0lXK29JcEJuK2dSc1l4RzI4S3Yz
      Ky9jdXpFMmgzd0lnQnZja3hlM09VMTFxbkgyNwpyUmFKblFERG5XZW94RDJFemE3cW5tMm56anM9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVUlkN0hKb2xqMmdlWW1taXRTTHpn
      ajBRMzhnRXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdN
      QmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZq
      ZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nak13
      TlRNd01EY3hORE13V2hjTk1qWXdNekU1TURjeE5ETXdXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQ
      TUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00K
      REUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxk
      REJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkVyOXNraVFieGpNdi80VERtVGgv
      aGtEdHY4UHFIYTJWMnFVCmwxSDJscTA5RloxRkxXMXhrQ0x3c0xWMWhWZFd0SU9PTHFJSlpRQmho
      U1BBVDR1Zzh5aWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURB
      Z0dtTUIwR0ExVWREZ1FXQkJTby9mNnJMWFdvNDNoZQpNNHo0SFI4Ulk5TVNBVEFLQmdncWhrak9Q
      UVFEQWdOSUFEQkZBaUJIbW95bUtoN0J0QlF1RUZDUEtQSGhOeW9OCnhSeS9MOHZxMFdJS1NjLzhp
      Z0loQU1naStMYktwSTdxYTFSRytwZ0d0ZXlISTlqOUhMNFVPL0RXMUdrS0dRN3cKLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMS
      EQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoT
      EhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoV
      EhMKD21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYI
      ARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVh
      dGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhIS
      CAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8a
      BkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0
      OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJf
      MBIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMqBkFkbWlucxoOCgQKAgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
