apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://34.83.218.105:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: supplychain-net

    genesis: |-
      CiIaIODzz9W6JqnjOtk2hKnPHEgWYN/e2u9OqXkEdwWtf+zHEp5eCpteCpheCngKWggBEAEaBgjB
      7OqcBiIKc3lzY2hhbm5lbCpAYWQ2YTRlMTkyZDBiZjUzMDJmNDNiYTNiOTRlN2NmOWNiYjc0MTU2
      NWQ4ZTAwZmJhZDljN2Y5OGJjMGY0OGQ0MBIaEhjV/w0TvW3N+WbUgj7SbY2MSeF/x7Rf+NsSm10K
      mF0SlV0SuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcK
      D21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVmQUwvWjBjMzhv
      RXRjbVFubUhFVmYvRjdIRk13Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpJeE1qRTFNRFV6TnpBMldoY05NalV4TURBME1EVXpOekEyV2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQK0VnWi9leThl
      OUN2RTc2TUdYMWl2OS83V3dIYk41K2gxTwo4ZmdyUW5naW44bDM4Yk1sN1R1QkpISmlXRDd1clBx
      cTNLOFAvMFhITkZpUmFNVy96RGFqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUkowYnBPTGNNRE9sVU8KbWxPL2h1UTNpbnhzYnpB
      S0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBYU9BR1NybTQ2bmdZeWRSTjV2SnBwdFJRSQpHRFFqZ0NS
      WThYb0EyMXZSN2dJZ0xVa1lVNXJieERucDBVZURuajI1anIyZzBCMGVPcENFRldNYzlzcWJGdzQ9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURFVENDQXJlZ0F3SUJBZ0lVRE5qQ3g2VitPRURKSFJrTTd1Mk4weHJ2Qk5Vd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakUxTURVME5EQXdXaGNO
      TWpNeE1qRTFNRFUwT1RBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEz
      TGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFN
      QmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFE
      REJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkK
      emowREFRY0RRZ0FFWDFpZGZ0L21tTzZsVnVPRmpFaEZRRzJ2TmpQNkRVeGxtM2UyeCtGNU0wcWdZ
      Y1NsOWtKbgo3VS9OSHRYUXptQXFWTkl4SG92L21OamNtNDdNOXN3eW5hT0NBU0l3Z2dFZU1BNEdB
      MVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTT0E2eWI3
      QTJ2TE5ITDJDcWhwdTFmNngxUVVEQWYKQmdOVkhTTUVHREFXZ0JSSjBicE9MY01ET2xVT21sTy9o
      dVEzaW54c2J6QWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM09XSm1OalZqTmprMExXTTFl
      bU0xTUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVk
      V1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZ
      M1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TklBREJGCkFpRUFrUnEzcGEvUVV5eWR0Z2pBWDZUeTRzaHlnYXQ2SG85NG1Ya0drT3RSSlQ0Q0lH
      NEdrZ3BvVWFaYk94bkQKalplYk5aZXRvd056MVpZVHNocXk1ZVQ3WkFROAotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVmQUwvWjBjMzhvRXRjbVFubUhFVmYvRjdIRk13Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qRTFNRFV6TnpBMldo
      Y05NalV4TURBME1EVXpOekEyV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1du
      VnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRY
      SmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NN
      NDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQK0VnWi9leThlOUN2RTc2TUdYMWl2OS83V3dIYk41K2gx
      Two4ZmdyUW5naW44bDM4Yk1sN1R1QkpISmlXRDd1clBxcTNLOFAvMFhITkZpUmFNVy96RGFqUWpC
      QU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdR
      V0JCUkowYnBPTGNNRE9sVU8KbWxPL2h1UTNpbnhzYnpBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlB
      YU9BR1NybTQ2bmdZeWRSTjV2SnBwdFJRSQpHRFFqZ0NSWThYb0EyMXZSN2dJZ0xVa1lVNXJieERu
      cDBVZURuajI1anIyZzBCMGVPcENFRldNYzlzcWJGdzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVy
      TVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcU
      EqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrREND
      QVo2Z0F3SUJBZ0lVZXZ6VzlQaklCamVEcGJ6NWI1N2FXMk52Vitvd0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck1qRXlNVFV3TlRNNE1UUmFGdzB5TlRFd01EUXdOVE00TVRSYU1Gb3hD
      ekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZi
      bVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUUhGdHVKRjA2TUxzYnFK
      ZTBpK3AxOWhYcmIxQ1hSWFhPSXN1SGY5aDlVV3JIc2FVK1Y5OStERVh5YlRlNlYKSU5ta3lJZVF3
      ODFrYjF6RzZBWXcza0dJbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgov
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVUwem9HcmRBR2RCcHZtTDh1VkM5MjhBWnpQWEl3Q2dZSUtv
      Wkl6ajBFCkF3SURTQUF3UlFJZ0tBVWp6d0hRNkN5ZDl4MzNnWk85SlRBVGlmeStoOFFYenEwVmxP
      TmF3K29DSVFDemhERGkKVHNuVkgrbXd3UlNEdHRBa3o0cWNobVNQaXFCdk9paklEL1ZjNGc9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlDN1RDQ0FwU2dBd0lCQWdJVVRpK1ZzVXU0WDUyTDBlTWdvZjFGcFdtSE51OHdDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV5TVRVd05UUTNNREJhRncweU16RXlNVFV3TlRVeU1E
      QmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIy
      NWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0Ex
      VUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTcUd5ekI4d2xXTUdTWHdHNWxyZTV0CmZX
      UEN4V0JlTVJWKzhZWmpORVlJOWdlOVNEMjRnZURqNzlMMHd0VXFWMDdZbFp4aWVJdnE4eFlaYWhQ
      c2FJcWYKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFB
      d0hRWURWUjBPQkJZRQpGS2x2bXp5VTZhOVZmaHFWOUc2YmdvTmhpVzZITUI4R0ExVWRJd1FZTUJh
      QUZOTTZCcTNRQm5RYWI1aS9MbFF2CmR2QUdjejF5TUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4
      ekxUVTBOR0kwWXpkaU5tUXRialZzWTJjd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdS
      dGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29a
      SXpqMEVBd0lEUndBd1JBSWdYT1QxTWJ1UnlnbDVqQUdzZm5oNEZDQWNXelREa1ZDaytGT25RK09G
      dTkwQwpJSEFMR2o0WDhJazh2VVg1ZGNlcy9qRFNqRFpSamtYYUQ1MUdnOXp5d0tiWQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVldnpXOVBqSUJqZURwYno1YjU3YVcyTnZWK293
      Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlE
      VlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1UVXdOVE00TVRSYUZ3MHlOVEV3
      TURRd05UTTRNVFJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4
      RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVF
      QXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMK
      QUFRSEZ0dUpGMDZNTHNicUplMGkrcDE5aFhyYjFDWFJYWE9Jc3VIZjloOVVXckhzYVUrVjk5K0RF
      WHliVGU2VgpJTm1reUllUXc4MWtiMXpHNkFZdzNrR0lvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURB
      UUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVTB6b0dyZEFHZEJwdm1MOHVW
      QzkyOEFaelBYSXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUlnS0FVanp3SFE2Q3lkOXgzM2daTzlK
      VEFUaWZ5K2g4UVh6cTBWbE9OYXcrb0NJUUN6aEREaQpUc25WSCttd3dSU0R0dEFrejRxY2htU1Bp
      cUJ2T2lqSUQvVmM0Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoHV3Jp
      dGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMS
      KhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVu
      dBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5l
      bENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMq
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zEpMrCgdPcmRlcmVyEocrEtIW
      Cg5zdXBwbHljaGFpbk1TUBK/FhrLFAoDTVNQEsMUErgUErUUCg5zdXBwbHljaGFpbk1TUBL1BS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVUlvYjJ4U1A5YU9T
      UitSaGpxY0s1RDVOazVEUXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpB
      TkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFk
      UGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJ
      eE1qRTFNRFV6TlRVM1doY05NalV4TURBME1EVXpOVFUzV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQ
      Ck1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9N
      QjA5eVpHVnkKWlhJeEd6QVpCZ05WQkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1H
      QnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCQzNpcGlxOHpaa2M0U2ZpRGFLUW5JRGYxQkF6
      Z0t5UlY3b0NHZjl5RjhLVDBQdE9qMGo5CnlWdncxdmZmVE9jWi93V1BVU3F1ZTBrVmFjblRydHdW
      RDFpalFqQkFNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBH
      QTFVZERnUVdCQlRYNGNySXhMTEtKYjJmUDk0UXlJMUpZbnI5ZVRBSwpCZ2dxaGtqT1BRUURBZ05K
      QURCR0FpRUFoWG1wek1sM1VvVmtYN0J1WU5pUkRkbHpmVVh0KzJQT0l3VWRLemRiCmtXMENJUURV
      S2gxZVQwR0dsNGNrTDk4ckQvMzVyb3FJaDd5NFJvUXZOLzZKdHp0eTNBPT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoioggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzRUQ0NBb2ln
      QXdJQkFnSVVVQzREd2Rvc1A1QVZDOGo0NVFVQjRZQkd3c2t3Q2dZSUtvWkl6ajBFQXdJdwpYakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGph
      R0ZwYmkxdVpYUXcKSGhjTk1qSXhNakUxTURVME1qQXdXaGNOTWpNeE1qRTFNRFUwTnpBd1dqQnNN
      UXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVN
      UkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUTR3CkRBWURWUVFMRXdWaFpHMXBiakVlTUJ3R0ExVUVB
      d3dWUVdSdGFXNUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3cKRXdZSEtvWkl6ajBDQVFZSUtvWkl6
      ajBEQVFjRFFnQUUvZzBiYjdiY1BXcW0rMFd4eXJhV1RHWXJBL3QxeXVMeAplMHorejNNSWVnOFF3
      Wm9oRUp5bmpjM1U5UUdlcEE3TVlhVUNsajlRTk9tNUFGNGxCVXVFbWFPQ0FSUXdnZ0VRCk1BNEdB
      MVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlRGdEYxeXJP
      SlcKa0RYZC9paDJDUlFkQ0JzbGJqQWZCZ05WSFNNRUdEQVdnQlRYNGNySXhMTEtKYjJmUDk0UXlJ
      MUpZbnI5ZVRBawpCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAzTmpjMVpEWmtZemM1TFhKcU1t
      TnpNSUdKQmdncUF3UUZCZ2NJCkFRUjlleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNu
      VmxJaXdpWVdSdGFXNGlPaUowY25WbElpd2kKYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpTENKb1pp
      NUZibkp2Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0J6ZFhCdwpiSGxqYUdGcGJpMXVaWFFpTENKb1pp
      NVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3ClJBSWdJMXNhNmRza1dG
      b0lmVWxTMXVQajI4UzVtaXhieURwbU16R2UzUjIyUXRJQ0lGeEI1MU9FM1hWRWtpU3YKc1dVaCta
      OHVqakI1Zng2ZEtmejZ1UFVnQTNlcgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEy
      EgZTSEEyNTZK9QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0FUQ0NBYWFnQXdJQkFn
      SVVJb2IyeFNQOWFPU1IrUmhqcWNLNUQ1Tms1RFF3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkx
      dVpYUXcKSGhjTk1qSXhNakUxTURVek5UVTNXaGNOTWpVeE1EQTBNRFV6TlRVM1dqQmVNUXN3Q1FZ
      RFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0
      eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVds
      dUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkMzaXBpcTh6WmtjNFNm
      aURhS1FuSURmMUJBemdLeVJWN29DR2Y5eUY4S1QwUHRPajBqOQp5VnZ3MXZmZlRPY1ovd1dQVVNx
      dWUwa1ZhY25UcnR3VkQxaWpRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFI
      L0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJUWDRjckl4TExLSmIyZlA5NFF5STFKWW5yOWVUQUsKQmdn
      cWhrak9QUVFEQWdOSkFEQkdBaUVBaFhtcHpNbDNVb1ZrWDdCdVlOaVJEZGx6ZlVYdCsyUE9Jd1Vk
      S3pkYgprVzBDSVFEVUtoMWVUMEdHbDRja0w5OHJELzM1cm9xSWg3eTRSb1F2Ti82SnR6dHkzQT09
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHV3JpdGVycxIsEiIIARIeEggS
      BggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIG
      CAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0VuZG9yc2VtZW50EiwSIggB
      Eh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3CgdSZWFkZXJzEiwSIggB
      Eh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNo
      U2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1p
      bnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoK
      CgZWMV80XzISABoGQWRtaW5zGoISCg1Db25zZW5zdXNUeXBlEvAREuURCghldGNkcmFmdBLYEQrB
      EQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3Gs8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSURBRENDQXFlZ0F3SUJBZ0lVTkZ5bEJFSDN0K1dNaEFPd0pFVW92Y2drbFBrd0NnWUlL
      b1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUURE
      QkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpFMU1EVTBNakF3V2hjTk1qTXhN
      akUxTURVME56QXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZM
      VEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZj
      bVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUmU2aEtQMGQ0Ly9PTFdDUU03VTc0b3JV
      VEMKd1lISjVHNkdYblNFN1dBblRJL21pUlYyTjBxS21Hc1RqN285WEZndVdXQWZGR3JDTk1yOUc3
      ZDVSVDJGbzRJQgpMakNDQVNvd0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0ND
      c0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JC
      Ulkxd1RtNTgwZWVwQkZRbXhSNGhxYkdYMXcKRVRBZkJnTlZIU01FR0RBV2dCVFg0Y3JJeExMS0pi
      MmZQOTRReUkxSllucjllVEE5QmdOVkhSRUVOakEwZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFH
      RnBiaTF1WlhTQ0dHOXlaR1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVsCmREQnNCZ2dxQXdRRkJn
      Y0lBUVJnZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwYkdsaGRHbHZiaUk2SWlJc0ltaG0KTGtWdWNt
      OXNiRzFsYm5SSlJDSTZJbTl5WkdWeVpYSXhMbk4xY0hCc2VXTm9ZV2x1TFc1bGRDSXNJbWhtTGxS
      NQpjR1VpT2lKdmNtUmxjbVZ5SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lIREhXTDFycEZu
      UmNtQVBWakl2Ci94UlFaSmJyem1sRVhBdGdOWWtxY1lqREFpQk1vOFozVFFvZFBqV0lJM1JnT1lp
      cUIyaVhrNEt6WUtzMERtQ0sKdVhFTXpnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoizwgt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREFEQ0NBcWVnQXdJQkFnSVVORnlsQkVIM3Qr
      V01oQU93SkVVb3ZjZ2tsUGt3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6
      QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RB
      ZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1q
      SXhNakUxTURVME1qQXdXaGNOTWpNeE1qRTFNRFUwTnpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpF
      YgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21S
      bGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1
      emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFS
      ZTZoS1AwZDQvL09MV0NRTTdVNzRvclVUQwp3WUhKNUc2R1huU0U3V0FuVEkvbWlSVjJOMHFLbUdz
      VGo3bzlYRmd1V1dBZkZHckNOTXI5RzdkNVJUMkZvNElCCkxqQ0NBU293RGdZRFZSMFBBUUgvQkFR
      REFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJN
      QkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSWTF3VG01ODBlZXBCRlFteFI0aHFiR1gxdwpFVEFmQmdO
      VkhTTUVHREFXZ0JUWDRjckl4TExLSmIyZlA5NFF5STFKWW5yOWVUQTlCZ05WSFJFRU5qQTBnaGh2
      CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR0c5eVpHVnlaWEl4TG5OMWNIQnNlV05v
      WVdsdUxXNWwKZERCc0JnZ3FBd1FGQmdjSUFRUmdleUpoZEhSeWN5STZleUpvWmk1QlptWnBiR2xo
      ZEdsdmJpSTZJaUlzSW1obQpMa1Z1Y205c2JHMWxiblJKUkNJNkltOXlaR1Z5WlhJeExuTjFjSEJz
      ZVdOb1lXbHVMVzVsZENJc0ltaG1MbFI1CmNHVWlPaUp2Y21SbGNtVnlJbjE5TUFvR0NDcUdTTTQ5
      QkFNQ0EwY0FNRVFDSUhESFdMMXJwRm5SY21BUFZqSXYKL3hSUVpKYnJ6bWxFWEF0Z05Za3FjWWpE
      QWlCTW84WjNUUW9kUGpXSUkzUmdPWWlxQjJpWGs0S3pZS3MwRG1DSwp1WEVNemc9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1pbnMiIgoHV3JpdGVy
      cxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZB
      ZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFk
      ZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdT
      dHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVy
      ZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBh
      YmlsaXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggK
      BlNIQTI1NhoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
