apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://34.145.127.104:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: supplychain-net

    genesis: |-
      CiIaIGr4RsQpjsOjAGMnfGbSEIXDOs/3EuYxqFLi1O1XHJloEpZeCpNeCpBeCngKWggBEAEaBgiy
      maudBiIKc3lzY2hhbm5lbCpAYzJhNmEyNjkzZjZlZTQyZGVkZTJhNGZkMjMxOGJhODgwNDE5ZGQ0
      NDA2MDY2ZmE2ZGU4ZTQwMDk0NTE4M2E1ORIaEhiKyqGg6FuAFwgbLi2ExGEHiVNrU0cn1XISk10K
      kF0SjV0SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVWGdBdXJ6eUhVTUxiK1lPbjlSS3dKSEk0RzhNd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJM01UQXlPVEEzV2hjTk1qVXhNREUyTVRBeU9UQTNX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJHcS80
      M1Q5TFVzUmNYOTlVT21NK3g1UmhWbit3K0pScEVqMElrYmtna1JWWElzNGhoWlUKWHZoUVFsVCtU
      YitqVGMrSGVrNjRiVlZtZHE1UEkzZXFteCtqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUUpXd1luNUhKaENaZTFKcExoN2VyVytq
      c2dOVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCRmgxTGJLSk9lQ3lUSjZYL3VaVElkTmRRT3BV
      SWNGaFF0N1BhTU9BSU4KVFFJaEFKVVQ0Rk9kRmo3aCtCeGVCTFRhUnY1TGdnL0xvanFrekpzMHFW
      Q2FsWGZ2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVRTBRbHBkLzRFa2Q1dlJzL0xSYitMQVpWckxJd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJM01UQXpOVEF3V2hjTk1q
      TXhNakkzTVRBME1EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOEFIWnpnNVNWQWFvblA2SWwxUG9qOUhNeFA1
      ZHpYWncKQWd1TUFxbTNqMm5nQnRjUDhHZnl1ODVOZ0NVM1Jac21IRVBudlBZWXJHYUFwMzNZRmFP
      YXRhT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUSmVoRnArL0N3CklZeDg1NWMvQmhvUlZ4bkY4akFmQmdOVkhTTUVHREFXZ0JR
      Sld3WW41SEpoQ1plMUpwTGg3ZXJXK2pzZ05UQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M09UVTBaalpqTm1ObUxYcHJjbWMwTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUloQUkwd3QySkpPemE1QnBGc3RhSkpBeEIrcUhBQUFESG5UQ2s4NzQ1enROa0VBaDlB
      RkZqN2kycHRIZk9MClZIMlVDZXdydHl6LzlBZFI3b3AvOTd5Tjk0MjAKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVWGdBdXJ6eUhVTUxiK1lPbjlSS3dKSEk0RzhNd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJM01UQXlPVEEzV2hjTk1qVXhNREUy
      TVRBeU9UQTNXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJHcS80M1Q5TFVzUmNYOTlVT21NK3g1UmhWbit3K0pScEVqMElrYmtna1JWWElzNGhoWlUK
      WHZoUVFsVCtUYitqVGMrSGVrNjRiVlZtZHE1UEkzZXFteCtqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUUpXd1luNUhKaENaZTFK
      cExoN2VyVytqc2dOVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCRmgxTGJLSk9lQ3lUSjZYL3Va
      VElkTmRRT3BVSWNGaFF0N1BhTU9BSU4KVFFJaEFKVVQ0Rk9kRmo3aCtCeGVCTFRhUnY1TGdnL0xv
      anFrekpzMHFWQ2FsWGZ2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGoISCg1Db25zZW5zdXNUeXBlEvAREuUR
      CghldGNkcmFmdBLYEQrBEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3Gs8ILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBRENDQXFlZ0F3SUJBZ0lVRXVENkd1dGxGZldHdlY2akpD
      ejU0VndHaVFRd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJM01U
      QXpOVEF3V2hjTk1qTXhNakkzTVRBME1EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU3ZScHp4cGQ5
      UUdGWkdZektTdWxncENMVWkKa3FnZzkxVC9oODdqSUtUN0s0MmlWamxIS1ZCY2pPN0IrTHpFQ3ds
      VWZIM1gvTGo2bmd1QkhPdnRheXJabzRJQgpMakNDQVNvd0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUitiWHpRakJiMGtQaGV2NUpYenJMcHFsME4KTmpBZkJnTlZIU01FR0RB
      V2dCUUpXd1luNUhKaENaZTFKcExoN2VyVytqc2dOVEE5QmdOVkhSRUVOakEwZ2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dHOXlaR1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVs
      CmREQnNCZ2dxQXdRRkJnY0lBUVJnZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwYkdsaGRHbHZiaUk2
      SWlJc0ltaG0KTGtWdWNtOXNiRzFsYm5SSlJDSTZJbTl5WkdWeVpYSXhMbk4xY0hCc2VXTm9ZV2x1
      TFc1bGRDSXNJbWhtTGxSNQpjR1VpT2lKdmNtUmxjbVZ5SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGNB
      TUVRQ0lBUlc2TnNwSkJ4WGlQMHdOcmdWCitmU3hrM083MkdmbWM0WWVHd2htK0tuM0FpQVhqdVJr
      SVJ3SmJOcGtucXBZSUVWek9HZUZNQkhJdTFGNFB5REMKVVMyYkpRPT0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQoizwgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREFEQ0NBcWVnQXdJ
      QkFnSVVFdUQ2R3V0bEZmV0d2VjZqSkN6NTRWd0dpUVF3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0Zw
      YmkxdVpYUXcKSGhjTk1qSXhNakkzTVRBek5UQXdXaGNOTWpNeE1qSTNNVEEwTURBd1dqQnhNUXN3
      Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3
      RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFE
      RXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DQUFTdlJwenhwZDlRR0ZaR1l6S1N1bGdwQ0xVaQprcWdnOTFUL2g4N2pJS1Q3
      SzQyaVZqbEhLVkJjak83QitMekVDd2xVZkgzWC9MajZuZ3VCSE92dGF5clpvNElCCkxqQ0NBU293
      RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYK
      QlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSK2JYelFqQmIwa1BoZXY1Slh6
      ckxwcWwwTgpOakFmQmdOVkhTTUVHREFXZ0JRSld3WW41SEpoQ1plMUpwTGg3ZXJXK2pzZ05UQTlC
      Z05WSFJFRU5qQTBnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR0c5eVpHVnla
      WEl4TG5OMWNIQnNlV05vWVdsdUxXNWwKZERCc0JnZ3FBd1FGQmdjSUFRUmdleUpoZEhSeWN5STZl
      eUpvWmk1QlptWnBiR2xoZEdsdmJpSTZJaUlzSW1obQpMa1Z1Y205c2JHMWxiblJKUkNJNkltOXla
      R1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVsZENJc0ltaG1MbFI1CmNHVWlPaUp2Y21SbGNtVnlJ
      bjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUFSVzZOc3BKQnhYaVAwd05yZ1YKK2ZTeGszTzcy
      R2ZtYzRZZUd3aG0rS24zQWlBWGp1UmtJUndKYk5wa25xcFlJRVZ6T0dlRk1CSEl1MUY0UHlEQwpV
      UzJiSlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZB
      ZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFk
      ZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMa
      BkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5zErkvCgtD
      b25zb3J0aXVtcxKpLxLeLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsQuErIWCgpjYXJyaWVyTVNQ
      EqMWGr8UCgNNU1AStxQSrBQSqRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVNRDBLL3pzY2diNGhvRnVnbVJwR2ZyVC9tV1F3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1qY3hNRE14TWpWYUZ3MHlOVEV3TVRZ
      eE1ETXhNalZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpB
      TkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3
      T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFU
      QUNIaE94YXZhcVdJL3lIOC80VDBzZGtaTFd3Unc3VURUSEI1VFYxODVzdmk0UEF2Ykg2WXY0VUtj
      NGovVgptQ1JyUk0rbFVhVjFmdW5adUoxVmVHdkRvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgv
      TUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVVJRTnBRWmRLZXBIUnE1Tm5keXlz
      QU9ZK3htOHdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUlXNmlXWnpFTmpJRTVEQ2NCczZ1QUxq
      clBWUlJpb0cxbEZTSXI4ZDA2OHlBaUVBK0JmWQpXREVKTWNmdHhSS0dVM0hla3RkVTFUM3Fqa0tX
      OXNtSWlsWDMweGM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrIILS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSUM3VENDQXBTZ0F3SUJBZ0lVSGRMMjdkajN3MG9hOGJNSDlFbzV1RU5z
      Z0Ywd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2
      Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3
      RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXlNamN4TURNNU1EQmFGdzB5
      TXpFeU1qY3hNRFEwTURCYU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQx
      TUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNU
      QldGa2JXbHVNQTRHQTFVRUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnlj
      bWxsCmNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVIydjRGQ2EzUzZE
      U3dRRk5ZaDBGZTIKaVhhNEhQVDhlcXBwczR3cWNDZ2hhVzlYYjFTQWhXUWxBeHZ5NFovQjd2RTgy
      OE9hQ2h4eTA3WFdvZEVkaCt3bwpvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dB
      MVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFCkZPaHRqeEw5dVhaMUQ4ZTVabmVUTUFGY2FTa1pN
      QjhHQTFVZEl3UVlNQmFBRkVVRGFVR1hTbnFSMGF1VFozY3MKckFEbVBzWnZNQ1FHQTFVZEVRUWRN
      QnVDR1dOaExYUnZiMnh6TFRkaU9HTTVPR0ppT1dJdE5uTmpjamd3Z1kwRwpDQ29EQkFVR0J3Z0JC
      SUdBZXlKaGRIUnljeUk2ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBj
      blZsSWl3aWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JX
      VnUKZEVsRUlqb2lRV1J0YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFX
      NGlmWDB3Q2dZSQpLb1pJemowRUF3SURSd0F3UkFJZ1VPOXkvU3lBc1Q4TXdwZURLMVJCVjB4dEJZ
      ZlBtZ09jNVBvR1RyamVVUzhDCklFMy9adEVBcVMzTDU4ZnJNZzJ4cGcvTE5WUVdDaWwyY2E4YStN
      L2MzVFIvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdBd0lCQWdJVU1EMEsvenNjZ2I0aG9G
      dWdtUnBHZnJUL21XUXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlY
      SnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV5TWpjeE1E
      TXhNalZhRncweU5URXdNVFl4TURNeE1qVmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZR
      UUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21s
      bGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdn
      cWhrak9QUU1CQndOQwpBQVRBQ0hoT3hhdmFxV0kveUg4LzRUMHNka1pMV3dSdzdVRFRIQjVUVjE4
      NXN2aTRQQXZiSDZZdjRVS2M0ai9WCm1DUnJSTStsVWFWMWZ1blp1SjFWZUd2RG8wSXdRREFQQmdO
      VkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVUlFO
      cFFaZEtlcEhScTVObmR5eXNBT1kreG04d0NnWUlLb1pJemowRQpBd0lEU1FBd1JnSWhBSVc2aVda
      ekVOaklFNURDY0JzNnVBTGpyUFZSUmlvRzFsRlNJcjhkMDY4eUFpRUErQmZZCldERUpNY2Z0eFJL
      R1UzSGVrdGRVMVQzcWprS1c5c21JaWxYMzB4Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoa
      BkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRt
      aW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMi
      NAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoL
      RW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFk
      bWlucxKxFwoPbWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJl
      ck1TUBKBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVVdS
      QUNwOGIwc2ZUTzZ4U28rSzlvakVWbWZZQXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJo
      TUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3
      WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhK
      bApjaTF1WlhRd0hoY05Nakl4TWpJM01UQXpNREU0V2hjTk1qVXhNREUyTVRBek1ERTRXakJrTVFz
      d0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhK
      cFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldG
      dWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkNU
      NFdweDArR2dYeGRoRUpOZjM3Ykgvc2hEZ05ud2tSSnp0Cm5qTlk2OVVSWnNSSmNhSUk4YmhIUERL
      dEFNb3BmZTNlSFZhTzl1V0lJY2w3bFVHT2ZFT2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4
      d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTaDY5cUhjbmtOS2YvRwp0b1d4TGxP
      cUxyM2l5REFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUFmeVVsM3huL1hIZHdjSDVEVU41cFZkd29C
      Ck15RGxaWnJTSEFYbCtZeXZDUUloQU1vNkNLM2d5S3ZKQ2t2VVN5bjlEd3dQQWMrWExPRzIzUG9j
      aUlvMXM4VkIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVJZzB6MGdEQVU4cGtvc1FqRXZtNVFCWDg4VG93
      Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxq
      YURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4
      SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qSTNNVEF6
      TnpBd1doY05Nak14TWpJM01UQTBNakF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05W
      QkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5
      WlhJeEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcK
      SFFZRFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENB
      UVlJS29aSQp6ajBEQVFjRFFnQUVRN3hQbysrVHZtZmZTQlBrWmZpc2FzRVJndGZxV3NwcUhZZnJa
      RGs3dFBkcXp1TVlKeFRyCjJtenRCNFhWMTVJeGg4UXlzVGJlQkZqM20zR2NrOUtVdnFPQ0FTSXdn
      Z0VlTUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdC
      QlNaN2pjRitlSERhRjZlZXl2N1FKTnJSL3NSRkRBZgpCZ05WSFNNRUdEQVdnQlNoNjlxSGNua05L
      Zi9HdG9XeExsT3FMcjNpeURBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAyT0dabVlqZGlO
      RFEyTFhvNWNXaDZNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBi
      bWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJ
      am9pYldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJX
      RnVkV1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhr
      ak9QUVFEQWdOSEFEQkUKQWlCNFpMRWpZNTNrYXNaUHRRVmptRjdhK0xQbjlud09iYTMwYWoxZE1P
      ZDJwd0lnWW1vMjB4ZkhmeWxaWndBMwpCWUcyN1IwbzVnUlJlR3B2bGt3YTdwZjhBeXM9Ci0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVVdSQUNwOGIwc2ZUTzZ4U28rSzlvakVWbWZZ
      QXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpY
      SXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TWpJM01U
      QXpNREU0V2hjTk1qVXhNREUyTVRBek1ERTRXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0Ex
      VUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJu
      Vm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJN
      RwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkNUNFdweDArR2dYeGRoRUpOZjM3Ykgvc2hE
      Z05ud2tSSnp0Cm5qTlk2OVVSWnNSSmNhSUk4YmhIUERLdEFNb3BmZTNlSFZhTzl1V0lJY2w3bFVH
      T2ZFT2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIw
      R0ExVWREZ1FXQkJTaDY5cUhjbmtOS2YvRwp0b1d4TGxPcUxyM2l5REFLQmdncWhrak9QUVFEQWdO
      SUFEQkZBaUFmeVVsM3huL1hIZHdjSDVEVU41cFZkd29CCk15RGxaWnJTSEFYbCtZeXZDUUloQU1v
      NkNLM2d5S3ZKQ2t2VVN5bjlEd3dQQWMrWExPRzIzUG9jaUlvMXM4VkIKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQoaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFu
      dWZhY3R1cmVyTVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoT
      EhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAa
      ExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVhdGlvblBv
      bGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hB
      MjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlu
      cxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAa
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8zEgAa
      BkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIO
      CAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlu
      cyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
