apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIB6KpXZWxNvc8ItWrqKqVoWHlrYG4ZeV3hGtROeUapyWEqBeCp1eCppeCngKWggBEAEaBgjY
      3b6WBiIKc3lzY2hhbm5lbCpAYzYwMDIwNWU5YWI4N2QyOGUwYWU3MzlmNjczNjE0NDIzZjA3YWY3
      MjgyOTdlODIxZDMyOTYwNjgyNmRiYjM4NhIaEhgz9t6qQ9Zwh65vVd7hpRpQnGHle8tmG9ISnV0K
      ml0Sl10Swy8KC0NvbnNvcnRpdW1zErMvEuguChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0Szi4SshYK
      CmNhcnJpZXJNU1ASoxYavxQKA01TUBK3FBKsFBKpFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVNUL1FzbVJyN0JNci9kVWxXeDZh
      YjNJR0dITXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdN
      Qmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5
      TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakEzTVRRd05UQXlNamhh
      RncweU5UQTFNRE13TlRBeU1qaGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpN
      YjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgK
      TUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9Q
      UU1CQndOQwpBQVFSLzlIRFVCUzQycFNlUTRZL3hMUFR5N2FOOXJKdm5aaG9rbkl2SjZzalltMFRE
      cmdFdFNTZk5POFN1bTZtCit1R3JRN0M3V3FSdCt3N3QxRG4yandMNm8wSXdRREFQQmdOVkhSTUJB
      ZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVOSt0RVBiTDJx
      SkovU1Z2dlNmM2h2VktDUllJd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBT285SEtaS2lTT09p
      bzdUU3dtcTM1Y3JGTEFmN0lsUUtuZnFnRlczM00zN0FpQXNKbmRiClkxQmhVb0NvU3E2akFxR21R
      amIwSkNCeU9sSU1qNVRPUWttS1FnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdUQ0NBcFNnQXdJQkFnSVVDVU5YazBLOTFkY0Fq
      Vnp0NW1PN3lxaDk0VUl3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5C
      Z05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZ
      WEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01UUXdO
      VEV3TURCYUZ3MHlNekEzTVRRd05URTFNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApW
      UVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhq
      QU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFX
      UnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FB
      UnFmWjJpOUFmSVcwNk9udmZvd1B1RQpGandFSXpmbUZ6MkJ1M0xLa1ZHTHpTNzlETG9kQTV2aGs2
      aHRaaUJsR2crdysvVmdDYzRHa3dXbjUyTExKWlZuCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JB
      UURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRktXT3d6aHZxNS91STJFaVl3
      N3FueU1kdC9PR01COEdBMVVkSXdRWU1CYUFGUGZyUkQyeTlxaVNmMGxiNzBuOQo0YjFTZ2tXQ01D
      UUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFprTkdNMlpqYzJaR1l0Y1dSblkyY3dnWTBHCkND
      b0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdS
      dGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZ
      dVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhC
      bElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnQXVmU2x3di96ZFQyeXRY
      amZ2ZzJoQ0xFQ2UvRnRxMXV6eE9QRkU1bit5VUMKSUZ0NTYzV2phZXB0d096dUpaT1BkZ0VMV2Rk
      MStYTkw4Z1habk9UVCtMTmUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hB
      MjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVU1Qv
      UXNtUnI3Qk1yL2RVbFd4NmFiM0lHR0hNd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhN
      Q1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZ
      RFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5
      Ck1qQTNNVFF3TlRBeU1qaGFGdzB5TlRBMU1ETXdOVEF5TWpoYU1Gb3hDekFKQmdOVkJBWVRBa2RD
      TVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVF
      Q2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2Nx
      aGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUVIvOUhEVUJTNDJwU2VRNFkveExQVHk3YU45ckp2
      blpob2tuSXZKNnNqWW0wVERyZ0V0U1NmTk84U3VtNm0KK3VHclE3QzdXcVJ0K3c3dDFEbjJqd0w2
      bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05W
      SFE0RUZnUVU5K3RFUGJMMnFKSi9TVnZ2U2YzaHZWS0NSWUl3Q2dZSUtvWkl6ajBFCkF3SURTQUF3
      UlFJaEFPbzlIS1pLaVNPT2lvN1RTd21xMzVjckZMQWY3SWxRS25mcWdGVzMzTTM3QWlBc0puZGIK
      WTFCaFVvQ29TcTZqQXFHbVFqYjBKQ0J5T2xJTWo1VE9Ra21LUWc9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tChoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJy
      aWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1T
      UBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVy
      TVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1Aa
      BkFkbWlucyoGQWRtaW5zErsXCg9tYW51ZmFjdHVyZXJNU1ASpxcarxUKA01TUBKnFRKcFRKZFQoP
      bWFudWZhY3R1cmVyTVNQEoYGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEVENDQWJL
      Z0F3SUJBZ0lVWjNubVpIYnpGU3pMdlhLMlRON2VpTENFWlRVd0NnWUlLb1pJemowRUF3SXcKWkRF
      TE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5
      YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFo
      Ym5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekUwTURVd01ESXpXaGNOTWpVd05UQXpNRFV3
      TURJeldqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlE
      VlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVF
      QXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5
      QXdFSEEwSUFCTmFMbThVNko2ZTB2bWo5K3dKWExucUh5QVpmNjMwT3Z1bVIKbmZmRHlYa1Z1MXRB
      UjVIY1dVQmtZOHlGVUlCVHNFOUFzaktSQ0VmUGVyODdGeDcrTW9xalFqQkFNQThHQTFVZApFd0VC
      L3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJkQ0tGSTlzNFB0
      aFNMClRKelczR0k1ZU9QcDdEQUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUErZnd5cGYrQ3Z1Mkdy
      TTVnSWtsUXFQdTIKcTZTTkREeXRUeDRHd3AxYTJHOENJUUR5RTBYaHJPUElqSVArYWZqMVdPalFk
      dXh0UmRYNjhadGoya1hmeGdHcwpuZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0t
      LS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQXJlZ0F3SUJBZ0lVYnJ6cnRhd1BVOEIz
      UTJZOUVheFEvSU1IdWRBd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFO
      QmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhO
      WVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3
      SGhjTk1qSXdOekUwTURVd056QXdXaGNOTWpNd056RTBNRFV4TWpBd1dqQ0JoakVMTUFrR0ExVUUK
      QmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtF
      d3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVk
      V1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBN
      Rmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemowREFRY0RRZ0FFSXB2MCtIaTc5ck5WeCtQTjcxalJU
      Z1NQLzdyWGNPNVgxS0NmQ0hKR3NaVFZCanNXdWFYYQplSzBiQThhQ3VWMFR5RTVMMFQwUTY2cE11
      cHhuWFk0MEZhT0NBU0l3Z2dFZU1BNEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVB
      akFBTUIwR0ExVWREZ1FXQkJTVFAreWVsWEY2SGxVdjI3TlVNcFZ6YXcxMGFqQWYKQmdOVkhTTUVH
      REFXZ0JSZENLRkk5czRQdGhTTFRKelczR0k1ZU9QcDdEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApi
      MjlzY3kwM1kyUTNabVJtT1RjMkxUVmpjbXhvTUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNu
      TWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxr
      Rm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRF
      bEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpH
      MXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGCkFpRUE4MnQxbDdseDhwbEZPNjg1eTVtSGh4
      Vjkxd2hORFhaTkZpbVdhN2h3QlY0Q0lCT0ZLYVNwaWxhb1ZQQVQKR3J3UVBVdGIzeXFMaWtCOGdS
      U1BESCt1TG1JWgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKhgYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVaM25tWkhiekZT
      ekx2WEsyVE43ZWlMQ0VaVFV3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpJd056RTBNRFV3TURJeldoY05NalV3TlRBek1EVXdNREl6V2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOYUxtOFU2SjZl
      MHZtajkrd0pYTG5xSHlBWmY2MzBPdnVtUgpuZmZEeVhrVnUxdEFSNUhjV1VCa1k4eUZVSUJUc0U5
      QXNqS1JDRWZQZXI4N0Z4NytNb3FqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUmRDS0ZJOXM0UHRoU0wKVEp6VzNHSTVlT1BwN0RB
      S0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQStmd3lwZitDdnUyR3JNNWdJa2xRcVB1MgpxNlNORER5
      dFR4NEd3cDFhMkc4Q0lRRHlFMFhock9QSWpJUCthZmoxV09qUWR1eHRSZFg2OFp0ajJrWGZ4Z0dz
      Cm5nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgB
      Eh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMI
      ARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUI
      ARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1l
      bnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5z
      GkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAa
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxKLKwoHT3Jk
      ZXJlchL/KhLKFgoOc3VwcGx5Y2hhaW5NU1AStxYawxQKA01TUBK7FBKwFBKtFAoOc3VwcGx5Y2hh
      aW5NU1AS8QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0FEQ0NBYWFnQXdJQkFnSVVQ
      QlBmMlVmbmVXa3BMYWdnS0NjT3BWdEE1RWt3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVC
      aE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdE
      Z1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpY
      UXcKSGhjTk1qSXdOekUwTURRMU9ERTVXaGNOTWpVd05UQXpNRFExT0RFNVdqQmVNUXN3Q1FZRFZR
      UUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVE
      QU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxX
      NWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQk9pSUEyQi9JRGtYaVFING5j
      b3VFQzQvdkFpckpPNDJIV083c1B3ekI2eUNhd0hmeEo3WApNTkNvQWtRT2tFa0pIcnNyZm5HTHVy
      dGYxaDRFZk56MUNFYWpRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJRNzBHWE5YYzNRVlpMQkRDUEY4TmFNK1Bzd0REQUsKQmdncWhr
      ak9QUVFEQWdOSUFEQkZBaUF5cG5uclY1ajZOZXNiZG1iSmx1UXpRQXZnWU15T1EvNTBZVmRrNlF5
      VgpHUUloQVBTRnd4VDVwdFNhR0dCcnBLYjJjejVnVXVmSDBMYzZVN0dMbWZ6bUZuQ3kKLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoioggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzRU
      Q0NBb2lnQXdJQkFnSVVKWkNLNkc0NjAvSnVMLzY4U0dWVFNvV09CeDB3Q2dZSUtvWkl6ajBFQXdJ
      dwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhC
      d2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekUwTURVd05qQXdXaGNOTWpNd056RTBNRFV4TVRB
      d1dqQnNNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5
      dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUTR3CkRBWURWUVFMRXdWaFpHMXBiakVlTUJ3
      R0ExVUVBd3dWUVdSdGFXNUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3cKRXdZSEtvWkl6ajBDQVFZ
      SUtvWkl6ajBEQVFjRFFnQUVNVmhEN0c4WUVMNjdsc2pzTjY0QUpFQ05XU3FGSVpOdgpCKytmZTIy
      blJ0YmJLQkF1L2xvMmxwUERnQ2dta3hJb25lTGovMVVCUHB4b25kZk8vOGpGdjZPQ0FSUXdnZ0VR
      Ck1BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFt
      STVkMWNReWYKOXQ0bDBIcG9LK25ncGUxUDFUQWZCZ05WSFNNRUdEQVdnQlE3MEdYTlhjM1FWWkxC
      RENQRjhOYU0rUHN3RERBawpCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAxTmpZM1l6WTNabVkz
      TFd4a04zbzFNSUdKQmdncUF3UUZCZ2NJCkFRUjlleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFp
      T2lKMGNuVmxJaXdpWVdSdGFXNGlPaUowY25WbElpd2kKYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlp
      TENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0J6ZFhCdwpiSGxqYUdGcGJpMXVaWFFp
      TENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3ClJBSWdQMVFG
      WFNCWHJrMWRrMXU3SFpNUjZDUkNXSHhuWm5QWFU3Z0l3ckRJcGZRQ0lHRnFlSUFhNlVUYm8vTnQK
      TE8zS3hhNXV3YTBKK0J5aWMxUUgwMUZTT05tKwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIO
      CgRTSEEyEgZTSEEyNTZK8QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0FEQ0NBYWFn
      QXdJQkFnSVVQQlBmMlVmbmVXa3BMYWdnS0NjT3BWdEE1RWt3Q2dZSUtvWkl6ajBFQXdJdwpYakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGph
      R0ZwYmkxdVpYUXcKSGhjTk1qSXdOekUwTURRMU9ERTVXaGNOTWpVd05UQXpNRFExT0RFNVdqQmVN
      UXN3Q1FZRFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1i
      MjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNl
      V05vWVdsdUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQk9pSUEyQi9J
      RGtYaVFING5jb3VFQzQvdkFpckpPNDJIV083c1B3ekI2eUNhd0hmeEo3WApNTkNvQWtRT2tFa0pI
      cnNyZm5HTHVydGYxaDRFZk56MUNFYWpRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURW
      UjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJRNzBHWE5YYzNRVlpMQkRDUEY4TmFNK1Bzd0RE
      QUsKQmdncWhrak9QUVFEQWdOSUFEQkZBaUF5cG5uclY1ajZOZXNiZG1iSmx1UXpRQXZnWU15T1Ev
      NTBZVmRrNlF5VgpHUUloQVBTRnd4VDVwdFNhR0dCcnBLYjJjejVnVXVmSDBMYzZVN0dMbWZ6bUZu
      Q3kKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI3CgdXcml0ZXJzEiwSIggBEh4S
      CBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI4CgZBZG1pbnMSLhIkCAESIBII
      EgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1pbnMiOwoLRW5kb3JzZW1lbnQSLBIi
      CAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcKB1JlYWRlcnMSLBIi
      CAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zKgZBZG1pbnMaHgoMQmF0
      Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlu
      cxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaghIKDUNvbnNlbnN1c1R5
      cGUS8BES5REKCGV0Y2RyYWZ0EtgRCsERChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijcazwgt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREFqQ0NBcW1nQXdJQkFnSVVBdGlJWkdneUs4
      NEE0eXNjZU5GdktwOE1FMjR3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6
      QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RB
      ZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1q
      SXdOekUwTURVd05qQXdXaGNOTWpNd056RTBNRFV4TVRBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpF
      YgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21S
      bGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1
      emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFS
      VWFTaE5lM3pmbnl5Q2ZQdEdCNVpwdWV4aQpyYWtBYVBzT1FzQVplcy9tRVI3YnVKMFdjWXZMd0p6
      MGlWTFMwaVhBMU4wOEdTOUJrNjlGUVg1a3lMKzNvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFR
      REFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJN
      QkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTY01VSUp0OFJZYlVCRkZqdC9mNXJVQS9lcQpUREFmQmdO
      VkhTTUVHREFXZ0JRNzBHWE5YYzNRVlpMQkRDUEY4TmFNK1Bzd0REQS9CZ05WSFJFRU9EQTJnaGh2
      CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1
      Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxz
      YVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3
      Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJ
      emowRUF3SURSd0F3UkFJZ2U2QktnY3NNRzBaajBmK2IKcHNmZ1Rva296T3R4N1JIUXZtdVZXd3Vh
      NFBNQ0lDZjR1MWFKeTlMTVQ1UmhrblVCa25VWjY1Tm9ZcU5MS1pSdAo2VzhBY1M1eAotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCiLPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQWpD
      Q0FxbWdBd0lCQWdJVUF0aUlaR2d5Szg0QTR5c2NlTkZ2S3A4TUUyNHdDZ1lJS29aSXpqMEVBd0l3
      ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RTBNRFV3TmpBd1doY05Nak13TnpFME1EVXhNVEF3
      V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1
      Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3
      SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pP
      UFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJVYVNoTmUzemZueXlDZlB0R0I1WnB1ZXhpCnJha0FhUHNP
      UXNBWmVzL21FUjdidUowV2NZdkx3SnowaVZMUzBpWEExTjA4R1M5Qms2OUZRWDVreUwrM280SUIK
      TURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJC
      Z2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNjTVVJSnQ4Ulli
      VUJGRmp0L2Y1clVBL2VxClREQWZCZ05WSFNNRUdEQVdnQlE3MEdYTlhjM1FWWkxCRENQRjhOYU0r
      UHN3RERBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NH
      bTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJ
      bUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVk
      RWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJ
      bTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnZTZCS2djc01HMFpqMGYrYgpw
      c2ZnVG9rb3pPdHg3UkhRdm11Vld3dWE0UE1DSUNmNHUxYUp5OUxNVDVSaGtuVUJrblVaNjVOb1lx
      TkxLWlJ0CjZXOEFjUzV4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAF
      KICAgAoaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucyIqCg9CbG9j
      a1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoH
      UmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRo
      bRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP//
      //8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWlu
      LW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoK
      BlYxXzRfMxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
