apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIDekP5cpb887smo5PTjMEbaRhwcWidhVBJyr+WGUuPBOErBeCq1eCqpeCngKWggBEAEaBgiY
      xOqYBiIKc3lzY2hhbm5lbCpAMjAwOTExMjJkNGVlZTdmYjI4ZDBhMTQxNzM1YzBmMTk0NmZlMzI2
      ZTVjZTNmZDM0NTU5MDA5ZGIyYmE1MGMwYhIaEhgNpP5Sak9czhzVcxoYE7kU/kpWRgwha2gSrV0K
      ql0Sp10SmysKB09yZGVyZXISjysS0hYKDnN1cHBseWNoYWluTVNQEr8WGssUCgNNU1ASwxQSuBQS
      tRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVRVpqN2d4cm1KOXJxNHFkNExLaElzSlJZMXNjd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T1RBNU1ESXdNREE0V2hjTk1qVXdOakk1TURJd01EQTRX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJBcE53
      aTdIZ1hMUnczbmZDaFJ4SVExVjNCWDc4S1djOXYzeEhQLzNLZXY0WGFyZWJReVEKUW9nR3dVdFNj
      QXg4eitYR255QytuVDJ0OEgyQ053YkpNNE9qUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFM0Y2N3ZGs1Tjh2THVWL3R6amF6RjRx
      a2ErakFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXJBRTFaQnJZdHdqSFdxckFRMTJHb09kM2k4
      RUE3WEcvRFdQYzJxcUcKS0s4Q0lRQzlTVVVUUWpzVlRDUnY4N0Zna1lBYjVtN2FHMVZJbVVFcks2
      SEFtQktZRUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKiCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNFRDQ0FvaWdBd0lCQWdJVVMzaFhzTmh6bWZKTG53YXNvZ1ZGSFlVdmRq
      Y3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09UQTVNREl3T0RBd1do
      Y05Nak13T1RBNU1ESXhNekF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUlvRWNKbW8yN1g2QlFFbk9MVFVFMzlZ
      bzdUMmtVblBoCmRTQVpnSUUxY1ozL0ViTEQxZEhWSVdtZ0FNTGtUSTNtdVlFbWpvdVBHb0hLWjJ3
      aVFuTHRTS09DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUnJ4NWJrQ2p0UApEd1dUVGIrTXRUS3lTeGN3dERBZkJnTlZIU01FR0RB
      V2dCVFM0Y2N3ZGs1Tjh2THVWL3R6amF6RjRxa2ErakFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDFOalkzWXpZM1ptWTNMWEJxYldOa01JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFJ3QXcKUkFJZ1FKaTYxMTF5c3BPZGZqSnNJVTR5T3F3bmhKWWUwTllNZHhSbk0zU0QySXdD
      SUFQeHpVZ1cyWi9WL0Z3VwpTOUNYNUV6NEt2emswSmhPZ0pzb2dpTDlWNmRhCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkr1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVUVaajdneHJtSjlycTRxZDRMS2hJc0pSWTFzY3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd09UQTVNREl3TURBNFdoY05NalV3
      TmpJNU1ESXdNREE0V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCQXBOd2k3SGdYTFJ3M25mQ2hSeElRMVYzQlg3OEtXYzl2M3hIUC8zS2V2NFhhcmVi
      UXlRClFvZ0d3VXRTY0F4OHorWEdueUMrblQydDhIMkNOd2JKTTRPalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRTNGNjd2RrNU44
      dkx1Vi90emphekY0cWthK2pBSwpCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUFyQUUxWkJyWXR3akhX
      cXJBUTEyR29PZDNpOEVBN1hHL0RXUGMycXFHCktLOENJUUM5U1VVVFFqc1ZUQ1J2ODdGZ2tZQWI1
      bTdhRzFWSW1VRXJLNkhBbUJLWUVBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlu
      cyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1p
      bnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zKgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0
      Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlu
      cxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaihIKDUNvbnNlbnN1c1R5
      cGUS+BES7REKCGV0Y2RyYWZ0EuARCskRChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijca0wgt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVkcFpqU2piWXgx
      WExmUG81YzBpL0dRditiV2N3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6
      QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RB
      ZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1q
      SXdPVEE1TURJd09EQXdXaGNOTWpNd09UQTVNREl4TXpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpF
      YgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21S
      bGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1
      emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFR
      ODNYbXlCOWMwR0xrNVQwbHVpdXV4VnVLMQp2RVg2Z0lZR3FkZmIrMWlVRmQ5dGVDMlhKaHZmb2RB
      bDlrKzZRcDRNdzVPWjd3N2pHRUgrVWNRMUV5VlhvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFR
      REFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJN
      QkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSU2I0V0RlSTNUS1VGNHpNVEFxZTBiN1hRdApGVEFmQmdO
      VkhTTUVHREFXZ0JUUzRjY3dkazVOOHZMdVYvdHpqYXpGNHFrYStqQS9CZ05WSFJFRU9EQTJnaGh2
      CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1
      Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxz
      YVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3
      Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJ
      emowRUF3SURTQUF3UlFJaEFKYTF6NkdFanZQU1h5ZE4KQlN3YXJEVy92VllpZXNjVXFWR0FZS0Rr
      eHdaMkFpQkFCYkg1WWNRdjM2d3dNaW1hNnlKdmNPY0JEcFhaTmVSTwowM3RmY0dDdTJBPT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      REF6Q0NBcW1nQXdJQkFnSVVkcFpqU2piWXgxWExmUG81YzBpL0dRditiV2N3Q2dZSUtvWkl6ajBF
      QXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVF
      Qnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6
      ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdPVEE1TURJd09EQXdXaGNOTWpNd09UQTVNREl4
      TXpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12
      VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5
      TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2Nx
      aGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRODNYbXlCOWMwR0xrNVQwbHVpdXV4VnVLMQp2RVg2
      Z0lZR3FkZmIrMWlVRmQ5dGVDMlhKaHZmb2RBbDlrKzZRcDRNdzVPWjd3N2pHRUgrVWNRMUV5Vlhv
      NElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZC
      d01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSU2I0V0Rl
      STNUS1VGNHpNVEFxZTBiN1hRdApGVEFmQmdOVkhTTUVHREFXZ0JUUzRjY3dkazVOOHZMdVYvdHpq
      YXpGNHFrYStqQS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVa
      WFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JC
      R0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNi
      V1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHda
      U0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFKYTF6NkdFanZQU1h5
      ZE4KQlN3YXJEVy92VllpZXNjVXFWR0FZS0RreHdaMkFpQkFCYkg1WWNRdjM2d3dNaW1hNnlKdmNP
      Y0JEcFhaTmVSTwowM3RmY0dDdTJBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAw
      bXMQChgBIAUogICAChoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJz
      GgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIX
      Eg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1p
      bnMqBkFkbWlucxLDLwoLQ29uc29ydGl1bXMSsy8S6C4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLO
      LhK7FwoPbWFudWZhY3R1cmVyTVNQEqcXGq8VCgNNU1ASpxUSnBUSmRUKD21hbnVmYWN0dXJlck1T
      UBKGBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVVhRYm96
      SVNqUWhHU25lUS9MbjRneDg4ZkZBb3dDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNR
      MGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURW
      UVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApj
      aTF1WlhRd0hoY05Nakl3T1RBNU1ESXdNakV3V2hjTk1qVXdOakk1TURJd01qRXdXakJrTVFzd0NR
      WURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFky
      Z3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRX
      WmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkNxMGFV
      UTUzNUFIYnFNeDR4QXNneWNzcGFoTkxXSUs5cnhZCisrZ1RpVG9FdXdHRTFpeGpJOUFhV2E3NFhw
      Um9rNzBqb3B4WFNHMnBrLzVoNUhvdHhsT2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0Rn
      WURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTV2I5cUpPTTlZVHRueApxNzZPS3dYTkhl
      RUtPVEFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBdmtrSGZHT2VKanZvSndsSk5nbUlVSmxwCmgr
      TWNGaWtlMnB6RmowbEV6ZHdDSVFDZGV5SWNLMldJb3QvOEZEcFZ2UHNBQjByNVRkYVcrWXEyOHlV
      c0JwOHgKcGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlERVRDQ0FyZWdBd0lCQWdJVU5JWlNGMXpPcE9neE5zRk9nU1NYMUVCWkxT
      a3dDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpY
      SXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3T1RBNU1E
      SXdPVEF3V2hjTk1qTXdPVEE1TURJeE5EQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJn
      TlZCQWNURVRRM0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRI
      VnlaWEl4SXpBTUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4
      dwpIUVlEVlFRRERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemow
      Q0FRWUlLb1pJCnpqMERBUWNEUWdBRW42dUdrVndqYjAvenFCbFpSZUN0dUdwLzZ6bVJHc3dOL3FP
      bEYrSS9KNlVkL1BWOGF6UjMKdis5TnBlR2ozaGtuVTJuT3pYSHRCUktJWW1CbUZWY0hIcU9DQVNJ
      d2dnRWVNQTRHQTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdR
      V0JCVDNWUEdKMmVqYjZjelJDWEQyQ1dyWkFxdCtOVEFmCkJnTlZIU01FR0RBV2dCU1diOXFKT005
      WVR0bnhxNzZPS3dYTkhlRUtPVEFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1S
      bU9UYzJMVFZrY21jNU1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1
      cGJtbDBJam9pZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1
      Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVB
      YldGdWRXWmgKWTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dx
      aGtqT1BRUURBZ05JQURCRgpBaUVBM1lITlZYSFJLSzJsbEV2bmMwZWtlSElIU3kzck80emcyakpX
      NmFWVFN4b0NJREIvSXl1V1F0elNjLzR2Ci9KbkVMdTdOdnoyS2VGVHJXQlFsYW5NemFXU1AKLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoYGLS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSUNEVENDQWJLZ0F3SUJBZ0lVWFFib3pJU2pRaEdTbmVRL0xuNGd4ODhm
      RkFvd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAx
      Y21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5
      WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPVEE1
      TURJd01qRXdXaGNOTWpVd05qSTVNREl3TWpFd1dqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBH
      QTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFo
      Ym5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpN
      Qk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQ3EwYVVRNTM1QUhicU14NHhBc2d5Y3Nw
      YWhOTFdJSzlyeFkKKytnVGlUb0V1d0dFMWl4akk5QWFXYTc0WHBSb2s3MGpvcHhYU0cycGsvNWg1
      SG90eGxPalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21N
      QjBHQTFVZERnUVdCQlNXYjlxSk9NOVlUdG54CnE3Nk9Ld1hOSGVFS09UQUtCZ2dxaGtqT1BRUURB
      Z05KQURCR0FpRUF2a2tIZkdPZUpqdm9Kd2xKTmdtSVVKbHAKaCtNY0Zpa2UycHpGajBsRXpkd0NJ
      UUNkZXlJY0syV0lvdC84RkRwVnZQc0FCMHI1VGRhVytZcTI4eVVzQnA4eApwZz09Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoT
      EhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAa
      ExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAa
      FRITCg9tYW51ZmFjdHVyZXJNU1AQARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIG
      CAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1T
      UBKjFhq/FAoDTVNQErcUEqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVQnN3ci9paWJOdjkxZEJzWC9BUW9Kbk92TkV3d0Nn
      WUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZR
      UUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTVNRGt3TWpBME1UWmFGdzB5TlRBMk1q
      a3dNakEwTVRaYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6
      QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3
      d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFB
      VEhkWWowM1N2dnZQWWdWL0JWV1N5WlJwMUw2bTZrYW1UMzlRN0IwYXhlSDA2L29mNkVaZDhyRWt4
      b1dvVVEKRlFmWGE3OURJRUI5TDVLSFpQK1VKNWNybzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFI
      L01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVU2YU1LdEpEZFRlOTRIUGphQm9E
      ZUxPU3ZOZXN3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJZ1RaZGNjVFl4aC9kZ1dZWndpcmQ0akpO
      QVhVby9OQUc5d1lVR0NVNTFIaVFDSVFEMlpZQ08KYXEzRWxjL2dNYm03bVk1WXJ0VW9GRGU5bW93
      dVIvMXlUdTllb2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDN1RDQ0FwU2dBd0lCQWdJVVMxNTd4VmhwbVlhcFdiSGZVajJ2WHE1
      cThNd3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJj
      d0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakE1TURrd01qRXhNREJhRncw
      eU16QTVNRGt3TWpFMk1EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0
      MU1DOHRNQzR4TXk5TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFz
      VEJXRmtiV2x1TUE0R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5
      Y21sbApjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFULy9SOXZySGVZ
      U2haYWFRN1VaSGdwCkI2eFhiTU9BdTFqU2xqL0ZNZ0pSa1dMT2ppRmROUkEwbjhhZ2diYlNGOVdH
      WEQzZldtMVQ4UjAyblk3dFdWQWcKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdH
      QTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRQpGQjNNS212SWhsOFJqLzE3Z2dHSlQxWHZET0VP
      TUI4R0ExVWRJd1FZTUJhQUZPbWpDclNRM1UzdmVCejQyZ2FBCjNpemtyelhyTUNRR0ExVWRFUVFk
      TUJ1Q0dXTmhMWFJ2YjJ4ekxUWmtOR00yWmpjMlpHWXRObkZpZG5Jd2dZMEcKQ0NvREJBVUdCd2dC
      QklHQWV5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUow
      Y25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNi
      V1Z1CmRFbEVJam9pUVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRh
      VzRpZlgwd0NnWUkKS29aSXpqMEVBd0lEUndBd1JBSWdHOUpRbjgySm5UNEpEb1A1bFZEU2lPbDJJ
      cUlqRlhXeGNBZ1JISERQNFk0QwpJQVpVaEZtZC81QzJqb1NzRGs3REpENWxMdXJSQWk3TngrQjFE
      Q0ZGNkJGcAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVCc3dyL2lpYk52OTFk
      QnNYL0FRb0puT3ZORXd3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5C
      Z05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZ
      WEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBNU1Ea3dN
      akEwTVRaYUZ3MHlOVEEyTWprd01qQTBNVFphTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApW
      UVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNt
      bGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkMKQUFUSGRZajAzU3Z2dlBZZ1YvQlZXU3laUnAxTDZtNmthbVQzOVE3QjBh
      eGVIMDYvb2Y2RVpkOHJFa3hvV29VUQpGUWZYYTc5RElFQjlMNUtIWlArVUo1Y3JvMEl3UURBUEJn
      TlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVTZh
      TUt0SkRkVGU5NEhQamFCb0RlTE9Tdk5lc3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUlnVFpkY2NU
      WXhoL2RnV1lad2lyZDRqSk5BWFVvL05BRzl3WVVHQ1U1MUhpUUNJUUQyWllDTwphcTNFbGMvZ01i
      bTdtWTVZcnRVb0ZEZTltb3d1Ui8xeVR1OWVvZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZB
      ZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZB
      ZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlu
      cyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZB
      ZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIE
      EgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYK
      EEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5n
      U3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRl
      cmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1p
      bnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRl
      cnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
