apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIH9LfvHLUdZlef0eg4SlzOsP05mcHdOjB+XvDOZCtN3iEpJeCo9eCoxeCngKWggBEAEaBgj6
      lq6WBiIKc3lzY2hhbm5lbCpAMjk2NDNlYzBhODEwOTUyZmU2YWQ2NTY2NjI5M2RlZmQzOTcwZWZm
      NTUyYzg2NzAyNmQxZjQ2YmZkNmNjMzRkYRIaEhi2UIxxLpm4/lDcl8/6F97ORhisT9qrJ+ISj10K
      jF0SiV0SiSsKB09yZGVyZXIS/SoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVVDhmUVVobWdJNEpjNVF0VU1jTTFPRUtlaVV3d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFeE1ESXhOREUzV2hjTk1qVXdORE13TURJeE5ERTNX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJDZjlT
      NGxhRE5ZSm1XNWY1RzBzQ0UraGRDR1Vqd3ZPd2lhREFyUEFZcmhUdStGWlZ4c2IKNXNPdEJyMkJk
      UUdIZlgrZTlTVm90RlNzaGRjT3BBaGZhZGlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0tvaTZwODgrZktvNDZmcnNMVE9EM29R
      Yk9nakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBL2lZOE80TGF0R3hwKzhZMkNCcGJBbWVzYjEw
      RFZUSVJrMXdiQkxGbTUKRmdJaEFPSGM0M1B4eFJpdXBvTDZBQ1ZUTFZiWTQ0bVJwMG10dWMrZVNi
      VWs0WHd1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVR3pVQXc5WlRLT3RiRGFqUkcrb2xIVys0Vys4d0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFeE1ESXlNakF3V2hjTk1q
      TXdOekV4TURJeU56QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZjNTanFUTFNLeHdoVmFuMjZXWmhrZVpsOEc3
      VS9zbUQKT2tQQ2RJamJtZjZra0pVTE1zY25iR0tjQmpNWXZsWHFkZGtOQWJwYjNIbXEzTXBxQ0dv
      aHZLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTeUdJV3dMdTk3CmVDZkR2UGx0bWJRQjFUQ3NkekFmQmdOVkhTTUVHREFXZ0JT
      S29pNnA4OCtmS280NmZyc0xUT0Qzb1FiT2dqQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xXMXNOR3M1TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnUFJieEhiVll5ZUN3dXJRSDF6S0xZYktRTlpLRnpaTHErSlppMklRSzRiOENJSHpv
      M3U2U2tZSGt5UkRGCnJjYlpPNkhmTTRLTlZUTjJuZWhWRHhWK2t0aUkKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVVDhmUVVobWdJNEpjNVF0VU1jTTFPRUtlaVV3d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFeE1ESXhOREUzV2hjTk1qVXdORE13
      TURJeE5ERTNXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJDZjlTNGxhRE5ZSm1XNWY1RzBzQ0UraGRDR1Vqd3ZPd2lhREFyUEFZcmhUdStGWlZ4c2IK
      NXNPdEJyMkJkUUdIZlgrZTlTVm90RlNzaGRjT3BBaGZhZGlqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0tvaTZwODgrZktvNDZm
      cnNMVE9EM29RYk9nakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBL2lZOE80TGF0R3hwKzhZMkNC
      cGJBbWVzYjEwRFZUSVJrMXdiQkxGbTUKRmdJaEFPSGM0M1B4eFJpdXBvTDZBQ1ZUTFZiWTQ0bVJw
      MG10dWMrZVNiVWs0WHd1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMaghIKDUNvbnNlbnN1
      c1R5cGUS8BES5REKCGV0Y2RyYWZ0EtgRCsERChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijca
      zwgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREFqQ0NBcW1nQXdJQkFnSVVTeXVvSXQ1
      WlRBV05rNFpqOGdoYnYvQnNXUGt3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhj
      Tk1qSXdOekV4TURJeU1qQXdXaGNOTWpNd056RXhNREl5TnpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pI
      UWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQ
      Y21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5
      TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05D
      QUFTbmZxdVp4UGJEQjRjd3ZSc1ZFMXlLUXJIdgpjaDdLUGNocWZibmpHbDZQWjFPOENGcmloSGlV
      RTcxdHdjWW9GdG1vZUczSzd4WnRlbTdRMmF5ckQvb0VvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgv
      QkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05W
      SFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSZGlIamtNbW5ZMmgvOEY4eUJDMHVBb21FTgpqakFm
      QmdOVkhTTUVHREFXZ0JTS29pNnA4OCtmS280NmZyc0xUT0Qzb1FiT2dqQS9CZ05WSFJFRU9EQTJn
      aGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNi
      M0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1a
      bWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVj
      M1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlL
      b1pJemowRUF3SURSd0F3UkFJZ2RzTUtqV0NCc1Qvc2JFbG0KVkg3UmJsc3BIMWRtVno5YnNFcHc0
      NHdzNjhnQ0lDUFhxOURpbnh3c3VuS0FsN0JBVjZPaWJwN0hSY0ZkYXVRMwp6Q1RuWjJaZAotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiLPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlE
      QWpDQ0FxbWdBd0lCQWdJVVN5dW9JdDVaVEFXTms0Wmo4Z2hidi9Cc1dQa3dDZ1lJS29aSXpqMEVB
      d0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpk
      WEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RXhNREl5TWpBd1doY05Nak13TnpFeE1ESXlO
      ekF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZU
      Rzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlN
      U0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Fo
      a2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNuZnF1WnhQYkRCNGN3dlJzVkUxeUtRckh2CmNoN0tQ
      Y2hxZmJuakdsNlBaMU84Q0ZyaWhIaVVFNzF0d2NZb0Z0bW9lRzNLN3hadGVtN1EyYXlyRC9vRW80
      SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3
      TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJkaUhqa01t
      blkyaC84Rjh5QkMwdUFvbUVOCmpqQWZCZ05WSFNNRUdEQVdnQlNLb2k2cDg4K2ZLbzQ2ZnJzTFRP
      RDNvUWJPZ2pBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpY
      U0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJH
      QjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JX
      VnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pT
      STZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnZHNNS2pXQ0JzVC9zYkVs
      bQpWSDdSYmxzcEgxZG1Wejlic0VwdzQ0d3M2OGdDSUNQWHE5RGlueHdzdW5LQWw3QkFWNk9pYnA3
      SFJjRmRhdVEzCnpDVG5aMlpkCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoY
      ASAFKICAgAgaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxC
      YXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRt
      aW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxK5LwoLQ29u
      c29ydGl1bXMSqS8S3i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLELhKxFwoPbWFudWZhY3R1cmVy
      TVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1TUBKBBi0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lCQWdJVUYrUUJxMDd0UFd1aExDU1Mxa3F0U25r
      QWJSd3dDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxw
      MWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhW
      eVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpF
      eE1ESXhOakl5V2hjTk1qVXdORE13TURJeE5qSXlXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEw
      R0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUx
      aGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJa
      TUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkR3dTNtclZaV2k5aVlkeTVUejNibVBp
      ZHFpVEZkR2dHVVYwCmovMVZqZjRWVUlWRFRGWUVPN0YzdDllK0tJSmNsK2sraUpyRFNOZmx2V0xK
      V0ZTZmp3aWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dt
      TUIwR0ExVWREZ1FXQkJRMENCTTd0aGtMaVV0Qwp0THZ2TGo1ei8rVHVYVEFLQmdncWhrak9QUVFE
      QWdOSEFEQkVBaUFmWnJpaXRya3M1TytUektGTFdsN3lnZk5jCkxkSlBzcXlXYWpEQkl4bXBrd0ln
      SE40Q3RoYlpaZnBsSFRvQXR5OUsvMXB5Wkl5K0VQNTQxNHFSN1dCdUpOND0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREVUQ0NBcmVn
      QXdJQkFnSVVkaSthN2cvQUtQa2VTcnkyODJGZzZsVVI0RUl3Q2dZSUtvWkl6ajBFQXdJdwpaREVM
      TUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlh
      V05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhi
      blZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056RXhNREl5TXpBd1doY05Nak13TnpFeE1ESXlP
      REF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNMak00THpndU5UUXZX
      blZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6QU1CZ05WQkFzVEJXRmti
      V2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZRUUREQlpCWkcxcGJrQnRZ
      VzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6ajBEQVFjRFFnQUVF
      S2xDNWw2SGFtRUpyTHB4YUJzUGJEQTRrUk03ZFRNL1h4RER3RmVrMUF2cGZqc3A3RnZnCkNKZXU2
      OGgwZStZV0JVWlA5SmJKMVBrU0RweWphMnZqTHFPQ0FTSXdnZ0VlTUE0R0ExVWREd0VCL3dRRUF3
      SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFxTGo4eHpkckFKQmVBYUc0azU4
      cS91TEFzWWpBZgpCZ05WSFNNRUdEQVdnQlEwQ0JNN3Roa0xpVXRDdEx2dkxqNXovK1R1WFRBa0Jn
      TlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAzWTJRM1ptUm1PVGMyTFdSM1luRTNNSUdYQmdncUF3
      UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JX
      bHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldGdWRXWmhZM1IxY21WeUlp
      d2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1poClkzUjFjbVZ5TFc1bGRD
      SXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQWta
      ODlGbnQrbWt1bUZMaUFPcGY0Y0dzbUw4TDhad29SU3dxdkgzUVhVR0FDSUR0K3c2c21zR1BSYnhq
      MApoTlBPcGJGLy9ycWxtelFqREkvVW1JcUtYQUFlCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      Qg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0Fi
      S2dBd0lCQWdJVUYrUUJxMDd0UFd1aExDU1Mxa3F0U25rQWJSd3dDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpFeE1ESXhOakl5V2hjTk1qVXdORE13TURJ
      eE5qSXlXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZ
      RFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFV
      RUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000
      OUF3RUhBMElBQkR3dTNtclZaV2k5aVlkeTVUejNibVBpZHFpVEZkR2dHVVYwCmovMVZqZjRWVUlW
      RFRGWUVPN0YzdDllK0tJSmNsK2sraUpyRFNOZmx2V0xKV0ZTZmp3aWpRakJBTUE4R0ExVWQKRXdF
      Qi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJRMENCTTd0aGtM
      aVV0Qwp0THZ2TGo1ei8rVHVYVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFmWnJpaXRya3M1TytU
      ektGTFdsN3lnZk5jCkxkSlBzcXlXYWpEQkl4bXBrd0lnSE40Q3RoYlpaZnBsSFRvQXR5OUsvMXB5
      Wkl5K0VQNTQxNHFSN1dCdUpOND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4
      CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMi
      OAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5z
      IjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBABGgZBZG1p
      bnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1Aa
      BkFkbWlucyoGQWRtaW5zErIWCgpjYXJyaWVyTVNQEqMWGr8UCgNNU1AStxQSrBQSqRQKCmNhcnJp
      ZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVN
      NGU1a2xRTUdCNXpsOWFSSURaeFppT2FwN0F3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVC
      aE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdE
      Z1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3
      MHkKTWpBM01URXdNakU0TXpWYUZ3MHlOVEEwTXpBd01qRTRNelZhTUZveEN6QUpCZ05WQkFZVEFr
      ZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0Ex
      VUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJn
      Y3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUVmdkdUphY3M4RkhQNjMyQXdubjNWZHc1TjNx
      WGt3Ykd3QjhrQ2pSLzZTaloxR2FsYlVFcHhQbDFpbnFCdwp6WjV4cDJhYUdSdUlVRnRtd29qL1NI
      eE5vMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJn
      TlZIUTRFRmdRVUhieUhRR2JvRENPZndiUkdhOEZ0NXFxam5iUXdDZ1lJS29aSXpqMEUKQXdJRFNB
      QXdSUUloQUl0QTFXQjlCUnlyQ1BPaEdLamwyQ1B3aW9MV1NiU3diaURDVjhtbkcrUS9BaUJ6dU40
      WAplbzlMLzRJMFpLLy9VTUl1U3ZiTDN5MjRUdTg1ZDNuUnRNSmZpQT09Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KIrIILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3VENDQXBTZ0F3
      SUJBZ0lVWFp2R0tmbzYvOG04Sy9UL2pkVFh0TlVJWlNJd0NnWUlLb1pJemowRUF3SXcKV2pFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5
      dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1
      bGREQWVGdzB5Ck1qQTNNVEV3TWpJMk1EQmFGdzB5TXpBM01URXdNak14TURCYU1IZ3hDekFKQmdO
      VkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdO
      VkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFVRUN4TUhZMkZ5Y21s
      bGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJ
      QkJnZ3Foa2pPUFFNQkJ3TkNBQVJFc1Q1TGQ2bUZPWERUWElnZnlxamQKd0NOU1M2VThvZTNkd01B
      eGQzN3lWd2FvR3VXa2hBc2NPSXQ5MmZBWEZuNFhOazAzZGFoK1J0eHhtekU4MCtjNwpvNElCR0RD
      Q0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllF
      CkZMMmRtUzlYMlBCYjBVZmYyaGtZczJ4Z1pvbTBNQjhHQTFVZEl3UVlNQmFBRkIyOGgwQm02QXdq
      bjhHMFJtdkIKYmVhcW81MjBNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6TFRaa05HTTJaamMy
      WkdZdGNEVjJabm93Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2ZXlKaFltRmpMbWx1
      YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cFlYUnBiMjRp
      T2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0YVc1QVkyRnljbWxs
      Y2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJemowRUF3SURSd0F3
      UkFJZ0JMNGNja3QzZ0N3bzI4MDE3ODRVVHR5STl3N09KcEdOMzdCcVY5WTVKWUlDCklDQ3pKd3dM
      aE9HOHM5c0h6SUNhRC9KSkV4YU1CZHNQRXFTV1B6RmV3VEM2Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlC
      K0RDQ0FaNmdBd0lCQWdJVU00ZTVrbFFNR0I1emw5YVJJRFp4WmlPYXA3QXdDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNakEzTVRFd01qRTRNelZhRncweU5UQTBNekF3TWpFNE16VmFN
      Rm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01C
      a3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnlj
      bWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRWZ2R1SmFjczhG
      SFA2MzJBd25uM1ZkdzVOM3FYa3diR3dCOGtDalIvNlNqWjFHYWxiVUVweFBsMWlucUJ3CnpaNXhw
      MmFhR1J1SVVGdG13b2ovU0h4Tm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3
      RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVSGJ5SFFHYm9EQ09md2JSR2E4RnQ1cXFqbmJRd0Nn
      WUlLb1pJemowRQpBd0lEU0FBd1JRSWhBSXRBMVdCOUJSeXJDUE9oR0tqbDJDUHdpb0xXU2JTd2Jp
      RENWOG1uRytRL0FpQnp1TjRYCmVvOUwvNEkwWksvL1VNSXVTdmJMM3kyNFR1ODVkM25SdE1KZmlB
      PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4I
      ARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoS
      CBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYI
      ARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggA
      GhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xp
      Y3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlu
      cyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVy
      ZXIxLnN1cHBseWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxokCgxDYXBh
      YmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZT
      SEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRt
      aW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMS
      CQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZB
      ZG1pbnMaDgoECgIKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
