apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIDdv2bklb7yKL45enTwSW5LH5TyT4rMwYmTGNlKy6ztrEpJeCo9eCoxeCngKWggBEAEaBgiZ
      j9OWBiIKc3lzY2hhbm5lbCpAZWVhYmUyOWE0YzYzN2VmNjhkODkyNDljZjFhY2Y0ZTlhOWQ1ZTlm
      MThiNGY3M2MzYjYzYjQxODkyMDhmMjQ4ZRIaEhimC9hrEGxGSC5qtJLBQFAJsYpVRBwmHW4Sj10K
      jF0SiV0SjysKB09yZGVyZXISgysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVR2ZId3p3aHBXU1YrcGZZSXlnQkljQXNGRzNJd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFNE1ESXlNVEUwV2hjTk1qVXdOVEEzTURJeU1URTBX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJNZEts
      MUQ3d3VSR1dPL2Y2ZXMxZUJ2VkUrU2VBZEsxejVZeGJ2Q1ljWEkvTXZXUmhTaXoKOWdTaGE3SGgx
      bnBMRDMvai9QVWRtRzROQkRBeFNjS3dub0dqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVHRScCtSelVKZXk0NTM4SkJ0ZXhHUjR2
      R0pqVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBQlovWEgrQ3JmWkRYeGNsaE5xNGtmbkE3aEFt
      cGhZUE1EZFNUOXczemwKYXdJaEFPRHFPWko0cFkxT0NycXBOK0ZDMDZMQWxZZUFqeDJhQStnRytq
      c3dtczZUCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVVXl2SGJxUjUxNGVmbTFJcGZNV0U0aldaR0pzd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFNE1ESXlPVEF3V2hjTk1q
      TXdOekU0TURJek5EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOWFlUllaeXdDdWZRakY0TkNFOVlBTWNCU0h2
      UW41WkwKWFd0L3llazNKaXhKWXpEN3k3SU5MektqOTJjbFo4NDhVcVpIN2tqS2x4UVI2Y2dzLzZ4
      dTNhT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTRldmbm1LLys0CnFCcTVMbjlOYXA0RHN4dkpSekFmQmdOVkhTTUVHREFXZ0JU
      dFJwK1J6VUpleTQ1MzhKQnRleEdSNHZHSmpUQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xUSm5ZbVp1TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQU1OaUNVMHVLU3FJNCtOQ2dQbUQyOGttUHRibjBTb0ZzTmZ0aFpFK3hLM1ZBaUFH
      K05lV1hlU1QyejZCClVlU1JDMm54WDdoK2JEUFBXRGVTdE9SdUF0d2dhQT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVUdmSHd6d2hwV1NWK3BmWUl5Z0JJY0FzRkczSXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RTRNREl5TVRFMFdoY05NalV3
      TlRBM01ESXlNVEUwV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCTWRLbDFEN3d1UkdXTy9mNmVzMWVCdlZFK1NlQWRLMXo1WXhidkNZY1hJL012V1Jo
      U2l6CjlnU2hhN0hoMW5wTEQzL2ovUFVkbUc0TkJEQXhTY0t3bm9HalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlR0UnArUnpVSmV5
      NDUzOEpCdGV4R1I0dkdKalRBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQUJaL1hIK0NyZlpEWHhj
      bGhOcTRrZm5BN2hBbXBoWVBNRGRTVDl3M3psCmF3SWhBT0RxT1pKNHBZMU9DcnFwTitGQzA2TEFs
      WWVBangyYUErZ0cranN3bXM2VAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjsK
      C0VuZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1p
      bnMqBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0
      cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlu
      cxqCEgoNQ29uc2Vuc3VzVHlwZRLwERLlEQoIZXRjZHJhZnQS2BEKwREKGG9yZGVyZXIxLnN1cHBs
      eWNoYWluLW5ldBCKNxrPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQWpDQ0FxbWdB
      d0lCQWdJVWZFdDRRWUhNYnJJY1U3bVNYN1I0WGtrZElJTXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpJd056RTRNREl5T1RBd1doY05Nak13TnpFNE1ESXpOREF3V2pCeE1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZR
      UURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkNBQVFiR0xjMXE5V1VQcnVMNDB4SU9aaGR1d0xGCmgvN0k2VXQ0aUZSOTdp
      eWRwN2pUN05oNHF6aFpja0hPREE2SVBkVVJ4c2JmOForektMcjV0UmpxbHZ4K280SUIKTURDQ0FT
      d3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdF
      RgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJlSFJoV2szcmUxVGFKSkZC
      YzlwT1dySFVYClh6QWZCZ05WSFNNRUdEQVdnQlR0UnArUnpVSmV5NDUzOEpCdGV4R1I0dkdKalRB
      L0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdW
      eVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhK
      eklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpv
      aWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdW
      eVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnSTVORU8rL0VnQUVYR2puQgpFcVhuUVY0
      cmo4MENPL0phTXFZTFlrd09UbndDSUUzUlJrazNpRGV2TnNXRjNYOCt3ZXlvMnRxdkdaRVNLU3hn
      ClJwR0NyVzRkCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIs8ILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVZkV0NFFZSE1ickljVTdtU1g3UjRYa2tkSUlN
      d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZ
      RFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFNE1ESXlPVEF3V2hj
      Tk1qTXdOekU0TURJek5EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRF
      dU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFR
      TEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1
      ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUWJHTGMxcTlXVVBydUw0MHhJ
      T1poZHV3TEYKaC83STZVdDRpRlI5N2l5ZHA3alQ3Tmg0cXpoWmNrSE9EQTZJUGRVUnhzYmY4Wit6
      S0xyNXRSanFsdngrbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFX
      TUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVk
      RGdRV0JCUmVIUmhXazNyZTFUYUpKRkJjOXBPV3JIVVgKWHpBZkJnTlZIU01FR0RBV2dCVHRScCtS
      elVKZXk0NTM4SkJ0ZXhHUjR2R0pqVEEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dH
      Q0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kK
      YUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJ
      aXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdJ
      NU5FTysvRWdBRVhHam5CCkVxWG5RVjRyajgwQ08vSmFNcVlMWWt3T1Rud0NJRTNSUmtrM2lEZXZO
      c1dGM1g4K3dleW8ydHF2R1pFU0tTeGcKUnBHQ3JXNGQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoSEgoFNTAwbXMQChgBIAUogICAChoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICA
      QBoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxKx
      LwoLQ29uc29ydGl1bXMSoS8S1i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRK8LhKxFwoPbWFudWZh
      Y3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1TUBKBBi0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVVlRMWg2NU1uaFpQUStsVTBx
      MnZ5NEFKaTQwQXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFa
      bUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05N
      akl3TnpFNE1ESXlNekUyV2hjTk1qVXdOVEEzTURJeU16RTJXakJrTVFzd0NRWURWUVFHCkV3SkRT
      REVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJB
      b00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxX
      NWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkJ4WnVSZS80dHRlZlVhd0RJ
      dGxIV2V5Y3orQVlNZDZES2NHCmZCSWhkOEl3SHBiNEtQQ1hFdkhtaXpCUHZyd0I3S0wzL0QyaC9n
      cmJXeDZpYUhQNi93S2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJUTTRXcGgzbmM5Zk1hUApmT25wRzhJYnJFY1VqakFLQmdncWhr
      ak9QUVFEQWdOSUFEQkZBaUFDQXVFN25sZWp3NDh5NTlieWl3OXF6OGNRCnppTDN1R2ZIdTdvSy9v
      cnc1d0loQUlEM2dQRllHa1RTcmNxRmo2cmlyNDVIL05HN01aaTRuYkM4NkpNbXhiVTQKLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREVU
      Q0NBcmVnQXdJQkFnSVVJVk5ha2FYYVJUTC9WN0tWZWxOVkFyQnNITVV3Q2dZSUtvWkl6ajBFQXdJ
      dwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3
      R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJO
      aExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056RTRNREl6TURBd1doY05Nak13TnpF
      NE1ESXpOVEF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNMak00THpn
      dU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6QU1CZ05WQkFz
      VEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZRUUREQlpCWkcx
      cGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6ajBEQVFj
      RFFnQUVuME0rc245d0ROb0ZpUEZlMjJ6bGxCRFpmenJpL0Rhd0FmR2dHWk9mZkwxbmhHTXVCbmxp
      Ck9OenUyUUJaa2JOd1BVSTNhMW1MdUNucTQ5RHhUd1orMjZPQ0FTSXdnZ0VlTUE0R0ExVWREd0VC
      L3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFXbCtNc3hydEVnYXJ0
      ZTJKdnNiWlNaVU9SS2pBZgpCZ05WSFNNRUdEQVdnQlRNNFdwaDNuYzlmTWFQZk9ucEc4SWJyRWNV
      ampBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAzWTJRM1ptUm1PVGMyTFdKMmJuZzBNSUdY
      QmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpvaWRISjFaU0lz
      SW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldGdWRXWmhZM1Ix
      Y21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1poClkzUjFjbVZ5
      TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkYK
      QWlFQTVhOWJ2UkVkYVkyLzNRSmluNHcxZ0NvcXVuaW93S3pzaDVMOVprNm5vOTBDSUZGbWN2c0Ja
      YWNSanNPMQpUY3ROQTI3R3dUYTdyU09yWFd3emt4c3VvYVdnCi0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      RERDQ0FiS2dBd0lCQWdJVVlRMWg2NU1uaFpQUStsVTBxMnZ5NEFKaTQwQXdDZ1lJS29aSXpqMEVB
      d0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1F
      Mk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpFNE1ESXlNekUyV2hjTk1qVXdO
      VEEzTURJeU16RTJXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9N
      UTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNN
      Qm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdD
      Q3FHU000OUF3RUhBMElBQkJ4WnVSZS80dHRlZlVhd0RJdGxIV2V5Y3orQVlNZDZES2NHCmZCSWhk
      OEl3SHBiNEtQQ1hFdkhtaXpCUHZyd0I3S0wzL0QyaC9ncmJXeDZpYUhQNi93S2pRakJBTUE4R0Ex
      VWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJUTTRX
      cGgzbmM5Zk1hUApmT25wRzhJYnJFY1VqakFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUFDQXVFN25s
      ZWp3NDh5NTlieWl3OXF6OGNRCnppTDN1R2ZIdTdvSy9vcnc1d0loQUlEM2dQRllHa1RTcmNxRmo2
      cmlyNDVIL05HN01aaTRuYkM4NkpNbXhiVTQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFk
      bWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZB
      ZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoG
      QWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBAB
      GgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyoGQWRtaW5zEqoWCgpjYXJyaWVyTVNQEpsWGrcUCgNNU1ASrxQSpBQSoRQK
      CmNhcnJpZXJNU1AS5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjl6Q0NBWjZnQXdJ
      QkFnSVVJOHBEZVdVSE5TYktLY2NYMnNmZFRLS2RRVUV3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVs
      ZERBZUZ3MHkKTWpBM01UZ3dNakkxTVRoYUZ3MHlOVEExTURjd01qSTFNVGhhTUZveEN6QUpCZ05W
      QkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVR
      TUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3
      V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTdFdJekZhREZqSWpBZkpVT2dZdDI5
      R1R3UnhUcTJxOVZYYnVKNkZaWVIvenh3ZVpPUXpVNGF2RXZtOWNUcQpwN0xTZmJnQ0lMSCswRnpQ
      d0d1ZVFmRW1vMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lC
      cGpBZEJnTlZIUTRFRmdRVWdoN1p4NlRRWmVHdDNjbFVOd1NtM1lCUW5sc3dDZ1lJS29aSXpqMEUK
      QXdJRFJ3QXdSQUlnTDBZUGNmclVHNGZvTDJKNjE3TE9zK0xnQ3k2V29JR1ByQnFWZFVXMkl1c0NJ
      SG1JTTA2YQp0WjJ4dWdrN2hMWEZDUzhIZW5mZy9YeXJCN1hPWXBkYVVLcHYKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdEQ0NBcFNn
      QXdJQkFnSVVCNmtCWnRSTllpRmJCNWRkNnhOUUlmTGp0Um93Q2dZSUtvWkl6ajBFQXdJdwpXakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlM
      VzVsZERBZUZ3MHkKTWpBM01UZ3dNak15TURCYUZ3MHlNekEzTVRnd01qTTNNREJhTUhneEN6QUpC
      Z05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9C
      Z05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnlj
      bWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQ0FBUUVTWHZ2WUlmaTJTTDdseURZeGttNQpteXhXbmdwOGx3WU9F
      RkIwbC9FOTY4T0p6ZU01Ulk0NTlDU1c0YzJKRitmVnpJME1ESFFITnJVNkVJWXB1SXBYCm80SUJH
      RENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JC
      WUUKRkFKZEgrSVU2MW54dE40NTk3SzYyeE1FajdPTU1COEdBMVVkSXdRWU1CYUFGSUllMmNlazBH
      WGhyZDNKVkRjRQpwdDJBVUo1Yk1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFprTkdNMlpq
      YzJaR1l0WnpSdGNIWXdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1Gakxt
      bHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIy
      NGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNt
      bGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFJn
      QXdRd0lnTk9TZmdvbmpDVXF4TkwxMmVqVUNpTGFVSjBzQ25ETVFrZGhabWwyN1d4NEMKSDEwWlFS
      ZHQ5a0NSV1h1MklUVHNEQVZzeEFIQ1dzeHJ3MFVpWGxSeVdzST0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUI5ekNDQVo2Z0F3SUJBZ0lVSThwRGVXVUhOU2JLS2NjWDJzZmRUS0tkUVVFd0NnWUlLb1pJemow
      RUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1
      allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNVGd3TWpJMU1UaGFGdzB5TlRBMU1EY3dNakkxTVRo
      YU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFj
      TUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJG
      eWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU3RXSXpGYURG
      aklqQWZKVU9nWXQyOUdUd1J4VHEycTlWWGJ1SjZGWllSL3p4d2VaT1F6VTRhdkV2bTljVHEKcDdM
      U2ZiZ0NJTEgrMEZ6UHdHdWVRZkVtbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVk
      RHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVnaDdaeDZUUVplR3QzY2xVTndTbTNZQlFubHN3
      Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ0wwWVBjZnJVRzRmb0wySjYxN0xPcytMZ0N5NldvSUdQ
      ckJxVmRVVzJJdXNDSUhtSU0wNmEKdFoyeHVnazdoTFhGQ1M4SGVuZmcvWHlyQjdYT1lwZGFVS3B2
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAES
      GhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4IARIaEggS
      BggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAES
      AggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQ
      Eg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5
      EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMq
      Fy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVy
      MS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJp
      bGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZT
      SEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRt
      aW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMS
      CQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZB
      ZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
