apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIF5rEQhkr00n2VqIF/JS1dBR1g4PWGn79SVhXKHhYOlfEqBeCp1eCppeCngKWggBEAEaBgiE
      zb6WBiIKc3lzY2hhbm5lbCpAOWU0MjhlMTg3ZGNkYzkxNmU3YWY5ZjllNTM3NzMxZTUwNmI4ZDA4
      M2IyMGY5ODQwMDkzNjY0ODU0NzE3ZmEzZhIaEhhFCB6HFj7zed/K4oyTKbkuwM6eUGNHTjoSnV0K
      ml0Sl10SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVUEJQZjJVZm5lV2twTGFnZ0tDY09wVnRBNUVrd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFME1EUTFPREU1V2hjTk1qVXdOVEF6TURRMU9ERTVX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJPaUlB
      MkIvSURrWGlRSDRuY291RUM0L3ZBaXJKTzQySFdPN3NQd3pCNnlDYXdIZnhKN1gKTU5Db0FrUU9r
      RWtKSHJzcmZuR0x1cnRmMWg0RWZOejFDRWFqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUTcwR1hOWGMzUVZaTEJEQ1BGOE5hTStQ
      c3dEREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBeXBubnJWNWo2TmVzYmRtYkpsdVF6UUF2Z1lN
      eU9RLzUwWVZkazZReVYKR1FJaEFQU0Z3eFQ1cHRTYUdHQnJwS2IyY3o1Z1V1ZkgwTGM2VTdHTG1m
      em1GbkN5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVSlpDSzZHNDYwL0p1TC82OFNHVlRTb1dPQngwd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFME1EVXdOakF3V2hjTk1q
      TXdOekUwTURVeE1UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFTVZoRDdHOFlFTDY3bHNqc042NEFKRUNOV1Nx
      RklaTnYKQisrZmUyMm5SdGJiS0JBdS9sbzJscFBEZ0NnbWt4SW9uZUxqLzFVQlBweG9uZGZPLzhq
      RnY2T0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRbUk1ZDFjUXlmCjl0NGwwSHBvSytuZ3BlMVAxVEFmQmdOVkhTTUVHREFXZ0JR
      NzBHWE5YYzNRVlpMQkRDUEY4TmFNK1Bzd0REQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xXeGtOM28xTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnUDFRRlhTQlhyazFkazF1N0haTVI2Q1JDV0h4blpuUFhVN2dJd3JESXBmUUNJR0Zx
      ZUlBYTZVVGJvL050CkxPM0t4YTV1d2EwSitCeWljMVFIMDFGU09ObSsKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVUEJQZjJVZm5lV2twTGFnZ0tDY09wVnRBNUVrd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFME1EUTFPREU1V2hjTk1qVXdOVEF6
      TURRMU9ERTVXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJPaUlBMkIvSURrWGlRSDRuY291RUM0L3ZBaXJKTzQySFdPN3NQd3pCNnlDYXdIZnhKN1gK
      TU5Db0FrUU9rRWtKSHJzcmZuR0x1cnRmMWg0RWZOejFDRWFqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUTcwR1hOWGMzUVZaTEJE
      Q1BGOE5hTStQc3dEREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBeXBubnJWNWo2TmVzYmRtYkps
      dVF6UUF2Z1lNeU9RLzUwWVZkazZReVYKR1FJaEFQU0Z3eFQ1cHRTYUdHQnJwS2IyY3o1Z1V1Zkgw
      TGM2VTdHTG1mem1GbkN5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGoISCg1Db25zZW5zdXNUeXBlEvAREuUR
      CghldGNkcmFmdBLYEQrBEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3Gs8ILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVQXRpSVpHZ3lLODRBNHlzY2VO
      RnZLcDhNRTI0d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFME1E
      VXdOakF3V2hjTk1qTXdOekUwTURVeE1UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUlVhU2hOZTN6
      Zm55eUNmUHRHQjVacHVleGkKcmFrQWFQc09Rc0FaZXMvbUVSN2J1SjBXY1l2THdKejBpVkxTMGlY
      QTFOMDhHUzlCazY5RlFYNWt5TCszbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCU2NNVUlKdDhSWWJVQkZGanQvZjVyVUEvZXEKVERBZkJnTlZIU01FR0RB
      V2dCUTcwR1hOWGMzUVZaTEJEQ1BGOE5hTStQc3dEREEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1
      ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1
      SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmho
      YVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBd1JBSWdlNkJLZ2NzTUcwWmowZitiCnBzZmdUb2tvek90eDdSSFF2bXVWV3d1YTRQTUNJQ2Y0
      dTFhSnk5TE1UNVJoa25VQmtuVVo2NU5vWXFOTEtaUnQKNlc4QWNTNXgKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQoizwgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREFqQ0NBcW1nQXdJ
      QkFnSVVBdGlJWkdneUs4NEE0eXNjZU5GdktwOE1FMjR3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0Zw
      YmkxdVpYUXcKSGhjTk1qSXdOekUwTURVd05qQXdXaGNOTWpNd056RTBNRFV4TVRBd1dqQnhNUXN3
      Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3
      RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFE
      RXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DQUFSVWFTaE5lM3pmbnl5Q2ZQdEdCNVpwdWV4aQpyYWtBYVBzT1FzQVplcy9t
      RVI3YnVKMFdjWXZMd0p6MGlWTFMwaVhBMU4wOEdTOUJrNjlGUVg1a3lMKzNvNElCCk1EQ0NBU3d3
      RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYK
      QlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTY01VSUp0OFJZYlVCRkZqdC9m
      NXJVQS9lcQpUREFmQmdOVkhTTUVHREFXZ0JRNzBHWE5YYzNRVlpMQkRDUEY4TmFNK1Bzd0REQS9C
      Z05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnla
      WEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJ
      anA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2li
      M0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnla
      WElpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ2U2QktnY3NNRzBaajBmK2IKcHNmZ1Rva296
      T3R4N1JIUXZtdVZXd3VhNFBNQ0lDZjR1MWFKeTlMTVQ1UmhrblVCa25VWjY1Tm9ZcU5MS1pSdAo2
      VzhBY1M1eAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZB
      ZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0I
      AxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMi
      KgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zEsMvCgtD
      b25zb3J0aXVtcxKzLxLoLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEs4uErsXCg9tYW51ZmFjdHVy
      ZXJNU1ASpxcarxUKA01TUBKnFRKcFRKZFQoPbWFudWZhY3R1cmVyTVNQEoYGLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUNEVENDQWJLZ0F3SUJBZ0lVWjNubVpIYnpGU3pMdlhLMlRON2Vp
      TENFWlRVd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdO
      ekUwTURVd01ESXpXaGNOTWpVd05UQXpNRFV3TURJeldqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBN
      QTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpE
      RTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGRE
      QlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTmFMbThVNko2ZTB2bWo5K3dKWExu
      cUh5QVpmNjMwT3Z1bVIKbmZmRHlYa1Z1MXRBUjVIY1dVQmtZOHlGVUlCVHNFOUFzaktSQ0VmUGVy
      ODdGeDcrTW9xalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlJkQ0tGSTlzNFB0aFNMClRKelczR0k1ZU9QcDdEQUtCZ2dxaGtqT1BR
      UURBZ05KQURCR0FpRUErZnd5cGYrQ3Z1MkdyTTVnSWtsUXFQdTIKcTZTTkREeXRUeDRHd3AxYTJH
      OENJUUR5RTBYaHJPUElqSVArYWZqMVdPalFkdXh0UmRYNjhadGoya1hmeGdHcwpuZz09Ci0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURF
      VENDQXJlZ0F3SUJBZ0lVYnJ6cnRhd1BVOEIzUTJZOUVheFEvSU1IdWRBd0NnWUlLb1pJemowRUF3
      SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3
      d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUy
      TmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekUwTURVd056QXdXaGNOTWpNd056
      RTBNRFV4TWpBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpNNEx6
      Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdOVkJB
      c1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJaQlpH
      MXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemowREFR
      Y0RRZ0FFSXB2MCtIaTc5ck5WeCtQTjcxalJUZ1NQLzdyWGNPNVgxS0NmQ0hKR3NaVFZCanNXdWFY
      YQplSzBiQThhQ3VWMFR5RTVMMFQwUTY2cE11cHhuWFk0MEZhT0NBU0l3Z2dFZU1BNEdBMVVkRHdF
      Qi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTVFAreWVsWEY2SGxV
      djI3TlVNcFZ6YXcxMGFqQWYKQmdOVkhTTUVHREFXZ0JSZENLRkk5czRQdGhTTFRKelczR0k1ZU9Q
      cDdEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwM1kyUTNabVJtT1RjMkxUVmpjbXhvTUlH
      WEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEoxWlNJ
      c0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1poWTNS
      MWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1IxY21W
      eUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJG
      CkFpRUE4MnQxbDdseDhwbEZPNjg1eTVtSGh4Vjkxd2hORFhaTkZpbVdhN2h3QlY0Q0lCT0ZLYVNw
      aWxhb1ZQQVQKR3J3UVBVdGIzeXFMaWtCOGdSU1BESCt1TG1JWgotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKhgYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJ
      Q0RUQ0NBYktnQXdJQkFnSVVaM25tWkhiekZTekx2WEsyVE43ZWlMQ0VaVFV3Q2dZSUtvWkl6ajBF
      QXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVF
      Qnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1N
      RTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056RTBNRFV3TURJeldoY05NalV3
      TlRBek1EVXdNREl6V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05v
      TVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVj
      TUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VH
      Q0NxR1NNNDlBd0VIQTBJQUJOYUxtOFU2SjZlMHZtajkrd0pYTG5xSHlBWmY2MzBPdnVtUgpuZmZE
      eVhrVnUxdEFSNUhjV1VCa1k4eUZVSUJUc0U5QXNqS1JDRWZQZXI4N0Z4NytNb3FqUWpCQU1BOEdB
      MVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUmRD
      S0ZJOXM0UHRoU0wKVEp6VzNHSTVlT1BwN0RBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQStmd3lw
      ZitDdnUyR3JNNWdJa2xRcVB1MgpxNlNORER5dFR4NEd3cDFhMkc4Q0lRRHlFMFhock9QSWpJUCth
      ZmoxV09qUWR1eHRSZFg2OFp0ajJrWGZ4Z0dzCm5nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVy
      TVNQGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVy
      TVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zErIWCgpjYXJyaWVyTVNQEqMWGr8UCgNNU1AStxQS
      rBQSqRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NB
      WjZnQXdJQkFnSVVTVC9Rc21ScjdCTXIvZFVsV3g2YWIzSUdHSE13Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFX
      VnlMVzVsZERBZUZ3MHkKTWpBM01UUXdOVEF5TWpoYUZ3MHlOVEExTURNd05UQXlNamhhTUZveEN6
      QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJt
      UnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNp
      MXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRUi85SERVQlM0MnBTZVE0
      WS94TFBUeTdhTjlySnZuWmhva25Jdko2c2pZbTBURHJnRXRTU2ZOTzhTdW02bQordUdyUTdDN1dx
      UnQrdzd0MURuMmp3TDZvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93
      UUVBd0lCcGpBZEJnTlZIUTRFRmdRVTkrdEVQYkwycUpKL1NWdnZTZjNodlZLQ1JZSXdDZ1lJS29a
      SXpqMEUKQXdJRFNBQXdSUUloQU9vOUhLWktpU09PaW83VFN3bXEzNWNyRkxBZjdJbFFLbmZxZ0ZX
      MzNNMzdBaUFzSm5kYgpZMUJoVW9Db1NxNmpBcUdtUWpiMEpDQnlPbElNajVUT1FrbUtRZz09Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrIILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUM3VENDQXBTZ0F3SUJBZ0lVQ1VOWGswSzkxZGNBalZ6dDVtTzd5cWg5NFVJd0NnWUlLb1pJemow
      RUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1
      allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNVFF3TlRFd01EQmFGdzB5TXpBM01UUXdOVEUxTURC
      YU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1
      a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFV
      RUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJxZloyaTlBZklXMDZPbnZmb3dQdUUKRmp3
      RUl6Zm1GejJCdTNMS2tWR0x6Uzc5RExvZEE1dmhrNmh0WmlCbEdnK3crL1ZnQ2M0R2t3V241MkxM
      SlpWbgpvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3
      SFFZRFZSME9CQllFCkZLV093emh2cTUvdUkyRWlZdzdxbnlNZHQvT0dNQjhHQTFVZEl3UVlNQmFB
      RlBmclJEMnk5cWlTZjBsYjcwbjkKNGIxU2drV0NNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6
      TFRaa05HTTJaamMyWkdZdGNXUm5ZMmN3Z1kwRwpDQ29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2
      ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1pt
      YVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFHWXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0
      YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJ
      emowRUF3SURSd0F3UkFJZ0F1ZlNsd3YvemRUMnl0WGpmdmcyaENMRUNlL0Z0cTF1enhPUEZFNW4r
      eVVDCklGdDU2M1dqYWVwdHdPenVKWk9QZGdFTFdkZDErWE5MOGdYWm5PVFQrTE5lCi0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVNUL1FzbVJyN0JNci9kVWxXeDZhYjNJR0dITXdD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURW
      UVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakEzTVRRd05UQXlNamhhRncweU5UQTFN
      RE13TlRBeU1qaGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhE
      ekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVB
      d3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpB
      QVFSLzlIRFVCUzQycFNlUTRZL3hMUFR5N2FOOXJKdm5aaG9rbkl2SjZzalltMFREcmdFdFNTZk5P
      OFN1bTZtCit1R3JRN0M3V3FSdCt3N3QxRG4yandMNm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFR
      SC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVOSt0RVBiTDJxSkovU1Z2dlNm
      M2h2VktDUllJd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBT285SEtaS2lTT09pbzdUU3dtcTM1
      Y3JGTEFmN0lsUUtuZnFnRlczM00zN0FpQXNKbmRiClkxQmhVb0NvU3E2akFxR21RamIwSkNCeU9s
      SU1qNVRPUWttS1FnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIzCgdSZWFk
      ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMS
      KBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgB
      EhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIe
      CAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVs
      Q3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoX
      L0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRo
      bRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP//
      //8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWlu
      LW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoK
      BlYxXzRfMxIAGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoH
      V3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlu
      cxACGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
