apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIFE8ttBBEsbzTTbUy2n0E2ms+MMHfMKKUDYqSPZ3EQ/mEppeCpdeCpReCngKWggBEAEaBgiB
      9MiXBiIKc3lzY2hhbm5lbCpAZDZkNmZiMGM1OGIyYWQ5MzkyZjE1NTViZGM2Y2FhNjA1ODA0Mjgw
      OGNkNmNhNWI0ZDE1YmQ4YmEzYzcwMmNkZBIaEhjLjqdceCgc1Lk2bDwrXYk0mZaGIporLfISl10K
      lF0SkV0SiysKB09yZGVyZXIS/yoSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVQzA0U3J1Z2dPZHpGQjg1QTNnQ2NTcUwyTnJ3d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RBNU1UQXlOVEV4V2hjTk1qVXdOVEk1TVRBeU5URXhX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJNOS9v
      MlhKU0dVOGh6OWtlVW95RlZJVktPdUZtWlB0Z1pPR0d0bkQ4ekxwNmx5dGw1ZWEKZFUvMWVyRzJn
      R08ydncrajYrRkVDSE9tTis2MFIrc2VyMjJqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUVBWQ0d1bWY0NWdGVVlwT2pWK05jVGtz
      eGlsVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXpIdzRPWk5YVWpHK2J5NGtzKzJQbm9HNnNC
      U1Q0dmdMSURlNHVVSU0KNEpJQ0lIQzhxL1VaTFFKZWU1UjVWUDkyM1JDSGUzL2NWU3NZd0hNUmsr
      NDdLUFFzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVTGVGbVYyWTRnUGdJTXBBWityYnFCUjZDZUZRd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RBNU1UQXpNekF3V2hjTk1q
      TXdPREE1TVRBek9EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFemtSOG5uYWFnVU00QVZTYmpKTHlBUzRsVjA2
      SGNsUkkKWVlNazd2ZVAxZFVIWm9VSUdSQlRucjlRcnJ6RE82V2o1d1l0Um5tZlNYYVhGczJzcDht
      bzlLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSa2xpWlFLU1ZuCktUQmtpSCtiSlNNcUREMzNrakFmQmdOVkhTTUVHREFXZ0JR
      UFZDR3VtZjQ1Z0ZVWXBPalYrTmNUa3N4aWxUQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xUUjNPVFk1TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnZTIxNVhVNXBkT3ZKTDl0UzZveWNhUklrRzgrN1pwaVVJdzRhWFRKai9Hc0NJRVBu
      Um43dXFoVS95cXljCmhuVW5WUnl4eXlkelRJUDhsN01FdktvekM4SUgKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVQzA0U3J1Z2dPZHpGQjg1QTNnQ2NTcUwyTnJ3d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RBNU1UQXlOVEV4V2hjTk1qVXdOVEk1
      TVRBeU5URXhXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJNOS9vMlhKU0dVOGh6OWtlVW95RlZJVktPdUZtWlB0Z1pPR0d0bkQ4ekxwNmx5dGw1ZWEK
      ZFUvMWVyRzJnR08ydncrajYrRkVDSE9tTis2MFIrc2VyMjJqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUVBWQ0d1bWY0NWdGVVlw
      T2pWK05jVGtzeGlsVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXpIdzRPWk5YVWpHK2J5NGtz
      KzJQbm9HNnNCU1Q0dmdMSURlNHVVSU0KNEpJQ0lIQzhxL1VaTFFKZWU1UjVWUDkyM1JDSGUzL2NW
      U3NZd0hNUmsrNDdLUFFzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGoISCg1Db25zZW5zdXNUeXBlEvAREuUR
      CghldGNkcmFmdBLYEQrBEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3Gs8ILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVR3RzMGt3RGNtODRFVDJ6NXNL
      c1NtdFlDQStvd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3T0RBNU1U
      QXpNekF3V2hjTk1qTXdPREE1TVRBek9EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUnJvODdTOGJX
      ZndrM0ZHbjJzZzM4aE9mNUwKVFFpeTNYaFNlRisyaHFRMm9LTFpVSHRVeTJ5NndVMUdmaWQ2Z1B3
      U05SV21jTndEc3VTcG5SNlhMWjJVbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUU9KUnhSbnB0d2s2OXFjYU5pb3hJOGpod0MKRWpBZkJnTlZIU01FR0RB
      V2dCUVBWQ0d1bWY0NWdGVVlwT2pWK05jVGtzeGlsVEEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1
      ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1
      SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmho
      YVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBd1JBSWdNU0ZPMUxHd0FabkFBZ1EvCklPVjlWOUMrWFRobDhoSmJ5WGp4bzFqUEdCVUNJRFVr
      Y3JMS1RWZkg1VFBFVFUxNjUvY2FkNHRHb05WOGpNMUcKRGdINi9IY2IKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQoizwgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREFqQ0NBcW1nQXdJ
      QkFnSVVHdHMwa3dEY204NEVUMno1c0tzU210WUNBK293Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0Zw
      YmkxdVpYUXcKSGhjTk1qSXdPREE1TVRBek16QXdXaGNOTWpNd09EQTVNVEF6T0RBd1dqQnhNUXN3
      Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3
      RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFE
      RXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DQUFScm84N1M4Yldmd2szRkduMnNnMzhoT2Y1TApUUWl5M1hoU2VGKzJocVEy
      b0tMWlVIdFV5Mnk2d1UxR2ZpZDZnUHdTTlJXbWNOd0RzdVNwblI2WExaMlVvNElCCk1EQ0NBU3d3
      RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYK
      QlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRT0pSeFJucHR3azY5cWNhTmlv
      eEk4amh3QwpFakFmQmdOVkhTTUVHREFXZ0JRUFZDR3VtZjQ1Z0ZVWXBPalYrTmNUa3N4aWxUQS9C
      Z05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnla
      WEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJ
      anA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2li
      M0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnla
      WElpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ01TRk8xTEd3QVpuQUFnUS8KSU9WOVY5QytY
      VGhsOGhKYnlYanhvMWpQR0JVQ0lEVWtjckxLVFZmSDVUUEVUVTE2NS9jYWQ0dEdvTlY4ak0xRwpE
      Z0g2L0hjYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZB
      ZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0
      aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMa
      BkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zEr0vCgtD
      b25zb3J0aXVtcxKtLxLiLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsguErEXCg9tYW51ZmFjdHVy
      ZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVS0IxU0x5MytSNWFWVzd6RDBoV2My
      UHJUNkhVd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdP
      REE1TVRBeU56RXpXaGNOTWpVd05USTVNVEF5TnpFeldqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBN
      QTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpE
      RTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGRE
      QlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQldNandVRTJKVzZ6aWY2TGpHUWlp
      K3QyRnVGb1pmV3VleSsKSmwxYllsUURKakFVR0ljQjBKRFJYUUpIZzh6MFlUaS9sVVpKU3hIYUMz
      ZzdRTThxYk1lalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFn
      R21NQjBHQTFVZERnUVdCQlN2U1lUZ2kwVlErWDJsCnVjVUFzaWd3RUR0eDlUQUtCZ2dxaGtqT1BR
      UURBZ05JQURCRkFpRUFoY3Q2SGNYaXladVZvSHEzQWZ1cHMxVCsKNkFwUjBIeUFoNUlXOXJuTU1o
      RUNJSGZUM3BBbkZFN1hodHRMRFUraWxrYTJneU1RYjNXazdyTjBHL2Y3NWVyMAotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERVRDQ0Fy
      ZWdBd0lCQWdJVVhmOTNwYWVQQ2l2YndBejJSQzdodWFHVHIxWXdDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3T0RBNU1UQXpOREF3V2hjTk1qTXdPREE1TVRB
      ek9UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRMemd1TlRR
      dlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZCQXNUQldG
      a2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJaRzFwYmtC
      dFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdB
      RTgrNXF1STdrTDN1YktVVG1HTy95YUkyeWVrRStZMU1hSkZVL3M4d0VxdERoZWZCSWdnbHoKRUFF
      Ym9WUmh2aDA1eld4bnlFN2hhS1dlcXpSbUtkaXlKcU9DQVNJd2dnRWVNQTRHQTFVZER3RUIvd1FF
      QXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUnE0UWhXR2FWQ3NvQnlsZVN1
      L2JMeFlHaklRREFmCkJnTlZIU01FR0RBV2dCU3ZTWVRnaTBWUStYMmx1Y1VBc2lnd0VEdHg5VEFr
      QmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDNZMlEzWm1SbU9UYzJMWEJxYW01bk1JR1hCZ2dx
      QXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZr
      YldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkzUjFjbVZ5
      SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNtVnlMVzVs
      ZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRgpBaUVB
      eTAwZDRnSDRKN1BmREZxWnNnYjNUdEhYak9Qd08zL1RYVEtHaTlGZ2dBZ0NJRUp6TC9XeUV3SnZ3
      YWFCCmprclVZS1lBa1daN0oyMDREamZJemF6cXAyTEgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEREND
      QWJLZ0F3SUJBZ0lVS0IxU0x5MytSNWFWVzd6RDBoV2MyUHJUNkhVd0NnWUlLb1pJemowRUF3SXcK
      WkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dX
      blZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhM
      bTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdPREE1TVRBeU56RXpXaGNOTWpVd05USTVN
      VEF5TnpFeldqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdE
      UVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dB
      MVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdT
      TTQ5QXdFSEEwSUFCQldNandVRTJKVzZ6aWY2TGpHUWlpK3QyRnVGb1pmV3VleSsKSmwxYllsUURK
      akFVR0ljQjBKRFJYUUpIZzh6MFlUaS9sVVpKU3hIYUMzZzdRTThxYk1lalFqQkFNQThHQTFVZApF
      d0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlN2U1lUZ2kw
      VlErWDJsCnVjVUFzaWd3RUR0eDlUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFoY3Q2SGNYaXla
      dVZvSHEzQWZ1cHMxVCsKNkFwUjBIeUFoNUlXOXJuTU1oRUNJSGZUM3BBbkZFN1hodHRMRFUraWxr
      YTJneU1RYjNXazdyTjBHL2Y3NWVyMAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5z
      IjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlu
      cyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1p
      bnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQEAEaBkFk
      bWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJlck1T
      UBoGQWRtaW5zKgZBZG1pbnMSthYKCmNhcnJpZXJNU1ASpxYawxQKA01TUBK7FBKwFBKtFAoKY2Fy
      cmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJ
      VVRDcVl3c1grWGtsWHQ1Mjh6d1RhdlhTaFRCWXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFl
      RncweQpNakE0TURreE1ESTVNVFZhRncweU5UQTFNamt4TURJNU1UVmFNRm94Q3pBSkJnTlZCQVlU
      QWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRH
      QTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVN3UWxra2txM1ZOOG9aSlRiNXFoeE9QWGQr
      THhPSzJXN1pJVDE2MDBqREJuT0pwNVkvUXNzMTVtNktHTm1DCi9laGxNT0xZd1d2cXlqbDN0cUdO
      YmlOZG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFk
      QmdOVkhRNEVGZ1FVUncvd2EwcFVHQjB1Q1pwNEhlOXd2RGFkSjQwd0NnWUlLb1pJemowRQpBd0lE
      U0FBd1JRSWhBS2tkaCt2d3pybkhKbDVKcFoyMDlDNURSUVcyKzZJVmJ6S1RuajVBbUNmNUFpQmpr
      VGp2CmR5cTJJa0RmZFhBZEFvL0cyd2RtbzRPRVhBdFREQW9KczBGWVNRPT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdqQ0NBcFNn
      QXdJQkFnSVVYdW1NL2xueXNvWlc2dmdkV1VsemVlNytEell3Q2dZSUtvWkl6ajBFQXdJdwpXakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlM
      VzVsZERBZUZ3MHkKTWpBNE1Ea3hNRE0yTURCYUZ3MHlNekE0TURreE1EUXhNREJhTUhneEN6QUpC
      Z05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9C
      Z05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnlj
      bWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQ0FBUU1OcVVDRzgrL1dBNlEva01HNDJMcAoyeGo5RVh1dFp5ODJw
      bTNMREU5QjVLS3VJVVUzL0lsRWRTeUZyVlZ0OG04QmNoSysybnBTcWhJYVRkOWRXWC83Cm80SUJH
      RENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JC
      WUUKRkxWV2VZVWp0NEF0SWJUMUhTNFFYM2F0ekV2T01COEdBMVVkSXdRWU1CYUFGRWNQOEd0S1ZC
      Z2RMZ21hZUIzdgpjTHcyblNlTk1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFprTkdNMlpq
      YzJaR1l0WW5ZM2VqSXdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1Gakxt
      bHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIy
      NGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNt
      bGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFNB
      QXdSUUloQU5hSTk1RlUwK2ViVjY0cCswTHhwbTU1Z05wQWF5a2xWTXZaZjFKbVhTZzQKQWlBRGJI
      S3RtSk1QekM1TUtlZERGVEV5Nkduc1AwYmNKc0hYR2tBcTlIWGh4Zz09Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVRDcVl3c1grWGtsWHQ1Mjh6d1RhdlhTaFRCWXdDZ1lJS29a
      SXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1
      allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakE0TURreE1ESTVNVFZhRncweU5UQTFNamt4TURJ
      NU1UVmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdO
      VkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJF
      dVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVN3UWxr
      a2txM1ZOOG9aSlRiNXFoeE9QWGQrTHhPSzJXN1pJVDE2MDBqREJuT0pwNVkvUXNzMTVtNktHTm1D
      Ci9laGxNT0xZd1d2cXlqbDN0cUdOYmlOZG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRH
      QTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVUncvd2EwcFVHQjB1Q1pwNEhlOXd2RGFk
      SjQwd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBS2tkaCt2d3pybkhKbDVKcFoyMDlDNURSUVcy
      KzZJVmJ6S1RuajVBbUNmNUFpQmprVGp2CmR5cTJJa0RmZFhBZEFvL0cyd2RtbzRPRVhBdFREQW9K
      czBGWVNRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIzCgdSZWFkZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAES
      GhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIG
      CAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhII
      EgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRp
      b25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggK
      BlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZB
      ZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3
      MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRf
      MxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5     
