apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://34.127.88.184:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: supplychain-net

    genesis: |-
      CiIaIORY6CFu//W2/Dpv6f+HSlbMvXtS27/LaaLTcdcaKsyTEppeCpdeCpReCngKWggBEAEaBgjR
      1KSdBiIKc3lzY2hhbm5lbCpAN2ZlMDFkMmY1YTAwZmQ0ZDFkNDJlZDkxNDkwNzk4NTc5MjQ5NGQy
      ZWNiOTFmZTk4MjQ3MmNlNDc2MzY5MGUwYxIaEhj2KnU0OZU1UFi6s8GhiTLsyck++TlvGaoSl10K
      lF0SkV0SjysKB09yZGVyZXISgysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVYzJPaldqM25xZ0NkQ0RuS0lFbzRCc2M0dEhRd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJMk1EUTBNelEyV2hjTk1qVXhNREUxTURRME16UTJX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJCblNP
      cFU3eEtBN2xydmt6OXlNTUFucStoY2Z2S09aNmd2Z3BTWGhhMTJheU9jcnRhNTQKeVdwY2R5MFF5
      MTJNcWlSR3VhMTAzbG9WSVJUM3B4VHQyK2VqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUkY4ekRRQ2VML2thbVI3WUgzQml6blkv
      VFZVakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQWpRRlNDRTZaMHFHYXlzZ1pGdDdiTXpaeis3
      clJkMmJ2OGhyemJ1bnkKcEFRQ0lIZk0wd25nNC90OUlXNmR3V0dzUTY3NktYMDlSRitPMzU3Mkt1
      OFR0Z2UzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVR3RRRW9oRXhDdjk0S0ZJdTg5SzFjOWl2bmFBd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpJMk1EUTFNREF3V2hjTk1q
      TXhNakkyTURRMU5UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFSDhvOGxteThXVzZ6Q3ZTMDdpRTlXN1Zmc0gr
      M29HYUkKSnJGcXRPUXhXbEJoMlBWQXU3eDBvalRVRkdwdVlLWXk5NVozZklqSmJod3VzMWRmblBJ
      VG9LT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRdldvVW44L1FOCkxtUnpERVBpTDRVSDlvVlRQakFmQmdOVkhTTUVHREFXZ0JS
      Rjh6RFFDZUwva2FtUjdZSDNCaXpuWS9UVlVqQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      Mk5EVTFZems0Tm1RNUxXTmplbnBxTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQU91T0pyVEVwemlmczQ1dlA0bGhsMWFxa1g2VGlrRnhIeFpPcXBjTmxjMkFBaUJS
      UjkycVRoYTJyV1hMCldvRlJDVFgxYnQzTnRCRVlJc0N6eWlpVG1hQWcwQT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVWMyT2pXajNucWdDZENEbktJRW80QnNjNHRIUXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1qSTJNRFEwTXpRMldoY05NalV4
      TURFMU1EUTBNelEyV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCQm5TT3BVN3hLQTdscnZrejl5TU1BbnEraGNmdktPWjZndmdwU1hoYTEyYXlPY3J0
      YTU0CnlXcGNkeTBReTEyTXFpUkd1YTEwM2xvVklSVDNweFR0MitlalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJGOHpEUUNlTC9r
      YW1SN1lIM0Jpem5ZL1RWVWpBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFqUUZTQ0U2WjBxR2F5
      c2daRnQ3Yk16WnorN3JSZDJidjhocnpidW55CnBBUUNJSGZNMHduZzQvdDlJVzZkd1dHc1E2NzZL
      WDA5UkYrTzM1NzJLdThUdGdlMwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRp
      ZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaghIKDUNvbnNlbnN1c1R5cGUS8BES5REKCGV0Y2Ry
      YWZ0EtgRCsERChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijcazwgtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJREFEQ0NBcWVnQXdJQkFnSVVFRi9uaUhVbGhIdmxwZlZia094WnJCWFEz
      dFV3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dH
      UVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXhNakkyTURRMU1EQXdX
      aGNOTWpNeE1qSTJNRFExTlRBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNO
      VEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURW
      UVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJp
      MXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUanl0ZmttRTl4dnJXelJ2
      RWxJQ0pRTnAzaQpOS1QyOVdXUnRJZ3l5elhpZFJFK0E4SkFVMWc4bEpObEc4d2xEanZPcGw2Z3Vy
      RlRqaXlWMHdJTStvZEZvNElCCkxqQ0NBU293RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpR
      UVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0Ex
      VWREZ1FXQkJSMko1UHZIL1o5Yk5EMVlTYXlXSWxZMFZtVAorekFmQmdOVkhTTUVHREFXZ0JSRjh6
      RFFDZUwva2FtUjdZSDNCaXpuWS9UVlVqQTlCZ05WSFJFRU5qQTBnaGh2CmNtUmxjbVZ5TVM1emRY
      QndiSGxqYUdGcGJpMXVaWFNDR0c5eVpHVnlaWEl4TG5OMWNIQnNlV05vWVdsdUxXNWwKZERCc0Jn
      Z3FBd1FGQmdjSUFRUmdleUpoZEhSeWN5STZleUpvWmk1QlptWnBiR2xoZEdsdmJpSTZJaUlzSW1o
      bQpMa1Z1Y205c2JHMWxiblJKUkNJNkltOXlaR1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVsZENJ
      c0ltaG1MbFI1CmNHVWlPaUp2Y21SbGNtVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUNE
      cmUyZzN3NXF2OEJaSmNtb3kKakMzUjFxSnJNdzdVbk1VZHNIVTN1bU9zQWlCdDhFVS9ReXAxN0Uy
      RVZMRjdyR2RnY0MwUEo1UFJXbTY2V1F1Tgp1M2FnbXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiLPCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQURDQ0FxZWdBd0lCQWdJVUVG
      L25pSFVsaEh2bHBmVmJrT3hackJYUTN0VXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      dwpIaGNOTWpJeE1qSTJNRFExTURBd1doY05Nak14TWpJMk1EUTFOVEF3V2pCeE1Rc3dDUVlEVlFR
      R0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkNBQVRqeXRma21FOXh2cld6UnZFbElDSlFOcDNpCk5LVDI5V1dSdElneXl6WGlkUkUrQThK
      QVUxZzhsSk5sRzh3bERqdk9wbDZndXJGVGppeVYwd0lNK29kRm80SUIKTGpDQ0FTb3dEZ1lEVlIw
      UEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpB
      TUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlIySjVQdkgvWjliTkQxWVNheVdJbFkwVm1U
      Cit6QWZCZ05WSFNNRUdEQVdnQlJGOHpEUUNlTC9rYW1SN1lIM0Jpem5ZL1RWVWpBOUJnTlZIUkVF
      TmpBMGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHRzl5WkdWeVpYSXhMbk4x
      Y0hCc2VXTm9ZV2x1TFc1bApkREJzQmdncUF3UUZCZ2NJQVFSZ2V5SmhkSFJ5Y3lJNmV5Sm9aaTVC
      Wm1acGJHbGhkR2x2YmlJNklpSXNJbWhtCkxrVnVjbTlzYkcxbGJuUkpSQ0k2SW05eVpHVnlaWEl4
      TG5OMWNIQnNlV05vWVdsdUxXNWxkQ0lzSW1obUxsUjUKY0dVaU9pSnZjbVJsY21WeUluMTlNQW9H
      Q0NxR1NNNDlCQU1DQTBjQU1FUUNJQ0RyZTJnM3c1cXY4QlpKY21veQpqQzNSMXFKck13N1VuTVVk
      c0hVM3VtT3NBaUJ0OEVVL1F5cDE3RTJFVkxGN3JHZGdjQzBQSjVQUldtNjZXUXVOCnUzYWdtdz09
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAoaBkFkbWlucxoi
      CglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIy
      cxoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxK5
      LwoLQ29uc29ydGl1bXMSqS8S3i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRLELhKxFwoPbWFudWZh
      Y3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1TUBKBBi0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lCQWdJVVByUXNkcFNocWNIY2VIMnJo
      bWVrQTM3T3l4SXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZC
      QWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFa
      bUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05N
      akl4TWpJMk1EUTBORFUxV2hjTk1qVXhNREUxTURRME5EVTFXakJrTVFzd0NRWURWUVFHCkV3SkRT
      REVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJB
      b00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxX
      NWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkVNRzhLUzVOSGtjcUhZRGVh
      cGpyanJsT2VJRWlocWtVckRwCmx4R3paQmVVVW80QmhQRk5zUFpiWm9OZHNuTzRoSzNHeHFPOUZq
      WnlOWnlaVnovN3BodWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JB
      UURBZ0dtTUIwR0ExVWREZ1FXQkJTOGdJMFkzQWtHU1RySwowSmNLenBmTFVxTXYyVEFLQmdncWhr
      ak9QUVFEQWdOSEFEQkVBaUFHZEx0ck1YYWtsU3U3OVcvUVZkWndMM3NGCkNmQk5LMWpDVzBTVWF3
      bXhBd0lnTDlZMkR6YWM5bVQ0L3kwMmVlaXV4SGZYZjlUU2QxQ2tyQnlWNWk0Tm9LZz0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREVU
      Q0NBcmVnQXdJQkFnSVVLMWg4blA5RzRNb2RYbGlUT2Z4U0Z0S3BOeEl3Q2dZSUtvWkl6ajBFQXdJ
      dwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3
      R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJO
      aExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qSTJNRFExTWpBd1doY05Nak14TWpJ
      Mk1EUTFOekF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNMak00THpn
      dU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6QU1CZ05WQkFz
      VEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZRUUREQlpCWkcx
      cGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6ajBEQVFj
      RFFnQUV0UkZaRWl4Z1FsRTY4RERnaG14amFkSDJEMVM1VGl1TjFiWWlOYVBMUmZrc2NBK2FVVXdV
      ClZzNUxXN0tKakZKT0pNSDYvd0RwcXhJS0FLYjRtcXplc0tPQ0FTSXdnZ0VlTUE0R0ExVWREd0VC
      L3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJ2dUYrUmk4Mi9id0dY
      dmhFSG5uSWNCVHVvQnpBZgpCZ05WSFNNRUdEQVdnQlM4Z0kwWTNBa0dTVHJLMEpjS3pwZkxVcU12
      MlRBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAyWWpsbU9HSmpZalprTFhkeFlqbHNNSUdY
      QmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpvaWRISjFaU0lz
      SW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldGdWRXWmhZM1Ix
      Y21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1poClkzUjFjbVZ5
      TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkYK
      QWlFQXdLSWtEWDFST0JYcG5JRjdLdUkwTS96VG5DZGRTT1ZOUEIwL1VTdzlHOE1DSUJndWM2dzhM
      dyttSjJjcwpoajNTaTFZMnNVdTd2U2M0TTd3MkU1OUJyVFFtCi0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      Q3pDQ0FiS2dBd0lCQWdJVVByUXNkcFNocWNIY2VIMnJobWVrQTM3T3l4SXdDZ1lJS29aSXpqMEVB
      d0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1F
      Mk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl4TWpJMk1EUTBORFUxV2hjTk1qVXhN
      REUxTURRME5EVTFXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9N
      UTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNN
      Qm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdD
      Q3FHU000OUF3RUhBMElBQkVNRzhLUzVOSGtjcUhZRGVhcGpyanJsT2VJRWlocWtVckRwCmx4R3pa
      QmVVVW80QmhQRk5zUFpiWm9OZHNuTzRoSzNHeHFPOUZqWnlOWnlaVnovN3BodWpRakJBTUE4R0Ex
      VWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTOGdJ
      MFkzQWtHU1RySwowSmNLenBmTFVxTXYyVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFHZEx0ck1Y
      YWtsU3U3OVcvUVZkWndMM3NGCkNmQk5LMWpDVzBTVWF3bXhBd0lnTDlZMkR6YWM5bVQ0L3kwMmVl
      aXV4SGZYZjlUU2QxQ2tyQnlWNWk0Tm9LZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFk
      bWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJNU1AQARoG
      QWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVy
      TVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJl
      ck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVy
      ZXJNU1AaBkFkbWlucyoGQWRtaW5zErIWCgpjYXJyaWVyTVNQEqMWGr8UCgNNU1AStxQSrBQSqRQK
      CmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJ
      QkFnSVVWbHE4SE80dlVYU2VYYkp4NmcyNmp0RHpSWmN3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVs
      ZERBZUZ3MHkKTWpFeU1qWXdORFEyTURKYUZ3MHlOVEV3TVRVd05EUTJNREphTUZveEN6QUpCZ05W
      QkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVR
      TUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3
      V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUMjlvNzFTRmorL0h2cUNmN1ZDT1l4
      VEhNWlNqMDh0ODladHNyVTVkT09ibWlFQlRUdzVoYXdYZ1pvaGZhMApUbEIyY0E0YVRCczNwR1BP
      OHFVZFpCYlVvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lC
      cGpBZEJnTlZIUTRFRmdRVVNSY3g2azdMTGJRanpRUDV3eUlsMmIwakExb3dDZ1lJS29aSXpqMEUK
      QXdJRFNBQXdSUUloQUswT2F0TXBicnpGSTlyRlBqMFNPTUVnTXA5eS9ubCtISUZ0aEN2SEt3MG5B
      aUJEcmRvLwp4WG56dWJ5OG80dDRIZmVSL2kvS1VLVGdUK3U3bXMyVHFXWHIvQT09Ci0tLS0tRU5E
      IENFUlRJRklDQVRFLS0tLS0KIrIILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3REND
      QXBPZ0F3SUJBZ0lVUVUyUjBubHp3NlRDWWZRbm9pcDBETlgrZld3d0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck1qRXlNall3TkRVME1EQmFGdzB5TXpFeU1qWXdORFU1TURCYU1IZ3hD
      ekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhF
      REFPQmdOVkJBb1RCME5oY25KcFpYSXhIakFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFVRUN4TUhZ
      MkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JRV1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RBVEJnY3Fo
      a2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVROODl3WnFtYmxaUVVNb3o2Q25vengKNmxwQmZ0R0Zs
      MmJHejUwV1RtZHZudlFqU1Yyb1ZMS0Y3ZUY3UDluZFVxSzk0WmQ0WGswbU5HT1ZSL3pGdDE5Ywpv
      NElCRnpDQ0FSTXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZS
      ME9CQllFCkZNaDkydHU4cE5QQ0tyank5Nk1iRlNRTU9QVzBNQjhHQTFVZEl3UVlNQmFBRkVrWE1l
      cE95eTIwSTgwRCtjTWkKSmRtOUl3TmFNQ01HQTFVZEVRUWNNQnFDR0dOaExYUnZiMnh6TFRnMFpE
      aGpOV000TkMxMmNtbzNjakNCalFZSQpLZ01FQlFZSENBRUVnWUI3SW1GMGRISnpJanA3SW1GaVlX
      TXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2CkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRH
      bHZiaUk2SW1OaGNuSnBaWElpTENKb1ppNUZibkp2Ykd4dFpXNTAKU1VRaU9pSkJaRzFwYmtCallY
      SnlhV1Z5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncQpoa2pPUFFRREFn
      TkhBREJFQWlCQmJJMjF5UFZ5MUtUTzJJRWwwWXRMVmZpbDI3L0laM3NvRWJTc3ZGU0ZqZ0lnCkRJ
      VnF6NC94VWxkVzN4Y0FLZCtwL01Kdjl1VFBzRUliMXk0OFhNRHlZL1U9Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVZscThITzR2VVhTZVhiSng2ZzI2anREelJaY3dDZ1lJS29a
      SXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1
      allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV5TWpZd05EUTJNREphRncweU5URXdNVFV3TkRR
      Mk1ESmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdO
      VkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJF
      dVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVQyOW83
      MVNGaisvSHZxQ2Y3VkNPWXhUSE1aU2owOHQ4OVp0c3JVNWRPT2JtaUVCVFR3NWhhd1hnWm9oZmEw
      ClRsQjJjQTRhVEJzM3BHUE84cVVkWkJiVW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRH
      QTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVU1JjeDZrN0xMYlFqelFQNXd5SWwyYjBq
      QTFvd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBSzBPYXRNcGJyekZJOXJGUGowU09NRWdNcDl5
      L25sK0hJRnRoQ3ZIS3cwbkFpQkRyZG8vCnhYbnp1Ynk4bzR0NEhmZVIvaS9LVUtUZ1QrdTdtczJU
      cVdYci9BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI0CgZBZG1pbnMSKhIg
      CAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIo
      Eh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhII
      EgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRp
      b25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVy
      L0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggK
      BlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZB
      ZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBseWNoYWluLW5ldDo3
      MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRf
      MxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
