apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: https://github.com/Mohitv/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://192.168.49.1:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIF0GbckhIpx4hrnfp/T/Tpz6lvciqW9omgiEMXexDuNMEqJeCp9eCpxeCngKWggBEAEaBgil
      msOWBiIKc3lzY2hhbm5lbCpAYTBhODYwY2QyNGFlZmNlNGEzN2E3OWEzMDliMDkzNzE5NzY5MjY1
      MzI1M2EyZGQzNDg3N2I2ZDZiNDcyNGMzZhIaEhhzCFjWmwwFyU0aTlA40wLaM6vtoFw/yh4Sn10K
      nF0SmV0SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVRVhPWWFWejBQci9Qb0FLbGN6YUtKL3l2c05nd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFMU1ERTFOakF4V2hjTk1qVXdOVEEwTURFMU5qQXhX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJKdDd5
      YkdseWxvdFNSQ1BHbElTcGU4bVRHSjlsQTNldzloSDNCL2o3Q1lzenRWOXYrSFcKOWNJSTJqRTQw
      dVlJYVA3bDYyQmNNc3VaUnVPY080UVpiYlNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVHBGVnd5QkkrVTVvZUNPVlFzamlsY0lj
      RjFMekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCeitmRXBrcCtXS2t0OHdVMzNNYjIwd01HdWFk
      SlBaY1IzeGl1eXVoZEwKRkFJaEFJMllsNldEdEFBanVucFpvSlpmRGl5eHFiRiszVXNVZ1NKYVF3
      RjBjVmNGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVUTMvNHcyTElmaU1rMFRuSm0rOC9nUWo4aUhzd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFMU1ESXdOREF3V2hjTk1q
      TXdOekUxTURJd09UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFTXRONG8zcjNWTnB1N0xHb2VMc3dNdnAwcFQ5
      K3ZXdjIKSzd4cVp0SGdUc0luVFlyMklleXJCQ3o3MHM4SVZLOVhuMUVXZk5BNE5XZWZETCtJNTdS
      RGJhT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUYTF1SnF6NXlJCjd1Z2d1THdWYnRQZkExZWZMREFmQmdOVkhTTUVHREFXZ0JU
      cEZWd3lCSStVNW9lQ09WUXNqaWxjSWNGMUx6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MU5qWTNZelkzWm1ZM0xYQTVPWFExTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQVBvV3VXanF5dXBGOVMvYnY2WHBYRDUySFRwVGNGZ1pFdVY3LzlmaU9vcjJBaUFn
      NHhSNUlDZitqMXdwCjBsQU53UmV4VEsvUC8wNUswNDIvV2ZzQTVjODZ6Zz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVUVYT1lhVnowUHIvUG9BS2xjemFLSi95dnNOZ3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RTFNREUxTmpBeFdoY05NalV3
      TlRBME1ERTFOakF4V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCSnQ3eWJHbHlsb3RTUkNQR2xJU3BlOG1UR0o5bEEzZXc5aEgzQi9qN0NZc3p0Vjl2
      K0hXCjljSUkyakU0MHVZSWFQN2w2MkJjTXN1WlJ1T2NPNFFaYmJTalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRwRlZ3eUJJK1U1
      b2VDT1ZRc2ppbGNJY0YxTHpBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQnorZkVwa3ArV0trdDh3
      VTMzTWIyMHdNR3VhZEpQWmNSM3hpdXl1aGRMCkZBSWhBSTJZbDZXRHRBQWp1bnBab0paZkRpeXhx
      YkYrM1VzVWdTSmFRd0YwY1ZjRgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaihIKDUNv
      bnNlbnN1c1R5cGUS+BES7REKCGV0Y2RyYWZ0EuARCskRChhvcmRlcmVyMS5zdXBwbHljaGFpbi1u
      ZXQQijca0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVV
      ZXIwVWQwdVlZenpsVUpHRjNGN05keXlrNDB3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVC
      aE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdE
      Z1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpY
      UXcKSGhjTk1qSXdOekUxTURJd05EQXdXaGNOTWpNd056RTFNREl3T1RBd1dqQnhNUXN3Q1FZRFZR
      UUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZR
      UUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNt
      UmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BR
      TUJCd05DQUFRNi9Dc0Yrb1NKK2U0b1BuZGJFeDRWYW1pZwp1Z2dIb1JzaVRObzVSMlpqak9ncGFN
      MHlpS3hLMnlHZmRCdzdCRWRZdzJYTHU3VXlsaVNMZ2hwREpLc1ZvNElCCk1EQ0NBU3d3RGdZRFZS
      MFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFq
      QU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUSDZrZHRmVDdTT29YZ2NOUjVqVlM0b1Vn
      eQpZREFmQmdOVkhTTUVHREFXZ0JUcEZWd3lCSStVNW9lQ09WUXNqaWxjSWNGMUx6QS9CZ05WSFJF
      RU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1S
      bGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1o
      bUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhK
      bGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgw
      d0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFKT0xoS0VVTkYwZktyZzYKY1pLTDF6Z3Y4M0RrMTRD
      YVR6YUhETWJFTlVxWUFpQWRZZkZrWHlaUFJhWUFtaDhFSzRxRHZGdXkrZmlxQUxUSgpYVVFHTEl5
      WnVRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi0wgtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVVZXIwVWQwdVlZenpsVUpHRjNGN05keXlrNDB3Q2dZ
      SUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFR
      RERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekUxTURJd05EQXdXaGNOTWpN
      d056RTFNREl3T1RBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRB
      dkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdk
      dmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRNi9Dc0Yrb1NKK2U0b1BuZGJFeDRW
      YW1pZwp1Z2dIb1JzaVRObzVSMlpqak9ncGFNMHlpS3hLMnlHZmRCdzdCRWRZdzJYTHU3VXlsaVNM
      Z2hwREpLc1ZvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFH
      Q0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FX
      QkJUSDZrZHRmVDdTT29YZ2NOUjVqVlM0b1VneQpZREFmQmdOVkhTTUVHREFXZ0JUcEZWd3lCSStV
      NW9lQ09WUXNqaWxjSWNGMUx6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxq
      YUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29E
      QkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1
      Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lh
      R1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFKT0xo
      S0VVTkYwZktyZzYKY1pLTDF6Z3Y4M0RrMTRDYVR6YUhETWJFTlVxWUFpQWRZZkZrWHlaUFJhWUFt
      aDhFSzRxRHZGdXkrZmlxQUxUSgpYVVFHTEl5WnVRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoSEgoFNTAwbXMQChgBIAUogICAChoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICA
      QBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3Ry
      aWN0aW9ucxIIGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoG
      QWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoG
      QWRtaW5zErkvCgtDb25zb3J0aXVtcxKpLxLeLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsQuErIW
      CgpjYXJyaWVyTVNQEqMWGr8UCgNNU1AStxQSrBQSqRQKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVKNTA4MzFsS3M1dWVuQ0F6ZXN3
      cHQ0cTNpQTR3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01UVXdNakF3TURS
      YUZ3MHlOVEExTURRd01qQXdNRFJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFa
      TWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVY
      Ck1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pP
      UFFNQkJ3TkMKQUFUakpTb1l3ZGd5djJ5SmFpUlh1TTI5SWpxTUdud3IwZk1nTGw0WDAzOFltd24z
      UnUzOTI3UGJpb1VpUzBwegpDcDA4bHlmK0hCUjJ3T0ZDYzc4dXpvV21vMEl3UURBUEJnTlZIUk1C
      QWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVTkySytjY0tQ
      ZnVsSGQxTWYyeGxtUlFKdFlYNHdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUlnYlAwS0pIbllxVldY
      eE5raTA0VWJaa2o5cGpabXNFSzArNEwwaVRSSUwxNENJUUNKUnlIMwpPOEdldDN4b3JQajBlT1hW
      QVlCbE0xMFV1NjlMOFNlS0dKL1RiZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrIILS0t
      LS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3VENDQXBTZ0F3SUJBZ0lVZEhwWmdBNVRmbHc3
      blRZU1N6ZlFqdXhMWmY0d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFO
      QmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRE
      WVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNVFV3
      TWpBM01EQmFGdzB5TXpBM01UVXdNakV5TURCYU1IZ3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQK
      VlFRSEV4STFNUzQxTUM4dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhI
      akFNQmdOVgpCQXNUQldGa2JXbHVNQTRHQTFVRUN4TUhZMkZ5Y21sbGNqRWFNQmdHQTFVRUF3d1JR
      V1J0YVc1QVkyRnljbWxsCmNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNB
      QVNFZEwyN3M4eEkrUTVxU2tkUjZVT2YKWFUwUk12M3R5eCtPenBtT0xKMmcyTURVcGxBM2U3QXk0
      MWtxVllrdmpaM0gyaGIxUW0vZmpUNDZxa1hVVmJLYgpvNElCR0RDQ0FSUXdEZ1lEVlIwUEFRSC9C
      QVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFCkZNVG43dnBlTmt6NWZsa2Zz
      ZWpTV05FL1N2dzFNQjhHQTFVZEl3UVlNQmFBRlBkaXZuSENqMzdwUjNkVEg5c1oKWmtVQ2JXRitN
      Q1FHQTFVZEVRUWRNQnVDR1dOaExYUnZiMnh6TFRaa05HTTJaamMyWkdZdGR6VjZNbkl3Z1kwRwpD
      Q29EQkFVR0J3Z0JCSUdBZXlKaGRIUnljeUk2ZXlKaFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlX
      UnRhVzRpCk9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lKallYSnlhV1Z5SWl3aWFH
      WXVSVzV5YjJ4c2JXVnUKZEVsRUlqb2lRV1J0YVc1QVkyRnljbWxsY2kxdVpYUWlMQ0pvWmk1VWVY
      QmxJam9pWVdSdGFXNGlmWDB3Q2dZSQpLb1pJemowRUF3SURSd0F3UkFJZ0JVMFRQWjlBUk9XaGlV
      d25hbFZKTFJkOU9kNkd0UnlSNnpiL2pOeVNjRWdDCklIdGJIYTN1eDNQcU5FUG8wMmh2cEdyQ1Ar
      dWd4K1FXZHo3SXcrRzdQQjhjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNI
      QTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVUo1
      MDgzMWxLczV1ZW5DQXplc3dwdDRxM2lBNHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncw
      eQpNakEzTVRVd01qQXdNRFJhRncweU5UQTFNRFF3TWpBd01EUmFNRm94Q3pBSkJnTlZCQVlUQWtk
      Q01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFV
      RUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdj
      cWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVRqSlNvWXdkZ3l2MnlKYWlSWHVNMjlJanFNR253
      cjBmTWdMbDRYMDM4WW13bjNSdTM5MjdQYmlvVWlTMHB6CkNwMDhseWYrSEJSMndPRkNjNzh1em9X
      bW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdO
      VkhRNEVGZ1FVOTJLK2NjS1BmdWxIZDFNZjJ4bG1SUUp0WVg0d0NnWUlLb1pJemowRQpBd0lEU0FB
      d1JRSWdiUDBLSkhuWXFWV1h4TmtpMDRVYlprajlwalptc0VLMCs0TDBpVFJJTDE0Q0lRQ0pSeUgz
      Ck84R2V0M3hvclBqMGVPWFZBWUJsTTEwVXU2OUw4U2VLR0ovVGJnPT0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQoaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fy
      cmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJN
      U1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmll
      ck1TUBoGQWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQ
      GgZBZG1pbnMqBkFkbWlucxKxFwoPbWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUK
      D21hbnVmYWN0dXJlck1TUBKBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0Fi
      S2dBd0lCQWdJVWJGY01rRE9RTFJFY0JGNzlxeHdiWkF4U2tTd3dDZ1lJS29aSXpqMEVBd0l3ClpE
      RUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25W
      eWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0x
      aGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpFMU1ERTFPREF6V2hjTk1qVXdOVEEwTURF
      MU9EQXpXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZ
      RFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFV
      RUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000
      OUF3RUhBMElBQklaQTlyVW9XUzRaaXBacEJMNXB3UTNrT2xxdG56OElnU2ZtCmlVT2FOenp6OXY0
      elBOS1ZzOEZiVlVobFlTcnI5MjFrNFhPdEY3M1d6SUduSVZmaFBDU2pRakJBTUE4R0ExVWQKRXdF
      Qi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJRMFFDdzJrWmJk
      a1JtaApYdUxab3M0aDMxb1IxakFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUEwQVpIcG85TUV6UWIx
      UWROU2NCZWdkUU1KCmVyUEE1TU9UOXBwdkRvR21FUUlnR1UxMHhQT3FJSmNQR1NZbTM4R0Nhc3U1
      eEZCZVIybnVIRmkxY2JmQmdaVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVDZzlYVGEwbkRMZzVldU80
      SmJ5WU1UQm80dGN3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05W
      QkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUx
      Wm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNO
      TWpJd056RTFNREl3TlRBd1doY05Nak13TnpFMU1ESXhNREF3V2pDQmhqRUxNQWtHQTFVRQpCaE1D
      UTBneEdqQVlCZ05WQkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5Z
      VzUxClptRmpkSFZ5WlhJeEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZ
      M1IxY21WeU1SOHcKSFFZRFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dF
      d1lIS29aSXpqMENBUVlJS29aSQp6ajBEQVFjRFFnQUVveDRWcVliV1hOenVnbE52VTJKclp3NGRm
      NnNONnc4YVlFWDhRSXdIOGZuQlcwTXRmcmZwCm9FUGFIL2NuMEhPUWhyRDNGckZFM043TEpFZ2xO
      SitEeUtPQ0FTSXdnZ0VlTUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFN
      QjBHQTFVZERnUVdCQlNTcWdMNTBVcGdDbGdHNFRCaHpjQm4wYWk2ZlRBZgpCZ05WSFNNRUdEQVdn
      QlEwUUN3MmtaYmRrUm1oWHVMWm9zNGgzMW9SMWpBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNj
      eTAzWTJRM1ptUm1PVGMyTFdoM2RuSnJNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9u
      c2kKWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVpt
      bHNhV0YwYVc5dQpJam9pYldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlq
      b2lRV1J0YVc1QWJXRnVkV1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJp
      SjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlCZ0N5ZUlTMXJSYTN6ajdXd0poenhpOHl2c1d3
      ZTFKVVh5WWxMTG00U2JQQUlnWW5xTEVkNEFkNnBkYWk3awoyUm1KK2NYaGlzKzRRWmhOcXF4VDhD
      Ylg2RTA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ3pDQ0FiS2dBd0lCQWdJVWJGY01rRE9RTFJFY0JG
      NzlxeHdiWkF4U2tTd3dDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJn
      TlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllX
      NTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0ho
      Y05Nakl3TnpFMU1ERTFPREF6V2hjTk1qVXdOVEEwTURFMU9EQXpXakJrTVFzd0NRWURWUVFHCkV3
      SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdO
      VkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21W
      eUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQklaQTlyVW9XUzRaaXBa
      cEJMNXB3UTNrT2xxdG56OElnU2ZtCmlVT2FOenp6OXY0elBOS1ZzOEZiVlVobFlTcnI5MjFrNFhP
      dEY3M1d6SUduSVZmaFBDU2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFI
      L0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJRMFFDdzJrWmJka1JtaApYdUxab3M0aDMxb1IxakFLQmdn
      cWhrak9QUVFEQWdOSEFEQkVBaUEwQVpIcG85TUV6UWIxUWROU2NCZWdkUU1KCmVyUEE1TU9UOXBw
      dkRvR21FUUlnR1UxMHhQT3FJSmNQR1NZbTM4R0Nhc3U1eEZCZVIybnVIRmkxY2JmQmdaVT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAES
      AggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggB
      EgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggB
      EgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAES
      HxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5u
      ZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxotChlCbG9ja0RhdGFIYXNo
      aW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1v
      cmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoM
      Q2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0S
      EhIICgZTSEEyNTYaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
