apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: solo

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.66.8.13:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIHVRYBdWcU+WHSWPEGa8t2WR7qRRrckKEv8dxqusbwrvErhMCrVMCrJMCngKWggBEAEaBgjW
      3tWcBiIKc3lzY2hhbm5lbCpAZWUzZTU4YjFmZTU4NDg0NjA1YWNlNmUwNDM2OTczYTRjODMzNjlh
      Y2I4YzRmZTc3MmRlNTYyMDk5MmIzZjhlZRIaEhhFOkon3Y1OP8waUcOeMMaH1pWktAcPYC0StUsK
      sksSr0sSvS8KC0NvbnNvcnRpdW1zEq0vEuIuChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SyC4SsRcK
      D21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVIbFZFTkpTeWdk
      OGlRV2p6YS9zZk9xZnlhaFF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6
      QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RB
      eE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpY
      UXdIaGNOTWpJeE1qRXhNRFEwTnpJNFdoY05NalV3T1RNd01EUTBOekk0V2pCa01Rc3dDUVlEVlFR
      RwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRB
      VEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNS
      MWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOMlpRRFEvd2o2
      UWxSNVZTelFQcG54VVJ3MS9FNkhERGpkVQp3Rm9MOWhYVkVzS0NwMHVGR2JlQVpjNjgxVWhKcGVW
      VmNmQUNwVUNYQWpSMEFkMFdzdldqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIw
      UEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFNUVXJ4d2NZa1ovbmwKRVcxem96eTBPOXhuSERB
      S0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTRZbWFEWEI4TDRuQnFVeWhuNjhHZjhScApDZFBZT0c5
      VGdHUXRBYnpCMGljQ0lFTDY2KytMdG9wc25Rd2N1a0htSkgvSDZBOG9xUTJNWnU1Q0QvbHBsSUNE
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSURFRENDQXJlZ0F3SUJBZ0lVTnArUm9NM1I0ZzMwelNucUNEbml1enpQQ1Rvd0NnWUlLb1pJ
      emowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBH
      QTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05W
      QkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakV4TURRMU16QXdXaGNO
      TWpNeE1qRXhNRFExT0RBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEz
      TGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFN
      QmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFE
      REJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkK
      emowREFRY0RRZ0FFaitTK0JYZlMxR2JzUnpsTytVOHM5QlI0S0hQNDRwSlFtek16a3hpWnhFSEdZ
      MHg1RzVjSwpUM1l5b0VJZmJma3BhLzdiRWJ5YWtmYzc4cWc4Zi9CRmhhT0NBU0l3Z2dFZU1BNEdB
      MVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSbGFTNGRs
      RGZ5T1dleWxrQUlzVS9pYnMvSkpqQWYKQmdOVkhTTUVHREFXZ0JUU1RVcnh3Y1lrWi9ubEVXMXpv
      enkwTzl4bkhEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMU9XUTROelUwTnpnMkxXZG1j
      SEJ3TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lk
      SEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVk
      V1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZ
      M1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TkhBREJFCkFpQmlTMlZkVnRTRGxXM3dxdW5QZzVIZ2YrVlMyRTNEVC8xbkQzenA4aFdzWVFJZ0tS
      TUNuTm5SUzNmWnhxQmQKdDhiS3FETVZVVUhNN1RiU1YvbldaMkxGbFMwPQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVIbFZFTkpTeWdkOGlRV2p6YS9zZk9xZnlhaFF3Q2dZSUtv
      Wkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1B
      MEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJn
      TlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qRXhNRFEwTnpJNFdo
      Y05NalV3T1RNd01EUTBOekk0V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1du
      VnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRY
      SmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NN
      NDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOMlpRRFEvd2o2UWxSNVZTelFQcG54VVJ3MS9FNkhERGpk
      VQp3Rm9MOWhYVkVzS0NwMHVGR2JlQVpjNjgxVWhKcGVWVmNmQUNwVUNYQWpSMEFkMFdzdldqUWpC
      QU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdR
      V0JCVFNUVXJ4d2NZa1ovbmwKRVcxem96eTBPOXhuSERBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlF
      QTRZbWFEWEI4TDRuQnFVeWhuNjhHZjhScApDZFBZT0c5VGdHUXRBYnpCMGljQ0lFTDY2KytMdG9w
      c25Rd2N1a0htSkgvSDZBOG9xUTJNWnU1Q0QvbHBsSUNECi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVy
      TVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVm
      YWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxK2FgoKY2Fycmllck1TUBKnFhrDFAoDTVNQErsU
      ErAUEq0UCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrREND
      QVo2Z0F3SUJBZ0lVRXBqSDgxQ0xMdUlOUlhxSVZqbXJDdHhhS2M4d0NnWUlLb1pJemowRUF3SXcK
      V2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlh
      V1Z5TFc1bGREQWVGdzB5Ck1qRXlNVEV3TkRRNE16TmFGdzB5TlRBNU16QXdORFE0TXpOYU1Gb3hD
      ekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZi
      bVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxj
      aTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU1dsbGJhY25hbmlrOVdm
      dGVESHE3U1BHZ2R3c3BnN2Q1VnFKcnI5UVMxRldQZkNWYkN6UXpyeUdQTWtyem0KT1lrdDBpWnFX
      WVNmK09QODllcTF5OUhkbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgov
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVXVThBdGlEdFRxQ3M1RUx5MTlYQm8yTmxFVHN3Q2dZSUtv
      Wkl6ajBFCkF3SURTQUF3UlFJaEFOZlNOU01ueVBzTXVQN25PRVRONUJjb1VwQTdkb1FubXY1Nm90
      NjNiUk5wQWlCZVg1T00KUnVCbVFKd1RnRmgzclFpb25RWFBRdkN5Qnp1Z2RaMEp0RUZpQUE9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlDN2pDQ0FwU2dBd0lCQWdJVUxwZ2R5QUdXWW9Ea0pkTStoWllNbkdOQXMvNHdDZ1lJS29aSXpq
      MEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allT
      NWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV5TVRFd05EVTBNREJhRncweU16RXlNVEV3TkRVNU1E
      QmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIy
      NWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0Ex
      VUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dU
      QVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUbXhHK2piRlI4SmxEVU5ySm5XY0xnCmpP
      OTdOSHJaUElna0s2VjlzTXowWmt6Q0pqU3E4a280RXFkazB0YjlnWUdDQ0FsSEpVWHVkTlgyYzlQ
      S0IzRGQKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFB
      d0hRWURWUjBPQkJZRQpGSUJVRGIyOUc4aGFhN2RRdlNSZ2RpYW1jMVFZTUI4R0ExVWRJd1FZTUJh
      QUZGbFBBTFlnN1U2Z3JPUkM4dGZWCndhTmpaUkU3TUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4
      ekxUZGpOMlEwTlRRME9EZ3RZM0F5WjJZd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdS
      dGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29a
      SXpqMEVBd0lEU0FBd1JRSWhBTExpZDEyZmZnenNjYkZPVzFnblcwazRXekRFZHlHd0FQUStqRytk
      Q3RKTQpBaUFiNWdkQVk2M20vVk1MdjRqYnBiLzFIdzRsd2dSeUkwVzV3OFpqR2xrTUxnPT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVRXBqSDgxQ0xMdUlOUlhxSVZqbXJDdHhh
      S2M4d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2
      Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3
      RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXlNVEV3TkRRNE16TmFGdzB5
      TlRBNU16QXdORFE0TXpOYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVr
      YjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVH
      QTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJC
      d05DCkFBU1dsbGJhY25hbmlrOVdmdGVESHE3U1BHZ2R3c3BnN2Q1VnFKcnI5UVMxRldQZkNWYkN6
      UXpyeUdQTWtyem0KT1lrdDBpWnFXWVNmK09QODllcTF5OUhkbzBJd1FEQVBCZ05WSFJNQkFmOEVC
      VEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVXVThBdGlEdFRxQ3M1
      RUx5MTlYQm8yTmxFVHN3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFOZlNOU01ueVBzTXVQN25P
      RVRONUJjb1VwQTdkb1FubXY1Nm90NjNiUk5wQWlCZVg1T00KUnVCbVFKd1RnRmgzclFpb25RWFBR
      dkN5Qnp1Z2RaMEp0RUZpQUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjMK
      B1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3Jp
      dGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMS
      KhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVu
      dBIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNo
      YW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFu
      bmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxKpGQoHT3JkZXJlchKd
      GRLKFgoOc3VwcGx5Y2hhaW5NU1AStxYawxQKA01TUBK7FBKwFBKtFAoOc3VwcGx5Y2hhaW5NU1AS
      8QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi96Q0NBYWFnQXdJQkFnSVVOQ3ErRUlr
      bTJLTXNGYkxEMXpFWVZGVjBTL0F3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhj
      Tk1qSXhNakV4TURRME5qSXlXaGNOTWpVd09UTXdNRFEwTmpJeVdqQmVNUXN3Q1FZRFZRUUdFd0pI
      UWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05W
      QkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJa
      TUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkZUMjRmS3lmOEJzUHNjUW1Vc0QvdEZB
      SCtpaUc5RFEvTXp3WFhpUUhRcTB0amowRUZ2WQo1dHVEL2hDc3V2bi9NNmpvWlMvUmkySGVMWWVt
      UnhRTWZRK2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dt
      TUIwR0ExVWREZ1FXQkJTTEhVUFNKQTVmYngwSTlOeUxpeEROOEpMclJEQUsKQmdncWhrak9QUVFE
      QWdOSEFEQkVBaUJlMzNXUitlTHJ4ZTdMWWNLRTZXZyt2NU4raTc4TVo5cUEyWHMyZXoyLwp4d0ln
      VmxldEZpemdkd3FzMTNJQmJJZ1MwTGhzdFIyWmthTEFLQjd4S1dObkpGUT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoioggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzRUQ0NBb2Vn
      QXdJQkFnSVVBZ0k1NFI0d3lNdjFrRE1yZklCbkQ4WjdPT1l3Q2dZSUtvWkl6ajBFQXdJdwpYakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGph
      R0ZwYmkxdVpYUXcKSGhjTk1qSXhNakV4TURRMU1qQXdXaGNOTWpNeE1qRXhNRFExTnpBd1dqQnNN
      UXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVN
      UkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUTR3CkRBWURWUVFMRXdWaFpHMXBiakVlTUJ3R0ExVUVB
      d3dWUVdSdGFXNUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3cKRXdZSEtvWkl6ajBDQVFZSUtvWkl6
      ajBEQVFjRFFnQUU5emU3ZkdwZDlXSHlXT0Z6S1ROc1IxakJ2Wnh3L3M4MwoxNHBQRlJkcUFxV2RG
      RG9ubjMzMnE2dGJhSUZ6VGVFTEZ2ZW93L2FGK0pFcUtNTFlwMXBNRXFPQ0FSTXdnZ0VQCk1BNEdB
      MVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlFBYmc3Zklj
      VEYKRlpLSENzaWFJZ29pckZyRXpUQWZCZ05WSFNNRUdEQVdnQlNMSFVQU0pBNWZieDBJOU55TGl4
      RE44SkxyUkRBagpCZ05WSFJFRUhEQWFnaGhqWVMxMGIyOXNjeTA0WkRjM05EVTJOVGt0ZEc0NWJX
      WXdnWWtHQ0NvREJBVUdCd2dCCkJIMTdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRX
      VWlMQ0poWkcxcGJpSTZJblJ5ZFdVaUxDSm8KWmk1QlptWnBiR2xoZEdsdmJpSTZJaUlzSW1obUxr
      VnVjbTlzYkcxbGJuUkpSQ0k2SWtGa2JXbHVRSE4xY0hCcwplV05vWVdsdUxXNWxkQ0lzSW1obUxs
      UjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklBREJGCkFpRUFxMDBYOEx3cnZu
      dUFJNDlPcFpIRDZNK2V2NU52K3Bia3paSXdwbXB4M1p3Q0lGdEtUNmVrNnBLclBtNXYKenNCVDNh
      c0xwUTMrWWhyUjRUSnlTcyt1amNlQQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEy
      EgZTSEEyNTZK8QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQi96Q0NBYWFnQXdJQkFn
      SVVOQ3ErRUlrbTJLTXNGYkxEMXpFWVZGVjBTL0F3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkx
      dVpYUXcKSGhjTk1qSXhNakV4TURRME5qSXlXaGNOTWpVd09UTXdNRFEwTmpJeVdqQmVNUXN3Q1FZ
      RFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0
      eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFaQmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVds
      dUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkZUMjRmS3lmOEJzUHNj
      UW1Vc0QvdEZBSCtpaUc5RFEvTXp3WFhpUUhRcTB0amowRUZ2WQo1dHVEL2hDc3V2bi9NNmpvWlMv
      UmkySGVMWWVtUnhRTWZRK2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFI
      L0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTTEhVUFNKQTVmYngwSTlOeUxpeEROOEpMclJEQUsKQmdn
      cWhrak9QUVFEQWdOSEFEQkVBaUJlMzNXUitlTHJ4ZTdMWWNLRTZXZyt2NU4raTc4TVo5cUEyWHMy
      ZXoyLwp4d0lnVmxldEZpemdkd3FzMTNJQmJJZ1MwTGhzdFIyWmthTEFLQjd4S1dObkpGUT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAES
      AggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAES
      AggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARIC
      CAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1pbnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhII
      EgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zKgZBZG1pbnMaIgoJQmF0Y2hTaXpl
      EhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxof
      ChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYx
      XzRfMhIAGgZBZG1pbnMaIQoNQ29uc2Vuc3VzVHlwZRIQEgYKBHNvbG8aBkFkbWlucyIiCgdXcml0
      ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIa
      BkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGlu
      Z1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3Jk
      ZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENh
      cGFiaWxpdGllcxIWEgwKCgoGVjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhIS
      CAoGU0hBMjU2GgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
