apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.66.8.13:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaICQ6UCutS+vO3wbaESp64qaVzQMRXa2lbtpmvRK5f6WbEp5eCpteCpheCngKWggBEAEaBgjE
      57ycBiIKc3lzY2hhbm5lbCpAODk1ODM3NjNkNjJlZjdmZDg2ZmE4MWIyNmQ1OWM4ZDZlMmFjYjgz
      ZGYwYTg5ZWQzYTQyM2VkNzEyZjE3ZTczNxIaEhjwmpT7ChSs2SYHVhbTyBhY7p5T5O2UnZ8Sm10K
      mF0SlV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVS0d3d1ljSUhWekFvY21mMU9uVnozT1VyQ3Rzd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBMk1USXdOek0yV2hjTk1qVXdPVEkxTVRJd056TTJX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJNSE1D
      RTdlSlpPZ0ZJVW9CK1BKSGZtaWlqbnlkTTNPMlB5SWxiMFBaVkNUell1c0drbkMKcVI5Y0hSRm0r
      bS9sYTl5VnJtMHcwdEFsR0RsSEdCbXNWVWVqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzVpVmtON3Q2ZTBTZU0yQlNmMkJKNDNo
      OFhUREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBNnhBQ3VORGh3NXVDTW9vRTk3YnBiNVJaMU1V
      Q1UyNGN4b3ZFejVVbmQKckFJaEFQak44VndGd0ZabU9tVUZBdGJFdDhKbDZCa2xXUzVNS3lsMGtY
      UEVMWUViCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0RENDQW9hZ0F3SUJBZ0lVSjJGVDNhUGlENEl2cnJJbFpMWGowZVZMdFAwd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBMk1USXhNekF3V2hjTk1q
      TXhNakEyTVRJeE9EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNGgrYnoyZHM5MUVFd3YycXR1TGZOV1IxSm44
      UU9FcHYKU2p4S04wMmVCRG5EdHRITXVrWFllcnNEOVZDTFRSQ2FmMXhocHhYblBzYmVHdm5CeTBK
      cHpLT0NBUkl3Z2dFTwpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUS3Z4MEUwVkNDCk1DcVQ0blNhb2VjeVdRa042VEFmQmdOVkhTTUVHREFXZ0JT
      NWlWa043dDZlMFNlTTJCU2YyQko0M2g4WFREQWkKQmdOVkhSRUVHekFaZ2hkallTMTBiMjlzY3kw
      MU5UazVOalJqTmkxemJESmlaRENCaVFZSUtnTUVCUVlIQ0FFRQpmWHNpWVhSMGNuTWlPbnNpWVdK
      aFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtCkxrRm1abWxzYVdG
      MGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYzNWd2NHeDUKWTJo
      aGFXNHRibVYwSWl3aWFHWXVWSGx3WlNJNkltRmtiV2x1SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdB
      TUVVQwpJUUNlRTMzUW1ZZFZFN0JOQzF1cVZOWjhmN3ppQzFMaDBhN3FNVHdIcExCeXd3SWdheHJM
      a0N0U1d3RHZMUGJXCjNGKzFvYUlrell3TDNQZHNvYnR6Zk5TRUhpcz0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVS0d3d1ljSUhWekFvY21mMU9uVnozT1VyQ3Rzd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBMk1USXdOek0yV2hjTk1qVXdPVEkx
      TVRJd056TTJXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJNSE1DRTdlSlpPZ0ZJVW9CK1BKSGZtaWlqbnlkTTNPMlB5SWxiMFBaVkNUell1c0drbkMK
      cVI5Y0hSRm0rbS9sYTl5VnJtMHcwdEFsR0RsSEdCbXNWVWVqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzVpVmtON3Q2ZTBTZU0y
      QlNmMkJKNDNoOFhUREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBNnhBQ3VORGh3NXVDTW9vRTk3
      YnBiNVJaMU1VQ1UyNGN4b3ZFejVVbmQKckFJaEFQak44VndGd0ZabU9tVUZBdGJFdDhKbDZCa2xX
      UzVNS3lsMGtYUEVMWUViCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGooSCg1Db25zZW5zdXNUeXBlEvgREu0R
      CghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3GtMILS0tLS1CRUdJ
      TiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQXF1Z0F3SUJBZ0lVY0lYd2ZObE1XUURRWUozTVVi
      bGZXVmRhSmc4d0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJB
      Z01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNt
      VnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBMk1U
      SXhNekF3V2hjTk1qTXhNakEyTVRJeE9EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0Ex
      VUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJB
      dwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3Ykhs
      amFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUUYzN001RFhS
      UzhQa0ordGFXV1UwTHBNVkQKOHFpVTYvZXlEWUZBRmVpUmxPTURLYmJUbTVDTHdhYmFlY0VsWWNt
      ZDF2Rnp6TlFiSldqR3R1OUpYUnk5bzRJQgpNakNDQVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUXpCN0NKZTFBc0JrUUdaZ0lhN0VRdUlBRjgKWERBZkJnTlZIU01FR0RB
      V2dCUzVpVmtON3Q2ZTBTZU0yQlNmMkJKNDNoOFhUREJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXlaR1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZr
      ClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZWFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJw
      YjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxq
      YUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2liM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFE
      QWdOSEFEQkVBaUE2ZGhLTzFVQmFDUk1HCllMYzdJODZzK044UGhsWjF4b1lEVGtIVEFsMXp5QUln
      TzJBYWpEWjg4dXpVTFZZOGZvUU8wK0JxUWRPaENQby8KcDlra20vZlJSVGM9Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQXF1
      Z0F3SUJBZ0lVY0lYd2ZObE1XUURRWUozTVVibGZXVmRhSmc4d0NnWUlLb1pJemowRUF3SXcKWGpF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxq
      YUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBMk1USXhNekF3V2hjTk1qTXhNakEyTVRJeE9EQXdXakJ4
      TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1
      TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lE
      VlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlC
      QmdncWhrak9QUU1CQndOQ0FBUUYzN001RFhSUzhQa0ordGFXV1UwTHBNVkQKOHFpVTYvZXlEWUZB
      RmVpUmxPTURLYmJUbTVDTHdhYmFlY0VsWWNtZDF2Rnp6TlFiSldqR3R1OUpYUnk5bzRJQgpNakND
      QVM0d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JC
      Z0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUXpCN0NKZTFBc0JrUUda
      Z0lhN0VRdUlBRjgKWERBZkJnTlZIU01FR0RBV2dCUzVpVmtON3Q2ZTBTZU0yQlNmMkJKNDNoOFhU
      REJCQmdOVkhSRUVPakE0Z2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0hHOXla
      R1Z5WlhJeExuVndaM0poWkdVdWRYQm5jbUZrClpTNWpiMjB3YkFZSUtnTUVCUVlIQ0FFRVlIc2lZ
      WFIwY25NaU9uc2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWkKTENKb1ppNUZibkp2Ykd4dFpXNTBT
      VVFpT2lKdmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFFpTENKbwpaaTVVZVhCbElqb2li
      M0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUE2ZGhLTzFVQmFDUk1HCllMYzdJ
      ODZzK044UGhsWjF4b1lEVGtIVEFsMXp5QUlnTzJBYWpEWjg4dXpVTFZZOGZvUU8wK0JxUWRPaENQ
      by8KcDlra20vZlJSVGM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAF
      KICAgAoaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1p
      bnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1p
      bnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcKD21h
      bnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0N6Q0NBYktnQXdJQkFnSVVWUXIyczAwVWlsU3BV
      UHBYZm1OOXZtWHNFUEF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpJeE1qQTJNVEl3T0RRMFdoY05NalV3T1RJMU1USXdPRFEwV2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJBWkpCSWJINS84Qm5M
      aEFhdEVHVDEvSk5xV05zeTl3b1RFegp3ZDk3L0FYOTRqVlJrdDFaMEFybjJLclhvaHlNWUVObjZY
      UmVkWFljVXhzbTF4RGFUVU9qUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUkIxTWJEdk9mUWZPV0MKcHY0bEpUbW91ZmlWdnpBS0Jn
      Z3Foa2pPUFFRREFnTkhBREJFQWlCWUNWRW5LTDlhNW9QUDRaaGhEdi81QndiRgo2WFN1WTJwZkZQ
      a1hXcytYRXdJZ0VKcWk0YVUrelVSSUpKWXVBZlAwVHJTWHJGQW9pWDQxdDJMR0VuVzlQT1k9Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURFRENDQXJlZ0F3SUJBZ0lVZTN2YzAxdUVhRTJJNmdJMCtQRlRqaDRRYzkwd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakEyTVRJeE5UQXdXaGNOTWpN
      eE1qQTJNVEl5TURBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpN
      NEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdO
      VkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJa
      QlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemow
      REFRY0RRZ0FFVXpiVjJuaW1oK0VRRE45WGZ4TjZBdVVUM0xiMzYyTFJma2hnODBKWlMzYk5ZWmg5
      YU0zUgo1UFBBdDR4NHY2SlJjUkltV252U00zQmk3R0x5bFhkOVRxT0NBU0l3Z2dFZU1BNEdBMVVk
      RHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRZTRGZ01VbmNZ
      NGFPaFFOWVBZcWNoL2lBd3lqQWYKQmdOVkhTTUVHREFXZ0JSQjFNYkR2T2ZRZk9XQ3B2NGxKVG1v
      dWZpVnZ6QWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMU5qYzVaR1JrT1RRM0xUbHlOM0Zu
      TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEox
      WlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1po
      WTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1Ix
      Y21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhB
      REJFCkFpQUkrRTVlOW15TDNSUzdwaW9Pdy84TU5aWjc1WVhVeG9pM00zVEQvUEU4WUFJZ0Y4UVZD
      ekdBVXdDdlVkaGgKcmdjbmJjblg2RkxiUzlvZHFyTW1jT2JkaXRRPQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQ0N6Q0NBYktnQXdJQkFnSVVWUXIyczAwVWlsU3BVUHBYZm1OOXZtWHNFUEF3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qQTJNVEl3T0RRMFdoY05N
      alV3T1RJMU1USXdPRFEwV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlh
      V05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxj
      akVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJBWkpCSWJINS84Qm5MaEFhdEVHVDEvSk5xV05zeTl3b1RFegp3
      ZDk3L0FYOTRqVlJrdDFaMEFybjJLclhvaHlNWUVObjZYUmVkWFljVXhzbTF4RGFUVU9qUWpCQU1B
      OEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      UkIxTWJEdk9mUWZPV0MKcHY0bEpUbW91ZmlWdnpBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCWUNW
      RW5LTDlhNW9QUDRaaGhEdi81QndiRgo2WFN1WTJwZkZQa1hXcytYRXdJZ0VKcWk0YVUrelVSSUpK
      WXVBZlAwVHJTWHJGQW9pWDQxdDJMR0VuVzlQT1k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQ
      EAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFj
      dHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcUEqwU
      EqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2
      Z0F3SUJBZ0lVSEtRRFR5aEZtbCtZZXpHbXZtUmtWd0ZOTG9Fd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5
      TFc1bGREQWVGdzB5Ck1qRXlNRFl4TWpBNU5URmFGdzB5TlRBNU1qVXhNakE1TlRGYU1Gb3hDekFK
      QmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2
      YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU3pqMWFZcUJZNDZnWngrLy9M
      V2cyQU5xeWRESm5sTFI0VUo2eWs5NEdJakFNY2I5OWJRSmhyVDNpSlJFMk4KUUF5czcxVmVnemd1
      RDZaa3UwTDV3SkRtbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FF
      QXdJQnBqQWRCZ05WSFE0RUZnUVUrMFo1RlNJWERTeGR5RkkyOVFsN1RlUWE4L3d3Q2dZSUtvWkl6
      ajBFCkF3SURTQUF3UlFJaEFQZUNsaklXZkRvNVVpR21oa0RjamJOYmNQT3g3cDRVTGVpbW1BKzht
      QjlKQWlBT2tZTmIKKzErNTZsNmxRZ3ZRRndYdFhseER4SVpETkE4RUFUVWFINlUxeXc9PQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      N1RDQ0FwU2dBd0lCQWdJVUpERjVmSlpRU2c4TFI5NHVOTmFhYnc1dDRBNHdDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNakV5TURZeE1qRTJNREJhRncweU16RXlNRFl4TWpJeE1EQmFN
      SGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWti
      MjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVD
      eE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTZG1naWJpK1Q0YTBEZlBDWklQVWQzCmhSTGlu
      ZXNvdHh4ZHoraENZVUN6S0pjUmt3dWRSdkdNWjRoODNZdVhFWm84dk1kQXVGeVRraE1uT1VPbjJB
      SS8KbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRQpGQnFWKzh1TENGdXJTdVNXaWVaVzgxdFBGclBOTUI4R0ExVWRJd1FZTUJhQUZQ
      dEdlUlVpRncwc1hjaFNOdlVKCmUwM2tHdlA4TUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxU
      WTFOelprTm1abVpEVXRjSEpzY0hBd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5
      SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFX
      eHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFX
      NUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpq
      MEVBd0lEUndBd1JBSWdSYmFPUUQ2b1FDSHhGclZyUFZaRk9xMU90WHFldnZLUFlySTk2aXhSYTk0
      QwpJRFlxWjkvUG5FRFhObVVnRWtJcXk0cDJ2c25UbEI3MG5HZUcwcUFhTkhoRgotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVIS1FEVHloRm1sK1llekdtdm1Sa1Z3Rk5Mb0V3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1EWXhNakE1TlRGYUZ3MHlOVEE1TWpV
      eE1qQTVOVEZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpB
      TkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3
      T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFT
      emoxYVlxQlk0NmdaeCsvL0xXZzJBTnF5ZERKbmxMUjRVSjZ5azk0R0lqQU1jYjk5YlFKaHJUM2lK
      UkUyTgpRQXlzNzFWZWd6Z3VENlprdTBMNXdKRG1vMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgv
      TUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVSswWjVGU0lYRFN4ZHlGSTI5UWw3
      VGVRYTgvd3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQVBlQ2xqSVdmRG81VWlHbWhrRGNqYk5i
      Y1BPeDdwNFVMZWltbUErOG1COUpBaUFPa1lOYgorMSs1Nmw2bFFndlFGd1h0WGx4RHhJWkROQThF
      QVRVYUg2VTF5dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIc
      EggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwK
      CgoGVjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1p
      bnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRl
      cmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
