apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: warehousenew-peer0
  namespace: warehousenew-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: warehousenew-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: warehousenew-net
      images:
        couchdb: hyperledger/fabric-couchdb:0.4.18
        peer: hyperledger/fabric-peer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.warehousenew-net:7051
      gossipexternalendpoint: peer0.warehousenew-net:7051
      localmspid: warehousenewMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:1.4.8
      couchdb:
        username: warehousenew-user

    storage:
      peer:
        storageclassname: warehousenewsc
        storagesize: 512Mi
      couchdb:
        storageclassname: warehousenewsc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://20.63.78.155:8200
      authpath: localwarehousenew-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/warehousenew-net/peers/peer0.warehousenew-net
      secretambassador: secretsv2/data/crypto/peerOrganizations/warehousenew-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/credentials/warehousenew-net/couchdb/warehousenew?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "none"
      external_url_suffix: upgrade.upgrade.com

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
