##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# Remove the build directory
- name: Remove build directory
  file:
    path: "./build"
    state: absent

- name: Create build directory if it does not exist
  file:
    path: "./build/channel-artifacts/"
    state: directory

# Ensure channel-artifacts dir exists
- name: Ensure channel-artifacts dir exists
  file:
    path: "{{ build_path }}/channel-artifacts"
    state: directory

# Create a json file
- name: Creating new json file
  file:
    path: "{{ build_path }}/channel-artifacts/orglevelEndpoints.json"
    state: touch

# Create a capabilities json 
- name: "create orglevelEndpoints json"
  shell: |
    echo -n "{\"OrdererOrgEndpoint\":{\"Endpoints\":{\"mod_policy\":\"Admins\",\"value\":{\"addresses\":[]}}}}" >> {{ build_path }}/channel-artifacts/orglevelEndpoints.json

# Set orderer org for the channel 
- name: Set orderer organization
  set_fact:
    ordererOrg: "{{ org }}"
  loop: "{{ organizations }}"
  loop_control:
    loop_var: org
  when: org.type == 'orderer' and org.name == channel.orderer.name

# create json file
- name: "Modify json for orderer MSP"
  shell: |
    jq '.["{{ ordererOrg.name }}MSPEndpoint"]=.["OrdererOrgEndpoint"] | del (.["OrdererOrgEndpoint"])' {{ build_path }}/channel-artifacts/orglevelEndpoints.json > {{ build_path }}/channel-artifacts/ordererAddresses.json

# update json file for orderer nodes address for the channel
- name: "Add orderer addresses"
  shell: |
    cp {{ build_path }}/channel-artifacts/ordererAddresses.json {{ build_path }}/channel-artifacts/ordererAddressesTemp.json
    jq '."{{ ordererOrg.name }}MSPEndpoint".Endpoints.value.addresses |= 
    "{{ orderer.name }}.{{ ordererOrg.name }}-net:{{ orderer.grpc.port }}"]' {{ build_path }}/channel-artifacts/ordererAddressesTemp.json > {{ build_path }}/channel-artifacts/ordererAddresses.json
  loop: "{{ ordererOrg.services.orderers }}"
  loop_control:
    loop_var: orderer

# update orderer address in syschannel and application channel
- name: Update orderer address in syschannel and application
  include_tasks: nested_main_orderer_addresses.yaml
  vars:
    kubernetes: "{{ org.k8s }}"
    component_ns: "{{ org.name | lower }}-net"
    orderers: "{{ org.services.orderers }}"
  loop: "{{ organizations }}"
  loop_control:
    loop_var: org
  when: org.type == 'orderer' and org.name == channel.orderer.name

