##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# Remove the build directory
- name: Remove build directory
  file:
    path: "{{ build_path }}"
    state: absent

- name: Create build directory if it does not exist
  file:
    path: "./build/channel-artifacts/"
    state: directory

# Ensure channel-artifacts dir exists
- name: Ensure channel-artifacts dir exists
  file:
    path: "{{ build_path }}/channel-artifacts"
    state: directory

# Create json file for orderer addresses
- name: Create json file for orderer addresses
  include_tasks: nested_create_json.yaml

# update orderer address in syschannel and application channel
- name: Update orderer address in syschannel and application
  include_tasks: nested_main_orderer_addresses.yaml
  vars:
    kubernetes: "{{ org.k8s }}"
    component_ns: "{{ org.name | lower }}-net"
    orderers: "{{ org.services.orderers }}"
  loop: "{{ organizations }}"
  loop_control:
    loop_var: org
  when: org.type == 'orderer' and org.name == channel.orderer.name
