##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# This task creates the orderer cli and fetch and modify the config block
############################################################################################
# Check or wait for the Orderer pod
# - name: "Wait for the new orderer pod"
#   include_role:
#     name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
#   vars:
#     component_type: "Pod"
#     namespace: "{{ component_ns }}"
#     kubernetes: "{{ kubernetes }}"
#     label_selectors:
#       - app = {{ channel.orderer.name | lower }}

# This task create script file to add orderer addresses
- name: "Create script file to add orderer addresses"
  template:
    src: "add_orderer_addresses.tpl"
    dest: "{{ build_path }}/add_orderer_addresses.sh"
  vars:    
    channel_name: "syschannel"
    org_name: "{{ ordererOrg.name }}MSP"
    os: "{{ fabric.os }}"
    arch: "{{ fabric.arch }}"
    version: "{{ network.version }}"

# This task add orderer addresses to syschannel
- name: Add orderer addresses to syschannel
  include_tasks: add-orderer_addresses.yaml
  vars:    
    orderer: "{{ orderers | first }}"
    channel_name: "syschannel"

# This task reate script file to add orderer addresses to application channel
- name: "Create script file to add orderer addresses"
  template:
    src: "add_orderer_addresses.tpl"
    dest: "{{ build_path }}/add_orderer_addresses.sh"
  vars:    
    channel_name: "{{ channel.channel_name | lower }}"
    org_name: "{{ ordererOrg.name }}MSP"
    os: "{{ fabric.os }}"
    arch: "{{ fabric.arch }}"
    version: "{{ network.version }}"

# This task add orderer addresses to application
- name: Add orderer addresses to application
  include_tasks: add-orderer_addresses.yaml
  vars:    
    orderer: "{{ orderers | first }}"
    channel_name: "{{ channel.channel_name | lower }}"