# Set orderer org for the channel
- name: Set orderer organization
  set_fact:
    ordererOrgs: "{{ org }}" 

# Construct the orderer addresses list
- name: Construct the orderer addresses list
  set_fact:
    end_points:
    |-
      {% for orderer in ordererOrg.services.orderers %}
        "{{ orderer.name }}.{{ ordererOrg.name }}-net:{{ orderer.grpc.port }}",      
      {% endfor %}
  loop: "{{ ordererOrg.services.orderers }}"
  loop_control:
    loop_var: orderer 

# Create yaml file with orderer address values
- name: Create yaml file with orderer address values
  template:
    src: "orderer-endpoints.yaml"
    dest: "{{ values_file }}"
  vars:
    OrdererOrgEndpoint: "{{ ordererOrg.name }}MSPEndpoint"
    values_file: "{{ build_path }}/channel-artifacts/orderer-endpoints.yaml"

# Save the yaml file to a variable  
- name: Save yaml to variable
  ansible.builtin.include_vars:
    file: "{{ build_path }}/channel-artifacts/orderer-endpoints.yaml"
    name: ordererEndPoints

# Convert the yaml file to json 
- name: convert yaml to json
  copy:
    content: "{{ ordererEndPoints | to_nice_json }}"
    dest: "{{ build_path }}/channel-artifacts/ordererAddresses.json"