##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# Ensure channel-artifacts dir exists
- name: Ensure channel-artifacts dir exists
  file:
    path: "{{ build_path }}/channel-artifacts"
    state: directory

# Create a json file
- name: Creating new json file
  file:
    path: "{{ build_path }}/channel-artifacts/capabilities.json"
    state: touch

# Create a capabilities json
- name: Create capabilities json
  shell: |
    echo -n "{\"channel\":{\"mod_policy\":\"Admins\",\"value\":{\"capabilities\":{\"V2_0\":{}}}},\"orderer\":{\"mod_policy\":\"Admins\",\"value\":{\"capabilities\":{\"V2_0\":{}}}},\"application\":{\"mod_policy\":\"Admins\",\"value\":{\"capabilities\":{\"V2_0\":{}}},\"version\":\"0\"}}" > {{ build_path }}/channel-artifacts/capabilities.json

# Upgrade the orderer group for application channel
- name: Upgrade application channel orderer group
  include_tasks: nested_main_orderer_group.yaml
  vars:
    kubernetes: "{{ org.k8s }}"
    component_ns: "{{ org.name | lower }}-net"
    orderers: "{{ org.services.orderers }}"
  loop: "{{ organizations }}"
  loop_control:
    loop_var: org
  when: org.type == 'orderer' and org.name == channel.orderer.name

# Upgrade the channel group for application channel
- name: Upgrade application channel group capability
  include_tasks: nested_main_channel_group.yaml
  vars:
     channel_name: "{{ channel.channel_name | lower }}"

# Upgrade the application group for application channel
- name: Upgrade application app group capability
  include_tasks: nested_main_application_group.yaml
  vars:
     channel_name: "{{ channel.channel_name | lower }}"
