##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# This task creates the orderer cli and fetch and modify the config block
############################################################################################
# This task creates the capabilities upgrade script for channel group
- name: "Create script file to upgrade channel group"
  template:
    src: "channel_group_capability.tpl"
    dest: "{{ build_path }}/appchannel-channel-group-capabilities.sh"
  vars:    
    channel_name: "{{ channel.channel_name | lower }}"
    os: "{{ fabric.os }}"
    arch: "{{ fabric.arch }}"
    version: "{{ network.version }}"

# This task updates capability of channel group in application channel
- name: Update channel group capabilities of application channel
  include_tasks: channel-group/channel_group_capability.yaml  
  vars:
    peer: "{{ participant.peers | first }}"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    component_ns: "{{ org.name | lower }}-net"
    channel_name: "{{ channel.channel_name | lower }}"
  loop: "{{ channel.participants }}"
  loop_control:
    loop_var: participant
  when: participant.type == "creator"

# # This task calls sign_block.yaml to generate the cli for the new orderer for the signing of the block
- name: Call sign_block.yaml to sign from all other peers
  include_tasks: channel-group/sign_block.yaml
  vars:
    peer: "{{ participant.peers | first }}"    
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    component_ns: "{{ org.name | lower }}-net"
    channel_name: "{{ channel.channel_name | lower }}"
  loop: "{{ channel.participants }}"
  loop_control:
    loop_var: participant
  when: participant.type != "creator"

- name: Call sign_block_orderer.yaml to sign from all orderers
  include_tasks: channel-group/sign_block_orderer.yaml
  vars:
    orderer: "{{ org.services.orderers | first }}"
    component_ns: "{{ org.name | lower }}-net"
    channel_name: "{{ channel.channel_name | lower }}"
  loop: "{{ network.organizations }}"
  loop_control:
    loop_var: org
  when: org.type == 'orderer' and org.name == channel.orderer.name
 
# This task updates the block to the channel
- name: Call update_block.yaml to add the new orderer to the existing network
  include_tasks: channel-group/update_block.yaml
  vars:
    peer: "{{ participant.peers | first }}"    
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    component_ns: "{{ org.name | lower }}-net"
    channel_name: "{{ channel.channel_name | lower }}"
  loop: "{{ channel.participants }}"
  loop_control:
    loop_var: participant
  when: participant.type == "creator"
