##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# This task creates the orderer cli and fetch and modify the config block
############################################################################################
# Check or wait for the Orderer pod
# - name: "Wait for the new orderer pod"
#   include_role:
#     name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
#   vars:
#     component_type: "Pod"
#     namespace: "{{ component_ns }}"
#     kubernetes: "{{ kubernetes }}"
#     label_selectors:
#       - app = {{ channel.orderer.name | lower }}

# This task creates the capabilities upgrade script for orderer
- name: "Create script file to upgrade sys channel orderer group"
  template:
    src: "orderer_group_capability.tpl"
    dest: "{{ build_path }}/appchannel-orderer-group-capabilities.sh"
  vars:    
    channel_name: "{{ channel.channel_name | lower }}"
    os: "{{ fabric.os }}"
    arch: "{{ fabric.arch }}"
    version: "{{ network.version }}"

# This task updates capability of orderer group in system channel
- name: Update orderer group capabilities of system channel
  include_tasks: orderer-group/orderer_group_capability.yaml
  vars:    
    orderer: "{{ orderers | first }}"
    channel_name: "{{ channel.channel_name | lower }}"
  
  
# This task calls sign_orderer.yaml for the signing of the block by all orderers
- name: Call sign_orderer.yaml to sign from new update block
  include_tasks: orderer-group/sign_block_orderer.yaml
  vars:
    component_ns: "{{ org.name | lower }}-net"
    channel_name: "{{ channel.channel_name | lower }}"
    orderer: "{{ orderersNode }}"
  loop: "{{ orderers }}"
  loop_control:
    loop_var: orderersNode
  when: orderersNode.type == 'orderer' and orderersNode.name != creator_orderer
 
# This task updates the block by the existing orderer
- name: Call update_orderer.yaml to add the new orderer to the existing network
  include_tasks: orderer-group/update_block_orderer.yaml
  vars:    
    component_ns: "{{ org.name | lower }}-net"
    channel_name: "{{ channel.channel_name | lower }}"
    orderer: "{{ orderersNode }}"
  loop: "{{ orderers }}"
  loop_control:
    loop_var: orderersNode
  when: orderersNode.type == 'orderer' and orderersNode.name == creator_orderer