##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# Remove the build directory
- name: Remove build directory
  file:
    path: "{{ build_path }}"
    state: absent

- name: Create build directory if it does not exist
  file:
    path: "{{ build_path }}/channel-artifacts/"
    state: directory

# Ensure channel-artifacts dir exists
- name: Ensure channel-artifacts dir exists
  file:
    path: "{{ build_path }}/channel-artifacts"
    state: directory

# Check if acl file exists
- name: Check that acl json exists
  stat:
    path: "{{channel.acls}}"
  register: acls_file

# Copy file
- name: Copy file 
  ansible.builtin.copy:
    src: "{{channel.acls}}"
    dest: "{{ build_path }}/channel-artifacts/add_app_channel_acls.json"
  when: acls_file.stat.exists

# This task add default acls in app channels application group
- name: Add add default acls in app channels application group
  include_tasks: nested_main_add_app_channel_acls.yaml
  vars:
    channel_name: "{{ channel.channel_name | lower }}"
  when: acls_file.stat.exists