##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
# This task create script file to add acls to application channel
- name: "Create script file to add policies to application channel"
  template:
    src: "add_app_channel_acls.tpl"
    dest: "{{ build_path }}/add_app_channel_acls.sh"
  vars:
    channel_name: "{{ channel.channel_name | lower }}"
    os: "{{ fabric.os }}"
    arch: "{{ fabric.arch }}"
    version: "{{ network.version }}"

# This task updates the acls to application channel
- name: Update channel group capabilities of application channel
  include_tasks: add_app_channel_acls.yaml
  vars:
    peer: "{{ participant }}"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    component_ns: "{{ org.name | lower }}-net"
  loop: "{{ channel.participants }}"
  loop_control:
    loop_var: participant
  when: participant.type == "creator"

# check if original channel config and modified config is same
# if that is the case we dont have to proceed doing the channel update
- name: "Check if required channel config already exists"
  shell: |
    if diff {{ build_path }}/config_orig.json {{ build_path }}/config_modified.json >/dev/null; then echo true; else echo false; fi
  register: is_config_same

# This task signs the acls to application channel
- name: Call sign_block.yaml to sign from all other peers
  include_tasks: sign_block.yaml
  vars:
    peer: "{{ participant }}"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    component_ns: "{{ org.name | lower }}-net"
  loop: "{{ channel.participants }}"
  loop_control:
    loop_var: participant
  when: participant.type != "creator" and is_config_same.stdout == "false"

# This task commits the acls to application channel
- name: Call update_block.yaml to add the new orderer to the existing network
  include_tasks: update_block.yaml
  vars:
    peer: "{{ participant }}"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    component_ns: "{{ org.name | lower }}-net"
  loop: "{{ channel.participants }}"
  loop_control:
    loop_var: participant
  when: participant.type == "creator" and is_config_same.stdout == "false"
