##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role upgrades the orderer binaries on orderer node
#############################################################################################

# Remove the build directory
- name: Remove build directory
  file:
    path: "./build"
    state: absent

- name: Create build directory if it does not exist
  file:
    path: "./build/channel-artifacts/"
    state: directory

- name: "Get genesis block from Vault"
  shell: |
    vault kv get -field={{ network.env.type }}GenesisBlock {{ vault.secret_path | default('secretsv2') }}/crypto/ordererOrganizations/{{ item.name }}-net        
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  register: vault_orderer_genesis_block  

- set_fact:
    genesis_block: "{{ vault_orderer_genesis_block.stdout }}"

- name: "Save genesis block"
  local_action: copy content="{{ genesis_block }}" dest=./build/channel-artifacts/genesis.block.base64

# This role creates value file for each orderer
- name: Create value file for each orderer in org
  include_tasks: create_orderer_value.yaml
  loop: "{{ component_services.orderers }}"
  loop_control:
    loop_var: orderer
  when: 
    - component_services.orderers is defined and component_services.consensus is defined    
  
