##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# Remove the build directory
- name: Remove build directory
  file:
    path: "./build"
    state: absent

- name: Create build directory if it does not exist
  file:
    path: "./build/channel-artifacts/"
    state: directory

# Ensure channel-artifacts dir exists
- name: Ensure channel-artifacts dir exists
  file:
    path: "{{ build_path }}/channel-artifacts"
    state: directory

# # Enable enable endorsement in application channels
- name: Enable endorsement in application channels
  include_tasks: nested_main_app_channel_endorsement.yaml
  vars:
    consortium: "{{ channel.consortium }}"
    orderer_name: "{{ channel.orderer.name }}"
    participant_name: "{{ participant.name }}"
  loop: "{{ channel.participants }}"
  loop_control:
    loop_var: participant
