##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
# Create yaml file with orderer address values
- name: Create yaml file with orderer address values
  template:
    src: "enable-endorsement-consortium.yaml"
    dest: "{{ values_file }}"
  vars:
    OrgName: "{{ participant.name }}"
    values_file: "{{ build_path }}/channel-artifacts/enable-endorsement-consortium.yaml"

# Save the yaml file to a variable
- name: Save yaml to variable
  ansible.builtin.include_vars:
    file: "{{ build_path }}/channel-artifacts/enable-endorsement-consortium.yaml"
    name: ordererEndPoints

# Convert the yaml file to json
- name: convert yaml to json
  copy:
    content: "{{ ordererEndPoints | to_nice_json }}"
    dest: "{{ build_path }}/channel-artifacts/enable_lifecycle_{{ participant.name }}MSP.json"

# This task create script file to add enable lifecycle to syschannel consortium orgs
- name: "Add enable lifecycle to syschannel consortium orgs"
  template:
    src: "add_app_channel_endorsement.tpl"
    dest: "{{ build_path }}/add_app_channel_endorsement.sh"
  vars:
    channel_name: "{{ channel.channel_name | lower }}"
    org_name: "{{ participant.name }}MSP"
    os: "{{ fabric.os }}"
    arch: "{{ fabric.arch }}"
    version: "{{ network.version }}"

# This task updates capability of channel group in application channel
- name: Update channel group capabilities of application channel
  include_tasks: update_app_channel_endorsement.yaml
  vars:
    peer: "{{ participant }}"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    component_ns: "{{ org.name | lower }}-net"
    channel_name: "{{ channel.channel_name | lower }}"
    org_name: "{{ participant.name }}MSP"
