##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# Remove the build directory
- name: Remove build directory
  file:
    path: "{{ build_path }}"
    state: absent

- name: Create build directory if it does not exist
  file:
    path: "{{ build_path }}/channel-artifacts/"
    state: directory

# Ensure channel-artifacts dir exists
- name: Ensure channel-artifacts dir exists
  file:
    path: "{{ build_path }}/channel-artifacts"
    state: directory

# Create app-channel policies json
- name: Create app-channel policies json
  copy:
    content: "{{ '{\"appPolicies\":{\"Endorsement\":{\"mod_policy\":\"Admins\",\"policy\":{\"type\":3,\"value\":{\"rule\":\"MAJORITY\",\"sub_policy\":\"Endorsement\"}},\"version\":\"0\"},\"LifecycleEndorsement\":{\"mod_policy\":\"Admins\",\"policy\":{\"type\":3,\"value\":{\"rule\":\"MAJORITY\",\"sub_policy\":\"Endorsement\"}},\"version\":\"0\"}}}' | from_json | to_nice_json}}"
    dest: "{{ build_path }}/channel-artifacts/add_app_channel_policies.json"

# This task add endorsement and lifecycle in app channels application group
- name: Add endorsement and lifecycle in app channels application group
  include_tasks: nested_main_add_app_channel_policies.yaml
  vars:
    channel_name: "{{ channel.channel_name | lower }}"
