##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
    
# This task create script file to add policies to application channel
- name: "Create script file to add policies to application channel"
  template:
    src: "add_app_channel_policies.tpl"
    dest: "{{ build_path }}/add_app_channel_policies.sh"
  vars:    
    channel_name: "{{ channel.channel_name | lower }}"
    os: "{{ fabric.os }}"
    arch: "{{ fabric.arch }}"
    version: "{{ network.version }}"

# This task updates capability of channel group in application channel
- name: Update channel group capabilities of application channel
  include_tasks: add_app_channel_policies.yaml
  vars:
    peer: "{{ participant }}"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    component_ns: "{{ org.name | lower }}-net"    
  loop: "{{ channel.participants }}"
  loop_control:
    loop_var: participant
  when: participant.type == "creator"

# This task calls sign_block.yaml to generate the cli for the new orderer for the signing of the block
- name: Call sign_block.yaml to sign from all other peers
  include_tasks: sign_block.yaml
  vars:
    peer: "{{ participant }}"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    component_ns: "{{ org.name | lower }}-net"    
  loop: "{{ channel.participants }}"
  loop_control:
    loop_var: participant
  when: participant.type != "creator"
 
# This task updates the block to the channel
- name: Call update_block.yaml to add the new orderer to the existing network
  include_tasks: update_block.yaml
  vars:
    peer: "{{ participant }}"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
    component_ns: "{{ org.name | lower }}-net"    
  loop: "{{ channel.participants }}"
  loop_control:
    loop_var: participant
  when: participant.type == "creator"
